### ISSUE TITLE
Teleporting to a specific coordinate in a specific world

### ISSUE THREAD

**Issue by spetznack** [Multiverse/Multiverse-Core#1006]
Hey! 

Request: Can you add the feature to use the tp command for tp'ing a player to a specific coordinate in a specific world? :) 

Reason: I am using command blocks alot for everything.. Instead of using the portal plugin I am using command blocks and the /mv tp [PLAYER] {WORLD} command to teleport people between the worlds right now and it is working perfectly. The last weeks I have been wanting to teleport people to specific coordinates in specific worlds, and I'd love to use the same command for that. 

Example: 
`/mv tp [PLAYER] {WORLD} {X Y Z]`
If you don't specify coordinates, it would teleport to the world's mv spawn like it does now :) 

Example usage with command block: 
`/mv tp @p[r=5] Survival 100 50 100`

Thank you for reading!

**Comment by ScarletSwitch** [comment]
You can just just warps, they work between servers

**Comment by WosHHua** [comment]
do you know how to make it so that it works with command blocks?
I'm trying to do /mv tp @s new_world but it says it cannot find player @s. what im trying to do is to make a command block and then people press it to travel to the worlds, can u help plz

**Comment by WosHHua** [comment]
HELP @main--

**Comment by spetznack** [comment]
The @s selector will select the executor of the command. So putting that command will try to teleport the command block which is not a valid player/entity. Describe what you are trying to do with this command and maybe I can help you.

**Comment by spetznack** [comment]
Wow to myself, sorry I didnt even read the last part of your post. You need to use @p to select the closest player or @a if you want to select all players within the radius you set inside the selector argument. 

You also have to replace the "new_world" with the exact position, see the link in main--'s amswer above to find out how that works. 

If you need further help the try to find a chatroom or discord for spigot/bukkit mod support :)

**Comment by ControlAlternateDelete** [comment]
> Wow to myself, sorry I didnt even read the last part of your post. You need to use @p to select the closest player or @A if you want to select all players within the radius you set inside the selector argument.
> 
> You also have to replace the "new_world" with the exact position, see the link in main--'s amswer above to find out how that works.
> 
> EDIT:
> Correction, you dont need to use exact If you just want to teleport the player to the spawn of another world.
> 
> This should do the trick:
> /mvtp @p[r=4] new_world
> 
> A side note to this is that this command executed by a command block will select the first player that is closest to the commandblock. You should to look into how the selector parameters work if you want to tweak this ;)
> 
> If you need further help the try to find a chatroom or discord for spigot/bukkit mod support :)

This doesn't seem to work for me

**Comment by nicegamer7** [comment]
This was possible in versions of Minecraft earlier than 1.13. Mojang made a change which meant it was no done automatically, and instead had to be handled by the plugins themselves. There is a test build of MV on our Discord server where we have this working. See #1961 for more details.
