### ISSUE TITLE
Multiverse World Acceleration Bug with MCPC 1.4.5

### ISSUE THREAD

**Issue by D4rKCooL** [Multiverse/Multiverse-Core#1008]
Hi, i just try the last dev build, and i have a really strange issue in some of my worlds. 
(Not in the primery one, but in my second one.) 
The fact is that everything except players are fast as hell, mobs, fire-spread, lava-flow, water-flow, leafs-decay, time, items de-spawn ... Well you get the point... It's funny for a moment, but the world is getting really hardcore.
I tried to generate another world, but the issue is still there.
I also tryed to use an upper version, but it became worse, and everything was a lot faster than before.

**Comment by TWSSYesterday** [comment]
MCPC has been discontinued, if you're still using this version; you can respond and we'll figure something out.
