### ISSUE TITLE
2.5-b641 & 2.4-AB not working on CB- 1.4.5-R1.0

### ISSUE THREAD

**Issue by connerreinhardt** [Multiverse/Multiverse-Core#1014]
[SEVERE] Error occurred while enabling Multiverse-Core v2.5-b641 (Is it up to date?) java.lang.IllegalArgumentException: No enum const class org.bukkit.Difficulty.MEDIUM at java.lang.Enum.valueOf(Enum.java:196) at org.bukkit.Difficulty.valueOf(Difficulty.java:10) at com.onarandombox.MultiverseCore.MultiverseCore.migrateWorldConfig(MultiverseCore.java:736) at com.onarandombox.MultiverseCore.MultiverseCore.loadConfigs(MultiverseCore.java:488) at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:299) at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217) at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457) at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381) at org.bukkit.craftbukkit.v1_4_5.CraftServer.loadPlugin(CraftServer.java:272) at org.bukkit.craftbukkit.v1_4_5.CraftServer.enablePlugins(CraftServer.java:254) at net.minecraft.server.v1_4_5.MinecraftServer.j(MinecraftServer.java:320) at net.minecraft.server.v1_4_5.MinecraftServer.e(MinecraftServer.java:299) at net.minecraft.server.v1_4_5.MinecraftServer.a(MinecraftServer.java:258) at net.minecraft.server.v1_4_5.DedicatedServer.init(DedicatedServer.java:147) at net.minecraft.server.v1_4_5.MinecraftServer.run(MinecraftServer.java:398) at net.minecraft.server.v1_4_5.ThreadServerApplication.run(SourceFile:856)

**Comment by TWSSYesterday** [comment]
This version is really old and I doubt you're still using it; thus ending this issue. If you are in fact still using this version, feel free to reply and we'll do our best to get back to you :)
