### ISSUE TITLE
Blocking mob spawns does not work

### ISSUE THREAD

**Issue by niallkb** [Multiverse/Multiverse-Core#1016]
i have set animals and monsters to false :
      animals:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []

yet animals still spawn.

**Comment by TWSSYesterday** [comment]
This should no longer be the case.
