### ISSUE TITLE
Portal Permissions not working...

### ISSUE THREAD

**Issue by TCPCMelville** [Multiverse/Multiverse-Core#1022]
Could anybody please take a look at my permissions file for groupmanager... The multiverse portal access and world access doesnt seem to work...

http://pastebin.com/c4YDTu00

**Comment by TWSSYesterday** [comment]
https://github.com/Multiverse/Multiverse-Portals/wiki/Big-list-o-permissions is the permission page, issue will be closed now as they are known working and this is an old ticket.
