### ISSUE TITLE
mv.bypass.gamemode problems

### ISSUE THREAD

**Issue by aikar** [Multiverse/Multiverse-Core#1030]
1) this.ignoreperm = new Permission("mv.bypass.gamemode." + this.getName(),
                "Allows players wit this permission to ignore gamemode changes.", PermissionDefault.FALSE);

Why isn't this default Op?

2) Can we have a way to disable all of this logic.

I don't use MV for managing flght/gamemode, and it's a bit annoying as Op in dev testing to keep getting plummeted to the ground, see 3:

3) Any idea why MV is still ENABLING before my plugin which has loadbefore: ["Multiverse-Core"]?
My plugin doesn't get time to add the permission nodes on a reload, and sends me to the ground.

Adding the bypass nodes is at least working for join, but MV runs before our code does on /reload and drops me.

**Comment by asmooke** [comment]
> Fixed this issue in this build: http://ci.onarandombox.com/job/Multiverse-Core/654/

this version does not work Minecraft 1.9 Bukkit

but in this version is not working (http://ci.onarandombox.com/job/Multiverse-Core/  ) gamemode/

Is there a solution? 

Thank you
