### ISSUE TITLE
entryfee error 2.4

### ISSUE THREAD

**Issue by aroepy** [Multiverse/Multiverse-Core#1039]
hey,

if i use an entry fee for letś say: hungergames,
then people won be charged... they are getting the prixe as bonus!! ( ME NO LIKING!)

i use 2.4multiverse doesn give an error about it.

when is it fixed?

my bukkit:
1.4.6
MV 2.4

thnx

**Comment by TWSSYesterday** [comment]
Definitely fixed by now.
