### ISSUE TITLE
Respawn Problem

### ISSUE THREAD

**Issue by twan2797** [Multiverse/Multiverse-Core#1047]
Hi guys,
I am playing on different worlds on my server (A-B-C-D), but whenever i die i respawn in world D
but i want to get respawned in the world i die,
I have changed the respawn world etc.. but i still respawn in world D...
also if i delete world D it gives internal server error,

I have tried everything, but i can't get it fixed... please help

**Comment by TWSSYesterday** [comment]
Cannot replicated, locking due to inability to replicate and lack of updates.
