### ISSUE TITLE
The End world spawn is not safe

### ISSUE THREAD

**Issue by FuRiouSOne** [Multiverse/Multiverse-Core#1068]
I have The End disabled in bukkit. I use multiverse to generate The End world and players use a special dungeon to get to the portal for The End world entrance.

Recently in one of the bukkit builds has broke teleporting to the multiverse generated The End world. Any time you try to use the portal it says spawn is not safe. I use the bypass and force spawn and it will teleport me to 0, 0, 0 location and fall to the void regardless what setspawn is in the config. I have even tried turning off adjustspawn but still happens.

Using bukkit 1.4.7 R1
Multivers-core 654
Multiverse-signportals 643

**Comment by TWSSYesterday** [comment]
This is no longer the case.
