### ISSUE TITLE
Suggestion/Request: First World Join Inventories

### ISSUE THREAD

**Issue by Xehara** [Multiverse/Multiverse-Core#1080]
My server works off of the spawn being a hub to our Easy world and our Hard world where the inventories are different. Any current plugin offering items to new members is completely voided when they enter either map. 

I'd like to be able to designate starter items for when players first enter the Easy map, and one for the Hard map. It's not just as easy as giving inventory to when they join a new map though as the Hard map is connected to the Nether and The End, and they shouldn't get a new starter kit upon entering either of those.

Is it possible to add in this feature with an enable/disable option? Thank you for your consideration.

**Comment by TWSSYesterday** [comment]
Possible using multiple other plugins, since it wouldn't be essential, not a lot of people would use it, there wouldn't be a point adding it.
