### ISSUE TITLE
/sethome and /home Issue

### ISSUE THREAD

**Issue by YankeBilly** [Multiverse/Multiverse-Core#1095]
So when a player uses /sethome it says "Home <worldname1> set."

But when the player moves somewhere and types /home it says "Teleported to you home <worldname1>" but actually teleports you to the same coordinates in <worldname2>..

This is frustrating a lot of good players on my server.

I use AdminCMD for these commands. But I know for a fact that it is Multiverse that is causing the issue. 

Would it possibly be because the world I'm trying to set home in is not the original spawn world?

**Comment by Embolex1** [comment]
It HAS something to so with Multiverse .... 

other example:
I tried to use /home.
Before i used multiverse it worked for me and all others on server.
But after
installing multiverse -> importing the worlds -> deleted the New worlds it HAS created (mistake in config) --> goin online
.... cool ... the old worlds were loaded ... 
i tried to use /home ... it told me: Wrong world. ... 
after this i tried /home [Name_of_World] [Name_of_Home]
but there was a unexpected text in chat:

 "Homes: home, hier, da, Lager, Spawn, bed"

it only shows me the names of homes but didnt teleport me there ....

And u want to say me, that the /home command isnt affected by multiverse??? 


go lost !

**Comment by dumptruckman** [comment]
The only possibility that Multiverse has something to do with this is that you're using Multiverse-Inventories. Even then, there's probably nothing we're doing wrong. It's likely a conflict between the way Multiverse-Inventories works and AdminCMD works. You can disable home sharing in MV-Inv. I'll leave that as an exercise for the reader.
