### ISSUE TITLE
Slow world load.

### ISSUE THREAD

**Issue by yaitsbilly** [Multiverse/Multiverse-Core#1097]
I have a world set up for Activities and the a HUB with in that world, If I use a portal that I've made to go to that portal it loads up just fine. But if I use one of the portals in the HUB to go to one of the activities in that world it takes a lot lot longer to load up that location once I spawn there.

Any reason why?

**Comment by TWSSYesterday** [comment]
Cannot replicate using latest builds, quite a lot has changed in 3 years.
