### ISSUE TITLE
World becomes flatland on new chunks generation

### ISSUE THREAD

**Issue by Malharhak** [Multiverse/Multiverse-Core#1120]
Hello,

I have a bug in Multiverse : All my worlds now genereate flatlands chunks, but the map was initially not (so I have a map with the first chunks being normal, and the next ones being flatland).

Is there any way to change the current generator used by the maps or somethings ? This is totally strange and it kinda screwed my maps..

**Comment by TWSSYesterday** [comment]
Cannot replicate, closed due to that and inactivity. In the worlds.yml you can change the generator although it's not advised.
