### ISSUE TITLE
Is there a permission to allow people to /mv tp to only one world?

### ISSUE THREAD

**Issue by minicl55** [Multiverse/Multiverse-Core#1138]
Is there a command (For example, multiverse.teleport.world_nether) that only allows teleport to a certian world?

**Comment by MrNicoYT** [comment]
multiverse.access.*     <---- where should i add this command so every1 can tp

**Comment by benwoo1110** [comment]
In general, a permissions manager such as LuckPerms (https://luckperms.net/) is used to apply permissions to specific users or groups of users. LuckPerms can also apply permissions differently depending on which world you're on.
