### ISSUE TITLE
[Request] Multiverse for normal Minecraft Singleplayer Survival

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Multiverse/Multiverse-Core#1142]
You're surely asking "Why the hell would you want or even need Multiverse for singleplayer?".

Well, there's some of us who'd just like to have it. I'm sure there are mods out there that try to simulate it, namenly Mystcraft. However, when I talk Multiverse, I mean it as in separate saved worlds.

Why this way? It's easier on the system for one. Instead of loading dimensions over dimensions over dimensions, with multiverse I'd just enter the portal to a newly created world in a new save, and the last save would cease to run for the time being.

The point is, a lot of people like to play by exploring. The more you explore, the more and more and more bloated the save becomes, the loading times become un-bear-able on low-mid-range computers. This way, when you notice your previous world became unbearably long to load, you enter a portal into a newly created world.

Why multiverse? WHy not just create a new save and play it? Because I want to take the stuff I had looted and mined in the new world back to my good ol' world where the huge main base is.

**Comment by devomaa** [comment]
this is still open, please make the desicion

**Comment by dumptruckman** [comment]
There's no real decision to make. It would be really cool to see this. It's also very very unlikely to ever happen.

**Comment by Ahsumcrafter** [comment]
Actually, there is a way to have multiple worlds on Single player. It's very easy and simple.

Now keep in mind that the new world(s) will be synchronized with the time and weather settings in the game (along with your inventory). Pls pay attention carefully:
 Requirements:
NBT Explorer
Minecraft (Obviously, at least 1.16 or higher, with cheats enabled on your first world)

1. Create two worlds (or if you have two worlds already with some stuff you did, it will work great too) and enter each one, copying the coordinates to where you want to teleport (Extremely important!)
2.  Open NBT explorer and select the 2nd world (in the saves folder) of your choice (which will be the one you will teleport to).
3.  Go to level.dat > WorldGenSettings > Dimensions> and copy minecraft:overworld
4. Now back out of the 2nd world folder and enter the 1st world folder. Go to the same path as step 3.
5. Paste the overworld data folder and rename it to anything you would like.
6. Save and minimize NBT Explorer. Open Minecraft again and enter the 1st world. A warning message should appear saying that you have enabled experimental settings. Ignore the warning and click Proceed.
7. Now that you are in your world, you should still be in the main world. Open chat and type in '/execute in minecraft:<WorldName> run tp @s <x> <y> <z>' and you should be directed to the 2nd world
8. When you enter the 2nd world, don't panic if you don't see the stuff you did. We still have work to do! Now exit the world and open the file explorer on your PC. Go to your world 2 save folder and select all the items within the folder.
9. Copy them, open NBT Explorer again and go to saves > World1 > dimensions > Minecraft > World2 > paste here!
10. Close NBT and file explorer and enter your world again. tp to the 2nd world and your stuff should be there! Enjoy! :)
