### ISSUE TITLE
Multiverse loses player spawn points

### ISSUE THREAD

**Issue by kuemmi** [Multiverse/Multiverse-Core#1147]
I'm using the latest dev builds (2.5) of multiverse core, portals and inventories with the latest CraftBukkit beta for Minecraft 1.5.1. The server has a survival world with nether and end, and a creative world. 

I set my spawn by sleeping in a bed in the survival world, went to the creative world and came back to the survival world. When I die, I now respawn at the spawn point of the survival world and not next to my bed. 
It all works fine if I die in the survival overworld, nether or end before going to the creative world.

bedRespawn is set to true, and respawnWorld is set to the survival world.

**Comment by redbrain1014** [comment]
I am also having this issue in 1.15.2 spigot, both with /spawnpoint and bed respawn. Help would be appreciated.

**Comment by benwoo1110** [comment]
This is too old to judge if its a bug in the current version. If you all still face issue with the latest version of mv and papermc, do open a new issue. thanks!
