### ISSUE TITLE
Tekkit / IslandWorld / Multiverse

### ISSUE THREAD

**Issue by jake1706** [Multiverse/Multiverse-Core#1155]
So, im having a bit of a proglem .. i was able to create a world with cleanroomgenerator and everything ... but when i try to use IslandWorld commands it says Regen in progress, try again later.
The problem is that it doesnt stop regen and i cant do mvregen!
"The command mvregen has been halted due to the fact that it could break something!
If you still wish to execute mvregen
please type: /mvconfirm"
and when i write /mvconfirm:
World could NOT be regenerated

**Comment by TWSSYesterday** [comment]
IslandWorld is a bukkit plugin, it's known working now. Closing ticket due to age and invalidity now.
