### ISSUE TITLE
Nether and End portals exit in wrong locations.

### ISSUE THREAD

**Issue by KillaVolt** [Multiverse/Multiverse-Core#1163]
While installing multiverse/netherportals/inventory there is an issue with warping through portals.
I have my regular survival worlds (overworld, nether and the end) which are the main play worlds.

When going through nether portals they exit in the nether in a completely different location than the existing exist portal, and when returning to the overworld the same thing happens. Moreover they usually end up putting you inside blocks causing you to suffocate and die.

This same thing happens when returning from the end, instead of going back to the spawn point of the world (or the essentials spawn point, which should be the worlds spawn) you end up near 0,0 inside the ground, dying.

**Comment by TWSSYesterday** [comment]
If this is still an issue, post another ticket, I've seen similar things occurring but not matching the description.
