### ISSUE TITLE
PVP option not working even when set.

### ISSUE THREAD

**Issue by Mettenburg** [Multiverse/Multiverse-Core#1168]
Okay I want to set only one world to have PVP (without arenas) and I have set everything possible to PVP: true and I still can not get PVP to enable. Hoping it's not a permissions thing. Can someone please help!!

Here is my worlds.yml file: http://pastebin.com/Mhwu5CbR
Here is my Permissions flie: http://pastebin.com/cEZZcrmG

These are the plugins I am using: http://pastebin.com/YSWHx45w

**Comment by YvesChasse** [comment]
Not sure if this has been answered already but it's a simple fix, It's starts in the MultiVerse Core Plugin. Just locate you Multiverse Core plugin and go to worlds.yml, Locate all your Pvp : 'false' Change them all to true. Simple fix :).

**Comment by Quantum64** [comment]
That might have fixed it if this plugin had decided to depend on multiverse.

**Comment by Quantum64** [comment]
How do you even find a closed issue from 2 years ago...

**Comment by RaflyR** [comment]
Mettenburg : does his pvp fishing rod work ?
