### ISSUE TITLE
Nether Portals Stopped Working On SOME Worlds

### ISSUE THREAD

**Issue by Boskosauce** [Multiverse/Multiverse-Core#1173]
Not sure what happened, as I didn't change any settings whatsoever. I have multiple worlds on my server. 'world' being the default survival world. PvPWorld being the pvp-factions world. Those two are the main two people use, anyway.

A few days ago, the portals stopped working on the PvPWorld. They work fine on the survival world though. And as I said, they were working just fine up until the past few days.

I've done some testing though. I've changed the default world in server.properties to the pvpworld and the nether portals worked on the pvp world again, but did not work on the survival world.

Does anyone have any ideas?

**Comment by TWSSYesterday** [comment]
This is definitely no longer an issue, if you're still having these problems, please make a new ticket.
