### ISSUE TITLE
Config File Resetting?

### ISSUE THREAD

**Issue by martafolf** [Multiverse/Multiverse-Core#1177]
Hello,

I have a small issue, which is that whenever I change a specific option in the config file, in this case its the PvP option, and then restart the server, it just resets back to what it was before, other options such as difficulty work seamlessly.

My server.proprieties has PvP= True, but some world on multiverse dont, and I wanted them to have it on true, but it just resets back to what it was before, whenever I restart or reload, or even /mv reload...

My Craftbukkit Version is the Latest Dev, for 1.5.2 compatibility, and I am running one of the latest Multiverse-Core Dev versions.

Regards,
Halothe23

**Comment by ACPLibrary** [comment]
We're experiencing the same issue currently. When setting config in worlds.yml to pvp = true for certain worlds, the values revert to pvp = false after a server restart.
Running:
MultiVerse Core 2.5.0 in Spigot 1.12.2
Plugins:
bStats
CleanChat 1.1
CleanroomGenerator
Essentials 2.15.0.1
GriefPrevention
HubKick
KittyCannon
Multiverse-Core 2.5.0
Multiverse-Portals
PermissionsEx
PerWorldInventory
PluginMetrics
Spawntp
SurvivalGames
WorldEdit
