### ISSUE TITLE
Cannot Delete World

### ISSUE THREAD

**Issue by Ridog** [Multiverse/Multiverse-Core#1198]
I accidentally created a new survival world with multiverse and now it seems there is no way to get rid of it.

I have tried unloading it with mv unload worldname and got the error.

"Error trying to unload world 'worldname'"

Then I tried mv remove worldname and got:

Hmm Multiverse does not know about this world but it's loaded in memory.
To unload it using multiverse, use:
/mv import worldname NORMAL
Error trying to unload world from config!

Trying mv import worldname NORMAL resulted in:

Multiverse already knows about 'worldname'!

Then I tried mv delete worldname and then mvconfirm and got:

World 'worldname' could not be unloaded.  Is it a default world?
World could NOT be deleted.

So I'm at a loss, what should I try next?

**Comment by DarkFlareMC707** [comment]
How do you turn off default?

**Comment by Ridog** [comment]
This was a long time ago but iirc the default world is listed in server.proporties and you need to change it to another world so that multiverse can delete it.

**Comment by LittleKitacho** [comment]
What if you dont have access to server.properties or the world file?

**Comment by Cyber-Sandy** [comment]
i also have the same problem. Multiverse keeps regenerating the map. it is not set to default. i deleted the world files, removed the data block from world.yml and restarting the server. no progress.

**Comment by benwoo1110** [comment]
Are you deleting the world folder originally generated by the server?
