### ISSUE TITLE
Multiverse and Herochat

### ISSUE THREAD

**Issue by anmghstnet** [Multiverse/Multiverse-Core#1238]
When using Herochat and Multiverse, world alias' aren't being password to Herochat. See the following example:
2013-06-24 02:20:34 [INFO] [G] world Enderman (Admin) - Gametista: test
2013-06-24 02:20:37 [INFO] [G] world Ocelot (M-III) - Risingdeath777: test

In the above example, we have the nick Spawn for "world"

Herochat says that it is Multiverse that isn't passing the nick of the world to them, is this something that can be looked at?

**Comment by Sam1370** [comment]
is this what you're looking for?
https://www.spigotmc.org/resources/mv-chatalias.44531/
