### ISSUE TITLE
Players position not save in other worlds.

### ISSUE THREAD

**Issue by Kayda** [Multiverse/Multiverse-Core#1323]
I have a server where I run a creative, pvp and survival worlds, There are no problems with the pvp worlds the problems I have lie within the creative and survival. Players positions are not save when they log out in those worlds, or I can't find a way around it. 

When a play logs in they are taken to a world I have set up as a lobby, so when they log out of the survival/creative world when they go back to them they are back at the spawns of said world. Is there a way I can make it so they go back to where they logged out if they go via the portal?

**Comment by manuelgu** [comment]
Sorry for bumping this but is there currently a way to achieve that? Can I get the logout location somehow within my own code? (I'll setup custom commands for teleporting to specific worlds)

**Comment by crjase** [comment]
a lot of servers already have this, so I know its possible. Anyone know how to do it?
