### ISSUE TITLE
Weird issues with worlds

### ISSUE THREAD

**Issue by thincks** [Multiverse/Multiverse-Core#1341]
So I am working on setting up a server and I am using multiverse, I made a new world and I needed to restart the server so I did. When I get back on the world has disappeared off /mv list and I have to import it again, I have no idea what is going on and its a pain to import it every time.

Note:This only happens to worlds that I have made, the default ones, normal,nether,end are still there.

**Comment by TWSSYesterday** [comment]
No longer the case, ticket closed due to lack of updates on ticket and bug being fixed/not being a bug.
