### ISSUE TITLE
HeroChat and multiverse alias

### ISSUE THREAD

**Issue by Porkki** [Multiverse/Multiverse-Core#1405]
So I am using HeroChat and I just can't get Multiverse aliases to work. With essentials chat aliases worked just fine, but because of Factions plugin i needed to switch HeroChat.

I have in multiverse config line:
prefixchat: 'true'

I really need aliases because mine world names are named by like A,B,C etc... and in chat with those world names it does not look so good or informative.
I already tried to google it and it seems like i am not only one who has this problem.
We really do need support with herochat and multiverse aliases. HeroChat devolpers says that we need to contact multiverse devolpers.

**Comment by Sam1370** [comment]
https://www.spigotmc.org/resources/mv-chatalias.44531/
