### ISSUE TITLE
mvregen not working

### ISSUE THREAD

**Issue by Bobcat00** [Multiverse/Multiverse-Core#1406]
MV Core build 688 has broken the /mvregen command.  MV is unable to delete the region folder.  Full error messages: http://pastebin.com/QqudzqQ4

Running:
Multiverse-Core 2.5-b688
Multiverse-Inventories 2.5-b374
Multiverse-NetherPortals 2.5-b682
Multiverse-Portals 2.5-b710

mvregen was apparently broken during an attempt to fix #1392. With build 686 an exception occured, but at least the world was regenerated.  Now the world can't be regenerated at all.

**Comment by TWSSYesterday** [comment]
Hey there @Bobcat00, is this still occurring on the latest builds? Sorry for the update nearly 3 years down the line however it's quite a big issue, I'm unable to reproduce this myself but if you could provide logs if it is that'd be great. For now, closed.
