### ISSUE TITLE
Respawnworld don't work

### ISSUE THREAD

**Issue by LordManzana** [Multiverse/Multiverse-Core#1409]
When I die on one world, all worlds teleport me to defualt world named "Hub".

Plugins:
http://gyazo.com/c286488584d1421b08bf90ccc53b8b00.png

Worlds file:
http://pastebin.com/P7XUmsCr

If you need some of my plugin config or you know some of my plugin make this error, please, tell me.

Thanks.

**Comment by TWSSYesterday** [comment]
Respawnworld setting does this now, sorry for old bump.
