### ISSUE TITLE
Per World GameRules not working

### ISSUE THREAD

**Issue by ghost** [Multiverse/Multiverse-Core#1412]
I'm using this link to get different commands for changing a gamerule for one world.
https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#gamerule

I have a Minigame server and I also have a survival world, I want certain gamerules to be changed in the survival world so it acts like normal singleplayer survival.

eg, I have FireTick turned off and I have used the command
/mv gamerule doFireTick true Survival, and still when setting fire to a tree the fire does not spread even though MultiVerse has told me that FireTick is True,

Plugins that might conflict are worldedit, worldguard & essentials
I've gone through my configd and I can't see and conflicting settings.

Is there anything else I can try? I really do need this resloved.
Thanks.

**Comment by TWSSYesterday** [comment]
No longer the case, ticket closed due to time frame.
