### ISSUE TITLE
Bug perms multiverse.teleport.self.NAME

### ISSUE THREAD

**Issue by Max633** [Multiverse/Multiverse-Core#1453]
Hello, 

When I give the permission multiverse.teleport.self.map (map = name of world) He can not teleport to the world.

A solution?

Thanks

**Comment by chillerkraft** [comment]
can i continue this ticket please

**Comment by chillerkraft** [comment]
i have the same issue, the only permissions i can get to work is mutiverse.teleport.self.w
i noticed also, when it says the perms that i should have, it shows that one twice in the list, not sure if that has anything to do with this bug

**Comment by chillerkraft** [comment]
i've given the group the perm for the world which is called Hub, and yes i tried making sure i did the correct case for the perm but still, i can not gain access. i have enforce access false but i still did try to give myself access via perm to that world in the group but it still would say i dont have the perm

**Comment by dkolb** [comment]
I'm having the same problem.

Here's a gist from a local test server including

- Listing of my user permissions on the server
- List of plugins installed (PermissionsEx and Multiverse-Core
- List of worlds
- PEX debug output (toggled on for my user) from where I issued the teleport command.

https://gist.github.com/dkolb/68bdeb2ba2ec441d1fe5

**Comment by dkolb** [comment]
(Oh snap, I just revived an ANCIENT ticket.  Let me know if you want a new one or this info moved to another ticket.  Sorry about that.)

**Comment by TWSSYesterday** [comment]
Update your Multiverse...
