### ISSUE TITLE
MCPC+ (Cauldron) No Subfolder Support

### ISSUE THREAD

**Issue by Yanniclord** [Multiverse/Multiverse-Core#1459]
So when i installed Multiverse, teleporting to "The End" from a stronhold portal, did send players at +100 69 0 in the overworld, and as Forge saves their worlds in subfolders of the world folder like world/DIM1 and not world, world_the_end and so, so it doesnt read the end as a world, as its not called world_the_end but DIM1, please add support for changing sub names of worlds to.

**Comment by TWSSYesterday** [comment]
MCPC+ has been discontinued, if you still would like support for this, reply and I will re open this ticket.
