### ISSUE TITLE
How to set a world to creative?

### ISSUE THREAD

**Issue by CourtneyOnFire** [Multiverse/Multiverse-Core#146]
I've tried 
/mvm set mode creative creative 
/mvm set creative creative
/mvm set mode creative 1 creative

World name is creative

The wiki says just type /mvm set creative but then when I type that and it says to /mvm set PROPERTY VALUE WORLD
What do I put for the property and value to make the world Creative?

**Comment by soshimee** [comment]
Weird, it says "That world does not exist" when I use /mvm set mode creative but I never typed world name

**Comment by kalleswe** [comment]
Well still does not work in 4.6, I won't be in creative when I've set a world as creative when I mvtp to it.
So this bug needs fixing.

**Comment by ElishQa** [comment]
has it been fixed? XD

**Comment by 6jsdpmkgzp-dev** [comment]
Try this;

/mv modify (worldname) set gamemode creative
