### ISSUE TITLE
Cauldron [1.6.4] multiblock structure issues after server reboot.

### ISSUE THREAD

**Issue by DarksideBD** [Multiverse/Multiverse-Core#1461]
Bit of a strange one here. Whenever you create a multiblock structure on the server it functions correctly UNTIL the server is restarted. On logging in after a reboot the structure fails to form and seperates into its comprising blocks.

Removing multiverse from the server corrects the problem instantly. Checked with dev builds #681 - #691. All builds exhibit the same issue.

![evidence](https://cloud.githubusercontent.com/assets/6227079/3563170/f9f53290-0a21-11e4-8e8e-841f9a890c7c.jpg)

Any help would be greatly appriciated. Thank you!

Server: Platform / Mods / Plugins:-

Cauldron # 1.6.4-1.965.21.89 FINAL

=============
\\server\mods
=============
	
Applied Energistics rv14 Finale3.jar              	
Armor Status HUD v1.15.jar                        	
Auto Packager v1.3.jar                            	
Autoutils v1.0.1.jar                              	
bdlib v1.2.3.48.jar                               	
Better Anvil v3.0.9.jar                           	
Better Signs Mod v1.6.4.B.jar                     	
Biblio Craft v1.5.5.jar                           	
BiblioWoods [Forestry] v1.3.jar                   	
BiblioWoods [Natura] v1.1.jar                     	
Big Reactors V0.3.4A2.jar                         	
Binnie Mods v1.8.0.jar                            	
Bspkrs Core v5.3.jar                              	
Buildcraft v4.2.2.455.jar                         	
Carpenter's Blocks v2.1.2.jar                     	
Chest Transporter v1.1.7.jar                      	
Chisel v1.6.0.5.jar                               	
CodeChicken Core  v0.9.0.9.jar                    	
CoFH Core v2.0.0.5.jar                            	
Computer Craft v1.63.jar                          	
Damage Indicators v2.9.2.4.jar                    	
DecoCraft1.6.4 V1.9b.jar                          	
Deconstruction v2.0.1.jar                         	
Dimensional Anchor v57.1.96.jar                   	
EnderIO v1.0.6.376.jar                            	
Enderium PowerArmor v0.1.0-4.jar                  	
EnderStorage v1.4.3.6.jar                         	
Ex Aiquo v0.11.2.jar                              	
Ex Nihilo NEI v1.0.0.jar                          	
Ex Nihilo v1.29e.jar                              	
Extra Buttons v1.6.4.1.jar                        	
Extra Cells v1.6.9d.jar                           	
Extra Utils v1.0.3c.jar                           	
Forestry A v2.3.1.1.jar                           	
FpsPlus 1.6.4 vC.jar                              	
Gendustry v1.1.3.78.jar                           	
Glowstone Wire Universal.jar                      	
HarvestCraft Waila v1.0.4.jar                     	
HexWool v0.3.2.jar                                	
ID Accountant.jar                                 	
Immibis Core v57.2.0.jar                          	
Immibis Peripherals v57.1.0.jar                   	
Infini Tubes v57.0.5.jar                          	
Inventory Tweaks v1.57-dev-95.jar                 	
Ironchest v5.4.1.702.jar                          	
JAMI v1.0.13.122.jar                              	
Jammy Furniture Mod v4.5.jar                      	
Keithy Utils v1.3.30.jar                          	
Liquid XP v57.1.2.jar                             	
Magic Bees v2.1.13.jar                            	
Mekanism Generators v6.0.5.46.jar                 	
Mekanism Tools v6.0.5.46.jar                      	
Mekanism v6.0.5.46.jar                            	
Metallurgy Bees v0.1.2.jar                        	
Metallurgy v3.4.1.32.jar                          	
MineFactory Reloaded v2.7.9 final - Fix.jar       	
Modular Pots v2 - modded.jar                      	
Mr Crayfish Furniture Mod v3.3.3.jar              	
Multi Page Chest v1.2.4b.jar                      	
Natura v2.1.14.jar                                	
NEI Addons v1.10.5.69.jar                         	
NEI Plugins v1.1.0.6.jar                          	
Nether Ores v2.2.2-56.jar                         	
Not Enough Codecs v0.1 snapshot-0.jar             	
Not Enough Items v1.6.1.9.jar                     	
Not Enough Keys v0.0.4.jar                        	
Obsidi Plates v2.0.0.15.jar                       	
Obsidian Boat v1.3.2.jar                          	
Open Blocks v1.2.9 snapshot-417.jar               	
Open Mods Lib v0.5.1 snapshot-214.jar             	
Open Peripheral Addons v0.1.5 snapshot-119.jar    	
Open Peripheral Core v0.4.1 snapshot-139.jar      	
Ore Dictionary Converter v1.4.3.jar               	
Paintings ++ v1.jar                               	
Pam's Clay Spawn v1.6.4.jar                       	
Pam's HarvestCraft v1.6.4a.jar                    	
Pam's Weee Flowers v1.6.4a.jar                    	
Planter Helper v0.4.3.jar                         	
PowerCrystals Core v1.1.8-20.jar                  	
Pressure v0.9.0.2.jar                             	
ProjectRed Base - Modified v4.3.7.32.jar          	
ProjectRed Compat v4.3.7.32.jar                   	
ProjectRed Integration v4.3.7.32.jar              	
ProjectRed Lighting v4.3.7.32.jar                 	
ProjectRed Mechanical v4.3.7.32.jar               	
ProjectRed World v4.3.7.32.jar                    	
Railcraft v8.4.0.0.jar                            	
Reconstructor v1.4.jar                            	
Redstone Arsenal v1.0.0.0.jar                     	
Refined Relocation v1.0.5d.jar                    	
SDXC Reciper v1.1.1.jar                           	
Secret Rooms Mod v4.6.2.324.jar                   	
Simply Jetpacks v0.3.1.jar                        	
SortFix v1.0.jar                                  	
Statues v2.1.1.jar                                	
Thermal Expansion v3.0.0.7.jar                    	
Translocator v1.1.0.15.jar                        	
Tree Capitator v1.6.4.r09.jar                     	
Tube Stuff v57.1.3.jar                            	
Tubes v2.0.1.jar                                  	
Waila Harvestability v1.0.4.jar                   	
Waila v1.5.2a.jar                                 	
Waypoints v1.0.2 fix.jar                          	
Weapon Mod v1.13.6.jar                            	
Wood Converter v2.6.5.jar                         	
WR-CBE 1.4.0.7.jar                                	
Zans Minimap v1.6.4.jar	

===================
\\server\mods\1.6.4
===================

CodeChickenLib-universal-1.6.4-1.0.0.62.jar	
ForgeMultipart-universal-1.6.4-1.0.0.268.jar	

=================
\\server\\plugins
=================
                                        	
Bankcraft v2.2.1.0.jar                            	
BOSEconomy v0.7.8.1.jar                           	
ChestShop.jar                                     	
Death Chest v1.13.3.jar                           	
Death Messages v2.6.2.jar                         	
Disposal Chest v1.7.jar                           	
EasyElevator v1.2.jar                             	
Factions v2.2.2.jar                               	
FoundDiamonds v3.6.3.jar                          	
Helmet v1.1.jar                                   	
ItemDuplicator.jar                                	
LWC v912.jar                                      	
LWC-Economy v912.jar                              	
MCMA_compat.jar                                   	
mcMMO v1.4.08.jar                                 	
Mcore v6.9.1.jar
Multiverse-Core-2.5_691.jar                                  	
My Home v2.3.1.jar
neoPaintingSwitch v1.3.4.jar                      	
PermissionsBukkit v2.1.jar                        	
Rail Switcher v1.0.5.jar                          	
RedBlocks v2.2.0.jar                              	
Sign Edit v3.3.2.jar                              	
Sign Lift v1.1.1.jar                              	
SpawnBed.jar                                      	
Stargate v0.7.9.10.jar                            	
Vault v1.2.27.jar                                 	
VoxelSniper v5.168.7.jar                          	
Worldedit v5.6.jar                                	

P.S. There are NO ID conflicts or errors generated in any of the server logs.

**Comment by TWSSYesterday** [comment]
Would be interesting to see if this is still an issue, for now closed.
