### ISSUE TITLE
**MAJOR ISSUE** Every Restart, Have To Re-Import The Worlds

### ISSUE THREAD

**Issue by bodhidragon** [Multiverse/Multiverse-Core#1492]
every time i restart my server, i have spawn in the default; 'world'. The spawnpoint is different and it is all messed up! I have to reimport the worlds that i had currently going; 'NovaCastelle' and had to redo all the portals as well. the portals were basically not working so i had to do /mvp modify dest :p(Blablabla) and vice versa. This is really annoying and i hope for your community to fix the bug.

**Comment by TWSSYesterday** [comment]
We must assume this is no longer occurring, if the issue is still occurring, then I will re open the ticket. If it is, try updating to the latest build found on http://ci.onarandombox.com/view/Multiverse/
