### ISSUE TITLE
World bans

### ISSUE THREAD

**Issue by MrSwag1313** [Multiverse/Multiverse-Core#1497]
i want diffrent bans i diffrent worlds like i have a hardcore world and one survival world, but when they die in the hardcore world i only want them to be banned i that world not the survival world. any tips on how to do that?

**Comment by Jadiction** [comment]
Hi, I know this is 5 years late, but the best solution for this is likely
1. Manually denying their permission to that world when you want (for example, on death)
2. Searching for a plugin to customize what happens on ban events
3. Having another plugin manage the "ban" per world, I.E doing #1 automatically
4. Try the plugin or bungeecord option as suggested by ghost.
