### ISSUE TITLE
My world has been reverted to an older stage!

### ISSUE THREAD

**Issue by IdkArledge** [Multiverse/Multiverse-Core#1504]
While reading through chat on how to LOAD an UNLOADED world I type /mvm set autoload true "Worldname" on the world... it did not work.

I tried again (this is on a SkyLands word BTW) and still nothing.

I typed this command in and tried on the normal spawn world and it worked (I did this as a test)

Next I typed it in again for the SkyLands world and it worked.

I restarted the server and my main spawn world is now UNLOADED and I was put into the world named "world" (which is not my default spawn world "Spawn" is my default world) and the world is my old version world!

**Comment by TWSSYesterday** [comment]
Not something Multiverse would handle, locked due to lack of updates and it no longer occurring if it ever did.
