### ISSUE TITLE
Per world money

### ISSUE THREAD

**Issue by ShadowBlock** [Multiverse/Multiverse-Core#1506]
Hi!

How can i set up per world money and disable essentials money.

Can someone help me?

**Comment by ShadowBlock** [comment]
Lol? About 2years later you close this thread.
06.03.2016 5:35 kirjutas kuupäeval "Liam" <notifications@github.com>:

**Comment by dumptruckman** [comment]
Multiverse-Inventories can do multi world money but it doesn't (and probably will never) have UUID support. It also has other long standing issues that will likely never be fixed. Good luck!
