### ISSUE TITLE
Startup Failure with Particular World

### ISSUE THREAD

**Issue by JoePCool14** [Multiverse/Multiverse-Core#1507]
Hello there!

I am using the latest Bukkit released build of MV Core and each time it starts up and loads a particular world of mine, it will say its Loading and get stuck at a certain percentage. Then it just stops loading and disables the entire plugin and prevents the server from fully starting. I have had this problem many times before and most of the time its a world that I don't care about. I'll delete the world and it will start perfectly. This time my spawn world has broken and I can't delete it. Do you have any suggestions on what I could do? Is this not a MV issue? Will I need to de-corrupt the world or something of the like? Any response would be fantastic as my server's been down for 2+ weeks now. Thank you so much for reading and I hope you have some sort of solution. :)

**Comment by TWSSYesterday** [comment]
Not the case, locked due to inactivity.
