### ISSUE TITLE
Multiverse and MCEDIT

### ISSUE THREAD

**Issue by YepImRobbie** [Multiverse/Multiverse-Core#1510]
I am using Spigot which supports 1.8 clients.

The world I am importing I tested on singleplayer and it worked perfectly.
Yet, when I import it, it just goes back to its original somehow without the schematic that was imported into it.

Despite, when I load it in I see it transferring all the files successfully.

Please help!

**Comment by TWSSYesterday** [comment]
No longer the case, ticket closed due to lack of updates on ticket.
