### ISSUE TITLE
MAJOR ISSUE: Chunk Generation normal -t flat

### ISSUE THREAD

**Issue by n0grief1** [Multiverse/Multiverse-Core#1513]
This issue causes a creative flatworld to generate flat chunks until the server is restarted, after the server is shutdown and put back up, that same world will start generating normal survival chunks instead of flat chunks.

To re-create this issue:

Create a basic test server using the 1.8 Spigot jar 

Save-all and stop server

Add multiverse core, multiverse portals, and multiverse inventories into plugins directory

Run server until startup is completed, save-all, stop then start again

Generate a world with the following command
/mv create Freebuild normal -t flat

Teleport to the world
/mvtp Freebuild

Generate some chunks, then save-all and stop server

Start server again, you will notice that now all the chunks you generate from then on will be survival chunks instead of flat chunks.

Hope to get this resolved soon as it makes creative un-playable, if i'm dumb and have simply messed up something with the commands please let me know!

**Comment by nocturn9x** [comment]
Sorry to necrobump, but this seems to be happening again...

**Comment by undecimer** [comment]
It is happening to me in late 2024
