### ISSUE TITLE
Custom Ore Generation error

### ISSUE THREAD

**Issue by ZioCrafter** [Multiverse/Multiverse-Core#1515]
Hi, I've created a mod with some Ore Generation.
I create a world with the command "/mv create MondoLibero normal", but my ores don't work.
Other generators of other mod work, but the my generators no, why?
Thanks!

**Comment by Jadiction** [comment]
Closing ticket due to lack of information. Please open a new ticket with more valid information if this issue is still occurring in the latest versions.
