### ISSUE TITLE
i get a error 

### ISSUE THREAD

**Issue by CraftPixel123** [Multiverse/Multiverse-Core#1525]
when i do /mvp create OpFactions3 -s9985038147 i get a error 
i tried it with out the seed but i still get an error
06:31:27  [Server thread/INFO]: View Distance: 10
06:31:27  [Server thread/INFO]: Zombie Aggressive Towards Villager: true
06:31:27  [Server thread/INFO]: Chunks to Grow per Tick: 650
06:31:27  [Server thread/INFO]: Clear tick list: false
06:31:27  [Server thread/INFO]: Experience Merge Radius: 3.0
06:31:27  [Server thread/INFO]: Preparing start region for level 4 (Seed: 998538147)
06:31:29  [Server thread/INFO]: Preparing spawn area for Opfactions2, 36%
06:31:30  [Server thread/INFO]: Preparing spawn area for Opfactions2, 77%
06:31:32  [Server thread/INFO]: [Multiverse-Core] 5 - World(s) loaded.
06:31:32  [Server thread/INFO]: [Multiverse-Portals] Enabling Multiverse-Portals v2.4-b548
06:31:32  [Server thread/INFO]: [Multiverse-Portals] - Version 2.4-b548 Enabled - By Rigby and fernferret
06:31:32  [Server thread/INFO]: [Multiverse-Portals]  0 - Portals(s) loaded
06:31:32  [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
06:31:32  [Server thread/INFO]: Done (26.588s)! For help, type "help" or "?"
06:31:33  [Server thread/INFO]: swagman10055[/211.30.162.177:56011] logged in with entity id 701 at ([world] -69.93491295530315, 7.6032536393630075, 1.4019477219622574)
06:31:57  [Server thread/INFO]: swagman10055 issued server command: /mv create OpFactions
06:32:21  [Server thread/INFO]: swagman10055 issued server command: /mv create OpFactions normal 998538147
06:32:26  [Server thread/INFO]: swagman10055 issued server command: /mv create OpFactions3 normal 998538147
06:32:26  [Server thread/INFO]: swagman10055: Starting creation of world 'OpFactions3'...
06:32:26  [Server thread/INFO]: [Multiverse-Core] Loading World & Settings - 'OpFactions3' - Env: NORMAL - Type: NORMAL
06:32:26  [Server thread/INFO]: -------- World Settings For [OpFactions3] --------
06:32:26  [Server thread/INFO]: Mob Spawn Range: 4
06:32:26  [Server thread/INFO]: Anti X-Ray: true
06:32:26  [Server thread/INFO]: 	Engine Mode: 1
06:32:26  [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
06:32:26  [Server thread/INFO]: 	Replace Blocks: [1, 5]
06:32:26  [Server thread/INFO]: Nerfing mobs spawned from spawners: false
06:32:26  [Server thread/INFO]: Cactus Growth Modifier: 100%
06:32:26  [Server thread/INFO]: Cane Growth Modifier: 100%
06:32:26  [Server thread/INFO]: Melon Growth Modifier: 100%
06:32:26  [Server thread/INFO]: Mushroom Growth Modifier: 100%
06:32:26  [Server thread/INFO]: Pumpkin Growth Modifier: 100%
06:32:26  [Server thread/INFO]: Sapling Growth Modifier: 100%
06:32:26  [Server thread/INFO]: Wheat Growth Modifier: 100%
06:32:26  [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
06:32:26  [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
06:32:26  [Server thread/INFO]: Alternative Hopper Ticking: false
06:32:26  [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
06:32:26  [Server thread/INFO]: Random Lighting Updates: false
06:32:26  [Server thread/INFO]: Structure Info Saving: true
06:32:26  [Server thread/INFO]: Sending up to 10 chunks per packet
06:32:26  [Server thread/INFO]: Max Entity Collisions: 8
06:32:26  [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
06:32:26  [Server thread/INFO]: Max TNT Explosions: 100
06:32:26  [Server thread/INFO]: Item Despawn Rate: 6000
06:32:26  [Server thread/INFO]: Item Merge Radius: 2.5
06:32:26  [Server thread/INFO]: Arrow Despawn Rate: 1200
06:32:26  [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
06:32:26  [Server thread/INFO]: View Distance: 10
06:32:26  [Server thread/INFO]: Zombie Aggressive Towards Villager: true
06:32:26  [Server thread/INFO]: Chunks to Grow per Tick: 650
06:32:26  [Server thread/INFO]: Clear tick list: false
06:32:26  [Server thread/INFO]: Experience Merge Radius: 3.0
06:32:26  [Server thread/INFO]: Preparing start region for level 5 (Seed: -2678508339784404295)
06:32:27  [Server thread/INFO]: Preparing spawn area for OpFactions3, 0%
06:32:28  [Server thread/INFO]: Preparing spawn area for OpFactions3, 3%
06:32:29  [Server thread/INFO]: Preparing spawn area for OpFactions3, 4%
06:32:30  [Server thread/INFO]: Preparing spawn area for OpFactions3, 4%
06:32:31  [Server thread/INFO]: Preparing spawn area for OpFactions3, 8%
06:32:32  [Server thread/INFO]: Preparing spawn area for OpFactions3, 8%
06:32:33  [Server thread/INFO]: Preparing spawn area for OpFactions3, 12%
06:32:34  [Server thread/INFO]: Preparing spawn area for OpFactions3, 12%
06:32:35  [Server thread/INFO]: Preparing spawn area for OpFactions3, 16%
06:32:36  [Server thread/INFO]: Preparing spawn area for OpFactions3, 16%
06:32:38  [Server thread/INFO]: Preparing spawn area for OpFactions3, 20%
06:32:39  [Server thread/INFO]: Preparing spawn area for OpFactions3, 20%
06:32:40  [Server thread/INFO]: Preparing spawn area for OpFactions3, 24%
06:32:41  [Server thread/INFO]: Preparing spawn area for OpFactions3, 28%
06:32:42  [Server thread/INFO]: Preparing spawn area for OpFactions3, 28%
06:32:43  [Server thread/INFO]: Preparing spawn area for OpFactions3, 32%
06:32:44  [Server thread/INFO]: Preparing spawn area for OpFactions3, 32%
06:32:45  [Server thread/INFO]: Preparing spawn area for OpFactions3, 36%
06:32:46  [Server thread/INFO]: Preparing spawn area for OpFactions3, 40%
06:32:47  [Server thread/INFO]: Preparing spawn area for OpFactions3, 40%
06:32:48  [Server thread/INFO]: Preparing spawn area for OpFactions3, 44%
06:32:49  [Server thread/INFO]: Preparing spawn area for OpFactions3, 44%
06:32:50  [Server thread/INFO]: Preparing spawn area for OpFactions3, 48%
06:32:51  [Server thread/INFO]: Preparing spawn area for OpFactions3, 52%
06:32:52  [Server thread/INFO]: Preparing spawn area for OpFactions3, 52%
06:32:53  [Server thread/INFO]: Preparing spawn area for OpFactions3, 56%
06:32:54  [Server thread/INFO]: Preparing spawn area for OpFactions3, 60%
06:32:55  [Server thread/INFO]: Preparing spawn area for OpFactions3, 61%
06:32:56  [Server thread/INFO]: Preparing spawn area for OpFactions3, 65%
06:32:57  [Server thread/INFO]: Preparing spawn area for OpFactions3, 69%
06:32:58  [Server thread/INFO]: Preparing spawn area for OpFactions3, 73%
06:32:59  [Server thread/INFO]: Preparing spawn area for OpFactions3, 77%
06:33:00  [Server thread/INFO]: Preparing spawn area for OpFactions3, 81%
06:33:01  [Server thread/INFO]: Preparing spawn area for OpFactions3, 85%
06:33:02  [Server thread/INFO]: Preparing spawn area for OpFactions3, 89%
06:33:03  [Server thread/INFO]: Preparing spawn area for OpFactions3, 93%
06:33:04  [Server thread/INFO]: Preparing spawn area for OpFactions3, 97%
06:33:05  [Server thread/WARN]: [Multiverse-Core] Spawn location from world.dat file was unsafe. Adjusting...
06:33:05  [Server thread/WARN]: [Multiverse-Core] Original Location: X: 0 Y: 0 Z: 0 P: 0 Y: 0
06:33:05  [Server thread/INFO]: [Multiverse-Core] New Spawn for 'OpFactions3' is Located at: OpFactions3:0.00,63.00,0.00:0.00:0.00
06:33:07  [Server thread/INFO]: swagman10055: Complete!
06:33:07  [Netty Server IO #2/WARN]: Selector.select() returned prematurely 512 times in a row; rebuilding selector.
06:33:07  [Netty Server IO #2/INFO]: Migrated 0 channel(s) to the new Selector.
06:33:07  [Server thread/INFO]: swagman10055 lost connection: Internal Exception: io.netty.handler.timeout.ReadTimeoutException
06:33:07  [Server thread/INFO]: swagman10055 left the game.
06:33:07  [User Authenticator #2/INFO]: UUID of player swagman10055 is cb2de3bd-d9e6-4d3d-91cd-16c29df2a023
06:33:07  [Server thread/INFO]: swagman10055[/211.30.162.177:56079] logged in with entity id 1444 at ([world] -67.09963719928538, 11.312577099539324, -0.2880208651821555)
06:33:21  [Server thread/INFO]: swagman10055 issued server command: /mvm delete OpFactions
06:33:54  [Server thread/INFO]: swagman10055 issued server command: /mv modify remove OpFactions
06:34:08  [Server thread/INFO]: swagman10055 issued server command: /mv remove Opfactions
06:34:08  [Server thread/WARN]: [Multiverse-Core] Hmm Multiverse does not know about this world but it's loaded in memory.
06:34:08  [Server thread/WARN]: [Multiverse-Core] To unload it using multiverse, use:
06:34:08  [Server thread/WARN]: [Multiverse-Core] /mv import Opfactions NORMAL
06:34:32  [Server thread/INFO]: swagman10055 issued server command: /whitelist on
06:34:32  [Server thread/INFO]: [swagman10055: Turned on the whitelist]
06:35:07  [Server thread/INFO]: swagman10055 issued server command: /mvp create OpFactions -s 998538147
06:35:20  [Server thread/INFO]: swagman10055 issued server command: /mvp create OpFactions -s998538147
06:35:20  [Server thread/INFO]: WEAPI
06:35:20  [Server thread/ERROR]: null
06:35:20 org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.4-b548
06:35:20 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:35:20 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:35:20 at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:35:20 at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:35:20 at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:35:20 at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:35:20 at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:35:20 at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:35:20 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_05]
06:35:20 at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_05]
06:35:20 at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:35:20 at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:35:20 at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:35:20 at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:35:20 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
06:35:20 Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;
06:35:20 at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:169) ~[?:?]
06:35:20 at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
06:35:20 at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
06:35:20 at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
06:35:20 at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
06:35:20 at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
06:35:20 at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:317) ~[?:?]
06:35:20 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:35:20 ... 14 more
06:36:59  [Server thread/INFO]: swagman10055 issued server command: /mvp create OpFactions -s
06:36:59  [Server thread/INFO]: WEAPI
06:36:59  [Server thread/ERROR]: null
06:36:59 org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.4-b548
06:36:59 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:36:59 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:36:59 at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:36:59 at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:36:59 at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:36:59 at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:36:59 at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:36:59 at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:36:59 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_05]
06:36:59 at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_05]
06:36:59 at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:36:59 at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:36:59 at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:36:59 at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:36:59 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
06:36:59 Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;
06:36:59 at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:169) ~[?:?]
06:36:59 at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
06:36:59 at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
06:36:59 at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
06:36:59 at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
06:36:59 at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
06:36:59 at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:317) ~[?:?]
06:36:59 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:36:59 ... 14 more
06:37:24  [Server thread/INFO]: swagman10055 issued server command: /mvp create OpFactions -s998538147
06:37:24  [Server thread/INFO]: WEAPI
06:37:24  [Server thread/ERROR]: null
06:37:24 org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.4-b548
06:37:24 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:37:24 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:37:24 at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:37:24 at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:37:24 at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:37:24 at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:37:24 at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:37:24 at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:37:24 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_05]
06:37:24 at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_05]
06:37:24 at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:37:24 at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:37:24 at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:37:24 at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:37:24 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
06:37:24 Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;
06:37:24 at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:169) ~[?:?]
06:37:24 at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
06:37:24 at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
06:37:24 at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
06:37:24 at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
06:37:24 at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
06:37:24 at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:317) ~[?:?]
06:37:24 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.jar:git-Spigot-52c130f-89944c0]
06:37:24 ... 14 more

**Comment by TWSSYesterday** [comment]
Use 5.x branch of WorldEdit.

**Comment by CraftPixel123** [comment]
if anybody has ideas and plz put a link to whatever i should download thank you!

**Comment by TWSSYesterday** [comment]
http://dev.bukkit.org/bukkit-plugins/worldedit/files/58-world-edit-5-6-3-for-bukkit-1-7-10/
