### ISSUE TITLE
Having multiple World nether and ends

### ISSUE THREAD

**Issue by Christian4945** [Multiverse/Multiverse-Core#1526]
I was wondering is there a way where i can have nether and like a survival world to connect so when you go through the portal you get sent to the nether

**Comment by ryantheleach** [comment]
You want multiverse-netherportals

**Comment by TWSSYesterday** [comment]
@ryantheleach Multiverse NetherPortals would help you do this.

**Comment by spetznack** [comment]
Be aware that NPC (villagers, monsters, horses, etc..) and possibly items disappears when they go through netherportals when using multiverse-netherportals build #682 (only one I have tested, the later builds do not have any changes)

This is related:
https://github.com/Multiverse/Multiverse-NetherPortals/issues/72
