### ISSUE TITLE
Beds save spawnpoint even in worlds with bedRespawn on false

### ISSUE THREAD

**Issue by Jeppa** [Multiverse/Multiverse-Core#1528]
If a bed gets used in a world with bedRespawn set to 'false' 
and players die, they respawn at the default respawn .. ok.
But if this player moves to a world with bedRespawn set to 'true' and
he dies in that world he gets teleportet to the bed in the first world!

setting bedRespawn to false should prevent the game from saving the
respawnpoint to the players file...

**Comment by TWSSYesterday** [comment]
You may be using another plugin (Such as essentials) which by default handles teleportation.

**Comment by Jeppa** [comment]
i have essentials respawn priority set to lowest
-> respawn-listener-priority: lowest
so essentials should not be involved in this behaviour.

**Comment by TWSSYesterday** [comment]
Is the config setting set or is it not actually saving the setting?

**Comment by bladextd** [comment]
Try setting it to medium. Or higher if that has anything to do with it.
