### ISSUE TITLE
portalsearchradius apparently not respected

### ISSUE THREAD

**Issue by gregrebholz** [Multiverse/Multiverse-Core#1530]
Spigot: This server is running CraftBukkit version git-Spigot-e497721-96d09e3 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
Plugins: Multiverse-Core v2.5-b688, Multiverse-NetherPortals v2.4-b530

I have the normal/default world named "world" with a scaling factor of 1.0, and "world_nether" with a scaling factor of 16.0, and the settings "defaultportalsearch = false" and "portalsearchradius = 16" in config.yml.  It seems that "world" portals are linking to a prior existing "world_nether" portal even when the expected translated coordinates are over 100 blocks away in X and Z.

First overworld portal to nether was created at world:{-686, 427}, which should give an expected (div 16) exit at world_nether:{-42, 26} but was actually spawned at world_nether:{-48, 28} (close enough).  The next portal created at world:{-1686, 1427} (1000 blocks away in X and Z), was linked to the original world_nether:{-48,28} portal.  A new portal at world:{3200,3200} creates a new portal at world_nether:{200,200} and the return trip works as expected.   For a final test all portals were destroyed, the world:{-1686, 1427} portal was created first, and created a new world_nether:{-105, 89} portal (correct 1/16th scaling).  When the world{-686,427} portal was created it found and linked to the world_nether:{-105, 89} portal.

I originally had the default portalsearchradius of 128, which would make this behavior correct.  I've tried setting portalsearchradius to 8 (and server restart) with no effect.  I've tried "linking" world and world_nether (and the converse) with no effect.  I also tried setting "defaultportalsearch = true" and server restart with no effect.

So it appears that a 128 block search radius within world_nether (2048 in world) is being used to link portals, regardless of the setting in config.yml.  Thanks for your time and efforts!

**Comment by chillerkraft** [comment]
i'm also noticing not being able to effectively change the portal search radius.

**Comment by benwoo1110** [comment]
Fixed in https://github.com/Multiverse/Multiverse-Core/commit/3bb8de6d33f72377453cf85e513ffc1f439397ae
