### ISSUE TITLE
1.8 World Corruption

### ISSUE THREAD

**Issue by OMGItsEric** [Multiverse/Multiverse-Core#1531]
When you create a new world, using this format, /mv create <Name> normal -t flat, then restart your server, the world corrupts. It does this: http://imgur.com/GtuuWJ5,Kynj9Ag,81UHs84#0
Also when you import a world using, /mv import <name> normal, you dont even have to restart, it instantly corrupts. Im using spigot 1.8 with the newest multiverse.

**Comment by TWSSYesterday** [comment]
Versions of everything? Doesn't happen to me and I'm on latest of both.

**Comment by OMGItsEric** [comment]
16.01 09:39:50 [Server] INFO [Multiverse-Core] Bukkit Version: git-Spigot-"a1bbf96" (MC: 1.8)
16.01 09:39:50 [Server] INFO [Multiverse-Core] Multiverse-Core Version: 2.5-b678
16.01 09:39:50 [Server] INFO [Multiverse-Core] Dumping Config Values: (version 2.9)
http://gyazo.com/f6776576581ce0a849c8c38e8ac57bf5

**Comment by ryantheleach** [comment]
I can't even work out which version of spigot that is. People previously complaining about the same issue found that using the latest versions of spigot prevented the issue from occurring, it can't fix what's already happened.

**Comment by TWSSYesterday** [comment]
@OMGItsEric Mind compiling the latest version please?

**Comment by logicalPolaris** [comment]
I'm having the same problem.

**Comment by TWSSYesterday** [comment]
@logicalPolaris update Spigot, use latest Multiverse. This issue seemed to be Spigot sided.

**Comment by logicalPolaris** [comment]
I have the latest spigot currently, as well as Multiverse b692.
![screenshot_2](https://cloud.githubusercontent.com/assets/11083026/6499494/1b7a9872-c2b1-11e4-8464-3ccd93624652.jpg)
![screenshot_3](https://cloud.githubusercontent.com/assets/11083026/6499495/1d9aa67e-c2b1-11e4-8d12-b7b764ed121a.jpg)

**Comment by TWSSYesterday** [comment]
Definitely no longer an issue, closed.
