### ISSUE TITLE
Not able to walk through portals

### ISSUE THREAD

**Issue by mephils** [Multiverse/Multiverse-Core#1534]
I created two portals, spawn2survival and survival2spawn

When I have survival2spawn selected I typed the command /mvp modify dest p:spawn2survival

But I can't walk through the portal, anyone know how I could fix that?

**Comment by TWSSYesterday** [comment]
When you walk through the portal, what happens?
Does the command "/mvp modify dest p:spawn2survival" return anything?

**Comment by mephils** [comment]
Yes, when I do /mvp modify dest p:spawn2survival it returns "Property destination of Portal (in yellow) survival2spawn (in green) was set to (in blue p:spawn2survival)

However when I attempt to walk through it nothing happens, it's as if it's an unedited piece of land

**Comment by TWSSYesterday** [comment]
Okay, so the portal is created, is anything coming up as an error in the log file? (Pastebin it please) What Spigot/CB version are you using?

**Comment by FernFerret** [comment]
Also, should be noted that this is the Core issue tracker, please reopen this issue in [Multiverse-Portals](https://github.com/Multiverse/Multiverse-Portals/issues) issue tracker if you wish to continue discussion.
