### ISSUE TITLE
Onarandombox Tests fail during build

### ISSUE THREAD

**Issue by MCTyler** [Multiverse/Multiverse-Core#1536]
Is there currently any way to build this project? All the tests fail when I try to build.

**Comment by MCTyler** [comment]
Opps, nevermind...Java 6...I was using 7.

**Comment by MCTyler** [comment]
I installed java 6 and used it and the tests still fail...can I get some help please?

**Comment by TWSSYesterday** [comment]
No longer the case, over a year old; wow.

**Comment by MCTyler** [comment]
Yea, I think you guys are are a little behind on tickets man! Lol! Thanks.
--- MCTyler commented on Jan 20, 2015

**Comment by TWSSYesterday** [comment]
:)
