### ISSUE TITLE
Suggestion: per world mod pack

### ISSUE THREAD

**Issue by nayfaan** [Multiverse/Multiverse-Core#1537]
can you make it so that we can use a different mod pack for each world?
so that the plugins are only usable in one world and separate from each other. and players does not need to have all the plugins to enter the server.

**Comment by ryantheleach** [comment]
Do you mean plugins or mods, you are using the terms interchangibly.

Multiverse has never supported per world plugins that didn't have the support themselves, there are other plugins that can handle this.

If on the other hand, you mean forge mods, then also no, but I don't know of any servers that can allow this.

The way most large networks do multiple modpacks or multiworld stuff these days is by running multiple servers behind a bungeecord proxy server.

**Comment by TWSSYesterday** [comment]
Not really a feature that can be implemented efficiently and wouldn't be an essential feature. Locked due to inactivity.
