### ISSUE TITLE
What this plugin should have

### ISSUE THREAD

**Issue by Freakingchichickenbones** [Multiverse/Multiverse-Core#1538]
I am the owner of my server and I made pets for the admin but they don't teleport through worlds . 😔

But you should add the ability to get pets teleporting through worlds and you could enable and disable it it would start disabled and also you could restrict them from entering worlds and if you had LibsDisguises they would keep there disguises please add this more people would get this plugin and it would mabby also be good for LibsDisguises

**Comment by Freakingchichickenbones** [comment]
Um will anyone tell me if this idea is good???

**Comment by ryantheleach** [comment]
disguises not persisting through worlds shouldn't be a multiverse problem as far as I can tell.

When you say pets, do you mean wolves or EchoPets. If EchoPets arn't following owners across world teleports that sounds more like an EchoPets issue.

**Comment by Freakingchichickenbones** [comment]
I mean normal pets

**Comment by TWSSYesterday** [comment]
I believe EchoPet and MyPet both have this feature now. Locking ticket after a year and a bit of inactivity.
