### ISSUE TITLE
Can't delete or unload worlds

### ISSUE THREAD

**Issue by Frostguy361** [Multiverse/Multiverse-Core#1540]
When I type /mv delete (worldname), I get the error "World could not be deleted!" and then I try /mv unload (worldname) and I get the error "Error trying to unload world (worldname)!". Also, I tried /mv remove (worldname) and I got the error "Error trying to remove (worldname) from config!". What could cause this? I tried removing the world from the server folder after shutdown and on restart it regenerated. So, I had to shut it down again and remove the world from the multiverse config and from the server folder. This is what I am running...

[Multiverse-Core] [Multiverse-Core] Multiverse-Core Version: 2.4-b527

[Multiverse-Core] [Multiverse-Inventories] Multiverse-Inventories Version: 2.5-b374

[Multiverse-Core] [Multiverse-Portals] Multiverse-Portals Version: 2.4-b548

Plugins: Too many

[Multiverse-Core] [Multiverse-Core] Economy being used: Essentials Economy

Bukkit version: craftbukkit-1.7.9-R0.2

**Comment by TWSSYesterday** [comment]
Replace the jar file, ideally backup all of your folders. Locked due to inactivity and age of issue.
