### ISSUE TITLE
Multiverse error during World generation

### ISSUE THREAD

**Issue by Warclen** [Multiverse/Multiverse-Core#1541]
I recently started a new server and when I installed multiverse I received the errors in the following link when generating the default world files. I tried deleting the specific world and, regenerating it. But, Nothing fixes it. Help?

http://pastebin.com/hTxuCh3z

I also get an error when walking through portals, I'll attach a paste of the code later when the authentication servers come back online.

**Comment by rhNeo** [comment]
You stopped the pastie at when MV starts. That makes it not useful at all.
