### ISSUE TITLE
Issues with NBT tags!

### ISSUE THREAD

**Issue by roopekoo** [Multiverse/Multiverse-Core#1542]
I have boots on my spawn world which give me 30% more boost. When I teleport to other world and go back to spawn, 30% speed is disappeared. NBT tags reset! This issue happens when leaving main world and coming back.
Can you check is this possible to fix? If so can you fix it?
Regards Roopekoo

**Comment by rhNeo** [comment]
So you are using NBT tags to boost you?

**Comment by roopekoo** [comment]
Then I'm looking for plugin that gives boost to certain area and to players which have diamond boots on them.
Any suggestios?

**Comment by RoenSweg** [comment]
Add "Plugin request" or some other tag to this post so someone that actually knows can help you :+1:

**Comment by ryantheleach** [comment]
I don't see how this could be a multiverse problem, unless you are using multiverse inventories or something.
