### ISSUE TITLE
Option to Go to last location when teleporting between worlds

### ISSUE THREAD

**Issue by Gaelan** [Multiverse/Multiverse-Core#1543]
Is this an option in Core? Is there a plugin that does this?

Thanks!

**Comment by rhNeo** [comment]
I believe MV does this by default. If not, check the configuration.

**Comment by manuelgu** [comment]
Any further information on that? Couldn't find anything in the config files and it also does not do this by default.. /mvtp worldname always teleports to the World Spawn.

**Comment by FernFerret** [comment]
I feel like this is the same thing as #1689. Closing as duplicate (since that one has a lot more description).
