### ISSUE TITLE
Spawning Issues

### ISSUE THREAD

**Issue by ShowStopperMatrix** [Multiverse/Multiverse-Core#1544]
I have a wold named "Plotworld" generated with the Plotsquared plugin. For some reason I cannot get anything to spawn in this world except bats with a Mob Egg (oddly enough a Bat Mob Spawner doesn't work). I want mobs from an egg or spawner to be able to spawn, but no natural spawning. Spawners also don't work in the world "Lobby", but they do work in "Survival".

Plotworld: No natural spawning, only Bat eggs work, no spawners (I want all eggs and spawners to work)
Lobby: No natural spawning, eggs work, no spawners (I want spawners to work)
Survival: Natural spawning, eggs and spawners work.

Contents of the worlds.yml: http://pastebin.com/DKDz80wr

Contents of settings.yml for the PlotSquared plugin: http://pastebin.com/b2sMxUVh

Contents of server.properties: http://pastebin.com/YEEiaS9X

List of installed plugins:
BarAPI.jar
BetterShops.jar
BiomeGenerator.jar
ChestDupeFix.jar
craftconomy3-3.2.1.jar
districts.jar
DPets.jar
dynmap-2.1.jar
EasySpawn.jar
EnjinMinecraftPlugin.jar
FirstJoin.jar
Multiverse-Core-2.5%20(1).jar
Multiverse-Portals-2.4.jar
Multiverse-SignPortals-2.4.jar
NoItemDrops.jar
Plot2Dynmap.jar
PlotSquared.jar
RandomTeleport.jar
SpawnerShop.jar
Trading_v2.0.jar
Vault.jar
worldedit-bukkit-6.0.jar
WorldGuard.jar

**Comment by rhNeo** [comment]
Can you show me your Worldguard configuration for the Plot world? It could be blocked in there.

**Comment by ShowStopperMatrix** [comment]
Here it is: http://pastebin.com/LkLLEyMN

**Comment by rhNeo** [comment]
Thx I'll take a look. Gtg so I'll reply in like one hour.

**Comment by ShowStopperMatrix** [comment]
I tried with the Worldguard plugin completely deactivated and it doesn't seem to be the issue.

**Comment by rhNeo** [comment]
Okey, and your PlotSquared configuration?

**Comment by ShowStopperMatrix** [comment]
That was the second link. 

An update, I tested different settings in the PlotSquared and Multiverse world configs and it seems the only way to get it working right is to turn on natural spawning in all the files/worlds. I'm not sure how to get the eggs and spawners to work without natural spawning though, but if this is the only way then alright.

**Comment by rhNeo** [comment]
Im sooooo stupid :P but yeah I couldn't find anything wrong with it.  Try a reinstall

**Comment by rhNeo** [comment]
Of PlotSquared*

**Comment by TWSSYesterday** [comment]
Should be working okay, tested fine on a client's server, closing for now. If anyone has a similar issue, I'll reopen this ticket back up.
