### ISSUE TITLE
Multiverse world not loading builds

### ISSUE THREAD

**Issue by mstivland2** [Multiverse/Multiverse-Core#1545]
Hi, I own a server and I'm trying to add a world I downloaded, but it keeps loading in as just a flat world without the builds. As far as I can tell I'm doing everything right and I don't think it's a matter of not spawning in the right place, though could be. My friend was able to put it on his server just fine. I can't figure it out.

**Comment by TWSSYesterday** [comment]
You making sure you're using /mv import?

**Comment by mstivland2** [comment]
Yeah, it was very strange, this was a while ago and we have a new host now
and it works perfectly on the new server. Beats me what it could have been,
but thanks!

**Comment by TWSSYesterday** [comment]
No problem, if this happens again let us know :)

**Comment by mstivland2** [comment]
Will do, thanks!
