### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by mohitnysa** [Multiverse/Multiverse-Core#1546]
Hello, i am having a serious issue which allows NOBODY to be able to do /spawn... itt just says "an internal error occurred while attempting to perform this command.. and it has this relatively large error message in console..
All the details (including the config file) is included below

CONSOLE LOG ERROR

http://pastebin.com/KhTRUDtH

CONFIG FILE (Took Out The Starting Part Because IT Was Coming Out HUGE)

http://pastebin.com/EaBiKzbT

And Im Not Too Sure, But IT Might Be Because Of Another Plugin I Installed Called UltimateHub Which Also Adds The /spawn Command, Its A Hunch Not too sure..

Please Help me Out :)

**Comment by TWSSYesterday** [comment]
Reformat in pastebins please :) The full log would be better.

**Comment by mohitnysa** [comment]
Okay One Second

**Comment by mohitnysa** [comment]
Wait How Do I Put In A Pastebin here?

**Comment by mohitnysa** [comment]
Just Put The Link?

**Comment by TWSSYesterday** [comment]
Yup :)

**Comment by mohitnysa** [comment]
K

**Comment by mohitnysa** [comment]
Should i put the config file in pastern too?

**Comment by mohitnysa** [comment]
pastebin*

**Comment by mohitnysa** [comment]
Wait A Minute..
I Just Lost All Of My Worlds..

**Comment by mohitnysa** [comment]
When I Try To Import The World Back In, It Says "an internal error occurred while attempting to perform this command. Details were printed to to your server console and logs, please add that to your bug report..

**Comment by dumptruckman** [comment]
Update Multiverse Core to a beta build instead of using 2.4 which is VERY outdated.

**Comment by mohitnysa** [comment]
wait But Im Not Using 2.4

**Comment by mohitnysa** [comment]
http://pastebin.com/G9SF0qaM
This is the error that comes up when i try to import

**Comment by dumptruckman** [comment]
Please read [this](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and submit the requested information.

**Comment by TWSSYesterday** [comment]
Spawn is handled by another plugin, the issue was mainly about importing worlds after it.
