### ISSUE TITLE
How to have players log in where logged out!

### ISSUE THREAD

**Issue by mrbensplanet** [Multiverse/Multiverse-Core#1547]
I want players to be able to log in where they logged out. I set use exact location (in bukkit.yml) to true, I am using multiverse and essentials. I don't want to give all users multiverse.* and I have tried many suggestions. Pls help!

**Comment by Frostguy361** [comment]
This is what i have "use-exact-login-location: false" and my players log in where they logged off. I assume that was the thing you were talking about. If that doesn't fix it then i could test a few other things but i don't know it works for me. I generally only mess with settings i know for a fact what they do this one i just left as is.

**Comment by mrbensplanet** [comment]
I already tried that,  it's either an essentials or multi verse plugin configuration prob

**Comment by TWSSYesterday** [comment]
This should definitely no longer be occurring.
