### ISSUE TITLE
How to update Multiverse?

### ISSUE THREAD

**Issue by Frostguy361** [Multiverse/Multiverse-Core#1548]
How do you update Multiverse from the stable release 2.4-AB to the beta release 2.5-b69? Can you just exchange the .jar files? Or do you have to erase the multiverse folder and let it generate a new one?

**Comment by Frostguy361** [comment]
Oh and anyone knowledgeable on the topic if they had the time could they assist with my other ticket (which actually may be solved after updating),

**Comment by TWSSYesterday** [comment]
Update jar files, a worlds.yml reset is recommended and a config.yml is highly recommended.
