### ISSUE TITLE
Unknown world but cannot import

### ISSUE THREAD

**Issue by TheMysterious** [Multiverse/Multiverse-Core#1549]
I have a world that is loaded and can be teleported to, works with color aliases and everything. But when I try to /mvunload it, it says: "[Multiverse-Core] Hmm Multiverse does not know about this world, but it's loaded in memory. To let Multiverse know about this world use /mvimport"
when I do /mvimport it says: "[Multiverse-Core] Multiverse already knows about this world!"

I know I could just /mvremove it and import it again and it would be fine. But I've had this issue quite a few times, and I just wanted to let you know.

**Comment by djbencrazy** [comment]
I have the same problem I can not import

**Comment by TWSSYesterday** [comment]
We must assume this is no longer occurring due to a lack of further response, if the issue is still occurring, then I will re open the ticket. If it is, try updating to the latest build found on http://ci.onarandombox.com/view/Multiverse/

**Comment by TheMysterious** [comment]
Probably, but I stopped using multiverse.
