### ISSUE TITLE
Portals making effects sideways?

### ISSUE THREAD

**Issue by xtoolbearx** [Multiverse/Multiverse-Core#1550]
![2015-02-20_18 07 54](https://cloud.githubusercontent.com/assets/10714893/6311103/e2409612-b92b-11e4-8c8c-08724ae909f9.png)

Can anyone help? plus and added little thing can I disable portal sounds?

**Comment by TWSSYesterday** [comment]
You can use :<ID> to do this, for example portal_block:1. Closed due to inactivity.
