### ISSUE TITLE
RPG-style separate resettable worlds

### ISSUE THREAD

**Issue by cajlo** [Multiverse/Multiverse-Core#1552]
I need feature that will do this:
1) I create world, called "%world%".
2) I create party "%party_name%" and invite some players.
3) We enter this world, instead of %world%, %world-party_name% world is loading, copyed "%world%" as itself.
4) As nobody is in "%world-party_name%", it simple unloading and deleting.
(I know plugin Instances do this, but no support for Cauldron)
(I know plugins LokiDungeons and DungeonBuilder do this, but no multiworld support)

**Comment by TWSSYesterday** [comment]
We must assume this is no longer occurring due to a lack of further response, if the issue is still occurring, then I will re open the ticket. If it is, try updating to the latest build found on http://ci.onarandombox.com/view/Multiverse/

**Comment by dumptruckman** [comment]
@TWSSYesterday This sounds like a feature request, not a bug.

In any case, it's not something we're likely to implement. There are other plugins out there that seek to implement this kind of feature.

**Comment by TWSSYesterday** [comment]
@dumptruckman Of course it is, I'm an idiot "I need a feature". it sounds non essential for Multiverse really.

**Comment by cajlo** [comment]
funny, year ago it was a request(26 feb 2015), and thanks call me idiot, so sweet, you know, wish you to read smth like this in near future

**Comment by FernFerret** [comment]
@cajlo I believe you misread @TWSSYesterday's comment (granted it has no punctuation :smiley:)

Read it like this:

>@dumptruckman Of course it is, I'm an idiot. (I didn't see it started with) "I need a feature".
>(however)it sounds ~~non essential~~ (outside the scope) for Multiverse really.

This really is outside the scope for Multiverse-Core. We've experimented with Multiverse-Adventures and Multiverse-Layers, but I'm not sure either are production ready (definitely not layers)

With all of that said, I don't think the team has time to look into this for now, so I'm going to leave it closed. Sorry you misread the chat and felt offended.
