### ISSUE TITLE
PermissionEx MYSQL

### ISSUE THREAD

**Issue by V0rki** [Multiverse/Multiverse-Core#1554]
03.03 08:41:37 [Server] INFO at ru.tehkode.permissions.PermissionManager.createBackend(PermissionManager.java:624)
03.03 08:41:37 [Server] INFO at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:367)
03.03 08:41:37 [Server] INFO at ru.tehkode.permissions.backends.PermissionBackend.getBackend(PermissionBackend.java:392)
03.03 08:41:37 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
03.03 08:41:37 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
03.03 08:41:37 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
03.03 08:41:37 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
03.03 08:41:37 [Server] INFO at ru.tehkode.permissions.backends.sql.SQLBackend.<init>(SQLBackend.java:193)
03.03 08:41:37 [Server] INFO at ru.tehkode.permissions.backends.PermissionBackend.performSchemaUpdate(PermissionBackend.java:90)
03.03 08:41:37 [Server] INFO at ru.tehkode.permissions.backends.sql.SQLBackend$3.performUpdate(SQLBackend.java:187)
03.03 08:41:37 [Server] INFO ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'
03.03 08:41:37 [Server] ERROR Error occurred with PermissionsEx! Please post it to http://git.io/xaHg. Full error:
03.03 08:41:37 [Server] WARN An update to PermissionsEx version 1.23.1 is available to download from http://dev.bukkit.org/bukkit-plugins/permissionsex/. Please review the changes and update as soon as possible!

**Comment by TWSSYesterday** [comment]
PermissionsEx error :)

**Comment by V0rki** [comment]
Vous n'auriez pas une idée de comment réglée ce problème ?

**Comment by TWSSYesterday** [comment]
https://github.com/PEXPlugins/PermissionsEx/issues/new?title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+Detailed+Information+%23%23%23%0A%0A%5BIs+available+here%5D%28https%3A%2F%2Fgist.github.com%2F9b0d37dabf5b949bb815%29%0A
