### ISSUE TITLE
Unsafe login area after world player was in was deleted.

### ISSUE THREAD

**Issue by NobleStrike** [Multiverse/Multiverse-Core#1555]
Steps to trigger issue.
1. Put player in a world.
2. Have them log out.
3. Delete the world.
4. Have player log in.
5. Player can end up in a unsafe area or height since the world
they were in before was deleted.

I would like to see that if the plugin detects that the world the player is
trying to log into is missing then it runs a custom command like /spawn
so it prevents any issues when resetting a map. It can spawn the player out of worldboarder/worldgaurd entree area of my spawn world and they glitch, fall and die and they cant go back to get their stuff.

Im running the last build of Spigot 1.8

Im also running essentials 2.x which does keep track of the log out location but is typically overridden with the playerdata's logout location.

**Comment by NobleStrike** [comment]
Wait im using the last build of multiverse on Bukkit. I see you were removed from their website. Is there a place for a updated version of multiverse that im not aware of?

**Comment by TWSSYesterday** [comment]
Unable to reproduce on later builds.
