### ISSUE TITLE
Multiverse not working with per-world permissions

### ISSUE THREAD

**Issue by TGvoid** [Multiverse/Multiverse-Core#1558]
I am running a server with multiple worlds. I only want players to access plotworld (Alias: Creative) and world (Alias: Lobby). In groupmanager, when I add a global permission to access the creative server (multiverse.teleport.self.plotworld) and try to teleport by doing /mvtp creative, it does not work. Here's my permissions file for Essentials Group Manager:

# These groups only contain permission nodes.
#
# **** You can NOT add anything other than permission nodes ****
# **** This is NOT where you set up the groups which you give to users! ****
# **** goto groupmanager/worlds/worldname/groups.yml if you want to set the actual groups! ****
#
# These collections are to be inherited in your different worlds groups.yml's
# They can also be added as one of a users subgroups, but NOT as a primary group.
# These collections are available to ALL group and user yml's.
#
# Add to and customize these groups to fit your needs.

groups:

# Permission nodes for GroupManager
# by ElgarL, snowleo, continued from gabrielcouto's original
# http://wiki.ess3.net

  g:groupmanager_default:
    permissions:
    - groupmanager.notify.self

  g:groupmanager_moderator:
    permissions:
    - groupmanager.listgroups
    - groupmanager.mandemote
    - groupmanager.manpromote
    - groupmanager.manselect
    - groupmanager.manuadd
    - groupmanager.manudel
    - groupmanager.manwhois
    - groupmanager.notify.other

  g:groupmanager_admin:
    permissions:
    - groupmanager.mantogglevalidate
    - groupmanager.mansave
    - groupmanager.mangcheckp
    - groupmanager.manglistp
    - groupmanager.manucheckp
    - groupmanager.manulistp

# Permission nodes for CraftBukkit
# by many devs and contributors
# http://dl.bukkit.org/

  g:bukkit_default:
    permissions:
    - bukkit.broadcast.user
    - -bukkit.command.plugins

  g:bukkit_moderator:
    permissions:
    - bukkit.command.ban
    - bukkit.command.ban.ip
    - bukkit.command.ban.player
    - bukkit.command.gamemode
    - bukkit.command.kick
    - bukkit.command.unban
    - bukkit.command.unban.ip
    - bukkit.command.unban.player

  g:bukkit_admin:
    permissions:
    - bukkit.broadcast
    - bukkit.broadcast.admin
    - bukkit.command.give
    - bukkit.command.help
    - bukkit.command.kill
    - bukkit.command.list
    - bukkit.command.me
    - -bukkit.command.op
    - -bukkit.command.op.give
    - -bukkit.command.op.take
    - bukkit.command.plugins
    - bukkit.command.reload
    - bukkit.command.save
    - bukkit.command.save.disable
    - bukkit.command.save.enable
    - bukkit.command.save.perform
    - bukkit.command.say
    - bukkit.command.stop
    - bukkit.command.teleport
    - bukkit.command.tell
    - bukkit.command.time
    - bukkit.command.time.add
    - bukkit.command.time.set
    - bukkit.command.version
    - bukkit.command.whitelist
    - bukkit.command.whitelist.add
    - bukkit.command.whitelist.disable
    - bukkit.command.whitelist.enable
    - bukkit.command.whitelist.list
    - bukkit.command.whitelist.reload
    - bukkit.command.whitelist.remove

# Permission nodes for Essentials
# by ementalo, snowleo, and KHobbits
# http://dev.bukkit.org/server-mods/essentials/

  g:essentials_default:
    permissions:
    - essentials.help
    - essentials.helpop
    - essentials.list
    - essentials.motd
    - essentials.rules
    - essentials.spawn
    - essentials.jail.allow.help
    - essentials.jail.allow.helpop
    - essentials.jail.allow.rules
    - multiverse.portal.access.ctolobby

  g:essentials_builder:
    permissions:
    - essentials.afk
    - essentials.afk.auto
    - essentials.chat.question
    - essentials.ignore
    - essentials.mail
    - essentials.mail.send
    - essentials.msg 
    - essentials.ping
    - essentials.warp
    - essentials.realname
    - plotme.use
    - plotme.use.add
    - plotme.use.remove
    - plotme.limit.5
    - automessage.recieve.default
    - multiverse.teleport.self.plotworld
    - multiverse.teleport.self.world

  g:vip:
    permissions:
    - essentials.me
    - essentials.nick
    - plotme.limit.10

  g:super:
   permissions:
    - essentials.hat
    - essentials.chat.color
    - plotme.limit.15

  g:mega:
    permissions:
    - essentials.msg.color
    - essentials.msg.format
    - essentials.chat.format
    - plotme.limit.20

  g:helper:
    permissions:
    - essentials.mute
    - essentials.mute.notify
    - essentials.shout
    - essentials.tempban.exempt
    - essentials.tempban
    - essentials.tempban.offline
    - plotme.limit.30
    - plotme.use.protect
    - sg.arena.forcestart
    - sg.arena.enable
    - sg.arena.disable
    - sg.arena.nocmdblock
    - essentials.socialspy
    - essentials.invsee

  g:essentials_moderator:
    permissions:
    - -essentials.spawner.enderdragon
    - essentials.afk.kickexempt
    - essentials.ban
    - essentials.ban.notify
    - essentials.banip
    - essentials.book.title
    - essentials.book.others
    - essentials.broadcast
    - essentials.chat.url
    - essentials.chat.magic
    - essentials.clearinventory
    - essentials.delwarp
    - essentials.eco.loan
    - essentials.exp.others
    - essentials.ext
    - essentials.fly
    - essentials.fly.safelogin
    - essentials.getpos
    - essentials.getpos.others
    - essentials.helpop.receive
    - essentials.home.others
    - essentials.invsee
    - essentials.jails
    - essentials.jump
    - essentials.kick
    - essentials.kick.notify
    - essentials.kill
    - essentials.kits.*
    - essentials.msg.magic
    - essentials.nick.color
    - essentials.nick.others
    - essentials.seen.banreason
    - essentials.seen.extra
    - essentials.setwarp
    - essentials.signs.create.*
    - essentials.signs.break.*
    - essentials.spawner
    - essentials.spawner.*
    - essentials.thunder
    - essentials.time
    - essentials.time.set
    - essentials.protect.alerts
    - essentials.protect.admin
    - essentials.protect.ownerinfo
    - essentials.ptime
    - essentials.ptime.others
    - essentials.togglejail
    - essentials.top
    - essentials.tp
    - essentials.tp.others
    - essentials.tphere
    - essentials.tppos
    - essentials.tptoggle
    - essentials.unban
    - essentials.unbanip
    - essentials.vanish
    - essentials.vanish.effect
    - essentials.warps.*
    - essentials.weather
    - essentials.whois
    - essentials.workbench
    - essentials.world
    - essentials.worlds.*
    - essentials.jail.allow.jails
    - essentials.jail.allow.togglejail
    - plotme.limit.*

  g:essentials_admin:
    permissions:
    - -essentials.backup
    - -essentials.essentials
    - -essentials.setspawn
    - -essentials.reloadall
    - -essentials.plugin
    - essentials.*
    - sg.arena.create
    - sg.arena.setspawn
    - sg.arena.resetspawns
    - sg.arena.delete
    - sg.lobby.set

# Permission nodes for Towny by ElgarL
# http://dev.bukkit.org/server-mods/towny-advanced/

  g:towny_default:
    permissions:
    - towny.chat.local

  g:towny_builder:
    permissions:
    - towny.wild.build.6
    - towny.wild.destroy.6
    - towny.wild.destroy.14
    - towny.wild.destroy.15
    - towny.wild.destroy.16
    - towny.wild.build.17
    - towny.wild.destroy.17
    - towny.wild.destroy.18
    - towny.wild.destroy.21
    - towny.wild.destroy.31
    - towny.wild.destroy.37
    - towny.wild.destroy.38
    - towny.wild.destroy.39
    - towny.wild.destroy.40
    - towny.wild.destroy.50
    - towny.wild.destroy.56
    - towny.wild.destroy.73
    - towny.wild.destroy.74
    - towny.wild.destroy.78
    - towny.wild.destroy.81
    - towny.wild.destroy.82
    - towny.wild.destroy.83
    - towny.wild.destroy.86
    - towny.wild.destroy.103
    - towny.wild.destroy.106
    - towny.wild.destroy.111
    - towny.wild.destroy.115

  g:towny_moderator:
    permissions:
    - towny.chat.mod
    - towny.wild.switch.64
    - towny.wild.build.83
    - towny.wild.build.86
    - towny.wild.build.103
    - towny.wild.build.111
    - towny.wild.build.115

  g:towny_admin:
    permissions:
    - towny.admin
    - -towny.wild.destroy.119
    - -towny.wild.destroy.120
    - towny.chat.admin

# Permission nodes for VanishNoPacket by mbaxter
# http://dev.bukkit.org/server-mods/vanish/

  g:vanish_moderator:
    permissions:
    - -vanish.*
    - vanish.vanish
    - vanish.smokin
    - vanish.nofollow
    - vanish.nopickup
    - vanish.preventincomingdamage
    - vanish.hooks.dynmap.alwayshidden
    - vanish.hooks.essentials.hide

  g:vanish_admin:
    permissions:
    - vanish.silentjoin
    - vanish.silentquit
    - vanish.silentchests

Builder is the default rank, not Default. Thanks for helping!

**Comment by TGvoid** [comment]
This is a screenshot of what happens in game: 
![2015-03-13_12 07 20](https://cloud.githubusercontent.com/assets/11463596/6643372/a9e77db8-c979-11e4-82af-c1e7afaf1d89.png)

**Comment by TWSSYesterday** [comment]
Group Manager is well known to not work well with multiple worlds. That being said, I've only seen one multiverse permission in your file, and that was for portals.
Please pastebin the Group Manager file if you still need help with this.

**Comment by chillerkraft** [comment]
im using pex and im having this same issue
if i have a world named Overworld and add multiverse.teleport.self.Overworld it doesnt work, it doesnt allow any type of teleportation. i need to use enforce access with this, which works for now but id still like to figure out how to get those perms to work.i just please help.

**Comment by TGvoid** [comment]
Is there a permissions plugin that has MySQL, is compatible with 1.8, and compatible with Multiverse?

**Comment by ryantheleach** [comment]
I've used zPermissions successfully.

**Comment by chillerkraft** [comment]
it's insane how little care for support there is for this plugin
vomits.
