### ISSUE TITLE
World.cfg keeps resetting - Can't set difficulty

### ISSUE THREAD

**Issue by Leaderproxima** [Multiverse/Multiverse-Core#1559]
All the worlds on my server have been set to default by mv automatically. We didn't want it to do that. So we changed every "PEACEFUL" in the config to "NORMAL" and then reloaded the plugin. When we checked it had reset itself to peaceful again.

Using both mvm and mv in game to set difficulty doesnt work whether we do it in the world or not.

Due to this we have no mob spawns at all. Upon disabling mv all mobs started spawning again.

**Comment by TWSSYesterday** [comment]
Stop the server, and start it up again after changing settings via file.

**Comment by Leaderproxima** [comment]
I've tried that. As soon as anyone goes into a world that isn't the overworld all of the worlds reset to peaceful in the config again and all mobs disappear.

**Comment by TWSSYesterday** [comment]
Use the command on the latest version, it will fix this issue.
