### ISSUE TITLE
cant get portal search radius or scale working

### ISSUE THREAD

**Issue by chillerkraft** [Multiverse/Multiverse-Core#1563]
i don't know what to do or say exactly about this issue
i want to reduce the portal search radius, and i'm trying to in the mv config but it's not changing anything. i have my skyworld attached to my netherworld, and the nether world has a 1.0 scale
please help? let me know what more info you need

**Comment by TWSSYesterday** [comment]
Is this issue still occurring?

**Comment by Jadiction** [comment]
Closing ticket due to lack of information (and no response in a reasonable time). Please open a new ticket with more valid information if this issue is still occurring in the latest versions.
