### ISSUE TITLE
how to set a spawnpoint? 

### ISSUE THREAD

**Issue by TheJuanGaymerMC** [Multiverse/Multiverse-Core#1564]
im dead in pvp and respawn in world please helpme

**Comment by TWSSYesterday** [comment]
Use /mv setspawn when in the world and at the respawnpoint. By default, essentials will take priority of this; edit the config.yml for essentials. Look for priority, it's near the bottom :)

**Comment by TheJuanGaymerMC** [comment]
very good thanks bro :)
