### ISSUE TITLE
my console is spammed )::::

### ISSUE THREAD

**Issue by moldavid** [Multiverse/Multiverse-Core#1565]
![image](https://cloud.githubusercontent.com/assets/11990565/7268531/a7157f98-e8ca-11e4-8a95-7a6cbe8fd5b2.png)
when someone break a block in a multiverse-core is multiverse core spamming my console ): but it is only in a multiverse-core world

**Comment by ryantheleach** [comment]
Where does is say this is a multiverse problem? looks like xnohack to me.
