### ISSUE TITLE
Getting this error with Spigot 1.8.3?

### ISSUE THREAD

**Issue by Vidsify** [Multiverse/Multiverse-Core#1568]
http://pastebin.com/s4Ns2stP

**Comment by TWSSYesterday** [comment]
Re download the file from Bukkit Dev, Multiverse Inventories isn't loading because Multiverse Core isn't loading.

**Comment by Vidsify** [comment]
What Version 2.5-b691 (beta). If so that's the version I'm using

**Comment by TWSSYesterday** [comment]
Re download the file :)
