### ISSUE TITLE
Is there a way to change the position of the chat prefix?

### ISSUE THREAD

**Issue by danbovey** [Multiverse/Multiverse-Core#1569]
I have my `prefixchat` config enabled with the default `prefixchatformat` but unfortunately the world alias appears in between the chat message as `[{group}][{world alias}]{player}: {message}`.

Is there a way to change the priority/position so that the world alias appears at the start of the chat message? I'd like to use the Multiverse prefix because it supports colours and aliases.

**Comment by TWSSYesterday** [comment]
Not via multiverse as it's a prefix, Essentials Chat has a feature where you can position things in chat though.

**Comment by danbovey** [comment]
In hindsight, this was a stupid easy issue to waste your time with. The focus was on formatting the chat when the more important issue for me was definitely the use of world aliases. I found this [closed issue](https://github.com/Multiverse/Multiverse-Core/issues/1238) which suggests that the world alias should be passed through to the chat plugin. To quote the original commentor...

>...is this something that can be looked at?
