### ISSUE TITLE
my worlds won't work

### ISSUE THREAD

**Issue by ccreep** [Multiverse/Multiverse-Core#1571]
Hello i am have just upgraded my server to 1.8.3 spigot and my multiverse core won't let me import/load my worlds.

Heres my startup log: http://pastebin.com/CaPLCQfb

**Comment by TWSSYesterday** [comment]
You have corrupt worlds, the log suggests you use chunkster :)

**Comment by ccreep** [comment]
where do i get it and how do i use it?

**Comment by TWSSYesterday** [comment]
https://www.beastnode.com/portal/knowledgebase/37/Running-Chunkster-to-Fix-Corrupt-Worlds.html
https://www.youtube.com/watch?v=l39UMtbuK2I

**Comment by ccreep** [comment]
i still don't understand how to use it since i am running a multicraft server

**Comment by TWSSYesterday** [comment]
They're tutorials on how to fix the issue

**Comment by ccreep** [comment]
i fixed the issue by putting bukkit 1.8 instead of spigot thats what is causing them to break 1.8 bukkit works fine you may close this post now
