### ISSUE TITLE
Can't create portals

### ISSUE THREAD

**Issue by TWKeyboard** [Multiverse/Multiverse-Core#1572]
I have world edit installed, when ever I try to make a portal I get a "An internal error has occurred while attempting to preform this command" This is the errors in the console when that happens, but I don't really know what do to:

15.05 10:52:51 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.8.1-20150304a.jar:git-Bukkit-33d5de3]
15.05 10:52:51 [Server] INFO at com.onarandombox.MultiversePortals.MultiversePortals.onCommand(MultiversePortals.java:336) ~[?:?]
15.05 10:52:51 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:71) ~[?:?]
15.05 10:52:51 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
15.05 10:52:51 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
15.05 10:52:51 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
15.05 10:52:51 [Server] INFO at com.onarandombox.MultiversePortals.commands.CreateCommand.runCommand(CreateCommand.java:56) ~[?:?]
15.05 10:52:51 [Server] INFO at com.onarandombox.MultiversePortals.PortalPlayerSession.getSelectedRegion(PortalPlayerSession.java:168) ~[?:?]
15.05 10:52:51 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getSelectionWorld()Lcom/sk89q/worldedit/LocalWorld;
15.05 10:52:51 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
15.05 10:52:51 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [craftbukkit-1.8.1-20150304a.jar:git-Bukkit-33d5de3]
15.05 10:52:51 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [craftbukkit-1.8.1-20150304a.jar:git-Bukkit-33d5de3]
15.05 10:52:51 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit-1.8.1-20150304a.jar:git-Bukkit-33d5de3]
15.05 10:52:51 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656) [craftbukkit-1.8.1-20150304a.jar:git-Bukkit-33d5de3]
15.05 10:52:51 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_65]
15.05 10:52:51 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_65]
15.05 10:52:51 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit-1.8.1-20150304a.jar:git-Bukkit-33d5de3]
15.05 10:52:51 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.8.1-20150304a.jar:git-Bukkit-33d5de3]
15.05 10:52:51 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.8.1-20150304a.jar:git-Bukkit-33d5de3]
15.05 10:52:51 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:919) [craftbukkit-1.8.1-20150304a.jar:git-Bukkit-33d5de3]
15.05 10:52:51 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1058) [craftbukkit-1.8.1-20150304a.jar:git-Bukkit-33d5de3]
15.05 10:52:51 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:625) ~[craftbukkit-1.8.1-20150304a.jar:git-Bukkit-33d5de3]
15.05 10:52:51 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.8.1-20150304a.jar:git-Bukkit-33d5de3]
15.05 10:52:51 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.8.1-20150304a.jar:git-Bukkit-33d5de3]
15.05 10:52:51 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mvp' in plugin Multiverse-Portals v2.5-b699

Anyone know what I'm doing wrong?

**Comment by TWSSYesterday** [comment]
1: Pastebin error log.
2: Get entire log, not just part of the stack trace:
3: Versions of WorldEdit, Multiverse Core, and Spigot/Craftbukkit?
You're using WE 6.x, use https://github.com/dmulloy2/Multiverse-Portals/releases/download/2.5-1.8/Multiverse-Portals.jar
