### ISSUE TITLE
How to disable world loading?

### ISSUE THREAD

**Issue by Zilacon** [Multiverse/Multiverse-Core#1573]
I am using Multiverse on a Cauldron server. Its the latest version of multiverse.

My issue is i want to disable the modded worlds until a player joins them through the mods method of going into the world. So its unloaded until then.

But even if i set autoload to false it still loads the world and keeps it loaded. Basically Multiverse is stopping the forgemodloader from unloading unused worlds.

Without multiverse ForgeModLoader would automatically unload all worlds that are not in use. I want to enable that again.

Server: KCauldron 1.7.10 Build 63
Multiverse: 2.5-b691 (beta)

**Comment by TWSSYesterday** [comment]
You can unload specific worlds, if forge assumes that you're meaning to unload all worlds, it's a problem you should take up with the developers of kCauldron :)

**Comment by Zilacon** [comment]
But i would need to do "/mv unload world" every time i start the server to do that right?

**Comment by TWSSYesterday** [comment]
No, it should be a toggle in the worlds.yml

**Comment by Zilacon** [comment]
See there is my problem. It is set to Autoload: 'false' for all of those worlds, yet they are loaded anyways and never get unloaded.

**Comment by TWSSYesterday** [comment]
And you're using the latest version of Multiverse?
Does an error occur on startup?

**Comment by Zilacon** [comment]
If multiverse does not have control of the world, like its not listed in worlds.yml the worlds load on start up but then ForgeModLoader unloads all of them after 15 seconds.

Yes i am using the latest version from bukkit.org

There are no errors.

**Comment by TWSSYesterday** [comment]
You can just remove it from the worlds.yml? Thatw ay it's not imported

**Comment by Zilacon** [comment]
I would but then it just teleports people out of the dimensions...
People were trying to access the SPECTRE dimension and it kept teleporting them back out until i imported it into multiverse. Then they were able to play on it.

**Comment by TWSSYesterday** [comment]
Deny access to the world?

**Comment by Zilacon** [comment]
Then how are they supposed to play on the worlds...

**Comment by TWSSYesterday** [comment]
Why did you want it unloaded?

**Comment by Zilacon** [comment]
To reduce stress on the server from having 42 worlds loaded...

**Comment by TWSSYesterday** [comment]
Ahh, so you want it loaded at one point?

**Comment by Zilacon** [comment]
Yes but unloaded when not in use by any players.

**Comment by TWSSYesterday** [comment]
You can set world limits with multiverse so you can edit the limit when more people on the server?

**Comment by Zilacon** [comment]
-_-
Why cant you guys just make multiverse act like Multiworld? I had no problems with that until i switched to 1.7.10 then i was forced to go with multiverse. Multiworld unloaded everything if it wasnt in use and even worked side by side with Forge.

MY PROBLEM IS: The modpack has over 40 worlds, and then my own custom 5 overworlds. When the server starts all of these worlds are loaded but multiverse keeps half of them loaded up even when no one is on them. I want it to unload ALL of the worlds if no one is using them or autoload: 'false' if its set to false that should mean it wont load the worlds up period when the server starts. But it does. And it keeps it loaded forever.

Forge unloads worlds for a reason, its a memory problem. Having 20,30,40 worlds loaded at the same time is like taking an axe to your servers ram.

When i didn't have multiverse installed my modded server of 200 mods used 1.2GB on start up. With multiverse it uses 2.8GB on start up. You do the math, 1.6GB since i put multiverse into my server because it keeps everything loaded and loads everything.

This is on a empty server too, no players online.

I am not trying to be rude but Multiverse has a history of memory leaks with forge servers. That is the reason why i stayed away from it for my 1.5.2/1.6.4 servers.

**Comment by TWSSYesterday** [comment]
So your issue is the autoload: 'false' not working?

**Comment by Zilacon** [comment]
Correct it loads everything and never unloads them. And if multiverse does not have the world imported they cant go to the world through the mod. Like if Twilight Forest has a portal that goes to DIM7 but DIM7 is not on multiverse it will pop you right back to the world you jumped through the portal in.

**Comment by TWSSYesterday** [comment]
Could I have your config.yml, worlds.yml and startup log please? Obviously pastes of them would be much more appreciated :)

**Comment by Zilacon** [comment]
Ok ive tried everything nothing works.
I dont want multiverse controlling ANY world that i dont put in the config or create via command. Everytime i remove it from the config or do mv remove world it adds the worlds right back in the config on start up.

And giving you a config is pointless cause its literally defaults, only thing i change is the autoload='false' and that doesn't work.

I want to set my 4 overworlds up in multiverse and have it ignore everything else. I dont want it loading worlds, adding worlds into its config, adding options for worlds, nothing.

**Comment by TWSSYesterday** [comment]
Used /mvm set autoload false at all so the command sets it?

**Comment by Zilacon** [comment]
It says the worlds dont exist, and yet when i do mv list it shows all of them there.

**Comment by TWSSYesterday** [comment]
Can you try importing it using the command?

**Comment by Zilacon** [comment]
Im done playing this idiot game with you.

http://prntscr.com/7bld7c

Stop treating your users like they are stupid and your plugin is some work of art. Ill get a programmer to fix multiworld for me instead of using this trash.

You force load every damn world and you keep them loaded until the server shuts down. You sit here acting like its me that's the problem and not you when its the other way around. I have been running servers for 5 years, i know when im making mistakes and when im not. Multiworld never loaded any world it was not setup to load, yours forces itself onto everything and you make it sound like it doesn't.

**Comment by TWSSYesterday** [comment]
I'm not treating you like an idiot, the command based system is known to work when the file editing version is not. I'm not acting like it's you who the problem is, if it has shown itself like that; it was not my intention so I'm sorry.
This seems to be an issue only occurring on KCauldron, and not other versions too.

**Comment by dumptruckman** [comment]
FWIW, I'm pretty sure this is what you wanted https://github.com/Multiverse/Multiverse-Core/wiki/World-properties#memory

Technically, in Bukkit terms, the world is still loaded but none of the chunks are.

**Comment by Zilacon** [comment]
No i want the world completely unloaded. Multiworld works properly and unloads worlds not in use and im sticking with that.

I love how many developers who ive come across blame others for their own problems. Much like MD-5 who claims not able to connect to cauldron servers is not a bungee issue, when YIVE fixed bungee and has a fixed download on his website that works perfectly.

**Comment by dumptruckman** [comment]
I'm not sure how you would achieve what you want with Bukkit without the server hanging every time a player teleports to an unloaded world. That kind of operation might work fairly well in some implementations but you'd definitely end up with the server hanging with CraftBukkit for instance.

**Comment by dumptruckman** [comment]
I'm gonna check out how Multiworld does it. Are there are particular settings involved in getting this desired behavior with that plugin?

**Comment by Zilacon** [comment]
We have not had any such issue, once the player enters whatever portal from whatever mod they choose the world loads up and they enter without issues.

**Comment by dumptruckman** [comment]
Are you running the server on an SSD?

**Comment by Zilacon** [comment]
Nope.

**Comment by chezpaul** [comment]
Zillion needs to learn how to be patient. Wow.
Anyway, I'm having the same problem as he was. On a KCauldron server.
There are two worlds I want gone, totally gone and /mv remove or /mv delete doesn't work.
I edited the autoload to false and they were still loaded but in gray when you /mv list
So I'm halfway there it seems.
I reset them to autoload true and they are still gray... oops...
I'll try the command line to see what happens.
I'm in the IRC right now waiting for an answer... we'll see.

**Comment by Zilacon** [comment]
And @chezpaul needs to learn how to spell peoples names correctly and actually look at time stamps for the replies. I reported the issue on May 23rd. This went on until June 7th without a solution and 5 months later there still is no solution to this problem.

Patience has to do with minutes to hours in dealing with something. Not months.

**Comment by chezpaul** [comment]
You are just proving my point.
He gave you answers that same day. You didn't follow his instructions and got mad right away.
That's why you never got helped.
BTW, I'm done answering your responses. No need to spam this thread. Thanks.  ;-)

**Comment by Zilacon** [comment]
@chezpaul His instructions were worse than a tech support agent over the phone. He kept suggesting the same thing over and over when i explained to him already everything he is telling me to do has already be done. All you are doing is throwing fuel onto a fire that has already burned out.

You are being a disrespectful troll that thinks hes important cause he can insult someone on the internet. Kudos internet tough guy, you can act all bad on the interwebz. You must be so proud of yourself.

**Comment by dumptruckman** [comment]
Keepspawninmemory:false is the only thing we can do as a plugin to influence this issue. Multiverse requests the server to load a world and then requests whether or not to keep the spawn in memory. After that we have no control over whether the world is "loaded" or not. There is confusion in the initial response because as far as a bukkit plugin is concerned there are only 2 world states: loaded or unloaded. Loading in this case is telling the server the world exists and unloading would be telling the server the world doesn't exist (meaning no teleports possible because it is not a valid world anymore). 
The reality is there are more than 2 states. World exists or not and world is loaded or not. Bukkit plugins are only able to deal with existence, not load state.
