### ISSUE TITLE
Portals error

### ISSUE THREAD

**Issue by MrPesee** [Multiverse/Multiverse-Core#1574]
Hello.
Whe i create a portal i have this error:
http://pastebin.com/mWCEmPyf

**Comment by TWSSYesterday** [comment]
use WorldEdit 5.x or Update Multiverse Portals to https://github.com/dmulloy2/Multiverse-Portals/releases/download/2.5-1.8/Multiverse-Portals.jar

**Comment by MrPesee** [comment]
Thanks, now itsokey, do you know what i have to do to modifycate the destination? i have done /mvp modify dest e:Survival:-41,96,255[178:2] with the portal selected and it says that Multiverse could not find the destination to -41,96,255[178:2]

**Comment by MrPesee** [comment]
Its okey, don it,Thanks for your time
