### ISSUE TITLE
Worlds delete themselves then having to import back! Please help!!

### ISSUE THREAD

**Issue by Sn0wi** [Multiverse/Multiverse-Core#1578]
Hey, I run a small server with a couple of worlds (World, World_nether, parkour, minigames, lobby and plotworld) and whenever i log off for a few hours or restart server, the worlds parkour, minigames, plotworld and lobby delete themselves which leaves me having to import them except lobby because i have a lobby plugin but when i try and import lobby back it says internal error occured.
Please help this is really annoying!

**Comment by TWSSYesterday** [comment]
You need to remove it from the worlds.yml.

**Comment by Sn0wi** [comment]
That solved nothing apart from now permanently deleting my lobby world, internal error trying to import it and the lobby plugin can't take me there anymore...

**Comment by TWSSYesterday** [comment]
The worlds will come back if they're in the worlds.yml or is the main world.
Error upon using import command? Versions of server software and multiverse?

**Comment by dumptruckman** [comment]
Always make backups before just deleting files. I would suggest shutting down your server and backing up the MV-Core plugin folder. Then delete that folder. Then restart your server. It will automatically import your default worlds (the ones specified in server.properties). Next use the `mv import` command to import all your additional worlds.

**Comment by Sn0wi** [comment]
Thanks everyone, I'm pretty sure everything is fine now
