### ISSUE TITLE
Valid location with bukkit location is broken.

### ISSUE THREAD

**Issue by tuskiomi** [Multiverse/Multiverse-Core#1579]
In Exact destination, use else if not just if.

**Comment by dumptruckman** [comment]
Please submit a pull request to fix this.

**Comment by dumptruckman** [comment]
I see that you submitted a pull request. Please describe in the pull request or issue exactly what this fixes. What is the problem that occurs without this change? Be descriptive.

**Comment by tuskiomi** [comment]
done and done:  https://github.com/Multiverse/Multiverse-Core/pull/1580

**Comment by tuskiomi** [comment]
You see, in the Class Exact location, You have the method setExactLocation(Location location).
the contents now are as follows:   
```      
       if (location != null) {
            this.location = location;
            this.isValid = true;
        }
        this.isValid = false;
```
because the statement this.isValid = false is outside the if block, there is no wway to set a valid location  with this method. 
I added an else{} branch after the if containing the this.isValid statement. This makes the location setting once again possible via Bukkit locations.

**Comment by tuskiomi** [comment]
updated pull request

**Comment by dumptruckman** [comment]
I understand the code itself. I'm wanting to know what isn't actually working right in the plugin.

**Comment by tuskiomi** [comment]
"there is no way to set a valid location with this method."

basically the entire method is useless as of now,

**Comment by dumptruckman** [comment]
I disagree. If the location isn't null, it sets the location to whatever you provided and specifies that the location is valid.

**Comment by dumptruckman** [comment]
Even if the method is useless, what is the BUG this is causing in the plugin?

**Comment by tuskiomi** [comment]
then, it sets location.isValid to false , no matter the parameter. whenever you call this method, the boolean variable isValid will always turn to false.

**Comment by dumptruckman** [comment]
Ah, I was missing the fact that isValid = false was already there. In any case, what is the problem this is causing in the plugin?

**Comment by tuskiomi** [comment]
It's more the API than the plugin, I was developing a plugin that allows players to built multiverse portals the same way nether portals are built, and because this method is broken I cannot set a valid location for the portal.

**Comment by dumptruckman** [comment]
Makes sense now. I didn't merge your pull for formatting issues but I credited you in the commit message.
