### ISSUE TITLE
Nether Portal Problem.

### ISSUE THREAD

**Issue by Terabyte-2** [Multiverse/Multiverse-Core#1582]
I'm not quite sure why this is happening as of now, but for some reasons the nether portals on my server decide to randomly teleport all players to either the nether, or the end. This started happening when I restored one of my old backups, which had no problems as of the creation. This doesn't just happen on a set of worlds, but EVERY world. If I delete the end, the portal just teleports you to itself. I do use multiverse-netherportals and It is completely up-to-date, as of all of my plugins. I've even tried the ./mvnp command to manually link my nether world to my survival world. I am usually the one to fix these kinds of things, but this has left me dumbfounded. This is the first time I've encountered a problem that I cannot find a fix to.

I don't know exactly what information you might need, so just ask if you might need it. Perhaps you could find something that I am missing, unless this is a problem on your end. Any assistance would be appreciated. Thanks!

Here's just a list of plugins and stuff to take into consideration:
I'm using the 1.8.6 Spigot build generated from BuildTools using the --rev BuildTools.jar 1.8.6 command.
I'm using Essentials, EssentialsChat, and EssentialsSpawn.
I use Multiverse-Core, Multiverse-NetherPortals, and Multiverse-Inventories.
All of my plugins are up-to-date. (100% Sure)

Here is a pastebin of my latest log: http://pastebin.com/SPPRWj0P

**Comment by TWSSYesterday** [comment]
Cannot replicate on purpose, that being said I know sometimes this has happened to friends.
