### ISSUE TITLE
mv creates many dims

### ISSUE THREAD

**Issue by simucad** [Multiverse/Multiverse-Core#1585]
to our prob: we use nether DIM-1 and end DIM-112 or we tried DIM1. then we now look with opis or in the worlds folder he makes 4 new dims -DIMxxxwx.  In opis DIM-1 and DIM-112 doesnt exist.
Can anyone explain me the system.

thanks and greets

**Comment by TWSSYesterday** [comment]
Still occurring?

**Comment by FernFerret** [comment]
Closing due to issue age (sorry). We slacked off on our issues. If you're still having this issue, please read up on [submitting a bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and post the details with a more recent server/multiverse version. Sorry again!
