### ISSUE TITLE
Problem with Importing worlds!

### ISSUE THREAD

**Issue by kungfalco** [Multiverse/Multiverse-Core#1587]
Im trying to import a world that I named Mines.

Error message from the console:
03.07 09:04:30 [Server] WARN Task #250 for MineResetLitePlus v1.5.11 generated an exception
03.07 09:04:17 [Server] WARN at java.lang.Thread.run(Thread.java:745)
03.07 09:04:17 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
03.07 09:04:17 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
03.07 09:04:17 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
03.07 09:04:17 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718)
03.07 09:04:17 [Server] WARN at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19)
03.07 09:04:17 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:262)
03.07 09:04:17 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
03.07 09:04:17 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
03.07 09:04:17 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
03.07 09:04:17 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
03.07 09:04:17 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970)
03.07 09:04:17 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135)
03.07 09:04:17 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642)
03.07 09:04:17 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
03.07 09:04:17 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
03.07 09:04:17 [Server] WARN at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897)
03.07 09:04:17 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
03.07 09:04:17 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
03.07 09:04:17 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
03.07 09:04:17 [Server] WARN at com.onarandombox.MultiverseCore.commands.ImportCommand.runCommand(ImportCommand.java:147)
03.07 09:04:17 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:229)
03.07 09:04:17 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:427)
03.07 09:04:17 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:56)
03.07 09:04:17 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:64)
03.07 09:04:17 [Server] WARN java.lang.NullPointerException

What should I do?

**Comment by TWSSYesterday** [comment]
https://www.spigotmc.org/resources/mineresetlite.5773/ try using that version, any additional info you could provide would be useful too :)
