### ISSUE TITLE
Generator Problems Spigot 1.8.3

### ISSUE THREAD

**Issue by logicalPolaris** [Multiverse/Multiverse-Core#1588]
I'm having troubles where every time I restart my server, all worlds using generators start generating normal terrain. It's with all my generators, including PlotMe and PlotSquared.

If I import a world with -g (generator), it generates fine, but after a server restart, it breaks.

If you have any questions, please ask away.

**Comment by TWSSYesterday** [comment]
Check your plot generator versions, someone had this issue beforehand and updating them fixed the issue.

**Comment by logicalPolaris** [comment]
I found out that the cause of it was a Jukebox plugin called "JukeLoop." Even though this makes so sense to me personally, removing it got rid of all the corruption. I'll open this back up if it comes back after removing it.

**Comment by TWSSYesterday** [comment]
Okay, thanks for your time :)
