### ISSUE TITLE
Automatic teleport!!

### ISSUE THREAD

**Issue by Jamesthebest77** [Multiverse/Multiverse-Core#1591]
I have several worlds in my minecraft multiverse-core...and sometimes i just teleport to a random world...just like that. no commands or anything...Whats wrong Can you hel ME!!

**Comment by TWSSYesterday** [comment]
This isn't a direct issue with Multiverse, what other plugins do you have?

**Comment by Jamesthebest77** [comment]
I have a lot...but how do i fix this? I will open a Rôle Pley server soon and I don't want poeple to teleport just like that!!??

**Comment by TWSSYesterday** [comment]
I want to help you, but it's one of your plugins so you could disable them one by one until it stops happening and delete the bad plugin, or I can help you find the plugin that does this, the name is nearly always a pointer.

**Comment by TWSSYesterday** [comment]
Update @Jamesthebest77

**Comment by FernFerret** [comment]
Closing with no response.
