### ISSUE TITLE
Could not pass event PlayerTeleportEvent

### ISSUE THREAD

**Issue by FloxRoxX** [Multiverse/Multiverse-Core#1594]
I just write this because i dont know how to handle this:
We recently get this output when a player teleports from a non multiverse registered world to another one.

http://pastebin.com/Bj1DVgzc

The teleport works but it leaves this Exception behind. We have a Cauldron Server with Multiverse running and some mods like galacticraft and so on. They register their own dimensions that are not recognized by multiverse. We use Multiverse-Core-2.4 and cauldron-1.7.10-2.1403.1.54-server.

We dont use the multiverse opposite (multiworld for forge) because its crappy with world handling and has too less features.

**Comment by TWSSYesterday** [comment]
Update Multiverse, you should be fine, even on the cauldron, and then try to reproduce.

**Comment by TWSSYesterday** [comment]
@FloxRoxX is the issue still persisting?

**Comment by TWSSYesterday** [comment]
Closed due to inactivity, try using latest builds of Thermos, the project has potential and is updated a lot more frequently.
