### ISSUE TITLE
Non-Default worlds are inaccessible...  

### ISSUE THREAD

**Issue by DanPixely** [Multiverse/Multiverse-Core#1595]
Recently, all of the Multiverse worlds located on my server, not including world, world_nether, and world_the_end, have become inaccessible. The files to the worlds still appear and contain every thing including the data, playerdata, and whatnot, but they don't appear when you type '/mv list'. Additionally, I use GGserver's server managing panel. Not sure if that has to do with anything...

**Comment by TWSSYesterday** [comment]
Use latest versions of everything to see if the issue persists, then pastebin your log file here.

**Comment by DanPixely** [comment]
By everything what do you mean? Plugins? I'm not much of a guru on this stuff,

**Comment by DanPixely** [comment]
Nevermind, problem resolved! If just had to re-import my worlds! But thanks for responding anyways, I appreciate it

**Comment by TWSSYesterday** [comment]
Sorry for not being specific enough with what I meant, I meant Multiverse plugin versions, and server version. Thanks for listing that as something that fixes it :)
