### ISSUE TITLE
How allow nether portals on survival mode ?

### ISSUE THREAD

**Issue by beltez** [Multiverse/Multiverse-Core#1596]
I have a world Factions and need allow nether portals for all, not with /mvp create. I tried to create on survival mode but dont work, not teleport me :(, do not want netherportals plugin, thanks.

HEELP!

**Comment by TWSSYesterday** [comment]
If your main world is "Factions" and you're only having Factions_nether and Factions_the_end; nether portals should be all working. If you have multiple survival worlds, you will need Multiverse Nether Portals.

**Comment by beltez** [comment]
I traid this, but when portal teleport u to nether, not create portal on nether, thanks friend.

**Comment by TWSSYesterday** [comment]
So it doesn't create a portal when you return from the world?

**Comment by beltez** [comment]
nope, why this ??

**Comment by dumptruckman** [comment]
Are you building the portals the standard Minecraft way? You should not have to use any commands for these portals.

**Comment by beltez** [comment]
this ---> https://www.youtube.com/watch?v=PVAFp0mKUnY&feature=youtu.be

**Comment by TWSSYesterday** [comment]
Seems to me like an unhealthy nether spawnpoint from the portal. Versions of everything?

**Comment by beltez** [comment]
Version server: 1.8.3
Multiverse-core-2.5
Multiverse-Inventories-2.5
Multiverse-NetherPortals-2.4
Multiverse-Portals // I dont know this xD

**Comment by TWSSYesterday** [comment]
When you do /ver Multiverse, what comes up, those are the "versions", I should have asked for the build numbers, for example 2.5-b691
http://ci.onarandombox.com/view/Multiverse/ lets you grab the files :)

**Comment by beltez** [comment]
http://i.imgur.com/JLewYNm.jpg :D

**Comment by TWSSYesterday** [comment]
No problem :)
