### ISSUE TITLE
Create a new World with Realistic World Gen and Multiverse but get every time the same World.

### ISSUE THREAD

**Issue by Dream-Master** [Multiverse/Multiverse-Core#1597]
I try to create a new World and using the RWG Mod

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1281910-teds-world-gen-mods-realistic-world-gen-alpha-1-3

https://github.com/Ted80-Minecraft-Mods/Realistic-World-Gen

I try to add different seeds but every world i generating looks like same. Maybe it using the Server seed and cant change.

I try Vanilla Mc and Biomes o plenty and get different worlds.

Did you know why this is happend that i can report this to RWG because I think it is a issue of this Mod.
Thanks in advance.

**Comment by TWSSYesterday** [comment]
It uses the type flag, have you set that? -t RWG

**Comment by Dream-Master** [comment]
yes i set the flag to rwg. try with different seed but all the same terrain. It generating RWG worlds but they looks same.

**Comment by lasercar** [comment]
I'm confused; isn't RWG (or RTG) a forge mod? and Multiverse is a bukkit plugin? How do you get them to work together?

**Comment by FernFerret** [comment]
Closing due to issue age (sorry). We slacked off on our issues. If you're still having this issue, please read up on [submitting a bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and post the details with a more recent server/multiverse version. Sorry again!
