### ISSUE TITLE
Error with generators

### ISSUE THREAD

**Issue by FraazT0** [Multiverse/Multiverse-Core#1598]
Every time I run a command related to generators (it doesn't matter which generator, it's every time the same thing). For example /mv gens says "An internal error occurred".
When I try to import a world with a generator it says the same thing but it prints some details on the console. I put them here: http://pastebin.com/9Q3S7CrH
How can I fix this problem? It's very annoying.
Note: I'm using Spigot 1.8.7

**Comment by TWSSYesterday** [comment]
Got the versions for everything?
Cannot reproduce on latest 1.8.8 Spigot and latest jenkins build of Multiverse. It seems like a simple update might fix this issue.

**Comment by FraazT0** [comment]
I'll try to update spigot, but mine Multiverse is the latest version.

**Comment by TWSSYesterday** [comment]
Is the Multiverse build from here: http://ci.onarandombox.com/job/Multiverse-Core/
A lot of people say they have the latest and we see them on version 2.4

**Comment by FraazT0** [comment]
Yes, the latest build from Jenkins.

**Comment by TWSSYesterday** [comment]
Can I have the startup log please (Pastebin preferably)

**Comment by FraazT0** [comment]
http://pastebin.com/RctcxAYN

**Comment by TWSSYesterday** [comment]
Your generators aren't loading. Not an issue directly to multiverse but I don't mind assisting you with them.

**Comment by FraazT0** [comment]
I don't know why, they worked fine for some time, then it started this problem.

**Comment by FraazT0** [comment]
Some idea on how to solve this?

**Comment by TWSSYesterday** [comment]
Update PlotMe and such to stable builds.

**Comment by FraazT0** [comment]
I don't have PlotMe.

**Comment by TWSSYesterday** [comment]
Other generators are having issues on the log it seems.

**Comment by dumptruckman** [comment]
Subterranea v1.7.10-R0.1 doesn't work on 1.8.8. IsleWorldGen v5.3 doesn't appear to work on 1.8.8. 

Additionally, while not related to generators you do have a bunch of errors related to not having certain plugins. You are missing: ActionBarAPI, ActionMessager, PlotMe, GroovyLoader, TitleManager, WelcomeTitle.

Something also may be wrong with Citizens. Judging by the state of the rest of your server it seems like you updated to a new server version without updating plugins that depend heavily on being run on the correct server version.
