### ISSUE TITLE
[Warn] [Multiverse-Core] Task #55437 for Multiverse-Core v2.5-b697 generated an exceptionjava.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by robotnikthingy** [Multiverse/Multiverse-Core#1599]
Hi, whenever I teleport toa diffirent world the server spams the console with this message. Also when I teleport back to spawn I cant close minecraft or move, my play just keeps twerking up and down.

[Warn] [Multiverse-Core] Task #55437 for Multiverse-Core v2.5-b697 generated an exceptionjava.util.ConcurrentModificationException at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_05] at java.util.HashMap$KeyIterator.next(HashMap.java:1453) ~[?:1.8.0_05] at net.minecraft.server.v1_8_R3.EntityTracker.a(EntityTracker.java:202) ~[spigot.jar:git-Spigot-f928e7a-994b2aa] at net.minecraft.server.v1_8_R3.EntityPlayer.B(EntityPlayer.java:1041) ~[spigot.jar:git-Spigot-f928e7a-994b2aa] at net.minecraft.server.v1_8_R3.EntityPlayer.updateAbilities(EntityPlayer.java:934) ~[spigot.jar:git-Spigot-f928e7a-994b2aa] at net.minecraft.server.v1_8_R3.PlayerInteractManager.setGameMode(PlayerInteractManager.java:36) ~[spigot.jar:git-Spigot-f928e7a-994b2aa] at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.setGameMode(CraftPlayer.java:764) ~[spigot.jar:git-Spigot-f928e7a-994b2aa] at com.onarandombox.MultiverseCore.listeners.MVPlayerListener$2.run(MVPlayerListener.java:353) ~[?:?] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-f928e7a-994b2aa] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-f928e7a-994b2aa] at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot.jar:git-Spigot-f928e7a-994b2aa] at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-f928e7a-994b2aa] at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-f928e7a-994b2aa] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-f928e7a-994b2aa] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]

**Comment by TWSSYesterday** [comment]
I need logs, versions etc, thanks :)

**Comment by TWSSYesterday** [comment]
@robotnikthingy are you able to provide the above? :)

**Comment by robotnikthingy** [comment]
Oh my bad, forgot all about this ticket. I seemed to have fixed the twerking part by setting keepspawninmemory to true (or something like that)

Using spigot 1.8.8, using Multiverse-Core-2.5

heres more detailed logs
http://pastebin.com/UTXd6he1

**Comment by TWSSYesterday** [comment]
Is this still happening on the latest version? If so, please let me know so I can assist you. If it isn't, please close the issue :)
