### ISSUE TITLE
Strange conflict with Vault if certain other plugins are present.

### ISSUE THREAD

**Issue by Drift91** [Multiverse/Multiverse-Core#1600]
I already made a ticket for vault with this, but since my logfile seems to blame Multiverse Portals I figured I'd post here too.

My Vault ticket: https://github.com/MilkBowl/Vault/issues/616

Contents of the above linked ticket:
I get the following Error: http://pastebin.com/30gb6w7y

Here's an archive of all the plugins I'm using: https://www.dropbox.com/s/dd8y4xvslzk6w8x/plugins.rar?dl=0

So far I've discovered that disabling Multiverse Portals seems to solve the issue. Another solution I found was to disable ChatPing, EnjinMinecraftPlugin AND LiftSign. Disabling only one or two of them doesn't seem to fix the issue. Also if I delete the rest of the plugins I don't get the error. I'm still looking into finding the other culprit(s).

This probably isn't a problem with Vault, but I'm at a complete loss as to who to report this to since there's so many different combinations of plugins that cause it.

**Comment by Sleaker** [comment]
Multiverse core should probably softdepend on Vault. It currently does not.

**Comment by Drift91** [comment]
After messing around more I've found that if I disable any random 3 plugins Vault suddenly runs. Or if I disable Multiverse Portals it'll run. So it seems Multiverse has something against a certain amount of plugins being installed alongside itself and Vault.

**Comment by Sleaker** [comment]
@Drift91 - that sounds more like a classloader ordering changing in the JVM than Multiverse itself. But Multiverse doesn't properly handle Vault as a dependency right now...

**Comment by dumptruckman** [comment]
Please try the latest dev builds. There has been significant changes to the handling of Vault. http://ci.onarandombox.com/job/Multiverse-Core/
http://ci.onarandombox.com/job/Multiverse-Portals/

**Comment by Drift91** [comment]
Appears to fix the issue. Thank you.
