### ISSUE TITLE
"World could NOT be deleted"

### ISSUE THREAD

**Issue by steven5703** [Multiverse/Multiverse-Core#1601]
Yes, I know you can fix it by deleting the world's folder and removing it from the config, but thats a hassle 

I have a build server that me and my friends use so there's like 20 worlds, occasionally I delete the old ones, but the plugin always says "World could NOT be deleted" for like half of the worlds. I make sure no one is in the world I'm deleting, still doesn't work..

**Comment by TWSSYesterday** [comment]
Logs? Versions? Could be a default world.

**Comment by steven5703** [comment]
Sure, http://pastebin.com/GeUPiiW5. Not sure if that's much help
Version is 2.4

**Comment by dumptruckman** [comment]
I believe in 2.5 we started using Apache Commons IO lib to delete files. It's still not perfect as Java does not allow you to take over a file lock. That means that we are doing all we can to remove the world folder with the delete command.
