### ISSUE TITLE
A world named "test" generates on server start (b967)

### ISSUE THREAD

**Issue by RoboMWM** [Multiverse/Multiverse-Core#1604]
Running build 967 of just multiverse-core (no other MV plugins), and despite my efforts to delete it, this world named "test" constantly keeps getting created on server start, if not already existing.

**Comment by TWSSYesterday** [comment]
Worlds.yml, by removing it from there, Multiverse plays no part in loading it. Check server.properties for default world too.

**Comment by RoboMWM** [comment]
Default world is world, and it is not in worlds.yml. Will post pastebin links to server log and worlds.yml

**Comment by RoboMWM** [comment]
Ok, might actually be a plotsquared issue, sorry about the confusion :s
