### ISSUE TITLE
[Suggestion] Re-create a world on server start

### ISSUE THREAD

**Issue by rogama25** [Multiverse/Multiverse-Core#1605]
I think that there isn't any option to re-create a different [not /mv reset world] world on each shutdown without any external plugin.

**Comment by dumptruckman** [comment]
There isn't any option for this. I doubt there's any other plugins for it either. Unless you have some compelling reason for why it must be a *new* world, why not just have the spawn location randomized at least 5000 or so blocks away and use a world border.

**Comment by rogama25** [comment]
Oh, I haven't thought about it. :grinning:
