### ISSUE TITLE
Crash World?

### ISSUE THREAD

**Issue by FraazT0** [Multiverse/Multiverse-Core#1606]
I don't know if it's because of Multiverse, but since is world-related I'll ask it here.
I have a world in my server that worked properly. Just a normal world, no generators. A few time ago, some chunks make the server crash if someone goes in there. The strage thing is that the console does not report anything strange, the server closes as if I make /stop. I tried to examine the world in singleplayer but it was normal.
I'm using latest multiverse and Spigot 1.8.8.
Download of the world: www.mediafire.com/download/oht9c94awvjqygh/MineralCity.zip

(sorry for my bad english)

**Comment by dumptruckman** [comment]
Try making a new test server without *any* plugins and this problem world as the primary world. If the same problem happens then there is something wrong with the world or the server. If it does not happen, you have a plugin that is causing the issue. It's very unlikely that it is Multiverse however.

**Comment by TWSSYesterday** [comment]
Looks to be okay, as Jeremy said; try reproducing by removing factors individually.
