### ISSUE TITLE
File reseting everytime I restart server, even though I save the file?

### ISSUE THREAD

**Issue by ItsLeJosh** [Multiverse/Multiverse-Core#1607]
Hello support,
I'm using Multiverse-Core2 and I'm trying to make it so that in chat, the world doesn't show up when they chat. I looked in the config file, set prefix chat to 'false' then saved. I proceeded to restart the server. After the restart I typed in chat and it still said the world next to it. I looked at the config file, and it had prefix chat to 'true'. Also, the names of the worlds in chat are messed up, whenever I set the aliases for the world I'm in, it says "World not found!" 

Please help,
Josh

**Comment by TWSSYesterday** [comment]
Hey there @ItsLeJosh Use /mv conf prefix false, that should do it! The config file has always been one best to be edited when the server is offline. I would always recommend updating to the latest build which can be found on http://ci.onarandombox.com/view/Multiverse/
