### ISSUE TITLE
Clocks and Compasses - Doesnt work

### ISSUE THREAD

**Issue by Lazorius** [Multiverse/Multiverse-Core#1616]
Clocks and compasses doesnt work for my server anymore.

A fairly unique circumstance happened on the server, It might have contributed to it,
Here is the short version:
We lost all server-files while the server was running, so me and one of our admins had to use a mod to download the chunks and redo the whole server plugins and configs from scratch.

It worked just fine before, I need them to work for our main attractions, Maze Runner+factions and RPG.

Server IP, if someone wants to join and see for themself: mc.kubeen.net

**Comment by dumptruckman** [comment]
This has absolutely nothing to do with Multiverse. Please try asking on your server forums or something.

**Comment by Lazorius** [comment]
i am the owner..
