### ISSUE TITLE
dumptruckman did not read my issue - compass and clock issue

### ISSUE THREAD

**Issue by Lazorius** [Multiverse/Multiverse-Core#1617]
You said that i should go to "the servers forums" and ask about the issue, While I am the owner, as i clearly stated when i said "my server".

Here is what i said:
"Clocks and compasses doesnt work for my server anymore.

A fairly unique circumstance happened on the server, It might have contributed to it,
Here is the short version:
We lost all server-files while the server was running, so me and one of our admins had to use a mod to download the chunks and redo the whole server plugins and configs from scratch.

It worked just fine before, I need them to work for our main attractions, Maze Runner+factions and RPG.

Server IP, if someone wants to join and see for themself: mc.kubeen.net"

**Comment by rlf** [comment]
You did not understand his answer m8.

It's most likely nothing to do with Multiverse, but rather that you tailored the chunks, meaning messed up with the seed vs chunks.

In other words, go "read on your servers forums", means, go read on Spigot/Bukkit/Craftbukkit forums (what-ever server you are running), and not "go read on your own server-forum to find the problem".

**Comment by dumptruckman** [comment]
@rlf has it right. I should have said server software forum. This is not a multiverse issue.
