### ISSUE TITLE
Mob/Animal Spawn Rate Not Working!

### ISSUE THREAD

**Issue by AdminZero** [Multiverse/Multiverse-Core#1619]
The spawn: true/fase seting seems to work but the SPAWNRATE: setting does not?  I have tried to use several variations of it but none seem to work (IE '0', 0, '-0'), how can I STOP animals from spawning naturally but STILL allow them to use spawn eggs and the animals to go though the portals? 

spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: 0
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []

**Comment by FernFerret** [comment]
Closing due to issue age (sorry). We slacked off on our issues. If you're still having this issue, please read up on [submitting a bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and post the details with a more recent server/multiverse version. Sorry again!
