### ISSUE TITLE
Backwards Compatibility - no version 1.7.10 and 1.8.0

### ISSUE THREAD

**Issue by akobes** [Multiverse/Multiverse-Core#1623]
Will the latest version of multiverse work with KCauldron server version 1.7.10? The latest 2 releases of Multiverse seem like they support game version 1.7.9 and 1.8.1. So I am wondering why it doesn't list 1.7.10 and 1.8.0.

**Comment by dumptruckman** [comment]
We can only select one version when uploading a file. It works on all of the version you listed as far as we know.
