### ISSUE TITLE
Multiverse For MC v1.5.2

### ISSUE THREAD

**Issue by n1ck1901** [Multiverse/Multiverse-Core#1630]
Hey, so for the life of me I can't seem to find a multiverse version for MC v1.5.2. I could be just over looking something simple, but can you give me a link or something?

Thanks, Nick..

**Comment by TWSSYesterday** [comment]
http://dev.bukkit.org/bukkit-plugins/multiverse-core/files/24-2-5-b641-beta/ probably, try the later ones though anyway. (Not the latest though)
