### ISSUE TITLE
Worlds all change to Peaceful after a server restart

### ISSUE THREAD

**Issue by Arshak13** [Multiverse/Multiverse-Core#1632]
Today, I had updated my server to the latest version of multiverse-core. I had updated it and once I did I restarted the server and right after I changed the worlds I wanted to be normal or easy to what I chose. I restarted the server again and it continued to change over to peaceful. I was told to post this issue here if it continues by TWSSYesterday.

**Comment by TWSSYesterday** [comment]
Fixed in latest build?

**Comment by dumptruckman** [comment]
World difficulty not keeping its setting in some cases is a known issue. We have never been able to reproduce the issue in testing and as such do not have a fix.

**Comment by DarkFlareMC707** [comment]
Could it just be that the server's automatic difficulty is peaceful?

**Comment by FernFerret** [comment]
Regardless of the server setting, MV should keep world difficulties set properly through restarts at a minimum with the use of the `worlds.yml`
