### ISSUE TITLE
Having trouble with build permissions.

### ISSUE THREAD

**Issue by Mitchell12345MB** [Multiverse/Multiverse-Core#1633]
Hi

I'm having a lot of trouble setting permissions a specific group for a specific world. I'm wanting to have the default group to not be able to build there, but all the other groups to be able to build there. Here's my permission layout (I'm using permissionsBukkit).

groups:
    default:
        permissions:
            multiverse.access.*: true
            multiverse.help: true
            multiverse.portal.access.*: true
            permissions.build: true
        worlds:
            vip:
                permissions.build: false
messages:
    build: '&cYou do not have permission to build here.'

debug: false

Thing is, when I set this, I have all the other groups not being able to build there. Can someone help me out?

**Comment by dumptruckman** [comment]
This has nothing to do with Multiverse. Please contact the developer of the plugin (perhaps permissionsbukkit) that controls build permissions.
