### ISSUE TITLE
Setting to disable non-multiverse worlds being added to config on shutdown.

### ISSUE THREAD

**Issue by triger545** [Multiverse/Multiverse-Core#1635]
My server uses Multiverse as our main world management plugin.

My server creates different copies of worlds to create private "instances." The problem I'm having is as follows. Say a player starts up an instance of the world "test." The instanced world will be called "test_1", to show it is instance number 1. If the server shuts down while this instance is active, Multiverse will save this world to the config, and load the world on the next startup. This makes startup take a lot longer, and will often mess with the copying of instanced worlds.

Possible Solutions:

Create a setting in the config.yml.

When the plugin is about to save the worlds, first check if this value is true. If so, all worlds can be added to the config. If false, Multiverse checks each world to see if they're already in the config. If the world isn't in the config, ignore it.

Another possible solution would be to make a setting in the config.yml that will determine if new worlds should have "autoload: true" when added to the MV Config.

**Comment by dumptruckman** [comment]
Multiverse does not save world configs for worlds that were not created by it. That is to say, whatever is creating test_1 must be using the Multiverse API to add the world, in which case the config is being created. I would suggest you contact the dev for that plugin and bring up the issue with them.
