### ISSUE TITLE
Handling infailed worlds

### ISSUE THREAD

**Issue by Aggroblut** [Multiverse/Multiverse-Core#1636]
-

**Comment by dumptruckman** [comment]
What is an "infailed" world? Multiverse-Core has never done anything with inventories or god mode.

**Comment by Aggroblut** [comment]
Sorry for my bad English. Here is my next try to describe it.

The thing I want to report is that if a world is removed (/mv remove) or disabled. Players that logout in these worlds and than log in (now its "infailed" for me, because the world don't exist) they will properly die because they don't move their location and in the other world (default world) the location of the old world is in the underground. So there is nothing that multiverse do but I expected that's multiverse job. 

But just forget it. I think you wont do anything. But I can write a plugin on my own that logs the logout world and checks on login, if the world is "infaild" and if that happens I can teleport the player somewhere else. The only problem here I cant get the object address of the unloaded/removed world. So I cant call out an worldchangeevent for other plugins, e.g. Inventory Manager. 

If you have an Idea how I can get the World Object of and unloaded world, I would be glad to hear it. 

Thanks for all.

**Comment by dumptruckman** [comment]
You cannot get the World object of an unloaded world.
