### ISSUE TITLE
/mv regen worldname-end no dragon?

### ISSUE THREAD

**Issue by joshthegrate** [Multiverse/Multiverse-Core#1637]
when i "/mv regen {worldname-end}" the world regens properly but doesn't spawn in an ender dragon.

i am using multiverse-core-2.5 Jenkins build # 711

**Comment by joshthegrate** [comment]
discovered the issue.  MCMA_compat.jar from mcmyadmin is the culprit as far as i can tell there is no config for it being generated but i do need it for mcmyadmin to be able to interface with my server correctly.

**Comment by FernFerret** [comment]
Closing as unrelated, thanks for the update.
