### ISSUE TITLE
Vanilla End portal is broken 

### ISSUE THREAD

**Issue by noobcopmikey** [Multiverse/Multiverse-Core#1640]
today while setting up my multiverse server i was testing interdenominational travail. everything was working or fixable for me untill i tested my Vanilla End portal. When entering the end i spawn at 37 0 -49 which instantly places me in the void.

**Comment by dumptruckman** [comment]
Try updating to the latest beta builds on http://dev.bukkit.org or latest dev builds on http://ci.onarandombox.com. We fixed this issue long ago in Multiverse-NetherPortals and if you're not using that plugin then Multiverse has nothing to do with your problem.
