### ISSUE TITLE
problem generation (imported map)

### ISSUE THREAD

**Issue by spitap** [Multiverse/Multiverse-Core#1643]
hello,
i had change the plugin of multiworld support and i had imported my 3 old world. but the 3th was a world with an empty generator and then, when i generate new chunks the world use a normal generator :( ...
Why i can rollback my map and import it without this problem?
thanks

**Comment by dumptruckman** [comment]
https://github.com/Multiverse/Multiverse-Core/wiki/Custom-Generator-Plugins
