### ISSUE TITLE
Multiverse Config doesn't save changes

### ISSUE THREAD

**Issue by firehawk5151** [Multiverse/Multiverse-Core#1644]
Okay, i just tried to use this plugin for the second time (the first was a while ago with great success) and this time whenever I make edits to the config.yml for Multiverse-core, the changes simply will not save. FileZilla says that i still have files that are being edited. I've tried editing other config.yml files such as the one for essential and testing if it saved the changes, and it did. The multiverse config simply doesn't save changes. The initial first change i wanted to make was the prefix for the worlds being there, i turned it to false, and when i reload the plugin it just turns back to true..

**Comment by bizah777** [comment]
You need to stop your server before you save config
