### ISSUE TITLE
Can't load "end" worlds

### ISSUE THREAD

**Issue by cj89898** [Multiverse/Multiverse-Core#1646]
Multiverse can't load, import end worlds. I created them with multiverse and they still do not work. I try to tp to them and it says it doesn't know about it.

Startup Log: http://justpaste.it/qgwb
worlds.yml: http://pastebin.com/ArhRDjv2
Error that is now occuring when trying to tp: http://pastebin.com/GkK1wQ2W

**Comment by TWSSYesterday** [comment]
Environment should be "END" not "the_end"

**Comment by cj89898** [comment]
I moved this to a different thread #1649 . Also It wasn't "the_end" environment.
