### ISSUE TITLE
World Tp

### ISSUE THREAD

**Issue by Kevintjuh** [Multiverse/Multiverse-Core#1648]
Hi guys,
I'm going to make a Network, called Awkward-Network.
With just a portforwarded server. I use MultiVerse-Core to make different worlds. I wanna make a survival, skywars, and a kingdom (build a kingdom and roleplay with other kingdoms), and maybe Minetopia(in the netherlands a real-life city with real money and so on) But the problem is, when you join a world, you;re just on the spawn of that world. can't that be fixed that you will join where you left the previous time? Is there a option, of can you update it?
Thanks for reading and I hope that you will bring a solution.
Greets Kevin.

**Comment by TWSSYesterday** [comment]
This is down to Essentials (most likely). There's a part of the config file where it sets the teleportation priority, if you set this to lowest, Multiverse will take priority.
