### ISSUE TITLE
multiverse.teleport.[self|other].WORLD_NAME might not work at all

### ISSUE THREAD

**Issue by dkolb** [Multiverse/Multiverse-Core#1651]
I commented yesterday on a really OLD issue with this and it was closed asking me to upgrade Multiverse.  I have upgraded to 2.5-b711 and still experienced the issue.  I forked and checked out the code and started diving into it.

So, I'm asking for some guidance in possibly crafting a pull request or to update the documentation, because I don't think this feature is actually implemented.

Then again, I'm relatively new to the Bukkit API scene, so I could be missing something.

Here's a log: https://gist.github.com/dkolb/38594088b323e5511d2a

Now for what I'm seeing in the code.

It seems the root of the issues is that the teleport permissions for each world are never added to the TeleportCommand via both `org.bukkit.plugin.PluginManager.addPermission#(org.bukkit.permissions.Permission)` and
`com.pneumaticraft.commandhandler.Command.addAdditionalPermission#(org.bukkit.permissions.Permission)` on the `TeleportCommand` instance itself, similar to how the `DestinationFactory` adds these permissions to bukkit `PluginManager` and the `TeleportCommand` instance when registering the various destination type permissions.

Furthermore, even if execution of /mv tp got past the call to `com.pneumaticraft.commandhandler.CommandHandler#checkAndRunCommand(org.bukkit.command.CommandSender, java.util.List<java.lang.String>, com.pneumaticraft.commandhandler.Command, boolean)`, `TeleportCommand` itself does not actually check the name of the destination against the user's permissions, which I assume to be a process similar to that found in `com.onarandombox.MultiverseCore.commands.TeleportCommand#checkSendPermissions` which checks that the specific destination type permission is present.

It looks like there are two places changes will be required:

`TeleportCommand` will need to check that either the destination type *or* the destination name permissions are present.  Specifically we might want to change the short-circuit around line 107 from

```
if (!this.checkSendPermissions(teleporter, teleportee, d)) {
    return;
}
```
to
```
if(!(this.checkSendToDestinationTypePermissions(teleporter, teleportee, d) &&
    this.checkSendToDestinationNamePermissions(teleporter, teleportee, d)) {
    return;
}
```
or perhaps simply extend checkSendPermissions's logic to include the destination name.

Second: At some point before anyone tries to /mv tp to a specific world, we need to register the permission with Bukkit and on the `TeleportCommand` instance.  The best approach seems to be in the WorldManager, either in each of the variations on doLoad, or further up at both addWorld and loadWorld.  

Finally, I don't know if we need to be careful about removing permissions from bukkit and the `TeleportCommand` instance, or if bukkit/Command will throw a fit or act weird if we inadvertently add the same permission twice.

Thoughts?  Comments?  Should I just go ahead with these changes and open a PR?

**Comment by dumptruckman** [comment]
That was never a valid permission. There's just multiverse.teleport.self.w and multiverse.teleport.other.w. Those permissions allow you to use mv tp to teleport someone to another world (any world*).

* The teleportee must have access permission to that world.

**Comment by dkolb** [comment]
Then the wiki definitely needs updating.

https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#teleport-command

Aliases:

/mv tp ...
/mvtp ...

Permission:

multiverse.teleport.self.NAME
multiverse.teleport.other.NAME

**Comment by dkolb** [comment]
Also:
https://github.com/Multiverse/Multiverse-Core/wiki/Big-List-O-Permissions#wiki-teleport

**Comment by dkolb** [comment]
And:
https://github.com/Multiverse/Multiverse-Core/wiki/List-Of-Permissions

**Comment by dumptruckman** [comment]
If you read the details in the command reference that the permission links to you will find:

The letter(s) at the end are the identifier for the destination. This is the same thing you would put before the destination if you teleport to it: /mv tp w:MyWorld. So Portals would be:

multiverse.teleport.self.p
multiverse.teleport.other.p

Even if you have the multiverse.teleport.other.w permission, you can only teleport people to worlds where YOU can go yourself. This will allow you to teleport a player to a world that they themselves cannot go to, as long as you have the permission to do so.

Please see the FAQ for why this change was made (Old permissions were simply multiverse.core.tp.[self|other]!

If you would like to edit the wiki to increase clarity, by all means, go for it. It's a wiki, it can be edited by the public.
