### ISSUE TITLE
Imported worlds don't carry over scoreboard objectives or teams.

### ISSUE THREAD

**Issue by GamingAndStuffs** [Multiverse/Multiverse-Core#1653]
The title basically says it all. 
You can test by taking this world, 
http://www.minecraftforum.net/forums/mapping-and-modding/maps/2559826-snowbomb-wars-by-epicelite3-v-1-0
Importing it, and then doing /scoreboard objectives list. None of the objectives normally in the map will be there.

**Comment by dumptruckman** [comment]
Unfortunately I don't think there is anything we can do about this. Multiverse simply asks the server to load the world. If the server doesn't load the scoreboards then the problem lies in the server.

**Comment by FernFerret** [comment]
I'm more than willing to look into this (i'm curious) but as @dumptruckman said, I don't think this info is carried in a world folder. Might be a candidate for another plugin.

I do want to peek into the world/server API just to make sure before closing this issue
