### ISSUE TITLE
Could not pass event PlayerTeleportEvent

### ISSUE THREAD

**Issue by XxFireDragon98xX** [Multiverse/Multiverse-Core#1654]
I am given this log:

```
[16:44:06 ERROR]: Could not pass event PlayerTeleportEvent to Multiverse-Core v2.5-b699
[16:44:06 ERROR]: null
```

When I issue the commands: ``/spawn``, ``/warp``, ``/setwarp``, ``/home``, ``/sethome``.

I am running a 1.8.8 Spigot Server

**Comment by TWSSYesterday** [comment]
Cannot see log file, could you pastebin it for me? :) Sounds like it's probably an Essentials issue, try Essentials X :)

**Comment by FernFerret** [comment]
As @TWSSYesterday said, please post some logs and read [Submitting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug).

**Comment by XxFireDragon98xX** [comment]
i found out the problem, this was a month ago
