### ISSUE TITLE
issue an internal error 

### ISSUE THREAD

**Issue by yardgg** [Multiverse/Multiverse-Core#1657]
Hello i folowed the tutorial to make a portal but when i try to enter the command /mvp create swamp w:swamp   the server answer me :  An internal error occured while attempting to perform this command  i attached the log i could find in my console 
[full logs.txt](https://github.com/Multiverse/Multiverse-Core/files/138909/full.logs.txt)
I m using Spigotmc-1.8.8-R0.1
Thanks for answering

**Comment by TWSSYesterday** [comment]
Wrong WorldEdit version, update Multiverse-Core and Multiverse-Portals to the latest along with WorldEdit. Your worlds.yml is corrupt/not configured properly. It has YAML parsing errors.

**Comment by yardgg** [comment]
i dont know what is YAML parsing errors i m french btw but i ll search about it  thanks for your help  , but i only have to  update world edit ? or  finding the version which match with each other ? i mean cant i take the  last version of WorldEdit and multiverse-Core + Multiverse-Portals 
Thanks you again for your help

**Comment by yardgg** [comment]
Hum i didn't understand first time i read that xd sorry  i m right this : http://dev.bukkit.org/bukkit-plugins/worldedit/files/61-world-edit-6-1-up-to-mc-1-8-8/ is the last version of world edit and same for  this : http://dev.bukkit.org/bukkit-plugins/multiverse-core/files/23-2-4-ab/ for multiverse core ? and i suppose this one for multiverse-portals ; http://dev.bukkit.org/bukkit-plugins/multiverse-portals/ 
i'm relatively new  at creating server , sorry for being a noob at  this thing ^^

**Comment by TWSSYesterday** [comment]
Download files from http://ci.onarandombox.com/view/Multiverse/ and WorldEdit from http://builds.enginehub.org/job/worldedit/8533/download/worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar

**Comment by yardgg** [comment]
hum  WorldEdit worked but i have a new problem with Multiverse i downloaded Multiverse-Core-2.5-javadoc.jar	 and Multiverse-Portals-2.5-javadoc.jar but maybe was it the wrong file it took me time to figure where to download the file so the console say to me that multiverse couldn't be loaded

**Comment by yardgg** [comment]
It worked thanks you a lot i could create my portal :D

**Comment by TWSSYesterday** [comment]
Glad to hear :)
