### ISSUE TITLE
Multiverse does no know how to take you to (name of the world)

### ISSUE THREAD

**Issue by mini88** [Multiverse/Multiverse-Core#1658]
I changed the version of multiverse from 2.4 to 2.5 and I lost everything i've done. I tryed to put the old version but now it says Multiverse does no know how to take you to (Name of the world) please help i lost everything.
![2016-02-21_17 34 48]
screenshot:
(https://cloud.githubusercontent.com/assets/17385614/13203887/4dae0286-d8ca-11e5-9eb8-b7f61c74e8ad.png)

**Comment by mini88** [comment]
I still have the world folder

**Comment by TWSSYesterday** [comment]
What is the output of /mvl

**Comment by mini88** [comment]
Sorry, I didnt understand im half english. In /mvl is not the world I want to recover. What can I do?

**Comment by TWSSYesterday** [comment]
Use /mvl, what's the output?

**Comment by mini88** [comment]
In /mvl there is all the names of my worlds... I dont know if that is what you asked for

**Comment by dumptruckman** [comment]
Do not downgrade from 2.5 to 2.4. Use 2.5. If the world is not loaded, just import it again with `/mv import`

**Comment by mini88** [comment]
Thanks!!! You saved me!! Thanks dumptruckman and twssyesterday to help me!! Very nice people <3
