### ISSUE TITLE
Kein Hunger

### ISSUE THREAD

**Issue by ZockerWelt** [Multiverse/Multiverse-Core#1659]
Ich habe das Porblem das Multivers-Core den Hunger in allen Welten ausschaltet!!! Ich habe schon alles mögliche ausprobiert was mir einfill um das Problem zu lösen hat aber alles nichts gebracht! Nun bitte ich um hilfe wie ich den Hunger wieder einschaltten kann weil ich den brauche für mein Survivale-Server!!!

**Comment by Nicewuerfel** [comment]
Und du bist sicher, dass die difficulty nicht auf 0 ist?

**Comment by FernFerret** [comment]
Sorry, I think the people in charge of this issue tracker use english to handle issues. Feel free to post an update in english, but I'm going to close this. If someone on the @Multiverse/core-development-team wishes to respond, feel free to do so.
