### ISSUE TITLE
How do I modify default config values?

### ISSUE THREAD

**Issue by ajthemacboy** [Multiverse/Multiverse-Core#1660]
I want to modify the default configuration values that are set when a world is imported, namely ``"keepSpawnInMemory: 'false'"`` instead of ``'true'``.

Where in the source can I change this?

**Comment by TWSSYesterday** [comment]
You'd possibly want to take a look at here: https://github.com/Multiverse/Multiverse-Core/blob/master/src/main/java/com/onarandombox/MultiverseCore/MVWorld.java Where it sets the value based on actions (commands).

**Comment by ajthemacboy** [comment]
I'm not sure what you mean. I know I can change the configs with commands, but I don't want to have to use commands at all.

**Comment by TWSSYesterday** [comment]
You'd use that, it just shows you how it's set. Perhaps read into it a bit more on how the setting is set for a world upon creation.

**Comment by ajthemacboy** [comment]
This line looks like the one to change: https://github.com/Multiverse/Multiverse-Core/blob/master/src/main/java/com/onarandombox/MultiverseCore/MVWorld.java#L133

Either that or line 130. Is a boolean false by default?

If I replace https://github.com/Multiverse/Multiverse-Core/blob/master/src/main/java/com/onarandombox/MultiverseCore/MVWorld.java#L133 with `world.setKeepSpawnInMemory(false)` would it work?

**Comment by TWSSYesterday** [comment]
I would give that a try, yes.

**Comment by dumptruckman** [comment]
Sure, that would cause all worlds to always be false forever. Currently there's no way to have a set of default settings for new worlds. That may be a thing in MV3 if MV3 ever launches. :3

**Comment by ajthemacboy** [comment]
I'm getting an error during the build test:

`Caused by: java.lang.IllegalStateException: Failed to transform class with name com.onarandombox.MultiverseCore.MultiverseCore. Reason: java.io.IOException: invalid constant type: 18`

Full log: https://gist.github.com/ajthemacboy/a6a057b6479fce1d87c1

Any last help you can offer me?

**Comment by dumptruckman** [comment]
Hmm.. @FernFerret mentioned having issues building MV-Core on Java 8 where the issue was related to the tests. I don't have this problem myself but you may try building under Java 7.

**Comment by ajthemacboy** [comment]
Just backdated to 7 and tried it again, this time it got further but still didn't work: https://gist.github.com/ajthemacboy/c03d0abbe8c212cf9ad8

**Comment by dumptruckman** [comment]
Paste the results of the file largest file in /home/aj/dev/Multiverse-Core/target/surefire-reports

**Comment by ajthemacboy** [comment]
https://gist.github.com/ajthemacboy/39250b1b95a8f9775893

**Comment by dumptruckman** [comment]
Woops.. seem to have led you astray. There's a file in that folder that has a stack trace in it. That's what I need to see.

**Comment by dumptruckman** [comment]
Er.. nm, that contains it as well.

**Comment by dumptruckman** [comment]
Oh.. your change causes the test to fail. Well, if you're using this as a person build, you can comment out the line 146 of TestWorldProperties.java

**Comment by ajthemacboy** [comment]
Thanks, build succeeded. Testing if it works now.

**Comment by ajthemacboy** [comment]
Works great, idle RAM usage of 100 MBs :)

Thanks for all your help <3

**Comment by FernFerret** [comment]
@dumptruckman @ajthemacboy yes, that was the error I was getting. I'll still have to look into it as a seperate thing.

@ajthemacboy what IDE are you using? IntelliJ?

**Comment by ajthemacboy** [comment]
@FernFerret I just built it with Maven in Linux terminal. I know almost nothing about programming so I don't even know how to use an IDE... lol

**Comment by FernFerret** [comment]
Interesting alright, I think I may open a new ticket to see if I can at least figure out what it is... not too concerned, just seems strange...

**Comment by ajthemacboy** [comment]
Let me know if you need more logs or testing.

**Comment by FernFerret** [comment]
Not at this time, I'm sadly able to reproduce this when using Java 8, but right now cleaning the issue tracker is my priority. Once it's less cluttered, we'll be able to work better.
