### ISSUE TITLE
Console warning from MV-C on Spigot 1.9

### ISSUE THREAD

**Issue by Leesam** [Multiverse/Multiverse-Core#1662]
Tried out a Spigot 1.9 build today shortly after release, saw a warning occur every 10 minutes in the console:

`9:09:30 PM CONSOLE: WARN]: Exception in thread "Craft Scheduler Thread - 27"
9:09:30 PM CONSOLE: WARN]: org.apache.commons.lang.UnhandledException: Plugin Multiverse-Core v2.5-b711 generated an exception while executing task 9
9:09:30 PM CONSOLE: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;`

I was running Plugin Multiverse-Core v2.5-b711 and git-Spigot-7ebe8ff-5eceede (MC: 1.9)

**Comment by dumptruckman** [comment]
You need to update all your MV plugins to the _latest_ dev builds. Core is #715. @Leesam you're on #711. @tmad40blue you're on #714.

**Comment by FernFerret** [comment]
Just to post an update here, make sure you're on *716* or higher at the time of this ticket! @dumptruckman did put out a 716 that fixed some things.
