### ISSUE TITLE
 Your of Core Protocol Level is: 19

### ISSUE THREAD

**Issue by Bjezirds** [Multiverse/Multiverse-Core#1665]
```
[01:04:10 ERROR]: [Multiverse-Inventories] This version of Multiverse-Inventories requires Protocol Level: 20
[01:04:10 ERROR]: [Multiverse-Inventories] Your of Core Protocol Level is: 19
```

I cant find a multiverse core with protocol 20 please help

**Comment by FernFerret** [comment]
You just need to download a [new version of Multiverse Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/). (Make sure you get build **716** or higher.

You can see that in the latest versions, the [Protocol Level is 20](https://github.com/Multiverse/Multiverse-Core/blob/cd312c3ab95301f3f22dfe001e47fb3df74aaa8b/src/main/java/com/onarandombox/MultiverseCore/MultiverseCore.java#L126)

Closing for now, if you have more issues please post the results of the ``/mv version`` command.
