### ISSUE TITLE
changing the command players use to switch worlds

### ISSUE THREAD

**Issue by MapleMoosey** [Multiverse/Multiverse-Core#1667]
Is there any way I can change the way players go from world to world without having a portal such as instead of the players using /mvtp can they type /server pickles for example.

**Comment by TWSSYesterday** [comment]
You can run aliases in the commands.yml in your minecraft server's root directory.

**Comment by FernFerret** [comment]
@MapleMoosey See here: http://wiki.bukkit.org/Commands.yml#Alias_Examples
