### ISSUE TITLE
Possible issue with PEX and Multiverse?

### ISSUE THREAD

**Issue by KCQuetzal** [Multiverse/Multiverse-Core#1668]
Pertinent information:

Spigot b39373b-249c5f0 (MC: 1.9)
PEX 1.23.4

I have 2 worlds that I do not want my default players to be able to access: Creative world (called creative) and my KitPvP world (called KitPvP). When I DO NOT give the explicit perm multiverse.access.creative (or multiverse.access.KitPvP) players are still able to access those worlds with mvtp creative (or mvtp KitPvP). Even if I negate those perms they can still access via command but they cannot access via portal.

Note that prior to 1.9 I did not have this issue given the exact same permissions.yml.

Any assistance is greatly appreciated!

Pastebin : http://pastebin.com/Spvqb6NY

**Comment by FernFerret** [comment]
Do this for me:

```
/mv debug 3
```

Then, try a simple MVTP command to one of those worlds:

```
/mvtp w:creative
```

Check your server logs, you should see something like this: (obviously with your world names instead of mine):

```
[09:29:09 INFO]: fernferret issued server command: /mvtp w:world
[09:29:09 INFO]: [Multiverse-Core-Debug] Checking to see if player [fernferret] has permission [multiverse.teleport.*]... YES
[09:29:09 INFO]: [Multiverse-Core-Debug] Checking to see if player [fernferret] has permission [multiverse.teleport.self.w]... YES
[09:29:09 INFO]: [Multiverse-Core-Debug] Checking to see if player [fernferret] has permission [multiverse.core.spawn.self]... YES
[09:29:09 INFO]: [Multiverse-Core-Debug] Adding mapping 'fernferret' => 'fernferret' to teleport queue
[09:29:09 INFO]: [Multiverse-Core-Debug] The first location you gave me was safe.
[09:29:09 INFO]: [Multiverse-Core-Debug] Got teleport event for player 'fernferret' with cause 'PLUGIN'
[09:29:09 INFO]: [Multiverse-Core-Debug] Inferred sender 'CraftPlayer{name=fernferret}' from name 'fernferret', fetched from name 'fernferret'
[09:29:09 INFO]: [Multiverse-Core-Debug] Player 'fernferret' is teleporting to the same world.
[09:29:09 INFO]: [Multiverse-Core-Debug] MV-Core is allowing Player 'fernferret' to go to 'world'.
```

Then, post that.

**Comment by KCQuetzal** [comment]
Thank you very much for your assistance.  Here are the results:

http://pastebin.com/g67aEjCq

**Comment by KCQuetzal** [comment]
Ok so I found the issue myself and resolved it myself but it is interesting that I had to do what I had to do.  So I noted that enforeaccess was set to false which is really weird because I know it was set to true before (many years as a matter of fact).  So I set it back to true and restarted server however the config got overwritten again to false.  I actually had to make the config.yml read only in order to keep the setting to true.  After I did that the worlds were once again blocked properly.  So it appears that something with Spigot 1.9 was causing the MV-Core config.yml to overwrite/generate default?  Very strange.

**Comment by FernFerret** [comment]
Hmm this is interesting...

```
[10:38:52 INFO]: [Multiverse-Core-Debug] Player 'DaddyMendoza' was allowed to go to 'creative' because enforceaccess is off.
[10:38:52 INFO]: [Multiverse-Core-Debug] MV-Core is allowing Player 'DaddyMendoza' to go to 'creative'.
```

see that? **enforceaccess** is off.

Have a read of the basic config:

https://github.com/Multiverse/Multiverse-Core/wiki/config.yml

If **enforceaccess** is iff, multiverse will not try to enforce world permissions.

So, try:

```
/mv config enforceaccess true
```

**Comment by FernFerret** [comment]
> Ok so I found the issue myself and resolved it myself but it is interesting that I had to do what I had to do. So I noted that enforeaccess was set to false which is really weird because I know it was set to true before (many years as a matter of fact). So I set it back to true and restarted server however the config got overwritten again to false. I actually had to make the config.yml read only in order to keep the setting to true. After I did that the worlds were once again blocked properly. So it appears that something with Spigot 1.9 was causing the MV-Core config.yml to overwrite/generate default? Very strange.

Hmm, I'll have to test it, BUT if you did the following, I bet this is what happend:

* Server is running
* opened YAML config
* Changed setting
* Restarted server (this probably caused the in-memory config) to be written to disk
* Started server, wrong value

Do I have something wrong? did you try to set the value via `/mv config ...`?

Closing issue, but still curious

**Comment by dumptruckman** [comment]
Indeed, we always recommend only using commands to set config values. If you must edit the config files, shut down the server first.

**Comment by KCQuetzal** [comment]
Very thankful for the support and assistance on this issue.  I wish I had been able to figure it out on my own so as to not have to be a bother to anyone.  It was just very strange that that particular config option changed once I upgraded to 1.9 (again I've been using Multiverse for years on the same server so I never thought to even look there).  Going forward I will utilize the debug capability first before opening a ticket.  Thank again! :)

**Comment by FernFerret** [comment]
No worries, you'll notice that over the past few years, while I've been a slacker, @dumptruckman responds to well written tickets but we just get so many that sometimes it's hard to find the good tickets from the garbage. We're also going through a purge of tickets atm, glad to hear it's resolved.
