### ISSUE TITLE
Update to Spigot 1.9

### ISSUE THREAD

**Issue by nichlasm1** [Multiverse/Multiverse-Core#1669]
I really need MV-Core and the other addon plugins updated to 1.9. 

Since the source code can't be imported i can't do this by myself so i would like to request this.

**Comment by KCQuetzal** [comment]
Have you tried the latest Development version?  Can be found here : http://ci.onarandombox.com/job/Multiverse-Core/

**Comment by FernFerret** [comment]
@nichlasm1 Please just make one issue, and don't make random pull-requests. @KCQuetzal is right. as I stated in your other thread, just go to that site, and download **#716** or higher.

I've also added a build note on #716 that states it's for 1.9.
