### ISSUE TITLE
Can't Figure How To Set This Up?

### ISSUE THREAD

**Issue by KingJayeh** [Multiverse/Multiverse-Core#1674]
So during using multiverse I was trying to figure out how they can spawn a certain way im not using mvportals just multiverse it self and when they spawn its facing south in config or ingame is there a way to make them face a certain way

**Comment by FernFerret** [comment]
Yes, See: [the Destinations page on our wiki](https://github.com/Multiverse/Multiverse-Core/wiki/Destinations#world-destinations).

You can set a destination with a direction: `w:world1:ne`. Try it out with: `/mvtp w:world1:ne`.

**Comment by KingJayeh** [comment]
Im trying to get spawn so when they spawn they face north idk how do you know the exact command

**Comment by FernFerret** [comment]
Stand where you want the spawn to be, looking where you want spawns to happen. Then type:

```
/mvss
```

Use `/mvss ?` for help ingame.

**Comment by KingJayeh** [comment]
I got it working but now /spawn makes them look south but when dieing or being killed they look north which is normal? Got any clues

**Comment by FernFerret** [comment]
Not really, please explain. I don't understand your issue now. As far as `/spawn`, it may not obey the multiverse spawn since I think that's another plugin's command. `/mv spawn` should do the trick.

**Comment by KingJayeh** [comment]
/mvspawn works fine and spawns them perfectly looking north but /spawn makes them spawn looking south is there any way that can be fixed?

**Comment by KingJayeh** [comment]
nvm I figured it out
