### ISSUE TITLE
end shulker "wink"

### ISSUE THREAD

**Issue by saturnux** [Multiverse/Multiverse-Core#1675]
on village, in the end, all shulker is not viewable. it apear on touch. and it desapear with distance.

Not worldguard or other. world named the_end.
if world named other, no problem.
_____________________
sorry bad english

**Comment by dumptruckman** [comment]
This has nothing to do with Multiverse. Update spigot.

**Comment by saturnux** [comment]
it's the latest.
The most strange is that it does so only on that world (the_end).
On a world different world (test2), I have no problem.

**Comment by FernFerret** [comment]
What @dumptruckman is saying, is that multiverse does not provide you the
ability to have multiple worlds, but rather provides a mechanism to
communicate with Spigot's Multi-World API. Thus this issue has nothing to
do with Multiverse. I'd go open a Spigot ticket, but it could also be a
client side problem.
