### ISSUE TITLE
MVImport 'Failed!'

### ISSUE THREAD

**Issue by OriginalsByToto** [Multiverse/Multiverse-Core#1682]
Hi,

I've a singleplayer world but when I would like to import it on my server, the message 'Failed!' appears.

Thank you in advance.

(I have MV 2.5-b699 for 1.8.1)

**Comment by TWSSYesterday** [comment]
Log files?
Version of Spigot?
Tried updating it?
What command are you running?

**Comment by OriginalsByToto** [comment]
The bug was that I upload but on ftp as root but the servers were launched via the servers account, and they do not have the permission to open the file session.lock

Sorry for opening this ticket, but this answer will help others.
