### ISSUE TITLE
Multiverse and essentials /warp - time problem

### ISSUE THREAD

**Issue by AlwaysCandr** [Multiverse/Multiverse-Core#1684]
Hi, this bug sometimes seems to occur when warping to different worlds that have different times. When warping, time does not change for the player like it should.
Let's say that World 1 has day and World 2 has night - when warping from 1 to 2, sometimes World 2 looks to me (and some players) like it was day, even tho it's not (checking /time + monsters are spawning normally and not burning). Any idea what to do?

**Comment by FernFerret** [comment]
This does not sound like a Multiverse issue, but rather a Spigot Multiworld API issue, or probably even a Minecraft Client issue.

Multiverse simply provides a command layer on top of the MultiWorld API that spigot provides, and Spigot does all the Heavy lifting, passing that information to the clients.

If you're still interested, try these:

- [ ] Make sure Multiverse-Core is up to date http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/
- [ ] Make sure your Spigot version is up to date `/version` 
- [ ] Post [this information](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) if you've done the above two and you're still having issues

**Comment by FernFerret** [comment]
Closing as no comment from reporter in > 7 days. Please comment if issue persists.
