### ISSUE TITLE
AsyncPlayerChatEvent spams console

### ISSUE THREAD

**Issue by Kayepur** [Multiverse/Multiverse-Core#1685]
i keep getting this block of error message in my console: http://pastebin.com/BWnhM2qk

is there any way to get rid of it? i am using the default config, outside of MySql database info.

**Comment by FernFerret** [comment]
Please do the following for us:

- [ ] Update your Multiverse-Core version http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/
- [ ] Post the results of `/mv version -g`

**Comment by Kayepur** [comment]
I am still running 1.8, i did the command, then realized you might want it after i update. here is the results from the currently installed plugin : [http://pastebin.com/1FQxSckh](url)

**Comment by FernFerret** [comment]
Change `%CHAT%` to `%chat%`, the case matters.

**Comment by FernFerret** [comment]
NOTE: don't forget to run `/mv reload` **after** editing the config.

**Comment by Kayepur** [comment]
that fixed it! thanks so much! now it's not such a headache to review console logs. :) :+1:
