### ISSUE TITLE
Cant Import A World

### ISSUE THREAD

**Issue by xVRage** [Multiverse/Multiverse-Core#1686]
Im trying to import a world for 1.7.10 i downloaded 1.7.9 version dont know if 1.8 will work but 1.7.9 wont work with 1.7.10 while importing. Most features work but not all.

**Comment by FernFerret** [comment]
I there, this issue does not have enough information. Please complete the following items for us:

- [ ] Ensure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/)
- [ ] Ensure you're running the [latest Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/)
- [ ] Post the result of `/mv version -g`
- [ ] Post the result of `/version`
- [ ] Post a bulleted list of simple steps to reproduce. [See here for more information.](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug)

**Comment by leasoncre** [comment]
you can't down-grade a world, only upgrade it.
ie: if you have a 1.8 world, you CANNOT run it with 1.7
i believe the same is true for trying to open a 1.7.10 world in 1.7.9

**Comment by FernFerret** [comment]
Closing as no comment from reporter in > 7 days. Please comment if issue persists.
