### ISSUE TITLE
[Question] - Empty End World

### ISSUE THREAD

**Issue by PinoyLifeCraft** [Multiverse/Multiverse-Core#1687]
Is there any way to create an empty world in End?
It's to lag if i will break all the block in end using WE - worldedit

**Comment by leasoncre** [comment]
get async -or-
try a void world generator. (i think void worlds can be made by multiverse by default?)

**Comment by FernFerret** [comment]
@leasoncre is partially correct. Multiverse [supports generator plugins](https://github.com/Multiverse/Multiverse-Core/wiki/Custom-Generator-Plugins) but does not provide any itself. Please have a read on that wiki link about using generators and post any further questions.

Keep in mind the links on that page are provided by developers and users and are not monitored by myself or the Multiverse team.

**Comment by dumptruckman** [comment]
Unfortunately the page @FernFerret linked seems to be outrageously outdated. Your best bet will be to google around to find a generator plugin that can provide this feature. Closing issue but feel free to post further questions.

**Comment by TWSSYesterday** [comment]
Perhaps even http://dev.bukkit.org/bukkit-plugins/multiverse-core/pages/generators/ would show, CleanroomGenerator is still working perfectly!

**Comment by leasoncre** [comment]
Cleanroomgenerator is supported without an external generator plugin
