### ISSUE TITLE
AdjustSpawn not working correctly

### ISSUE THREAD

**Issue by sigmaroot** [Multiverse/Multiverse-Core#1694]
I'm running Multiverse-Core version 2.5-b719
In all of my worlds, adjustSpawn is set to false, but every time after a server restart the spawnpoints for some worlds change to a different location some blocks away. It's annoying because I'm using Multiverse-Portals to enter these worlds and sometimes the players are spawning outside the spawn building / area of that world...

Can you please check that?

[http://pastebin.com/KF2mNmBR](http://pastebin.com/KF2mNmBR)

This is the output of mvdebug 3 in a world where adjustSpawn is set to false...

**Comment by sigmaroot** [comment]
No answer yet, *push*

**Comment by FernFerret** [comment]
Hmm, that probably shouldn't be happening.

I'll carve out some time this weekend for this bug too. Sorry for the lack of responses, been really busy lately.

**Comment by FernFerret** [comment]
Could you also post the result of `/mv version -g`

**Comment by sigmaroot** [comment]
Yes, thank you for your answer!

[https://gist.github.com/anonymous/9029ed8a185fa2593c0f78ba887f8b55](https://gist.github.com/anonymous/9029ed8a185fa2593c0f78ba887f8b55)

**Comment by FernFerret** [comment]
Hmm so I stumbled onto some issues a month ago or so with the config parser
not parsing things properly. Thanks for the config, that's all the info I
need right now, just need to carve out some time to test it.

**Comment by sigmaroot** [comment]
Not fixed yet... I'm giving up that...

**Comment by sigmaroot** [comment]
Reopened for furthered fixes.
