### ISSUE TITLE
Survival Mobs spawning in Nether?

### ISSUE THREAD

**Issue by Sharrq** [Multiverse/Multiverse-Core#1695]
So im not entirely sure if this is Multiverse causing this or not, but it seemed like a good place to start. 

After updating to Spigot 1.9, the nether is spawning creepers, zombies, and skeletons and there are no pigmen, zombie pigmen, blazes, ghasts, magma cubes, etc. 

I tried deleting the world data and regenerating it, but i got the same result.

I can provide logs and such, just need to know which files you need.

Here is the result of /version
[INFO] This server is running CraftBukkit version git-Spigot-2038f4a-44216f1 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

**Comment by Sharrq** [comment]
We updated to Spigot 1.9.2 and it is still happening.

**Comment by FernFerret** [comment]
Interesting. The version i'm running is `spigot-1.9-f04e043`.

Multiverse really doesn't have the capacity to cause something like this (or else it'd totally be a feature :smile: ).

It sounds like it could be world corruption or at the very least world type confusion. I'm more than willing to help you look into this, so post the result of `/mv version -g` and we'll have a look (probably next weekend).

**Comment by FernFerret** [comment]
I should note that I just started running a server again, and my users have made it to the nether (in a few hours heh). I'll see what they find. I'm only running Multiverse, PermBukkit and dynmap.

**Comment by dumptruckman** [comment]
I wonder if the world was perhaps imported as a normal world.

**Comment by Sharrq** [comment]
So Multiverse says that it is a Nether World, we have completely deleted the world folder and let it regen multiple times. We also tried restoring the world from pre 1.9 and although it had nether mobs in it, if you butcher them, new spawns will be wrong. Im not entirely sure it is a Multiverse issue, but it seemed like a logical place to start. 

World_Nether Multiverse Info
http://pastebin.com/rq5ZKC80

mv version
http://pastebin.com/rWK9mL4Q

Server Version (We have tried 1.9.2 and 1.9)
11:40:34 PM CONSOLE: [INFO] This server is running CraftBukkit version git-Spigot-1480adb-8b61cc5 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)

**Comment by Sharrq** [comment]
We found the issue. We use the plugin TerrainControl (a map generator) to generate one of our specialty worlds. It for some reason is affecting the mob spawns in all of our nether worlds even though we didnt use it to generate them.

I disabled the plugin and pigmen started spawning. Thanks for offering to help me track this down though!
