### ISSUE TITLE
Lightning not working!

### ISSUE THREAD

**Issue by TerZer** [Multiverse/Multiverse-Core#1697]
On normally generating worlds no problem, everything is working, but in worlds made by MV there are no lightnings. I tried to summon lightning - "/summon LightningBolt", but it didn't worked. Tested on 2.5-b719 and 2.5-b717.

**Comment by dumptruckman** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-2025

**Comment by dumptruckman** [comment]
Not an MV bug.
