### ISSUE TITLE
Multiverse-Portals not installing

### ISSUE THREAD

**Issue by GunnerFRC** [Multiverse/Multiverse-Core#1698]
Hello,
I'm trying to install Multiverse-Portals on Bukkit but it says I need the latest version of Core in the console, which I have. I'm running MC 1.9 and MVP is 2.6 while MVC is 2.5. I tried manually installing MCP via FTB, but the latest version was 2.5. In the server, when I did /plugins with that method it listed MCP in red.
Does anyone know why?

**Comment by dumptruckman** [comment]
I have no idea where you acquired Multiverse-Portals 2.6 as we have not created this version. The latest dev builds are available here http://ci.onarandombox.com/view/Multiverse/

**Comment by GunnerFRC** [comment]
Open #1698

**Comment by GunnerFRC** [comment]
Not Closed, because I still can't solve this issue. I was able to get 2.6, or whatever the latest version was from my server control panel (it has built in plugin installer). As I've said, I've tried manually installing it but no luck.
