### ISSUE TITLE
World Alias and Towny Chat

### ISSUE THREAD

**Issue by Poeschl** [Multiverse/Multiverse-Core#1701]
Any chance to get the world alias into the towny chat formatter as like {mv-worldname}?

Or is there a plugin out for mix towny chat and the alias?

**Comment by FernFerret** [comment]
Our chat aliases are available to other plugins (not sure if towny supports Mv's chat names). @krinsdeath wrote a chat plugin a few years ago that took advantage of this exact item.

If you'd prefer to *just* use towny's chat, you can disable the `chatprefix` in the multiverse config, then MV won't mess with your chat prefixes' at all!

I'm going to close this particular issue, but if you ask the towny devs and they need some help, please send them to this ticket or to #multiverse on esper.net.
