### ISSUE TITLE
Multiverse - Error (says not up to date)

### ISSUE THREAD

**Issue by MomaCods** [Multiverse/Multiverse-Core#1703]
When I add Multiverse and multiverse inventories I get these errors 

I am not sure what else to do

http://pastebin.com/RRtKJ8g8

**Comment by TWSSYesterday** [comment]
Update Multiverse from here: http://ci.onarandombox.com/view/Multiverse/
Next time you post an error like this, could you add versions of everything to the post. Thank you :)

**Comment by MomaCods** [comment]
They are the latest versions ... and the config shows that too

**Comment by dumptruckman** [comment]
As I can see in the *log* your Multiverse plugins are most definitely not the latest versions that are available on the site @TWSSYesterday linked you to. You need to use the dev builds for 1.9. Also, Multiverse-Inventories is no longer supported. Please check out [PWI](https://www.spigotmc.org/resources/per-world-inventory.4482/) which supports importing your MV-inventories files.
