### ISSUE TITLE
World can't be loaded

### ISSUE THREAD

**Issue by capew1** [Multiverse/Multiverse-Core#1706]

**Comment by capew1** [comment]
log couldnt be uploaded. anyways, the issue is that my world 'world' cant be loaded. i do /mv load world and it says detail;s have been printed to the log, but i cant upload it

**Comment by FernFerret** [comment]
This ticket isn't well written, so I'm going to close it. If you want to post some more information, [have a look at our wiki](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and write a better ticket.
