### ISSUE TITLE
Random errors in console, I have not found a way to trigger them.

### ISSUE THREAD

**Issue by Xzeajan** [Multiverse/Multiverse-Core#1707]
I keep having random lines of text like these in my console, any way to get them out? They are scary.
Yet in-game I have no issues

I only use multiverse core.  v2.5-b641

![image](https://cloud.githubusercontent.com/assets/18505109/14686399/ceb02822-0738-11e6-8495-4de5dee6af97.png)

![image](https://cloud.githubusercontent.com/assets/18505109/14686473/1bbf3e46-0739-11e6-86d5-5fdda53a0457.png)

**Comment by dumptruckman** [comment]
You need to the latest dev builds for 1.9. http://ci.onarandombox.com/view/Multiverse/
