### ISSUE TITLE
Unloading a world will sometimes put people into a restricted world.

### ISSUE THREAD

**Issue by Codingale** [Multiverse/Multiverse-Core#1709]
For example if we have 4 worlds:

Lobby
Build
Survival
Secret

If we unload survival sometimes people who join will relog into Secret world, even though they shouldn't have access to it. Is there a way to fix this/prevent it?

**Comment by FernFerret** [comment]
Hmm. I thought there was a "default" world, that people got placed in if something else went wrong. Is your Secret world your first world on the server?

**Comment by Codingale** [comment]
It honestly seems random what world they're place in sometimes it's normal worlds. We have a lot more than the example.
