### ISSUE TITLE
---- ShadowCloud --- Need Help --- 

### ISSUE THREAD

**Issue by xVanquished** [Multiverse/Multiverse-Core#1710]
Ok, The Issue is, We Have 2 Worlds, 1 Normal and the second one will be Skywars, We want them so they can talk to eachother in both worlds. But The Issue Is, We tried all the Commands, Seen every Report, If I Missed something Please Help, (Version 2.9) Or comment the Command Please, We'll Be # Waiting,

Regards Vanquished

**Comment by mcarey10** [comment]
Hi, Please Stop Talking Like This.
With Love,
Matt

**Comment by FernFerret** [comment]
This issue either does not have enough details, or details have been requested and not provided. Please read up on "[submitting a bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug)" and form a more complete bug report.
