### ISSUE TITLE
I don't know what to do....

### ISSUE THREAD

**Issue by Deem17** [Multiverse/Multiverse-Core#1714]
Hi all,

I recently made a world with a spawn in it, after a week or two i wanted to check my world again and now i have this..... Its a shield around my spawnpoint. I have no idea what it is or how to fix it, i hope someone else can help me!

![2016-05-04_16 50 15](https://cloud.githubusercontent.com/assets/19190103/15018084/8112358e-1218-11e6-9b8f-a015b3c6a97b.png)
![2016-05-04_16 50 35](https://cloud.githubusercontent.com/assets/19190103/15018104/9087ffe4-1218-11e6-91cc-74e79aaeed56.png)

**Comment by FernFerret** [comment]
This has nothing to do with multiverse. Try disabling other plugins.
