### ISSUE TITLE
Bug Respawn world

### ISSUE THREAD

**Issue by Alibabaand40voleur** [Multiverse/Multiverse-Core#1716]
Hi, when i die, i don't respawn in the world configurated in my config world.
We tested to remove bed spawn in essentials ; bedRespawn: 'false'
We tested to fix in essentials ; respawn-listener-priority: lowest
We tested to remove Essentials.spawn
We tested to remove all my plugins et just let Multiverse-Core
And the spawn point x y z is safe.

So i don't know wher is the problèm and why i don't respawn in the world configurated..
I need ur help : Soory for my bad english :p

**Comment by FernFerret** [comment]
Hi there. 

I don't quite understand the configuration that you have. Please read up on "[submitting a bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug)" and specifically post the results of `mvv -g`.

**Comment by Oruss7** [comment]
bedRespawn: 'true'
Set it to false in your world config (multiverse)
