### ISSUE TITLE
Multiverse Worlds staying unloaded when startup

### ISSUE THREAD

**Issue by Difluoride** [Multiverse/Multiverse-Core#1717]
When restarting my server, the worlds I have created stay unloaded. I tried the /mv anchor command and received the following error:
http://hastebin.com/yekaqikeha.avrasm

Also, this is after the command:
/mv version -g:
http://hastebin.com/zemovolupi.css

**Comment by CakeLady** [comment]
I am having this same issue, and when I run /mv import (world) normal, i get "An internal error occurred when attempting to perform this command"  The weird thing is that I do not get this on all the worlds, or even the same worlds consistently.  I have tried removing the plugin and reinstalling it (several times), removing world edit, and a few other things I cant remember right now. 
http://hastebin.com/esaqinuqax.vbs
