### ISSUE TITLE
Cannot change difficulty setting at server start

### ISSUE THREAD

**Issue by Giordano22** [Multiverse/Multiverse-Core#1718]
I have tried the command /mvm set diff 0 Craftia and that works, until the server is restarted.
I have changed the entry in worlds.yml, while the server is not running, but the server rewrites those values at startup. The world always loads with difficulty set to easy.

I am running Thermos 1.7.10-1558 with a custom pack of mods. I can list them if it is relevant.

**Comment by FernFerret** [comment]
This issue either does not have enough details. Please read up on "[submitting a bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug)" and form a more complete bug report, thanks!

**Comment by Loonyy** [comment]
Did you ever fix this issue? I'm having the same problem.
