### ISSUE TITLE
Console each world command

### ISSUE THREAD

**Issue by woutereng** [Multiverse/Multiverse-Core#1719]
For example, I'm running multiverse with tons of worlds
I want to do a server command wich only does that in that specific world
in my example, I'm running a townyserver
I want to do the command /townyworld toggle forcepvp
it says it can't do that because of invalid world
is there a way to get a command such as: /mv [world] townyworld toggle forcepvp?

**Comment by FernFerret** [comment]
Most MV commands do support any world (where they make sense). Other plugins will have to implement the Multiworld API (in Spigot/Bukkit/etc.) as well if they wish to take advantage of having a multiworld plugin.
