### ISSUE TITLE
Cannot select a player in a specific world

### ISSUE THREAD

**Issue by AndreasEK** [Multiverse/Multiverse-Core#1722]
It'd be nice if I could do something like

clear @a[tag=!setup,world=adventureworld]

to setup players in an adventure world. Later, at the end of the setup process, the user would be added the tag "setup".

**Comment by AndreasEK** [comment]
My only workaround at the moment is to do something like:

@a[tag=!setup,x=-261,y=82,z=-402,r=100000]

It appears that the check for coordinates restricts the selection to work only in the world, the command block itself is in

**Comment by FernFerret** [comment]
Hmm what context is this being used in? How does this apply to Multiverse? Sorry for the confusion, more curious than anything right now!

**Comment by AndreasEK** [comment]
well, we have a community server, and are currently building an adventure map, and I would like to setup players when they enter the map. (So, when they don't have the tag yet, but are in the specified world).

add something to their inventory, add a score to the scoreboard, etc.
