### ISSUE TITLE
Unknown console error

### ISSUE THREAD

**Issue by DLDOLPHIN** [Multiverse/Multiverse-Core#1723]
Problem:
Keep receiving this error:
http://pastebin.com/FEAtV1a6

Link generated from /mv version -g:
http://pastebin.com/iVKhFmUG

Startup log:
http://pastebin.com/GeWgGnKz

**Comment by TWSSYesterday** [comment]
PlotSquared is giving out an error, I'd update to the latest of both Multiverse-Core and PlotSquared and then try to reproduce, If you need further help, feel free to ask!

**Comment by Jadiction** [comment]
Closing ticket. Please open a new ticket with more valid information if this issue is still occurring in the latest versions.
