### ISSUE TITLE
No syntax for specifying teleportation to a player's own bed.

### ISSUE THREAD

**Issue by totemo** [Multiverse/Multiverse-Core#1724]
We're trying to replace the vanilla end portal with a multiverse portal to avoid some 1.9 glitchiness.

I can see that the BedDestination class actually supports a player's own bed [if the player name is empty](https://github.com/Multiverse/Multiverse-Core/blob/master/src/main/java/com/onarandombox/MultiverseCore/destination/BedDestination.java#L65), however, it is impossible to specify such a destination because DestinationFactory validates destinations by calling isThisType() and the BedDestination.isThisType() method requires a valid player name and offers no syntax with the meaning of "this player".

I note that one previous issue, #137, asked for the same thing and there was a linked document in that discussion that purported to solve the issue, however, that page is now gone from the internet and the [current documentation for destinations](https://github.com/Multiverse/Multiverse-Core/wiki/Destinations#bed-destinations) is of no assistance in this matter.

So, at the very least, the documentation is somewhat incomplete in that it doesn't categorically rule out teleportation to a player's own bed (which would save some time in searching for a solution), but I would hope that you might see the problem as more of a missing feature.

Cheers.

**Comment by ryantheleach** [comment]
Apologies,  I may have written this bug a long time back.

From what I see, it should still be backwards compatible with the old way of specifying the players bed, which was literally "b:playerbed" 

I'm surprised that "b:" wouldn't throw an exception actually...

**Comment by Sonuvaharris** [comment]
Bump.

Also running into this issue. 
Triggering a portal with dest b:playerbed throws an error.
Also an issue with /mv tp b:playerbed.

**Comment by Jadiction** [comment]
Actually, re-opening this because I just tested this again and it seems when you do _/mv tp b:playername_, it only works when you're in the world that the bed is at, it's not found/blocked in other worlds. This might be intentional, not sure. So not sure if this is a bug or not.

As for using a portal set to _dest b:playername_, it does throw an error, on both the world the bed is in and a world it isn't. Error: https://pastebin.com/raw/5UWvnjQg
