### ISSUE TITLE
Add "generator settings" like Minecraft vanilla

### ISSUE THREAD

**Issue by JohOply** [Multiverse/Multiverse-Core#1725]
Hi guys

Could you add generator settings like in the server.proporties file, to be able to custom each world ?

Thank you for reading :)

**Comment by RianOBrian** [comment]
Hi JohOply,

To get custom generator settings for each world, use a generator when creating that world. The server.properties file is only for 'world' because adding worlds is part of a separate plugin.

Thanks,
Rian

**Comment by c0wg0d** [comment]
I would love to get support for this as well.  Please make it happen!

**Comment by JohOply** [comment]
Hi Rian,

I don't want use generator because i want a stable world for all minecraft versions (i dev stoped his plugin, how can i continue?)

I speak about generator from properties because it is the example which can be applied in MV :)
