### ISSUE TITLE
Cant go through end/nether portals

### ISSUE THREAD

**Issue by QuadraNetwork** [Multiverse/Multiverse-Core#1727]
Hello
I have a Problem with the Nether and the end in new created worlds.
I think I know where the problem is but i dont know how to solve it.
In Multiverse there is always the default world called "world" and for this world there is a end and a nether. The Nether world is called world_the_nether and the end word_the_end.
And I think this is the problem because for my new generated worlds there are no (worldname)_the_nether or (worldname)_the_end worlds generated. Is there a way to create an end and a nether for my new worlds? :)

**Comment by TheOtakuJames** [comment]
You should be able to do '/mvcreate (worldname)_nether nether' and '/mvcreate (worldname)_the_end end'. I used to have that problem and I just created them like that. Hope this helps!

**Comment by goldenmasterly** [comment]
I have been having this problem and i tried '/mvcreate (worldname)_nether nether' and '/mvcreate (worldname)_the_end end' and that didn't work

**Comment by TheOtakuJames** [comment]
Oh that is strange? What worlds do you have?

**Comment by goldenmasterly** [comment]
the worlds i have are
Galifrey
Galifrey_the_end
world
world_the_end
world_the_nether
minigames
and nether and end portals only work in world

**Comment by TheOtakuJames** [comment]
Hmm ok. try deleting Galifrey_the_end (love the name btw) and then re-creating it, and a Nether one. If not I'm unsure how to fix this sorry :(
