### ISSUE TITLE
WorldTp

### ISSUE THREAD

**Issue by AcePlays** [Multiverse/Multiverse-Core#1728]
Okay So Ive setup a gui so when a player clicks on the item in the gui it does a command /mvtp Factions {Player} I need it so when they click it again in that world it sais something like "Your already in this world"

**Comment by AcePlays** [comment]
*Gui Menu

**Comment by AcePlays** [comment]
Also Would there be a plugin that does this for me other the mv?

**Comment by FernFerret** [comment]
Multiverse simply provides you access to the Multi-World API provided by Bukkit. You should check to see if someone is already in the world before running your command from the GUI.

The reason we allow people to teleport to the same world, is that `/mvtp world` actually means "take me to the spawn of world" not just "take me to world".
