### ISSUE TITLE
Multiverse first join spawn not working properly

### ISSUE THREAD

**Issue by Elvi81** [Multiverse/Multiverse-Core#1729]
I can't for the love of me get first join spawn to be directed to the multiverse spawn, it ALWAYS goes to the old server World.

Config.yml http://pastebin.com/BP3Z3433, Worlds.yml http://pastebin.com/MrBLv62D

Here's even the Essentials config just for the heck of it Config.yml http://pastebin.com/CRwU5CaB

As you probably can see, most is as it should be but yet it goes to the wrong spawn.

/mv setspawn done in both Worlds.
/spawn redirected to /mv spawn via commands.yml.
/spawn in Essentials disabled.

Also here's a link to a similair post over on the spigot forums just to show what already has been suggested.
https://www.spigotmc.org/threads/multiverse-first-join-spawn.155229/

Mc version is 1.9.4.

Plugins include:
AutoSaveWorld
BetterShops
BossBarAPI
Citizens, Blacksmith, Denizen,Sentry
Essentials, Chat, GroupManager, Spawn
GriefPrevention
InfernalMobs
MarioKart
MassiveCore, CreativeGates
mcMMO
MobArena
Multiverse-Core, Portals
ProtocolLib
PurpleIRC
Quests
uCars
Vault
WizardlyMagic
WorldEdit, Guard

**Comment by FernFerret** [comment]
Issue acknowledged, but I don't have time to look at this right at this moment. I remember us putting in something specific for this at one point... I'll respond more later.
