### ISSUE TITLE
Multiverse-NetherPortals Spawn in block or under world

### ISSUE THREAD

**Issue by TheKekoslovakian** [Multiverse/Multiverse-Core#1730]
My 1.10 Minecraft Server running Spigot 1.10 R0.1 (obviously) has been having problems with Nether Portals. I use Multiverse-NetherPortals and Multiverse-Portals with the regular Multiverse-Core. I have my Wild world linked with the Wild_nether world using MV-NetherPortals. Portals made near the Wild world spawnpoint work normally, almost, with the exception of often being put into blocks and suffocating and upon '/back' being put into a safe Nether environment. It's almost as if Multiverse's safe area detector broke and Essentials's works. But here's where the worse problems start. If a nether portal is built far away from the Wild world spawnpoint the nether portal brings people under the Nether, typically at the y value of around -11,000. I have no explanation for why this is. I really need help as this is server breaking and I have to have the server on maintenance. If anyone needs more specific info just reply to the thread and all help will be greatly appreciated! Also, no nether portals appear with the teleportation.

Plugin List: EssentialsX, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, ChestShop, PermissionsEx, WorldEdit, WorldGuard, PerWorldInventory, FUBS Random Teleport, Factions, MassiveCore, AutoSaveWorld, Vault

**Comment by FernFerret** [comment]
Interesting, I haven't yet test MV in 1.10 (haven't gotten my server updated yet), but I should be able to this weekend.

As for the Safe-T-Teleportor not working, that would indicate that something is wrong with the server, since I just use `sendTo`. Try updating your Spigot (as they say, make sure you update every few hours).

If you could also post the result of `/mv version -g`

**Comment by TheKekoslovakian** [comment]
I'm not sure its the server. But it may be. I see several other people having similar issues. [http://dev.bukkit.org/bukkit-plugins/multiverse-netherportals/](http://dev.bukkit.org/bukkit-plugins/multiverse-netherportals/)

If you Google [Multiverse-NetherPortals Spigot](https://www.google.com/search?q=Multiverse-NetherPortals+Spigot&ie=utf-8&oe=utf-8#q=Multiverse-NetherPortals+Spigot+site:www.spigotmc.org) you can see other people having this problem. Also, how do I check for updates on Spigot, are they announced on the main page or are smaller updates announced elsewhere?

Result of `/mv version -g`: 
[Link to Output](https://gist.github.com/anonymous/b27a90751fb3b683570a37360e51e5a7)

**Comment by Aarronmc** [comment]
Im having this exact same issue, was there ever a resolution for it?

**Comment by FernFerret** [comment]
I've heard some mumblings of this issue on my server, but no concrete testing has happened. tldr: I don't know what's causing this, or if it's MV's fault or what a workaround/resolution exists.

My server is down for maintence for probably the next week, I'll poke some friends to see if they can reproduce this and if we can find out a resolution.

**Comment by CoolLord22** [comment]
Any word on a resolution? Another issue I have is that the netherportals from a world teleport a player inside blocks in the nether. and a new portal is never formed.

**Comment by CoolLord22** [comment]
Well, kinda stupid here- I just downloaded build 712 and it all works fine now. https://ci.onarandombox.com/job/Multiverse-NetherPortals/712/
