### ISSUE TITLE
End World - Dragon Respawn With Restart

### ISSUE THREAD

**Issue by Beaupedia** [Multiverse/Multiverse-Core#1731]
We created an End world with Multiverse that we use as a creative world, unfortunately as of 1.9 the enderdragon respawns with every restart. We've disabled mob spawning, set the world to peaceful. None of it works.

If we kill the dragon normally, with swords, etc. it will stay dead until a restart. Any ideas?

**Comment by FernFerret** [comment]
Hrm. This is something I can say that I haven't tested... at all. Multiverse really doesn't control any of the respawning behavior other than acting as a proxy for the server. Could you post the output of `/mv version -g`?

**Comment by Beaupedia** [comment]
Here's what we get:

[Multiverse-Inventories] Multiverse-Inventories Version: 2.5-b410
[Multiverse-Inventories] First Run: false
[Multiverse-Inventories] Using Bypass: false
[Multiverse-Inventories] Default Ungrouped Worlds: false
[Multiverse-Inventories] Using GameMode Profiles: false
[Multiverse-Inventories] === Groups ===
[Multiverse-Inventories] default: {Worlds: [world, world_the_end, world_nether], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest]}

**Comment by SimSonic** [comment]
Some changes?
