### ISSUE TITLE
After install of multiverse logs are getting filled with spam of kicking

### ISSUE THREAD

**Issue by Elvi81** [Multiverse/Multiverse-Core#1732]
So as the tital says, the logs are getting filled with kicks from flying and this is while in creative mode.
This is what it can look like http://pastebin.com/2fJ0mwjP
And in return this spills over to purpleirc so the irc chat get's spammed too forcing me to restart the server to make it stop.
Current mc version, 1.9.4

**Comment by TheOtakuJames** [comment]
I also have this problem, hope it can be fixed soon. (I am on 1.10)

**Comment by TWSSYesterday** [comment]
Cannot replicate using latest server and Multiverse-Core versions.
