### ISSUE TITLE
Never turns to night time...

### ISSUE THREAD

**Issue by TheOtakuJames** [Multiverse/Multiverse-Core#1734]
Hia,

Recently on my server I have been having a glitch where the day never turns to night. Now I know it's not the gamerule (or mvgamerule) doDaylightCycle, as the sun does move, just as soon as it gets to sun set and starts to set, it teleports back to sunrise and restarts the day. It has not been night on my server for over a week, and it happens in all my worlds.

So to test which plugin was causing it, I hired a free server to do some testing on. I installed the main ones I thought would do it one by one (Essentials, WorldEdit, and Multiverse-Core) and once I got to putting multiverse on the problem appeared. Uninstalled Multiverse-Core, and it went to night.

How can this be fixed? I've narrowed it down to Multiverse-Core, and have made sure the doDaylightCycle is true in all worlds.
Here's my config: http://pastebin.com/rfrERpzb
And here's my worlds.yml: http://pastebin.com/KTZWgXwV
I am using the latest Spigot 1.10 build, and the latest Multiverse-Core build.

Thanks for the help,
~James

**Comment by TheOtakuJames** [comment]
Bump

**Comment by SentryTheDefiant** [comment]
What happens when you do a /time set day  in each world? does the time tick forward like it should? Are you running any plugins that might lock the time? If so, I'd try removing them and their configs an add them after you've already loaded and stopped your server with all other plugins installed.

**Comment by TheOtakuJames** [comment]
When I do /time set day, the same thing happens. Also when I change it to night, it does the round of night and gets stuck on day. The only plugins that I have that can control time are the normal Essentials and Minecraft time settings, and of course the time lock on Multiverse. The Essentials one just stops it in one place, and the sun does not move at all, which is different to the problem I am having. I can't uninstall either Multiverse or Essentials either, as they would break the server - I have many worlds through Multiverse, and homes, warps, nicks etc. would be removed if I uninstalled Essentials.

**Comment by TWSSYesterday** [comment]
Issue still occurring on latest Paper Spigot build?

**Comment by TWSSYesterday** [comment]
Cannot replicate using latest server and Multiverse-Core versions. If this is still an ongoing issue, please let us know.

**Comment by GaMingN21** [comment]
I have the same problem I do not know myself how it should be clear that it is to 1 plugin "multiverse core" you can change with essentials / ptime (playertime) but then there are no mobs spawning because it is not a real night alone for that player I am looking for solutions myself ...
