### ISSUE TITLE
Replacement

### ISSUE THREAD

**Issue by WatchAc** [Multiverse/Multiverse-Core#1735]
Hello, I've installed a plugin called lobby watch which is for teleporting from world to world , but I don't know how to do it with multiverse. When I put the command for example /mv tp Survival x y z It says in the game /mv tp player world x y z . How can I make it that the player selecting the item in the watch menu is teleported to the world with the coordinates ( %player% and @p don't work ).

**Comment by TWSSYesterday** [comment]
https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#teleport-command
