### ISSUE TITLE
console error every few minutes

### ISSUE THREAD

**Issue by Ac3dUd3** [Multiverse/Multiverse-Core#1736]
I keep getting this error every few minutes in the console, but the plugin still seems to work perfectly fine
Im on spigot 1.10
MV ver is 2.5-b688

Error http://hastebin.com/webotatidi.avrasm

**Comment by DRP96** [comment]
Same here (Bukkit 1.10)

**Comment by TWSSYesterday** [comment]
Still having this issue on latest spigot/paper spigot build and latest Multiverse?

**Comment by Ac3dUd3** [comment]
no idea personally, i shut my network down months ago, im thinking about opening again so if i run into the same issue i will tell you

**Comment by TWSSYesterday** [comment]
Sorry to hear about your network, I hope you re open it!
