### ISSUE TITLE
Continued Console Error

### ISSUE THREAD

**Issue by Beaupedia** [Multiverse/Multiverse-Core#1737]
Getting errors every few minutes: http://hastebin.com/govosaxoya.avrasm

Multiverse-Core version 2.5.0-SNAPSHOT-b722
Multiverse-Inventories version 2.5-b410
Spigot 1.10

**Comment by TWSSYesterday** [comment]
Is this issue still occurring? (Also, the hastebin has timed out)

**Comment by Beaupedia** [comment]
Yeah, it still occurs regularly.  Here's the error: https://pastebin.com/J76Kmixi

**Comment by dumptruckman** [comment]
https://github.com/Multiverse/Multiverse-Inventories/blob/master/README.md
