### ISSUE TITLE
Failure to load

### ISSUE THREAD

**Issue by MooshroomStatus** [Multiverse/Multiverse-Core#1738]
I restarted my server (mind you, all I did was remove a small plugin that had nothing to do with essentials or multiverse or anything) and suddenly multiverse was no longer working. The plugin just completely stopped. All of my worlds were gone from the in-game list, yet still in the worlds.yml list, and I can't re load my worlds back onto the server without getting "Error trying to load world [WORLD]!"

http://pastebin.com/FPMDA3dr

I'm not sure what happened, but out of the blue, everything was just gone.

I'm using the latest version of Multiverse with Spigot 1.9.4

**Comment by TWSSYesterday** [comment]
Are you still seeing these issues on the latest Paper Spigot build?

**Comment by TWSSYesterday** [comment]
Cannot replicate using latest server and Multiverse-Core versions. If this is still an ongoing issue, please let us know.
