### ISSUE TITLE
Is this dead? no updates to fix stuff for ages!!

### ISSUE THREAD

**Issue by krustymk** [Multiverse/Multiverse-Core#1740]

**Comment by chezpaul** [comment]
It is dead. No one's home. Such a shame

**Comment by TWSSYesterday** [comment]
What's broken? For 99% of people that use the plugin, there are no issues. It doesn't need updating every minecraft version. If you have an issue, use the issue tracker which this location is. Include a sensible title and description and provide logs and configuration files.
