### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ayrtonneke** [Multiverse/Multiverse-Core#1741]
As far i know the plugin works just fine.
But i keep getting this message in the console.
I don't know much about these things so can someone give me a solution?

> ERROR]: Error occurred while enabling Multiverse-Core v2.5-b688 (Is it up to date?)
> java.lang.NoSuchMethodError: org.bukkit.entity.Projectile.getShooter()Lorg/bukkit/entity/LivingEntity;
>         at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.purgeWorld(SimpleWorldPurger.java:110) ~[?:?]
>         at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.purgeWorld(SimpleWorldPurger.java:196) ~[?:?]
>         at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.purgeWorld(SimpleWorldPurger.java:73) ~[?:?]
>         at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:428) ~[?:?]
>         at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:402) ~[?:?]
>         at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:377) ~[?:?]
>         at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:676) ~[?:?]
>         at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:306) ~[?:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:362) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:322) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at org.bukkit.craftbukkit.v1_9_R2.CraftServer.reload(CraftServer.java:746) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at org.bukkit.Bukkit.reload(Bukkit.java:539) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1349) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1184) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
>         at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
>         at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-798f32d-0cd0397]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]

**Comment by Ayrtonneke** [comment]
Another one

> WARN]: Exception in thread "Craft Scheduler Thread - 0"
WARN]: org.apache.commons.lang.UnhandledException: Plugin Multiverse-Core v2.5-b688 generated an exception while executing task 20
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at org.mcstats.multiverse.Metrics.postPlugin(Metrics.java:357)
        at org.mcstats.multiverse.Metrics.access$400(Metrics.java:64)
        at org.mcstats.multiverse.Metrics$1.run(Metrics.java:245)
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by Ayrtonneke** [comment]
it gives this warning each 10 minutes

**Comment by TWSSYesterday** [comment]
Updated to latest? Server versions? Config files? Please use pastebin

**Comment by TWSSYesterday** [comment]
Cannot replicate using latest server and Multiverse-Core versions. If this is still an ongoing issue, please let us know.
