### ISSUE TITLE
Removed worlds reappear after some time

### ISSUE THREAD

**Issue by WInf9Kieran** [Multiverse/Multiverse-Core#1743]
Hello.
Does anybody know why the world "test" and "creative_world2" keep getting regenerated?
I can see both in /mv list but I want them to be gone. When I do /mv delete test I have to confirm it and the world is temporary gone. But after some time and restarts both appear again.

The difficulty in one world gets reset aswell. I want peaceful but after a restart it's easy again. Why?

CraftBukkit: git-Bukkit-00359a1 MC: 1.10.2
MV: Multiverse-Core Version: 2.5.0-SNAPSHOT-b722

**Comment by Flipkidd** [comment]
I'm having a familiar issue with this, but it won't even let me delete the world. Check if they are you default worlds or something, and look for console errors. Hope this helps

**Comment by TWSSYesterday** [comment]
This deletes the world, not remove it from your worlds.yml. Do /mv remove to do that.
