### ISSUE TITLE
Crash on connexion 

### ISSUE THREAD

**Issue by Gohu29** [Multiverse/Multiverse-Core#1744]
Hello everyone. I have a problem when i connect on my serveur. it's modded server.

I created a world with Multiverse this world have Id 3.
When I'm connecting forge doesn't reconize the world and shut down my launcher.
This world have "keep spawn memory" in true.

http://pastebin.com/ibv6BRfX

**Comment by Jadiction** [comment]
Closing ticket. Please open a new ticket with more valid information if this issue is still occurring in the latest versions.
