### ISSUE TITLE
Help !!

### ISSUE THREAD

**Issue by shootcraft** [Multiverse/Multiverse-Core#1751]
Some worlds automatically unloaded when I restart the server

**Comment by TWSSYesterday** [comment]
Logs, and versions please, we need more info to help

**Comment by VladasX** [comment]
I have the exact same issue.

/ver Multiverse-Core shows:
2.5-b688

Logs: [https://paste2.org/4s024Gjs](url)

**Comment by TWSSYesterday** [comment]
Closing due to latest dev build fixing the issue. Will upload as an AB when testing has finished
