### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by Yunk21** [Multiverse/Multiverse-Core#1752]
Multiverse version:  Multiverse-Core v2.5-b688
Server version : Spigot 1.10

[Here is a link to the error](http://hastebin.com/ixaqujukup.avrasm)
Any help would be greatly appreciated!

**Comment by TWSSYesterday** [comment]
Please update to the latest version: https://ci.onarandombox.com/job/Multiverse-Core/lastSuccessfulBuild/artifact/target/Multiverse-Core-2.5.0-SNAPSHOT.jar

**Comment by Yunk21** [comment]
Thanks that fixed it!
