### ISSUE TITLE
MultiVerse Crashes server on join

### ISSUE THREAD

**Issue by seanfrasure** [Multiverse/Multiverse-Core#1753]
Crashes when I or another player try to join the server. After removing MultiVerse the problem seems to be gone so I think this is the problem.

Crash log: http://pastebin.com/raw/KagAn31K
Crash report: http://pastebin.com/raw/3dSeBBX5

**Comment by TWSSYesterday** [comment]
Versions?

**Comment by seanfrasure** [comment]
MultiVerse version 2.1

**Comment by TWSSYesterday** [comment]
Server version?

**Comment by seanfrasure** [comment]
Server Version 1.7.10

**Comment by TWSSYesterday** [comment]
Multiverse version?.

**Comment by seanfrasure** [comment]
MultiVerse version 2.5

**Comment by TWSSYesterday** [comment]
Use /ver Multiverse-Core

**Comment by seanfrasure** [comment]
I can't... When anyone joins the server instantly crashes... I have MultiVerse disable right now. I also already said "MultiVerse version 2.5" in 3 other comments (including a pastebin).

**Comment by TWSSYesterday** [comment]
And I've said to do /ver Multiverse-Core because there is more than one version of Multiverse 2.5

**Comment by seanfrasure** [comment]
Multiverse-Core version 2.5-b641

**Comment by TWSSYesterday** [comment]
That version is quite out of date

**Comment by seanfrasure** [comment]
It's the latest one I can get with Bukkit

**Comment by TWSSYesterday** [comment]
Try the latest here: http://ci.onarandombox.com/view/Multiverse/

**Comment by seanfrasure** [comment]
I installed "Multiverse-Core-2.5.0-SNAPSHOT-javadoc.jar" and it doesn't show up with /pl after reloading/restarting the server multiple times. A config also doesn't show up. I will re-check all the files soon.

**Comment by TWSSYesterday** [comment]
You want this version: https://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/lastSuccessfulBuild/artifact/target/Multiverse-Core-2.5.0-SNAPSHOT.jar

**Comment by seanfrasure** [comment]
I used that version but it still crashes with all the same logs/reports. I'm not sure whats wrong.

**Comment by seanfrasure** [comment]
I tried deleting the config folder and it still crashes.

**Comment by TWSSYesterday** [comment]
Are you still having issues?

**Comment by seanfrasure** [comment]
No, after removing a world it worked fine. I figured out that every time I went into one part of the map, the server  would crash. I deleted that world. Thanks for all the help!
