### ISSUE TITLE
WARN Exception in thread "Craft Scheduler Thread - 628" - How do I solve this error?

### ISSUE THREAD

**Issue by Fusion09a** [Multiverse/Multiverse-Core#1754]
The following keeps occurring about every 5 minutes on my server. Not sure how to fix it.

24.08 10:20:20 [Server] INFO ... 3 more
24.08 10:20:20 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
24.08 10:20:20 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
24.08 10:20:20 [Server] INFO at org.mcstats.multiverse.Metrics$1.run(Metrics.java:245)
24.08 10:20:20 [Server] INFO at org.mcstats.multiverse.Metrics.access$400(Metrics.java:64)
24.08 10:20:20 [Server] INFO at org.mcstats.multiverse.Metrics.postPlugin(Metrics.java:357)
24.08 10:20:20 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
24.08 10:20:20 [Server] INFO at java.lang.Thread.run(Unknown Source)
24.08 10:20:20 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
24.08 10:20:20 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
24.08 10:20:20 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
24.08 10:20:20 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Multiverse-Core v2.5-b688 generated an exception while executing task 7937
24.08 10:20:20 [Server] WARN Exception in thread "Craft Scheduler Thread - 628"

**Comment by TWSSYesterday** [comment]
Have you:
Tried updating either Multiverse/Your server jar?
What are your configurations?

**Comment by Fusion09a** [comment]
We are on the Multiverse 2.5 build as it solved some other issues we had in the past. The server jar is the latest Spigot build for 1.10.2

**Comment by TWSSYesterday** [comment]
What version of Multiverse 2.5, we have a lot. Do /ver Multiverse-Core to find out

**Comment by Fusion09a** [comment]
2.5-b691

**Comment by TWSSYesterday** [comment]
Update please, been quite a few versions since. https://ci.onarandombox.com/job/Multiverse-Core/lastSuccessfulBuild/artifact/target/Multiverse-Core-2.5.0-SNAPSHOT.jar

**Comment by Fusion09a** [comment]
Looks like it's resolved. Thanks. Will let you know if something pops up. Should fix the links on the main page as the latest download shows 2.5-b691

**Comment by TWSSYesterday** [comment]
It's the latest AB, dev builds are bleeding :)
