### ISSUE TITLE
Errors on world change

### ISSUE THREAD

**Issue by IndigoDreamer** [Multiverse/Multiverse-Core#1756]
We keep getting these errors spamming our console every time we change worlds. We have the latest dev builds of MV Core, MV Portals and MV Inventories installed from github on a 1.10.2 spigot server.

http://pastebin.com/6cXqtrtF

**Comment by TWSSYesterday** [comment]
Disable perworldplugins and try again.

**Comment by IndigoDreamer** [comment]
Already removed it and reinstalled. Per World Plugins is not the issue. Still no change. But I am starting to think multiverse is not the problem either anymore. Turns out it happens on any click event not just world change. I've messaged the author of MinigamesLib about the issue also. Hopefully he will know what the problem is.

**Comment by TWSSYesterday** [comment]
The error was from pwp

**Comment by IndigoDreamer** [comment]
No the error is still there when pwp is removed is just doesn't say at the top "ERROR **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****" anymore.

**Comment by TWSSYesterday** [comment]
Looks like you should speak to the developer of the MG plugins, they're the ones erroring out it would seem

**Comment by IndigoDreamer** [comment]
Yeah, trying to but he's being stubborn and refusing to help because I am having issues posting the error in the only place he will listen to them. Guess I'll just have to delete them. Thanks for trying to help though. Really kind of you :)

**Comment by MysticCity** [comment]
We dont refuse it:
All Time we say Just Post your Error on github.

But all time you say that you dont want use Guthub.... and now you say the BugTraker from github dont work....


But here all work ??? ^^

**Comment by IndigoDreamer** [comment]
I told you a fucking thousand times you stubborn wanker that I can't post it it wont let me"!
