### ISSUE TITLE
Multiverse Help

### ISSUE THREAD

**Issue by RedstonePro1-Minecraft** [Multiverse/Multiverse-Core#1757]
I try to go to my world, Spawn. And it says Multiverse does not know how to take you to Spawn. Then I do /mv import Spawn normal, and it doesn't work! What do I do?

**Comment by TWSSYesterday** [comment]
Logs?

**Comment by RedstonePro1-Minecraft** [comment]
My version of minecraft is 1.10.2. Do you support 1.10.2?

**Comment by TWSSYesterday** [comment]
We do indeed, could you do /ver Multiverse-Core please

**Comment by RedstonePro1-Minecraft** [comment]
The version is: 2.5-b641

**Comment by TWSSYesterday** [comment]
You should update to the latest on the dev build server.

**Comment by RedstonePro1-Minecraft** [comment]
What is The latest version?

**Comment by TWSSYesterday** [comment]
722, https://ci.onarandombox.com/job/Multiverse-Core/lastSuccessfulBuild/artifact/target/Multiverse-Core-2.5.0-SNAPSHOT.jar

**Comment by RedstonePro1-Minecraft** [comment]
Also wll it save all my worlds? Do I delete the folder of Multiverse? The .jar? Just delete the .jar and keep the folder?

**Comment by TWSSYesterday** [comment]
Keep the folder, just change the jar file

**Comment by RedstonePro1-Minecraft** [comment]
ok thanks

**Comment by TWSSYesterday** [comment]
Let me know how it goes.

**Comment by RedstonePro1-Minecraft** [comment]
how do I get rid of the part when I talk it says what world I'm in?

**Comment by TWSSYesterday** [comment]
Use /mv conf prefixchat false
