### ISSUE TITLE
Multiverse World Help

### ISSUE THREAD

**Issue by RedstonePro1-Minecraft** [Multiverse/Multiverse-Core#1758]
Hello, I found a weird glitch. When I do /mv tp Spawn, it teleports me there. But now, when I do /mv tp Spawn, It says Multiverse does not know how to take you there. When I do /mv import Spawn normal it gives me an error. I checked the worlds file and Spawn is still there. What do I do? I am running the latest version of Multiverse and 1.10.2 for Minecraft.

**Comment by TWSSYesterday** [comment]
Is this still an issue?

**Comment by Jadiction** [comment]
Closing ticket due to lack of information (and no response in a reasonable time). Please open a new ticket with more valid information if this issue is still occurring in the latest versions.
