### ISSUE TITLE
Multiverse vs. Warps

### ISSUE THREAD

**Issue by RazvanBossRO** [Multiverse/Multiverse-Core#1762]
When I create a new world with Multiverse from that world I can go to another world's warp!What can or should I do?

**Comment by TWSSYesterday** [comment]
Can you use warps in multiple worlds? Yes, try essentials x out.

**Comment by RazvanBossRO** [comment]
Ok,I will try!

**Comment by RazvanBossRO** [comment]
I didn't work! :(

**Comment by TWSSYesterday** [comment]
What part of it?

**Comment by RazvanBossRO** [comment]
Essentials x
