### ISSUE TITLE
Permissions help

### ISSUE THREAD

**Issue by LEEFFM** [Multiverse/Multiverse-Core#1763]
im not too great with permissions i was wondering if there is a way to make it so OP's do not have all permissions by default i am using multiverse core and multiverse signportals, basically i want a world that only guild members of our gaming community can access and a public world that all other op's and public members can access id prefer not to use a permissions plugin if possible otherwise i do have permissionsbukkit downloaded just not in the server yet. can anyone help with this?

**Comment by TWSSYesterday** [comment]
You'd need to have a permission plugin
