### ISSUE TITLE
MVCore vs AuthMe BUG

### ISSUE THREAD

**Issue by JiRt** [Multiverse/Multiverse-Core#1764]
## Hello. MV-Core ignores the config AuthMe plugin 

allowChat: false
        # Hide the chat log from players who are not authenticated?
        hideChat: false
        # Allowed commands for unauthenticated players 
##  and allowing gamers to write to chat before login / registration.

MC 1.10

**Comment by TWSSYesterday** [comment]
This would be the other way around. Multiverse shouldn't be intruding here. If you still continue to see this after reporting to AuthMe development team, please re open this issue.

**Comment by sgdc3** [comment]
This is our chat listener: https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/listener/PlayerListener.java#L98

Maybe MV is listening at LOWEST priority too...

**Comment by sgdc3** [comment]
@JiRt could you post your MV config?

**Comment by sgdc3** [comment]
@JiRt Firstly, update to latest AuthMe builds, we changed a lot of stuff since october...

**Comment by dumptruckman** [comment]
I don't see how this could possibly be related to MV. The only thing we do with chat is modify the format. We don't send any messages out so there's no way we're doing anything that would go against the normal flow of what Bukkit does. If the event shouldn't happen then we aren't causing it to happen.
