### ISSUE TITLE
World could NOT BE deleted

### ISSUE THREAD

**Issue by Flipkidd** [Multiverse/Multiverse-Core#1766]
I am trying to make a world named "Islands" with the generator "IsleWorldGen" Whenever I reload Multiverse, or restart the server it automatically generates a world named "Islands", without the generator. I tried to delete is but I get this: `[Server] INFO World could NOT be deleted!
16.10 07:24:45 [Server] WARN World 'Islands' could not be unloaded. Is it a default world?
16.10 07:24:43 [Server] INFO /mvconfirm will only be available for 10 seconds.
16.10 07:24:43 [Server] INFO please type: /mvconfirm
16.10 07:24:43 [Server] INFO If you still wish to execute mvdelete
16.10 07:24:43 [Server] INFO The command mvdelete has been halted due to the fact that it could break something!`

I change the `level-name=Islands` to `level-name=Isle` but when I reload the server it automatically changes it back to `level-name=Islands` Please PLEASE help me with this! Thank you very much 😀

**Comment by TWSSYesterday** [comment]
Worlds.yml?

**Comment by Flipkidd** [comment]
Sry, issue was fixed. The problem was that I was using Multicraft, and the default world was set to Islands which overrode my changes in the server.properties.
Thanks for your help anyways 😀
