### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by JugadorON** [Multiverse/Multiverse-Core#1767]
https://dev.bukkit.org/bukkit-plugins/multiverse-core/

I need version to 1.10.2, please!!!

Java 8!

**Comment by TWSSYesterday** [comment]
Use the latest dev build which you can find here: https://ci.onarandombox.com/job/Multiverse-Core/lastSuccessfulBuild/artifact/target/Multiverse-Core-2.5.0-SNAPSHOT.jar
FYI the latest on bukkit dev works okay on 1.10.2.
