### ISSUE TITLE
World won't import

### ISSUE THREAD

**Issue by michaeel1** [Multiverse/Multiverse-Core#1769]
I put a world I wanted to copy some building's from into my server files. The name of the file is thecube. So after it was done, I went to import them and I did /mv import thecube normal and I keep getting an error message saying "An internal error has occurred while attempting to preform this command.". I'm not sure what to do from here. Any ideas?

**Comment by TWSSYesterday** [comment]
Pastebin your latest.log please. Have you tried updating Multiverse + Server version

**Comment by Jadiction** [comment]
Closing ticket due to lack of information (and no response in a reasonable time). Please open a new ticket with more valid information if this issue is still occurring in the latest versions.
