### ISSUE TITLE
World commands?

### ISSUE THREAD

**Issue by SmallEnderman** [Multiverse/Multiverse-Core#1770]
i made a huge mistake... i made a world with multiverse and i tped to it. i changed the gamerule of randomTickSpeed a bit toooooo high... now everytime i try to join i automaticly crash the server.. and if i try to change the tickspeed inside the console it changes for the main world (stable) not the side world (unstable) pls help

**Comment by Jadiction** [comment]
Hi, the solution to this would be to use the command /mv gamerule as it allows for per world configuration with command usage (in the console as well). If you used the vanilla command to specify your gamerule, you can use a program to modify your level.dat file and modify your _randomTickSpeed_ value.

Closing ticket.
