### ISSUE TITLE
Difficulty stuck on 'HARD'

### ISSUE THREAD

**Issue by Loonyy** [Multiverse/Multiverse-Core#1772]
Hey,

Ever since I updated to Minecraft 1.10 and created a new main world, the difficulty has been stuck on hard for my "world" -- Everytime I try to reset it to easy in the config, it always changes back to hard. I've tried changing it in the config, through /mv commands and even with /difficulty.

I've tried to fix this on Multiverse 2.4 and multiple developer builds. Here's the version I'm currently running:
http://pastebin.com/NSXdvCyx

Worth mentioning that the 'world' is the only world I have this issue with.

**Comment by TWSSYesterday** [comment]
With a fresh worlds.yml, and then importing the world; do the commands set and stay set?

**Comment by Loonyy** [comment]
Huh?
What do you mean do the command set and stay set?

**Comment by Loonyy** [comment]
I have regenerated the worlds.yml and the default configuration for the world difficulty is on HARD and I cannot change it.

**Comment by TWSSYesterday** [comment]
Can you edit it via command? Does it save or does it instantly reset after a reboot?

**Comment by Loonyy** [comment]
It resets after reboot.

**Comment by Loonyy** [comment]
Deleting the level.dat in the world folder fixed this issue but Multiverse should be overwriting this anyway.

**Comment by FernFerret** [comment]
Interesting... I'll have to look, but this may be an upstream issue with the world management API.
