### ISSUE TITLE
When I try to load a world...

### ISSUE THREAD

**Issue by Rapolis** [Multiverse/Multiverse-Core#1775]
I try to load a world, this happens ALWAYS!!!!
An internal error has occured while attempting to perform this command.
WHY?! MY WORLD IS NOT CORRUPT OR ANYTHING AND I AM SO DONE WITH THIS STUPID ISSUE!!! Sorry if I act aggressive since I just got mad for wasting over 2 hours looking in the forums!!!
Please tell me what is the cause? I can't enter my console since my computer freezes from it.

**Comment by ljacqu** [comment]
Try to look for an error in your log and post it here.

**Comment by Rapolis** [comment]
errrr my logs are just.... gone by itself that i cant even paste it here! also i use a deprecated version of your plugin which fixes all my problems and has updated to 1.11........... argh just close this issue i am pretty sure all others have this problem

**Comment by ljacqu** [comment]
The problem is if you just post the generic error message:

> An internal error has occured while attempting to perform this command.

It literally means that: _something_ doesn't work. So you can imagine that it will be hard for anyone to help without any additional information.

**Comment by FernFerret** [comment]
as @ljacqu said, without a stack trace we have no idea what's going on. I have not *yet* tested with 1.11 but I believe the test constructor will explode. Please do the following things:

* [ ] Remember that all of this stuff you're dealing with (1.11) has not been verified yet.
* [ ] Download [a new build here](https://ci.onarandombox.com/job/Multiverse-Core/725/).
* [ ] If it works, great, if not, please post a stack trace.

I believe [this commit](https://github.com/Multiverse/Multiverse-Core/commit/3364709e537695f512c537d9657ee9fbf219c4dc) fixes the issue, but remember, this is a very turbulent (read: tough) time for the spigot guys. They're dealing with updating their internal APIs with all of the things that may have broken from the actual minecraft team.
