### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WilliamEstrela** [Multiverse/Multiverse-Core#1780]
http://prnt.sc/dhej10

**Comment by MythTheWolf** [comment]
When did this happen?
Details?

**Comment by TWSSYesterday** [comment]
Hey @WilliamEstrela the fault would lie with an old version of Multiverse that doesn't support the other plugin in the error or vice versa, please let us know if this is still an ongoing issue after having word from the developer of that plugin/extra
