### ISSUE TITLE
Wrong Gamemode when traveling between worlds

### ISSUE THREAD

**Issue by bloggy** [Multiverse/Multiverse-Core#1781]
I am administrator on my server with *-permissions. I keep losing my current gamemode when travelling to another world. How to fix this? I want all players to keep their gamemode when switching between worlds.

**Comment by Relaking** [comment]
Which Permission-Plugin are you using?
If you have set the _mv.bypass.gamemode.WORLD_ or _mv.bypass.gamemode.*_ permission, you should not loose your gamemode when switching your worlds.

**Comment by bloggy** [comment]
PermissionEx
