### ISSUE TITLE
Error on Spigot 1.11

### ISSUE THREAD

**Issue by Loonyy** [Multiverse/Multiverse-Core#1782]
http://pastebin.com/CBg4AfZS

Using V2.5 of MV

**Comment by TWSSYesterday** [comment]
You're using quite an old version of Multiverse, please update from our jenkins server.

**Comment by Loonyy** [comment]
..version 2.5 is the latest version from the Jenkins page..

**Comment by Loonyy** [comment]
http://pastebin.com/Zvv8eM8M my version.

**Comment by dumptruckman** [comment]
@Loonyy The version you were using when you created this issue is different than the one you last commented on having. The version you last commented about does not have this issue so I am closing this.

**Comment by Loonyy** [comment]
.. I haven't changed versions. I'm using the exact same version....

**Comment by TWSSYesterday** [comment]
Using build 688 in error, and 722 in mv version.
