### ISSUE TITLE
How to teleport ALL players in a certain world?

### ISSUE THREAD

**Issue by FrozenBeard** [Multiverse/Multiverse-Core#1783]
There dousnt seem to be a way to teleport all players that are in a certain world? Like I have an xmas world, and I want to unload it; I want to safely teleport everyone from this xmas world to spawn or somewhere safe, how do I do this?

**Comment by seanfrasure** [comment]
`/tpall` using Essentials/EssentialsX
Or you could make a simple Skript:
```Skript
command "/tpworldplayers":
        permission: staff
        trigger:
                loop all players:
                        if loop-player is in world "world":
                                teleport loop-player to player
                                message "&aTeleported!"
                                stop
```

**Comment by Jadiction** [comment]
Closing ticket because the solution is to use another plugin such as EssentialsX.

**Comment by MatthewMajf** [comment]
no fuck you nigger
