### ISSUE TITLE
console spam!

### ISSUE THREAD

**Issue by chillerkraft** [Multiverse/Multiverse-Core#1787]
i've narrowed this console spam down to multiverse core build725
please help me figure out why it started showing up about a week ago on all my servers
i somehow got it to stop on one of the servers but not the other 2. i dont remember how
http://pastebin.com/rQEYLPzA

**Comment by TWSSYesterday** [comment]
Haven't seen this, need a bit more information. latest.log on pastebin and server version please. (Please include build numers/hashes)

**Comment by chillerkraft** [comment]
http://pastebin.com/rUDUFqNb

[20:28:56 INFO]: This server is running CraftBukkit version git-Spigot-7d78b81-270755d (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by dumptruckman** [comment]
What process did you use to narrow this down to Multiverse? The only way you can really do that is by uninstalling **all** other plugins. If you didn't do that, then do that first before you assume the problem is related to MV. My guess is that the issue comes from another plugin and only happens when a certain world is loaded that would not be loaded without MV.

**Comment by chillerkraft** [comment]
i disabled plugins until disabling mvcore made the problem go away. i then re enabled all plugins except mvcore and confirmed it's mvcore. is there any other procedure i should try?

**Comment by chillerkraft** [comment]
i would stop the server, .disable a plugin, and then start the server again to see if issue was still occuring

**Comment by chillerkraft** [comment]
UPDATE: spam occured on my server where im not using multiworld. must be a different plugin. im suspecting islandworld. will investigate more and update here but yea. all good now. multiverse not to blame

**Comment by chillerkraft** [comment]
yea. it was islandworld.
