### ISSUE TITLE
Minecraft Forge support

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [Multiverse/Multiverse-Core#1789]
ok  I generated a world for direwolf20 difficulty a request Minecraft user    ford  one thing I have not all mod generate

i use Multiverse-Core in the past

**Comment by REVIEWGAMINGMAN** [comment]
Forge mods do not generate terrain/ores/scattered feature

**Comment by REVIEWGAMINGMAN** [comment]
hello

**Comment by Jadiction** [comment]
Closing ticket due to lack of information. Please open a new ticket with more valid information if this issue is still occurring in the latest versions.
