### ISSUE TITLE
AHHHH

### ISSUE THREAD

**Issue by Gregory1346** [Multiverse/Multiverse-Core#1793]
[url=https://postimg.org/image/so75jy5c7/][img]https://s23.postimg.org/so75jy5c7/2017_02_01_09_58_49.png[/img][/url]

[url=https://postimg.org/image/i2na7xz0n/][img]https://s23.postimg.org/i2na7xz0n/2017_02_01_09_58_55.png[/img][/url][/img][/url]
RIP all my builds!

**Comment by Gregory1346** [comment]
my bad, horrible links:
https://s23.postimg.org/kvghryzd7/2017_02_01_09_58_49.png
https://s23.postimg.org/4lqbp2op7/2017_02_01_09_58_55.png

**Comment by dumptruckman** [comment]
RIP this issue that doesn't have an explanation.

**Comment by dumptruckman** [comment]
However, your issue is your server software (most probably) and has nothing to do with Multiverse.

**Comment by CoolLord22** [comment]
Hm, I had the same issue before. The fix is really simple. Just stand in the messed up chunk, and leave the game and then come back. Boom! The chunk fixes itself 😄
