### ISSUE TITLE
Forge mods do not generate terrain/ores/scattered features

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [Multiverse/Multiverse-Core#1797]
Forge mods do not generate terrain/ores/scattered features

**Comment by REVIEWGAMINGMAN** [comment]
https://drive.google.com/file/d/0BzP-IJ_uCGD9Nm9zb1cxM2RvaFE/view?usp=sharing sorry pastebin IS not allow me to post trying to get me to upgrade to their Pro

**Comment by dumptruckman** [comment]
This has nothing to do with Multiverse.
