### ISSUE TITLE
Pvp issue? /mvm set pvp true and properties do not work?!?

### ISSUE THREAD

**Issue by Linebeck** [Multiverse/Multiverse-Core#1798]
Okay so I updated to the most recent build 745. The one on the spigot page worked the same way, where I had to run that command for everything to even work properly.

So here is the problem. I have WorldGuard, and Multiverse-Core. All my worlds should be set to pvp true. However, I want some regions to not be pvp enabled, that is why I have WorldGuard. I get no errors in console, and its just a really odd bug. 

When I swing my fist at someone inside of the flagged pvp deny zone. It just gives me that warning: "You can not pvp here", etc. But still continues to damage the other player....?

If you could help sort this out that would be great.

Thanks!

**Comment by Tzzzt123** [comment]
you want a complete world with pvp right? go to this world and do "/rg flag __global__ pvp allow"

**Comment by Jadiction** [comment]
I'll look into replicating this soon.

**Comment by Jadiction** [comment]
After trying: PVP set to false does not give any messages when attempting to PVP. It's likely your warning is coming from another plugin. Both PVP enabled & disabled work as intended with my tests.
