### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Loonyy** [Multiverse/Multiverse-Core#1799]
http://pastebin.com/K9jh8sfe

**Comment by TWSSYesterday** [comment]
Server version?
Server build?
Multiverse information?
Have you tried updating Multiverse? Is the error the same or does it not display anymore?
How can we replicate this?

**Comment by Loonyy** [comment]
25.02 11:57:39 [Server] INFO This server is running CraftBukkit version git-Spigot-7d78b81-f709362 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core] Multiverse-Core Version: 2.5-b688
25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core] Bukkit Version: git-Spigot-7d78b81-f709362 (MC: 1.11.2)
25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core] Loaded Worlds: [{"MVWorld@1412050122":{"Gen":"PlotSquared","Type":"NORMAL","Env":"NORMAL","Name":"PlotsSix"}}, {"MVWorld@216591785":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world"}}, {"MVWorld@1455093300":{"Gen":"PlotSquared","Type":"NORMAL","Env":"NORMAL","Name":"PlotsFour"}}, {"MVWorld@811456081":{"Gen":"PlotSquared","Type":"NORMAL","Env":"NORMAL","Name":"PlotsOne"}}, {"MVWorld@890560748":{"Gen":"PlotSquared","Type":"NORMAL","Env":"NORMAL","Name":"PlotsThree"}}, {"MVWorld@2119878210":{"Gen":"PlotSquared","Type":"NORMAL","Env":"NORMAL","Name":"PlotsFive"}}, {"MVWorld@2135983339":{"Gen":"PlotSquared","Type":"NORMAL","Env":"NORMAL","Name":"PlotsTwo"}}, {"MVWorld@560015886":{"Gen":"\u2018PlotSquared\u2019","Type":"NORMAL","Env":"NORMAL","Name":"IslandPlots"}}]
25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core] Multiverse Plugins Loaded: 0
25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core] Using Vault: true
25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core] Economy being used: Essentials Economy
25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core] Permissions Plugin: Bukkit Permissions (SuperPerms)
25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core] Dumping Config Values: (version 2.9)
25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core]  messagecooldown: 5000
25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core]  teleportcooldown: 1000
25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core]  worldnameprefix: true
25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core]  worldnameprefixFormat: ⊰%world%⊱ %chat%
25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core]  enforceaccess: true
25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core]  displaypermerrors: true
25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core]  teleportintercept: true
25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core]  firstspawnoverride: true
25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core]  firstspawnworld: PlotsOne
25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core]  debug: 0
25.02 11:57:57 [Server] INFO [Multiverse-Core] [Multiverse-Core] Special Code: FRN002

Where's the latest MV build? I'm not sure how to replicate it.

**Comment by TWSSYesterday** [comment]
https://ci.onarandombox.com/job/Multiverse-Core/ Build 688 is quite old :P
