### ISSUE TITLE
Reconfig my settings

### ISSUE THREAD

**Issue by TLiG98** [Multiverse/Multiverse-Core#1802]
Every time i restart my server or reload it. All of settings for Multiverse Core, that I've changed, resets. This issue really annoys me. If you think of something that might  be the problem, maybe settings or something else, please contact me as soon as possible! Thank you

**Comment by sgdc3** [comment]
Multiverse shouldn't save the config on disable

**Comment by TLiG98** [comment]
That's most of the problem. When the file is saved, and I start the server all the configs at reset almost. Such as allow animals to spawn are set back to true when I restart my server

**Comment by sgdc3** [comment]
I know, the only workaround atm is to stop the server, edit the file and then start the server....

**Comment by dumptruckman** [comment]
Ideally you edit the settings via commands. If you want to edit them by hand, the safest way is to do it while your server is not running.
