### ISSUE TITLE
Your not in a plot area

### ISSUE THREAD

**Issue by CosmicPyrex** [Multiverse/Multiverse-Core#1804]
So when users on my server try to do /plot auto in spawn it says '[P2] Your not in a plot area' it sounds like this is from the user not being in the specific world the plots are in, but I have seen MANY servers that obviously have bypassed that. Help!

**Comment by Tzzzt123** [comment]
CosmicPyrex they need to be in the corresponding PlotWorld to be able do /plot auto
So set a warp named "plots" in your plot world, then they do /warp plots and then /plot auto
