### ISSUE TITLE
Worlds Not Deleting

### ISSUE THREAD

**Issue by CosmicPyrex** [Multiverse/Multiverse-Core#1806]
So I am having an issue with worlds not deleteing they are PlotSquared worlds I delete them out of the worlds.yml, and then save that and go back and delete them from the FTP directory (Whole world file) then restart my server. They keep regenerating back, not sure what to dod as this has been an issue for awhile

Thanks,
CosmicPyrex,
PrisonBreach CEO

**Comment by Greenfoot5** [comment]
Have you tried doing /mv delete [world]

**Comment by CosmicPyrex** [comment]
Yes

**Comment by CosmicPyrex** [comment]
Yes

**Comment by CosmicPyrex** [comment]
Oops I didn't mean to close this

**Comment by TWSSYesterday** [comment]
You need to use /mv remove <name> to remove it from the worlds.yml file.

**Comment by CosmicPyrex** [comment]
Says 'error trying to remove world from config!'

**Comment by TWSSYesterday** [comment]
What's the error in console when you do that?

**Comment by CosmicPyrex** [comment]
02.04 14:58:51 [Server] WARN Hmm Multiverse does not know about this world but it's loaded in memory.
02.04 14:58:51 [Server] WARN To let Multiverse know about it, use:
02.04 14:58:51 [Server] WARN /mv import prison_spawn NORMAL

**Comment by Greenfoot5** [comment]
The /mv import prison_spawn NORMAL and then do /mv delete prison_spawn.

**Comment by CosmicPyrex** [comment]
http://imgur.com/a/ezbhX

Nope.

**Comment by CosmicPyrex** [comment]
Anyone? Still a huge problem for me..

**Comment by TWSSYesterday** [comment]
If you back up your worlds.yml file and start again; trying to do this again what happens? What version of Multiverse-Core are you using?

**Comment by dumptruckman** [comment]
The general strategy is this:

`mv delete <worldname>`

If that doesn't work, shut down the server and remove the world directory manually.

The reason why the command fails to work is because some other plugin is causing the server to keep an open file handle on the world. The only real solution is to stop the server and manually delete.
