### ISSUE TITLE
Feature request: Teleport with delay

### ISSUE THREAD

**Issue by SlimeDog** [Multiverse/Multiverse-Core#1807]
Please add variable delay to **/mvtp**. Something like:
> **/mvtp *[player]* *target* *[delayInSeconds]***

And a permission node to bypass the delay, for OPs.

EDITED Use case: Players use **/mvtp** to move between Multiverse worlds. Unfortunately, they can use **/mvtp** to avoid certain death. With a delay, they would be unable to do so.

**Comment by Tzzzt123** [comment]
SlimeDog simply don't give em permision

**Comment by Tzzzt123** [comment]
*permission to /mvtp

**Comment by SlimeDog** [comment]
Obviously, but not helpful if I want them to have permission to execute /mvtp. I just want a delay, and I want a permission mode to bypass the delay that I have proposed.

**Comment by SlimeDog** [comment]
So, I commissioned and use [CommandDelay](https://www.spigotmc.org/resources/commanddelay.40014/) for this purpose (and more).
