### ISSUE TITLE
Displays map files from one world on second world

### ISSUE THREAD

**Issue by hyperfirecat** [Multiverse/Multiverse-Core#1810]
Sorry if there's a proper formatting for this, not posted an issue before. 
Bukkit server with two worlds on it. Both worlds seem to work fine, warps and all. However, the map item files for the second world don't appear. Where a map (say number 85) for world 2 should appear on a frame, it displays the map (number 85) from world 1 instead.
Anyone have any ideas on what causes this? An issue with this plugin, an interaction with other plugins? 

Help appreciated! Let me know if this problem is unusual and I should post some other info about my setup. I'm not the one who set up this server, considering resetting everything from scratch to try to fix it...

**Comment by Phoenix616** [comment]
Minecraft stores all the maps of the server in a single location (in the data folter of the main world set with the level-name option in the server.properties)

Allowing maps to display different content on different worlds is not something that Multiverse can or (imo.) should do as you can transfer items between worlds. Changing the display of the map depending on the world would then make it impossible to see maps from world A in world B.

If you really want/need that you are better of using separate servers and connecting them with something like BungeeCord.
