### ISSUE TITLE
confusion over import and bungeecord

### ISSUE THREAD

**Issue by smmmadden** [Multiverse/Multiverse-Core#1811]
Hi - I looked for a page on Spigot for Multiverse for discussions but couldn't locate one, so coming here to ask the questions.  I've recently switched to using Bungeecord Network and have my worlds setup under the same folder structure as documented.  I can connect to bungee, login to the default world and switch to any of the worlds in bungee.   

I setup one world that is stripped down of most plugins and using it as my hub (central point everyone spawns in).  What I had hoped to do is to use CreativeGates to allow a portal from "TheHub" to any of the other worlds.  Unfortunately, it only works for the same world for "named portals" to connect to.

Then someone said to me to use Multiverse, Multiverse-Portal, Multiverse-NetherPortal and Multiverse-SignPortal as it will allow mutli-world connections.  Unfortunately, the directions are missing the detail on how to do this for a bungee network.  There is an option for mvp import, but all my worlds are already in their respective folder locations which I can't change or then that breaks.  Is there a way to setup each world with MV iin the configuration to explicitly tell the server where the worlds are and on what port via 127.0.0.1 IP (which they reside on)?

Scenario:
The Hub - users spawn here the first time. Envision the players picking one of many portals to walk through and when they do, they appear at "spawn" for that world.  If they've been there at least once, they go to their last known location.  Similar worlds for *_nether and *_the_end for each using the NetherPortal plugin for the same.
-----MyCreativeWorld:port
-----MySurvivalWorld:port
-----MyFutureWorld:port
-----etc

Can this be done?  -Thanks for any help! :-)  Steve
EDIT 5/9/17:  I've installed a couple other plugins to help with cross-world support with Bungeecord.  CommandSyncServer & CommandsDispatcher (BungeeCord Plugin) and CommandSyncClient (Minecraft plugins).  Are there API's to BungeeCord to create portals or signs for TP to other worlds?

**Comment by smmmadden** [comment]
Is anyone even reading these issues?  I've posted in multiple places and it gives the impression the plugin is abandoned when no one replies to them.

**Comment by Phoenix616** [comment]
BungeeCord connects multiple Minecraft server together, Multiverse only allows your to create multiple worlds on a single server, not teleport between different servers in your BungeeCord network.

**Comment by smmmadden** [comment]
Thanks Phoenix616 for the reply, I truly appreciate it.  That answers a lot of questions I had about its usefulness in the infrastructure I'm using.  Good to know I don't have to wait for any changes to support 1.12 since it doesn't appear to help my use case.  Closing the request as answered. :-)
