### ISSUE TITLE
Debug.log locked open in portals

### ISSUE THREAD

**Issue by enginekid92** [Multiverse/Multiverse-Core#1812]
I'm thinking this is isolated to portals, but whenever I have portals installed the debug.log file is locked open.  This would be fine and dandy, except my CP can't make a backup due to it :/

**Comment by dumptruckman** [comment]
Please do `mvv -g` from console and give me the link it gives you after a few moments.

**Comment by enginekid92** [comment]
Waiting on the command to return.  Sorry for the delay, was not expecting such a quick reply.  Thanks!

**Comment by enginekid92** [comment]
Checked using the latest snapshot version of MV core, same issue.

**Comment by dumptruckman** [comment]
Alright, just wanted to be sure you're using the newer style logging so I know where to look. I'm not sure when I can look into this. I haven't heard of anyone having issues with backups because of this though. Can you delete the lock file when the server is shut down?

**Comment by Jadiction** [comment]
I've encountered some backup plugins abruptly stropping the backup process because they were unable to back up the locked "debug.log.lck" file. I had to add Multiverse-Portals to the excluded list to fix it. I can confirm this, but I don't think it's exactly an issue of Multiverse unless the locked file isn't necessary.

**Comment by benwoo1110** [comment]
I think mv its just writing to the file while your backup plugin is trying to read from it. Generally you shouldn't be backing up your server with its running. You can just set to ignore that file anyways, since I don't think debug log is needed for backup.
