### ISSUE TITLE
Multiverse Format Overriding PEX

### ISSUE THREAD

**Issue by CosmicPyrex** [Multiverse/Multiverse-Core#1815]
So I recently uploaded Multiverse-Core to my 3rd server in my Network. I changed the world prefix option in the config to false, but my chat is still in the formatting of Multiverse rather PEX;

 [![https://gyazo.com/9be78ae7d94fb32ef9fd052cc63839d8](https://gyazo.com/9be78ae7d94fb32ef9fd052cc63839d8/raw)](https://gyazo.com/9be78ae7d94fb32ef9fd052cc63839d8) 

I have been searching for an option to change this or have PEX override, and I did it somehow years ago for my other servers I have to be missing something. Please help!

**Comment by CosmicPyrex** [comment]
@dumptruckman18

**Comment by TWSSYesterday** [comment]
Please don't tag members of the team, we will get to the issue when possible. What plugins are you using? Multiverse wouldn't do this unless you've purposefully set it up to do this. Please pastebin a list of plugins.

**Comment by Jadiction** [comment]
Closing ticket due to lack of information (and no response in a reasonable time). Please open a new ticket with more valid information if this issue is still occurring in the latest versions.
