### ISSUE TITLE
Please Update Multiverse-Core to 1.11.2 & 1.12

### ISSUE THREAD

**Issue by pinkpig3777** [Multiverse/Multiverse-Core#1816]
Just like the title says, please update the plugin to support 1.11.2 and 1.12. Mainly 1.11.2 because that's what my server currently is. I tried to use it to create a new world and it spammed my console with errors then the server crashed.

**Comment by dumptruckman** [comment]
The beta build on dbo has been working on 1.11.2 for a long time now. The dev builds on http://ci.onarandombox.com work on 1.12

**Comment by dumptruckman** [comment]
Sorry, mispoke. The latest *download* on DBO works on 1.11.2.
