### ISSUE TITLE
Multiverse-Core problem with custom advancments

### ISSUE THREAD

**Issue by Ste3et** [Multiverse/Multiverse-Core#1817]
the actually snapshot Multiverse-Core (v2.5.0-SNAPSHOT-b725) deos not load custom advancments: https://hub.spigotmc.org/jira/browse/SPIGOT-3275

**Comment by Jadiction** [comment]
Closing ticket due to lack of information. Please open a new ticket with more valid information if this issue is still occurring in the latest versions.
