### ISSUE TITLE
Can't set arbitrary gamerules like with the stock /gamerule command

### ISSUE THREAD

**Issue by dcoshea** [Multiverse/Multiverse-Core#1818]
https://www.reddit.com/r/Minecraft/comments/5dhfq4/trouble_changing_max_entity_cramming/da4ndxq/ suggests that the `/gamerule maxEntityCramming 0` command could be used *prior* to upgrading to Minecraft 1.11 to avoid any mob deaths due to the `maxEntityCramming` rule.  This seems to work because `/gamerule` lets you supply it with an arbitrary rule name which will then be set to the given value.

A new, arbitrary game rule set in this way will appear in the output of `/mv gamerules`.

However, `/mv gamerule` does not itself allow arbitrary rules to be set - it seems to require that the rule already exist, returning e.g. `Failure! Gamerule myrule cannot be set to 1` if it doesn't. It is helpful that the command performs this check to avoid frustration due to typos, but it would be nice if there was also a way to allow new rules to be set.

This was seen with the build https://ci.onarandombox.com/job/Multiverse-Core/722/, but I don't see any commits in the meantime that would have changed this.

**Comment by benwoo1110** [comment]
![image](https://user-images.githubusercontent.com/30431861/95230449-7f2e6280-0834-11eb-8c04-961ee0cc45e1.png)
Recent commits have tweaked the message.
But if you want to just set an arbitrary game rule, it's not possible bcu as the gamerules available is defined by your Server and Bukkit's API
