### ISSUE TITLE
Substantial pause on bootup may be MV core or MV N portals intialising Log4j 2 handler

### ISSUE THREAD

**Issue by frizzbee30** [Multiverse/Multiverse-Core#1819]
Hi, trying the latest dev builds of MV core   and MV Nether portals, we have noticed a considerable delay in boot of around 40 seconds at this load point, which has forced us to roll back the version.

MV build 727

MV NP 717

06.06 16:24:23 [Server] INFO [TouchscreenHolograms] Enabling TouchscreenHolograms v1.3.2
06.06 16:23:37 [Server] INFO Log4j 2 handler detected: com.enjin.common.compatibility.LegacyLog4j2Handler
06.06 16:23:37 [Server] INFO Initializing for the first time

Thanks

**Comment by dumptruckman** [comment]
The log you pasted has no useful information. Please provide a full startup log.

**Comment by frizzbee30** [comment]
I'll pull through the full log when I have a chance, I figured there had been a change with an addition, hence the log handler pause.  Thanks

**Comment by dumptruckman** [comment]
Well, to be honest, I'd attribute the 14 second delay to TouchscreenHolograms.

**Comment by frizzbee30** [comment]
Thanks I'll do some testing and try removing TouchScreenHolograms to see if still occurs

**Comment by frizzbee30** [comment]
closing as likely not related
