### ISSUE TITLE
Error when loading world

### ISSUE THREAD

**Issue by Flandyn** [Multiverse/Multiverse-Core#1821]
Multiverse fails to load world, if a player is in the world already then they can use the world, however if you try to enter the world with /warp or /mvtp then you cannot access it.
The world uses a custom generator, this has never happened before.

Server log: https://pastebin.com/A44EyzH2

**Comment by dumptruckman** [comment]
You should probably update to the latest release.

**Comment by Jadiction** [comment]
Closing ticket due to lack of information (and no response in a reasonable time). Please open a new ticket with more valid information if this issue is still occurring in the latest versions.
