### ISSUE TITLE
Adding more than 6 worlds breaks Multiverse-Core

### ISSUE THREAD

**Issue by Nekrose483** [Multiverse/Multiverse-Core#1822]
Hi, my issue is that i have my world with multiverse which is the standard "world", "world_nether", and "world_the_end" and then i created two creative superflat worlds for youtuber tutorial friends and then another random normal world for another friend who just wants their own "realm" works really nice and its perfect.. up to 6 worlds. when i add the 7th... via generation or import or anything, it just breaks. every teleport leads me to random places in "world", the default map. and the other maps are completely unreachable. the only way i've found to solve this issue is to delete one, making 6 worlds again. doesn't matter which world i delete... and it doesn't matter how the new world was made, just more than 6 worlds breaks Multiverse-Core completely.

installed is multiverse-core, world teleporters, perworldchat, perworldinventory

and to note, i have tested this issue while using multiverse as the only plugin in bukkit. the issue still persists. is there any way to solve this issue or raise the number of "max worlds" i can have?

**Comment by Nekrose483** [comment]
i should note that i'm on 1.11.2 version of minecraft, using the lastest multiverse-core

**Comment by dumptruckman** [comment]
I've never heard of a world limit before and I've seen people with 20+ worlds. Not quite sure why it's different for you.

**Comment by Nekrose483** [comment]
do you have any suggestions at all that would help me to resolve this issue?

**Comment by dumptruckman** [comment]
Are you running out of memory or hard drive space possibly? Seems pretty unlikely but a lack of storage space causes some pretty strange bugs. If not either of those, try making a fresh server, with literally only MV-Core. Then just start making worlds like crazy with the command `/mvc TestX normal` where X is an increasing number. Let me know if that exact process still causes issue with the vanilla teleport command and `/mvtp` command.

**Comment by Nekrose483** [comment]
seems to work for a while. no issue really until i tried teleporting to a world i had already been to. then i just teleported to somewhere random in the default world. i tried this again.. i'm not sure there is a specific number of worlds that causes this.. there is a memory leak, a bad bad memory leak with running bukkit or spigot or anything on centos so i have to run it on my mac server.it does have all the ram it needs. and i've certainly not run out of disk space.. on my main server, (i have not changed anything since reporting this issue on my main server) once the server starts ,it seems like you can teleport to the world. so can anyone else.. until you teleport back to the new world, then it stops working for everyone.

i'm running Multiverse-Core-2.4 just to be clear.

**Comment by Nekrose483** [comment]
ok so..after saying this i found out all the sites advertising for multiverse-core are all outdated. even this github says 2.3 is the latest i found a 2.5 build on jenkins and so far no issues though, i'll see if it still works fine after leaving the server on all night

**Comment by Nekrose483** [comment]
tried it again, no reboots or anyhting, just leaving it on for 15 minutes, multiverse just "doesn't know how to make me to" the world i've created. though, it did weirdly rearrange all the worlds in the config file. maybe it needed to be refreshed with a reboot. will update tomorrow morning

**Comment by dumptruckman** [comment]
Actually, https://dev.bukkit.org/projects/multiverse-core shows 2.5.0 as the latest release.

**Comment by Nekrose483** [comment]
after leaving it on, with 2.5 it just says "i dont know how to take you to [world]"

**Comment by Nekrose483** [comment]
on github, it says it here: https://github.com/Multiverse/Multiverse-Core/releases

and i didn't find it on bukkit.org. i found it on curse's website.

**Comment by Nekrose483** [comment]
didn't work at all. but at least its not teleporting me to random places making me have to find my way back or test which world i'm in. so that's nice.

**Comment by TheIntelloBox** [comment]
I have more than 6 worlds on Spigot 1.12 and no problem.

**Comment by Nekrose483** [comment]
sadly this isn't about 1.12 but 1.11.2 and now while i have 4, having removed 2, it will no longer teleport me to any of them... and as i said i updated. which is when it just all together stoped working. i am also running the server from a mac computer.

**Comment by TheIntelloBox** [comment]
When I was in 1.11.2 I hadn't his bug.

**Comment by Nekrose483** [comment]
well i do, are there any helpful suggestions you can make?
java 8...1.11.2 minecraft/spigot version. multiverse core 2.5.0

**Comment by iso2013** [comment]
@Nekrose483 Try zipping your server directory and uploading it somewhere (without the server jars, those are illegal to redistribute), so we can take a look. I've never heard of this bug, ever. And I've been using Multiverse since 1.7, with far more than 6 worlds.

Maybe it's an incompatibility with "world teleporters"? Can you link the download/resource page for that, please?

6 seems like a very arbitrary number...

**Comment by Nekrose483** [comment]
having updated to 1.12 i've found multicore is too laggy to use. even giving it alone 6gb+ of RAM on the server, it is still completely unplayable. might be an issue with spigot itself, as i've had other memory leak issues before.

either way, i'm giving up on it. sorry for being a waste of your time, but this mod is completely unusable for me.

the original issue might very well have been the same memory leak issues with other worlds not being able to load and what not.. the lag not noticable because the mod itself crashes and unloads every time someone visits a world.

anway, sorry.

**Comment by dumptruckman** [comment]
So.. something that just came to mind. Are you loading the same worlds each time? Have you actually tried it with completely fresh worlds? It's possible that a particular world file is what is causing all of your issues.

**Comment by Nekrose483** [comment]
after trying it with no worlds, fresh install of spigo 1.12, no other mods. running on MacOS lastest version 26GBs of RAM. giving it 6gbs itself to run. its still completely too laggy to be remotely useable. the world wont load and logging in takes like half an hour before i stop rubber banding. commands are too slow to work, so it just ignores them. 

so its not the worlds i'm using. and/or if it was, there's some other issue as well.

**Comment by ryantheleach** [comment]
That's a performance issue in either minecraft itself, or has to do with the contents at spawn in each of those worlds.

I'd recommend profiling to find out potentially what is causing your server to lag, because all multiverse does is make some nice wrapping commands around bukkit, and handle teleportation / loading / creation + inventories (if you have the plugin installed)
