### ISSUE TITLE
Automatically Unloading Worlds

### ISSUE THREAD

**Issue by SpyroTheDragon** [Multiverse/Multiverse-Core#1826]
Hi, Multiverse has been unloading my plotworld and spawn area everytime theres no players in them, ill restart, and the worlds load in fine, but 5 minutes later.. poof unloaded.

and I get this from the console.
[17:29:29 INFO]: [Multiverse-Core] World 'PlotWorld' was unloaded from memory.

**Comment by HePezi** [comment]
I have this same issue. 
Imported my old minigame world, working fine but when there is no players there the world unloads. and need to be unloaded with /mv load.

**Comment by BarbaqSmash** [comment]
Oh thanks. I already fixed it though by just doing some console stuff...
Don't really remember. Thanks

http://bit.ly/BarbaqSmash
