### ISSUE TITLE
Multiverse Deleting A World 

### ISSUE THREAD

**Issue by Sethinitely** [Multiverse/Multiverse-Core#1827]
Okay, so multiverse deleted a world of mine. I can't remove it from list or anything. I want to recover it. It got deleted because it crashed so many times. Is there any possible way of getting it back? Or is it lost for good?

**Comment by Jadiction** [comment]
When a world is deleted, the world folder is deleted as well; meaning no, there is no way to recover it. 
I'd suggest a backup system to avoid this from happening in the future.  
Closing ticket.
