### ISSUE TITLE
No method for world importation in MV API

### ISSUE THREAD

**Issue by HipFok** [Multiverse/Multiverse-Core#1829]
Hello to everyone and thank you to every Mutiverse developer for carrying this vital plugin.

I am a beginner in plugin development with spigot/bukkit, and have started quite a big project in which I have to use the Multiverse API. However, for various reasons, I need to be able to import a world from a folder which would NOT be present during server startup.
I believe MV can achieve this using the `/mv import` command, but when trying to achieve the same task from plugin code, I remark that the WorldManager does not provide a method for world importation.

Is this purposely missing for any reason? If not, I think this would wake a useful addition which would make life easier for some developers (including me), and suggest its implementation in the API.

Thank you.

**Comment by dumptruckman** [comment]
It does. They're just called addWorld. [here](https://ci.onarandombox.com/job/Multiverse-Core/javadoc/com/onarandombox/MultiverseCore/api/MVWorldManager.html#addWorld-java.lang.String-org.bukkit.World.Environment-java.lang.String-org.bukkit.WorldType-java.lang.Boolean-java.lang.String-) and [here](https://ci.onarandombox.com/job/Multiverse-Core/javadoc/com/onarandombox/MultiverseCore/api/MVWorldManager.html#addWorld-java.lang.String-org.bukkit.World.Environment-java.lang.String-org.bukkit.WorldType-java.lang.Boolean-java.lang.String-boolean-).
