### ISSUE TITLE
Update Circle CI and Travis CI so they build with Java 8

### ISSUE THREAD

**Issue by dumptruckman** [Multiverse/Multiverse-Core#1834]
I'm not sure who has set this up (I'm guessing @FernFerret) but apparently we have to build with Java 8 since MC 1.12. Can you fix this up and perhaps email me the details so I can log in should this need to be fixed in the future?

**Comment by sgdc3** [comment]
Just change it in the .travis.yml file, for circle you have to create a circle.yml file, it will override the settings

**Comment by dumptruckman** [comment]
Ah, okay, thanks.
