### ISSUE TITLE
Multiverse createing a world fail

### ISSUE THREAD

**Issue by Zarpez** [Multiverse/Multiverse-Core#1835]
Please help me i dont know what to do :( 
my multiverse wont create a world its just says fail

08.07 18:21:31 [Server] INFO Zarpez issued server command: /mv create plotverden normal -t flat
08.07 18:21:31 [Server] ERROR null
08.07 18:21:31 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mv' in plugin Multiverse-Core v2.5.0-b727
08.07 18:21:31 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.07 18:21:31 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.07 18:21:31 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.07 18:21:31 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.07 18:21:31 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.07 18:21:31 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.07 18:21:31 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.07 18:21:31 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.07 18:21:31 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
08.07 18:21:31 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
08.07 18:21:31 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.07 18:21:31 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.07 18:21:31 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.07 18:21:31 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.07 18:21:31 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.07 18:21:31 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
08.07 18:21:31 [Server] INFO Caused by: java.lang.IllegalAccessError: tried to access field ch.njol.skript.command.Commands.suppressUnknownCommandMessage from class ch.njol.skript.mirre.FilterPrintStream
08.07 18:21:31 [Server] INFO at ch.njol.skript.mirre.FilterPrintStream.println(FilterPrintStream.java:27) ~[?:?]
08.07 18:21:31 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.command.CraftConsoleCommandSender.sendRawMessage(CraftConsoleCommandSender.java:26) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.07 18:21:31 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.command.CraftConsoleCommandSender.sendMessage(CraftConsoleCommandSender.java:22) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.07 18:21:31 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.command.ColouredConsoleSender.sendMessage(ColouredConsoleSender.java:63) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.07 18:21:31 [Server] INFO at org.bukkit.command.Command.broadcastCommandMessage(Command.java:414) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.07 18:21:31 [Server] INFO at org.bukkit.command.Command.broadcastCommandMessage(Command.java:380) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
08.07 18:21:31 [Server] INFO at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:112) ~[?:?]
08.07 18:21:31 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) ~[?:?]
08.07 18:21:31 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
08.07 18:21:31 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]

**Comment by dumptruckman** [comment]
This is not related to Multiverse. They key information is here:
```
08.07 18:21:31 [Server] INFO Caused by: java.lang.IllegalAccessError: tried to access field ch.njol.skript.command.Commands.suppressUnknownCommandMessage from class ch.njol.skript.mirre.FilterPrintStream
08.07 18:21:31 [Server] INFO at ch.njol.skript.mirre.FilterPrintStream.println(FilterPrintStream.java:27) ~[?:?]
```
You can see the name of another plugin... Which perhaps appears to be Skript?
