### ISSUE TITLE
Config Resetting

### ISSUE THREAD

**Issue by SatproMC** [Multiverse/Multiverse-Core#1839]
I dont want the world prefix, and if I change it in config it resets to do it!
Spigot 1.12 and 2.5 version MV Core

**Comment by sgdc3** [comment]
you need to do it while the server is stopped

**Comment by Jadiction** [comment]
As suggested by sgdc3, you must modify the configuration file while the server is offline. This is because when you shut the server off (or restart), the config is overwritten.
