### ISSUE TITLE
Per world players counter

### ISSUE THREAD

**Issue by Someone-NEW** [Multiverse/Multiverse-Core#1840]
Hello guys 

 Can you add support some more variables/placeholders with using PlaceholderAPI for Per world players count? like this examples here fore me this one not work %server_online_<world name>%

 

%world_online_<world name>%

Im not using bunke and this is realy needed tnx

**Comment by TWSSYesterday** [comment]
Maxim can get this without Multiverse needing to be used. Best bet is to contact him as he can make it happen.

**Comment by Someone-NEW** [comment]
maxim??? wtf who is this? hmm i say i need to know how using this with Multiverse or not with PlaceholedrAPI this api is best out there. i realy dont know everything about that and maxim and i thing one smal placeholder can be used in MV too i see multiverse placeholders for MV in API page but no one for per world player counter this will be look like a more servers but will be just a worlds when you look into gui menu thank you

**Comment by TWSSYesterday** [comment]
Maxim is the guy who made featherboard, he helps run PlaceholderAPI and Clip runs it
