### ISSUE TITLE
Multiverse Per-World Teleport Permissions Not Getting Set Correctly.

### ISSUE THREAD

**Issue by crashtheparty** [Multiverse/Multiverse-Core#1841]
So I have tried to get enforce-access:true to work with Multiverse for a while now and can't seem to get it to work properly. I have a world named spawn and I am trying to get players to be able to teleport to it. I gave all users (default users) the permission node multiverse.teleport.self.spawn, but they still do not have access to '/mvtp spawn'. Using /mv check, I can see that the player 'does not have the required teleport permission (multiverse.teleport.self.w) to use /mvtp spawn', which is not correct as the player does have it.

Permissions plugin is PEX. Using the latest versions of both plugins.

**Comment by Jadiction** [comment]
Duplicate issue of https://github.com/Multiverse/Multiverse-Core/issues/1786
