### ISSUE TITLE
Items with Data Values for Currency

### ISSUE THREAD

**Issue by SilentMrDave** [Multiverse/Multiverse-Core#1843]
I apologize in advance if this is the incorrect place to ask but is it possible to set the price for entry into a world to be an item with a data value (such as Polished Granite "1:2"). I haven't found anything that says if you can or can't.

**Comment by dumptruckman** [comment]
There's not a way to do this in MV-Core. You can do it with MV-Portals but it would involve writing some JavaScript and also being familiar with the Bukkit API.
