### ISSUE TITLE
mv.bypass.gamemode.* doesn't work

### ISSUE THREAD

**Issue by Shiikii** [Multiverse/Multiverse-Core#1844]
Well, like in title. Bypass doesn't work, all stuff members have their gamemode switched when moving between worlds through portals(Ancient Gates).
I tried with .* and with worlds name, none work.

Plugin list:
`TopLite, WorldEdit, LoginSecurity, PermissionsEx, WorldBorder, EasyCarts, Vault, SaneEconomy, ZHorse, Multiverse-Core, ProtocolLib, WorldGuard, SkinsRestorer, Companies, DiscordSRV, Essentials, EssentialsProtect, BKCommonLib, EssentialsChat, CommandCost, AncientGates, HolographicDisplays, QuickShop`

**Comment by Jadiction** [comment]
Unable to replicate. Duplicate issue of https://github.com/Multiverse/Multiverse-Core/issues/1844 Try updating the plugin.
