### ISSUE TITLE
feauter plugins per world it will be awesome

### ISSUE THREAD

**Issue by edwardtakev** [Multiverse/Multiverse-Core#1847]
feauter plugins per world it will be awesome ... and many more people will love this plugin like i do without it !! no bug nothing the best plugin !!

**Comment by Jadiction** [comment]
Hello, a plugin that could accomplish this is linked on the Multiverse resource page (https://dev.bukkit.org/projects/perworldplugins). I have not used it myself or tested it, but you may try it out yourself.
