### ISSUE TITLE
Multivere-core spamming info 5/6 time per second

### ISSUE THREAD

**Issue by godartm** [Multiverse/Multiverse-Core#1849]
It will stop when i remove multiverse-core , you i can fix this ?

`[Server thread/INFO]: [@: Entity data updated to: {HurtByTimestamp:0,Attributes:[0:{Base:20.0d,Name:"generic.maxHealth"},1:{Base:0.0d,Name:"generic.knockbackResistance"},2:{Base:0.699999988079071d,Name:"generic.movementSpeed"},3:{Base:0.0d,Name:"generic.armor"},4:{Base:0.0d,Name:"generic.armorToughness"}],Invulnerable:0b,FallFlying:0b,ShowArms:0b,PortalCooldown:0,AbsorptionAmount:0.0f,FallDistance:0.0f,DisabledSlots:0,DeathTime:0s,WorldUUIDMost:2100544977920541447L,Pose:{Head:[0:1.1940894f,1:4.5982914f,2:0.0f],Body:[0:0.0f,1:1.6190758f,2:0.0f]},Spigot.ticksLived:104155821,Invisible:0b,Motion:[0:0.0d,1:-0.0784000015258789d,2:0.0d],Small:0b,UUIDLeast:-8520248147641858587L,Health:20.0f,Bukkit.updateLevel:2,Air:300s,OnGround:1b,Dimension:0,Rotation:[0:225.0f,1:0.0f],HandItems:[0:{},1:{}],UUIDMost:-8221242426014611804L,Pos:[0:-42.5d,1:4.0d,2:11.5d],Fire:-1s,ArmorItems:[0:{},1:{},2:{},3:{id:"minecraft:skull",Count:1b,Damage:5s}],NoBasePlate:0b,HurtTime:0s,WorldUUIDLeast:-5135522037315708219L}]`

**Comment by q220** [comment]
Looks like debug output, is globaldebug enabled in your config file?
