### ISSUE TITLE
Multiverse and Worldguard problem

### ISSUE THREAD

**Issue by LinearBotSystems** [Multiverse/Multiverse-Core#1851]
I have a bug I can setup regions in my original world and everything is fine but I can't allow anything in a new region I setup in a new world like:  use allow or interact allow. I mean I can set it to allow but it won't work it will be simply ignored 

I can only guess there a certain setting which aren't copied to the new world which blocks this.

My setting is Spigot 1.12 , mv-core 2.6, mv-portal 2.5.2 and Worldguard 6.2.2

**Comment by FlyingPikachu** [comment]
@LinearBotSystems Happened to browsing your profile atm ;)

Are you thinking MV is the cause? This would happen to myself sometimes, but it'd always turn out to be a WG parent or priority issue, often conflicting with the __global__ region. Have you checked those flags?

**Comment by LinearBotSystems** [comment]
Yeah I have checked __global__ and priority nothing wrong there.

**Comment by LinearBotSystems** [comment]
The problem I see it when I created the new world all permissions were basically zero only the most basic . I had to download PermissionEx to give me rights over mv in the new world , there is also a bug with the new advancements that you can't disable them in the chat in a new world without an extra plugin because server setting won't be copied into the new world with spigot. 

I highly suspect something similar is going on.

**Comment by Relaking** [comment]
>  there is also a bug with the new advancements that you can't disable them in the chat in a new world without an extra plugin because server setting won't be copied into the new world with spigot.
You simply need to set the gamerule announceAdvancements to false in every. single. world.
This is not possible in the console, you have to do that in-game.

**Comment by Richar05** [comment]
No puedo romper bloques en el mundo que creo y no esta en aventura ayuda
