### ISSUE TITLE
why items from first wolrd stay in my inv when i teleport to another world?

### ISSUE THREAD

**Issue by Alzi24** [Multiverse/Multiverse-Core#1853]
why items from first wolrd stay in my inv when i teleport to another world?how to remove that

**Comment by LinearBotSystems** [comment]
This is because multiverse makes it so that you can travel between worlds like it is one world that is the whole purpose of this add-on  but there is one options: https://www.spigotmc.org/resources/per-world-inventory.4482/ this will help you to do so.

**Comment by Jadiction** [comment]
To follow up on this, Multiverse-Inventories should work to separate inventories per-world and also allow linking of worlds you do want the same inventory on.
