### ISSUE TITLE
[H] displayed after world name

### ISSUE THREAD

**Issue by Alfiepops8** [Multiverse/Multiverse-Core#1854]
There is an [H] displayed after one of my world names, and the world name prefix is broken for that world, what does the [H] mean and how can I fix the not displayed prefixes?
![screen shot 2017-08-10 at 10 42 34](https://user-images.githubusercontent.com/30895756/29165110-93a74a00-7db9-11e7-98b2-c81e1ff6ee45.png)

**Comment by Chewsterchew** [comment]
Hidden
