### ISSUE TITLE
Force tp to world when change gamemode

### ISSUE THREAD

**Issue by ahriee** [Multiverse/Multiverse-Core#1855]
Hi!
**My worlds: towny, townyhub, resource, nether, end, test (all survival mode)**
I have this issue wherein whenever i try to changemy gamemode to survival it teleports me to towny and if i change to creative i get teleported to end world which is weird, even if i teleport to other worlds before & after changing my gamemodes it still teleports me to the same exact area. i tried creating a test world to see whats wrong, when i change to creative first it seems okay, but when i change to survival i get tped to test world spawn point.
Any ideas how to fix this? Please help me. Thank you in advance

**Here's my config.yml from multiverse core**
> multiverse-configuration:
  ==: com.onarandombox.MultiverseCore.MultiverseCoreConfiguration
  enforceaccess: 'false'
  prefixchat: 'true'
  prefixchatformat: '[%world%]%chat%'
  useasyncchat: 'true'
  teleportintercept: 'true'
  firstspawnoverride: 'true'
  displaypermerrors: 'true'
  globaldebug: '0'
  silentstart: 'false'
  messagecooldown: '1000'
  version: '2.9'
  firstspawnworld: TownyHub
  teleportcooldown: '1000'
  defaultportalsearch: 'false'
  portalsearchradius: '128'

**multiverse inv config.yml**
>  Multiverse-Inventories Settings
 ===[ Multiverse Inventories Config ]===
settings:
   This is the locale you wish to use.
  locale: en
   If this is true it will generate world groups for you based on MV worlds.
  first_run: false
   If this is set to true, it will enable bypass permissions (Check the wiki for more info.)
  use_bypass: false
   If set to true, any world not listed in a group will automatically use the settings for the default group!
  default_ungrouped_worlds: false
   The default and suggested setting for this is FALSE.
  False means Multiverse-Inventories will not attempt to load or save any player data when they log in and out.
   That means that MINECRAFT will handle that exact thing JUST LIKE IT DOES NORMALLY.
   Changing this to TRUE will have Multiverse-Inventories save player data when they log out and load it when they log in.
   The biggest potential drawback here is that if your server crashes, player stats/inventories may be lost/rolled back!
  save_load_on_log_in_out: false
   If this is set to true, players will have different inventories/stats for each game mode.
   Please note that old data migrated to the version that has this feature will have their data copied for both game modes.
  use_game_mode_profiles: true
shares:
   When set to true, optional shares WILL be utilized in cases where a group does not cover their uses for a world.
   An example of this in action would be an ungrouped world using last_location.  When this is true, players will return to their last location in that world.
   When set to false, optional shares WILL NOt be utilized in these cases, effectively disabling it for ungrouped worlds.
  optionals_for_ungrouped_worlds: true
   You must specify optional shares you wish to use here or they will be ignored.
   The only built in optional share is "economy"
  use_optionals:
   last_location

**Comment by Jadiction** [comment]
Closing ticket, please open a new ticket if this is still occurring in new Multiverse versions.
