### ISSUE TITLE
Cant Import/Load worldss

### ISSUE THREAD

**Issue by MrLeitung** [Multiverse/Multiverse-Core#1857]

**Comment by MrLeitung** [comment]
Hello, sorry for my bad English..
i want to Import a world named : SkyPvPmap but if i type in /mv import SkyPvPmap normal it just says §cFAILED!

if i type in /mv load SkyPvPmap it says: Error trying to load world 'SkyPvPmap'!
pls help 👍 
i use Spigot 1.8.8 on my Server und Multiverse 2.5.0.

**Comment by Jadiction** [comment]
Closing ticket due to lack of information. Please open a new ticket with more valid information if this issue is still occurring in the latest versions.
