### ISSUE TITLE
Respawn world not working suddenly.

### ISSUE THREAD

**Issue by BrettplayMC** [Multiverse/Multiverse-Core#1858]
For some reason, my respawn world option in the multiverse-core config stopped working recently and it no longer tp's player's to the set world.  I have tried /mv debug 3, removing plugins I thought were causing it, and more and nothing.  I am on the latest 2.5.0 release on Bukkit running Spigot 1.8.8.

**Comment by Jadiction** [comment]
Closing ticket due to lack of information (and no response in a reasonable time). Please open a new ticket with more valid information if this issue is still occurring in the latest versions.
