### ISSUE TITLE
Ayuda con este error del mv 

### ISSUE THREAD

**Issue by AlejoGamingYT** [Multiverse/Multiverse-Core#1859]
Ayuda en mi server no sirve ningun comando del mv siempre que pongo algo me sale esto 

![image](https://user-images.githubusercontent.com/31374381/29744264-face1e2a-8a66-11e7-9ba3-ef0f5e28cf98.png)

**Comment by Superdarco** [comment]
Que version usas del MV?

**Comment by TWSSYesterday** [comment]
Please provide the version of Multiverse Core you are using and what Spigot/PaperSpigot/Bukkit you are using as well as a full log via pastebin to let us assist you.
---------------------------------------------------------------------
Proporcione la versión de Multiverse Core que está utilizando y lo que Spigot / PaperSpigot / Bukkit que está utilizando, así como un registro completo a través de pastebin para ayudarnos.

**Comment by Jadiction** [comment]
Closing ticket due to lack of information (and no response in a reasonable time). Please open a new ticket with more valid information if this issue is still occurring in the latest versions.
