### ISSUE TITLE
Can't setspawn Random?

### ISSUE THREAD

**Issue by ericmoros** [Multiverse/Multiverse-Core#1862]
You could add an extra to the mvss command, a value that if It's equal to 'Random' (or something similar) randomizes the spawn in the world

Example:
/mv set spawn random

(And then every time that I die spawns in a different location)

**Comment by sgdc3** [comment]
That should be handled by a specific plugin.

**Comment by benwoo1110** [comment]
Agreed, it should be handled by purpose-built spawning plugin ^^
