### ISSUE TITLE
Issues Teleporting back to a World with a Two Word Name.

### ISSUE THREAD

**Issue by SkullSphinx** [Multiverse/Multiverse-Core#1863]
So my main world is 'Bobbys World' so when I teleported to the 1st MV world I created I now cannot go back. I've put in: '/mvtp' or '/mv tp', my name, and all these combinations:
Bobbys_World
Bobbys World
Bobbys.World
Bobbys-World
Bobbys/World.

I do not know what else to try. Thank you.

**Comment by ryantheleach** [comment]
Have you tried /mvtp 'Bobbys World'
