### ISSUE TITLE
Autoheal, hunger, portal forming do not work in new MV world

### ISSUE THREAD

**Issue by AIphaDragon** [Multiverse/Multiverse-Core#1865]
Hello,
We have a server with MV resource world. The matter is, that in this world does not work autoheal, hunger does not deplete and players cannot build nether and end portals, as they simply do not work.
So, how can we fix it?
Thanks in advance

MV-Core worlds pastebin: https://pastebin.com/Xfy3XQfE
MV-Core config pastebin: https://pastebin.com/5RmH57QH

MV-Inv config pastebin: https://pastebin.com/N2Ygf0Gv
MV-Inv groups pastebin: https://pastebin.com/RKwgfzXf

Multiverse-Inventories Version: 1.4
Multiverse-Core Version: 2.5-b719

**Comment by Jadiction** [comment]
Try updating to the latest Multiverse-Core version. Closing ticket. Please open a new ticket if this issue is still occurring in the latest versions.
