### ISSUE TITLE
Deleted portals still teleport you

### ISSUE THREAD

**Issue by Paperclippy** [Multiverse/Multiverse-Core#1867]
Self explanatory. I created a portal, deleted it, reset the destination, but it still teleported me to the old location, no matter what. I deleted the portal, deleted both portals, even moved it to a different location then tried again with the same old names, and then gave up. Having a different location and different names probably works, but that would be way too weird having 2 empty spaces for portals. Please fix

**Comment by Jadiction** [comment]
Hi, I know this is an old issue, but I am currently looking through all the old (and new) tickets. 
I was unable to replicate this. Tried several times. If this is still happening (while on the latest version), please make a new ticket with more information. Thanks!
