### ISSUE TITLE
Cannot Delete Plugin

### ISSUE THREAD

**Issue by Kekulism** [Multiverse/Multiverse-Core#1872]
I have been trying to delete Multiverse in it's entirety for a while now. It seems like no one has had this problem so i'll put it in myself. I've deleted everything in the Multiverse folder except for one stubborn file that refuses to go away. It's scripts.bin. On my Anvilnode server, every time i try to delete it, it fails. Can anyone help me out?

**Comment by TWSSYesterday** [comment]
You need to delete the .jar file for Multiverse-Core. We're sad to see you go :(
