### ISSUE TITLE
/mvtp permission

### ISSUE THREAD

**Issue by TheCactusMonkey** [Multiverse/Multiverse-Core#1873]
What is the permissions to use /mvtp and tp yourself to a world.
I have this permissions atm:
    - multiverse.access.*
    - multiverse.portal.access.*
    - multiverse.core.spawn.self
    - multiverse.core.tp.self
    - multiverse.teleport.self
    - multiverse.teleport.self.ServerLobby
    - multiverse.teleport.self.ServerSurvival
    - multiverse.teleport.self.GamesLobby

ServerLobby is my HUB ServerSurvival is my SURVIVAL and GamesLobby is my GAMES AND PARKOUR HUB.

I cant get it to work it says that i dont have the permissions and then it shows me like 10 diffrent teleport permission nodes.

Thanks,
TheCactusMonkey

**Comment by TheCactusMonkey** [comment]
Help anyone?!

**Comment by SaitDev** [comment]
I assume ServerLobby, ServerSurvival, GamesLobby are your different server running on a proxy (Bungeecord/Waterfall). If that sace, /mvtp only help tp between worlds in only one server

**Comment by Jadiction** [comment]
Closing ticket due to lack of information (and no response in a reasonable time). Please open a new ticket with more valid information if this issue is still occurring in the latest versions.
