### ISSUE TITLE
Error while trying to import a world

### ISSUE THREAD

**Issue by xenos5077** [Multiverse/Multiverse-Core#1878]
Hi! I've Multiverse on version 1.12.2 and when trying to import a world that was generated in solo, exported to the FTP and in the good version here's what the console gives me out: 

In Game : https://imgur.com/a/gSl8g
On Pastebin : https://pastebin.com/zLL4em0i

19.11 20:22:13 [Server] INFO Xenos5077 issued server command: /mv import Principal normal
19.11 20:22:13 [Server] INFO Xenos5077: Starting import of world 'Principal'...
19.11 20:22:13 [Server] INFO [Multiverse-Core] Loading World & Settings - 'Principal' - Env: NORMAL - Type: null
19.11 20:22:13 [Server] WARN java.io.FileNotFoundException: ./Principal/session.lock (Permission denied)
19.11 20:22:13 [Server] WARN at java.io.FileOutputStream.open0(Native Method)
19.11 20:22:13 [Server] WARN at java.io.FileOutputStream.open(FileOutputStream.java:270)
19.11 20:22:13 [Server] WARN at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
19.11 20:22:13 [Server] WARN at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
19.11 20:22:13 [Server] WARN at net.minecraft.server.v1_12_R1.WorldNBTStorage.i(WorldNBTStorage.java:53)
19.11 20:22:13 [Server] WARN at net.minecraft.server.v1_12_R1.WorldNBTStorage.<init>(WorldNBTStorage.java:47)
19.11 20:22:13 [Server] WARN at net.minecraft.server.v1_12_R1.ServerNBTManager.<init>(SourceFile:21)
19.11 20:22:13 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.createWorld(CraftServer.java:899)
19.11 20:22:13 [Server] WARN at org.bukkit.Bukkit.createWorld(Bukkit.java:454)
19.11 20:22:13 [Server] WARN at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
19.11 20:22:13 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466)
19.11 20:22:13 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:268)
19.11 20:22:13 [Server] WARN at com.onarandombox.MultiverseCore.commands.ImportCommand.runCommand(ImportCommand.java:152)
19.11 20:22:13 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
19.11 20:22:13 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
19.11 20:22:13 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
19.11 20:22:13 [Server] WARN at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:919)
19.11 20:22:13 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
19.11 20:22:13 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
19.11 20:22:13 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651)
19.11 20:22:13 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
19.11 20:22:13 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
19.11 20:22:13 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
19.11 20:22:13 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
19.11 20:22:13 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
19.11 20:22:13 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

**Comment by TWSSYesterday** [comment]
Please ensure the correct permissions are being granted. What's the version of Multiverse-Core you are using?

**Comment by iamdavidfrancis** [comment]
I'm getting the exact same issue. @xenos5077 did you ever solve this problem?

@TWSSYesterday here's the output of /mv version on my server:
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Core] Multiverse-Core Version: 2.5.0-b727
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Core] Bukkit Version: git-Spigot-2086bb0-d0a3620 (MC: 1.12.2)
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Core] Loaded Worlds: [{"MVWorld@1907401591":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"Dcon World"}}, {"MVWorld@1395095980":{"Gen":"null","Type":"NORMAL","Env":"NETHER","Name":"Dcon World_nether"}}, {"MVWorld@745358651":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"survival"}}, {"MVWorld@480875505":{"Gen":"null","Type":"NORMAL","Env":"THE_END","Name":"Dcon World_the_end"}}]
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Core] Multiverse Plugins Loaded: 1
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Core] Economy being used: Essentials Economy
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Core] Permissions Plugin: Bukkit Permissions (SuperPerms)
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Core] Dumping Config Values: (version 2.9)
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Core]  messagecooldown: 5000
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Core]  teleportcooldown: 1000
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Core]  worldnameprefix: true
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Core]  worldnameprefixFormat: [%world%]%chat%
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Core]  enforceaccess: false
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Core]  displaypermerrors: true
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Core]  teleportintercept: true
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Core]  firstspawnoverride: true
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Core]  firstspawnworld: Dcon World
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Core]  debug: 0
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Core] Special Code: FRN002
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Portals] Multiverse-Portals Version: 2.5.0-b751
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Portals] Loaded Portals: 2
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Portals] Dumping Portal Values: (version 2.7)
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Portals]  wand: 271
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Portals]  useonmove: true
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Portals]  enforceportalaccess: true
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Portals]  portalsdefaulttonether: false
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Portals]  portalcooldown: 1000
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Portals]  clearonremove: false
02.06 21:57:35 [Server] INFO [Multiverse-Core] [Multiverse-Portals] Special Code: FRN001

**Comment by xenos5077** [comment]
Sorry for late response time, well yeah, was actually using the last version, and, no i did never resolve this issue, i did not tried to search further as i remove multiverse and get another plug-in. But here's the information i recolted anyway, it's about the world version or something like seed or generation related issue after investigating a littlebit

**Comment by xenos5077** [comment]
I'd like to know if you found something else about this issue if you don't mind, comment it here :D

**Comment by Jadiction** [comment]
Hi is this still happening? If so, can you try to back up the "session.lock" file, remove it and then try the import? (I'm not 100% sure, but I believe the lock file doesn't contain any information necessary for the world)

**Comment by InfRandomness** [comment]
Hi, sorry for not answering, i did not see the response. I did not use Mv world anymore because it was to buggy and I never solved the actual problem, but if you want me to test again to take further resolving to the issue, i can setup a server to reproduce the bug and try to resolve it

**Comment by InfRandomness** [comment]
All the permissions were set as i was oped and had the * wildcard on Pex permission plugin, and had the latest version of MV

**Comment by Jadiction** [comment]
By permissions, I'm pretty sure the error refers to file permissions. As in it doesn't have the rights to remove the file(s) from the directory, but I think it only said that because the file was locked. I suggest removing the locked file and re-attempting to import. I don't believe Multiverse is buggy. There are very little bugs [from what I see](https://github.com/Multiverse/Multiverse-Core/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3ABug+-label%3AUnconfirmed+-label%3A%22Unrelated+to+MV%22).
