### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by AnonymousBluejay** [Multiverse/Multiverse-Core#1879]
My server crashes with this plugin, it used to work fine but one day when I restarted the server, it stopped working and crash my server every time I start it up. I removed all the plugins and put them back in one by one and found out Multiverse is causing it. I did not change the version of either the server or the plugin, Multiverse 2.5, Multiverse portals 2.5 Multiverse sign portals 2.4. Server version Spigot 1.12.2. Server appears fine on the server list, but disconnect player and give error message:

io.netty.channel.AbstractChannel$AnnotatedConnectionException: Connection refused: no further information:

Console display error message after crashing

19.12 20:11:10 [Server] ERROR The server has stopped responding!
19.12 20:11:10 [Server] ERROR Please report this to http://www.spigotmc.org/
19.12 20:11:10 [Server] ERROR Be sure to include ALL relevant console errors and Minecraft crash reports
19.12 20:11:10 [Server] ERROR Spigot version: git-Spigot-3d850ec-809c399 (MC: 1.12.2)
19.12 20:11:10 [Server] ERROR ------------------------------
19.12 20:11:10 [Server] ERROR Server thread dump (Look for plugins here before reporting to Spigot!):
19.12 20:11:10 [Server] ERROR ------------------------------
19.12 20:11:10 [Server] ERROR Current Thread: Server thread
19.12 20:11:10 [Server] ERROR PID: 29 | Suspended: false | Native: false | State: RUNNABLE
19.12 20:11:10 [Server] ERROR Stack:
19.12 20:11:10 [Server] ERROR java.util.ArrayList.indexOf(ArrayList.java:317)
19.12 20:11:10 [Server] ERROR java.util.ArrayList.contains(ArrayList.java:300)
19.12 20:11:10 [Server] ERROR java.util.ArrayList.batchRemove(ArrayList.java:720)
19.12 20:11:10 [Server] ERROR java.util.ArrayList.removeAll(ArrayList.java:690)
19.12 20:11:10 [Server] ERROR net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1386)
19.12 20:11:10 [Server] ERROR net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665)
19.12 20:11:10 [Server] ERROR net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817)
19.12 20:11:10 [Server] ERROR net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
19.12 20:11:10 [Server] ERROR net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
19.12 20:11:10 [Server] ERROR net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
19.12 20:11:10 [Server] ERROR java.lang.Thread.run(Thread.java:745)
19.12 20:11:10 [Server] ERROR ------------------------------
19.12 20:11:10 [Server] ERROR Entire Thread Dump:

19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
19.12 20:11:12 [Server] ERROR Metrics.Metrics.postPlugin(Metrics.java:475)
19.12 20:11:12 [Server] ERROR Metrics.Metrics.access$4(Metrics.java:354)
19.12 20:11:12 [Server] ERROR Metrics.Metrics$1.run(Metrics.java:227)
19.12 20:11:12 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
19.12 20:11:12 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
19.12 20:11:12 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
19.12 20:11:12 [Server] ERROR java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
19.12 20:11:12 [Server] ERROR java.lang.Thread.run(Thread.java:745)
19.12 20:11:12 [Server] ERROR ------------------------------
19.12 20:11:12 [Server] ERROR Current Thread: Craft Scheduler Thread - 20
19.12 20:11:12 [Server] ERROR PID: 108 | Suspended: false | Native: true | State: RUNNABLE
19.12 20:11:12 [Server] ERROR Thread is waiting on monitor(s):
19.12 20:11:12 [Server] ERROR Locked on:java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
19.12 20:11:12 [Server] ERROR Locked on:sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
19.12 20:11:12 [Server] ERROR Locked on:sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
19.12 20:11:12 [Server] ERROR Locked on:sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
19.12 20:11:12 [Server] ERROR Stack:
19.12 20:11:12 [Server] ERROR java.net.PlainSocketImpl.socketConnect(Native Method)
19.12 20:11:12 [Server] ERROR java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
19.12 20:11:12 [Server] ERROR java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
19.12 20:11:12 [Server] ERROR java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
19.12 20:11:12 [Server] ERROR java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
19.12 20:11:12 [Server] ERROR java.net.Socket.connect(Socket.java:589)
19.12 20:11:12 [Server] ERROR java.net.Socket.connect(Socket.java:538)
19.12 20:11:12 [Server] ERROR sun.net.NetworkClient.doConnect(NetworkClient.java:180)
19.12 20:11:12 [Server] ERROR sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
19.12 20:11:12 [Server] ERROR sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
19.12 20:11:12 [Server] ERROR sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
19.12 20:11:12 [Server] ERROR sun.net.www.http.HttpClient.New(HttpClient.java:308)
19.12 20:11:12 [Server] ERROR sun.net.www.http.HttpClient.New(HttpClient.java:326)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
19.12 20:11:12 [Server] ERROR com.praya.lifeessence.h.b.b(MCStats.java:318)
19.12 20:11:12 [Server] ERROR com.praya.lifeessence.h.b.a(MCStats.java:210)
19.12 20:11:12 [Server] ERROR com.praya.lifeessence.h.b$1.run(MCStats.java:125)
19.12 20:11:12 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
19.12 20:11:12 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
19.12 20:11:12 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
19.12 20:11:12 [Server] ERROR java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
19.12 20:11:12 [Server] ERROR java.lang.Thread.run(Thread.java:745)
19.12 20:11:12 [Server] ERROR ------------------------------
19.12 20:11:12 [Server] ERROR Current Thread: Craft Scheduler Thread - 19
19.12 20:11:12 [Server] ERROR PID: 107 | Suspended: false | Native: true | State: RUNNABLE
19.12 20:11:12 [Server] ERROR Thread is waiting on monitor(s):
19.12 20:11:12 [Server] ERROR Locked on:java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
19.12 20:11:12 [Server] ERROR Locked on:sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
19.12 20:11:12 [Server] ERROR Locked on:sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
19.12 20:11:12 [Server] ERROR Locked on:sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
19.12 20:11:12 [Server] ERROR Stack:
19.12 20:11:12 [Server] ERROR java.net.PlainSocketImpl.socketConnect(Native Method)
19.12 20:11:12 [Server] ERROR java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
19.12 20:11:12 [Server] ERROR java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
19.12 20:11:12 [Server] ERROR java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
19.12 20:11:12 [Server] ERROR java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
19.12 20:11:12 [Server] ERROR java.net.Socket.connect(Socket.java:589)
19.12 20:11:12 [Server] ERROR java.net.Socket.connect(Socket.java:538)
19.12 20:11:12 [Server] ERROR sun.net.NetworkClient.doConnect(NetworkClient.java:180)
19.12 20:11:12 [Server] ERROR sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
19.12 20:11:12 [Server] ERROR sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
19.12 20:11:12 [Server] ERROR sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
19.12 20:11:12 [Server] ERROR sun.net.www.http.HttpClient.New(HttpClient.java:308)
19.12 20:11:12 [Server] ERROR sun.net.www.http.HttpClient.New(HttpClient.java:326)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
19.12 20:11:12 [Server] ERROR io.lumine.xikage.mythicmobs.mcstats.MetricsLite.postPlugin(MetricsLite.java:365)
19.12 20:11:12 [Server] ERROR io.lumine.xikage.mythicmobs.mcstats.MetricsLite.access$200(MetricsLite.java:53)
19.12 20:11:12 [Server] ERROR io.lumine.xikage.mythicmobs.mcstats.MetricsLite$1.run(MetricsLite.java:175)
19.12 20:11:12 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
19.12 20:11:12 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
19.12 20:11:12 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
19.12 20:11:12 [Server] ERROR java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
19.12 20:11:12 [Server] ERROR java.lang.Thread.run(Thread.java:745)
19.12 20:11:12 [Server] ERROR ------------------------------
19.12 20:11:12 [Server] ERROR Current Thread: Craft Scheduler Thread - 18
19.12 20:11:12 [Server] ERROR PID: 106 | Suspended: false | Native: true | State: RUNNABLE
19.12 20:11:12 [Server] ERROR Thread is waiting on monitor(s):
19.12 20:11:12 [Server] ERROR Locked on:java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
19.12 20:11:12 [Server] ERROR Locked on:sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
19.12 20:11:12 [Server] ERROR Locked on:sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
19.12 20:11:12 [Server] ERROR Locked on:sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
19.12 20:11:12 [Server] ERROR Stack:
19.12 20:11:12 [Server] ERROR java.net.PlainSocketImpl.socketConnect(Native Method)
19.12 20:11:12 [Server] ERROR java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
19.12 20:11:12 [Server] ERROR java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
19.12 20:11:12 [Server] ERROR java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
19.12 20:11:12 [Server] ERROR java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
19.12 20:11:12 [Server] ERROR java.net.Socket.connect(Socket.java:589)
19.12 20:11:12 [Server] ERROR java.net.Socket.connect(Socket.java:538)
19.12 20:11:12 [Server] ERROR sun.net.NetworkClient.doConnect(NetworkClient.java:180)
19.12 20:11:12 [Server] ERROR sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
19.12 20:11:12 [Server] ERROR sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
19.12 20:11:12 [Server] ERROR sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
19.12 20:11:12 [Server] ERROR sun.net.www.http.HttpClient.New(HttpClient.java:308)
19.12 20:11:12 [Server] ERROR sun.net.www.http.HttpClient.New(HttpClient.java:326)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
19.12 20:11:12 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
19.12 20:11:12 [Server] ERROR net.citizensnpcs.Metrics.postPlugin(Metrics.java:400)
19.12 20:11:12 [Server] ERROR net.citizensnpcs.Metrics.access$500(Metrics.java:57)
19.12 20:11:12 [Server] ERROR net.citizensnpcs.Metrics$1.run(Metrics.java:486)
19.12 20:11:12 [Server] Startup Done (0.333s)
19.12 20:11:13 [Multicraft] Skipped 696 lines due to rate limit (200/s)

It mentions a few other plugin, but they all function correctly, even a server with Multiverse plugin only crashes.

**Comment by TWSSYesterday** [comment]
What version of Multiverse? What specific version of Spigot?
Have you tried using Paperspigot to get a different result?

**Comment by AnonymousBluejay** [comment]
I used 2.5, tried Latest Beta build and Latest Release build, used on Spigot 1.12.2 R0.1 SNAPSHOT b1461. It used to work perfectly fine, but a few weeks ago when I restarted the server one day it just started crashing. And no I have no tried Paperspigot.

**Comment by TWSSYesterday** [comment]
What is the version of Multiverse? That's the main part of the version, not the actual version itself

**Comment by AnonymousBluejay** [comment]
how do i check?

**Comment by AnonymousBluejay** [comment]
It seems like this is a config error, I deleted all of the worlds and config and this plugin seems to be working again, thank you for your effort to help.

**Comment by Shmacked** [comment]
I will note along the same lines ( I may have to create a new thread on this), my server crashes when I try to run the mvcreate command, to create a new world on the server... I am running it on a raspberry pi, so my first thoughts where maybe permission problems? It will start loading then it will crash. Everything is up to date... the server and the plugin. Advice - I may have to make a new thread.

**Comment by TWSSYesterday** [comment]
Hi @AnonymousBluejay You can do /ver Multiverse and it should come up. Thanks for letting us know it's resolved.
