### ISSUE TITLE
Spawn Handling

### ISSUE THREAD

**Issue by ninjaturdius** [Multiverse/Multiverse-Core#1886]
Is it possible to completely disable multiverse from handling player spawning in a world? I can't seem to find a way to do it in the config or world properties.

**Comment by TWSSYesterday** [comment]
Depends on what other settings the plugin you're using has. Essentials lets you set it's priority to highest which will override MV. If you need further help, let me know.

**Comment by ninjaturdius** [comment]
I was hoping to be able to get random-spawn to handle it, but when i looked for options that could help in its config, i couldn't find any regarding priority. I did find a workaround though, and decided not to use random-spawn after all.
