### ISSUE TITLE
My Mv World Create Do Not generate _NETHER even _THE_END HELP!

### ISSUE THREAD

**Issue by Rodagave115YT** [Multiverse/Multiverse-Core#1890]
Hello Everyone! I Hope You Are Doing Well!
I have a little issue with my plugin Multiverse-Core 
When I create a world Like ( /mvcreate Example ) the world creates succesfully but when I want to go to the Nether Or To The End It do not teleports me!
And that problem affects on my GroupManager because it do not recognize the world As a ( world )
And The Multiverse-Core tells me that the world is on the All_unnamed_worlds
Can You Please Please Help me out with this problem?
Thank You SO Much!!

**Comment by DjAlEx234** [comment]
It doesn't generate the end and the nether on its own. You have to set the world type with /mvcreate.
For example: "/mvcreate Example NETHER" or "/mvcreate Example END" (I am not sure about the end one).

**Comment by bc-hill** [comment]
This is implemented with [multiverse-netherportals](https://dev.bukkit.org/projects/multiverse-netherportals).
