### ISSUE TITLE
Chat Manager Issue

### ISSUE THREAD

**Issue by DjAlEx234** [Multiverse/Multiverse-Core#1891]
This is not an issue with the chat manager itself, the chat manager is the issue. I have another chat plugin installed but for some reason, multiverse takes priority over it. Mostly because multiverse has no anti-swear. And the plugin I have does.

**Comment by Jadiction** [comment]
Did you modify the Multiverse-Core configuration file to set "prefixchat" to false? Closing ticket due to lack of information. Please open a new ticket with more valid information if this issue is still occurring in the latest versions.
