### ISSUE TITLE
reload bug

### ISSUE THREAD

**Issue by iTaeyeonKim** [Multiverse/Multiverse-Core#1893]
when I reload the server, my worlds from any difficulty turns to EASY for some reason.
I tried stop the server and setup difficulties, and when i started all was normal, but when i again type /reload , difficulty was set to EASY again

**Comment by TWSSYesterday** [comment]
Don't reload the server. What versions of everything are you using? If you're going to treat the server badly (i.e. by using reload) then there isn't much we can do.

**Comment by Jadiction** [comment]
As mentioned, using /reload isn't recommended. Use the command /mvm set difficulty (while in the world) to change the difficulty. This is recommended because the config overwrites configurations during restarts (and I think reloads too).
