### ISSUE TITLE
Teleport Event

### ISSUE THREAD

**Issue by JoelDeadMach** [Multiverse/Multiverse-Core#1895]
Hello,

We have a fully custom core in our network but we use mv for extra worlds but we have an multiverse error when user want to to teleport!

Error: https://hastebin.com/wojofimika.vbs

How to fix this?
Also world permissions dont work

**Comment by TWSSYesterday** [comment]
Hi @JoelDeadMach This error doesn't seem to have anything Multiverse related in it, I'll leave this issue open for another couple of days in case you have another error that in fact does relate to Multiverse.
