### ISSUE TITLE
Whitelist certain item ids to cross between worlds?

### ISSUE THREAD

**Issue by boxedsarcasm** [Multiverse/Multiverse-Core#1896]
Hi, i have a server that had different gamemodes. I would like to know if it was possible to let an item pass?
Like if the item id was 5, that could go to my other worlds. Thanks :D

**Comment by Jadiction** [comment]
If I'm understanding correctly, you have different inventories and when you tp to another world, you'd like specific items allowed to stay in the inventory? If this is the case, letting specific items go through while using different inventories isn't possible. The exact inventory per world is saved. (I'm assuming you're using Multiverse-Inventories as well)
