### ISSUE TITLE
Awful alchemy: iron ingot turns into a gold nugget! What's the problem? (((

### ISSUE THREAD

**Issue by swordin** [Multiverse/Multiverse-Core#1897]
In the world that I created with the plugin Multiverse-Core the iron ingot turns into a gold nugget ((( 

pic:
https://file-up.net/big_b82ed10e04efebbae720180317092038.jpg

How to fix that?...

**Comment by sgdc3** [comment]
Impossible, not related to MV, some of your plugins is doing that...

**Comment by swordin** [comment]
well... I have got quite a standard set of plugins and there was nothing like this the whole year until I installed MV-Core & MV-Portals. 

I do not know how to explain such a fail miracle.

**Comment by dumptruckman** [comment]
Start up a test server with just the MV plugins and see that this effect does not occur. Then start adding plugins one by one, checking to see if the effect is now occurring. You will eventually discover which plugin is causing this.
