### ISSUE TITLE
Multiverse failed to import world

### ISSUE THREAD

**Issue by LoJoSho** [Multiverse/Multiverse-Core#1898]
Hello there, There is an earth map which I let my player base play on for now, I want to create a plain version of that, so I re-downloaded the whole map and uploaded it too the server files. I did /mv import and it started and failed. I checked the server console and here is what it does: 
https://pastebin.com/hiEnyrhN 
it just suddenly stops.

If you can help in anyway you can, that would be great. Thanks ~LoJoSho

**Comment by xtechgamer735** [comment]
Are you using the most recent builds from https://ci.onarandombox.com/view/Multiverse/?

**Comment by LoJoSho** [comment]
Thanks for the help, however I figured out what the problem was. I forgot to delete the uid.dat ! Still, I already updated it to the latest verison. Still thanks for the advice! Have a great day

**Comment by xtechgamer735** [comment]
Cool - no worries!
