### ISSUE TITLE
Set view distance per world

### ISSUE THREAD

**Issue by derheyne** [Multiverse/Multiverse-Core#1900]
Is there any way to set `view-distance` or `mob-spawn-rate` per world? I couldn't find anything in the wiki. At the start, chat-logs say it's 10 for all worlds, whether it's a nether or normal world or the end, but it's set to 16 in the `server.properties` and `spigot.yml`.

**Comment by Govindass** [comment]
you can set it per-world in spigot.yml file, just copy paste the default: part and rename "default:" into world name, for example "spawn:"

**Comment by Jadiction** [comment]
Solution posted - Closing ticket. Please don't hesitate to open a new ticket if you are still encountering issues.
