### ISSUE TITLE
Multiverse Respawn

### ISSUE THREAD

**Issue by CoolLord22** [Multiverse/Multiverse-Core#1901]
Is there a way to override multiverse's handling of respawning? I'm using https://www.spigotmc.org/resources/worldguard-extra-flags.4823/ to change the respawn location when players die but it overrides to the world spawn...

**Comment by Jadiction** [comment]
Hello, is this still an issue? What is your configuration file, multiverse version, and Minecraft version? Is your respawnWorld set? Try making it empty (which should default respawn to that world). If that doesn't work, I'd try asking that plugin's developer what they can do to prioritize over Multiverse's method when using respawn flags.
