### ISSUE TITLE
Does world un-loading mean the world uses less ram?

### ISSUE THREAD

**Issue by RileyDatLord** [Multiverse/Multiverse-Core#1903]
What I am trying to say is does unloading a world make it use less ram? So that if I have multiple worlds, I can unload a world if theres no players on it, then if someone tries to go to that world it loads it again

**Comment by Govindass** [comment]
world loading causes a lagspike server-wide so that is not a good idea, better keep them loaded

**Comment by RileyDatLord** [comment]
> world loading causes a lagspike server-wide so that is not a good idea, better keep them loaded

Yeah I am fine with that, I’m just wondering if unloading a world will use less ram?

**Comment by Govindass** [comment]
> > world loading causes a lagspike server-wide so that is not a good idea, better keep them loaded
> 
> Yeah I am fine with that, I’m just wondering if unloading a world will use less ram?

maybe, but if you have spawn chunks disabled it should be okay to keep them loaded. I have 55 worlds loaded at once without RAM problems on 4gb ram allocated.

**Comment by RileyDatLord** [comment]
Ok thanks, sorry for late response!
