### ISSUE TITLE
Structures spawning on custom world

### ISSUE THREAD

**Issue by TheDragonsRoost** [Multiverse/Multiverse-Core#1906]
Hi,
I have a problem here. I recently imported a custom world I made for my roleplay server and no matter what, structures spawn. I want to try and get rid of them, but Multiverse won't let me change the "structures" part from true to false.
Is there some way to turn off structures in Multiverse?

**Comment by benwoo1110** [comment]
You cant disable structures after the world is created, you need to disable it on world creation. For mv create command I believe its the `-a false` flag.

**Comment by benwoo1110** [comment]
Also closing this issue as its inactivity. Feel free to create a new issue if needed or join our discord at https://discord.gg/NZtfKky
