### ISSUE TITLE
Can I disable certain/all Plugins on a world?

### ISSUE THREAD

**Issue by Venetevo** [Multiverse/Multiverse-Core#1913]
Please help! I want to disable some of my plugins if I can, but If I can't, I can settle for all my plugins disabled, But just on that one world.

**Comment by Venetevo** [comment]
Anybody?

**Comment by TWSSYesterday** [comment]
Hi @Venetevo This isn't possible through the Multiverse project. I would recommend looking elsewhere for this. Bare in mind, you may be better off running a bungee system as having this in place is known to cause multiple issues; performance being one with your server.
