### ISSUE TITLE
Customized world Generation?

### ISSUE THREAD

**Issue by Wasdspacemouse** [Multiverse/Multiverse-Core#1914]
I've been trying for the past few days to either import a world with custom generation, or let my server do it for me. I tried using the generator-settings in server.properties in my vanilla test world and it worked just fine, but when I use it in my main server, the world turns out default (with the exception of my fixedbiome being ocean). So it seems like something is causing the world to not generate like it would in vanilla. While I can't guarantee this is caused from Multiverse, I can say Multiverse is the only plugin I have that handles the worlds, so I could only imagine it's caused by this. Just in case, I've attached a photo of my plugins below. 
![plugs](https://user-images.githubusercontent.com/29446039/41559016-0380f3f8-7300-11e8-8731-3fe985b306bb.PNG)

**Comment by Jadiction** [comment]
Can you try turning your server off (or test locally), only using Multiverse, specifying your world generation and then seeing if it works? Remember to modify the config files while the server is offline.

**Comment by Wasdspacemouse** [comment]
I managed to solve this issue almost a year ago by manually loading all the chunks in a singleplayer world, then importing the world to my server. It's not the prettiest solution, but considering I'm no longer actively working on my server, I figured I'd suggest my crude solution and call it at that.
