### ISSUE TITLE
Weird bug: Drops get deleted by Multiverse 

### ISSUE THREAD

**Issue by bloggy** [Multiverse/Multiverse-Core#1915]
I am unable to drop any item. I have to delete the multiverse world.yml folder to make it work again.
There is some message that entity was killed in the console.
What is this? And how to fix?

**Comment by ryantheleach** [comment]
I don't understand how you pinned multiverse on this?

When you delete world.yml are you reloading the worlds? logging out? restarting the server?

Try those steps when the bug happens with multiverse, and if it still 'fixes' it, why do you think it's multiverse?

If you also disable multiverse, you might be able to get the bug to trigger.

Is this related to when you go through portals at all?
