### ISSUE TITLE
I can't tp to my glitched world HELP!!!!!

### ISSUE THREAD

**Issue by FLUTTERDASH5000** [Multiverse/Multiverse-Core#1916]
I accidently put in a command block on one of my world that has a repeated /butcher command and now no monsters can spawn in any world, all i need to do is break it, i know, but my problem is that i cant get there, the world is called Wolf Blade High. Do you see my problem now, iu accidently made the name impossible to get to. Does anyone have a solution for this, or just deleting the world works too? I cant delete it either becausde of the spaces, also the commands per world plugin doesnt work either cause its on a broadcasting thing too. PLEASE HELP ME MY SMP IS GONNA BE RUINED!!!!!

**Comment by dumptruckman** [comment]
Try surrounding the name with quotes when using commands.

**Comment by FLUTTERDASH5000** [comment]
it works thx

**Comment by FLUTTERDASH5000** [comment]
@ryantheleach i cant disable command blocks because i use command blocks for other things, also im in 1.12

**Comment by ryantheleach** [comment]
I was meaning to only disable them while you fixed it.

**Comment by FLUTTERDASH5000** [comment]
i cant get to the world because it was infected with a virus so it restarted itself and the command block is gone
