### ISSUE TITLE
Switch from mcstats to bstats

### ISSUE THREAD

**Issue by garypwn** [Multiverse/Multiverse-Core#1918]
Is far as I can tell, mcstats has not been supported since 2015. The site is still up, but there have been significant patches of downtime, the creator does not respond to issues on his github, and most plugin authors have bailed and switched to bStats. Multiverse has mcstats as a compile dependency, and it makes building any project that depends on Multiverse a bad time.

**Comment by FernFerret** [comment]
Ah interesting, sorry, this one slipped through my radar, I'm going through trying to do a bit of spring (winter?) cleaning. This one is totally on my list now.
