### ISSUE TITLE
My world is unloaded and i can't load it

### ISSUE THREAD

**Issue by gofiguretwitch** [Multiverse/Multiverse-Core#1921]
So my skywars world is unloaded and when i do /mv load skywars. It says error trying to load skywars and it does nothing can i get help?

**Comment by brobie1kanobi** [comment]
I know this is an old thread but I have dealt with this so I figured I would offer my knowledge..
Adding "normal" to the end to your command will help (ex. /mv load skywars normal). I have had it where that doesn't even help, in that case you need to unzip/ rezip the file for the world, remove the world and re-upload the file to the file manager again. It's taken 3 or 4 times but it will work.
