### ISSUE TITLE
World generator not injected for default world

### ISSUE THREAD

**Issue by Pieter12345** [Multiverse/Multiverse-Core#1924]
Having a setup with two worlds with the same custom world generator which only differ in UUID and name, the custom world generator does not get injected for the world which is set to be the `firstspawnworld` (in `Multiverse-Core/config.yml`) and the `level-name` (in `server.properties`).

Tests that verify the existence of this bug:
- For the spawn world: Bukkit.getServer().getWorld("spawnWorld").generator == null
- For the other world: Bukkit.getServer().getWorld("otherWorld").generator == \<My world generator instance\>
- Bukkit.getServer().getPluginManager().getPlugin("Multiverse-Core").getMVWorldManager().getMVWorld(org.bukkit.Bukkit.getServer().getWorld("spawnWorld")).getGenerator() == \<My world generator name\>
- Bukkit.getServer().getPluginManager().getPlugin("Multiverse-Core").getMVWorldManager().getMVWorld(org.bukkit.Bukkit.getServer().getWorld("otherWorld")).getGenerator() == \<My world generator name\>

This results in the end-user being unable to set a custom world generator for the default/spawn world, even though it is properly set according to the config.

**Comment by altrisi** [comment]
Probably the same as #1602 
As suggested, a temporary fix is to use bukkit.yml generator for the main world ([See in the issue](https://github.com/Multiverse/Multiverse-Core/issues/1602#issuecomment-192756658))
As also suggested at the same issue, _you cannot override the standard overworld generator for the main world set in server.properties_ ([See in the issue](https://github.com/Multiverse/Multiverse-Core/issues/1602#issuecomment-192757023)) _except with bukkit.yml_
