### ISSUE TITLE
Random Error on teleporting to worlds

### ISSUE THREAD

**Issue by SoraShiunin** [Multiverse/Multiverse-Core#1928]
Only happens sometimes. 
So not sure how to replicate it every time, but it happens when you go from one world to another sometimes.
Looks like it also happens when a player joins the server.
https://pastebin.com/B882NidC

**Comment by Jadiction** [comment]
This looks like the error is coming from the plugin "Discordsrv", the error shows it's hooking Multiverse. Closing ticket as this does not pertain to the Multiverse-Core plugin.
