### ISSUE TITLE
Multiverse

### ISSUE THREAD

**Issue by Misio12320** [Multiverse/Multiverse-Core#1929]
Hello I have a problem with my server my world have over 1.89GB and yesterday I cloned this world worked fine and after stop it just rolled back.. https://pastebin.com/SJhRwdjz version 1.13 Plugins: https://ibb.co/kK1Eve

**Comment by Codewow** [comment]
Plugin isn't updated for 1.13 so it may have issues running on it.

**Comment by Misio12320** [comment]
Well why my Multiverse gamerule doesn't save... DoMotLoot true everytime it makes deny

**Comment by Jadiction** [comment]
When you modify your gamerule, do you use a command or edit the configuration file? When modifying the config file, your server needs to be offline. The server crashed, so it's no question why it rolled back; it couldn't save before shutting down. Are you still having issues with crashes with it relating to Multiverse?

**Comment by Misio12320** [comment]
I was using command. Nope, I dont have any problems while shutting down the server also its old and i changed hosting so its another now.
