### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Misio12320** [Multiverse/Multiverse-Core#1930]
Hello. Please add feature to clone world without fill or decrease the memory of this world.
+ Add option to change another world to this.. Like I have 2 worlds: 1 its world and other is world2 and I want copy the world2 to world... hm

**Comment by FernFerret** [comment]
I'm sorry this is out of the scope of what I'd like to do in this project. I'm just trying to clean up some issues (again) and this isn't one I see getting done.

**Comment by Misio12320** [comment]
Its old and outdated my message... And suggestion to make a per world alias or something? I want to do world1 nick: message world2 [worldname] nick: message etc?
