### ISSUE TITLE
multiverse api?

### ISSUE THREAD

**Issue by supercas240** [Multiverse/Multiverse-Core#1932]
trying to use the multiverse api in a plugin, but i can barely find any information on it.

**Comment by FernFerret** [comment]
All of our Java code is pretty well documented, so we generate JavaDocs from there and put them on [our Jenkins server](https://ci.onarandombox.com/job/Multiverse-Core/javadoc/). All of the plugins implement the APIs provided in Core, so they're pretty good places to look too.
