### ISSUE TITLE
Multiverse Bypass Permission Node Not Working

### ISSUE THREAD

**Issue by Blue-Fred** [Multiverse/Multiverse-Core#1937]
So, a while ago I added the mv.bypass.gamemode.* to my Admin group.  It worked for a while, but now it's not working.
![image](https://user-images.githubusercontent.com/43733076/46263857-69b22f80-c4da-11e8-8179-a377b568d79f.png)
![image](https://user-images.githubusercontent.com/43733076/46263862-7a62a580-c4da-11e8-954b-329662410c36.png)

I'm using Luckperms, can I have some help in trying to fix this?

**Comment by Blue-Fred** [comment]
Also, plugins I am using:
- Multiverse-Core-2.6.0
- Multiverse-Portals-2.5.2-SNAPSHOT
- Multiverse-NetherPortals-2.5.2-SNAPSHOT
- Multiverse-SignPortals-2.5.2-SNAPSHOT
- LuckPerms-Bukkit-4.2.58
- HolographicDisplays
- EssentialsX-2.15.0.1
- EssentialsXChat-2.15.0.1
- ColoredSigns-2.0
- CleanroomGenerator-1.1.0
- ProtocolLib
- Vault-1.7.1
- worldedit-bukkit-7.0.0-SNAPSHOT-dist
- worldguard-legacy-7.0.0-SNAPSHOT-dist

I believe the error is either with Multiverse, EssentialsX, or LuckPerms.

**Comment by Jadiction** [comment]
Hi, is this still happening?

I just tested this and was unable to replicate.

>mv.bypass.gamemode.* assigned to my group/player
>In creative gamemode world
>Go to survival gamemode world
>Stay in creative gamemode

Are you using the latest version of Multiverse?

**Comment by Jadiction** [comment]
Closing ticket because it's old. Update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists or for a faster response, you can also receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
