### ISSUE TITLE
Selectors like @p don't work with /mvtp

### ISSUE THREAD

**Issue by liamcullins** [Multiverse/Multiverse-Core#1938]
Plugin version: Build 719
Minecraft version: 1.13.1
Spigot version: git-Spigot-f6a273b-8ab46ff

I'm attempting to write a command in a command block that teleports any player that moves over a certain spot to a different world. Here's what I wrote, just for reference's sake (space in selector is intentional, and not present in the command I wrote in the block):

_/mvtp  @ a[x=-6,y=55,z=-16,distance=..1] Amplified_

The error message I got back was something along the lines of "Sorry, player @a[x=-6,y=55,z=-16,distance=..1] not found". It isn't recognizing the selector as such, but instead is interpreting it as a player username. Also, using /execute doesn't work, either, since it gives me red text at the end when I put /mvtp in as the command to run. I'm guessing this is because /execute won't recognize non-vanilla commands. Again, for reference's sake:

_/execute as entity @ e[type=player,x=-6,y=55,z=-16,distance=..1] run /mvtp Amplified_

**Comment by EbonJaeger** [comment]
The selectors are a thing that are built in to vanilla commands; any plugin that wants to use something like them has to do it all themselves.

**Comment by liamcullins** [comment]
Does this mean that they'll never work? They worked just fine in 1.12.2. Also, do you have any suggestions on how to achieve the desired effect, rather than just telling players that they need to use the _/mvtp_ command to teleport to the desired world?

**Comment by EbonJaeger** [comment]
MultiVerse-Portals exists for just this kind of thing.

**Comment by liamcullins** [comment]
I'd been using a development build of Multiverse and Multiverse-Portals, because I figured the old stable version for 1.12 wouldn't work on a 1.13.1 server. Since switching back to the stable build, I was able to make a portal just fine. However, having the dev 1.13 version of WorldEdit installed alongside Multiverse breaks the _/mvpcreate_ command. Hopefully this changes soon, unless the old 1.12 version of WorldEdit will still work in 1.13.1.

**Comment by EbonJaeger** [comment]
I think that was fixed in the latest code, at least looking at the Github commits from last month.

**Comment by liamcullins** [comment]
Version 7.0.0 of WorldEdit, or Multiverse Portals?

**Comment by EbonJaeger** [comment]
WorldEdit. Sorry, I edited it in after.

**Comment by liamcullins** [comment]
I downloaded the [last successful build of WorldEdit](http://builds.enginehub.org/job/worldedit/last-successful?branch=master) (#3905), and the _/mvpcreate_ command still gives me an error message when trying to use it.

**Comment by liamcullins** [comment]
If I'm running my server using Spigot, should I be using _worldedit-bukkit-7.0.0-SNAPSHOT-dist.jar_ or _worldedit-core-7.0.0-SNAPSHOT-dist.jar_?

**Comment by EbonJaeger** [comment]
I would say to create a new issue on the MV-P Github page, then.

**Fake Edit:** worldedit-bukkit-7.0.0-SNAPSHOT-dist.jar

**Comment by dumptruckman** [comment]
You have to use the latest dev builds of Multiverse-Portals for compatibility with the latest WorldEdit. https://ci.onarandombox.com/job/Multiverse-Portals/

**Comment by MrPistachios** [comment]
if you want to use selectors you can use a plugin like command hook
https://www.spigotmc.org/resources/commandhook.61415/

We ended up using portals also but still needed selectors for other things, like letting our players add their own prefix color
