### ISSUE TITLE
/mv delete doesnt delete worlds 

### ISSUE THREAD

**Issue by Hexical1** [Multiverse/Multiverse-Core#1943]
I'm on 2.6.0 with Spigot on 1.12.2

Whenever I try to /mv delete a world, it gives me a confirmation that the world was deleted - but upon restart the world re-appears.

**Comment by Jadiction** [comment]
Is this still happening? What is the world's name? Can you check after /mv delete if the world folder is deleted? If so, then it sounds like upon restart that a plugin is regenerated the world, or you have your default world specified as the world you're deleted and it's required on server start so it generates.

**Comment by Jadiction** [comment]
Closing ticket due to lack of information. Please open a new ticket with more valid information if this issue is still occurring in the latest versions or for a faster response, you can also receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
