### ISSUE TITLE
Worlds keep unloading randomly

### ISSUE THREAD

**Issue by LebsterFace** [Multiverse/Multiverse-Core#1945]
My worlds keep unloading randomly
I've already set them all to autoload true and memory true but nothing seems to be working
I need all worlds to be loaded at all times

https://pastebin.com/raw/S60Pnkeh - Multiverse version
https://pastebin.com/raw/zTw6rUgw - Startup log
https://pastebin.com/raw/h7drseH1 - Multiverse worlds.yml

**Comment by LebsterFace** [comment]
HELLO?

**Comment by LebsterFace** [comment]
HELLO!?!?

**Comment by LebsterFace** [comment]
?????

**Comment by Jadiction** [comment]
Is this still happening? With all those plugins and errors upon startup, I suspect a possible plugin conflict that keeps "unloading" your worlds. Can you try running just Multiverse plugins and see if the issue persists?

**Comment by LebsterFace** [comment]
It has been so long since creating this issue that I have found a workaround by just repeatedly loading the worlds

**Comment by Jadiction** [comment]
Yeah, sorry about that. I was just added to this project yesterday. I will do my best to clean up these tickets starting now. Thanks for the reply.
