### ISSUE TITLE
 Auto-tab-complete hide command if player has no permission

### ISSUE THREAD

**Issue by x1p** [Multiverse/Multiverse-Core#1947]
**Description of issue or feature request:**
Players who don't have access to specific commands are still able to tab complete them in 1.13.x
Players see much commands they should not be able to see using /(tab). There are about 50 commands which normal players should not be able to see. This of course should not happen.
I'm no dev, but it's been said that the key lies in the plugin.yml which should state all commands and their permissions.

Can this be solved?

**Comment by Jadiction** [comment]
Closing as this is not a Multiverse issue.
