### ISSUE TITLE
Galacticraft 3 issue

### ISSUE THREAD

**Issue by KevinMagers** [Multiverse/Multiverse-Core#1950]
I'm running the 1.7.10 pack from the technic launcher and I'm running the server with Thermos 1.7.10-1614,  MV2.5 itself seems to work properly on its own however once MV is present, galacticraft planet select GUI bugs out when selecting anything other than overworld or satellite. I've been able to manually go to some planets/moons via mv tp to get them to start generating/loading and it will work to fix the gui issue for the planet loaded, but this is only temporary fix, issue starts all over once the server restarts. I understand this may not be a direct issue with MV so i am also making a nearly identical ticket with galacticraft
![guierror](https://user-images.githubusercontent.com/14279193/50126650-6a35a900-0233-11e9-9e70-b08ec7ad233e.PNG)

**Comment by Jadiction** [comment]
Hello, it's unlikely Multiverse will do anything for this as it's not a Multiverse issue than it is a conflict. Your best bet is to contact the other developer(s) and see if they can find a solution.
