### ISSUE TITLE
May be posted in the wrong area, noob question..

### ISSUE THREAD

**Issue by brobie1kanobi** [Multiverse/Multiverse-Core#1951]
First, I am sorry if this is in the wrong thread/area, but I am new to this forum. I am just wondering, when giving someone a single world permission to access an individual world, (i.e. multiverse.access.example) are aliases counted toward giving said permission. To clarify: I have a world called "Thunder Dome" (with a space) and it's alias is set as "td". Do I give them the permission "multiverse.access.thunder_dome" or can I just use "multiverse.access.td"? 
Also, thank you for taking the time to make this plugin! It is freaking awesome! 
Another note, I am running a server via Minehut, so I am unable to update to the newest version, though everything seems to work aside from the occasional "starting import of world" and then I get "internal error while attempting to process (or something like that)". The console tells me it's a "spawn null location" error even though I have set the spawn for said world prior to upload to the file directory. I tried taking a screenshot, but couldn't find it to share here.. -_- hopefully I described my "issue" well enough.

Feel free to close this "issue" as I am aware it is NOT an actual issue, I just didn't find anywhere I was supposed to post a question.
  Thank you in advance for your time! 
Dan

**Comment by Jadiction** [comment]
Hi, I believe the permission node requires you to use the name given when imported/created. I'd recommend sticking to lowercase and one-word world names as it's better practice for the later versions of Minecraft in terms of plugin compatibility and Minecraft itself. You can try the alias for the permission node and see if it works, but I'm not seeing any documentation show aliases work. As for the other issue, you likely won't receive any support from older plugin versions as bug fixes are implemented in newer versions and your issue may be fixed already.
