### ISSUE TITLE
ci.onarandombox.com's cert is expired

### ISSUE THREAD

**Issue by FernFerret** [Multiverse/Multiverse-Core#1952]
Looks like the cert expired Nov 27th... whoops.

**Comment by sgdc3** [comment]
@FernFerret can't you just switch to cloudflare?

**Comment by sgdc3** [comment]
Ok, if for any reason you need a new buildserver i'm the maintainer of ci.codemc.org, a public jenkins/nexus for minecraft related projects, i would be glad to host the mv suite projects ;)

**Comment by Rigby90** [comment]
Apologies. It's running LetsEncrypt but looks like I broke the automated renewal last time round. Not sure why I didn't get any alerts! Should be resolved now and will check on it again in the new year when it should 'automatically' renew again.

I've previously spoke with @dumptruckman about moving CI's, however he seemed happy with leaving things as is.

Appreciate the offer @sgdc3 , but as I've taken a step back from the project and dealings with MV it's entirely up to the active maintainers and contributors as to how it is all handled.


Merry Christmas, hope you all have a great time!

@FernFerret - Thank you for tagging me. Hope all is well!

**Comment by FernFerret** [comment]
Thanks @Rigby90! I think it's safe to say that while I have a desire to make some minor improvements, I don't want to (nor do I have the time) to change the build system. So many projects floating around...
