### ISSUE TITLE
Multiverse doesn't know about world

### ISSUE THREAD

**Issue by AvianKing** [Multiverse/Multiverse-Core#1956]
Hi, I get this message when I'm trying to remove a world from my server:
14.01 21:20:30 [Server] INFO [Multiverse-Core] Multiverse does not know about 'Seasons' and it's not loaded by Bukkit.
But the world exists in the config file. The world is called Enchanted Seasons and it lists the alias as "Seasons".
Do I need to use the full name to remove it, and if so how do I do that when the name is two words with a space in between?
![screenshot 717](https://user-images.githubusercontent.com/46692618/51143048-94bb5780-181b-11e9-9c22-91a5bb724639.png)

**Comment by dumptruckman** [comment]
Try using `/mv remove "Enchanted Seasons"`.

**Comment by Jadiction** [comment]
Going to assume this is solved - closing the ticket. If you're still having issues, please don't hesitate to make another ticket or for a faster response, you can also receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
