### ISSUE TITLE
Error when trying to build from GitHub

### ISSUE THREAD

**Issue by EGobi** [Multiverse/Multiverse-Core#1957]
I can't build MVC 2.6.0 from source. Maven throws the following error:
`[ERROR] Failed to execute goal on project Multiverse-Core: Could not resolve dependencies for project com.onarandombox.multiversecore:Multiverse-Core:jar:2.6.0: Could not transfer artifact org.spigotmc:spigot-api:jar:1.12-R0.1-20170803.111256-74 from/to spigot-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/): No PSK available. Unable to resume.`

For now, I'll be sticking with version 2.5.0 from the bukkit.org project page.

**Comment by OpticFusion1** [comment]
@EGobi Try my fork of the plugin https://github.com/OpticFusion1/Multiverse-Core see if it errors as well

**Comment by EGobi** [comment]
@OpticFusion1, thanks buddy, at first I got the following error:
`[ERROR] Failed to execute goal on project Multiverse-Core: Could not resolve dependencies for project com.onarandombox.multiversecore:Multiverse-Core:jar:2.7.4: Could not transfer artifact org.bukkit:bukkit:jar:1.9-R0.1-20160330.160319-146 from/to spigot-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/): peer not authenticated`

But then I fixed it running `mvn install -D maven.wagon.http.ssl.insecure=true -D maven.wagon.http.ssl.allowall=true`. Now I get the following error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:testCompile (default-testCompile) on project Multiverse-Core: Compilation failure: Compilation failure:
[ERROR] /C:/Users/.../Downloads/Multiverse-Core-master/Multiverse-Core-master/src/test/java/com/onarandombox/MultiverseCore/TestWorldProperties.java:[155,32] cannot find symbol
[ERROR]   symbol:   method getPrice()
[ERROR]   location: variable mvWorld of type com.onarandombox.MultiverseCore.api.MultiverseWorld
[ERROR] /C:/Users/.../Downloads/Multiverse-Core-master/Multiverse-Core-master/src/test/java/com/onarandombox/MultiverseCore/TestWorldProperties.java:[238,16] cannot find symbol
[ERROR]   symbol:   method setPrice(double)
[ERROR]   location: variable mvWorld of type com.onarandombox.MultiverseCore.api.MultiverseWorld
[ERROR] /C:/Users/.../Downloads/Multiverse-Core-master/Multiverse-Core-master/src/test/java/com/onarandombox/MultiverseCore/TestWorldProperties.java:[239,33] cannot find symbol
[ERROR]   symbol:   method getPrice()
[ERROR]   location: variable mvWorld of type com.onarandombox.MultiverseCore.api.MultiverseWorld
[ERROR] /C:/Users/.../Downloads/Multiverse-Core-master/Multiverse-Core-master/src/test/java/com/onarandombox/MultiverseCore/TestWorldProperties.java:[336,33] cannot find symbol
[ERROR]   symbol:   method getPrice()
[ERROR]   location: variable mvWorld of type com.onarandombox.MultiverseCore.api.MultiverseWorld
```
Which I have no clue on how to fix…

**Comment by OpticFusion1** [comment]
@EGobi if you're using my fork of the plugin make sure to make a new issue at https://github.com/OpticFusion1/Multiverse-Core/issues/new <3 and i'll look into that

**Comment by dumptruckman** [comment]
You shouldn't have to build spigot locally when all that is needed is spigot-api. In any case, I've finally gotten around to updating mv-core to 1.13 and have went back to the bukkit api instead. We were never using any of the features added in spigot-api so I thought it'd be best to build against bukkit to increase compatibility.

**Comment by OpticFusion1** [comment]
> 
> 
> @OpticFusion1 Out of curiosity, why are you promoting your own branch instead of attempting to improve our existing one? We are always open to pull requests. If you'd like to discuss working more closely on the project I'd be more than happy to talk about that as well. Feel free to join our [discord chat](https://discord.gg/NZtfKky)

https://github.com/Multiverse/Multiverse-Core/wiki/How-can-I-help#things-to-keep-in-mind-for-pull-requests

more specifically

"However, there are a few things to keep in mind, such as backward compatibility and efficiency <insert MV-Portals efficiency joke here>." my fork completely removes pretty much any and all backwards compatibility nor do i plan to because i don't like supporting 1.8-1.12.2, the only backwards compatibility i do have planned is only there so i can convert configs to use 1.13+ materials and that's only temp..

**Comment by OpticFusion1** [comment]
so yea, i could PR, but literally every single PR i make would go against the whole "backwards compatibility" thing, whether it be removing backwards compatibility, or just not supporting it in any way, shape or form..

**Comment by dumptruckman** [comment]
@EGobi how come you're trying to build from source anyway? Particularly if you're just going to use a published binary when you can't. If you would still like to build from source, please try again with the latest updates as there's been some significant changes.

**Comment by EGobi** [comment]
@dumptruckman, unfortunately now I get IllegalArgumentException errors…
```[ERROR] Failed to execute goal se.eris:notnull-instrumenter-maven-plugin:0.6.8:instrument (default) on project Multiverse-Core: Execution default of goal se.eris:notnull-instrumenter-maven-plugin:0.6.8:instrument failed: NotNull instrumentation failed for […]\Multiverse-Core\target\classes\com\onarandombox\MultiverseCore\commands\InfoCommand.class: java.lang.IllegalArgumentException: Unsupported class file major version 55```

**Comment by dumptruckman** [comment]
@EGobi so it seems you somehow compiled for java 11. The NotNull instrumented does not support java 11.
