### ISSUE TITLE
Vanilla Command Selectors

### ISSUE THREAD

**Issue by Geant200** [Multiverse/Multiverse-Core#1961]
Hello,

I made an update of my server to version 1.13.2.

Before my server was in version 1.12.

Here is my problem on my server I made a teleportation system using a block command and with a pressure plate and the restone as on the images that am.

Portal image 1
http://www.war-team.com/images/autre/perso/minecraft/commande_tp_1.jpg

Portal image 2
http://www.war-team.com/images/autre/perso/minecraft/commande_tp_2.jpg

In the block command I placed the following command line.
` /mv tp @p[distance=6] e:redstone_guide:-4,102,7`

Block command image
http://www.war-team.com/images/autre/perso/minecraft/commande_tp_3.jpg

Before in 1.12 the command was the following.
`/mv tp @p[r=6] e:redstone_guide:-4,102,7`

In 1.13.2 I test the next command line but it does not work.
` /mv tp @p[distance=6] e:redstone_guide:-4,102,7`

Can you give me a solution to make it work?

Multiverse is still compatible for version 1.13.2?

I thank you in advance.

**Comment by SlimeDog** [comment]
@p[distance=..6] ?

**Comment by Geant200** [comment]
All players within 6 blocks are teleported.

**Comment by dumptruckman** [comment]
I'm fairly certain that has never been an option in Multiverse-Core. Perhaps you have a third party plugin that has added this feature?

**Comment by Geant200** [comment]
I've always done like that and I'm not a plugin that can not distance I just Spigot server interface but I do not think it's him ^^.

**Comment by Geant200** [comment]
But it's really Multiverse version 1.13.2 that I need I doubt that it's a job to stay up to date I thank the developers in advance.

I noticed that the developers work on Multiverse 3?

Can you tell me an update will happen for 1.13.2 or a new Multiverse 3?

Thank you in advance.

**Comment by dumptruckman** [comment]
Thanks. That error has been resolved and new versions of Multiverse-Core and Multiverse-Portals are available: https://ci.onarandombox.com/job/Multiverse-Core/757/ https://ci.onarandombox.com/job/Multiverse-Portals/784/

**Comment by dumptruckman** [comment]
If all you need is a version of MV for 1.13, those should work and you can close this ticket. However, they're still largely untested so it is still possible similar errors could pop up. Please open a new ticket for any more errors like that.

**Comment by Geant200** [comment]
I just tested the following version: Multiverse-Portals v3.0.0-SNAPSHOT-b784


What command I must add in the command block to tell me tp coordinates in another world.

exemple : `/mv tp @p[distance=6] e:redstone_guide:-4,102,7`  ??

Portal image 1
http://www.war-team.com/images/autre/perso/minecraft/commande_tp_1.jpg

I have an error in the Log as follows:

`[14:42:25] [Server thread/ERROR]: Error occurred while enabling Multiverse-Portals v3.0.0-SNAPSHOT-b784 (Is it up to date?)
java.lang.IllegalArgumentException: Name cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.Material.matchMaterial(Material.java:3860) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.Material.matchMaterial(Material.java:3845) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at com.onarandombox.MultiverseCore.utils.MaterialConverter.convertTypeString(MaterialConverter.java:39) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.MaterialConverter.convertConfigType(MaterialConverter.java:24) ~[?:?]
	at com.onarandombox.MultiversePortals.MVPortal.loadMVPortalFromConfig(MVPortal.java:188) ~[?:?]
	at com.onarandombox.MultiversePortals.MultiversePortals.loadPortals(MultiversePortals.java:230) ~[?:?]
	at com.onarandombox.MultiversePortals.MultiversePortals.onEnable(MultiversePortals.java:141) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:579) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:541) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:419) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`

**Comment by Geant200** [comment]
Multiverse-Portals v3.0.0-SNAPSHOT-b785

It's good I have more error in the log ^^.

But for the command I can not find ^^.

**Comment by dumptruckman** [comment]
So the error is fixed now? If not please update to the latest Core where it should be fixed: https://ci.onarandombox.com/job/Multiverse-Core/758/

I'm afraid I'm still not quite sure what you're trying to achieve with the command. Can you please explain it again?

**Comment by SlimeDog** [comment]
Suggestion: Define those 3x2 areas as Multiverse-Portals portals, and let them do the work.

**Comment by Geant200** [comment]
I already use for other portal but for this portal room I want to use a command block.

**Comment by Geant200** [comment]
It must have a command that works in 1.13.2 with Multiverse as in 1.12 ^^.

**Comment by SlimeDog** [comment]
I would be better to use the portal functionality than use a command block and pressure plate and etc..

**Comment by Geant200** [comment]
I suspect but I have gateways that are not built the same and I need to use the redstone system with a command block ^^.

**Comment by SlimeDog** [comment]
> @p[distance=..6] ?
> All players within 6 blocks are teleported.

So make it
> @p[distance=..2] or whatever works to guarantee only the player standing on the pressure plate.

**Comment by Geant200** [comment]
I tested with the following command does not work.

`/mv tp @p [distance =2] e: redstone_guide: -4,102,7`

can you give me a complete example of the command to place in the command block please.

**Comment by SlimeDog** [comment]
The dots are important!
> @p[distance=..2]

**Comment by Geant200** [comment]
Still not working.

/mv tp @p[distance=..2] e: redstone_guide: -4,102,7

**Comment by SlimeDog** [comment]
What is the error message? "not working" is not very useful.

**Comment by Geant200** [comment]
No error message when I go on the pressure plate that I laugh at all I'm not teleporting.

**Comment by SlimeDog** [comment]
From my own testing just now, it seems that vanilla @ entity selectors do not work with the **_mvtp_** command; only explicitly player names Over to the MV devs. :(

**Comment by Geant200** [comment]
My video test
https://www.youtube.com/watch?v=Ssx6-eRuXoA&feature=youtu.be

You need to develop a hotfix? for Multiverse.

**Comment by EbonJaeger** [comment]
The selectors are different in 1.13 in Spigot. Plugins have to implement them themselves now, iirc, which is immensely stupid. Which is Spigot for ya.

**Comment by Geant200** [comment]
`Which is Spigot for ya. `

?? I do not understand your question sorry.

**Comment by SlimeDog** [comment]
@Geant200 While you're waiting, may I recommend [CommandSigns](https://www.spigotmc.org/resources/command-signs.10512/), which you can attach to pressure plates as well as signs and buttons, to produce similar results (and no command block required). This method works fine in both 1.12.2 and 1.13.x. With CommandSigns, a players selector would not be required, since the player who triggers the pressureplate is the selected entity (%player% also works, btw).

**Comment by EbonJaeger** [comment]
> 
> 
>> `Which is Spigot for ya. `
> 
> ?? I do not understand your question sorry.

Was a statement, not a question. The people over at Spigot love changing things randomly.

**Comment by dumptruckman** [comment]
Alright, some background here. When MC added the selector stuff for commands, they intended it to be only for vanilla commands. However, it ended up that you were able to use it with some other commands via command blocks. As of 1.13, Mojang redid the command framework and this time made it so those selectors only work for vanilla commands. As of yet, Spigot has not added any way for people to apply it to custom commands. As it would be a pretty large undertaking, I doubt we will be adding this feature ourselves.

You're basically left with two options, don't upgrade to 1.13, or use the plugins that @SlimeDog has recommended.

**Comment by SlimeDog** [comment]
As of 27 minutes ago, Spigot now contains an @ selector API, complements of md_5.
https://hub.spigotmc.org/jira/browse/SPIGOT-4193

**Comment by dumptruckman** [comment]
LOL. Apparently all I had to do was bring this up in IRC.

**Comment by SlimeDog** [comment]
Good on you. :)

@Geant200 So we're on the path to it working as you wanted.

**Comment by Geant200** [comment]
Bonjour,

@EbonJaeger I understand 

@dumptruckman I will test it's recommendation.

@SlimeDog an update of Spigot 1.13.2 ?.

**Comment by SlimeDog** [comment]
WHEN dumptruckman announces an update that includes selectors, it will require that you build and install an update for Spigot (one assumes that you know how to build Spigot).

**Comment by Geant200** [comment]
If it is replace spigot.jar yes but if it is recompile Spigot no.

**Comment by SlimeDog** [comment]
Technically, you are not allowed to "replace" spigot.jar. You have to build it with [BuildTools](https://hub.spigotmc.org/jenkins/job/BuildTools/).

**Comment by Geant200** [comment]
I will see that

**Comment by Geant200** [comment]
I followed the documentation of BuildTools for version 1.13.2.

The doc 
https://www.spigotmc.org/wiki/buildtools/#windows

I redid tests with the command block for portals not walk.

**Comment by SlimeDog** [comment]
WHEN dumptruckman announces an update for Multiverse-Core ...

**Comment by MrSpock78** [comment]
In the meantime this might help?
https://www.spigotmc.org/resources/psudocommands-add-the-target-selector-to-plugin-commands.56738/

**Comment by Geant200** [comment]
@MrSpock78 I tested and it does not work.

**Comment by MrSpock78** [comment]
What is your command?

**Comment by MrSpock78** [comment]
Did you read the discription of the plugin?
Should be something like "/psudo mv tp ..."

**Comment by Geant200** [comment]
Always not

I have test 1
/psudo TheBelzebuth mv tp @p[distance=..2] e: redstone_guide: -4,102,7

I have test 2
/TheBelzebuth mv tp @p[distance=..2] e: redstone_guide: -4,102,7

**Comment by MrSpock78** [comment]
/Psudo <command>: -Issues the command as the sender
    /PsudoAs <sender> <command> - Issues the command as the sender specified.

So either "/psudo mv tp..."
or "/psudoas TheBelzebuth mv tp.."

**Comment by nicegamer7** [comment]
Reopening this very old issue since we'd like this feature to make it to MV. For anyone who is still interested, there is a test build of MV on our Discord server with this functionality.
