### ISSUE TITLE
Multiverse not keeping worlds in memory and not autoloading properly in config and commands after a restart (or two)

### ISSUE THREAD

**Issue by axemwa** [Multiverse/Multiverse-Core#1962]
When trying to set "keepSpawnInMemory" to true via worlds config and restarting server it doesn't apply cause I go to check the worlds with "/gc" command and the spawn chunks arent staying loaded as set in worlds config,
however using the "/mvm set memory true" command does apply and keeps the spawn chunk loaded at least until the server restarts, then it shows that it isn't loaded anymore.
Can u plz fix this if it's not working as intended?

The same thing was happening with autoLoad. Even though it's set to true in config, it doesn't acutally apply until you type the actual command /mvm set autoload true. After doing all that and restarting the server things are working properly but this might need to be fixed cause this means that the config settings for "autoload" and "keepSpawnInMemory" do nothing and only the commands can apply them?

Although after a second restart the autoload command didn't seem to stay in effect cause the world I chose so auto load and stay loaded with the commands wasn't loaded when I went to check with "/gc" after the second restart

I also suggest adding an option where you can set the "keepSpawnInMemory"s' radius for each world 

These issues were originally posted here on the 1.13 multiverse - https://www.spigotmc.org/threads/multiverse-core-1-13-support.354763/page-3#post-3296893

Version Info: 

[08:41:32 INFO]: Multiverse-Core version 2.7.0-SNAPSHOT-b748
[08:41:32 INFO]: Website: https://dev.bukkit.org/projects/multiverse-core
[08:41:32 INFO]: Authors: Rigby, fernferret, lithium3141, main-- and dumptruckman
[08:41:32 INFO]: Multiverse-Portals version 2.5.2-SNAPSHOT-b774
[08:41:32 INFO]: Authors: Rigby and fernferret
[08:41:32 INFO]: Multiverse-SignPortals version 2.5.2-SNAPSHOT-b723
[08:41:32 INFO]: Authors: Rigby and fernferret
[08:41:32 INFO]: Multiverse-NetherPortals version 2.5.2-SNAPSHOT-b736
[08:41:32 INFO]: Authors: Rigby and fernferret

**Comment by dumptruckman** [comment]
First of all, we always recommend _only_ changing the settings using the commands. Altering the configs by hand may lead to problems like you experienced.
As for those two options, unfortunately they are a little misleading. `autoload` just means that that world will be loaded without having to manually type `/mv load worldname`. `keepSpawnInMemory` does not load the spawn chunks itself, instead it just tells the server to not _unload_ them once they are loaded. It may be possible to force the chunks to load but I'm not familiar with how we could do that. I'll keep it in mind for future updates.

**Comment by axemwa** [comment]
ok thankyou, my mistake :)
