### ISSUE TITLE
Worlds open at specific times

### ISSUE THREAD

**Issue by MrBuzzzz** [Multiverse/Multiverse-Core#1963]
Is it possible to have specific worlds closed and opened at specific times for set periods. For example I want to have a minigames world open between 4pm and 8pm daily and all my other MV worlds open all the time.

**Comment by dumptruckman** [comment]
Yeah. You could do this with another plugin I imagine. Basically you need something that could change people's permissions on a schedule. I'm afraid this is a too specific thing for us to include in Multiverse though.
