### ISSUE TITLE
Teleporting issues

### ISSUE THREAD

**Issue by Castiella** [Multiverse/Multiverse-Core#1964]
Hi!

I'm a bit late reporting this issue as i thought the plugin was abandoned!

Basically, this is happening:

hub is in the world "Hub" and Spawn is in the world "Spawn"

Player: (In Spawn world)  /warp hub
>Player gets teleported to the hub world, but rather to the last place they stood in that world instead of the specific warp.

This also happens with teleporting home into another world ect.

Here is the server log for reference:
[latest.log](https://github.com/Multiverse/Multiverse-Core/files/2821167/latest.log)

Thank you!

**Comment by Castiella** [comment]
resolved, wron build used

**Comment by Castiella** [comment]
Actually my bad, its still happening

**Comment by Castiella** [comment]
We are using 2.7.0

**Comment by dumptruckman** [comment]
This could be many things and none of them are Multiverse-Core. You should ask for support on the plugin that provides the `/warp` command. You could also look through your list of plugins and see if any of them could be related and trying to disable them until it works again.
