### ISSUE TITLE
Worlds keep loading even after being deleted from both worlds.yml and the server files

### ISSUE THREAD

**Issue by GodGMN** [Multiverse/Multiverse-Core#1973]
Hello. I've tried to delete multiple times some of my worlds that I used for testing purposes. I tried some things: 

- Using /mv delete command to delete worlds (it did delete them all without any error)
- Unloading them and just keeping them unloaded (I don't want them to be loaded on startup)
- Turning off the server, editing worlds.yml to delete those worlds, delete the worlds from server files (the world folder)

All of these things lead to the same result: whenever I restart the server, the worlds get created and loaded again. Also, I edited the worlds config file to edit some things, like the names of the worlds in the chat prefix, their color and animals/monster spawns. This worked, but I also changed difficulties and weather, and again, whenever I restart my server, difficulty changes to hard and weather gets activated again, with no one touching it.

I have Multiverse-Core and Multiverse-Portals. Portals seem to work fine.

**Comment by jaylawl** [comment]
what are the names of those worlds? do they happen to be x_nether and x_the_end? because those get generated automatically by minecraft, not by mv

**Comment by Jadiction** [comment]
As jaylawl said, if your server.properies is assigned to a world for the default map, then it will generate _nether and _the_end. As for your configurations not saving, your server must be off while making changes to the config file as restarting the server reloads/overwrites the configuration file. You could always refer to the commands as well, as those will likely be more successful.
