### ISSUE TITLE
MV Script question

### ISSUE THREAD

**Issue by ReaperCrewGreen** [Multiverse/Multiverse-Core#1974]
Hello,
I am just wondering if there are any tutorials on how to use the mv script feature. and if not could you inform me on how it works?

**Comment by dumptruckman** [comment]
Unfortunately due to changes coming in Java the script feature may be removed from the plugin. :( I may look at replacing it with hooks for something else like skript or denizens.

**Comment by ReaperCrewGreen** [comment]
That is unfortunate. What changes to java are causing this? (just curious xD)

Is there a way to make it so that players can only mv tp to a different world and not the world they are currently in?

**Comment by dumptruckman** [comment]
I believe it is Java 12 that drops the Javascript engine that we are using.

**Comment by ReaperCrewGreen** [comment]
Gotcha, ok thanks for your help :)
