### ISSUE TITLE
teleporting between worlds with separate inventories

### ISSUE THREAD

**Issue by Castiella** [Multiverse/Multiverse-Core#1976]
teleporting between worlds with separate inventories causes the issues described here:

https://github.com/EssentialsX/Essentials/issues/2445

https://github.com/PaperMC/Paper/issues/1889.

This contradicts what you said here: https://github.com/Multiverse/Multiverse-Core/issues/1964

**Comment by Castiella** [comment]
(I'm using the recent dev build)

**Comment by 269Grimawewsome** [comment]
Most likely, another plugin is causing this. As I'm not a thread manager I may can help you out. may I have a full server log?

**Comment by Castiella** [comment]
As i have said, I have paid two system administrators to look at this, and take out every plugin but multiverse and essentials and it is still persisting.

It is an issue where when you teleport to a world with a separate inventory, you get teleported to your last location in the world rather than the place you warp.

the only resolution i have found to this, is switching to another plugin such as per-world inventories, which i dont want to do.

**Comment by dumptruckman** [comment]
You initially opened #1964 on the Multiverse-Core issues page and you did not mention *anything* about inventories. The log you included also did not include the startup logging which would tell me which plugins you had installed. Now, you've open *another* ticket on Multiverse-Core and only hint about some kind of relation to inventories. Looking at the log you left on https://github.com/EssentialsX/Essentials/issues/2445 I can see you have Multiverse-Inventories installed.

Now, Multiverse-Inventories *does* have a feature that could cause the problem you're talking about. It also has its own [issue tracker](https://github.com/Multiverse/Multiverse-Inventories/issues) and [wiki](https://github.com/Multiverse/Multiverse-Inventories/wiki). The `last_location` sharable is **optional** and must be manually enabled before it does anything. As far as I can tell, there's nothing in game or in the config files to even indicate this is a feature. This means you must have [read about it](https://github.com/Multiverse/Multiverse-Inventories/wiki/Big-List-O-Shares#last_location) before blindly turning it on.

I'm closing this ticket as it is *not* related to Multiverse-**Core**. If you think this is a bug in Multiverse-*Inventories*, please kindly open a ticket [there](https://github.com/Multiverse/Multiverse-Inventories/issues).
