### ISSUE TITLE
Worlds unloading after reload / server stop

### ISSUE THREAD

**Issue by 269Grimawewsome** [Multiverse/Multiverse-Core#1979]
**I've checked other threads, but nothing works.**
PLUGINS IM USING:
Multiverse Core 2.5.0
Multiverse Portals 2.50
Server Log: https://pastebin.com/raw/uKqWPVig
The issue started: After switching to spigot. 
Can I switch back to bukkit: No
Needed response out of 5: 5!!!

**Comment by 269Grimawewsome** [comment]
More issues:
21.03 15:03:58 [Server] WARN at java.util.regex.Pattern.error(Pattern.java:1957)
21.03 15:03:58 [Server] WARN at java.util.regex.Pattern.clazz(Pattern.java:2550)
21.03 15:03:58 [Server] WARN at java.util.regex.Pattern.sequence(Pattern.java:2065)
21.03 15:03:58 [Server] WARN at java.util.regex.Pattern.expr(Pattern.java:1998)
21.03 15:03:58 [Server] WARN at java.util.regex.Pattern.compile(Pattern.java:1698)
21.03 15:03:58 [Server] WARN at java.util.regex.Pattern.<init>(Pattern.java:1351)
21.03 15:03:58 [Server] WARN at java.util.regex.Pattern.compile(Pattern.java:1028)
21.03 15:03:58 [Server] WARN at java.util.regex.Pattern.matches(Pattern.java:1133)
21.03 15:03:58 [Server] WARN at java.lang.String.matches(String.java:2121)
21.03 15:03:58 [Server] WARN at com.onarandombox.MultiverseCore.commands.HelpCommand.getFilteredItems(HelpCommand.java:46)
21.03 15:03:58 [Server] WARN at com.onarandombox.MultiverseCore.commands.HelpCommand.runCommand(HelpCommand.java:79)
21.03 15:03:58 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
21.03 15:03:58 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
21.03 15:03:58 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
21.03 15:03:58 [Server] WARN at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:916)
21.03 15:03:58 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
21.03 15:03:58 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
21.03 15:03:58 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641)
21.03 15:03:58 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385)
21.03 15:03:58 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220)
21.03 15:03:58 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
21.03 15:03:58 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
21.03 15:03:58 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
21.03 15:03:58 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
21.03 15:03:58 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
21.03 15:03:58 [Server] WARN at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
21.03 15:03:58 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
21.03 15:03:58 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
21.03 15:03:58 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
21.03 15:03:58 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
21.03 15:03:58 [Server] WARN at java.lang.Thread.run(Thread.java:748)
21.03 15:03:59 [Server] INFO TheGrim issued server command: /mv hel[p
21.03 15:03:59 [Server] WARN java.util.regex.PatternSyntaxException: Unclosed character class near index 12
21.03 15:03:59 [Server] INFO ().*hel[p.*
21.03 15:03:59 [Server] INFO ^
21.03 15:03:59 [Server] WARN at java.util.regex.Pattern.error(Pattern.java:1957)
21.03 15:03:59 [Server] WARN at java.util.regex.Pattern.clazz(Pattern.java:2550)
21.03 15:03:59 [Server] WARN at java.util.regex.Pattern.sequence(Pattern.java:2065)
21.03 15:03:59 [Server] WARN at java.util.regex.Pattern.expr(Pattern.java:1998)
21.03 15:03:59 [Server] WARN at java.util.regex.Pattern.compile(Pattern.java:1698)
21.03 15:03:59 [Server] WARN at java.util.regex.Pattern.<init>(Pattern.java:1351)
21.03 15:03:59 [Server] WARN at java.util.regex.Pattern.compile(Pattern.java:1028)
21.03 15:03:59 [Server] WARN at java.util.regex.Pattern.matches(Pattern.java:1133)
21.03 15:03:59 [Server] WARN at java.lang.String.matches(String.java:2121)
21.03 15:03:59 [Server] WARN at com.onarandombox.MultiverseCore.commands.HelpCommand.getFilteredItems(HelpCommand.java:46)
21.03 15:03:59 [Server] WARN at com.onarandombox.MultiverseCore.commands.HelpCommand.runCommand(HelpCommand.java:79)
21.03 15:03:59 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
21.03 15:03:59 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
21.03 15:03:59 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
21.03 15:03:59 [Server] WARN at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:916)
21.03 15:03:59 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
21.03 15:03:59 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
21.03 15:03:59 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641)
21.03 15:03:59 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385)
21.03 15:03:59 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220)
21.03 15:03:59 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
21.03 15:03:59 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
21.03 15:03:59 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
21.03 15:03:59 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
21.03 15:03:59 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
21.03 15:03:59 [Server] WARN at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
21.03 15:03:59 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
21.03 15:03:59 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
21.03 15:03:59 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
21.03 15:03:59 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
21.03 15:03:59 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by Jadiction** [comment]
Hi, can you post your config file?
Have you tried using Multiverse 3.0.0 (found on the bukkit resource page) and checking if the problem persists?
As for your other errors, notice you're typing **/mv hel[p** and not **/mv help**. Although, I will say it's weird that it runs into parsing issues when that command variation is used and it should return an unknown command instead.

**Comment by benwoo1110** [comment]
Closing this issue as mv 2.5.0 is outdated. If you still have any issue, do create a new issue or join our discord at https://discord.gg/NZtfKky
