### ISSUE TITLE
Problems with "/mvp import"

### ISSUE THREAD

**Issue by ktg5** [Multiverse/Multiverse-Core#1985]
Hello, when I do "/mv import (world_name)" I get this in my console...
`14.04 09:08:33 [Server] WARN java.lang.NullPointerException
14.04 09:08:33 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.saveWorldsConfig(WorldManager.java:822)
14.04 09:08:33 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:277)
14.04 09:08:33 [Server] WARN at com.onarandombox.MultiverseCore.commands.ImportCommand.runCommand(ImportCommand.java:152)
14.04 09:08:33 [Server] WARN at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
14.04 09:08:33 [Server] WARN at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143)
14.04 09:08:33 [Server] WARN at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
14.04 09:08:33 [Server] WARN at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:900)
14.04 09:08:33 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
14.04 09:08:33 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:138)
14.04 09:08:33 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:684)
14.04 09:08:33 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1585)
14.04 09:08:33 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1439)
14.04 09:08:33 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(SourceFile:37)
14.04 09:08:33 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(SourceFile:9)
14.04 09:08:33 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9)
14.04 09:08:33 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
14.04 09:08:33 [Server] WARN at java.util.concurrent.FutureTask.run(Unknown Source)
14.04 09:08:33 [Server] WARN at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
14.04 09:08:33 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:839)
14.04 09:08:33 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:382)
14.04 09:08:33 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:792)
14.04 09:08:33 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:695)
14.04 09:08:33 [Server] WARN at java.lang.Thread.run(Unknown Source)`
Anyone know how to fix this?
Also I do get info about the worlds, but still that error.

**Comment by ktg5** [comment]
Can I just get any info about my problem please? Like if there's something going on?

**Comment by Jadiction** [comment]
It's likely you were trying to import a world of a different version than your server version. Try using the singleplayer client to convert it first then try importing. Otherwise, it seems it's the world files are messed up.

**Comment by ktg5** [comment]
I'm not loading worlds from older versions, this was back in the day I used to use BeastNode's service. But now I just use my home server. And also, "...tells me to do '/mv import'. When I do it comes with a error and when I load into the world all my hard work is gone, back to the beginning," All the worlds I created were all created in "/mv create" command.
