### ISSUE TITLE
Support for spigot and 1.13.2 and the upcoming 1.14 minecraft versions

### ISSUE THREAD

**Issue by Klawdek** [Multiverse/Multiverse-Core#1988]
This plugin is still on bukkit and only specifies bukkit versions in the docs.  Also no mention anywhere as to what versions of minecraft are supported.  It would be nice to have support for the latest versions of minecraft and the versions supported should be listed somewhere.

**Comment by hamcoremusic** [comment]
You can use the latest dev build on 1.13.2!

**Comment by SlimeDog** [comment]
We've been using DEV builds on Spigot 1.13.2 without issues, for quite a while now. Fingers crossed for 1.14 update.

**Comment by ravkr** [comment]
It works fine on Spigot 1.14, I'm using it for the last two days.
Only problem I found is crash when doing two `/mv create`'s at the same time (but I don't know if it's an old bug, or something new)

**Comment by hamcoremusic** [comment]
Any issues with Multiverse inventories?

**Comment by SlimeDog** [comment]
MV-Core, MV-Inventories, MV-Portals, MV-NetherPortals all work fine on my Spigot 1.13.2. MV-Core and MV-Inventories seem to be fine on Spigot 1.14; MV-Portals does not load; MV-NetherPortals not tested (by me). Hopefully, there will be Spigot 1.14-specific updates soon.

**Comment by MonstahGames** [comment]
As @SlimeDog said, MV-Portals disables upon server startup
MV-NetherPortals makes the player disconnect. 
I'm running 3.0.0-SNAPSHOT (on all my mv plugins) on Spigot 1.14.
Provided is a log of the error when a player enters a portal.
https://pastebin.com/7SiUXGRB

**Comment by SlimeDog** [comment]
MV 3.0.0-SNAPSHOTs

Worlds seem to generate without error in 1.14, but as I use them, they crash the server on restart. Waiting patiently for upgrade to support 1.14.

**Comment by Valkyy** [comment]
One of the worlds in my server that I tried converting from 1.13.2 to 1.14 stopped at 99% and froze the server startup. I had to convert it in single player instead.

**Comment by SlimeDog** [comment]
It might be useful to open a ticket for that, if you can reproduce it.

**Comment by Jadiction** [comment]
Hi, please refer to https://github.com/Multiverse/Multiverse-Core/issues/1998 for 1.14.x updates. You may also get announcements from the Multiverse Discord at https://discord.gg/NZtfKky

**Comment by SlimeDog** [comment]
Some of us are DisCord-cutters. I guess we will wait for news to drift out of the clouds.
