### ISSUE TITLE
Multiverse-Core server login

### ISSUE THREAD

**Issue by DiamondLogic** [Multiverse/Multiverse-Core#1991]
Hi when I login into my server and the world that I left when I rejoin the server it puts me back at the spawn that I logged off at but in a different part of the world and cannot get back to my base because of the server trying to force me to respawn back at the spawn before, please help i have the latest version of multiverse-core bukkit, please help it's getting annoying with the respawning at the world spawn, when I logged off in a completely different place, however, I don't have the bukit.yml file

**Comment by ray040417** [comment]
There is a helpful plugin called Lastlocation
I am using it on my server and it puts you back to the last location you were on before logging of/world changing

**Comment by DiamondLogic** [comment]
> There is a helpful plugin called Lastlocation
> I am using it on my server and it puts you back to the last location you were on before logging of/world changing

Does that work with multiverse

**Comment by DiamondLogic** [comment]
Its got to be a plugin available for aternos
