### ISSUE TITLE
[1.14] Converting certain world freezes server startup.

### ISSUE THREAD

**Issue by Valkyy** [Multiverse/Multiverse-Core#1992]
I'm using multiverse 3.0.0 beta, and I just upgraded my server to 1.14. I had trouble converting one specific world from 1.13.2 to 1.14 (maybe because of the size? It's a very large world, but there's been no trouble converting it in the past). The world load just gets stuck anywhere from 90-100%; it never finishes loading and freezes the server startup. So, I have to manually close out of the server. I tried going into single player and converting it that way, but loading the world in the server, it didn't work.

**Comment by Phoenix616** [comment]
This is most likely not an issue with Multiverse but with Minecraft/CraftBukkit itself. I suggest waiting for at least 1.14.1 and non-dev builds of the server before attempting to convert any production worlds.

**Comment by Jadiction** [comment]
Agreed with Phoenix616. An option is to convert your worlds on singleplayer (or local), then move them over for the server.
