### ISSUE TITLE
/mv command is not recognized.

### ISSUE THREAD

**Issue by xHyperSource** [Multiverse/Multiverse-Core#1993]
Hello everyone,

So, yesterday I installed Multiverse-Core on my server. It worked fine, and I got to import all my worlds successfully. When I restarted my server, I tried typing in `/mv` in chat, but it would say `Unknown command. Type /help for help.` like I never installed it! When I type `/plugins` I can see multiverse enabled. Can someone please help me?

Thank you,
xHyperSource.

**Comment by Jadiction** [comment]
Hi, which Multiverse version? Can you try /mv in console? Perhaps you don't have permissions. While loading up, check to see what Multiverse says (does it say it failed to start up and was disabled?).

**Comment by Jadiction** [comment]
Closing ticket due to lack of information. Please open a new ticket with more valid information if this issue is still occurring in the latest versions or for a faster response, you can also receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).

**Comment by Neweko** [comment]
Jadiction Help me
