### ISSUE TITLE
"/mv import" doesn't save lists and resets worlds.

### ISSUE THREAD

**Issue by ktg5** [Multiverse/Multiverse-Core#1994]
Hello,
When I want to tp to one of my worlds on my server, it says that it doesn't know any info about it and tells me to do "/mv import". When I do it comes with a error and when I load into the world all my hard work is gone, back to the beginning,

I've had it up to the highest amount and me and my friends can't deal with this. 

If there's some build to fix this issue, please tell me or I'm just not going run my server and go back to shitty realms.

-ktg5.

Using Craftbukkit 1.13.2 w/ latest version.

**Comment by Jadiction** [comment]
Duplicate issue of https://github.com/Multiverse/Multiverse-Core/issues/1985
