### ISSUE TITLE
Only load Worlds with lowercase and Slow charge

### ISSUE THREAD

**Issue by andfont** [Multiverse/Multiverse-Core#1999]
My Server MC-Spigot 1.14.1
Version Plugin: Multiverse-Core version 3.0.0-SNAPSHOT-b761
Error net.minecraft.server.v1_14_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:MundoABF
MORE INFO ERROR:
https://pastebin.com/gYWkP8DP
PLEASE!!
It is also very slow to load the worlds is always doing 4:56:15] [Server-Worker-5 / INFO]: Preparing spawn area: 0% etc ... it's too bad to fix these problems please! they only pass in 1.14 not in 1.13 thanks

**Comment by Phoenix616** [comment]
Non-lowercase worlds are currently not supported See. [SPIGOT-4925](https://hub.spigotmc.org/jira/browse/SPIGOT-4925) for discussions about potential solutions for that. If you need a fix now rename the worlds.

**Comment by andfont** [comment]
really? this is a big problem I have many plugins configurations and database data that are linked with these worlds with uppercase and lowercase names that it is almost impossible to solve! if not eliminate thousands of user data! this is a big problem! I can not believe that spigot has that problem :( please some solution that is not to force to change the worlds with lowercase since many complements stop working etc. thanks: (((((

**Comment by Diamondman121314** [comment]
This is no longer an issue as it was fixed with [this commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/de9b85b8a1e5f24b6607697255b3b762fd9d24d2). It's also in Paper as of build #35, but doesn't function unless using at least #37.
