### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by ReAperr01** [Multiverse/Multiverse-Core#2002]
Hi,
Ok so i installed Maven : 

```
> C:\Users\reape>mvn -version
> Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
> Maven home: C:\apache-maven-3.6.1\bin\..
> Java version: 12, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-12
> Default locale: fr_FR, platform encoding: Cp1252
> OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

i think i did everything well but build is not passing:

```
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  13.165 s
> [INFO] Finished at: 2019-05-23T10:39:26+02:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal se.eris:notnull-instrumenter-maven-plugin:0.6.8:instrument (default) on project Multiverse-Core: Execution default of goal se.eris:notnull-instrumenter-maven-plugin:0.6.8:instrument failed: NotNull instrumentation failed for C:\Users\reape\Multiverse-Core\target\classes\com\onarandombox\MultiverseCore\utils\SimpleWorldPurger.class: java.lang.IllegalArgumentException: Unsupported class file major version 56 -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by mwof-obdurate** [comment]
I received a very similar error while building. I'm unsure what exactly I should do next.

> C:\Users\Josh\Desktop\Multiverse-Core>mvn -v
> Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T15:00:29-04:00)
> Maven home: E:\Downloads\apache-maven-3.6.1\bin\..
> Java version: 12.0.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-12.0.1
> Default locale: en_US, platform encoding: Cp1252
> OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  6.852 s
> [INFO] Finished at: 2019-06-07T00:18:55-04:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal se.eris:notnull-instrumenter-maven-plugin:0.6.8:instrument (default) on project Multiverse-Core: Execution default of goal se.eris:notnull-instrumenter-maven-plugin:0.6.8:instrument failed: NotNull instrumentation failed for C:\Users\Josh\Desktop\Multiverse-Core\target\classes\com\onarandombox\MultiverseCore\commands\InfoCommand.class: java.lang.IllegalArgumentException: Unsupported class file major version 56 -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by sethwalker1** [comment]
Sorry for reviving this issue, but I have the same problem. I believe the issue is my maven or java version.

**Comment by mwof-obdurate** [comment]
> Sorry for reviving this issue, but I have the same problem. I believe the issue is my maven or java version.

I was having this issue and I just gave up and downloaded the pre-built .jar from their [Jenkins](https://ci.onarandombox.com/job/Multiverse-Core/). I know it's not a solution but I didn't need to build it on my own.

**Comment by sethwalker1** [comment]
I can confirm the issue is being caused by an unsupported version of Java, specifically Java 12. I'm looking further into this right now.
