### ISSUE TITLE
multiverse when creating a world the server crashes, and it gets corrupted

### ISSUE THREAD

**Issue by panleo21** [Multiverse/Multiverse-Core#2005]
/mv create paradise normal -g ParadiseLand:Eden​  < the command i use
plugins i have: mutliverse core, paradiseland
what happend:
I did the command , says in console creating 1% 4 % and so on until it stays on 65%-97%
and then the server crashes, restarting the server after the crash, trying to /mvtp paradise
wont work says unloaded, but i can also do /mv import paradise i did that , and then I noticed the screnshoots, 
im using server.pro as a hosting , on 2 gigabyte and 3+ hz , version 1.13.2

screenshoots of the new world that was created: 
![2019-05-31_18 28 31](https://user-images.githubusercontent.com/51241927/58720277-00205300-83d2-11e9-800b-a853369be9cb.png)
![2019-05-31_18 28 35](https://user-images.githubusercontent.com/51241927/58720282-01518000-83d2-11e9-9c97-f56292b8200d.png)

**Comment by iamceph** [comment]
I can confirm this as using VoidWorld, server crashes. This is the cause: java.lang.UnsupportedOperationException: Custom generator is missing required method generateChunkData.

Crash: https://hastebin.com/iyixasupag.rb

**Comment by HexedHero** [comment]
I use this same plugin on 1.14.2 and can confirm this DOESN'T happen.

Might be a 1.13 issue.
