### ISSUE TITLE
Import world

### ISSUE THREAD

**Issue by Misio12320** [Multiverse/Multiverse-Core#2010]
Hello. I get a lot of console spam when I execute command to import a world. https://pastebin.com/e2y80gKG. And while generating new world with custom generator the server just crash. 
 This server is running Paper version git-Paper-65 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
[20:48:52 INFO]: Checking version, please wait...
[20:48:52 WARN]: Can't keep up! Is the server overloaded? Running 50313ms or 1006 ticks behind
[20:48:52 INFO]: Previous version: git-Paper-58 (MC: 1.14.2)
[20:48:52 INFO]: You are running the latest version

**Comment by Misio12320** [comment]
the server does not crash but with the custom -g the server just freezes at 100%

**Comment by Misio12320** [comment]
also the performance is DEATH with view distance more than 5.  [Multiverse-Core] "Multiverse-Core v4.0.0-SNAPSHOT-b763" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].
1.14.2 I have setup view distance to 32 and I can't join the server but on default world it works. java -Xms128M -Xmx33000M -jar paper-66.jar --forceUpgrade --eraseCache

**Comment by sorienrot** [comment]
Test without capital letters. Rename the world folder.

mv import SwiatDrop normal >>> mv import swiatdrop normal

**Comment by dumptruckman** [comment]
We have no control over whether or not custom generators work or the performance of worlds with or without custom generators. Seek help from the developers of the custom generator.

**Comment by Phoenix616** [comment]
> Test without capital letters. Rename the world folder.
> 
> mv import SwiatDrop normal >>> mv import swiatdrop normal

Not necessary. Any world name case is supported.
