### ISSUE TITLE
[paper-64+] Chat no longer works and throws exception in 4.0.0-snapshot

### ISSUE THREAD

**Issue by DXUltimate** [Multiverse/Multiverse-Core#2011]
So, whenever someone tries to use the regular chat in the game, this exception is thrown and spammed in console, while not sending the chat messages.

https://pastebin.com/zPZZCCa6

Please note this only happens in paper versions 64 and newer, and it happens with both 3.0.0 and 4.0.0. This async event event happens in older versions of paper as well, but the chat still works.

**Comment by Jadiction** [comment]
Hm, I don't have this with the latest version and I'm currently using the very latest version of paper right now. I suppose plugin conflict is not possible in this case? Can you try?

**Comment by DXUltimate** [comment]
Yep.

So from what I got so far, the only plugins I could think that would be causing these issues could be viaversion, essentials, quickshop, cmi and luckperms (which is my permissions plugin). I've disabled all of them and it seems the chat is still not working, throwing the same exception.

Version of paper I am using is paper-68 to test these with, and I've redownloaded it just to make sure, but it's the same issue.

Here is the console dump from the command.
https://puu.sh/DD701/7a718c7425.png

**Comment by Jadiction** [comment]
It seems likely to be a config issue? Seeing as how I don't have the error. Maybe Pastebin your config as well.

**Comment by DXUltimate** [comment]
Okay, here it is.

https://pastebin.com/1tzpChXb

**Comment by Jadiction** [comment]
_prefixchatformat: '%chat'_ should be _prefixchatformat: '%chat%'_
Let me know if it fixes your issue.

**Comment by DXUltimate** [comment]
Alright, that actually fixed the issue. I'm not sure how a simple thing managed to completely wipe out chat, but, it works now. Thank you!
