### ISSUE TITLE
Chat Prefix doesn't work anymore in 4.0.0

### ISSUE THREAD

**Issue by xhatz** [Multiverse/Multiverse-Core#2012]
Hello! I'm using Paper 68.

Basically, when prefixchat is set to true, it doesn't add anything to the chat syntax. Otherwise I'm having no problems at all!

FIND: the prefix **does** show in the console, though!

Thank you!

**Comment by xhatz** [comment]
EDIT: After I rebooted, it came back for some reason... I really have no idea what I did to fix it tho xD

**Comment by Jadiction** [comment]
Self-solved.
