### ISSUE TITLE
Error on startup(server version 1.14.2)

### ISSUE THREAD

**Issue by Pabi7** [Multiverse/Multiverse-Core#2013]
This error was thrown when I started my server: http://pasted.co/aedebd15

I am using the #764(dev build)

Just trying to help and get this issue resolved. Please let me know what other information you need. 

Thanks!

**Comment by DXUltimate** [comment]
They're already aware of this since this has been posted in issue #2000 =3

**Comment by Jadiction** [comment]
Duplicate of https://github.com/Multiverse/Multiverse-Core/issues/2000
