### ISSUE TITLE
Unable to change gamemode to Adventure... Always keeps survival mode...

### ISSUE THREAD

**Issue by RasmonT** [Multiverse/Multiverse-Core#2014]
I'm unable to change gamemode.. even when i restart server or reload the plugin the mode never changes! It's always stays Survival...

       worlds:
    BedWarsLobby:
    ==: MVWorld
    hidden: 'false'
    alias: BedWarsLobby
    color: WHITE
    style: NORMAL
    pvp: 'false'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'false'
    difficulty: PEACEFUL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
      currency: '-1'
    hunger: 'false'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: ADVENTURE
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 5008.0
      y: 122.0
      z: 5033.0
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '0'
    generator: 'null'
    playerLimit: '-1'
    allowFlight: 'true'

Any suggestions ? I will need the plugin for setting up maps and other servers for minigames.... (Need adventure mode on each world)

**Comment by RasmonT** [comment]
EDIT:

When i made myself as a player (not owner with -*- permissions) i was setted up in adventure mode, is there possibility to disable the bypass permission for OPS/Owners ?

**Comment by Jadiction** [comment]
You can try negating the bypass permission.

_- -mv.bypass.gamemode.*_

I've never tried this myself while having the wildcard "*" as a permission, so I'm not sure if the negate works or not.

If it doesn't work, I'd suggest just going through your plugins and giving you all permissions individually. (Note that some plugins use several differently named permission nodes if you do this)
For example, if you had essentials and backup:
- essentials.*
- backup.*

**Comment by Jadiction** [comment]
Going to assume this is solved - closing the ticket. If you're still having issues, please don't hesitate to make another ticket or for a faster response, you can also receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
