### ISSUE TITLE
Minecraft 1.14.2 MV Core Issue.

### ISSUE THREAD

**Issue by Merlet30** [Multiverse/Multiverse-Core#2017]
[Server thread/WARN]: [Multiverse-Core] "Multiverse-Core v4.0.0-SNAPSHOT-b764" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

Upon loading my server I'm getting this problem, and it is causing quite a bit of server lag.  What could be the fix?  I got the download from Jenkins.  
https://ci.onarandombox.com/job/Multiverse-Core/764/

**Comment by Jadiction** [comment]
Duplicate issue of https://github.com/Multiverse/Multiverse-Core/issues/2000
