### ISSUE TITLE
Can't load a world

### ISSUE THREAD

**Issue by TobyRT** [Multiverse/Multiverse-Core#2021]
Tried adding a world onto my server and it came up with

18.06 15:10:35 [Server] ERROR [Multiverse-Core] The world 'Alternate' could NOT be loaded because the server didn't like it!
18.06 15:10:35 [Server] ERROR [Multiverse-Core] We don't really know why this is. Contact the developer of your server software!
18.06 15:10:35 [Server] ERROR [Multiverse-Core] Server version info: git-Spigot-1a3504a-dfa7583 (MC: 1.13.2)
18.06 15:10:35 [Server] ERROR [Multiverse-Core] Failed to Create/Load the world 'Alternate'

Contacted my server provider and they said to contact you

**Comment by Jadiction** [comment]
Is the world version the same as the server? Can you provide the output link from `/mv version -b`?

**Comment by Jadiction** [comment]
Closing ticket. It's recommended that for support, you can get faster response on the [Multiverse Discord](https://discord.gg/NZtfKky).
