### ISSUE TITLE
World names more restricted with 1.14.2

### ISSUE THREAD

**Issue by doncaruana** [Multiverse/Multiverse-Core#2022]
With 4.0.0 b765, world names are more restrictive with 1.14.2. The same worlds (a couple with a space, one with an equal and one with a space and a comma) load fine with 1.13.2. With 1.14.2, they won't load because there is an illegal character in the path.

**Comment by Jadiction** [comment]
I may be wrong, but I believe I heard Minecraft is enforcing single word lower case world names, just Spigot allows it by changing the world directories to lowercase. Someone may correct me if I'm wrong.

**Comment by doncaruana** [comment]
Looks like you're correct...
https://hub.spigotmc.org/jira/browse/SPIGOT-4925

Says resolved, but not exactly what that's supposed to mean as I don't see any code changes for it anywhere.

**Comment by Jadiction** [comment]
If you don't have many plugins associated with world names, you can simply just change the world directory to the upcoming world name standards.
Or even if the plugins are formatted in something simple like YML/JSON, you can go into their config and rename your worlds to the new name to keep the information.

**Comment by doncaruana** [comment]
I don't have anything outside of multiverse dependent on the names so I decided to alias the worlds (to their "current" name and then edit , then go edit all the multiverse yml files to match the renamed folders. I did a trial run on one of the worlds and it seemed to work fine. A little work now and it's behind me. Thanks for the suggestion!

**Comment by Jadiction** [comment]
Yep! Multiverse's alias feature is perfect for this case. Instead of "world_nether", it can be referenced as "Survival (Nether)" or something of the sorts. 
It's as if they knew years ago this naming convention would be standardized.
Glad I could help.
