### ISSUE TITLE
probleme grass

### ISSUE THREAD

**Issue by acrospate** [Multiverse/Multiverse-Core#2024]
Hello, since the installation of multiverse on server 1.14.2, the block of grass does not push anymore. / gamerule properly set and not change before installing multivers.

**Comment by Jadiction** [comment]
What do you mean the grass block doesn't push anymore? Like from pistons? `/gamerule` mostly works fine for multi-worlds.

**Comment by Jadiction** [comment]
Closing ticket due to lack of information. Please open a new ticket with more valid information if this issue is still occurring in the latest versions or for a faster response, you can also receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
