### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Natecurt3030** [Multiverse/Multiverse-Core#2025]
I'm using Paper Spitgot (latest) version 1.14.2 and the latest dev builds of Multi-verse Core (#765) and Portals (#797). I occasionally receive an internal server error when entering portals made with Multi-verse Portals. The error I receive reads as follows:

19.06 21:57:54 [Server] WARN [Multiverse-Core] TravelAgent not available for PlayerPortalEvent for Username
19.06 21:57:54 [Server] WARN [Multiverse-Core] TravelAgent not available for PlayerPortalEvent for Username
19.06 21:57:54 [Server] WARN Failed to handle packet for IP Address
19.06 21:57:54 [Server] INFO net.minecraft.server.v1_14_R1.ReportedException: Colliding entity with block
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:500) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.tick(PlayerConnection.java:146) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:259) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1216) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1061) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:905) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
19.06 21:57:54 [Server] INFO Caused by: java.lang.NullPointerException
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.PortalTravelAgent.a(PortalTravelAgent.java:33) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.EntityPlayer.a(EntityPlayer.java:925) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.BlockEnderPortal.a(BlockEnderPortal.java:34) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.IBlockData.a(IBlockData.java:209) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.Entity.checkBlockCollisions(Entity.java:912) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.Entity.move(Entity.java:658) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.EntityLiving.e(EntityLiving.java:2202) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.EntityHuman.e(EntityHuman.java:1480) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2553) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.EntityHuman.movementTick(EntityHuman.java:401) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2315) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:150) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:418) ~[patched_1.14.2.jar:git-Paper-81]
19.06 21:57:54 [Server] INFO ... 8 more
19.06 21:57:54 [Disconnect] User Username has disconnected, reason: Internal server error

**Comment by Jadiction** [comment]
Hm, I don't have this when using Multiverse-Portals made portals. According to your stack trace, your Paper version `Paper-81` isn't the latest. Currently (as of 6/19/19) it's [97](https://papermc.io/downloads). Do you have any plugins that could conflict? Can you provide the link from `/mv version -b`.

**Comment by Natecurt3030** [comment]
Hi!

Sorry for the late response. I have updated to the latest paper spigot version as of this post (6/24/19 version 107) and still receive the same error. Here is the link generated by the command you mentioned: https://j.mp/2J2WDox. I don't believe any of my plugins should be interfering but are there any specific plugins you know of which have been causing issue? I don't have any other multi-world related plugins. I can provide you a list of the ones I use if that would be of any use.

Thank you!

**Comment by Jadiction** [comment]
Can you try loading the server with just Multiverse-Core and Multiverse-Portals and see if the issue persists?

**Comment by Jadiction** [comment]
Closing ticket due to lack of information. Please open a new ticket with more valid information if this issue is still occurring in the latest versions or for a faster response, you can also receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
