### ISSUE TITLE
Update MV to not use EntityCreatePortalEvent as it is deprecated for performance reasons

### ISSUE THREAD

**Issue by Ve6om** [Multiverse/Multiverse-Core#2027]
26.06 00:13:57 [Server] Server thread/INFO Enabling Multiverse-Core v4.0.0-b766
26.06 00:13:57 [Server] Server thread/WARN "Multiverse-Core v4.0.0-b766" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by Jadiction** [comment]
Duplicate issue of https://github.com/Multiverse/Multiverse-Core/issues/2000
