### ISSUE TITLE
"previous world is null"

### ISSUE THREAD

**Issue by NanoParticles** [Multiverse/Multiverse-Core#2028]
So, I got a command block setup(using command hook along side multiverse) and I'm not sure if its either command hook or multiverse. There's nothing generating in console log indicating a problem with multiverse or command hook. I get spammed in the chat "previous world is null" while stepping on a pressure plate that teleports a player to an existing world, but then it teleports me to that existing world upon stepping onto a different pressure plate. Is this normal?

**Comment by dumptruckman** [comment]
I'm going to need more information. What commands are the pressure plates running?

**Comment by NanoParticles** [comment]
It's only running:
/mvtp @p lobby

Command hook adds support to for the @p

**Comment by dumptruckman** [comment]
The message you're getting isn't found anywhere within Multiverse-Core or Multiverse-Inventories. Those are the only Multiverse plugins that could possibly be relevant. My best guess is some other plugin is causing those messages.

**Comment by NanoParticles** [comment]
I don't know if this has to do with anything, but I just looked in the console, and I found something that was generated by Multiverse-Core.

"Multiverse-Core v4.0.0-b766 has a register a listener for org.bukkit.event.entity.EntyCreatePortalEvent on "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors." Then it lists the authors

**Comment by Jadiction** [comment]
As stated above, the error you're having isn't Multiverse related. As for the deprecated warning, Multiverse is aware of the deprecated event that you're informed about in console. The "performance impact" isn't noticeable and is fine to ignore.

Closing ticket. Please open a new ticket if you're having issues with Multiverse or for a faster response, you can also receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).

**Comment by dumptruckman** [comment]
@NanoParticles looks like it is LobbyAPI that causes this message.

**Comment by matthieuxyz** [comment]
Got here from google, and eventually found out that it is indeed from LobbyAPI:

Error line: https://github.com/ZombieStriker/LobbyAPI/blob/4f849fd65ffd3f410f0a3ed18a2345c177e6fac2/src/me/zombie_striker/lobbyapi/Main.java#L433

Reported issue:
https://github.com/ZombieStriker/LobbyAPI/issues/7
