### ISSUE TITLE
Chunks load out of control

### ISSUE THREAD

**Issue by FatherWh0** [Multiverse/Multiverse-Core#2029]
I updated one of my servers to 1.14.3. Ever since it's had an issue where one world will start loading chunks. It keeps loading until it overloads the server and the watchdog shuts it down.  It doesn't happen with the three vanilla worlds. It happens with a world that's been visited by a player. Leaving that world doesn't stop the chunks from continuing to load.

paper 1.14.3 build 114
Multiverse-Core 4.0.0 (tried official release and jenkins build # 766

 Plugins (74):
 Arconix*, AreaShop, ArmorStandEditor, AsyncWorldEdit, AutoMessage*, BottledExp, ChatFeelings, ChestShop, ClearChat*, ClearLag, CoreProtect, CraftBook, CurrencyDrops*, CustomVanillaVillagers, DeathMessages*, DecoHeads*, DriveBackup*, dynmap*, Dynmap-Essentials*, Dynmap-WorldGuard*, EpicRename, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, ezAuctions, FlashyTP*, FlyWorld*, icJukeBox*, ImageOnMap*, LegacyPvP*, LibsDisguises, LWC, MarriageMaster, mcMMO, Minigames, Minigames-Regions, MobArena, MoreVanillaMobs*, Multiverse-Core, Multiverse-NetherPortals, MyPet, NoChorusFruitTP*, NoSpawnerChange, PermissionsEx*, PerWorldInventory, PlaceholderAPI*, PlayerParticles, PlotSquared, PlugMan, PokeStaff*, ProtocolLib*, RandomTeleport, RedstoneClockDetector*, Shopkeepers, SnowballDamage*, Stables*, SuperbVote, SuperTrails*, UltimateTimber, Vault, ViaVersion*, VillageInfo*, VoidGenerator, Votifier*, WDLCompanion*, WhatIsIt, WorldBorder*, WorldEdit, WorldEditCUI, WorldGuard, WorldGuardExtraFlags, WorldSchematics2, XrayInformer*

**Comment by Jadiction** [comment]
This isn't Multiverse as it doesn't mess with chunk loading. It's possible it's a 1.14.3 bug or another plugin. Closing issue. If you're positive that Multiverse is causing an issue, please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue with an indication that it's Multiverse.
