### ISSUE TITLE
Players get in spawn whenever log in server

### ISSUE THREAD

**Issue by sixamscrew** [Multiverse/Multiverse-Core#2030]
Hello, I have authme, when a player logs in server, after the /login, instead of being teleported to their last location, they always (including me) get in the mv spawn! I already tried changing enforceaccess to false, changing the adjustspawn in world to true or false, nothing. Players always in spawn at join, and I don't want it, If I disable the plugin, they get in their last location places but... I need this plugin for having multiple worlds :( This started to happen when I updated the server from 1.13.2 to 1.14
Thanks in advance
Multiverse-core 4.0.0. SNAPSHOT MC 1.14.3

**Comment by Jadiction** [comment]
I've yet to run into this. With just Multiverse running, does this persist? I don't believe Multiverse touches your connection spawn location. I'd say it's another plugin doing this.

**Comment by sixamscrew** [comment]
It is just Multiverse core doing this. When I remove the plugin, the players get successfully in their last location after login, when multiverse in in plugins folder, the players get always the spawn...

**Comment by Jadiction** [comment]
Can you output the Pastebin link from `/mv version -b`? Also a list of your plugins.

**Comment by sixamscrew** [comment]
Can I send you a private message?

**Comment by Jadiction** [comment]
It doesn't really have any sensitive information, but sure if you'd like.

**Comment by sixamscrew** [comment]
Here is the /mv version -b:
https://pastebin.com/2RLVQDkX

**Comment by Jadiction** [comment]
Okay, so you join the server, you start off where you last disconnect at, use /login and you get teleported to the spawn set for the world?

P.s If you would like quicker help with this, you could join the [Multiverse Discord](https://discord.gg/NZtfKky).

**Comment by sixamscrew** [comment]
The problem was in AuthMe commands.yml:
onLogin:
    welcome:
        command: mv tp %p world
        executor: CONSOLE
        delay: 0

I don't know how that appeared there, but anyway thanks for the help, the issue is solved.
