### ISSUE TITLE
Deprecated method error.

### ISSUE THREAD

**Issue by Kimpstheman** [Multiverse/Multiverse-Core#2031]
When starting up the server, multiverse core gives a deprecated method error:

https://pastebin.com/SymhuS9V

Using latest release.

Running Paper 1.14.3 #117 build

**Comment by Tresswa** [comment]
I have noticed this same error at start up.

**Comment by Jadiction** [comment]
Duplicate of https://github.com/Multiverse/Multiverse-Core/issues/2000
