### ISSUE TITLE
Generator Listings Returns Error & Invalid Generator

### ISSUE THREAD

**Issue by RageYT** [Multiverse/Multiverse-Core#2033]
### ISSUE
---
When I try to list the generator types with **/mv gen** it throws an error in-game and refers to the console. After reviewing the console it shows this error,

https://pastebin.com/WkveyRJm

### VERSIONS
---
**Spigot:**  1.12.2
**Minecraft:** 1.12.2
**Multiverse:** 2.5.0-b751

**Comment by Jadiction** [comment]
Need a bit more information. A faster response can be found on the [Multiverse Discord](https://discord.gg/NZtfKky). If you could go there and explain more, we could likely find a solution or find the culprit.

**Comment by Jadiction** [comment]
Closing old ticket. Make sure to update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if you believe you are encountering a bug. You can receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
