### ISSUE TITLE
Data Packs 

### ISSUE THREAD

**Issue by TheSaltyPug** [Multiverse/Multiverse-Core#2036]
I made a comment on issue #1842 about this, but I'm afraid that that might get buried under the other issues because its kind of old.

The issue is that data packs cannot be loaded in multiverse world. I have not actually put any into the default "world", but I assume that they would work there, if only for that world. 

MV worlds do NOT generate with a "datapacks" folder. If one is created and a datapack is put inside it, it does not run.

I

**Comment by dumptruckman** [comment]
No need to create another issue.
