### ISSUE TITLE
mvtp command not available in command blocks.

### ISSUE THREAD

**Issue by cemarriott** [Multiverse/Multiverse-Core#2038]
Paper MC 127
MultiVerse Core 4.0.0
MultiVerse NetherPortals 4.0.0
MultiVerse Portals 4.0.0
(variety of other plugins, let me know if a list would be useful)

As the target selectors are not usable in non-vanilla commands, I instead tried to use the syntax `/execute as @p run mvtp <world>` so that the command itself doesn't have to handle the selector.
However mvtp is not recognized as a valid command that can be used. The autocomplete list doesn't show mvtp, and if you try to run the command anyway, it will mark it as an error with a "Incorrect argument for command" message.

<img width="1680" alt="Screen Shot 2019-07-10 at 9 12 27 PM" src="https://user-images.githubusercontent.com/1731607/61015258-c3446600-a358-11e9-8cd0-e26e09868869.png">
<img width="494" alt="Screen Shot 2019-07-10 at 9 12 44 PM" src="https://user-images.githubusercontent.com/1731607/61015263-c7708380-a358-11e9-842b-c912f4397926.png">

**Comment by HIHIQY1** [comment]
Any update on this issue?

**Comment by cemarriott** [comment]
> Any update on this issue?

Using the @[CommandHook](https://www.spigotmc.org/resources/commandhook.61415/) plugin, I was able to use the mvtp command in command blocks with target selectors working properly.

The console command I have in the block is `mvtp @p a:New_Hub`, for example.

**Comment by benwoo1110** [comment]
Command selectors on 1.13+
Spigot does not allow plugin commands to use vanilla command selectors on 1.13+. You can use a plugin to restore this:

PsudoCommands: https://www.spigotmc.org/resources/psudocommands-add-the-function-to-plugin-commands.56738/
CommandHook: https://www.spigotmc.org/resources/commandhook.61415/
