### ISSUE TITLE
Importing the same world again and again

### ISSUE THREAD

**Issue by Freez159** [Multiverse/Multiverse-Core#2039]
Every time a restart server, I have to import the same world again. When I start server, type /mv list. The world is not there so I have to do /mv import worldname normal. Please help me what to do

**Comment by Jadiction** [comment]
When you import it, does the console show any errors or any indication that it couldn't write to the configuration file? Are you modifying the configuration file after importing? Check the file and see if it made changes. If so, restart and see what happens. Can you also provide more information, such as the link from `/mv version -b`?

**Comment by Jadiction** [comment]
Closing ticket. It's recommended that for support, you can get faster response on the [Multiverse Discord](https://discord.gg/NZtfKky).
