### ISSUE TITLE
Multiverse-Core v4.0.1-SNAPSHOT-bUNKNOWN

### ISSUE THREAD

**Issue by AM9327** [Multiverse/Multiverse-Core#2040]
Server thread/WARN [Multiverse-Core] "Multiverse-Core v4.0.1-SNAPSHOT-bUNKNOWN" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by Jadiction** [comment]
Duplicate issue of #2000
