### ISSUE TITLE
Build server (ci.onarandombox.com) is down?

### ISSUE THREAD

**Issue by atm0915** [Multiverse/Multiverse-Core#2043]
https://ci.onarandombox.com/job/Multiverse-Core/ appears to be down right now. Just letting y'all know

**Comment by dumptruckman** [comment]
Thank you. I had to manually restart it just the other day because it was down. However, it seems that it went down again after that. I'll try to investigate what's going on.

**Comment by dumptruckman** [comment]
It's back up once again!

**Comment by Jeppa** [comment]
seems to be down again...

http://http://ci.onarandombox.com/ :
503 Service Temporarily Unavailable

https://http://ci.onarandombox.com/ :
Error 525 Ray ID:.... SSL handshake failed

**Comment by pimentelleo** [comment]
i guess it is up again check it out
