### ISSUE TITLE
Generate lag change or use worlds

### ISSUE THREAD

**Issue by andfont** [Multiverse/Multiverse-Core#2045]
versions:
MC Spigot 1.14.3-R0.1-SNAPSHOT)
Multiverse-Core version 4.0.0-SNAPSHOT-b764
description problem:
We have the latest version of the multiverse core and it generates a lot of lag, it does not work well in 14, we have checked with the "timings paste" and it is very bad indeed! Much lag when changing worlds etc. It makes the server work very badly! please in previous versions this did not happen! something is wrong to fix this problem please!
Error:
it's a barbarity! generate pcTicks! 4,413.50%
Multiverse-Core v4.0.0-SNAPSHOT-b764Total: 26.269 s Pct: 0.22%
   Pct Total	Pct Tick	   Total	      Avg	 PerTick	     Count		Event
       0.20%	4,413.50%	 24.27 s	 2,206.75 ms	 0.0	       0.0k	    Task: MVPlayerListener$1(Single)
       0.01%	  30.17%	  1.69 s	    15.09 ms	 0.0	       0.1k	    Task: MVPlayerListener$2(Single)
       0.00%	   0.01%	  0.17 s	     0.00 ms	 0.3	      62.8k	    MVEntityListener::creatureSpawn(CreatureSpawnEvent)
       0.00%	   0.02%	  0.10 s	     0.01 ms	 0.0	       9.5k	    MVPlayerListener::playerTeleport(PlayerTeleportEvent)
       0.00%	   0.00%	  0.02 s	     0.00 ms	 0.1	      11.8k	    Task: ScriptTask(interval 20)
       0.00%	   0.01%	  0.01 s	     0.00 ms	 0.0	       1.1k	    MVEntityListener::entityRegainHealth(EntityRegainHealthEvent)
       0.00%	   0.00%	  0.00 s	     0.00 ms	 0.0	       3.0k	    MVPortalListener::portalForm(PlayerInteractEvent)
       0.00%	   0.01%	  0.00 s	     0.01 ms	 0.0	       0.4k	    MVEntityListener::foodLevelChange(FoodLevelChangeEvent)
       0.00%	   0.07%	  0.00 s	     0.04 ms	 0.0	       0.0k	    MVPlayerListener::playerJoin(PlayerJoinEvent)
       0.00%	   0.06%	  0.00 s	     0.03 ms	 0.0	       0.0k	    MVWeatherListener::weatherChange(WeatherChangeEvent)
       0.00%	   0.05%	  0.00 s	     0.02 ms	 0.0	       0.0k	    MVWeatherListener::thunderChange(ThunderChangeEvent)
       0.00%	   0.02%	  0.00 s	     0.01 ms	 0.0	       0.1k	    MVPlayerListener::playerChangedWorld(PlayerChangedWorldEvent)
       0.00%	   0.08%	  0.00 s	     0.04 ms	 0.0	       0.0k	    MVPlayerListener::playerRespawn(PlayerRespawnEvent)
       0.00%	   0.02%	  0.00 s	     0.01 ms	 0.0	       0.0k	    MVPlayerListener::playerQuit(PlayerQuitEvent)
       0.00%	   0.19%	  0.00 s	     0.09 ms	 0.0	       0.0k	    MVPlayerListener::playerPortal(PlayerPortalEvent)
       0.00%	   0.09%	  0.00 s	     0.05 ms	 0.0	       0.0k	    MVPlayerListener::playerPortalCheck(PlayerPortalEvent)
       0.00%	   0.03%	  0.00 s	     0.01 ms	 0.0	       0.0k	    BuscriptListener::pluginDisable(PluginDisableEvent)
       0.00%	   0.02%	  0.00 s	     0.01 ms	 0.0	       0.0k	    VaultHandler$VaultListener::vaultEnabled(PluginEnableEvent)
       0.00%	   0.02%	  0.00 s	     0.01 ms	 0.0	       0.0k	    VaultHandler$VaultListener::vaultDisabled(PluginDisableEvent)
       0.00%	   0.00%	  0.00 s	     0.00 ms	 0.0	       0.0k	    VaultListener::pluginDisable(PluginDisableEvent)
       0.00%	   0.00%	  0.00 s	     0.00 ms	 0.0	       0.0k	    VaultListener::pluginEnable(PluginEnableEvent)

**Comment by dumptruckman** [comment]
Please share your entire timings report. Use https://pastebin.com

**Comment by andfont** [comment]
? You already have the timings report above where we see the exaggeration of use of the multiverse-core

**Comment by andfont** [comment]
sorry and I think it's solved thank you very much! xDD good work xD

**Comment by andfont** [comment]
but why have you closed the case when it is not solved? that there is some version that no longer passes those lagg and elevated timings?
