### ISSUE TITLE
Generate lag change or use worlds

### ISSUE THREAD

**Issue by andfont** [Multiverse/Multiverse-Core#2047]
versions:
 MC Spigot 1.14.3-R0.1-SNAPSHOT)
 Multiverse-Core version 4.0.0-SNAPSHOT-b764
 description problem:
 We have the latest version of the multiverse core and it generates a lot of lag, it does not work well in 14, we have checked with the "timings paste" and it is very bad indeed! Much lag when changing worlds etc. It makes the server work very badly! please in previous versions this did not happen! something is wrong to fix this problem please!
 Error:
 it's a barbarity! generate pcTicks! 4,413.50%
 Multiverse-Core v4.0.0-SNAPSHOT-b764Total: 26.269 s Pct: 0.22%
 Pct Total Pct Tick Total Avg PerTick Count Event
 0.20% 4,413.50% 24.27 s 2,206.75 ms 0.0 0.0k Task: MVPlayerListener$1(Single)
 0.01% 30.17% 1.69 s 15.09 ms 0.0 0.1k Task: MVPlayerListener$2(Single)
 0.00% 0.01% 0.17 s 0.00 ms 0.3 62.8k MVEntityListener::creatureSpawn(CreatureSpawnEvent)
 0.00% 0.02% 0.10 s 0.01 ms 0.0 9.5k MVPlayerListener::playerTeleport(PlayerTeleportEvent)
 0.00% 0.00% 0.02 s 0.00 ms 0.1 11.8k Task: ScriptTask(interval 20)
 0.00% 0.01% 0.01 s 0.00 ms 0.0 1.1k MVEntityListener::entityRegainHealth(EntityRegainHealthEvent)
 0.00% 0.00% 0.00 s 0.00 ms 0.0 3.0k MVPortalListener::portalForm(PlayerInteractEvent)
 0.00% 0.01% 0.00 s 0.01 ms 0.0 0.4k MVEntityListener::foodLevelChange(FoodLevelChangeEvent)
 0.00% 0.07% 0.00 s 0.04 ms 0.0 0.0k MVPlayerListener::playerJoin(PlayerJoinEvent)
 0.00% 0.06% 0.00 s 0.03 ms 0.0 0.0k MVWeatherListener::weatherChange(WeatherChangeEvent)
 0.00% 0.05% 0.00 s 0.02 ms 0.0 0.0k MVWeatherListener::thunderChange(ThunderChangeEvent)
 0.00% 0.02% 0.00 s 0.01 ms 0.0 0.1k MVPlayerListener::playerChangedWorld(PlayerChangedWorldEvent)
 0.00% 0.08% 0.00 s 0.04 ms 0.0 0.0k MVPlayerListener::playerRespawn(PlayerRespawnEvent)
 0.00% 0.02% 0.00 s 0.01 ms 0.0 0.0k MVPlayerListener::playerQuit(PlayerQuitEvent)
 0.00% 0.19% 0.00 s 0.09 ms 0.0 0.0k MVPlayerListener::playerPortal(PlayerPortalEvent)
 0.00% 0.09% 0.00 s 0.05 ms 0.0 0.0k MVPlayerListener::playerPortalCheck(PlayerPortalEvent)
 0.00% 0.03% 0.00 s 0.01 ms 0.0 0.0k BuscriptListener::pluginDisable(PluginDisableEvent)
 0.00% 0.02% 0.00 s 0.01 ms 0.0 0.0k VaultHandler$VaultListener::vaultEnabled(PluginEnableEvent)
 0.00% 0.02% 0.00 s 0.01 ms 0.0 0.0k VaultHandler$VaultListener::vaultDisabled(PluginDisableEvent)
 0.00% 0.00% 0.00 s 0.00 ms 0.0 0.0k VaultListener::pluginDisable(PluginDisableEvent)
 0.00% 0.00% 0.00 s 0.00 ms 0.0 0.0k VaultListener::pluginEnable(PluginEnableEvent)

**Comment by andfont** [comment]
please do not close the case without giving an answer this is not solved before this problem did not exist thank you I pass the pastedbin

**Comment by andfont** [comment]
Here are examples of the problem where the exaggerated consumption of the multiverse-core is clearly seen, see the plugin section examples:
https://pastebin.com/EAfU8BpG
https://timings.spigotmc.org/?url=sanitesaxu

**Comment by dumptruckman** [comment]
The only way this seems possible is if something unusual is going on on your server possible caused by another plugin. Can you try turning on debug mode and seeing if the console is being spammed by MV debug messages? `/mv debug 3` will enable debug output and `/mv debug 0` will disable it.

**Comment by dumptruckman** [comment]
Nevermind. I just thought about it some more and it's not likely being spammed that is the problem. When your players log in are they being sent to another world? If so, it's possible they are causing a bunch of chunks to need to be loaded. You could probably relieve this by either setting `keepspawninmemory` to `true` for that world or possibly using Paper instead of Spigot.

**Comment by andfont** [comment]
indeed they have to be sent to another world, this always worked perfectly but from 1.14 and the latest versions of multiverse-core is going very badly! the tps increase greatly as can be clearly seen in the reports provided. all other plugins work perfectly and do not generate high tps as if it does the multiverse-core.

**Comment by andfont** [comment]
For me it is not the one that solves to move to paper we do not like paper at all! It has many more bugs than spigot, so please, it is not a solution to turn to paper thanks and we look forward to a hot fix of this.

**Comment by andfont** [comment]
our worlds already had the keepspawninmemory to true

**Comment by dumptruckman** [comment]
Unfortunately this is not something we can fix in Multiverse. We cannot control how the server teleports players or how it loads chunks. Those two things are the culprit for the timing issue you see.

Notably, in the roughly 12.5 hours recorded in your timings, these problematic teleports from Multiverse only happened 32 times consuming a total of 70 seconds. That's 0.1% of the total ticks which would result in an averaged TPS drop of about 0.03. If you're experiencing lag all the time, then these teleports are ***not*** the problem.

**Comment by dumptruckman** [comment]
Looking again at your timings, you may want to investigate whatever mundoabf is. That appears to be taking up more processing time than anything else.

**Comment by andfont** [comment]
the tps is being consumed by the multiverse-core plugin all other plugins and functions are fine, we are not satisfied with the closing of the case, we have made more timings and it is evident that the multiverse-core is causing it when changing worlds.
