### ISSUE TITLE
Can't create portals

### ISSUE THREAD

**Issue by alainamathew** [Multiverse/Multiverse-Core#2050]
Sorry to bother, but whenever I try to create a portal using the wand, it always says, "You need to LEFT click on a block with your wand!" I have tried doing it on a different server and it just says the same thing. I also have tried making a portal multiple places on my world and I am still unable to. It would be appreciated if you could help. Thanks.

**Comment by Jadiction** [comment]
Do you have WorldEdit installed? What's the version of it? What versions of Multiverse-Core and Multiverse-Portals? MC Version?

**Comment by Jadiction** [comment]
Closing ticket. It's recommended that for support, you can get faster response on the [Multiverse Discord](https://discord.gg/NZtfKky).
