### ISSUE TITLE
 permission debugger tool/logging

### ISSUE THREAD

**Issue by JohOply** [Multiverse/Multiverse-Core#2058]
Hi there

When player is not able to go to a world with a teleport (it says "You don't have access to go there"), is it possible to add a log to the console? It could be useful for debug

Thank you

**Comment by benwoo1110** [comment]
I think it will be more of a permission debugger tool/logging, like `/ess debug` in essentialsX if anyone is interested to implement.

**Comment by SDpyro** [comment]
It would be beneficial to have a portal give an error, indicating a portal perm issue and/or a target world issue.

**Comment by benwoo1110** [comment]
Permissions plugin such as Luckperms has good permission debugging tools
