### ISSUE TITLE
World Gets Deleted after server restarts

### ISSUE THREAD

**Issue by PuggoExist** [Multiverse/Multiverse-Core#2060]
If i build on a world then restart my server the world gets deleted. The files are still in the console but i cant teleport to it,

**Comment by PuggoExist** [comment]
i found a way to get into the world but the builds are gone

**Comment by Jadiction** [comment]
It's very unlikely Multiverse is doing this. Troubleshoot your other plugins. Ensure your world is loaded by Multiverse and that the world is imported. Otherwise, Multiverse is not managing it.

**Comment by PuggoExist** [comment]
I found out that what was happening is we ran out of storage so when I
restarted it it had to delete it.
