### ISSUE TITLE
Turn off falldamage perworld basis

### ISSUE THREAD

**Issue by joshbutlermedia** [Multiverse/Multiverse-Core#2067]
I can't find anything about how to turn off fall damage. I've tried /mv modify falldamage false, and variants of that with no help. I also went to the worlds.yml folder and there is no spot for it. Am I missing something or is there a different plug-in that would give me the option to change this on a per-world basis?

**Comment by Jadiction** [comment]
This isn't a provided function in Multiverse. You'd have to look for another plugin to do this.
