### ISSUE TITLE
Plugin Error in Console

### ISSUE THREAD

**Issue by MinecraftMarcus1** [Multiverse/Multiverse-Core#2069]
[Server] Server thread/WARN "Multiverse-Core v4.1.0-SNAPSHOT-b772" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by Jadiction** [comment]
Duplicate of #2000.
