### ISSUE TITLE
Can't Create worlds and import

### ISSUE THREAD

**Issue by alexvermaning0** [Multiverse/Multiverse-Core#2072]
Error log:
https://pastebin.com/KN9VB92W
Version: 12.08 17:12:51 [Server] INFO [Multiverse-Core] [Multiverse-Core] Dumping Config Values: (version 2.9)
12.08 17:12:51 [Server] INFO [Multiverse-Core] [Multiverse-Core]  messagecooldown: 5000
12.08 17:12:51 [Server] INFO [Multiverse-Core] [Multiverse-Core]  teleportcooldown: 1000
12.08 17:12:51 [Server] INFO [Multiverse-Core] [Multiverse-Core]  worldnameprefix: false
12.08 17:12:51 [Server] INFO [Multiverse-Core] [Multiverse-Core]  worldnameprefixFormat: [%world%]%chat%
12.08 17:12:51 [Server] INFO [Multiverse-Core] [Multiverse-Core]  enforceaccess: false
12.08 17:12:51 [Server] INFO [Multiverse-Core] [Multiverse-Core]  displaypermerrors: true
12.08 17:12:51 [Server] INFO [Multiverse-Core] [Multiverse-Core]  teleportintercept: true
12.08 17:12:51 [Server] INFO [Multiverse-Core] [Multiverse-Core]  firstspawnoverride: true
12.08 17:12:51 [Server] INFO [Multiverse-Core] [Multiverse-Core]  firstspawnworld: world
12.08 17:12:51 [Server] INFO [Multiverse-Core] [Multiverse-Core]  debug: 0
12.08 17:12:51 [Server] INFO [Multiverse-Core] [Multiverse-Core] Special Code: FRN002

**Comment by Jadiction** [comment]
Need more info. Such as:
- Your server version
- The output link from /mv version -b
