### ISSUE TITLE
Teleport with a CommandBlock

### ISSUE THREAD

**Issue by Geant200** [Multiverse/Multiverse-Core#2078]
Hello everyone.

Spigot version : 1.14.4

Version Multiverse 
Multiverse-Core-4.1.0-SNAPSHOT
Multiverse-NetherPortals-4.1.0-SNAPSHOT
Multiverse-Portals-4.1.0-SNAPSHOT
Multiverse-SignPortals-4.1.0-SNAPSHOT

I created several world I use a CommandBlock to teleport with the following command.

`/mv tp @p[r=6] e:redstone_guide:-4,102,7`

it does not work I tested with otherwise.

`mv tp @p[distance=..6] e:redstone_guide:-4,102,7`

it still does not work.

Can you help me please.
I thank you in advance.

**Comment by Jadiction** [comment]
A duplicate suggestion of https://github.com/Multiverse/Multiverse-Core/issues/2038

**Comment by Geant200** [comment]
The command works great.
mv tp @p[distance=..6] e:redstone_guide:-4,102,7

The problem came from Command Bloc when I recovered my world of the 1.13 to have it in 1.14.4 the command block did not work anymore with my command I had to break the block command by a new command block and that's it .

Thanks to _NewAge. for his help who found me the solution.
