### ISSUE TITLE
spawnrate does not work on Minecraft 1.14+

### ISSUE THREAD

**Issue by Mario359** [Multiverse/Multiverse-Core#2080]
On my server there is a map with plots
On this map, I decided to reduce the spawn rate of monster to have something simpler
So I do:
```
  plots:
  [...]
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '10000'
        exceptions:
        - wither
  [...]
```
On Minecraft 1.13.2 it worked very well
But since my server has been updated on Minecraft 1.14.4 it doesn't work anymore
I have the impression that the spawn rate for monsters has been increased in 1.14, but even with a higher value (9999999) it doesn't change anything
I use Paper-167 MC:1.14.4 and Multiverse-Core 4.1-b773

**Comment by Jadiction** [comment]
The spawn rate defines how many ticks there are between attempts to spawn animals. For more information see: https://jd.bukkit.org/org/bukkit/World.html#setTicksPerAnimalSpawns(int)

**Comment by Mario359** [comment]
The spawnrate at -1, 10000 or even 999999 doesn't change anything
![2019-08-23_15 47 13](https://user-images.githubusercontent.com/20285750/63597384-9e7d1880-c5bd-11e9-9b3e-f45c628d1197.png)
Monsters spawn in a normal way

**Comment by Jadiction** [comment]
Closing old ticket. Please open a new ticket if you believe you are encountering a bug. You can receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
