### ISSUE TITLE
Internal Error 

### ISSUE THREAD

**Issue by itsWarHammer** [Multiverse/Multiverse-Core#2081]
when i do /mv it says internal error and in console this is the bug report 

java.lang.NullPointerException
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897)
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710)
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641)
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481)
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909)
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902)
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886)
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819)
22.08 08:49:27 [Server] INFO [08:49:27] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by itsWarHammer** [comment]
Version 1.14

**Comment by dumptruckman** [comment]
This is not the full error. I need to see the rest, especially the part after "Caused By".

**Comment by itsWarHammer** [comment]
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: java.lang.NullPointerException
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897)
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710)
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641)
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481)
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909)
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902)
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886)
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819)
22.08 09:41:56 [Server] INFO [09:41:56] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by itsWarHammer** [comment]
is this it ?
