### ISSUE TITLE
Internal Error for all commands - Multiverse disabling itself

### ISSUE THREAD

**Issue by Oonicorn** [Multiverse/Multiverse-Core#2082]
Hi, so every time my server reboots, Multiverse stops working entirely. If I delete the folder with all the configs and stuff, it generates a new one and works fine until I have to restart the server again. I've got no idea what the issue could be, but here's the error log from the console:
(By the way, the console has more recent towards the top so it looks backwards)

22.08 11:07:22 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
22.08 11:07:22 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-171]
22.08 11:07:22 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-171]
22.08 11:07:22 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.4.jar:git-Paper-171]
22.08 11:07:22 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:456) ~[patched_1.14.4.jar:git-Paper-171]
22.08 11:07:22 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701) ~[patched_1.14.4.jar:git-Paper-171]
22.08 11:07:22 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-171]
22.08 11:07:22 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-171]
22.08 11:07:22 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.14.4.jar:git-Paper-171]
22.08 11:07:22 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'mv' in plugin Multiverse-Core v4.0.0-b766 - plugin is disabled.
22.08 11:07:22 [Server] WARN Unexpected exception while parsing console command "mv"

I would really REALLY like to figure out what's going wrong so I could fix this error.

**Comment by Jadiction** [comment]
Sounds like the plugin gets corrupted on reboot. Could be the way you (or your host) reboots the server or another plugin. Attempt restarts with just Multiverse (backup server first) and see if it reproduces.

**Comment by Jadiction** [comment]
Going to close the ticket since it doesn't appear to be an MV issue. It's best (way faster as we use GitHub to track bugs/suggestions) to receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
