### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by actioninspire** [Multiverse/Multiverse-Core#2084]
I’ve been having a lot of trouble getting the difficulty setting of my worlds to stay put using this plugin. I’ve checked out a bunch of posts with folks who have had similar issues in the past to try and troubleshoot, but nothing I’ve done has worked, no matter how I save the file, or type the commands, or stop the server. I’m hoping you guys may be able to provide me with more insight on how to fix this?
Please respond when you can, and thank you for reading!

**Comment by Jadiction** [comment]
Going to close the ticket since it doesn't appear to be an MV issue. It's best (way faster as we use GitHub to track bugs/suggestions) to receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
