### ISSUE TITLE
gamemode not set correctly in imported world

### ISSUE THREAD

**Issue by AeSix** [Multiverse/Multiverse-Core#2091]
Spigot 1.14.4
Multiverse-Core 4.1.1 build 777
PlotSquared 4.340 (imported as generator into MV)

Yesterday the server, and the world was updated from 1.13.2 to 1.14.4 (using --forceUpgrade)
the world (newworld) was originally created without MV on 1.11, updated to 1.12.2, upgraded to 1.13.2 (with --forceUpgrade) and /then/ MV (for 1.13.2) was added some time ago to add an additional world (VIP) - thankfully it was never open to the public.

I updated MV, and all other plugins which needed to be, for 1.13.2 -> 1.14.4
The newworld world was imported into MV.  (NOTE: A second "VIP" world, also created with PlotSquared, was NOT imported. - this may be an issue with PS, not MV, however)

When MV imported the main world, the worlds.yml game mode entry was set to "SURVIVAL" - the server has always been in creative game mode.  I assume MV reads game mode from server.properties, but only because I am unsure where it would get that information otherwise. 

I am @AeSix#2025 on the MV Discord, if you'd like to talk in real-time. Please ping me.

**Comment by Jadiction** [comment]
The `survival` gamemode is the default when importing/creating. You simply just need to go to the worlds and `/mvm set gamemode xxxxx`.

**Comment by Jadiction** [comment]
It's best (way faster as we use GitHub to track bugs/suggestions) to receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).

**Comment by AeSix** [comment]
So, this isn't seen as a bug at all for imports?
Thanks, I guess.

**Comment by Jadiction** [comment]
It's not a bug, survival is the default and that's intentional behavior. All you have to do is to set up each world to be creative...
