### ISSUE TITLE
Not an issue or a bug but a request for help if possible

### ISSUE THREAD

**Issue by EchocallingEarth** [Multiverse/Multiverse-Core#2092]
Sorry if asking in the wrong place or manner I attempted to find the right place to ask but could not find any option to do so. 

I am wondering if there is a way for me to create a custom End using Multiverse Core?

I am hoping to create an End with no land generated. To be used for a space world on our server. Is this possible and if so how would I write the create command? Allow me to be clear we do not want a void world as that lacks stars the end darkness etc. 

If not possible with multiverse by itself possibly with a generator??? 
Thanks in advance as I knw your super busy.

Respectfully ~ Echo

**Comment by Jadiction** [comment]
This is not possible with Multiverse, you will have to look for a generator that does this if there is one.
