### ISSUE TITLE
Cannot Teleport Between Worlds

### ISSUE THREAD

**Issue by MaddDawg555** [Multiverse/Multiverse-Core#2094]
Hi, I have no idea what's going on here.  I haven't teleported to a different world in a long while and was waiting to use it to teach somebody to play the game on a fresh world.  When I try to teleport, however, it just teleports me to a single location in the original spawn world.  I've tried deleting and recreating worlds and everything, nothing has worked so far.  I have full permissions (op) with LP and even gave myself all teleport/access perms just in case but to no avail.  It also tells me the worlds don't exist when i try to change their difficulties, though I'm typing them just as they're listed (I even checked the world file names!  I've tried installing new builds (now on 4.1.1) but nothing is working.  I'm running the latest version of Paper.

Plugins:
AlchemicalArrows
ArmoredElytra
BlockLocker
DeathChestPro
DragonEggDrop
EssentialsX (Original + AntiBuild/Chat/GeoIP/Protect/Spawn
EpicWorldGenerator
FastLeafDecay
GetSpawners
GriefPrevention
LuckPerms
mcMMO
MendingEnchant
Multiverse-Core
OpenInv
SimpleAntiMobLag
Vault
VeinMiner
WorldEdit

**Comment by Jadiction** [comment]
What is the world name?
What command are you using?
Which Multiverse version are you using?

**Comment by MaddDawg555** [comment]
World names WHERE TP WORKS are: "public" "public_nether" "public_the_end"
World that just teleports me to a random place in "public" is "private".  I also tried other world names, all teleport me to "public" locations.
/mv tp private
/mv tp [my ign] private
Neither worked.  I was running build 719 from Spigot when I first had the problem (but I first installed 719 as well, it worked before).  I now am on build 777 (most recent).

**Comment by Jadiction** [comment]
This seems like a plugin conflict. Can you back up your server and only try with the Multiverse plugins?

**Comment by MaddDawg555** [comment]
I think it may be due to Epic World Generator.  I kept just MV and multiverse installed (because if I loaded new chunks in a different world i wanted the chunk loading to be consistent in terms of world generation).  Same problem remained.  Either that or my files are just screwed somewhere.

**Comment by Jadiction** [comment]
Closing old ticket. Please open a new ticket if you believe you are encountering a bug. You can receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
