### ISSUE TITLE
Flying is disabled when player joins world.

### ISSUE THREAD

**Issue by twoody9295** [Multiverse/Multiverse-Core#2095]
If a non-opped player joins the creative world on my server they are unable to fly.  allowflight and flight are both set to true and the worlds gamemode is set to creative.  Only if I do /mv reload while a player is in the world then they can fly, but if they go to a different world and then come back to the creative world they can no longer fly.

**Comment by Jadiction** [comment]
Sounds like a plugin conflict. Backup your server and try without the other plugins.

**Comment by Jadiction** [comment]
Closing old ticket. Please open a new ticket if you believe you are encountering a bug. You can receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
