### ISSUE TITLE
Help me :(

### ISSUE THREAD

**Issue by MiuSofii** [Multiverse/Multiverse-Core#2096]
[Multiverse-Core] "Multiverse-Core v4.1.0-b775" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

and sometimes I get an error that breaks the server
[https://pastebin.com/tpfGs41V](url)

**Comment by Jadiction** [comment]
Duplicate of #2000
Your error in the Pastebin isn't related to Multiverse.
