### ISSUE TITLE
how to make it so everyone can use /mvtp

### ISSUE THREAD

**Issue by sudocode1** [Multiverse/Multiverse-Core#2097]
how can i make it so people without op can use /mvtp

**Comment by Jadiction** [comment]
https://github.com/Multiverse/Multiverse-Core/wiki/Permissions For permission setup
https://github.com/Multiverse/Multiverse-Core/wiki/Big-List-O-Permissions For permission list (in your case: `multiverse.teleport.self.w` will allow someone to teleport to worlds they have access to.)

**Comment by Jadiction** [comment]
Closing old ticket. Please open a new ticket if you believe you are encountering a bug. You can receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
