### ISSUE TITLE
config file keeps changing back

### ISSUE THREAD

**Issue by sudocode1** [Multiverse/Multiverse-Core#2098]
Why whenever I change the prefixchat to false and I restart the server it changes back?

**Comment by Jadiction** [comment]
When you modify your config and it resets, it's because when the server gets reloaded or restarted, it overwrites changes. You must shut down the server, re-open the configuration file, modify the file, save it and turn the server back on.

**Comment by Jadiction** [comment]
Closing old ticket. Please open a new ticket if you believe you are encountering a bug. You can receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
