### ISSUE TITLE
Item frames do not function correctly when using other worlds.

### ISSUE THREAD

**Issue by Toad-Z** [Multiverse/Multiverse-Core#2099]
I recently discovered that when I am using a world that is not the original world on the Multiverse plugin, item frames do not function correctly as when I put an item into it I am then unable to take it out of the frame again, regardless of the gamemode that I am in, unless I break the block supporting the frame. This is really inconvenient for the project that I am working on so I would be really grateful if this bug gets fixed! :)

**Comment by Jadiction** [comment]
> using a world that is not the original world on the Multiverse plugin

Do you mean an imported world? 

I have yet to experience this, item frames have always worked regardless if the world is "created" by MV or not (MV doesn't actually create the world, it makes the world the same way Bukkit would)

Do you have other plugins? This sounds like another plugin, not MV.

What is your MC/Spigot/Paper version?

**Comment by Jadiction** [comment]
Closing old ticket. Please open a new ticket if you believe you are encountering a bug. You can receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
