### ISSUE TITLE
CleanroomGenerator do crazy stuff

### ISSUE THREAD

**Issue by JanaFischinger** [Multiverse/Multiverse-Core#2100]
Hello

I have a big problem and hope somebody can help me.
on my server i created a flat world a few years ago with:
/mvcreate test normal -g CleanroomGenerator:20,stone,8,dirt,1,grass

And today when i walk in a new area i got some 16x16 blocks:
https://imgur.com/7nTUNnn

how can it fix this

**Comment by Jadiction** [comment]
This is a generator issue, not MV.
