### ISSUE TITLE
Survival server issue

### ISSUE THREAD

**Issue by Adib23704** [Multiverse/Multiverse-Core#2105]
Hello. I am Adib. I am using Multiverse-core for 3 months. I use Multiverse-core, signportals, inventories. So, I want to make my server a minigame plus survival server. I made a new world for survival. When I quit or tp to the main lobby and tp back to survival world I don't respawn in my last place. I respawn at WORLD's Spawn point. But I don't want it. Can you please help me with it?

**Comment by mirimel1001** [comment]
noice

**Comment by Adib23704** [comment]
> noice

Sir if you know the answer then reply :D

**Comment by Jadiction** [comment]
When teleporting between worlds, the default behavior is to go to the spawn of the world. This can be changed; however, it's not perfect. You'll need to toggle `last_location` on (provided by Multiverse-Inventories) by doing `/mvinv toggle last_location`. Keep in mind this forces last location for ALL worlds, there is currently no way to only use this function for specific worlds.

**Comment by Adib23704** [comment]
> When teleporting between worlds, the default behavior is to go to the spawn of the world. This can be changed; however, it's not perfect. You'll need to toggle `last_location` on (provided by Multiverse-Inventories) by doing `/mvinv toggle last_location`. Keep in mind this forces last location for ALL worlds, there is currently no way to only use this function for specific worlds.

Thanks for this useful answer. But there is any way to do this in specific worlds?

**Comment by mirimel1001** [comment]
okay

**Comment by Jadiction** [comment]
> is any way to do this in specific worlds?

There is not, sorry.

**Comment by Adib23704** [comment]
Ok Thanks for this help @Jadiction
