### ISSUE TITLE
Warning in console

### ISSUE THREAD

**Issue by greyasin2** [Multiverse/Multiverse-Core#2109]
Hey authors of Multiverse-Core i got a warning at the warning says to notify the authors. This is the warning : "Multiverse-Core v4.0.0-b766" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com. onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by EbonJaeger** [comment]
See issue #2000.
