### ISSUE TITLE
Cant go to nether

### ISSUE THREAD

**Issue by TheRealLifeMC** [Multiverse/Multiverse-Core#2112]
Hi, I am having a problem with going to the nether, I can make portals but when you go in it won't take you anywhere I am on the latest version of MV

**Comment by Jadiction** [comment]
Did you set it up properly? What's the destination of the portal?

**Comment by TheRealLifeMC** [comment]
It is set up right, and the destination is the nether. It was working until
I restart the server awhile back than it all stoped

**Comment by Jadiction** [comment]
Are you talking about normal nether portals or Multiverse-Portals?

**Comment by TheRealLifeMC** [comment]
Normal portals

**Comment by Jadiction** [comment]
If you're trying to go to a nether portal that isn't `(your world here)_nether` then you'll need [Multiverse-NetherPortals](https://dev.bukkit.org/projects/multiverse-netherportals/).

**Comment by Jadiction** [comment]
Closing old ticket. Please open a new ticket if you believe you are encountering a bug. You can receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
