### ISSUE TITLE
Crash Server/Краш сервера 

### ISSUE THREAD

**Issue by Stason4ikRU** [Multiverse/Multiverse-Core#2113]
p.s Please use google translator
Такая проблема: я создаю новый мир. Если я в этом новом мире хожу 1-2 минуты, то сервер крашеться
[latest.log](https://github.com/Multiverse/Multiverse-Core/files/3722146/latest.log)

Version Minecraft 1.14.4
Version plugins Multiverse-Portals-4.1.0, Multiverse-Core-4.1.0

**Comment by Jadiction** [comment]
This error is not from Multiverse. You have a lot of errors going on during that startup.
