### ISSUE TITLE
Playerwhitelist

### ISSUE THREAD

**Issue by brocool27** [Multiverse/Multiverse-Core#2114]
Sorry,you can't use CLEAR with playerwhitelist Please visit our github wikli for more information.

![image](https://user-images.githubusercontent.com/53382908/66786178-115f8d00-eea5-11e9-9dc2-d57602c057b2.png)

**Comment by benwoo1110** [comment]
Wiki states that you can only clear: 

- worldblacklist
- animals
- monsters

I think playerwhitelist is a typo in the wiki or removed in a previous update by the dev.

https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#examples-19

**Comment by benwoo1110** [comment]
Ok, I removed playerwhitelist example from the documentation.
