### ISSUE TITLE
Error org.bukkit.event.entity.EntityCreatePortalEvent 

### ISSUE THREAD

**Issue by AlvarZ4** [Multiverse/Multiverse-Core#2115]
"Multiverse-Core v4.1.0-b775" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by EbonJaeger** [comment]
See #2000
