### ISSUE TITLE
Event is Deprecated. "Server performance will be affected"

### ISSUE THREAD

**Issue by kalleswe** [Multiverse/Multiverse-Core#2117]
[WARNING] [Multiverse-Core] "Multiverse-Core v2.6.0-b738" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman]. 

Even still exists in latest version 4.1:

[WARNING] [Multiverse-Core] "Multiverse-Core v4.1.0-b775" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by EbonJaeger** [comment]
See #2000.

**Comment by Drift91** [comment]
Read the line literally right below that. I almost missed it, too.
