### ISSUE TITLE
503 error on https://ci.onarandombox.com/

### ISSUE THREAD

**Issue by Drift91** [Multiverse/Multiverse-Core#2118]
When trying to access the [build server](https://ci.onarandombox.com/) I'm greeted with a 503 'Service Unavailable' error.

**Comment by sgdc3** [comment]
Unofficial mirror: https://ci.codemc.io/job/ThirdParty/job/Multiverse-Core/

**Comment by ScuroK** [comment]
will you fix it or maybe make the unofficial mirror official? :D

**Comment by sgdc3** [comment]
I can give you full admin access to a Multiverse subdirectory on my jenkins if you find difficult to maintain ci.onarandombox.com @Jadiction @dumptruckman

**Comment by sgdc3** [comment]
We can try also to import the previous builds, should be easy, i have done it several times in the past.

**Comment by jwulf** [comment]
What about maven? http://repo.onarandombox.com/content/groups/public/ is also 503.

**Comment by FernFerret** [comment]
Hrm @Rigby90 runs the ci server. Maybe he knows something about it?

**Comment by Rigby90** [comment]
> Hrm @Rigby90 runs the ci server. Maybe he knows something about it?
> 
> I realize the current dev team/community might want to move to something else, it was **ages** ago when we setup the Jenkins server, but it's kinda a cool piece of Multiverse's history to have around!

We did move to a new Jenkins & Nexus server a month or so back as I wasn't in a position to maintain it. It's currently being handled by @dumptruckman 

Hopefully he can read this and resolve?

**Comment by ScuroK** [comment]
any news?

**Comment by Rigby90** [comment]
Sorry, I did speak to @dumptruckman the other day and it did come back up, however looks like it's still not supporting SSL termination.

@ScuroK Should be resolved now, both over HTTP and HTTPS.
