### ISSUE TITLE
handlerscript on portal

### ISSUE THREAD

**Issue by Littledodger** [Multiverse/Multiverse-Core#2120]
Hi everyone,
I'm trying to execute a command when a player pass throu a portal. I found handlerscript parameter for all portals but I don't find anything about that on the MV wiki. 
Can someone help me telling me how to do for that ?

Thanks a lot :)

**Comment by Littledodger** [comment]
Nobody can help me ?

**Comment by Jadiction** [comment]
With the vanilla plugin, you cannot do this. If you'd like to make your own plugin to do this, that'd be fine.

**Comment by mistermsk** [comment]
Not really understanding this. Per what I found you can.

[](https://github.com/Multiverse/Multiverse-Portals/issues/50)

Quote by main: 

> This is implemented now. You can use the handlerscript property to assign a handler script that invokes a command when a portal is used.

[](https://github.com/Multiverse/Multiverse-Portals/issues/254)


> Yes, this is already possible with the handlerScript property of the portal. It may be somewhat complex but the details of how to write scripts are found here: http://dev.bukkit.org/server-mods/buscript/

> edit: the scripts you assign should be stored in Multiverse-Core/scripts.

[](https://dev.bukkit.org/projects/multiverse-portals/files/2428333)

> New: Added experimental 'handlerscript' property to portals, allowing a buscript script to take control over portal access.

This is where it gets tricky. It states that handler script need to be in the multiverse/scripts and they need to possibly be in 'buscripts'. I am having difficulty finding anything on buscripts and anything referencing that folder that is created by multiverse and the scripts.bin file in it.

**Comment by dumptruckman** [comment]
[Buscript](https://dev.bukkit.org/projects/buscript) is on dev.bukkit.org. There use to be forum posts on there with more information but the forum was removed. You can write the scripts in javascript and put them in the `multiverse-core/scripts` folder. Then you set the `handlerScript` property to the name of the file.

If it's just a command you can do a file with just this in it `command("kill %player%")`.
