### ISSUE TITLE
Multiverse-Import not working

### ISSUE THREAD

**Issue by emergenitro** [Multiverse/Multiverse-Core#2123]
Hello there!

So, I just created a world using /mvc Testworld normal -t flat
It showed successfully created but... when I tried to join it (using /mv tp Testworld), this shows up
[https://gyazo.com/5fb43ffad5294a3dcce8aadf89bd4a20](https://gyazo.com/5fb43ffad5294a3dcce8aadf89bd4a20) and so... I tried using /mvc Testworld normal -t flat again and this came [https://gyazo.com/7a5b963654502acbd322e3206928b672](https://gyazo.com/7a5b963654502acbd322e3206928b672) and when I tried using /mvim Testworld normal -t flat this comes [https://gyazo.com/fd64d3fa8ab46dee47edbd2279879659](https://gyazo.com/fd64d3fa8ab46dee47edbd2279879659). My log is https://mclo.gs/GaI2OA2

Please help ASAP as this is a big server and I'm working on adding Bedwars!
Thanks

**Comment by blubberdiblub** [comment]
The log you linked either isn't from the **first time** you tried to create the world or there was already a folder with the name `Testworld`. If it isn't from the first time you tried to create the world, please provide this log.

The other times you tried to create the world, you should have cleaned up / deleted the preexisting world, as the folder clearly existed, but was in a state that couldn't be loaded.
