### ISSUE TITLE
Entities can't go through nether portals.

### ISSUE THREAD

**Issue by Geeeeri** [Multiverse/Multiverse-Core#2128]
Hey there!
I am having an issue where entities are unable to go from the overworld to the nether but they can from the nether to the end. 
I'm using paper spigot's latest version and MV-Core, MV-NetherPortals, MV-Inventories. If you need any of the configuration files, I'd be more than happy to provide them.
Sadly, I was using my laptop and the video quality isn't the best but the issue is visible. 
https://streamable.com/gh6do

**Comment by Geeeeri** [comment]
This issue is still happening, perhaps the timings report might help:
https://timings.aikar.co/?id=3da2c3124b2743c58848b3a67cc4316b

I also found a small "error" message when the server is loading.
https://hastebin.com/oyadeqifub.css

**Comment by Geeeeri** [comment]
It has been 3 months. An update would be nice.

**Comment by bluelhf** [comment]
@Geeeeri The hastebin link has expired. Can you send the error again?

**Comment by Geeeeri** [comment]
Setting "allow-nether" to "false" in the server.propertise file causes this issue. I waited months for this. Thanks for the help..
