### ISSUE TITLE
First Run Time

### ISSUE THREAD

**Issue by ZEROOblivious** [Multiverse/Multiverse-Core#2129]
**It said to notify you.... so i did...**

13.11 15:01:29 [Server] INFO [Multiverse-Core] Enabling Multiverse-Core v4.1.0-b775

13.11 15:01:29 [Server] WARN [Multiverse-Core] "Multiverse-Core v4.1.0-b775" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by Remski01** [comment]
https://github.com/Multiverse/Multiverse-Core/issues/2000
