### ISSUE TITLE
error when trying to load worlds

### ISSUE THREAD

**Issue by Noodleburg** [Multiverse/Multiverse-Core#2132]
i tried to install multiverse netherportals. After that all my worlds were unloaded. I uninstalled that and restarted my server to no avail. have tried deleting the config file etc. also deleted and reinstalled worlds to no avail. here are my error files.

[Multiverse-Core] "Multiverse-Core v2.5.0-b727" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

 Nov 15 10:58 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) Nov 15 10:58 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) Nov 15 10:58 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) Nov 15 10:58 [Server] WARN at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) Nov 15 10:58 [Server] WARN at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) Nov 15 10:58 [Server] WARN at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) Nov 15 10:58 [Server] WARN at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) Nov 15 10:58 [Server] WARN at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) Nov 15 10:58 [Server] WARN at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) Nov 15 10:58 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) Nov 15 10:58 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) Nov 15 10:58 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) Nov 15 10:58 [Server] WARN at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:919) Nov 15 10:58 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) Nov 15 10:58 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) Nov 15 10:58 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) Nov 15 10:58 [Server] WARN at com.onarandombox.MultiverseCore.commands.ReloadCommand.runCommand(ReloadCommand.java:38) Nov 15 10:58 [Server] WARN at com.onarandombox.MultiverseCore.MultiverseCore.loadConfigs(MultiverseCore.java:509) Nov 15 10:58 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorldConfig(WorldManager.java:772) Nov 15 10:58 [Server] WARN at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183) Nov 15 10:58 [Server] WARN at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) Nov 15 10:58 [Server] WARN at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) Nov 15 10:58 [Server] WARN at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:67) Nov 15 10:58 [Server] WARN at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections(YamlConfiguration.java:77) Nov 15 10:58 [Server] WARN at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections(YamlConfiguration.java:79) Nov 15 10:58 [Server] WARN at org.bukkit.configuration.MemorySection.set(MemorySection.java:222) Nov 15 10:58 [Server] WARN at org.bukkit.configuration.MemorySection.set(MemorySection.java:188) Nov 15 10:58 [Server] WARN at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) Nov 15 10:58 [Server] WARN java.lang.IllegalArgumentException: Cannot set to an empty path Nov 15 10:58 [Server] INFO Noodleburg issued server command: /mvreload Nov 15 10:58 [Multicraft] Server ran command Admin Say

#  -------------------------------------------------------------------------  #
# This is the MV2 Config. If you mess it up, copy the values out              #
# delete it, and it will be regenerated. Then use the ingame interface        #
# to add your values back via the "/mv conf" command.                         #
# When in-game, simply type: "/mv conf ?" for help.                           #
# A config with explanations can be found here:                               #
# https://github.com/Multiverse/Multiverse-Core/wiki/config.yml               #
#                                                                             #
#                                                                             #
#  IMPORTANT !! IMPORTANT !! IMPORTANT !! IMPORTANT !! IMPORTANT !!IMPORTANT  #
#                                                                             #
# Do NOT delete this line from your config!!!!                                #
# ==: com.onarandombox.MultiverseCore.MultiverseCoreConfiguration             #
#                                                                             #
#  IMPORTANT !! IMPORTANT !! IMPORTANT !! IMPORTANT !! IMPORTANT !!IMPORTANT  #
#  -------------------------------------------------------------------------  #

multiverse-configuration:
  ==: com.onarandombox.MultiverseCore.MultiverseCoreConfiguration
  enforceaccess: 'false'
  prefixchat: 'true'
  prefixchatformat: '[%world%]%chat%'
  useasyncchat: 'true'
  teleportintercept: 'true'
  firstspawnoverride: 'true'
  displaypermerrors: 'true'
  globaldebug: '0'
  silentstart: 'false'
  messagecooldown: '5000'
  version: '2.9'
  firstspawnworld: world
  teleportcooldown: '1000'
  defaultportalsearch: 'false'
  portalsearchradius: '128'

**Comment by Jadiction** [comment]
This is because you are using an outdated version of Multiverse for your server version.
