### ISSUE TITLE
World Prefix gone, wont come back

### ISSUE THREAD

**Issue by Brabus453** [Multiverse/Multiverse-Core#2133]
Suddenly the world prefix in chat does not show anymore, does not come back even after reload en restart server.

checked config, and nothing changed... what could be the issue?

**Comment by Brabus453** [comment]
i just did /mvload world. now it shows world again, does this meen mv is not loading world on startup ?

**Comment by Jadiction** [comment]
Closing old ticket. You can receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
