### ISSUE TITLE
1.14.4 deprecated event.

### ISSUE THREAD

**Issue by andrewkm** [Multiverse/Multiverse-Core#2137]
1.14.4 startup.

`[19:18:09] [Server thread/WARN]: [Multiverse-Core] "Multiverse-Core v4.1.1-SNAPSHOT-b3" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].`

**Comment by EbonJaeger** [comment]
#200
