### ISSUE TITLE
Deprecated event call error. Reporting as the error requests this

### ISSUE THREAD

**Issue by hackaholic5069** [Multiverse/Multiverse-Core#2139]
[Multiverse-Core] "Multiverse-Core v4.1.0-b775" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by EbonJaeger** [comment]
#2000
