### ISSUE TITLE
Nether portas not leading to the correct world. 

### ISSUE THREAD

**Issue by jadsspt** [Multiverse/Multiverse-Core#2140]
Well I Have A world called spawn and have spawn_nether and the end,so what i've done is create a world, world_nether, verified everything but When i é ter nether portal on world i go to spawn_neter, IDK why.

**Comment by Tresswa** [comment]
Multiverse-core does not change the default minecraft portal formation, which only ties the world set defined in server.properties together. you can use multiverse-netherportals to tie together separate world sets though.

**Comment by Jadiction** [comment]
As Tresswa explained, you'll need Multiverse-NetherPortals to link nether and end worlds properly if you have more than one.
