### ISSUE TITLE
Fabric Support

### ISSUE THREAD

**Issue by Fritz-CO-KG** [Multiverse/Multiverse-Core#2142]
Well as zou can tell in the title, i'd like to ask if multiverse works with fabric-server. I'd like to install carpet mod *and* multiverse at once. Is there a way to do this? Thank you

**Comment by Fritz-CO-KG** [comment]
I apologize if this thread was created before, sorry for that

**Comment by Jadiction** [comment]
Never heard of fabric-servers. If they're not related to Bukkit/Spigot then it's unlikely to work. It's on you to test it, if it doesn't work then there's no support.

**Comment by Endstarky** [comment]
Fabric server is mod server like forge but cant operate forges mod as it has its own api. And no still there is no multiverse mod for fabric till i know but for mods like world edit u can use orbis .

**Comment by benwoo1110** [comment]
probably too far fetch atm. Basically every part of mv need a revamp for it to be considered possible for support a entirely new platform.

**Comment by Qrashi** [comment]
you're right, the easiest way to do this is by installing bungeecord (travertine is better) and running multiple fabric servers with fabricproxy installed on them. it's even better than a multiverse since can have different mods for every server.
