### ISSUE TITLE
Thread Dump error when creating new world

### ISSUE THREAD

**Issue by AmadeusTrill** [Multiverse/Multiverse-Core#2150]
I am getting a thread dump error when creating a new world

The error happens on both spigot and paper spigot
Multiverse is the only plugin installed

Minecraft 1.15.1
Multiverse-Core 4.1.0

This happens both on my personal  computer and my home server
Full error is in the hastebin link
I'd removed the chunks from the error log to test something, it did have specific chunks there though.

https://hastebin.com/voqaveqohu.md

Seems to work fine in Spigot 1.15, something may have changed in:
org.bukkit.WorldCreator.createWorld

**Comment by Jadiction** [comment]
Hastebin link expired.

It's best (way faster as we use GitHub to track bugs/suggestions) to receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
