### ISSUE TITLE
Support: Possible to prevent someone from entering a world via nether/end portals?

### ISSUE THREAD

**Issue by JasonHorkles** [Multiverse/Multiverse-Core#2151]
Is it possible to prevent someone from entering a world via nether/end portals if they don't have a perm or something? I tried negating the access perm but then it just treats the world like it's not even there. I need this so when people try to make end and nether portals in the creative plots that they can't actually go anywhere

**Comment by Jadiction** [comment]
You could prevent nether/end creation so there is no nether/end to go to.

**Comment by JasonHorkles** [comment]
I've tried a few times and got 0 responses so that's why I asked here

**Comment by Jadiction** [comment]
Do you teleport to another world's nether/end from the plot world? Use Multiverse-NetherPortals to prevent that.

**Comment by JasonHorkles** [comment]
Yes I did - and I have the NetherPortals addon but I think I might've fixed it now anyways
