### ISSUE TITLE
Game mode switched back after reentering a world

### ISSUE THREAD

**Issue by OrdosX** [Multiverse/Multiverse-Core#2154]
## What is expected
After a player changed his game mode with `/gamemode` command, his game mode remains the same when:
* The player goes to another world through a portal and then come back
* The player disconnect from the server and join in
## What happens now
The player's game mode is switched back to the world's default game mode after doing things above.
## Environments
Plugin: 4.1.0
Server: PaperMC 1.14.4 build 236
Java: OpenJDK 1.8.0_222
System: Ubuntu 18.04

**Comment by leasoncre** [comment]
i'm seeing this as well.
Steps to Reproduce: Set gamemode to creative, disconnect, reconnect and back in survival. (very troublesome if you were high up...)
It seems to be resetting force-gamemode=true (on join) but his is set to false in server.properties
NOTE: troubleshooting proved to be this mod, and it only did it on 2nd launch after all files were generated. initial (first) launch was fine.

Multiverse-Core Version: 4.1.0-b775
Server PaperMC 1.15.1 managed through AMP
Java 8u231 (build 1.8.0_231-b11)
Win 10 host VM, 64bit

**Comment by FibreL** [comment]
mv.bypass.gamemode.*

Add this permission to everyone who must stay at their desired gamemode that is not set for world in MV config. (or to their groups in your permission plugin)
Example: don't add this permission to those who can't change to another gamemode than survival if the worlds are set to survival in config.

**Comment by leasoncre** [comment]
> mv.bypass.gamemode.*
sounds good. though i'm op and it still does this. just seems odd to me that an op would require this to be expressly set.

**Comment by OrdosX** [comment]
Thanks a lot! The problem is solved using this method.
