### ISSUE TITLE
When trying to import Build Bundles. Sorry for the problem <3

### ISSUE THREAD

**Issue by Sammwy** [Multiverse/Multiverse-Core#2155]
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.Chunk.a(Chunk.java:876)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.Chunk.a(Chunk.java:851)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:434)
10.01 09:44:52 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46)
10.01 09:44:52 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
10.01 09:44:52 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
10.01 09:44:52 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
10.01 09:44:52 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:135)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:117)
10.01 09:44:52 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:145)
10.01 09:44:52 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:91)
10.01 09:44:52 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:592)
10.01 09:44:52 [Server] WARN at com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.playerCanSpawnHereSafely(SimpleBlockSafety.java:83)
10.01 09:44:52 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:419)
10.01 09:44:52 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:80)
10.01 09:44:52 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:57)
10.01 09:44:52 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:476)
10.01 09:44:52 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:268)
10.01 09:44:52 [Server] WARN at com.onarandombox.MultiverseCore.commands.ImportCommand.runCommand(ImportCommand.java:147)
10.01 09:44:52 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
10.01 09:44:52 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
10.01 09:44:52 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
10.01 09:44:52 [Server] WARN at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:916)
10.01 09:44:52 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
10.01 09:44:52 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
10.01 09:44:52 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
10.01 09:44:52 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
10.01 09:44:52 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
10.01 09:44:52 [Server] WARN at java.lang.Thread.run(Thread.java:748)
10.01 09:44:52 [Server] WARN java.lang.NullPointerException
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.WorldServer.b(WorldServer.java:580)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:455)
10.01 09:44:52 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46)
10.01 09:44:52 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
10.01 09:44:52 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
10.01 09:44:52 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
10.01 09:44:52 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:135)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:117)
10.01 09:44:52 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:145)
10.01 09:44:52 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:91)
10.01 09:44:52 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:592)
10.01 09:44:52 [Server] WARN at com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.playerCanSpawnHereSafely(SimpleBlockSafety.java:83)
10.01 09:44:52 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:419)
10.01 09:44:52 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:80)
10.01 09:44:52 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:57)
10.01 09:44:52 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:476)
10.01 09:44:52 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:268)
10.01 09:44:52 [Server] WARN at com.onarandombox.MultiverseCore.commands.ImportCommand.runCommand(ImportCommand.java:147)
10.01 09:44:52 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
10.01 09:44:52 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
10.01 09:44:52 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
10.01 09:44:52 [Server] WARN at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:916)
10.01 09:44:52 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
10.01 09:44:52 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
10.01 09:44:52 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
10.01 09:44:52 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
10.01 09:44:52 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
10.01 09:44:52 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
10.01 09:44:52 [Server] WARN at java.lang.Thread.run(Thread.java:748)`	
 WARN at com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.playerCanSpawnHereSafely(SimpleBlockSafety.java:83)
 WARN at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:419)
 WARN at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:80)
 WARN at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:57)
 WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:476)
 WARN at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:268)
 WARN at com.onarandombox.MultiverseCore.commands.ImportCommand.runCommand(ImportCommand.java:147)

**Comment by Jadiction** [comment]
Provide as much information as you can. Such as:
- Your server version
- The output link from /mv version -b
- Any errors in console that relate to Multiverse

**Comment by Jadiction** [comment]
Closing old ticket. If you still need help, it's best (way faster as we use GitHub to track bugs/suggestions) to receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
