### ISSUE TITLE
Console Warn 1.14.4

### ISSUE THREAD

**Issue by Thund3rst0rm89** [Multiverse/Multiverse-Core#2157]
>.... [16:01:07 WARN]: [Multiverse-Core] "Multiverse-Core v4.1.0-b775" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by EbonJaeger** [comment]
#2000

**Comment by Thund3rst0rm89** [comment]
sry i did'nt find it
