### ISSUE TITLE
[1.15.1] Generator set to “null” when importing world

### ISSUE THREAD

**Issue by DeleteMetaInf** [Multiverse/Multiverse-Core#2158]
I imported a skyblock world created with the plugin [Simple Skyblock](https://www.spigotmc.org/resources/simple-skyblock-1-8-x-1-15-x.72100/) using this command:
`/mv import skyblock normal SimpleSkyblock`
The world was imported just fine, but the generator was set to “null” instead of “SimpleSkyblock.” There were no errors in the console.

I changed the generator to “SimpleSkyblock” manually in worlds.yml and reloaded, and it wasn’t changed back automatically, which is good. However, I’m still unsure as to why the import command didn’t work properly.

##### Console output
```
[03:26:00 INFO]: DelMetaInf issued server command: /mv import skyblock normal SimpleSkyblock
[03:26:00 INFO]: DelMetaInf: Starting import of world 'skyblock'...
[03:26:00 INFO]: [Multiverse-Core] Loading World & Settings - 'skyblock' - Env: NORMAL - Type: null
```

### Versions
* **Minecraft:** 1.15.1
* **[PaperMC](https://papermc.io):** Build 57
* **Multiverse-Core:** 4.1.0
* **Simple Skyblock:** 1.3.6

**Comment by DeleteMetaInf** [comment]
The same happened when using [VoidGenerator](https://www.spigotmc.org/threads/voidgenerator.158472/) as the generator and _creating_ a new world.

**Comment by DeleteMetaInf** [comment]
The same happened when using [VoidGenerator](https://www.spigotmc.org/threads/voidgenerator.158472/) as the generator and _creating_ a new world.

This time, whenever I change it in the config, it’s reset back to “null.” 😕

**Comment by nicegamer7** [comment]
The correct way to create a world using a custom generator is as follows (using VoidGenerator as an example):
```
/mvc new_world NORMAL -g VoidGenerator
```
If that solves the problem for your, feel free to close this issue! If not, please let us know.

**Comment by benwoo1110** [comment]
The above explanation by nicegamer7 should fix your issue so I will be closing it. If you still have any issues, feel free to open a new issue or ask in your MV discord at https://discord.gg/NZtfKky
