### ISSUE TITLE
Inventory cleared when changing worlds. 

### ISSUE THREAD

**Issue by liscuate** [Multiverse/Multiverse-Core#2161]
Okay so i have the issue with miltiverse inventories that when a Player switches to a world the Player will of course spawn without anything but when they go back to the normal world the users loose their items that was in their inventory.

**Comment by willies952002** [comment]
Hello, I recommend including the following information to make it easier for the developers to help:

Server Software and Version - Example:
>Server Software: `Paper 1.15.2 - build 67`

Plugin List with Versions - Example:
>Plugins:
>\- `Multiverse` @ `4.1.1-SNAPSHOT-b777`
>\- `Multiverse-Inventories` @ `4.0.0-SNAPSHOT-b467`
>\- `EssentialsX` @ `2.17.1`

Link generated from `/mv version -b`

**Comment by Jadiction** [comment]
You need to setup Multiverse-Inventories properly. See the wiki here: https://github.com/Multiverse/Multiverse-Core/wiki/Basics-%28Inventories%29
