### ISSUE TITLE
Select portal material [Not frame]:Feature Request

### ISSUE THREAD

**Issue by devilx1985** [Multiverse/Multiverse-Core#2162]
Hi, 

Would be awesome if you add "end portal" material and "nether portal" material for creation of portals, the actual portal and not the frame.

**Comment by benwoo1110** [comment]
This issue will be better suited here https://github.com/Multiverse/Multiverse-Portals/issues. Also I think its related to https://github.com/Multiverse/Multiverse-Portals/issues/270
