### ISSUE TITLE
Missing dependency declaration

### ISSUE THREAD

**Issue by SlimeDog** [Multiverse/Multiverse-Core#2163]
Spigot 1.15.2 (Jenkins 2596)
Multiverse-Core 4.1.1-b777

**Description**
Beginning with Spigot 1.15.2 (Jenkins 2596), missing dependency declarations are reported in the log on server start-up as WARN messages.

Reference: [https://hub.spigotmc.org/jira/browse/SPIGOT-5546](https://hub.spigotmc.org/jira/browse/SPIGOT-5546)

The relevant log entry is:
```
[22:03:37] [Server thread/WARN]: [Multiverse-Core] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER} which is not a depend, softdepend or loadbefore of this plugin.
```

**Steps to reproduce the behavior**
- Update Spigot to 1.15.2 latest
- Start the server
- Search the log for 'Loaded class'

**Expected behavior**
Dependencies should be declared in plugin.yml

**Comment by andrewkm** [comment]
Same here.

`[Multiverse-Core] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER} which is not a depend, softdepend or loadbefore of this plugin.`

**Comment by bonjourkemal** [comment]
I'm following.

**Comment by nicegamer7** [comment]
It seems we forgot to close this. This issue is fixed in our latest CI build.

**Comment by SlimeDog** [comment]
Please check the CI server (http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/). It's been inaccessible (504 gateway error) for days.

**Comment by nicegamer7** [comment]
Thanks for letting us know, we are aware of the issue.
