### ISSUE TITLE
"Multiverse-Core v4.1.1-SNAPSHOT-b777" has registered a listener...

### ISSUE THREAD

**Issue by Zyptor** [Multiverse/Multiverse-Core#2164]
`[WARNING] [Multiverse-Core] "Multiverse-Core v4.1.1-SNAPSHOT-b777" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].`

It said to contact the authors and I didn't really know how so I hope this works.

**Comment by EbonJaeger** [comment]
#2000
