### ISSUE TITLE
When i join I dont have my stuff from before???

### ISSUE THREAD

**Issue by Tylers31** [Multiverse/Multiverse-Core#2165]
Hello, whenever i join my server with multiverse on do not have my items before. Any idea how to disable it?

**Comment by Jadiction** [comment]
Are you using Multiverse-Inventories? If not, then you should have the same items on all worlds. Otherwise, it's another plugin conflicting. 
It's best (way faster as we use GitHub to track bugs/suggestions) to receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
