### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by Relaxing9** [Multiverse/Multiverse-Core#2166]
Keep getting this spammed on different tiles, it also mentions Multiverse-Core:
Running Server Version: git-Spigot-b9baf71-512ff7a (MC: 1.15.2) 
https://pastebin.com/ipUkBrhj
(world was forceUpgraded)

**Comment by Jadiction** [comment]
What is your Multiverse version?

**Comment by Jadiction** [comment]
Closing old ticket. If you still need help, it's best (way faster as we use GitHub to track bugs/suggestions) to receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
