### ISSUE TITLE
Error with the prefix when teleported

### ISSUE THREAD

**Issue by pushuangchang** [Multiverse/Multiverse-Core#2169]
The prefix %world% didn't change when players teleported with the mod teleportation method.
Only when the command /mv tp is used can the prefix change.
Is it because some of the other plugins or mods?
the version is 2.5.0 and the game version is 1.12.2.

**Comment by Jadiction** [comment]
I haven't been able to reproduce this. Likely another plugin causing it. It shouldn't matter how you get to the other world, the prefix should change, if you actually go to that world.
