### ISSUE TITLE
/mv set spawn

### ISSUE THREAD

**Issue by cantercrow** [Multiverse/Multiverse-Core#2170]
Hi,

I have a paper spigot  server running MultiVerse-Core but for some reason the "/mv set spawn" does not work, when I issue the command it says that the spawn was set but when I come out and then back in I dont spawn to the place I set.

Do you know what to try?

**Comment by Jadiction** [comment]
Is there another plugin controlling the spawn points?

**Comment by benwoo1110** [comment]
The set spawn is for new players only, you will spawn at your last location afterwards.

**Comment by Jadiction** [comment]
Closing old ticket. If you still need help, it's best (way faster as we use GitHub to track bugs/suggestions) to receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
