### ISSUE TITLE
"your bed isn't either unset, missing or blocked"

### ISSUE THREAD

**Issue by Zaroxin** [Multiverse/Multiverse-Core#2172]
Hello I have 2 worlds "world" (for lobby with SuperLobby), "world1"(for survival). All player that enter to the server spawn in world (lobby) then they have to teleport to survival if they want to play it. I use a block command to teleport a player /mv tp @a world1 (it works, players spawn in the setspawn) But I have a problem with the spawn in world1. 
When I set a bed and die in world (lobby) I respawn in bed there is no problem at all, but when I set a bed and die in world1(survival) I respawn in the setspawn not in the home bed. I try with my OP account and it has the same problem. 

This is the config.yml for multiverse core

multiverse-configuration:
  ==: com.onarandombox.MultiverseCore.MultiverseCoreConfiguration
  enforceaccess: 'true'
  prefixchat: 'false'
  prefixchatformat: '[%world%]%chat%'
  useasyncchat: 'true'
  teleportintercept: 'true'
  firstspawnoverride: 'false'
  displaypermerrors: 'true'
  globaldebug: '0'
  silentstart: 'false'
  messagecooldown: '5000'
  version: '2.9'
  teleportcooldown: '1000'
  defaultportalsearch: 'false'
  portalsearchradius: '128'

This is for world.yml 
 world:
    ==: MVWorld
    hidden: 'false'
    alias: world
    color: WHITE
    style: NORMAL
    pvp: 'false'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'false'
    difficulty: EASY
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
      currency: '-1'
    hunger: 'false'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: -250.21057133978536
      y: 77.0
      z: 413.41544107063595
      pitch: 6.0000076
      yaw: -88.05012
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '-572866818722502127'
    generator: 'null'
    playerLimit: '-1'
    allowFlight: 'false'

world1:
    ==: MVWorld
    hidden: 'false'
    alias: ''
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'true'
    difficulty: NORMAL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
      currency: '-1'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: -150.5
      y: 64.0
      z: 146.5
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '4526019536134363146'
    generator: 'null'
    playerLimit: '-1'
    allowFlight: 'true'

There is something that I dont know if it relevant. I tried to respawnworld in the config for each world but when I restart the server it erase it.. I have essentialsX, Multiverse Core, SuperLobby, other mods but not for config just for game. Pls help

**Comment by benwoo1110** [comment]
You will need multiverse inventories to store bed spawns of non vanilla worlds (i.e. world that are not named 'world')

https://dev.bukkit.org/projects/multiverse-inventories

**Comment by Jadiction** [comment]
Closing old ticket. If you still need help, it's best (way faster as we use GitHub to track bugs/suggestions) to receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
