### ISSUE TITLE
I can't change the weather beyond the major world_(:з」∠)_

### ISSUE THREAD

**Issue by ASTRAYRMOR** [Multiverse/Multiverse-Core#2173]
Why I can't change the weather beyond the major world, neither /weather nor /mvm set weather

**Comment by benwoo1110** [comment]
Ensure that your MV-core version is compatible with your server version. https://dev.bukkit.org/projects/multiverse-core/files

**Comment by Jadiction** [comment]
Closing old ticket. If you still need help, it's best (way faster as we use GitHub to track bugs/suggestions) to receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
