### ISSUE TITLE
Upgraded from 1.13 to 1.15 no bamboos or hives

### ISSUE THREAD

**Issue by Darkweasam** [Multiverse/Multiverse-Core#2176]
Hello,

I just updated from 1.13 to 1.15 and updated the plugin to the latest version, though uppon NEW world generation, there are no bamboos or hives spawning at all, even when I use a seed that has a bee hive right at spawn, the hive is just not there

Any idea?

**Comment by Jadiction** [comment]
As far as I'm aware, MV uses bukkit's API to generate new worlds unless generators are used then it's on the generator, so this shouldn't be an MV issue.
