### ISSUE TITLE
 [ERROR ]The world could NOT be loaded because it contains errors and is probably corrupt!

### ISSUE THREAD

**Issue by lnCraf** [Multiverse/Multiverse-Core#2178]
I am getting this error when loading my server, but my worlds are not corrupted. When trying to tp from World A to World B, it fails, as "/mv list" says World B is "unloaded." But when I restart and choose World B as the default world for my server, it loads fine and is not corrupted.

Any idea what the issue is?

**Comment by Jadiction** [comment]
Do you have autoload enabled for World B?

**Comment by mandatoryoption** [comment]
Check your world file permissions and make sure you have ownership

**Comment by Jadiction** [comment]
Closing old ticket. As mentioned before, If you still need help, it's best (way faster as we use GitHub to track bugs/suggestions) to receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
