### ISSUE TITLE
Can't Go To Nether After Restarting Server?

### ISSUE THREAD

**Issue by Wizirdi** [Multiverse/Multiverse-Core#2180]
So when you first create a new world and it's nether world, you can goto the nether just fine.

After you restart the server, it will say "previous world is null" when you try to goto the nether.

If I create a new world/nether it'll work fine, then once I restart, same thing.

The nether ONLY works consistently in the main world that everyone starts in.

I'm using mvc, mvi and mvnp
Any thoughts?

**Comment by Jadiction** [comment]
Related to #2028 
Plugin cause is LobbyAPI.
