### ISSUE TITLE
Nether portal problems

### ISSUE THREAD

**Issue by kolya5544** [Multiverse/Multiverse-Core#2181]
Hello! I am running 1.14.4 server, and for some reasons I can't use nether portals!

Unless I make it using Multiverse-Portals, they don't work. I am talking about default, SP-like obsidian+flint and steel portals.

I linked the worlds, loaded them both, but whenever I go in the portal it just never actually teleports me. Nothing is shown in the console and debug gives no information why it happens. I am OPped and given * using PEX. Both Multiverse Core and Multiverse NetherPortal are latest available versions (4.1.0)

Plugins: https://pastebin.com/jPLhpCyL
![image](https://user-images.githubusercontent.com/20096248/75111182-e998e680-5647-11ea-82a8-794856defb19.png)

**Comment by Jadiction** [comment]
Do you have several overworlds & nethers? If so you need MV-NetherPortals. Otherwise, ensure your nether is generated. You may have other plugins denying teleportation there.

**Comment by kolya5544** [comment]
Hello! The problem was that I also had plugin WarpPortals! Sorry! Removing WarpPortals helped.
