### ISSUE TITLE
World Gamemode Often Being Ignored

### ISSUE THREAD

**Issue by TheVillain14** [Multiverse/Multiverse-Core#2182]
I have a creative world in my server. When users go through the portal to enter the world, they are (quite commonly) going through the portal and remaining in survival mode. Then, upon re-entering the same portal a second time, they will then turn Creative. Default gamemode is survival, creative world gamemode is creative. They do not have bypass. 2nd time going through the portal does what it should do the first time. Asking them to go through again isn't too bad, however it will cause problems when there are no people who are aware online. Also, I fear the reverse could happen (which would be more problematic) in that someone could return to a survival world still in creative mode. Any solutions?

**Comment by Jadiction** [comment]
I've encountered something similar to this that may be the same issue, issue found here: #2171 
Ensure you don't have something such as WorldGuard (for example a __global__ flag) changing your gamemode.

**Comment by Jadiction** [comment]
Closing old ticket. If you still need assistance, it's best (way faster as we use GitHub to track bugs/suggestions) to receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
