### ISSUE TITLE
When I Use /mvtp @p , It Doesn't work. It Show An Error Message: Sorry , I couldn't Find Player: @p. Please Help Me Fix This. 

### ISSUE THREAD

**Issue by ThatsCloseEnough123** [Multiverse/Multiverse-Core#2185]
.

**Comment by Jadiction** [comment]
You were never supposed to be able to use `@p` in plugin commands, and Multiverse has never supported it directly. Apparently, it was a "bug" in Spigot.

**Comment by ShahabShahid01** [comment]
What would I use then?

**Comment by Jadiction** [comment]
You would just do `/mvtp <player name>`. If you need it to perform on the player using it, use a placeholder or variable provided by the plugin(s).

**Comment by tokigamer1** [comment]
give me commond how to connect znpcs to other world
