### ISSUE TITLE
autoload not working

### ISSUE THREAD

**Issue by OT5x** [Multiverse/Multiverse-Core#2188]
I've run the command /mvm set autoload true but when I do it says it worked but it didn't autoload is enabled in the config but every time I have to import the worlds myself.

**Comment by benwoo1110** [comment]
Autoload is for worlds that are already imported to be loaded on server startup. You still have to /mv import <world> <type> to import new worlds.

**Comment by rollerproCG** [comment]
Yup! This has been bugging me for so long. I really want this to be solved. To elaborate a bit on what was said, Auto Load just straight up does not work. I currently run a 1.12.2 server and no matter what I do to set autoload to true, I have to MANUALLY load each and every world every time I restart. This conflicts with plugins so it ain't ideal.

**Comment by benwoo1110** [comment]
did you set keep-spawn-in-memory to true?

**Comment by benwoo1110** [comment]
look at #2203

**Comment by OT5x** [comment]
I actually fixed this a long time ago. Turns out that I installed the wrong version, I feel so stupid I must have just clicked download without even looking at the version.
