### ISSUE TITLE
Multiverse v4.1.0 console warning

### ISSUE THREAD

**Issue by YumiBloody** [Multiverse/Multiverse-Core#2189]
i runned your plugin in spigot minecraft server, version 1.15.2 and this showed up:

[WARNING] .... [Multiverse-Core] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.2-b107 which is not a depend, softdepend or loadbefore of this plugin.

[WARNING] .... [Multiverse-Core] "Multiverse-Core v4.1.0-b775" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

[WARNING] .... [Multiverse-Core] Cannot load worlds.yml 

it says "please notify the authors, i think that you are the authors or you know them.

btw, thanks and sorry for my bad english

**Comment by Muspah** [comment]
See #2000
