### ISSUE TITLE
Multiverse-Core, new listener

### ISSUE THREAD

**Issue by bambinidk** [Multiverse/Multiverse-Core#2190]
When I started my server up last time, the server console error appears like this:

[Multiverse-Core] "Multiverse-Core v4.1.0-b775" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

___________________________
Server version: Spigot-1.14.4 (Build: R0.1-SNAPSHOT)
Plugin version: v4.1.0-b775
Plugin: Multiverse-Core

**Comment by Muspah** [comment]
See #2000;
