### ISSUE TITLE
Warn on startup

### ISSUE THREAD

**Issue by BraAnansi** [Multiverse/Multiverse-Core#2192]
I just put multiverse into my server and started it up, getting a warn saying I should contact people. Not sure if this has been seen before, or if someone could help clear this up.

`WARN "Multiverse-Core v2.5-b719" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--].`

**Comment by Muspah** [comment]
See #2000
