### ISSUE TITLE
MVTP with command blocks in 1.15.2

### ISSUE THREAD

**Issue by Adyox** [Multiverse/Multiverse-Core#2194]
I installed Multiverse-Core recently and encountered a small problem.
I created two worlds. What I wanted at the beginning was to be able to TP myself in the second world from the first one thanks to a command block.
The problem is that I can't find which command is used for this.
I had succeeded in 1.8 thanks to : /mvtp @p world
But in 1.15 I don't think so.

**Comment by Jadiction** [comment]
As far as I'm aware, MV doesn't do anything to command blocks, so any command block issues/behavior is based on your server software (bukkit, spigot, paper etc).
As for the @ selectors, I don't believe they were intentional and are "removed" in later versions. I could be wrong about this part.
