### ISSUE TITLE
[API usage] How can I import this plugin to my Spigot plugin Maven settings?

### ISSUE THREAD

**Issue by Polda18** [Multiverse/Multiverse-Core#2196]
Hi. I am intending to use Multiverse core plugin API in my own Spigot plugin I am making for our server. It is a minigame plugin, only private plugin, with no publication intended (yet). I am thinking of using Multiverse plugin for creating game template worlds (also reffered to as "maps") and of course creating a temporary game world for an actual game. I am in fact creating more plugins, every single plugin is going to use Multiverse.

How can I import the Multiverse API to my plugin using Maven without having to rely on my local repository (which can change, thus requiring to change the JAR location on my disk - it also doesn't solve for external disk usage, though it could be resolved by using relative paths). I'd like to use stable release (no snapshots), which is currently version 4.1. Is it somewhere in Maven repository I can pull it out?

**Comment by Jadiction** [comment]
The best information for this will be in the #dev-chat on the [Multiverse Discord](https://discord.gg/NZtfKky). Dumptruckman will likely reply when he has time.
