### ISSUE TITLE
World import error in 1.15.2

### ISSUE THREAD

**Issue by Macintosh-Fan** [Multiverse/Multiverse-Core#2197]
I add a map to the server folder and imported but it did not work. 
![image](https://user-images.githubusercontent.com/50642934/77258736-d1fa5100-6c39-11ea-888c-d6f6bc5bb70b.jpg)
![image](https://user-images.githubusercontent.com/50642934/77258743-dd4d7c80-6c39-11ea-9982-0cdc0edd6fa8.jpg)

**Comment by Macintosh-Fan** [comment]
![image](https://user-images.githubusercontent.com/50642934/77258781-15ed5600-6c3a-11ea-9b0d-b27ddbd7e3c9.jpg)
![image](https://user-images.githubusercontent.com/50642934/77258807-36b5ab80-6c3a-11ea-8b5e-707276e61d3c.jpg)

**Comment by Macintosh-Fan** [comment]
Never mind, had to load a world in single player. Then import to multiplayer

**Comment by Icebluewolf** [comment]
@Macintosh-Fan what exactly do you mean? Did you have to put the world in .minecraft/saves. load it, copy it from .minecraft/saves   , than put it in the server?

**Comment by Macintosh-Fan** [comment]
@Icebluewolf Yes. Multiverse should be able to run this itself without me having to do the Minecraft saves import and then copy and all of that. It is a bug that has yet to be fixed.
