### ISSUE TITLE
[Suggestion] MultiVerse Chat Extension

### ISSUE THREAD

**Issue by JCOnlin3** [Multiverse/Multiverse-Core#2199]
I've been scouring the internet for a plugin that can control chat per world how I would like it to, but am failing to find anything othat than local/global chat.
I already use Multiverse Core and Inventories, so if I can keep as much of it within Multiverse as possible, it would makes my life, and i imagine others admins lives so much easier.

I wonder if this would be good to have as another branch of Multiverse > Multiverse Chat

Essentially, I'm looking for per-world chat, with the ability to talk globally given they have the permission, and a toggleable admin mode that shows all chat across worlds.

There are a number of permissions and configs that I think could make this suggested plugin very flexible and useful.

**Chat Format - Configurable**
[(mv world alias)] (Existing format) (message)
i.e. [Survival] {Admin} JCOnline >> Hello Survival!

[Global] (Existing Format) (message)
i.e. [Global] {Admin} JCOnline >> Hello World!

**Commands**
_(Message)_ - (Default) Send message to current world only.
_!(Message)_ - Sends message globally (Prefix can be configured).
_/mvchat global <on/off>_ - Allows user to toggle speaking in global by default.
_/mvchat admin <on/off>_ - Allows user to toggle viewing all worlds chats.
_/mvchat (world) (message)_ - Allows user to send message to a specific world.

**Permissions**
_- mv.chat.world.(worldname)/(*)_ > Permits users to chat in specific worlds, and if they lack permission have a configurable message stating so.
_- mv.chat.global_ > Allows user to talk globally across the server in all worlds.
_- mv.chat.global.toggle_ > Allows users to toggle speaking globally by default.
_- mv.chat.admin_ > Allows users to toggle viewing chat across all worlds for moderation.
_- mv.chat.admin.world_ > Allows users to send a message to a specific world if they are not in it for moderation purposes.

This is something i've been looking for for a while now and am struggling to find plugins that are either up to date, or cover the diversity in the configs for per-world usage.

**Comment by benwoo1110** [comment]
I believe there is already various plugins that does the above mentioned features. Some include Chatcontrol, Chat Manager and Venturechat.

https://www.spigotmc.org/resources/chatcontrol%E2%84%A2-the-ultimate-chat-plugin-500-000-downloads-1-2-5-1-15-2.271/
https://www.spigotmc.org/resources/chat-manager-1-7-1-15-with-30-features-and-40-commands.52245/
https://www.spigotmc.org/resources/venturechat.771/

**Comment by benwoo1110** [comment]
As mention, there are already many great alternatives, so I don't see MV implementing this.

**Comment by pcboii** [comment]
Would be nice to have this in the same family/eco-system of plugins.
