### ISSUE TITLE
Confused about nether portals

### ISSUE THREAD

**Issue by emanuele3d** [Multiverse/Multiverse-Core#2200]
Hi there, and thank you for the Multiverse family of plugins. 

I am using them to setup a family-friendly MC server for my neighbourhood. There are a lot of children around here who are used to play together, but with the Coronavirus epidemic they might soon have to stay home the whole time. I am hoping the possibility to play together in minecraft will give them a chance to lift their spirits if they start going stir-crazy at home. =)

I am a little confused about portals, but I am not sure if this is relevant to the Multiverse-Portals plugin or the Multiverse-Nether-Portals pluging, which is why I write here.

**The fundamental question is: can I have two parallel -sets- of overworld/nether/end worlds, configured one as creative/peaceful and the other as survival/easy? And can they be connected by vanilla-type mechanics from the user point of view?**

The creation of the two sets of world is not a problem, `/mv list` currently gives me:
- Creative_End - THE_END
- Survival_nether - NETHER
- Creative_Nether - NETHER
- Superflat -  NORMAL
- Survival - NORMAL
- Survival_end - THE_END
- Creative - NORMAL
- [H]jail - NORMAL

The Creative set of worlds is correctly connected together: they are the original Spigot 1.14.4 worlds generated through the hosting interface and aliased with Multiverse commands.
The Superflat world and the Survival overworld are both bidirectionally connected to the Creative
overworld via Multiverse portals. I am using LuckPerm and the portal permissions are working like a charm, so that I can limit younger children to the Creative and Superflat worlds.

However, if I create a Nether Portal in the Survival overworld, it leads me to `Creative_Nether` instead of `Survival_nether`. 

But I thought multiverse wired the nether and end worlds to overworlds according to suffix?

**Comment by nicegamer7** [comment]
I believe you need Multiverse-NetherPortals to correctly link nether portals (it also does end portals).

Also, I think it's awesome you're doing this! Hopefully, they have fun with it :)

**Comment by emanuele3d** [comment]
Hi @nicegamer7 , thank you for your suggestion. I did as you suggested and so far it seems to work! Thank you again!
