### ISSUE TITLE
TravelAgent and 1.15

### ISSUE THREAD

**Issue by nicegamer7** [Multiverse/Multiverse-Core#2202]
1.15 still doesn't have TravelAgent, however, the methods are now implemented in PlayerPortalEvent. So we should update the MVPlayerListener to support that.

I'll see if I can open a pull request for this.

**Comment by benwoo1110** [comment]
Should be added 5.0.0 Release Milestone #2418

**Comment by nicegamer7** [comment]
Should've been closed by #2580.
