### ISSUE TITLE
Auto load DOES NOT work, at least in 1.12.2

### ISSUE THREAD

**Issue by rollerproCG** [Multiverse/Multiverse-Core#2203]
I was searching for issues on this and found just one other which was marked as "can't reproduce". Well, if you still can't find out what's up, I can give you any info that you need. No matter what I do to set autoload to true, not a single world in multiverse loads on a server startup. Not even the main world! Sure, I spawn in the main world, but multiverse thinks it hasn't even loaded yet! This conflicts with several plugins that rely on other worlds being loaded. The only option has been to manually reload each and every world on a restart, which is tedious and messes up certain plugins unless I do a /reload, which is NOT ideal. Please look into this as it is probably the biggest thing holding my server back at the moment. I can't use valuable plugins because they disable /reload, and I "need" that right now.

**Comment by benwoo1110** [comment]
Are you using multiverse core `version 2.5.0`?

**Comment by rollerproCG** [comment]
Oh my goodness I can't believe it was that simple! I was using the latest version of multiverse core, so when I got 2.5, it works. If anyone else ever has this issue, don't be like me. Make sure you are using the correct version.
