### ISSUE TITLE
I cannot import flat world

### ISSUE THREAD

**Issue by Fattoush** [Multiverse/Multiverse-Core#2205]
Despite using the _/mv import Wor normal -t flat_ or even _/mv import Wor normal -g flat_ or _/mv import Wor normal_ or _/mv import Wor normal flat_ commands, I can't import flat type world, because every world I import is normal type. (Wor is name of my world I wanna import)

**Comment by benwoo1110** [comment]
1. Try /mv import Wor FLAT
2. Ensure that the version of MV-core is compatible with your server version.

**Comment by Fattoush** [comment]
It doesn't work because it's not a world environment. I use the latest version of MultiVerse - 4.1.0, which is for 1.15, which I use on my server (Spigot 1.15.2) so everything is fine here.
![2020-03-28_21 42 28](https://user-images.githubusercontent.com/55689170/77833440-9bdb3680-713d-11ea-93e5-d92afdd262dd.png)

**Comment by benwoo1110** [comment]
Is your world you importing the same version as your server? (I.e. your world is generated on 1.15.2 version)

Try `/mv create flat_world NORMAL -t FLAT` with caps

**Comment by Fattoush** [comment]
The map I want to upload is 5 years ago, but I've previously uploaded other schemes or maps from so many years ago. Now, for the first time, I'm uploading a map with a super flat generator and I noticed an error. I checked the command you entered, but it still doesn't work. Creates a normal world.

**Comment by benwoo1110** [comment]
If its 5 years ago, assume its around version 1.8. 

You need to convert the world using single player first.

1. Open the world in 1.8
2. open it in 1.12
3. Open it in 1.13
4. Open it in 1.15.2

(My guess is the issue is with 1.12 to 1.13 there is a major change in items id)
