### ISSUE TITLE
stuck in a world

### ISSUE THREAD

**Issue by thom57696** [Multiverse/Multiverse-Core#2207]
I have a problem with multiverse when I create a world and tp me it works but when I want to return to my home world it does not work

[url=https://www.noelshack.com/2020-14-1-1585551049-2020-03-29-23-31-55.png][img]https://image.noelshack.com/minis/2020/14/1/1585551049-2020-03-29-23-31-55.png[/img][/url]

[url=https://www.noelshack.com/2020-14-1-1585551049-2020-03-29-23-31-55.png][img]https://image.noelshack.com/minis/2020/14/1/1585551049-2020-03-29-23-31-55.png[/img][/url]

**Comment by benwoo1110** [comment]
I am not very sure is world names with spaces is supported, doesnt look like it is. Can you try creating 2 worlds with no spaces in its name and see if you can teleport between them?

If possible, then you will have to bakcup, remove, rename, then reimport your worlds without space.

**Comment by Jadiction** [comment]
It's best (way faster as we use GitHub to track bugs/suggestions) to receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
