### ISSUE TITLE
[Feature Request]Beds and respawning

### ISSUE THREAD

**Issue by imaxorz** [Multiverse/Multiverse-Core#221]
Currently in the config you can chose what world you re-spawn in, for each world on the server. However if you set "bedrespawn: true" those settings no longer apply and you will always respawn either in your bed or in the spawn of the main world (if you don't have a bed set)

Would it be possible to add a feature so you can have both options? Meaning the plugin first checks if you have a bed set, if you do then you respawn in your bed, if you don't then it checks "respawnworld: " setting.

Even more useful would be if you can have a different bed in a different world. Meaning if you have a bed set in worldA, you respawn in that bed when you die in WorldA. If you have a bed set WorldB, you respawn in that bed when you die in WorldB. Not sure if this would be possible though.

Thank you.

**Comment by DearFox** [comment]
It seems that I will encounter the same error on version 1.16.5
