### ISSUE TITLE
/mv isn't showing anything but i have multiverse installed

### ISSUE THREAD

**Issue by DarthPlague1s** [Multiverse/Multiverse-Core#2211]
![image](https://user-images.githubusercontent.com/63123147/78396284-02050500-75e7-11ea-8d5b-b806a3ca00c3.png)

I am in my multiverse here and you can see /mv doesn't work

**Comment by benwoo1110** [comment]
Check your server log for mv plugin errors. Also check that the mv version you using is compatible with your server version.

**Comment by Jadiction** [comment]
Closing old ticket. If you still need help, it's best (way faster as we use GitHub to track bugs/suggestions) to receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
