### ISSUE TITLE
Can't stop wandering traders from spawning.

### ISSUE THREAD

**Issue by Phr3d13** [Multiverse/Multiverse-Core#2216]
I'm trying to set up a custom portal/hub world. Have monster spawning set to false, as well as animal spawning. Can't figure out where to look to stop wandering traders from spawning too...

**Comment by benwoo1110** [comment]
My guess is mv didnt update for spawn configs to control spawning of wandering traders. A work around will be to use worldguard regions (another plugin) to disable mob spawning.

**Comment by benwoo1110** [comment]
Wandering traders and villager are not included in MV spawning settings. I will tag this to a possible suggestion. However, plugins like worldguard already have such a feature.

**Comment by fulto7** [comment]
I before I create the world, I go into where it says "Rules" then I go down to where it says "Mob Spawning" and set the option to false, when the wandering trader eventually
comes to you, just get a nametag, name the wandering trader and it's llamas a random name, and then tp to a remote location near the world boarder, make a little room for them at bedrock level then /tp @e (player name) to your location. Problem solved!
![Screen Shot 2020-10-01 at 4 12 50 PM](https://user-images.githubusercontent.com/37345295/94858545-3116fa80-0401-11eb-9ad7-8c767102a957.png)

**Comment by benwoo1110** [comment]
Closing as it similar to #1845
