### ISSUE TITLE
registered listener 

### ISSUE THREAD

**Issue by xnxanatorx** [Multiverse/Multiverse-Core#2218]
09.04 02:49:23 [Server] Server thread/WARN [Multiverse-Core] "Multiverse-Core v4.1.0-b775" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by benwoo1110** [comment]
See #2000

This is not a bug or issue.
