### ISSUE TITLE
Multiverse wont let my server start on java 14

### ISSUE THREAD

**Issue by lukeeexd** [Multiverse/Multiverse-Core#2219]
Hi, 

Using java 14 the server starts up then stops. I found out through binary search that the issue is with multiverse. I deleted multiverse folder and it started fine, however when I imported a world it crashes, then starting up the server again it boots then shuts down. Here is what it put out https://paste.tws.gg/?08eb8469e5fc67de#CcXb99DwqRVbd3z9BUEykiJJSvmcTtESrRaLavVJptsn

**Comment by benwoo1110** [comment]
The error looks like its from EpicWorldGenerator. Another thing to note is that minecraft only officially support java 8. Although java 14 is backwards compatible, it may not be 100%.

**Comment by lukeeexd** [comment]
> The error looks like its from EpicWorldGenerator. Another thing to note is that minecraft only officially support java 8. Although java 14 is backwards compatible, it may not be 100%.

Hi, thanks for the reply. Java 11,13 and 14 all work with minecraft. Infact ZGC is the best with java 14. I use it on another server, I'll make an issue with EWG too.

**Comment by benwoo1110** [comment]
Yes, as i mentioned Java 11,13 and 14 are all backwards compatible with java 8. But minecraft and plugins for it is coded and built based on java 7/8, and may not compatible with newer versions of Java 11,13 and 14, bcu is highly dependent on how they are programmed. In mv's case (and most plugins), it is only tested for java 8 (sometimes 7) support.

**Comment by nicegamer7** [comment]
Are you still getting the error? If so, can you post your log once again?

**Comment by nicegamer7** [comment]
I'm going to close this due to inactivity and because #2279 was merged. Feel free to open a new issue if needed.
