### ISSUE TITLE
My nether portal on my survival world leads to a flat world?

### ISSUE THREAD

**Issue by LeoIce06** [Multiverse/Multiverse-Core#2222]
My nether portal on my survival world leads to a flat world? When players enter the nether the enter normally but when they go back through the portal they end up at a flat world?

**Comment by benwoo1110** [comment]
Please install mv-netherportals here: https://dev.bukkit.org/projects/multiverse-netherportals/files

Learn how nether portals are linked using mv-netherportals here: https://github.com/Multiverse/Multiverse-Core/wiki/Basics-(NetherPortals)

**Comment by benwoo1110** [comment]
Will be closing this. If you still have issues, feel free to open a new issue or come to our discord at https://discord.gg/NZtfKky. Thanks!
