### ISSUE TITLE
What is "VERSION_1_1" in the world type. 

### ISSUE THREAD

**Issue by AgentShield233** [Multiverse/Multiverse-Core#2223]

**Comment by benwoo1110** [comment]
Please provide more description/explanation of your issue, thanks!

**Comment by AgentShield233** [comment]
Yes, ok.
I and my friends are trying to create a skyblock on our server. We want our Nether to be a buffet (floating Islands) nether biome world. This is super easy to create, but when you /mvimport it, It changes to a normal (nether) world. 
So I want to know what VERSION_1_1 in the Type for /mvcreate and /mvimport. 
I'm ok with creating a new Nether floating islands world with the multiverse plugin, but I can't do a buffet world. So I wanted to know what the VERSION_1_1 so I can see if that will work.

**Comment by benwoo1110** [comment]
If you want skyblocks, you will need to get a custom world generator plugin like this: https://www.spigotmc.org/resources/bentobox-skyblock-acidisland-skygrid-caveblock.73261/

using /mvcreate with custom generators: https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#create-command

**Comment by benwoo1110** [comment]
Will be closing this. If you still have issues, feel free to open a new issue or come to our discord at https://discord.gg/NZtfKky. Thanks!

**Comment by CDWimmer** [comment]
I have the same question. 
On doing /mv env I get this list. What in the world is `VERSION_1_1 ?

![image](https://user-images.githubusercontent.com/31413434/114608984-2da8d980-9c96-11eb-83d1-5fe397d56354.png)

**Comment by benwoo1110** [comment]
It’s something you ask spigot dev. It’s already removed on 1.16. My guess it’s some legacy thing.

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/WorldType.html
