### ISSUE TITLE
Explosions

### ISSUE THREAD

**Issue by goldenkuky209** [Multiverse/Multiverse-Core#2225]
Creepers and TNT break blocks even if in WorldGuard or claimed land.

**Comment by benwoo1110** [comment]
You will have to check that your plugins are not blocking Creepers and TNT break blocks. MV does not have an feature to block or prevent these. 

Try looking into WorldGuard and/or claimed land plugin that you have. If you have essentials protect and essentials antibuild, also look into those plugin stopping your above mentioned action. 

You can try removing all plugins other than mv to test.

**Comment by benwoo1110** [comment]
Closing this as its most likely unrelated to MV. If you are still facing issues, feel free to open a new issue or come to our discord at  https://discord.gg/NZtfKky
