### ISSUE TITLE
Farms not working in an imported world

### ISSUE THREAD

**Issue by Macin1** [Multiverse/Multiverse-Core#2228]
Hi, all the farms I had in a world I imported are not working. This includes, iron golem farm and zero tick farms. Also imported villagers do not find their beds and working stations. All of this was working on a separate server with only one world. Do you know what causes this and how to fix it?

**Comment by benwoo1110** [comment]
1. Are the worlds generated from the same version as your server version?
2. What server and mv version are you using?
3. possibly others plugins or papermc have option to prevent 0 tick farms and other gameplay behaviour as well.

**Comment by benwoo1110** [comment]
Closing this due to the lack of information. If you are still facing issue feel free to open a new issue following the issue template and detailing the pointers I stated above. You can also join our discord at https://discord.gg/NZtfKky
