### ISSUE TITLE
2nd Nether portal links to first?

### ISSUE THREAD

**Issue by mngyuan** [Multiverse/Multiverse-Core#2229]
Steps to reproduce
---
1) Build two portals in `world` more than 1024 blocks away from each other
2) Enter portal 1
3) Portal generates in `world_nether`, return to `world`
4) Enter portal 2

Expected
---
5) A second portal generates in `world_nether`

Actual
---
5) Portal 2 takes me to portal 1's counterpart in `world_nether`

Setup
---
spigot-1.14.4
Multiverse-Core
Multiverse-NetherPortals
dynmap

**Comment by benwoo1110** [comment]
1. Ensure all your mv plugins are the latest form bukkit.
2. Try Stop your server, then In mv config.yml set `defaultportalsearch: ‘true’` and start your server again

**Comment by mngyuan** [comment]
updated Multiverse-Core and Multiverse-NetherPortals from 4.0 to 4.1 and tried with `defaultportalsearch: ‘true’` and `defaultportalsearch: ‘false’`, still not working

**Comment by mngyuan** [comment]
alright, went really far and successfully got a new set of nether portals linked to each other. not sure why the `defaultportalsearch` and `portalsearchradius` variables don't seem to work. Also seems to work better if I move in the nether and build my initial portal there instead of in the overworld. I think the original issue was because even though I was >1024 blocks away (~1100) in the overworld there wasn't a valid place to put a portal in the nether >128 blocks away from my original portal.
