### ISSUE TITLE
Lighting not loading in The End

### ISSUE THREAD

**Issue by etpof** [Multiverse/Multiverse-Core#2231]
Here's what The End looks like on my server:
![bug](https://user-images.githubusercontent.com/13365820/79783623-ed2ab000-830e-11ea-8138-d38e4ed3e22e.png)

Latest server log:
https://pastebin.com/niCmx9Uz

mv version -b output:
https://pastebin.com/yvM23PwN

worlds.yml:
https://pastebin.com/QfSMkefS

Multiverse-Core is the only plugin I have. Removing it restores lighting to The End, so I can confirm that it is the cause of the bug. I'm running version 2.5.0 (I've tried versions from 2.4 to 2.5) on a Thermos 1.7.10 server. I understand that it is an older build and I'm not sure if you guys can help with running Thermos, but I'd really appreciate any suggestions because I can't find any info on errors like this on the internet.

I read in #1649 that 

> If you load a world and it immediately unloads then something is probably wrong with the world.

and I noticed that DIM1 unloads as soon as the server starts in my case. I've created new End dimensions with /mv create, but they all are dark, too. I've tried using Cauldron, KCauldron, and Thermos, but all of them yield the same bug. I'm not running any mods yet either, so that shouldn't be the issue.

I also tried using Multiworld instead, and that plugin loads The End with lighting, but I think I'd prefer to use Multiverse, if at all possible, because it's just a much better plugin lol.

**Comment by benwoo1110** [comment]
Unfortunately Thermos is not a version that we support as it is a very old version of Minecraft and is a bukkit+forge hack server. These cause various bugs to arise by the server software itself. I'd suggest you contact Thermos about this world lighting issue.
