### ISSUE TITLE
[Question] World colour name

### ISSUE THREAD

**Issue by Macintosh-Fan** [Multiverse/Multiverse-Core#2232]
I have the end dimension and idk what the colour name is for **&5**...
What is the colour name?
Example: &c = RED

**Comment by benwoo1110** [comment]
For mv colour codes: https://minecraft.tools/en/color-code.php

To set worldname alias of different colours: https://github.com/Multiverse/Multiverse-Core/wiki/World-properties#alias

**Comment by Macintosh-Fan** [comment]
Thanks!
