### ISSUE TITLE
zombie villagers spawn even though I turned them off

### ISSUE THREAD

**Issue by Alv5ro** [Multiverse/Multiverse-Core#2237]
I believe that I turned zombie villagers from spawning off, however the still spawn in my world. Am I doing it wrong or is this a bug? I even tried "zombievillager" but that didn't work either

    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: [villager]
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: [zombie_villager]

**Comment by benwoo1110** [comment]
closing as its similar to #1845
