### ISSUE TITLE
gamemodes dont work

### ISSUE THREAD

**Issue by stikosek** [Multiverse/Multiverse-Core#2240]
so i have a creative world and i need to set the gamemode to creative for that world
but i cant i tried /defaultgamemode it didnt work then i tried to set the gamemode in the worlds.yml 
file it didnt work ether so i think its a bug so please help 

thanks
(by the way no errors in the console)

**Comment by benwoo1110** [comment]
Take a look at the commands used to set gamemode: https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#modify-command-set


In short, it should be `/mvm set gamemode creative WORLDNAME`

**Comment by benwoo1110** [comment]
Another thing to add is to Ensure you don’t have `mv.bypass.gamemode.NAME` permission or other plugins like WorldGuard altering the gamemode.

**Comment by stikosek** [comment]
> Take a look at the commands used to set gamemode: https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#modify-command-set
> 
> In short, it should be `/mvm set gamemode creative WORLDNAME`

thanks i will try that

**Comment by stikosek** [comment]
> Another thing to add is to Ensure you don’t have `mv.bypass.gamemode.NAME` permission or other plugins like WorldGuard altering the gamemode.

Thanks it worked!
