### ISSUE TITLE
Server Dosen't start because of MV2

### ISSUE THREAD

**Issue by EgZiG** [Multiverse/Multiverse-Core#2241]
STARTUP LOG - https://pastebin.com/E74MrsZh
Look at the last 5 lines of log

My server won't start now

**Comment by benwoo1110** [comment]
see #2000 this issue will not cause a server shutdown. From your log this is the only error:
```
furhat's ability to change his face and match his voice to the face intriguing. This ability made furhat more human-like which gives people a sense of comfort when interacting with it. 
```

If your server still cant start, I suggest you send a full startup log, including the full startup as well as crash/shutdown process.

**Comment by EgZiG** [comment]
it wasnt crash, my server was normallt as everyday restrting and ...

**Comment by benwoo1110** [comment]
As I already mention, the warn will not effect the server performance, if there isn't any crash due to other reason, there is nothing you need to worry about. Thanks!

**Comment by EgZiG** [comment]
yes , but my server won;t start now, and I want to play

**Comment by benwoo1110** [comment]
If you server wont start, please send a full startup log, including the full startup as well as shutdown process. The log you sent previously only showed half the startup, I will need the full one to help you diagnose the issue.

**Comment by EgZiG** [comment]
there was no information for server stopping in console , its reallt wierd , because there alsways were information in console
 when i shut down server , nothing happens in console

**Comment by benwoo1110** [comment]
The only way I can help you is if you show me your full server log. You should be able you find it in `/yourserver/logs/latest.log`

**Comment by EgZiG** [comment]
o wow , this time startup log was other,

**Comment by EgZiG** [comment]
I'l send u in a sec

**Comment by EgZiG** [comment]
ummm lol, something happend and server try to turn on , but then it sutomaticlly shutting it off and its happening for 20th time

**Comment by EgZiG** [comment]
[latest (1).log](https://github.com/Multiverse/Multiverse-Core/files/4550181/latest.1.log)

**Comment by benwoo1110** [comment]
Things that you can try: 

First turn off the server.

if you have add this to bukkit.yml remove it and use the mv import command later: 
```
worlds:
  plotworld:
    generator: PlotSquared
```
Then, remove worlds.yml and after a restart, reimport the world with `/mvimport WORLDNAME normal -g PlotSquared`
