### ISSUE TITLE
Warn message at start

### ISSUE THREAD

**Issue by Teyir** [Multiverse/Multiverse-Core#2243]
Hello, 

I have allways this warn message on my server start.

I test with a multiverse core stable version but I have allways this.

Thank you very much

PS: I'm on 1.15.2 paper build - 220

`

> [Multiverse-Core] "Multiverse-Core v4.1.1-SNAPSHOT-b777" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

`

**Comment by benwoo1110** [comment]
see #2000 it's not an issue to worry. Thanks!
