### ISSUE TITLE
OneBlock Skyblock

### ISSUE THREAD

**Issue by nunuhaza** [Multiverse/Multiverse-Core#2245]
![image](https://user-images.githubusercontent.com/53810639/80999475-57973080-8e77-11ea-91d1-4dc7270a4f2d.png)

just isn't working on import worlds, seems to work on default world file though.

**Comment by benwoo1110** [comment]
If you want custom worlds like one block world. I suggest using a custom generator plugin like this: https://www.spigotmc.org/resources/voidgenerator.25391/

**Comment by benwoo1110** [comment]
"just isn't working" cant really warrant much help unfortunately... Thus I will be closing this issue. Please create a new issue following the issue template with detailed explanation if needed or join our discord at https://discord.gg/NZtfKky

**Comment by RaydellRios** [comment]
Bro, you can try copying the folder "datapacks" from the OneBlock map that you downloaded and paste it in the main world folder.
