### ISSUE TITLE
: Error occurred while enabling Multiverse-Core v4.1.0-b775 (Is it up to date?)

### ISSUE THREAD

**Issue by Spirious111** [Multiverse/Multiverse-Core#2246]
Hello my plugin multiverse core is installed on my 1.12.2 minecraft server, everything work exept some issues like i cant teleport myself with /mv tp world on a world that i created with a command /mv and the only error in the log is "[16:56:55] [Server thread/ERROR]: Error occurred while enabling Multiverse-Core v4.1.0-b775 (Is it up to date?)" did someone know why ? I think that is because i have the latest version of multiverse core downloaded but its not for minecraft 1.12.2.
I just want an answer before delete it and redownload the good version of the plugin.
also, i want to apologize for my bad english, i'm french, so, sorry! 
thanks =)

**Comment by benwoo1110** [comment]
For 1.12.x, you will need to use an older version of Multiverse for it to work. Multiverse 2.5.0 should work: https://dev.bukkit.org/projects/multiverse-core/files/2428161

**Comment by Spirious111** [comment]
Thank you for that fast answer !!! you're the best.

**Comment by Hissam1048v** [comment]
I'm on 1.15.2 but same issue

**Comment by AngheloXT** [comment]
1.8.8? :C
