### ISSUE TITLE
Multiverse crash when i create a world

### ISSUE THREAD

**Issue by Minemobs** [Multiverse/Multiverse-Core#2247]
Hi, i try to create a world with multiverse and when i run this command
/mv create plotworld -g PlotMe-DefaultGenerator
The server crash.
Logs :  https://copynpaste.cursehosting.fr/owegulowog.md

**Comment by nicegamer7** [comment]
I suggest you try a PlotSquared. PlotMe has been discontinued and I'm doubting whether it supports 1.14.

**Comment by benwoo1110** [comment]
Closing it due to inactivity and outdated generator plugin used. However, if you still have other issues, feel free to open a new issue or join our discord at https://discord.gg/NZtfKky
