### ISSUE TITLE
Warn while server starts

### ISSUE THREAD

**Issue by Volgeop** [Multiverse/Multiverse-Core#2250]
Hello, please could you fix this?
` [Multiverse-Core] "Multiverse-Core v4.1.1-SNAPSHOT-b777" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].`

and this?
`[Multiverse-Core] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER} which is not a depend, softdepend or loadbefore of this plugin.`

**Comment by benwoo1110** [comment]
see #2000 it's not and issue nor something to worry about. Thanks!
