### ISSUE TITLE
Async tasks error witch PaperMC #280

### ISSUE THREAD

**Issue by SharasGit** [Multiverse/Multiverse-Core#2252]
Hello,

I was on PaperMC 273 1.15.2 without any issue, 7 worlds with Multiverse-core. Today, i upgraded to PaperMC 280 and when my server close, i have this error every time. I reported it to PaperMC, they told me to see with Multiverse.

[10:40:53] [Server thread/ERROR]: Nag author: 'Rigby' of 'Multiverse-Core' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.

Thank you.

**Comment by Muspah** [comment]
Introduced here: https://github.com/PaperMC/Paper/commit/55e17a8599205450358c6114003305e492cc9a92

**Comment by nicegamer7** [comment]
By any chance, did you run the version command before shutting down?

**Comment by SharasGit** [comment]
No. But i was able to reproduce easily the error by stopping too fast the server after starting it. When the server run for sometimes, i rarely have that error, but sometimes i got it.

**Comment by Muspah** [comment]
Only when stopping too fast? We're doing scheduled restarts (cronjob executing stop in tmux) every 24 hours, and it will almost always show the warning message.

**Comment by SharasGit** [comment]
I'm now using paper #334 with 7 worlds. I also do a cron every 24 hours, but i do not use the restart, i do a stop, wait a minute and start it after that. I still have the error, but no as often as with #280. Up until now, the error did not corrupt anything.

**Comment by nicegamer7** [comment]
Okay, thanks for the info. I've been hinted that it may be our metrics, so I'm working on implementing bStats. I'll post a test build once it's done and we'll see if you still get the warning.

**Comment by Muspah** [comment]
Same here indeed, it seems like a basic task hanging on e.g. an HTTP call. I first thought of some version checking, but Metrics sounds like a good one too.

**Comment by nicegamer7** [comment]
Alright, I've got a test build available [here](https://github.com/Multiverse/Multiverse-Core/files/4740670/Multiverse-Core-4.1.1-SNAPSHOT.zip). Please give it a try and let me know if it solves the issue for you.

**Comment by SharasGit** [comment]
I tested your build and i wasn't able to reproduce the error with it. I tried multiple times, even stopped the server right after the start, it stopped perfectly. I reinstalled 4.1.0 and was able to reproduce the error immediately. Look like you found the problem ;)

**Comment by nicegamer7** [comment]
Awesome! I'll open a PR then. Thanks for testing.
