### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by Redblock6YT** [Multiverse/Multiverse-Core#2255]
12.05 15:06:20 [Server] INFO Redblock6 issued server command: /mv load event
12.05 15:06:20 [Server] WARN java.lang.NullPointerException
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.NBTTagCompound.a(SourceFile:406)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.NBTTagCompound.load(SourceFile:70)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.NBTTagCompound.a(SourceFile:406)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.NBTTagCompound.load(SourceFile:70)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.NBTTagCompound.a(SourceFile:406)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.NBTTagCompound.load(SourceFile:70)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:84)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:53)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:43)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:71)
12.05 15:06:20 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:25)
12.05 15:06:20 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:1)
12.05 15:06:20 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:336)
12.05 15:06:20 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
12.05 15:06:20 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:135)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:117)
12.05 15:06:20 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.loadChunk(CraftWorld.java:277)
12.05 15:06:20 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.loadChunk(CraftWorld.java:169)
12.05 15:06:20 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.setKeepSpawnInMemory(CraftWorld.java:1208)
12.05 15:06:20 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld$3.set(MVWorld.java:134)
12.05 15:06:20 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld$3.set(MVWorld.java:129)
12.05 15:06:20 [Server] WARN at me.main__.util.multiverse.SerializationConfig.SerializationConfig.flushPendingVPropChanges(SerializationConfig.java:248)
12.05 15:06:20 [Server] WARN at com.onarandombox.MultiverseCore.WorldProperties.flushChanges(WorldProperties.java:374)
12.05 15:06:20 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:90)
12.05 15:06:20 [Server] WARN at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:57)
12.05 15:06:20 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:476)
12.05 15:06:20 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:447)
12.05 15:06:20 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:422)
12.05 15:06:20 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorld(WorldManager.java:403)
12.05 15:06:20 [Server] WARN at com.onarandombox.MultiverseCore.commands.LoadCommand.runCommand(LoadCommand.java:36)
12.05 15:06:20 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
12.05 15:06:20 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
12.05 15:06:20 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
12.05 15:06:20 [Server] WARN at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:916)
12.05 15:06:20 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
12.05 15:06:20 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
12.05 15:06:20 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
12.05 15:06:20 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
12.05 15:06:20 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
12.05 15:06:20 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
12.05 15:06:20 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by nicegamer7** [comment]
Which version of Multiverse are you using?

**Comment by Redblock6YT** [comment]
oh I already fixed it sry


ok thx bai
