### ISSUE TITLE
Saving location data for certain worlds only

### ISSUE THREAD

**Issue by utilityracer** [Multiverse/Multiverse-Core#2257]
I want to be able to save my location in one world so that when I spawn in it I'm in the same place where I left off but in my hub I want to spawn at the spawn point.
Currently, I have used /mvinv toggle last_location so that it remembers my location but when I go to spawn in the hub it remembers that location too so I end up spawning in the portal. I am using HubThat (https://dev.bukkit.org/projects/hubthat) to create and teleport to the hub but it still does not go to the spawn point I had set.
 
I'd really appreciate any help!

**Comment by nicegamer7** [comment]
This is currently a bug in Multiverse Inventories that we are working on. Would you mind opening on the Multiverse Inventories repo and I'll keep you updated on the progress there?

**Comment by benwoo1110** [comment]
Probably this issue https://github.com/Multiverse/Multiverse-Inventories/issues/367. Anyways its an issue with mv-inv not mv-core, so I will be closing this.

If you face other issues with mv feel free to join our discord at https://discord.gg/NZtfKky
