### ISSUE TITLE
Cannot import a world on multiverse-core...

### ISSUE THREAD

**Issue by GTg4ming** [Multiverse/Multiverse-Core#2258]
Hello,
I'm using Multiverse-Core in 1.12.2 mohist server. Everything is up to date but i cannot import a world named Oldvale in exemple... However, I have check all the commands and it's not working... I don't have a permission plugin who can cause conflict with the plugin.
The error is :
FAILED.
That world folder does not exist. These look like worlds to me:
"other world in the server"
An issue ?

**Comment by benwoo1110** [comment]
Unfortunately we dont support mohist server (or any bukkit+forge hack servers). The only thing I suppose you can try is for MC 1.12 You will need to use an older version of Multiverse - 2.5.0 should work https://dev.bukkit.org/projects/multiverse-core/files/2428161
