### ISSUE TITLE
setKeepSpawnInMemory() doesn't work. 

### ISSUE THREAD

**Issue by SJS830** [Multiverse/Multiverse-Core#2262]
This is my code:

```
MultiverseWorld world = manager.getMVWorld(worldName);
world.setKeepSpawnInMemory(false);
```

However, in `worlds.yml`, `keepSpawnInMemory` is still false.

**Comment by nicegamer7** [comment]
Look at the review open in Multiverse/Multiverse-NetherPortals#155, it should solve your problem.

**Comment by nicegamer7** [comment]
-_-

I just realized I never opened the review. Sorry.
