### ISSUE TITLE
Feature Request: Per World Warp/Warp Group

### ISSUE THREAD

**Issue by BlueManiac2** [Multiverse/Multiverse-Core#2266]
Can you please add Per World Warp Group or Warps with permissions or something please

**Comment by benwoo1110** [comment]
There are already many warp plugins out there, google will probably give you many possible choice. So I don't think its needed to be implemented in MV. Unless you can explain how your warp feature you are suggesting only work if MV is present. (Noting that you don't need MV to have multi-world warp support.)
