### ISSUE TITLE
I need 1.8.x Version Of The Plugin

### ISSUE THREAD

**Issue by bpekalp** [Multiverse/Multiverse-Core#2270]
Where to find it? I need every 1.8 version supported.
1.8
1.8.1
1.8.2
1.8.3
1.8.4
1.8.5
1.8.6
1.8.7
1.8.8
1.8.9

**Comment by Muspah** [comment]
https://dev.bukkit.org/projects/multiverse-core/files

MV usually supports a lot of versions, it doesn't brake every MC update.

**Comment by mr2meowsYT** [comment]
For 1.8.x, you will need to use an older version of Multiverse for it to work. Multiverse 2.5 should work: https://dev.bukkit.org/projects/multiverse-core/files/898527
You may also try the new (and experimental) updated Multiverse-Core version here: https://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core%20(MC%201.8)/
(Note: At this moment, there are no MV submodules (Portals, NetherPortals, SignPortals, Inventories) available that are compatible for the updated version)
(P.S. For any errors in the new MV version for 1.8, please report them here)

**Comment by nicegamer7** [comment]
I'm going to close this issue. If you still need help, please join us on Discord!
