### ISSUE TITLE
MultiverseCore | /time set [time] not working. | 1.15.2 Paper 

### ISSUE THREAD

**Issue by CyreX12** [Multiverse/Multiverse-Core#2271]
Hello. I have a problem with MVCore 4.1.1.  if the plugin is in, the / time set command will not work. I took out all the plugins and then it didn't go.

MultiverseCore 4.1.1
mc: Paper 1.15.2 | build #305

**Comment by benwoo1110** [comment]
Will need more information then "will not work". If you are still having issues, please create a new issue and follow the issue template or ask in our discord https://discord.gg/NZtfKky
