### ISSUE TITLE
I cannot create a world

### ISSUE THREAD

**Issue by sjc0910** [Multiverse/Multiverse-Core#2276]
When i use /mvcreate to create a world, it displays `Failed.` and i can't import that world.
command: **/mvcreate create normal -t flat**
Console Log: https://paste.ubuntu.com/p/JSG76dGcbZ/

**Comment by nicegamer7** [comment]
Interestingly enough, I have been seeing more and more of these reports, so I'm beginning to think something's wrong.

Here are some things to try:
- Make sure your server software is up to date, be it Spigot or Paper. CraftBukkit is generally not recommended these days and isn't a great choice.
- Make sure you're Multiverse Core and its subplugins are up to date. The latest versions of each plugin are available at [here](https://dev.bukkit.org/projects/multiverse-core).
- Try deleting the generated world's folder (in this case, the `create` folder) and removing the entry from Multiverse Core's `worlds.yml` file. Then try to create it again.

**Comment by sjc0910** [comment]
Thank you for your answer, but that didn't help. It displays `Failed.` again.
Console log: https://paste.ubuntu.com/p/2dbF9qGkTz/

**Comment by sjc0910** [comment]
I'm using the latest version `Multiverse-Core 4.1.0` and the server version is Spigot 1.15.2

**Comment by nicegamer7** [comment]
I've been trying to reproduce this but I've been having some trouble. Can you please provide the following:
- Which host you are using (or if you're self hosting)
- Which version of Java your server runs on
- The output of `/version`
- The output of `/mv version`

**Comment by sjc0910** [comment]
The server is running on my computer (Windows 10).
Java version: [Click here](https://paste.ubuntu.com/p/yXCzD4m6Hk/)
`/version` output: [Click here](https://paste.ubuntu.com/p/g3KMYRZP5j/)
`/mv version` output: [Click here](https://paste.ubuntu.com/p/rwmqzJr6s5/)

**Comment by sjc0910** [comment]
I can use `/mvcreate` to create some worlds before, but now I can't.

**Comment by nicegamer7** [comment]
You can't create any world?

**Comment by sjc0910** [comment]
Yes.

**Comment by sjc0910** [comment]
I'm a Chinese and I'm not good at English.

**Comment by sjc0910** [comment]
I used `/mvcreate nether2 nether` just now and [here](https://paste.ubuntu.com/p/D5ZhWqXncS/) is the output in the console.

**Comment by nicegamer7** [comment]
That's okay. Are there any errors on startup or any errors on shutdown?

**Comment by sjc0910** [comment]
Let me have a look.

**Comment by sjc0910** [comment]
Here's [the output of Multiverse-Core](https://paste.ubuntu.com/p/FSYxqcdWsX/).

**Comment by sjc0910** [comment]
I don't know if that's an error.

**Comment by sjc0910** [comment]
There aren't any errors when the server is shutting down.

**Comment by nicegamer7** [comment]
Okay. I have some more questions:
- Is your system's language English? If not, which language?
- Do you have Administrator access and sufficient privileges to the folder containing the server?

**Comment by sjc0910** [comment]
My system language is Chinese.
I'm the Administrator user of my computer.

**Comment by nicegamer7** [comment]
Can you try with Paper and provide the log if you get a similar error?

**Comment by sjc0910** [comment]
Paper?

**Comment by nicegamer7** [comment]
Yes, PaperMC, a fork of Spigot.

Available [here](https://papermc.io/).

**Comment by sjc0910** [comment]
I'll try that later. Thank you.

**Comment by sjc0910** [comment]
I'm downloading PaperMC, but I still want to use Spigot.  
Can you fix those errors in Spigot?  
Thank you very much!

**Comment by nicegamer7** [comment]
We'll fix the issue if it's an issue with Spigot. I just want to see if it also happens with Paper.

**Comment by sjc0910** [comment]
OK.

**Comment by sjc0910** [comment]
There aren't any errors when I use `/mvcreate` in Paper. I hope that never will be wrong.

**Comment by nicegamer7** [comment]
Thanks for giving it a try. Can you upload your `server.properties`, `bukkit.yml`, and `spigot.yml` files?

**Comment by sjc0910** [comment]
[Here](https://paste.ubuntu.com/p/X8nTXkFzFz/)'s the `server.properties`.

**Comment by sjc0910** [comment]
[spigot.yml](https://paste.ubuntu.com/p/JJGKcNTSnG/)  
[bukkit.yml](https://paste.ubuntu.com/p/Q3mhbGhBnm/)

**Comment by nicegamer7** [comment]
In your `server.properties`, make sure to set `gamemode`, then try to create a world!

**Comment by sjc0910** [comment]
Yeah! I can create world now! Thank you very much.

**Comment by sjc0910** [comment]
Multiverse-Core is really a good plugin.

**Comment by nicegamer7** [comment]
Awesome! Thanks for your kind remark. I'll see if something can be done to prevent this in the future.

**Comment by sjc0910** [comment]
But I have another question:  
When using `/reload`, the config of `Multiverse-Core` will not save, so I must use `/stop` to restart.  
Can you fix this error?

**Comment by nicegamer7** [comment]
I will look into it, although, using `/reload` is generally not recommended.

**Comment by sjc0910** [comment]
I know that, but `/reload` is faster than `/stop`, so I like to use `/reload`
