### ISSUE TITLE
Cloning isn't working

### ISSUE THREAD

**Issue by Foxagone** [Multiverse/Multiverse-Core#2282]
Hi I'm a server owner, and I'm working on a "minigame creator" function using multiverse core.
It should work like
- it clones certain world (/mv clone world normal)
- it renames the world by the world's owner (/mvm set alias world <owners-name>) [im using a different plugin on the owners name part and its working fine.]
- it teleports the owner to the world with his name /mv tp world
But what it actually did is, it clones the world, it renames it but if you want to teleport there, it always teleports you to the same world, even if it's not named by your name. Does someone know where the problem is?

**Comment by nicegamer7** [comment]
What version of Multiverse are you using? And you coding your own plugin using the Multiverse API, or are you executing commands another way?

**Comment by benwoo1110** [comment]
Closing due to lack of information. If you are still facing do create a new issue or come to our MV discord at https://discord.gg/NZtfKky
