### ISSUE TITLE
Console Error on server shutdown. Paper 346#

### ISSUE THREAD

**Issue by DiegoDaniel** [Multiverse/Multiverse-Core#2284]
11.06 04:00:23 [Server] ERROR Nag author: 'Rigby' of 'Multiverse-Core' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.

**Comment by nicegamer7** [comment]
I'm going to close this as a duplicate of #2252 (already fixed, just needs to be incorporated into MV).
