### ISSUE TITLE
default gamemode adventure?

### ISSUE THREAD

**Issue by anar4732** [Multiverse/Multiverse-Core#2290]
i have minigame dimension so i need adventure mode as default world gamemode.
Please add it.

**Comment by benwoo1110** [comment]
`/mvm set gamemode adventure <worldname>`

**Comment by anar4732** [comment]
> `/mvm set gamemode adventure <worldname>`

Not working. it says gamemode can be only survival and creative

**Comment by benwoo1110** [comment]
1. whats your server version/type?
2. Whats the  mv version you are using?

[
![works](https://user-images.githubusercontent.com/30431861/84584679-d8aff300-ae39-11ea-8b3b-d8e9323826ee.PNG)
](url)

works for me on 1.15.2 paper server with mv version 4.1.0 ^

**Comment by anar4732** [comment]
Ow. it worked on last version. thank you!
