### ISSUE TITLE
Registered Listener Error

### ISSUE THREAD

**Issue by KadeWolfe** [Multiverse/Multiverse-Core#2291]
Hello! I keep getting this message when starting up my server

14.06 04:53:26 [Server] WARN "Multiverse-Core v4.1.0-b775" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

I have no idea what it means! Thanks!

**Comment by nicegamer7** [comment]
No need to worry! Look at the line right below that warning.
