### ISSUE TITLE
While using command blocks i cannot use the @p input to send the person who steps on the pressure plate, to a new world.

### ISSUE THREAD

**Issue by ItzMePig** [Multiverse/Multiverse-Core#2292]
So im trying to use command blocks to send people to new worlds, however, its seems i cannot use the "@p" command.  I have a bunch of plugins and im not sure if this is affecting the "@p" command or not. Whenever i try to use the pressure plate it says "Sorry, I couldnt find @p"
Please help me fix this! Thanks -ItzMePig

**Comment by DeadSteve51** [comment]
For some reason some servers do this, I remember that for my old server I would use /minecraft:tp @p (coords)

Try using that for multiverse

**Comment by benwoo1110** [comment]
multiverse, just like most plugins, so not have support for command blocks and vanilla selectors. You can try using command hooks to try and solve it, but there is no guarantees.

https://www.spigotmc.org/resources/commandhook.61415/
