### ISSUE TITLE
MV World chat prefix does not work

### ISSUE THREAD

**Issue by dpakman** [Multiverse/Multiverse-Core#2293]
In config I set:
  prefixchat: 'true'
  prefixchatformat: '[%world%]%chat%'

but the world names do not print on chat....I only see "[]". Running version 4.1.1 build #785

**Comment by benwoo1110** [comment]
Look into setting up world alias: https://github.com/Multiverse/Multiverse-Core/wiki/World-properties#alias

It's also possible another chat formatter plugin is causing it
