### ISSUE TITLE
Prevent anti plugin deletion

### ISSUE THREAD

**Issue by Prefix** [Multiverse/Multiverse-Core#2294]
We just got server raided, people got somehow into our rcon op'ed themselves and boom they deleted everything they could. Mvcore assisted them:
[00:08:48] [Server thread/INFO]: Petras issued server command: /mv import plugins normal
[00:09:03] [Server thread/INFO]: Petras issued server command: /mv delete plugins

**Comment by Prefix** [comment]
if you can please help others and prevent of such things

**Comment by nicegamer7** [comment]
This was implemented long ago... what version of MV were you using?

**Comment by nicegamer7** [comment]
My mistake, it was not long ago. See #1917.
