### ISSUE TITLE
Restart error that makes it so I can't even join the server.

### ISSUE THREAD

**Issue by DeadSteve51** [Multiverse/Multiverse-Core#2295]
17.06 22:19:25 [Server] ERROR Error occurred while enabling Multiverse-Core v4.0.0-b766 (Is it up to date?)
17.06 22:19:25 [Server] INFO java.lang.NoClassDefFoundError: org/bukkit/entity/Phantom
17.06 22:19:25 [Server] INFO at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.killDecision(SimpleWorldPurger.java:152) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.purgeWorld(SimpleWorldPurger.java:119) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.purgeWorld(SimpleWorldPurger.java:197) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.purgeWorld(SimpleWorldPurger.java:74) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.MultiverseCore.MVWorld$SpawningPropertyValidator.validateChange(MVWorld.java:286) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.MultiverseCore.MVWorld$SpawningPropertyValidator.validateChange(MVWorld.java:260) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.serializationconfig.SerializationConfig.SerializationConfig.validate(SerializationConfig.java:893) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.serializationconfig.SerializationConfig.SerializationConfig.setPropertyValue(SerializationConfig.java:443) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.serializationconfig.SerializationConfig.SerializationConfig.setPropertyValue(SerializationConfig.java:368) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.serializationconfig.SerializationConfig.SerializationConfig.setPropertyValue(SerializationConfig.java:353) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.serializationconfig.SerializationConfig.SerializationConfig.setPropertyValueUnchecked(SerializationConfig.java:736) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.MultiverseCore.WorldProperties.setAllowAnimalSpawn(WorldProperties.java:424) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.MultiverseCore.MVWorld.setAllowAnimalSpawn(MVWorld.java:767) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.MultiverseCore.MVWorld.validateEntitySpawns(MVWorld.java:195) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.MultiverseCore.MVWorld.validateProperties(MVWorld.java:205) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:94) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:59) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:477) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:448) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:423) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:728) ~[?:?]
17.06 22:19:25 [Server] INFO at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:315) ~[?:?]
17.06 22:19:25 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
17.06 22:19:25 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
17.06 22:19:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
17.06 22:19:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
17.06 22:19:25 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
17.06 22:19:25 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
17.06 22:19:25 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
17.06 22:19:25 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
17.06 22:19:25 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
17.06 22:19:25 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
17.06 22:19:25 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
17.06 22:19:25 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Phantom
17.06 22:19:25 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched.jar:git-PaperSpigot-"4c7641d"]
17.06 22:19:25 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d"]
17.06 22:19:25 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
17.06 22:19:25 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
17.06 22:19:25 [Server] INFO ... 33 more
17.06 22:19:25 [Server] INFO [Multiverse-Core] Disabling Multiverse-Core v4.0.0-b766

**Comment by benwoo1110** [comment]
For 1.8.x, you will need to use an older version of Multiverse for it to work. Multiverse 2.5 should work: https://dev.bukkit.org/projects/multiverse-core/files/898527

You may also try the new (and experimental) updated Multiverse-Core version here: https://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core%20(MC%201.8)/
(Note: At this moment, there are no MV submodules (Portals, NetherPortals, SignPortals, Inventories) available that are compatible for the updated version)
(P.S. For any errors in the new MV version for 1.8, please report them here)

**Comment by nicegamer7** [comment]
I'll be closing this now since the solution is posted above. If you still need help, just reopen it!
