### ISSUE TITLE
Amplified world import does not work

### ISSUE THREAD

**Issue by wayspurrchen** [Multiverse/Multiverse-Core#2296]
Hi, #1343 suggests that you can import an amplified world but when trying to do /mv import <name> AMPLIFIED you receive this error:

![image](https://user-images.githubusercontent.com/1059075/85033198-4dd73d00-b146-11ea-9153-d1d51cb5c10b.png)

Thank you!

**Comment by wayspurrchen** [comment]
On further inspection, trying to import an amplified world as NORMAL does seem to cause future amplified terrain generation to work properly, but the UI or documentation could use an update for overly concerned admins like myself :)

**Comment by benwoo1110** [comment]
Alright, Glad you solved it. We will improve our documentation when we can. Thanks!
