### ISSUE TITLE
Multiverse crashes server after a while

### ISSUE THREAD

**Issue by Barroncz** [Multiverse/Multiverse-Core#2305]
Hello, Multiverse crashes server after a while when i started server, when i removed MV all was alright. Do you need console errors? It will be nice to have MV 1.16. thank you

**Comment by benwoo1110** [comment]
see #2303 on my comment on updating spigot 1.16 build.

**Comment by Barroncz** [comment]
yeah but i dont know how to update server on my host. I dont know how to build last spigot and use it.

**Comment by benwoo1110** [comment]
You will have to tell your host to update for you then.
