### ISSUE TITLE
Blocks aren't ticked in non-overworlds in 1.16.1

### ISSUE THREAD

**Issue by jkapi** [Multiverse/Multiverse-Core#2307]
We updated our Minecraft server to 1.16.1 yesterday, and all worked well, or so we thought... The problems arose when people started to go to the Nether.

Lava and Sand weren't working. They were very fast with making flying machines in the Nether to mine ancient debris, and although the flying machines worked, normal redstone did not.

So, this morning I went on an investigation to see if there were conflicting plugins. I made a copy and removed everything until there was just Multiverse-Core left. It still didn't work. As a sanity check I also rebuilt Spigot. But it didn't work. So I also removed Multiverse, changed the world in server.properties to be the ones of our new survival and it worked.

After this I also tried in the end if things work.

So the problems we found so far are:
- Fluids aren't updated
- Gravity-affected entities aren't updated
- Redstone isn't updated

![javaw_tLp5QhjTkN](https://user-images.githubusercontent.com/16419568/85920341-1b7abd80-b873-11ea-9181-bca15f0ad7f4.png)
Fluids and gravity affected blocks not working

![javaw_a8GIDy3GVO](https://user-images.githubusercontent.com/16419568/85920354-436a2100-b873-11ea-9b1e-100c53d2ec91.png)
Redstone not working

**Comment by nicegamer7** [comment]
Thank you for taking the time to investigate the issue. This is very concerning! I'll see if I can replicate this and figure out what's wrong!

**Comment by ErrelUnderhill** [comment]
Seconding this issue. I've done the same tests in the nether both in newly generated chunks and 1.15.2 imported chunks and I've gotten the same results. 

I also saw at least one other person on the dev.bukkit page mentioning the same issues.

**Comment by nicegamer7** [comment]
I was able to replicate this behaviour, although, only in non-main worlds. Is that the behaviour you've both experienced? Or are the main worlds also broken?

**Comment by jkapi** [comment]
Yep, main world seems to work fine, it's just extra worlds where it doesn't work

**Comment by ErrelUnderhill** [comment]
Yeah, same situation with me. The main world normal nether and end work fine, but for nether and end of the extra worlds have the issue.

**Comment by nicegamer7** [comment]
Since it only happens on non-main worlds, I'm going to mark this as unrelated to MV, but will continue to investigate.

**Comment by jkapi** [comment]
@nicegamer7 I do beg to differ as it only happens to non-main worlds

**Comment by Resi23** [comment]
I have the same problem, I let the Nether and End generate over MC I have no problems. I generate it with "/mv create world_nether1 nether" or "/mv create world_the_end1 end" is the world buggy and nothing ticks

**Comment by MikedeKokkie** [comment]
Same here. This issue is not unrelated to MV. It only happens when MV is loaded, so clearly it has everything to do with MV.

**Comment by nicegamer7** [comment]
Thanks for reporting everyone. I forwarded the issue to Spigot and it's been fixed in the latest version, so make sure to use Spigot's BuildTools to get it! I tested it myself and everything seems to be working. I'll keep this open until someone confirms it's working on their end.

[Here](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/7884e07936e984bc2045a40b69c481a603f8d449)'s the fix if anyone's interested.

**Comment by benwoo1110** [comment]
Yep, the issue seems to be fixed. I testing on the latest papermc 1.16.1

```
[16:23:49 INFO]: This server is running Paper version git-Paper-3 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[16:23:49 INFO]: Checking version, please wait...
[16:23:51 INFO]: You are running the latest version
```

![2020-06-28_16 23 27](https://user-images.githubusercontent.com/30431861/85942504-44c34880-b95c-11ea-858b-03f68ee74fe9.png)


you can get papermc at: https://papermc.io/ci/job/Paper-1.16/ 
Just replace your spigot.jar with the paper one and use that to start your server.

**Comment by nicegamer7** [comment]
Awesome, thanks to everyone who participated :)
