### ISSUE TITLE
World Not load good 1.16.1

### ISSUE THREAD

**Issue by Flap18** [Multiverse/Multiverse-Core#2309]
When I enter to my server,
I can´t see anything blocks and do any moviment, only I can play when I change the world
![image](https://user-images.githubusercontent.com/67468981/85924645-e16de380-b893-11ea-94d0-92d604d723e8.png)
![image](https://user-images.githubusercontent.com/67468981/85924649-eb8fe200-b893-11ea-848f-0e50df89f5b1.png)
It only do, when I disconect In my world Hub, But If Disconect on another worlds at the moment good, only in one world

> 27.06 14:34:56 [Server] Server thread/INFO issued server command: /mv version
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Inventories] Multiverse-Inventories Version: 3.0.0-b459
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Inventories] First Run: false
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Inventories] Using Bypass: false
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Inventories] Default Ungrouped Worlds: false
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Inventories] Using GameMode Profiles: false
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Inventories] === Groups ===
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Inventories] default: {Worlds: [parcelas, survival_nether, hub_the_end, skyland, tienda, hub, minas, survival, survival_the_end], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Core] Multiverse-Core Version: 4.1.0-b775
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Core] Bukkit Version: git-Spigot-6f4ff1b-983305b (MC: 1.16.1)
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Core] Loaded Worlds: [{"MVWorld@462277096":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"Calabaza"}}, {"MVWorld@1468830015":{"Gen":"null","Type":"NORMAL","Env":"NETHER","Name":"Survival_nether"}}, {"MVWorld@1255460383":{"Gen":"PlotSquared","Type":"NORMAL","Env":"NORMAL","Name":"test"}}, {"MVWorld@1866165341":{"Gen":"null","Type":"NORMAL","Env":"THE_END","Name":"Survival_the_end"}}, {"MVWorld@437009115":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"tntrun"}}, {"MVWorld@700077516":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"Bosque"}}, {"MVWorld@1173541586":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"paintball"}}, {"MVWorld@1906247605":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"trees"}}, {"MVWorld@171848127":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"Survival"}}, {"MVWorld@1901138177":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"factions"}}, {"MVWorld@585513403":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"Fuego"}}, {"MVWorld@734863613":{"Gen":"PlotSquared:s=34,g=7,f=2,m=2","Type":"NORMAL","Env":"NORMAL","Name":"parcelas"}}, {"MVWorld@1350918130":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"world_herobrine_graveyard"}}, {"MVWorld@698713594":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"arenas"}}, {"MVWorld@974998164":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"Hub"}}, {"MVWorld@2023055330":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"minas"}}, {"MVWorld@34993613":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"creativo"}}]
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Core] Multiverse Plugins Loaded: 1
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Core] Economy being used: Essentials Economy
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Core] Permissions Plugin: Bukkit Permissions (SuperPerms)
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Core] Dumping Config Values: (version 2.9)
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Core]  messagecooldown: 5000
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Core]  teleportcooldown: 1000
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Core]  worldnameprefix: true
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Core]  worldnameprefixFormat: [%world%]%chat%
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Core]  enforceaccess: false
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Core]  displaypermerrors: true
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Core]  teleportintercept: true
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Core]  firstspawnoverride: true
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Core]  firstspawnworld: Hub
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Core]  debug: 0
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Core] Special Code: FRN002
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Inventories] Multiverse-Inventories Version: 3.0.0-b459
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Inventories] First Run: false
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Inventories] Using Bypass: false
27.06 14:34:56 [Server] Server thread/INFO [Multiverse-Core] [Multiverse-Inventories] Default Ungrouped Worlds: false
27.06 14:35:04 [Multicraft] Skipped 3 lines due to rate limit (30/s)

**Comment by benwoo1110** [comment]
Try with the latest papermc 1.16.1 

https://papermc.io/ci/job/Paper-1.16/

**Comment by benwoo1110** [comment]
There has been huge improvements to 1.16 since its release, so there is a high chance your issue is fixed since then. If you still have issues, feel free to reopen the issue or ask in our discord at https://discord.gg/NZtfKky

latest builds to get:
https://papermc.io/ci/job/Paper-1.16/
http://ci.onarandombox.com/view/Multiverse/

**Comment by Kogp498** [comment]
I have this exact same issue, I updated to the las version of multiverse and it didn't work, please help :(
