### ISSUE TITLE
Update to 1.16

### ISSUE THREAD

**Issue by Srborjaa** [Multiverse/Multiverse-Core#2311]
Hi, I know that this is not the best place to post that, but could you update Multiverse-Core to 1.16?

Thanks so much :P

**Comment by benwoo1110** [comment]
Multiverse already supports 1.16.1

However, as 1.16.1 is new, there are many bugs still present in the spigot/paper 1.16.1 which may be "game-breaking" and make it seem that mv is broken. If you faces issues with MV, first try with the latest paper/spigot build. If issue persist, report to here or our mv-discord and we will definitely take a look. Thanks!
