### ISSUE TITLE
Lost all items on my server please help!

### ISSUE THREAD

**Issue by TheJJcarter21R** [Multiverse/Multiverse-Core#2312]
ok, so I've lost EVERYTHING on my server after a roll back, so here's the story we updated to 1.16 and I tried to fix something, only to break more. Apex(our server host) offered to roll back the server. We did and it is WELL before the server went by by, all the inv groups and shit is there, but like no of the items. I'm willing to send y'all any files you need to fix this. Hell i'll even pay, please just give my players back their stuff****

**Comment by Phoenix616** [comment]
Multiverse does not modify inventories, groups etc. All it does is load and provide some per-world settings + commands to manage those. What makes you think it's this plugin's fault? (Logs, configs etc. would be pretty usefull)

**Comment by benwoo1110** [comment]
Closing this due to the lack of information. If you are still facing issue, you can open a new one with more detailed report with Logs, configs etc. You can also join our discord at https://discord.gg/NZtfKky
