### ISSUE TITLE
New environments (like nether or end) aren't recognized by the Advancements

### ISSUE THREAD

**Issue by Thyodas** [Multiverse/Multiverse-Core#2313]
Hello,
I'm using a datapack that adds tones of advancements named BlazeandCave's Advancements Pack on my server, moreover I'm using Paper and Multiverse core and have 2 different group of world (2 overworlds, 2 nethers and 2 ends) but I have noticed that every advancements that are reserved for a certain type of world aren't working on the none original worlds.

For instance, in my original _world_nether_ the advancements are working fine, but on the _other_nether_ Minecraft doesn't seem to recognize _other_nether_ as a nether world type. It must be related to predicates (in the datapacks configs), with the predicates you can put conditions for a certain advancement to trigger. Like the location, and so the dimension which can only be 3 types "overworld" "the_end" and "the_nether". I think that due to how multiverse core emulate a new world, my _other_nether_ isn't recognized as a world of dimension "the_nether" by Minecraft.

I have already contacted the creator of the datapack but he can do nothing, he just told me that plugins sometimes break some part of datapacks.

Is it possible to fix this issue?
Thanks!

**Comment by benwoo1110** [comment]
We are in the works for add per world Advancements and Game Stats with multiverse-inventories. https://github.com/Multiverse/Multiverse-Inventories/pull/363

However, As a far as we have tried, we have not seen the possibility of datapack features being per world, due to the vanilla implementation of it.
