### ISSUE TITLE
Individual chats per world

### ISSUE THREAD

**Issue by Alv5ro** [Multiverse/Multiverse-Core#2319]
Suggestion:
I've looked for other plugins that would do this, it's self explanatory, each world has their own chat, and you can't see the entire server chat. I've seen a plugin that does this but it isn't maintained and I think it would be a great addition to MV core.

**Comment by Alv5ro** [comment]
So I've tried the unmaintained plugin: https://www.spigotmc.org/resources/perworldchat.29897/ . It half works, so you can list the chats that should have a single chat, but doesn't work when it comes to connected worlds (a world with and end and nether). If you're going to use their source code, take this into consideration

**Comment by benwoo1110** [comment]
There are many chat plugins out there that has this feature, ranging from plugins like Chat Control, Chat Manager, DeluxeChat, VentureChat and probably more. So there isn't much of a use for mv to create a chat plugin.
