### ISSUE TITLE
Server Crash Bug

### ISSUE THREAD

**Issue by SoRadGaming** [Multiverse/Multiverse-Core#2320]
In 1.16.1, Entering the final end portal crashes the whole server. Tested with 4.1.0
Log: https://pastebin.com/4f4J5unT

**Comment by Phoenix616** [comment]
As far as I can tell from this error there isn't a mention of a plugin in the error so this might actually be a bug in your server software which you might want to report to them.

**Comment by SoRadGaming** [comment]
Currently, the server is hosted on Shockbyte, I have opened a ticket with them, I will download the server and try hosting on my personal rig to confirm this.

**Comment by SoRadGaming** [comment]
The issue persists, at first when going through the exit end portal, it spawns inside the nether portal in the world instead of spawn(e.g bed), after trying to change the spawn it no crashes the server. Log: https://pastebin.com/tmr1Z9LJ

**Comment by SoRadGaming** [comment]
I have solved the issue by resetting the plugin files, yet now it respawns me in the wrong location and not the world spawn.

**Comment by SoRadGaming** [comment]
I'm having a small issue, whenever I go to The End by going through the End portal, it creates an Nether portal once I arrive?
