### ISSUE TITLE
Players respawning in different worlds

### ISSUE THREAD

**Issue by spoghettii** [Multiverse/Multiverse-Core#2321]
I have EssentialsSpawn and Multiverse installed, and I want to make it so there is a different spawn for each world, so you can type /spawn to get to the spawn for that world. To get to the main spawn (Hub) you can only type /hub with the Hub plugin. Instead of respawning in the multiverse spawn for that world, players respawn in the hub. I have priority set to lowest so multiverse should do everything. I can only use /setspawn in 1 world, and I don't want people to die in 1 world and respawn in a different one.

**Comment by nicegamer7** [comment]
Personally, `lowest` has never worked for me. I only got expected behaviour when I set it to `none`. Try that and see if it works.

**Comment by spoghettii** [comment]
> Personally, `lowest` has never worked for me. I only got expected behaviour when I set it to `none`. Try that and see if it works.

Thanks, this fixed it.
