### ISSUE TITLE
Jenkins down? 

### ISSUE THREAD

**Issue by Sketaful** [Multiverse/Multiverse-Core#2323]
Well. Not a bug in the code here, but where do I get my hands on the latest dev if I don't want to compile it myself? The link to the dev version just give me ewrror 504. ;(

**Comment by benwoo1110** [comment]
yes, just use the latest from Bukkit for now.

**Comment by benwoo1110** [comment]
We have uploaded the latest dev build in mv discord server for now. Invite link: https://discord.gg/NZtfKky

**Comment by benwoo1110** [comment]
Jenkins is finally up again: http://ci.onarandombox.com/view/Multiverse/

**Comment by ShayBox** [comment]
It seems to be abandoned
