### ISSUE TITLE
/mv import fails at all times

### ISSUE THREAD

**Issue by Qwertycrackers** [Multiverse/Multiverse-Core#2324]
I assume this issue must be some kind of user error, because I cannot make /mv import work. I am running Multiverse-Core and -Portals -4.1.0 on PaperMC 1.16.1. I am attempting to import some adventure-style CTM maps as extra worlds, and absolutely nothing I have tried successfully imports. The error asks me to run Minecraft-Region-Fixer, but it comes out clean for all the worlds I am having problems with.

All the worlds I am testing load up fine in singleplayer. In addition, I generated a new singleplayer world, and attempting to import it returns the same error about world corruption. Is this a bug or am I stupid?

**Comment by benwoo1110** [comment]
1. Is the world created on 1.16.1?
2. Try with the latest build of 1.16.1 spigot/paper (i.e. when you run `/version` they say you on the latest build)
3. Try with only mv plugins installed

**Comment by Qwertycrackers** [comment]
1. Tested with both an old world and a new one generated on 1.16.1. Both work when loaded in singleplayer.
2. Updated to the latest snapshot (git-Paper-46). No change.

Will try 3 later.

**Comment by localmemedealer** [comment]
Having this same problem. Imports work fine on 1.15.2, assuming we just gotta wait for an update

**Comment by benwoo1110** [comment]
Anyone still having issue with latest version of mv and papermc. Also please send full error and output of `/mvversion -p` if you face issues.

**Comment by Qwertycrackers** [comment]
I actually figured it out. I had unpacked the world as root and my
minecraft user didn't own the file. Perhaps /mvimport could give a
more helpful error? Either way it's not really a bug with your stuff.

**Comment by benwoo1110** [comment]
Alright glad to hear! Will be closing the issue then.

**Comment by K85** [comment]
> I actually figured it out. I had unpacked the world as root and my minecraft user didn't own the file. Perhaps /mvimport could give a more helpful error? Either way it's not really a bug with your stuff.
> […](#)
> On 11/7/20, Ben Woo ***@***.***> wrote: Anyone still having issue with latest version of mv and papermc. Also please send full error and output of `/mvversion -p` if you face issues. -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#2324 (comment)](https://github.com/Multiverse/Multiverse-Core/issues/2324#issuecomment-723443084)

This works. You should notice the owner and the group of the world folder
