### ISSUE TITLE
Portal Generates When Exiting End

### ISSUE THREAD

**Issue by SoRadGaming** [Multiverse/Multiverse-Core#2325]
When leaving the end Dimension, jumping through the portal teleports you to your spawn but you stand inside a nether portal that is generated as you spawn in.

**Comment by benwoo1110** [comment]
hmm that's odd, may I ask what MV versions, and server version/type you are using?

**Comment by SoRadGaming** [comment]
Paper 1.16.1 from v3 to v43, Multiverse Core 4.1.0, Multiverse Inventories 3.0.0, Multiverse Portals 4.1.0, Multiverse NetherPortals 4.1.0. Would you like a video recording, a server log would be useless, nothing appears.

**Comment by SoRadGaming** [comment]
> hmm that's odd, may I ask what MV versions, and server version/type you are using?
Paper 1.16.1 from v3 to v43, Multiverse Core 4.1.0, Multiverse Inventories 3.0.0, Multiverse Portals 4.1.0, Multiverse NetherPortals 4.1.0. Would you like a video recording, a server log would be useless, nothing appears.

**Comment by benwoo1110** [comment]
Try with only MV plugins installed, and yes, do send all relevant information.

**Comment by SoRadGaming** [comment]
> Try with only MV plugins installed, and yes, do send all relevant information.

I use Shockbyte to Host, but I have the same issue when hosting from my client, I have disabled all other plugins. Here is the Log: https://pastebin.com/g2E0RU8X
And the video to go with it, https://youtu.be/hOlXRmNyLz0

**Comment by nicegamer7** [comment]
Thanks for taking the time to make a video! If you don't mind me asking, was this also a problem on 1.15?

P.S. nice world.

**Comment by SoRadGaming** [comment]
> Thanks for taking the time to make a video! If you don't mind me asking, was this also a problem on 1.15?
> 
> P.S. nice world.

Thanks, I did not have the issue on 1.15.

**Comment by SoRadGaming** [comment]
Paper 83 has fixed this issue
