### ISSUE TITLE
Essentials conflict in 1.16

### ISSUE THREAD

**Issue by Castiella** [Multiverse/Multiverse-Core#2326]
See linked Github for full report. Would be grateful if you could help!

https://github.com/EssentialsX/Essentials/issues/3449

Thanks!

**Comment by benwoo1110** [comment]
run `/mv debug 3` and the do the relevant teleport actions. after which, send the logs here via www.pastebin.com

**Comment by Castiella** [comment]
Savagejd87 is a player with no permission to access the world "CreativeWorld"
He can not access with /mvtp (what we expect) however can with /warp and /tpa (essentials commands)
_Castielle_ Is myself who has OP

https://pastebin.com/sSvRtMJH

**Comment by benwoo1110** [comment]
`enforceaccess is off` from your log. Check that in mv config.yml  it is set to `enforceaccess: 'true'`

**Comment by benwoo1110** [comment]
Also to add on, if you modify your config and it resets, it's because when the server gets reloaded or restarted, it overwrites changes. You must shut down the server, re-open the configuration file, modify the file, save it and turn the server back on.

**Comment by Castiella** [comment]
That is very interesting to know, thank you so much for resolving. I'm not sure why our config reset!

**Comment by benwoo1110** [comment]
No problem! ;)
