### ISSUE TITLE
Animals spawning with the animals variable set to False

### ISSUE THREAD

**Issue by AdrianR25** [Multiverse/Multiverse-Core#2328]
Animals are still spawning after using ```/mvm set animals false```. I'm using a normal world with default generation.
I've tested this (and can reproduce) in a Spigot server with default config and only MV-Core installed, also with default config. It also happens in a Paper server.

**Comment by mani00132** [comment]
I got a similar problem, there are no mobs or animals spawning after a restart and I have to run /mvm set animals true, else they won't spawn. In the config everything is set to true

**Comment by nicegamer7** [comment]
I believe this is a duplicate of #2318, closing as such.
