### ISSUE TITLE
Not respawning at respawn anchors

### ISSUE THREAD

**Issue by troykay** [Multiverse/Multiverse-Core#2329]
Server: Paper 1.16.1 build 44
Multiverse-Core: 4.1.0
Multiverse-Netherportals 4.1.0

I have a nether world.  I have a resource anchor in that nether world.  The anchor is charged.  
I set my respawn point using the anchor (and get the message, and the achievement).
I die. 
The resource anchor uses one of its charges.
I respawn at the world's default spawn point.   

I removed all of my plugins and added them in one by one.  I don't see this behaviour until MV is installed.

**Comment by troykay** [comment]
Also affects Multiverse-Core-4.1.1-SNAPSHOT from 07/02/2020

**Comment by ichronox** [comment]
I get this same issue, but not using the default version.

Of course this should be expected as it is not compatible with later mc versions.

**Comment by nicegamer7** [comment]
Possibly related: https://hub.spigotmc.org/jira/browse/SPIGOT-5989 and https://github.com/PaperMC/Paper/pull/3920.

**Comment by Brokkonaut** [comment]
I did a fix for it here: https://github.com/Brokkonaut/Multiverse-Core/commit/126e005057c33e39da784ea2bcec863a71d620ac
But that is incompatible to Minecraft < 1.16, so maybe different solution would be better.

**Comment by nicegamer7** [comment]
Thanks @Brokkonaut. I think there's no other way to fix this. Could you open a PR?

**Comment by nicegamer7** [comment]
I've posted a build on the MV Discord server that should fix this.

**Comment by SoRadGaming** [comment]
I tested it with Paper 110, Latest Devbuilds but Multiverse Inv 3.0 as https://github.com/Multiverse/Multiverse-Inventories/issues/375

**Comment by SoRadGaming** [comment]
Yes

**Comment by andris155** [comment]
Thanks for fix @Brokkonaut

**Comment by berlincount** [comment]
We're also affected by this one. Is any solution forthcoming?

**Comment by nicegamer7** [comment]
It was on hold since it would remove support for versions prior to 1.15 (which we are currently supporting). However, it looks like ben came up with a way to keep support for older versions, so it *may* come soon (no guarantees).

**Comment by benwoo1110** [comment]
Yea, I got it to work with some reflection. Will send a test build soon.

**Comment by benwoo1110** [comment]
@berlincount here is the test build for it https://github.com/Multiverse/Multiverse-Core/pull/2565#issuecomment-784006923

**Comment by berlincount** [comment]
Finally had a chance to test: works perfectly fine! :) thanks!

**Comment by benwoo1110** [comment]
Alright glad to hear that!
