### ISSUE TITLE
1.16.1 Nether Structures do not spawn (even with "-a true") but the locate command still works

### ISSUE THREAD

**Issue by OhNo2** [Multiverse/Multiverse-Core#2333]
I am running 1.16.1 Spigot and the nether structures do not spawn in newly generated nether worlds. with the base "/mvcreate survival_nether nether" the /locate command does not work and returns "no structures located" while when I do "/mvcreate survival_nether nether -a true" the /locate command returns coordinates but no structures are actually there.

**Comment by nicegamer7** [comment]
I'm closing this as a duplicate, see #2310.
