### ISSUE TITLE
Entry Fee Not Working ver. 4.1.0

### ISSUE THREAD

**Issue by TrueDakkon** [Multiverse/Multiverse-Core#2334]
I've tried setting it in the config and doing the commands for it:
`/mvm set price 25 creative`
`/mvm set currency 388 creative`
but nothing seems to be working. When I go through the portal in my survival world I want it to charge 25 emeralds to get to the creative world. The problem is that it isn't taking any emeralds from my inventory when I go through the portal. I don't know if this is because I'm oped or not, but I know it should be charging me that entry fee.

**Comment by nicegamer7** [comment]
Could you provide the link given by `/mvv -b --include-plugin-list` please.

**Comment by TrueDakkon** [comment]
https://pastebin.com/Ng1Nwn3D

**Comment by nicegamer7** [comment]
I think the issue is that your economy plugin doesn't support Vault. Unfortunately there's nothing we can do about that 🙁.
