### ISSUE TITLE
Gamemode not changing after using command.

### ISSUE THREAD

**Issue by MindOfModz** [Multiverse/Multiverse-Core#2338]
I used `/mvm set mode CREATIVE` for two of my worlds. I used the command on the worlds i wanted the gamemode changed. 

However, it still stayed in survival.

**Comment by SoRadGaming** [comment]
Try this while inside the world you wish to modify

> /mvmodify set gamemode creative

If you want to change the rules without being in the world simply put

> /mvmodify set gamemode creative WORLDNAME

**Comment by nicegamer7** [comment]
It's possible you have the `mv.bypass.gamemode.WORLDNAME` permission node, or another plugin is conflicting.

**Comment by MindOfModz** [comment]
@nicegamer7 do server OP's automatically get the bypass permissions? Because i de-opped myself and it worked fine. thanks for help though.

Thank you too @SoRadGaming

**Comment by mvez73** [comment]
> @nicegamer7 do server OP's automatically get the bypass permissions? Because i de-opped myself and it worked fine. thanks for help though.
> 
> Ill close this issue when you respond :)
> 
> Thank you too @SoRadGaming

OP players have ALL permissions.

**Comment by benwoo1110** [comment]
Yea, I'd suggest you having a permission plugin like LuckPerms to manage permissions. Its much better.

**Comment by MindOfModz** [comment]
That’s what I tried. But me being stupid forgot that ops bypass it.

**Comment by nicegamer7** [comment]
Glad you figured it out. Is it okay to close this now?

**Comment by MindOfModz** [comment]
Yes. Thank you for the help i will close this issue now,
