### ISSUE TITLE
Multiverse 4.1.1-SNAPSHOT ignores world-container setting from bukkit.yml

### ISSUE THREAD

**Issue by dirtyequi** [Multiverse/Multiverse-Core#2341]
It seems that mv 4.1.1-SNAPSHOT ignores the world-container setting from bukkit.yml as you can see here:

> minecraft@multivac:/data/minecraft/servers/pandora$ grep level-name server.properties
level-name=pandora
minecraft@multivac:/data/minecraft/servers/pandora$ grep world-container bukkit.yml
  world-container: worlds
minecraft@multivac:/data/minecraft/servers/pandora$ ls -l worlds
total 0
drwxr-xr-x  4 minecraft minecraft 109 Jul 11 09:08 end2
drwxr-xr-x  6 minecraft minecraft 134 Jul 11 09:08 minera2
drwxr-xr-x 12 minecraft minecraft 228 Jul 11 09:08 pandora
drwxr-xr-x  8 minecraft minecraft 159 Jul 11 09:08 pminera
drwxr-xr-x  6 minecraft minecraft 134 Jul 11 09:08 pnether
minecraft@multivac:/data/minecraft/servers/pandora$ ls -l |grep pandora
drwxr-xr-x  7 minecraft minecraft      151 Jul 11 09:03 pandora
minecraft@multivac:/data/minecraft/servers/pandora$

When trying to (re)import those existing worlds:

> mv import pminera normal
[09:12:08 INFO]: FAILED.
[09:12:08 INFO]: That world folder does not exist. These look like worlds to me:
[09:12:08 INFO]:

That problem occurs since updating on paper-1.16.1-86 (mv-4.1.1) and worked flawlessly (on every update) before. Please check and fix.

**Comment by Muspah** [comment]
Seems to be a Spigot issue: https://hub.spigotmc.org/jira/plugins/servlet/mobile#issue/SPIGOT-5824

**Comment by benwoo1110** [comment]
yea, its mention to be unlikely to be fixed. It also states that you can use command line flags of --world-container, -W, --universe, --world-dir Any of those, they're all aliases.

**Comment by dirtyequi** [comment]
Thank you for pointing me to the spigot ticket. Everything works as expected now.

**Comment by Muspah** [comment]
Paper seems to be doing something.. https://github.com/PaperMC/Paper/pull/3878

**Comment by benwoo1110** [comment]
Seems like paper fixed this issue, so I will be closing it. See: PaperMC/Paper#3873
