### ISSUE TITLE
usable with modded 1.15.2?

### ISSUE THREAD

**Issue by grandogarndo** [Multiverse/Multiverse-Core#2343]
Hey, I have an arena server with mods on 1.15.2, and I don't want to build every arena in the same world. is there any way to use this with mods? like a mod version or data pack. I've researched and haven't found any way to do it but actual developers might have the secrets.

**Comment by benwoo1110** [comment]
in the near future, no. mod work very differently as they use multi dimension and not worlds. You can try some Bukkit + forge hacks like catserver, but we don't offer much support of them.

**Comment by grandogarndo** [comment]
Would kettle work? it seems to be in the right language for me, but I don't know if it goes to 1.15.2

**Comment by benwoo1110** [comment]
I dont see MV supporting forge server in the near future, sorry.
