### ISSUE TITLE
Monster World Spawn

### ISSUE THREAD

**Issue by TheBlankSlate** [Multiverse/Multiverse-Core#2345]
I'm not sure If I'm doing something wrong here but for some reason every time I restart my server I have to re-enable monster spawning (using /mvmset monsters true) despite it already being enabled in the config.

**Comment by asterism-s** [comment]
This is happening to me too and has been reported before I believe - a tip until it's fixed is that doing /mv reload works just as well as the set monsters command :)

**Comment by anar4732** [comment]
i think the problem is on 1.16 only

**Comment by nicegamer7** [comment]
It's possible this is a Spigot bug, but I'll have to do some more digging to be sure.

**Comment by TheBlankSlate** [comment]
If you have everything up to date you should fix the problem.

**Comment by LinearBotSystems** [comment]
solved for me I don't know of it was multiverse the version I had was from feb or earlier but there was a newer built but without version increment .

**Comment by LinearBotSystems** [comment]
With Paper spigot 150 it seems broken again testing 158

**Comment by nicegamer7** [comment]
I'm going to close this as a duplicate of #2318.
