### ISSUE TITLE
Issue with Mv core says its not up to date

### ISSUE THREAD

**Issue by Redicicle** [Multiverse/Multiverse-Core#2348]
So when I add Mv core or any Mv to my 1.8.8 server i keep getting this issue

> _15.07 07:52:30 [Server] ERROR Error occurred while enabling Multiverse-Core v4.1.0-b775 (Is it up to date?)
15.07 07:52:30 [Server] INFO java.lang.NoClassDefFoundError: org/bukkit/entity/Phantom
15.07 07:52:30 [Server] INFO at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.killDecision(SimpleWorldPurger.java:152) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.purgeWorld(SimpleWorldPurger.java:119) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.purgeWorld(SimpleWorldPurger.java:197) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.purgeWorld(SimpleWorldPurger.java:74) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.MultiverseCore.MVWorld$SpawningPropertyValidator.validateChange(MVWorld.java:286) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.MultiverseCore.MVWorld$SpawningPropertyValidator.validateChange(MVWorld.java:260) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.serializationconfig.SerializationConfig.SerializationConfig.validate(SerializationConfig.java:893) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.serializationconfig.SerializationConfig.SerializationConfig.setPropertyValue(SerializationConfig.java:443) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.serializationconfig.SerializationConfig.SerializationConfig.setPropertyValue(SerializationConfig.java:368) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.serializationconfig.SerializationConfig.SerializationConfig.setPropertyValue(SerializationConfig.java:353) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.serializationconfig.SerializationConfig.SerializationConfig.setPropertyValueUnchecked(SerializationConfig.java:736) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.MultiverseCore.WorldProperties.setAllowAnimalSpawn(WorldProperties.java:424) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.MultiverseCore.MVWorld.setAllowAnimalSpawn(MVWorld.java:767) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.MultiverseCore.MVWorld.validateEntitySpawns(MVWorld.java:195) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.MultiverseCore.MVWorld.validateProperties(MVWorld.java:205) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:94) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:59) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:477) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:448) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:423) ~[?:?]
15.07 07:52:30 [Server] INFO at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:728) ~_

**Comment by Redicicle** [comment]
I have downloaded the latest file for all of the mv plugins and it still gives this issue

**Comment by benwoo1110** [comment]
For 1.8.x, you will need to use an older version of Multiverse for it to work. Multiverse 2.5 should work: https://dev.bukkit.org/projects/multiverse-core/files/898527

**Comment by benwoo1110** [comment]
The version of MV I linked above should solve your issue, I will close it for now. If you still face any issue, feel free to reopen the issue or come to our MV discord https://discord.gg/NZtfKky
