### ISSUE TITLE
Entering an end portal in world created by mv causes server to restart

### ISSUE THREAD

**Issue by FatherWh0** [Multiverse/Multiverse-Core#2350]
In a end world created by MV, entering the end portal causes the server to restart. The player then becomes trapped as the server will restart every time the player logs in. Here are two pastes from an incident where a player named Waterwood fell into an end portal.
https://pastebin.com/k0t7JX0z
https://pastebin.com/LPpLvb9P
This problem does not occur in the vanilla end.

MV 4.1.0
MVNP 4.1.0
paper # 82

**Comment by thenullmatrix** [comment]
I know this was fixed in a spigot update its working fine for me now. I would try updating paper.

**Comment by FatherWh0** [comment]
You are correct. I updated to paper 92 and it's fixed.

**Comment by thenullmatrix** [comment]
You are welcome
