### ISSUE TITLE
Can't join world?

### ISSUE THREAD

**Issue by ghost** [Multiverse/Multiverse-Core#2351]
I do /mvtp KitPvp and it just says it doesn't know how to take me there

**Comment by leviem1** [comment]
There's not much information in your question. This is like asking us why your family member is upset. There are quite literally thousands of things that may be wrong, and we don't know _anything_ about the situation. 😝 

Let's start with the basics that will help pin down the issue:
1. What version of Minecraft and Multiverse are you running?
2. Did you import the world before teleporting? If so, double check that the name of the world is correct.
3. Have you ever been able to get it to work or is this new behavior?
4. If this is new behavior, is there anything that you recently changed? If so, what?

If you get me that information, I'd be happy to help! Please remember that I'm helping you "just cause" (I'm just some person) so if you're willing to work with me I'll work with you. 😄

**Comment by benwoo1110** [comment]
Sadly its really not enough information, so I will be closing this issue. If you still need help, you can create a new issue or ask in our discord  https://discord.gg/NZtfKky.
