### ISSUE TITLE
NPE on teleporting to another world

### ISSUE THREAD

**Issue by TheNety** [Multiverse/Multiverse-Core#2356]
Hey, whenever I try to teleport to any world, for example /mv tp world_nether this console error occurs https://mcpaste.io/be390cfdf23e3b03

Using:
Multiverse-Core 4.1.1-SNAPSHOT-b785
Paper build 99 for 1.16.1

**Comment by iOshawott** [comment]
same, but it'll be fixed in paper build which will merge it https://github.com/PaperMC/Paper/pull/3942

**Comment by TheNety** [comment]
Yep that fixed it, thanks for letting know that it's Paper issue
