### ISSUE TITLE
Using placeholders in Multiverse core

### ISSUE THREAD

**Issue by LikeManTV** [Multiverse/Multiverse-Core#2361]
Hello,
this isn't a issue but I have a question and need answer.
Is there a way of putting %player% (or smthing like that) into TP command?
/mvtp {player} {world} - the %player% would replace the player name to the one who used the command.
I need this to a gui menu, so that when player clicks on a block, it will run the command and teleport him.
If its not possible, you can write me some other ways on how to make this.
Thanks,
- LikeManTV

**Comment by LikeManTV** [comment]
Please somebody

**Comment by benwoo1110** [comment]
it will be up to your gui menu to replace the %player% with the actual playername.

**Comment by LikeManTV** [comment]
It is related to MV..
The gui itself just runs commands.

**Comment by benwoo1110** [comment]
its the GUI's responsibility to replace  %player% placeholder with the actually player name. not mv.

**Comment by benwoo1110** [comment]
My suggestion is to look into your GUI plugin to see what is need to be done to replace a player placeholder with the actually player name. You may also want to config such that to run the mv command runs in console.

**Comment by LikeManTV** [comment]
I solved it xd
Easy way is to put just "/mvtp world"
