### ISSUE TITLE
Having trouble with multiple worlds.

### ISSUE THREAD

**Issue by Orcah** [Multiverse/Multiverse-Core#2362]
So me and my friends have a server set up to play minecraft together and goof off. Our simple world is in survival, but we wanted to look into multiverse to have a creative world we can switch to at any given moment. However, I'm not particularly tech savvy and are having trouble with setting up the worlds the way I want them to be. 

Here's the setting I want and don't know how to do.

- Gamemode to automatically change between worlds.
- No items to transfer between worlds
- My friends to be able to switch between worlds without being admins.

What commands should I use? Thanks for the help!

**Comment by thenullmatrix** [comment]
You may want to ask on the discord https://discord.gg/NZtfKky This is really for reporting bugs/issues. I would also do a search on how to setup multiverse you will find some videos that will help explain how to set it up.

**Comment by benwoo1110** [comment]
1. to change the enforce gamemode you can run `/mvm set gamemode <gamemode> <worldname>` if you want to bypass it entirely, you need to give `mv.bypass.gamemode.GAMEMODE` permission node using a permission plugin like luckperms.

2. Use Multiverse-Inventories. https://dev.bukkit.org/projects/multiverse-inventories https://github.com/Multiverse/Multiverse-Core/wiki/Basics-(Inventories)

3. you shouldn't give them teleport permissions. MV permissions nodes: https://github.com/Multiverse/Multiverse-Core/wiki/Big-List-O'-Permissions#teleport-permissions Tho, you may have other plugins that have teleport command.
