### ISSUE TITLE
Picking a version for 1.12.2

### ISSUE THREAD

**Issue by FrozenBeard** [Multiverse/Multiverse-Core#2363]
1.12.2 still being the most stable version of minecraft for 40+ online players, some of us are stuck using it until Mojang sorts it out.
What is the correct/best version of MV to use for 1.12.2, im currently using 2.5.0.
Is there a version of the 4.x series for 1.12.2, or has it just been given up on for 1.13?

25% of all Minecraft servers use below 1.13 still. https://bstats.org/global/bukkit

**Comment by nicegamer7** [comment]
For 1.12.x, you will need to use an older version of Multiverse for it to work. Multiverse 2.5.0 should work: https://dev.bukkit.org/projects/multiverse-core/files/2428161

**Comment by nicegamer7** [comment]
Sorry, I didn't read that completely. There's currently no plans to bring version 4 to 1.12 (as far as I am aware). Sorry for the inconvenience.
