### ISSUE TITLE
Plugin getting disabled and giving "internal error occurred while attempting to run this command".

### ISSUE THREAD

**Issue by TheRealsccfornow** [Multiverse/Multiverse-Core#2364]
For some really dumb reason it keeps giving this error when I try doing any mv related commands

Server version: 1.16
Java version: 1.15.2

Log:
`23.07 17:12:53 [Server] INFO GalacticMagnet issued server command: /mv create world2
23.07 17:12:53 [Server] ERROR null
23.07 17:12:53 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'mv' in plugin Multiverse-Core v4.1.1-SNAPSHOT-bUNKNOWN - plugin is disabled.
23.07 17:12:53 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:12:53 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:12:53 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:12:53 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1912) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:12:53 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:12:53 [Server] INFO at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:12:53 [Server] INFO at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:12:53 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:12:53 [Server] INFO at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:12:53 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:12:53 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:12:53 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:12:53 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:12:53 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:12:53 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:12:53 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:12:53 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:12:53 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:12:53 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
23.07 17:13:02 [Server] INFO GalacticMagnet issued server command: /mv create world2
23.07 17:13:02 [Server] ERROR null
23.07 17:13:02 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'mv' in plugin Multiverse-Core v4.1.1-SNAPSHOT-bUNKNOWN - plugin is disabled.
23.07 17:13:02 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:13:02 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:13:02 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:13:02 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1912) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:13:02 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:13:02 [Server] INFO at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:13:02 [Server] INFO at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:13:02 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:13:02 [Server] INFO at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:13:02 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:13:02 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:13:02 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:13:02 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:13:02 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:13:02 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:13:02 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:13:02 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:13:02 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-101]
23.07 17:13:02 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]`

**Comment by nicegamer7** [comment]
That means there is an error earlier in your server's startup. Please upload the latest server log to something like pastebin and send it here.

**Comment by benwoo1110** [comment]
You can see #2215 as well

**Comment by benwoo1110** [comment]
try https://github.com/Multiverse/Multiverse-Core/issues/2215#issuecomment-640545807 build, it may fix your error, but without your server startup log, not much more we can suggest.
