### ISSUE TITLE
1.16

### ISSUE THREAD

**Issue by Loonyy** [Multiverse/Multiverse-Core#2365]
Hi, are the dev builds for Spigot 1.16.1? Or are you going to release when ready on Bukkit?

**Comment by benwoo1110** [comment]
Yes the dev builds can run on 1.16.1 and also 1.16.1 is all out for spigot/paper

https://papermc.io/downloads

**Comment by SlimeDog** [comment]
Am I looking in the wrong place for dev builds? The last successful build at http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/ is nearly a year old, so cannot be 1.16.x compliant.

**Comment by benwoo1110** [comment]
lastest build is only a month old. It passed all the test and its working. The only reason its mark s as fail is bcu we are working on a new java-docs for it that is not completed yet. Its safe to use.
