### ISSUE TITLE
Error importing world

### ISSUE THREAD

**Issue by bobbyl140** [Multiverse/Multiverse-Core#2367]
I have Multiverse Core and Multiverse Nether Portals installed on my server running NukkitX (I know this is intended for Bukkit, but I have a plugin that allows you to use Bukkit plugins). I am attempting to import a world using /mvimport, but it gives an error message. I don’t think this is a problem with the transitional plugin, it worked fine a few weeks ago. I would like to link this world to a nether world for players to use, but I need it imported first. Thank you.

**Comment by benwoo1110** [comment]
MV is a bukkit plugin, and doesnt support officially any nukkit to bukkit hack. May i know what transitional plugin you are using?

**Comment by bobbyl140** [comment]
I use pokkit to load a bukkit/spigot plugins.

**Comment by Makergear25** [comment]
I am still having issues what version of bukkit should i use

**Comment by benwoo1110** [comment]
Unforntuately we dont support NukkitX and probably won't for the near future.
