### ISSUE TITLE
Help whit spawn, please response quickly!

### ISSUE THREAD

**Issue by Pitopi22** [Multiverse/Multiverse-Core#2368]
Hi Multiverse-core team, can you help me whit the /mvtp?
My problem is what when i use /mvtp I am teleported not where i was, but where there is the default spawn. This is a big problem for a vanilla server. How can i fix it?
Sorry for my english but i'am italian.
Thank you and goodbye,
A multiverse core user!!

**Comment by Pitopi22** [comment]
Pleaseeeeee responseeeeeeeeee

**Comment by nicegamer7** [comment]
When teleporting between worlds, the default behavior is to go to the spawn of the world. This can be changed; however, it's not perfect. You'll require Multiverse-Inventories (same version as your MV-Core). Once installed, you'll need to toggle last_location on by doing `/mvinv toggle last_location`. Keep in mind this forces last location for ALL worlds, there is currently no way to only use this function for specific worlds.
