### ISSUE TITLE
End Portal No Spawn Location Error

### ISSUE THREAD

**Issue by ethanic17** [Multiverse/Multiverse-Core#2370]
I am running Multiverse-Core (+ MV-Inventories and MV-Portals) and am running into an issue where if you don't set a spawn point before entering the end portal, you will be permanently stuck in the end unless you TP out using commands. Basically, the end portal doesn't work, whenever you try to go through it it'll display "You have no home bed or charged respawn anchor, or it was obstructed" and then spawn you on top of the bedrock pillar on the portal. I encountered this issue both on Spigot and Paper (1.16.1) and both on the stable build (v4.1.0) and dev build (v4.1.1 snapshot).

**Comment by willies952002** [comment]
Same issues as in #2160
