### ISSUE TITLE
By Server Starting

### ISSUE THREAD

**Issue by Katzatrophe** [Multiverse/Multiverse-Core#2372]
[Multiverse-Core] "Multiverse-Core v4.1.1-SNAPSHOT-b777" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by Muspah** [comment]
See #2000

**Comment by Katzatrophe** [comment]
oh, sorry.

**Comment by Katzatrophe** [comment]
please delete.

**Comment by zax71** [comment]
The issue is closed. That's the best we can do
