### ISSUE TITLE
Mi servidor no inicia por un error de multiverse core

### ISSUE THREAD

**Issue by Raphiiix** [Multiverse/Multiverse-Core#2373]
erver thread/WARN Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.2-b107 which is not a depend, softdepend or loadbefore of this plugin.
04.08 16:05:27 [Server] Server thread/WARN "Multiverse-Core v4.1.0-b775" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].

**Comment by nicegamer7** [comment]
This is fixed in our CI builds.
