### ISSUE TITLE
Conflict between CMI and Multiverse-Core

### ISSUE THREAD

**Issue by broken1arrow** [Multiverse/Multiverse-Core#2374]
I dont know how long we had this error.

But if you dont set bedhome, you end up in spawn area even if you have a sethome (and the player is not in a Multiverse world). 
We try in "Midgardsaga" and it its a normal overworld. Even if i put in Multiverse world, in the files not work.

https://www.youtube.com/watch?v=IJAqnU1YJQM&feature=youtu.be

My settings in cmi is:
ReSpawn:
  # Time in seconds to make player immortal after he respawns
  # Can be used to prevent respawn camping
  # Set to 0 if you want to disable it
  Immortality: 5
  # If you want 3rd party plugin to handle player respawning, simply set this to false and reload plugin
  Enabled: true
  Global:
    # Defines respawn order if defined world is not present in Specific list
    # Possible respawn locations: anchor, bedLocation, spawn, homeLocation, worldSpawn, warp![warpName]
    # Spawn is preset spawnlocation with /cmi setspawn command, that location should have RespawnLocation set to true
    # bedLocation is location set by interacting with bed, BedInteraction should be set to false and players requires cmi.bedhome to set bed location
    # homeLocation is location set by player which is with default (Home) name, if that one doesnt exist then first in the list will be used if possible
    # worldSpawn is location preset to this world, this is not CMI location but default world spawn location
    # warp![warpName] can be any valid warp you set for players to be teleported, they will bypass any requirements for that warp
    PriorityOrder:
    - bedLocation
    - homeLocation
    - spawn
    - worldSpawn
  # Defines respawn order for defines worlds
  # Remove world if you want to leave respawn handling for server or 3rd party plugin
  Specific:
    Midgardsaga:
    - bedLocation
    - homeLocation
    - spawn
    - worldSpawn
    Midgardsaga_nether:
    - worldSpawn
    - bedLocation
    - homeLocation
    - spawn
    Midgardsaga_the_end:
    - bedLocation
    - homeLocation
    - spawn
    - worldSpawn

**Comment by broken1arrow** [comment]
I remove all worlds beside Multiverse generated world. 

I hope is not to big downside to do this (I see it you can fix so I can turn off spawn ability in Multiverse). I can not add firstspawnoverride: false (it remove this setting).

**Comment by benwoo1110** [comment]
You can ask CMI to use a higher priority listener for PlayerRespawn. Unforunately CMI is behind paid walls so I cant test or see the their code to check.

**Comment by broken1arrow** [comment]
> 
> 
> You can ask CMI to use a higher priority listener for PlayerRespawn. Unforunately CMI is behind paid walls so I cant test or see the their code to check.

I fix it, I turn off all setings for respawn in Multiverse and it fix the problem.
