### ISSUE TITLE
Error on server stop, "not properly shutting down async tasks"

### ISSUE THREAD

**Issue by Xastabus** [Multiverse/Multiverse-Core#2376]
Server: Paper 134
Multiverse-Core 4.1.0

Received the following error on server stop.
`[01:30:11 ERROR]: Nag author: 'Rigby' of 'Multiverse-Core' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
`

**Comment by nicegamer7** [comment]
This is no longer an issue in our CI builds and will be fixed in the next release! Thanks for reporting.
