### ISSUE TITLE
Server lagging out due to Multiverse

### ISSUE THREAD

**Issue by Quintoking** [Multiverse/Multiverse-Core#2377]
Server is paper 1.16.1 recent updated from 1.15.1
Any time someone uses a command or a portal to go from one world to another the server will crash.
i'm lost on what to do from here.

12.08 16:22:25 [Server] ERROR org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
12.08 16:22:25 [Server] ERROR org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
12.08 16:22:25 [Server] ERROR co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
12.08 16:22:25 [Server] ERROR org.bukkit.plugin.EventExecutor$$Lambda$3680/72914896.execute(Unknown Source)
12.08 16:22:25 [Server] ERROR org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
12.08 16:22:25 [Server] ERROR com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor43.execute(Unknown Source)
12.08 16:22:25 [Server] ERROR me.minebuilders.clearlag.listeners.ChunkLimiterListener.onChunkLoad(ChunkLimiterListener.java:23)
12.08 16:22:25 [Server] ERROR me.minebuilders.clearlag.listeners.ChunkLimiterListener.countChunks(ChunkLimiterListener.java:35)
12.08 16:22:25 [Server] ERROR org.bukkit.craftbukkit.v1_16_R1.CraftWorld.getLoadedChunks(CraftWorld.java:467)
12.08 16:22:25 [Server] ERROR java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
12.08 16:22:25 [Server] ERROR java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
12.08 16:22:25 [Server] ERROR java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
12.08 16:22:25 [Server] ERROR java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
12.08 16:22:25 [Server] ERROR java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
12.08 16:22:25 [Server] ERROR java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
12.08 16:22:25 [Server] ERROR java.util.Iterator.forEachRemaining(Iterator.java:116)
12.08 16:22:25 [Server] ERROR java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
12.08 16:22:25 [Server] ERROR Stack:
12.08 16:22:25 [Server] ERROR PID: 44 | Suspended: false | Native: false | State: RUNNABLE
12.08 16:22:25 [Server] ERROR Current Thread: Server thread
12.08 16:22:25 [Server] ERROR ------------------------------
12.08 16:22:25 [Server] ERROR Chunk Holder - null for (62,18)
12.08 16:22:25 [Server] ERROR Save Task - none
12.08 16:22:25 [Server] ERROR Load Task - none
12.08 16:22:25 [Server] ERROR 62,18 in 'World_End:
12.08 16:22:25 [Server] ERROR Chunk wait task info below: 
12.08 16:22:25 [Server] ERROR Server thread dump (Look for plugins here before reporting to Paper!):
12.08 16:22:25 [Server] ERROR ------------------------------
12.08 16:22:25 [Server] ERROR The server has not responded for 20 seconds! Creating thread dump
12.08 16:22:25 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-100 (MC: 1.16.1) ---
12.08 16:22:25 [Multicraft] Skipped 3260 lines due to rate limit (30/s)
12.08 16:22:20 [Server] ERROR net.minecraft.server.v1_16_R1.Chunk.loadCallback(Chunk.java:863)
12.08 16:22:20 [Server] ERROR org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
12.08 16:22:20 [Server] ERROR org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
12.08 16:22:20 [Server] ERROR co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
12.08 16:22:20 [Server] ERROR org.bukkit.plugin.EventExecutor$$Lambda$3680/72914896.execute(Unknown Source)
12.08 16:22:20 [Server] ERROR org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
12.08 16:22:20 [Server] ERROR com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor43.execute(Unknown Source)
12.08 16:22:20 [Server] ERROR me.minebuilders.clearlag.listeners.ChunkLimiterListener.onChunkLoad(ChunkLimiterListener.java:27)
12.08 16:22:20 [Server] ERROR org.bukkit.craftbukkit.v1_16_R1.CraftChunk.unload(CraftChunk.java:186)
12.08 16:22:20 [Server] ERROR org.bukkit.craftbukkit.v1_16_R1.CraftWorld.unloadChunk(CraftWorld.java:487)
12.08 16:22:20 [Server] ERROR org.bukkit.craftbukkit.v1_16_R1.CraftWorld.unloadChunk0(CraftWorld.java:510)
12.08 16:22:20 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkProviderServer.purgeUnload(ChunkProviderServer.java:724)
12.08 16:22:20 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkMapDistance.purgeTickets(ChunkMapDistance.java:83)
12.08 16:22:20 [Server] ERROR Stack:
12.08 16:22:20 [Server] ERROR PID: 44 | Suspended: false | Native: false | State: RUNNABLE
12.08 16:22:20 [Server] ERROR Current Thread: Server thread
12.08 16:22:20 [Server] ERROR ------------------------------
12.08 16:22:20 [Server] ERROR Chunk Holder Priority - 2
12.08 16:22:20 [Server] ERROR Chunk Holder Status - minecraft:full
12.08 16:22:20 [Server] ERROR Chunk Ticket Status - minecraft:empty
12.08 16:22:20 [Server] ERROR Chunk Status - minecraft:full
12.08 16:22:20 [Server] ERROR Chunk Holder - non-null
12.08 16:22:20 [Server] ERROR Save Task - none
12.08 16:22:20 [Server] ERROR Load Task - none
12.08 16:22:20 [Server] ERROR 62,18 in 'World_End:
12.08 16:22:20 [Server] ERROR Chunk wait task info below: 
12.08 16:22:20 [Server] ERROR Server thread dump (Look for plugins here before reporting to Paper!):
12.08 16:22:20 [Server] ERROR ------------------------------
12.08 16:22:20 [Server] ERROR The server has not responded for 15 seconds! Creating thread dump
12.08 16:22:20 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-100 (MC: 1.16.1) ---
12.08 16:22:20 [Multicraft] Skipped 996 lines due to rate limit (30/s)

- Another instance after it happened.
11.08 20:43:07 [Server] INFO Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Paper Watchdog Thread"
11.08 20:43:07 [Multicraft] Skipped 25 lines due to rate limit (30/s)
11.08 20:42:20 [Multicraft] Auto-saving world...
11.08 20:32:11 [Multicraft] Auto-saving world...
11.08 20:24:55 [Server] INFO Disabling ClearLag v3.1.6
11.08 20:24:55 [Server] INFO Disabling PlugMan v2.1.7
11.08 20:24:55 [Server] INFO Disabling HolographicDisplays v2.4.3
11.08 20:24:55 [Server] WARN [Votifier] Protocol error. Ignoring packet - Socket closed
11.08 20:24:55 [Server] INFO [Votifier] Votifier disabled.
11.08 20:24:55 [Server] INFO [Votifier] Disabling Votifier v1.9
11.08 20:24:55 [Server] INFO Disabling Multiverse-Core v4.1.0-b775
11.08 20:24:55 [Server] INFO Disabling SimpleSpawn v1.1
11.08 20:24:55 [Server] INFO Disabling Multiverse-Inventories v3.0.0-b459
11.08 20:24:55 [Server] INFO Disabling Multiverse-Portals v4.1.0-b805
11.08 20:24:55 [Server] INFO Disabling Vault v1.7.3-b131
11.08 20:24:55 [Server] INFO - Disabled
11.08 20:24:55 [Server] INFO Disabling Multiverse-NetherPortals v4.1.0-b763
11.08 20:24:55 [Server] INFO VaultAPI unhooked from Ultimate_Economy
11.08 20:24:55 [Server] INFO Disabling Ultimate_Economy v1.2.5f
11.08 20:24:55 [Server] INFO Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
11.08 20:24:55 [Server] INFO Disabling WorldEdit v7.2.0-beta-02+d10d7d6
11.08 20:24:55 [Server] INFO [Economy] Essentials Economy unhooked.
11.08 20:24:55 [Server] INFO Disabling Essentials v2.18.0.0
11.08 20:24:55 [Server] INFO Shutting down executor and cancelling any pending tasks...
11.08 20:24:55 [Server] INFO Disabling WorldGuard v7.0.3;5407315
11.08 20:24:55 [Server] INFO Unloaded module: Statistics v1.01
11.08 20:24:55 [Server] INFO Disabling FogusCore v1.9.9
11.08 20:24:55 [Server] INFO ServerSigns is now disabled.
11.08 20:24:55 [Server] INFO Disabling ServerSigns v4.6.1
11.08 20:24:55 [Server] INFO has been Disabled.
11.08 20:24:55 [Server] INFO Disabling ItemJoin v5.0.6-RELEASE-b395
11.08 20:24:55 [Server] INFO GriefPrevention disabled.
11.08 20:24:55 [Server] INFO Disabling GriefPrevention v16.14.0
11.08 20:24:55 [Server] INFO Success! Disabled CoreProtect v19.1
11.08 20:24:53 [Server] INFO Finishing up data logging. Please wait...
11.08 20:24:53 [Server] INFO Disabling CoreProtect v19.1
11.08 20:24:53 [Server] INFO Disabling EnjinMinecraftPlugin v3.5.7
11.08 20:24:53 [Server] INFO Disabling Wild v2.16-29ce9af
11.08 20:24:53 [Server] INFO Disabling ChestShop v3.10.1 (build 174)
11.08 20:24:53 [Server] INFO Disabling SilkSpawners v6.3.1
11.08 20:24:53 [Server] INFO Auto-save: Saved 1 online users | 0 offline users.
11.08 20:24:53 [Server] INFO Disabling GoldenCrates v3.9.4.1
11.08 20:24:53 [Server] INFO Stopping server
11.08 20:24:53 [Server] INFO at org.spigotmc.WatchdogThread.run(WatchdogThread.java:157) ~[patched_1.16.1.jar:git-Paper-131]
11.08 20:24:53 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.close(MinecraftServer.java:737) ~[patched_1.16.1.jar:git-Paper-131]
11.08 20:24:53 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.stop(DedicatedServer.java:699) ~[patched_1.16.1.jar:git-Paper-131]
11.08 20:24:53 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.stop(MinecraftServer.java:763) ~[patched_1.16.1.jar:git-Paper-131]
11.08 20:24:53 [Server] INFO at java.lang.Thread.stop(Thread.java:850) [?:1.8.0_111]
11.08 20:24:53 [Server] INFO java.lang.ThreadDeath: null
11.08 20:24:53 [Server] ERROR Main thread terminated by WatchDog due to hard crash
11.08 20:24:53 [Server] INFO Stopping main thread (Ignore any thread death message you see! - DO NOT REPORT THREAD DEATH TO PAPER)
11.08 20:24:53 [Multicraft] Skipped 974 lines due to rate limit (30/s)
11.08 20:24:52 [Server] ERROR net.minecraft.server.v1_16_R1.IWorldReader.getChunkAt(IWorldReader.java:100)
11.08 20:24:52 [Server] ERROR net.minecraft.server.v1_16_R1.World.getChunkAt(World.java:391)
11.08 20:24:52 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:500)
11.08 20:24:52 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:568)
11.08 20:24:52 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkMapDistance.markUrgent(ChunkMapDistance.java:221)

- Time before that one

12.08 03:07:02 [Server] WARN Can't keep up! Is the server overloaded? Running 58856ms or 1177 ticks behind
12.08 03:07:02 [Multicraft] Skipped 1001 lines due to rate limit (30/s)
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender.append(RollingRandomAccessFileAppender.java:218) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:177) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:57) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:217) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:232) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.layout.PatternLayout$PatternSelectorSerializer.toSerializable(PatternLayout.java:455) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:61) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:338) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:122) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:138) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.impl.ThrowableProxy.toExtendedStackTrace(ThrowableProxy.java:661) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.core.impl.ThrowableProxy.loadClass(ThrowableProxy.java:549) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at org.apache.logging.log4j.util.LoaderUtil.loadClass(LoaderUtil.java:141) ~[patched_1.16.1.jar:git-Paper-131]
12.08 03:06:57 [Server] INFO at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_111]
12.08 03:06:57 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_111]
12.08 03:06:57 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_111]
12.08 03:06:57 [Server] INFO at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_111]
12.08 03:06:57 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:411) ~[?:1.8.0_111]
12.08 03:06:57 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_111]
12.08 03:06:57 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_111]
12.08 03:06:57 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_111]
12.08 03:06:57 [Server] INFO java.lang.StackOverflowError: null
12.08 03:06:57 [Server] ERROR Could not pass event ChunkLoadEvent to ClearLag v3.1.6
12.08 03:06:57 [Multicraft] Skipped 9142 lines due to rate limit (30/s)
12.08 03:06:55 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkMapDistance.addPriorityTicket(ChunkMapDistance.java:294)
12.08 03:06:55 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:640)
12.08 03:06:55 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkMapDistance.a(ChunkMapDistance.java:117)
12.08 03:06:55 [Server] ERROR net.minecraft.server.v1_16_R1.PlayerChunk.a(PlayerChunk.java:745)
12.08 03:06:55 [Server] ERROR net.minecraft.server.v1_16_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:147)
12.08 03:06:55 [Server] ERROR net.minecraft.server.v1_16_R1.PlayerChunk$$Lambda$4342/1832009293.run(Unknown Source)
12.08 03:06:55 [Server] ERROR net.minecraft.server.v1_16_R1.PlayerChunk.lambda$null$14(PlayerChunk.java:735)
12.08 03:06:55 [Server] ERROR net.minecraft.server.v1_16_R1.Chunk.loadCallback(Chunk.java:863)
12.08 03:06:55 [Server] ERROR org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
12.08 03:06:55 [Server] ERROR org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
12.08 03:06:55 [Server] ERROR co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
12.08 03:06:55 [Server] ERROR org.bukkit.plugin.EventExecutor$$Lambda$3687/1091327337.execute(Unknown Source)
12.08 03:06:55 [Server] ERROR org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
12.08 03:06:55 [Server] ERROR com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor43.execute(Unknown Source)
12.08 03:06:55 [Server] ERROR me.minebuilders.clearlag.listeners.ChunkLimiterListener.onChunkLoad(ChunkLimiterListener.java:27)
12.08 03:06:55 [Server] ERROR org.bukkit.craftbukkit.v1_16_R1.CraftChunk.unload(CraftChunk.java:186)
12.08 03:06:55 [Server] ERROR org.bukkit.craftbukkit.v1_16_R1.CraftWorld.unloadChunk(CraftWorld.java:487)
12.08 03:06:55 [Server] ERROR org.bukkit.craftbukkit.v1_16_R1.CraftWorld.unloadChunk0(CraftWorld.java:510)
12.08 03:06:55 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkProviderServer.purgeUnload(ChunkProviderServer.java:725)
12.08 03:06:55 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:640)
12.08 03:06:55 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkMapDistance.a(ChunkMapDistance.java:117)
12.08 03:06:55 [Server] ERROR net.minecraft.server.v1_16_R1.PlayerChunk.a(PlayerChunk.java:723)
12.08 03:06:55 [Server] ERROR Stack:
12.08 03:06:55 [Server] ERROR PID: 45 | Suspended: false | Native: false | State: RUNNABLE
12.08 03:06:55 [Server] ERROR Current Thread: Server thread
12.08 03:06:55 [Server] ERROR ------------------------------
12.08 03:06:55 [Server] ERROR Server thread dump (Look for plugins here before reporting to Paper!):
12.08 03:06:55 [Server] ERROR ------------------------------
12.08 03:06:55 [Server] ERROR The server has not responded for 22 seconds! Creating thread dump
12.08 03:06:55 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-131 (MC: 1.16.1) ---
12.08 03:06:55 [Multicraft] Skipped 7746 lines due to rate limit (30/s)
12.08 03:06:48 [Server] ERROR org.bukkit.plugin.EventExecutor$$Lambda$3687/1091327337.execute(Unknown Source)
12.08 03:06:48 [Server] ERROR org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
12.08 03:06:48 [Server] ERROR com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor45.execute(Unknown Source)
12.08 03:06:48 [Server] ERROR me.minebuilders.clearlag.listeners.ChunkEntityLimiterListener.onChunkLoad(ChunkEntityLimiterListener.java:27)
12.08 03:06:48 [Server] ERROR org.bukkit.craftbukkit.v1_16_R1.CraftChunk.getEntities(CraftChunk.java:104)
12.08 03:06:48 [Server] ERROR org.bukkit.craftbukkit.v1_16_R1.CraftWorld.getChunkAt(CraftWorld.java:409)
12.08 03:06:48 [Server] ERROR net.minecraft.server.v1_16_R1.IChunkProvider.getChunkAt(SourceFile:16)
12.08 03:06:48 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:500)
12.08 03:06:48 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:568)
12.08 03:06:48 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkMapDistance.markUrgent(ChunkMapDistance.java:221)
12.08 03:06:48 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkMapDistance.addPriorityTicket(ChunkMapDistance.java:294)
12.08 03:06:48 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:640)
12.08 03:06:48 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkMapDistance.a(ChunkMapDistance.java:117)
12.08 03:06:48 [Server] ERROR net.minecraft.server.v1_16_R1.PlayerChunk.a(PlayerChunk.java:745)
12.08 03:06:48 [Server] ERROR net.minecraft.server.v1_16_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:147)
12.08 03:06:48 [Server] ERROR net.minecraft.server.v1_16_R1.PlayerChunk$$Lambda$4342/1832009293.run(Unknown Source)
12.08 03:06:48 [Server] ERROR net.minecraft.server.v1_16_R1.PlayerChunk.lambda$null$14(PlayerChunk.java:735)
12.08 03:06:48 [Server] ERROR net.minecraft.server.v1_16_R1.Chunk.loadCallback(Chunk.java:863)
12.08 03:06:48 [Server] ERROR org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
12.08 03:06:48 [Server] ERROR org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
12.08 03:06:48 [Server] ERROR co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
12.08 03:06:48 [Server] ERROR org.bukkit.plugin.EventExecutor$$Lambda$3687/1091327337.execute(Unknown Source)
12.08 03:06:48 [Server] ERROR org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
12.08 03:06:48 [Server] ERROR com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor45.execute(Unknown Source)
12.08 03:06:48 [Server] ERROR me.minebuilders.clearlag.listeners.ChunkEntityLimiterListener.onChunkLoad(ChunkEntityLimiterListener.java:27)
12.08 03:06:48 [Server] ERROR org.bukkit.craftbukkit.v1_16_R1.CraftChunk.getEntities(CraftChunk.java:104)
12.08 03:06:48 [Server] ERROR org.bukkit.craftbukkit.v1_16_R1.CraftWorld.getChunkAt(CraftWorld.java:409)
12.08 03:06:48 [Server] ERROR net.minecraft.server.v1_16_R1.IChunkProvider.getChunkAt(SourceFile:16)
12.08 03:06:48 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:500)
12.08 03:06:48 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:568)
12.08 03:06:48 [Multicraft] Skipped 8656 lines due to rate limit (30/s)
12.08 03:06:31 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:500)
12.08 03:06:31 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:568)
12.08 03:06:31 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkMapDistance.markUrgent(ChunkMapDistance.java:221)
12.08 03:06:31 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkMapDistance.addPriorityTicket(ChunkMapDistance.java:294)
12.08 03:06:31 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:640)
12.08 03:06:31 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkMapDistance.a(ChunkMapDistance.java:117)
12.08 03:06:31 [Server] ERROR net.minecraft.server.v1_16_R1.PlayerChunk.a(PlayerChunk.java:745)
12.08 03:06:31 [Server] ERROR net.minecraft.server.v1_16_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:147)
12.08 03:06:31 [Server] ERROR net.minecraft.server.v1_16_R1.PlayerChunk$$Lambda$4342/1832009293.run(Unknown Source)
12.08 03:06:31 [Server] ERROR net.minecraft.server.v1_16_R1.PlayerChunk.lambda$null$14(PlayerChunk.java:735)
12.08 03:06:31 [Server] ERROR net.minecraft.server.v1_16_R1.Chunk.loadCallback(Chunk.java:863)
12.08 03:06:31 [Server] ERROR org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
12.08 03:06:31 [Server] ERROR org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
12.08 03:06:31 [Server] ERROR co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
12.08 03:06:31 [Server] ERROR org.bukkit.plugin.EventExecutor$$Lambda$3687/1091327337.execute(Unknown Source)
12.08 03:06:31 [Server] ERROR org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
12.08 03:06:31 [Server] ERROR com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor43.execute(Unknown Source)
12.08 03:06:31 [Server] ERROR me.minebuilders.clearlag.listeners.ChunkLimiterListener.onChunkLoad(ChunkLimiterListener.java:27)
12.08 03:06:31 [Server] ERROR org.bukkit.craftbukkit.v1_16_R1.CraftChunk.unload(CraftChunk.java:186)
12.08 03:06:31 [Server] ERROR org.bukkit.craftbukkit.v1_16_R1.CraftWorld.unloadChunk(CraftWorld.java:487)
12.08 03:06:31 [Server] ERROR org.bukkit.craftbukkit.v1_16_R1.CraftWorld.unloadChunk0(CraftWorld.java:510)
12.08 03:06:31 [Server] ERROR net.minecraft.server.v1_16_R1.ChunkProviderServer.purgeUnload(ChunkProviderServer.java:724)
12.08 03:06:31 [Server] ERROR Stack:
12.08 03:06:31 [Server] ERROR PID: 45 | Suspended: false | Native: false | State: RUNNABLE
12.08 03:06:31 [Server] ERROR Current Thread: Server thread

Some things i noted are that i can tp between worlds fine but hostile mobs wont spawn. To fix that i need to do /mvreload however after doing that is when the error for tp'ing between worlds happens and will crash the server.

**Comment by Quintoking** [comment]
[crash-2020-08-12_16.11.50-server.txt](https://github.com/Multiverse/Multiverse-Core/files/5066287/crash-2020-08-12_16.11.50-server.txt)

**Comment by benwoo1110** [comment]
You are getting ` java.lang.OutOfMemoryError`, either you have too many worlds/plugins/players and your server hardware is just cant keep up. If you haven't use papermc and the optimised JVM flags.

https://papermc.io/downloads
https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/

**Comment by Quintoking** [comment]
It was not due to to many of anything. But thanks. I figured it out.
