### ISSUE TITLE
Frame rate drops to 0 when crossing chuck borders in x and y directions

### ISSUE THREAD

**Issue by Marcell0101** [Multiverse/Multiverse-Core#2380]
I have Multiverse core 4.1.0 and Inventories on a spigot 1.16.2 server, but whenever I'm to cross a chuck border in the multiverse generated world, the frame rate drops to zero, then I wait, and within the chunk, everythink is ok. When teleporting, this effect is even bigger.  This is not my default set world.
My computer has a good graphics card so I don1t think that that is the problem.

**Comment by Marcell0101** [comment]
Update: I generated a new world with the snapshot of 4.1.1, and there I do not experience the issue on that world. The original still lags.

**Comment by zombachu** [comment]
For anyone else that runs into this issue, see [https://hub.spigotmc.org/jira/browse/SPIGOT-6079](https://hub.spigotmc.org/jira/browse/SPIGOT-6079) as it may be the cause (was for me)
