### ISSUE TITLE
Plugin Not Working

### ISSUE THREAD

**Issue by KaidenSkywalker** [Multiverse/Multiverse-Core#2381]
Hello, The commands are not working for this please help.

**Comment by nicegamer7** [comment]
Hi there.

We'll need a bit more info to help you out. Like which versions of Minecraft and MV you're using, maybe a list plugins, and your server's startup log would be great.

For the future, you'd probably get a quicker response on our Discord server.

**Comment by ThisIsOllie** [comment]
> Hi there.
> 
> We'll need a bit more info to help you out. Like which versions of Minecraft and MV you're using, maybe a list plugins, and your server's startup log would be great.
> 
> For the future, you'd probably get a quicker response on our Discord server.

Would you happen to have a link to this Discord server by any chance?

**Comment by nicegamer7** [comment]
Yes! Here it is: https://discord.gg/NZtfKky

**Comment by KaidenSkywalker** [comment]
I found the problem but thanks.
