### ISSUE TITLE
ive spent 6 hours trying to find whats causing this

### ISSUE THREAD

**Issue by thesnekthatsmilesback** [Multiverse/Multiverse-Core#2382]
i cant import a world to multiverse..
i know u guys need logs so here u go: https://pastebin.com/yaJfCnaJ

**Comment by nicegamer7** [comment]
The version of Multiverse you're using is incompatible with 1.12. You'll need to use this version, https://dev.bukkit.org/projects/multiverse-core/files/2428161.

**Comment by benwoo1110** [comment]
The version nicegamer7 gave should work. If you still have any issue, feel free to reopen the ticket or as in our discord https://discord.gg/NZtfKky. Thanks!
