### ISSUE TITLE
[Require asistance] How to switch worlds

### ISSUE THREAD

**Issue by DerShendi** [Multiverse/Multiverse-Core#2387]
I have a pixelmon server and i have the actual playing world in the second world but pokemon dont spawn in there 
So my question is how do i switch the worlds because the pokemon spawn only in the first OW

**Comment by nicegamer7** [comment]
Try changing the world in `server.properties`.

**Comment by benwoo1110** [comment]
Your server's default world is defined by `level-name=worldname` in your `server.properties` file of your server. Hope this helps!
