### ISSUE TITLE
1.16 support

### ISSUE THREAD

**Issue by kennethvd1997** [Multiverse/Multiverse-Core#2388]
hello i tried the plugin on a spigot1.16.1 server but it is not working right.
when i type the commands they can autofill but when I hit enter nothiong happens.
but when I instal it in a 1.15 server it works perfectly.

**Comment by nicegamer7** [comment]
Please upload your `latest.log` file from the `logs` folder to something like paste.gg so we can see what's wrong.

**Comment by benwoo1110** [comment]
If you are using WorldEdit for the wand, ensure you are using their latest that supports 1.16. As for mv, use the latest dev builds http://ci.onarandombox.com/view/Multiverse/. Without any console logs or error message, we can't really diagnose the issue much, so I will be closing it. You can join our discord  https://discord.gg/NZtfKky or create a new issue with **more detailed** explanation of your issue
