### ISSUE TITLE
Feature Request - Clone World for Active Player

### ISSUE THREAD

**Issue by PorgCollector** [Multiverse/Multiverse-Core#2391]
I'm building a Skyblock server for multiple friends, and would love to have a feature where a new player can push a button, trigger a command block, and clone a new, clean skyblock world. Ideally this would be done with an adaptation to the clone command:

```
/mv clone4me {world_to_clone}
```

This would be the equivalent of 

```
/mv clone {world_to_clone} {player_name}
```

**Comment by benwoo1110** [comment]
if you want to use command block to replace something like @p to the actual player name you should use a plugin like:
