### ISSUE TITLE
Gamemodes aren't switching correctly when traveling between worlds

### ISSUE THREAD

**Issue by TheSirRolfe** [Multiverse/Multiverse-Core#2398]
### Information

**Server version:** Minecraft 1.16.2, Paper MC jar version #152

**Full output of `/mv version -b`:** https://pastebin.com/SZcKbLwN

**Server log:** https://gist.github.com/TheSirRolfe/8d539ef100261fcc54ef655d0827c48f

### Details
I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
Basically on my server I have a hub world and, currently, 2 other worlds (creative and survival) which are accessed through mvportals. When the server is first turned on the default gamemode, adventure mode, is loaded correctly but if I go through one of the portals my gamemode will not change (I'm OP and also have the rank Owner which has access to all permissions, and I have enable_bypass set to false in the mvinv config).
If I use /reload and reload all the server plugins without shutting down the server, if I go through one of the portals my gamemode will now change correctly, however if I then go back through the portal I entered that world from my gamemode **won't** change back to adventure mode. I've made sure the gamemodes are all set correct in the worlds.yml doc and I've even tried using the /mvmodify command in each world, but nothing has fixed it yet.

**Steps to reproduce**  
1. I booted up my server
2. I logged in
3. I walked through a portal to either the creative or survival world
4. My gamemode didn't change when l loaded into the world
5. I did /reload and /reload confirm
6. I then went back to the hub world and tried again
7. This time my gamemode now changed going through the portal to creative/survival
8. But now my gamemode won't change going back through the portal to the hub world

**Expected behavior**  
My gamemode would change when going between worlds but it didn't, or it would change going one way but not the other.

**Comment by benwoo1110** [comment]
please follow the issue template, I need to know details like your server version, mv version etc.....

**Comment by TheSirRolfe** [comment]
Ah, my bad. If you could point me in the direction of the issue template
I'll fix up my post right away.

**Comment by benwoo1110** [comment]
https://github.com/Multiverse/Multiverse-Core/issues/new?template=report-a-bug.md

**Comment by TheSirRolfe** [comment]
Fixed my post according to the template.

**Comment by TheSirRolfe** [comment]
It would seem the issue is only to do with the Owner rank. By moving myself to each worlds default rank (regardless if OP or not) the portals are functional and the gamemode switching works exactly as intended. My guess would be that even though enable_bypass is set to false, by having the '*' for permissions it bypasses it anyway.

**Comment by benwoo1110** [comment]
ah I see, there is a `mv.bypass.gamemode.WORLDNAME` permission node with will cause that, you should set this permission node to false

**Comment by TheSirRolfe** [comment]
Ah ok cool. Thank you very much.
