### ISSUE TITLE
Multiverse plugin management

### ISSUE THREAD

**Issue by rudraksha007** [Multiverse/Multiverse-Core#2399]
### world based plugin management

**As many times plugins may conflict each other due to their function, this may help to enable/disable plugins in certain Worlds.**

**As I am a regular user of multiverse, many times I face a problem when two features from different plugins conflicts.
         For example: In my case, Skywars gave it's custom items(for game join) to players whereas the server also had survival
          Also I can't find any plugin like this for spigot 1.16.1 ("per world plugins" is there for spigot 1.8 but it is discontinued for any other update). Hope this request find a good place in this project
    Thankyou...**

**Comment by benwoo1110** [comment]
Unfortunately, multiverse should not alter how other plugin works. Usually good plugins will have config to disable their own features in certain worlds. If that plugin uses permissions nodes, you can also use a permission manager like luckperms and its context features to set permission/command access to only certain worlds you want.
