### ISSUE TITLE
Multiverse not working with 1.16.1-1.16.2 paper

### ISSUE THREAD

**Issue by Zlemoncurd** [Multiverse/Multiverse-Core#2400]
when I do /pl the Multiverse-Cord is always red and I have tried everything I can think of to fix this problem. The commands are broken for example /mv does nothing and always says "An internal error as happened" (all the commands say the same thing)

Please Help, Zlem 

<3

**Comment by benwoo1110** [comment]
Please follow the issue template, thanks!
https://github.com/Multiverse/Multiverse-Core/issues/new?template=help.md

**Comment by Zlemoncurd** [comment]
The server version is paper 1.16.1 but supports 1.16.2

Multiverse-Core v4.1.0-b775

I have tried everything

The problem is it doesn't work just says internal error

**Comment by benwoo1110** [comment]
I need your full server log, as stated in the issue template.......

**Comment by Zlemoncurd** [comment]
https://pastebin.com/z1Vw4zwc
Here :)

**Comment by benwoo1110** [comment]
See https://github.com/Multiverse/Multiverse-Core/issues/2215#issuecomment-640545807 there is a build that fixes it
