### ISSUE TITLE
Multiverse not working with 1.16.1-1.16.2 paper

### ISSUE THREAD

**Issue by Zlemoncurd** [Multiverse/Multiverse-Core#2402]
Information

* **Paper 1.16.1 but 1.16.2 implemented
![image](https://user-images.githubusercontent.com/70798945/92317418-72abc400-f054-11ea-818e-5e2697b0adbc.png)

server log -> https://pastebin.com/kJtagxc6
![image](https://user-images.githubusercontent.com/70798945/92317427-8c4d0b80-f054-11ea-9d9c-b711f09c258b.png)

### Help request

**Problem**
The plugin doesn't work at all

**What I have tried**
Downloading dev builds, going through the config I have tried everything I can think of

**Comment by benwoo1110** [comment]
See #2215 there is build that fixed this. https://github.com/Multiverse/Multiverse-Core/issues/2215#issuecomment-640545807

**Comment by nicegamer7** [comment]
This is a known issue. It's usually an incompatibility with another plugin, see #2215 for a build of MV that'll work.
