### ISSUE TITLE
Re enabling the nether

### ISSUE THREAD

**Issue by N0thingsleft** [Multiverse/Multiverse-Core#2403]
I can't seem to re enable the nether
I have been looking all over the internet!

**Comment by benwoo1110** [comment]
Please follow the issue template.

**Comment by leviem1** [comment]
@N0thingsleft Does this seem relevant?
Multiverse/Multiverse-NetherPortals#173

**Comment by benwoo1110** [comment]
Closing this due to the lack of information. Feel free to reopen with more detailed information provided or visit our discord at https://discord.gg/NZtfKky
