### ISSUE TITLE
Pairing the Overworld with Nether and End

### ISSUE THREAD

**Issue by Fluffycat712** [Multiverse/Multiverse-Core#2404]
So i have an issue with nether portals and probably end too, lets say we have an overworld called Survival, you create a portal but instead of teleporting you to Survival_Nether it teleports you to world_nether, how can i change teleporting destinations or basically world pairs?

**Comment by benwoo1110** [comment]
Do you have multiverse-netherportals installed? also ppl really need to follow the issue template....

**Comment by Fluffycat712** [comment]
Is it compatible with 1.16.1? is have installed it but no folder got created

**Comment by benwoo1110** [comment]
Post the issue at the correct gihub repo https://github.com/Multiverse/Multiverse-NetherPortals/issues and **follow the issue template** thanks.
