### ISSUE TITLE
Error on server startup.

### ISSUE THREAD

**Issue by MoneyDrip** [Multiverse/Multiverse-Core#2405]
Hello I am running a 1.14.4 PAPERspigot minecraft server.

Whenever I start the server, I get this error in the console.
`[Multiverse-Core] "Multiverse-Core v4.1.0-b775" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].`

**Comment by benwoo1110** [comment]
See #2000
