### ISSUE TITLE
Extreme lag on creation of world. Or even server crash.

### ISSUE THREAD

**Issue by torisetDev** [Multiverse/Multiverse-Core#2407]
Server version: Paper 1.16.2
Multiverse version: Latest Dev

**Problem**
When i create a world the server lags A lot and times out everyone.

**What I have tried**
I have tried removing multiverse addons like mv portals and mv inventories and still the case.
The server has 3.5GB of ram and its cloud-hosted.

**Comment by torisetDev** [comment]
And sometimes even crashes

**Comment by torisetDev** [comment]
And crashes i think are due to this spam in console from multiverse creation of a world
![image](https://user-images.githubusercontent.com/67580316/92882145-5030f680-f418-11ea-869f-51aad75e61f5.png)

**Comment by benwoo1110** [comment]
It looks like a chunk gen issue on 1.16. Please follow the issue template and give the relevant info such as full server log, output of `/mvversion -b` etc.
