### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by SlimeDog** [Multiverse/Multiverse-Core#2409]
**Description**  

MV-Core, MV-NetherPortals, and MV-Portals all report dev build errors, and have done for some time. Based on Discord conversations, we understand that the latest dev builds work, but it would increase confidence if the builds succeeded.

**Comment by benwoo1110** [comment]
Latest build is successful so I guess it's fixed? http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/793/

**Comment by SlimeDog** [comment]
MV-Core: no errors reported in last build 793 (latest, 2020-09-22. No indication in comments that there was an explicit fix.
MV-Inventories: no errors reported in last six builds, starting with build 472 (2020-08-02).

**MV-NetherPortals: errors reported in last two builds, starting with build 765 (2020-08-26).**
**MV-Portals: errors reported in last six builds, starting with build 809 (2020-08-26).**

**Comment by benwoo1110** [comment]
sad i thought it was fixed ;(

**Comment by nicegamer7** [comment]
It turns out, MV NetherPortal, Portals, and SignPortals are seeing a different issue than what MV Core had.

I should've checked when we fixed MV Core, sorry about that.

**Comment by nicegamer7** [comment]
@dumptruckman to the rescue! The issue if is fixed (for real this time 😋).

**Comment by benwoo1110** [comment]
I was about to type that... haha

**Comment by SlimeDog** [comment]
Our knight in shining armor. :)
