### ISSUE TITLE
Command blocks are active on all worlds

### ISSUE THREAD

**Issue by Ishan2345** [Multiverse/Multiverse-Core#2410]
I am having issues with multiverse, in my loaded worlds, i have command blocks that need to be on repeat (e.g world 1 has repeating command blocks) but this also affects world 2 aswell, and when I am in world 2, the command blocks from world 1 affect world 2 aswell, in my case, constantly setting the spawnpoint of a player to where they are. This is extremely frustrating and I was wondering if there was any way that this could be changed. Thanks

**Comment by benwoo1110** [comment]
It's up to the commands ran on the command block to have per world support, MV shouldn't be altering other commands from vanilla/other plugins.
