### ISSUE TITLE
Nether/End issue with Multiverse

### ISSUE THREAD

**Issue by felipeaguiar24004** [Multiverse/Multiverse-Core#2413]
When I created a multiverse survival world, when ever I go to the nether/end I enter with all my stuff and when I appear in the nether it disappears. Then when I go back through the nether, I spawn in a void without any of my stuff and I die. Please help!

To see the video click the link and download the video

http://www.mediafire.com/file/0l2tglju8laq1st/file

**Comment by benwoo1110** [comment]
if you have mv inv, look into setting it up properly: https://github.com/Multiverse/Multiverse-Core/wiki/Basics-(Inventories)

you will also need to follow the **issue template** if you want further help.

**Comment by benwoo1110** [comment]
Closing this as issue template is not followed and not enough information is provided. Also it looks like a setup issue with mv-inv (or another per-world inv plugin). If you still face issue, do feel free to open a new issue and provide detailed explanation or just our discord at https://discord.gg/NZtfKky
