### ISSUE TITLE
My server crashes everytime I try to import a world

### ISSUE THREAD

**Issue by Zlemoncurd** [Multiverse/Multiverse-Core#2416]
#2268 # Help request

Version  4.1.1-SNAPSHOT-bUNKNOWN

**Problem**
My server crashes everytime I type /mv import (world) 

**What I have tried**
Waiting to see if the world would load 

**Screenshots**

**Comment by benwoo1110** [comment]
You will need to follow the issue template:
* Full output of `/mv version -b`
* server startup log
* Crash report
* Is the world you are importing generated on the same mc version as your server?

**Comment by benwoo1110** [comment]
Will be closing this due to the lack of information. If you are still facing issue, create a new one following the issue template and provide the information as stated in my message previous. Alternatively you can also join our discord at https://discord.gg/NZtfKky. Thanks!
