### ISSUE TITLE
Playerdata, mapdata and datapacks no longer being detected by multiverse

### ISSUE THREAD

**Issue by Borous** [Multiverse/Multiverse-Core#2417]
Greetings, 
My server recently got ported to a new host, all files had been cloned 1:1 to the new virtual machine and after booting it up for the first time, all was functional. Except for playerdata and a handful of other specifics, 

A noticeable thing was that after the transfer, any player who joined spawned in a different position from what they had been before the migration. amongst with all datapacks seemingly having vanished, 

after looking into the server directory, I realized that multiverse was no longer using the main world to store and read playerdata, 

to be precise, previously, playerdata, data, and datapacks had been stored within a map named “world”, whilst now it’s being stored in a separate world we have named “Imperius”,

Looking into the playerdata files of world “Imperius” it quickly became apparent that indeed, practically no playerdata was to be found. Then, looking into the world “world”, all the previous playerdata, datapacks etc where still there, they are just not being used anymore. 

I have already tried the obvious method of just copying all previous playerdata and such to the world Multiverse is currently reading from, however, that seemed to have had no effect.

are there perhaps config files that need to be readjusted for the plugin to properly read the player data from the specified world “world”? 

The server itself is currently running on the most recent paperspigot 1.16.2 build, and the latest version of multiverse-core.

**Comment by benwoo1110** [comment]
This means the issue lies in the things you have not copied over/changed from your previous server. A possibility is your level-name in server.properties or other missing/modified config/file.

**Comment by Borous** [comment]
Thank you for your response, looking into the server.properties, the level-name= has indeed changed to the other world, 

however, upon  trying to change it to "world", after the server starts it automatically sets it back to "imperius", even when the Multiverse plugin is removed from the plugins folder, any clues on what else might be causing that specific world to have been set as the default level?

**Comment by benwoo1110** [comment]
you mentioned datapacks, its possible a datapack is changing the level-name.

**Comment by Borous** [comment]
I removed all the datapacks from any world file, and Yep, server booted up, and all invetories etc where back like how they used to, not a clue why a datapack of all things would be dictating the level-name, but hey, it's fixed now, 

Thank you for helping me out here :D , I really wouldn't have figured it out otherwise.
