### ISSUE TITLE
Strongholds do not generate

### ISSUE THREAD

**Issue by RJthedude15** [Multiverse/Multiverse-Core#2441]
### Information

* **Server version:** [18:09:38 INFO]: This server is running CraftBukkit version git-Spigot-0287a20-7560f5f (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[18:09:38 INFO]: You are 133 version(s) behind

* **Full output of `/mv version -b`:** https://pastebin.com/mZ0DagXL

* **Server log:** https://gist.github.com/RJthedude15/888e093bbd13c6576f48023610a31faa

### Help request

**Problem**
I created a new world and tested if going to the end worked. I discovered that there was no stronghold within the world and the eye of ender was just floating where the stronghold should be.

**What I have tried**
I have used several versions of 1.16 and tried creating  "_the_end" after the name of the world name that I want. For example: "/mv create lol_the_end end", then "/mv create lol normal"

**Screenshots**

**Comment by nicegamer7** [comment]
This is a known issue in the earlier versions of 1.16. I'm unsure when it was fixed, but I know in 1.16.3 this isn't an issue. We are not supporting 1.16.1, you'll need to update to fix this issue. See #2310 for more details.
