### ISSUE TITLE
Client Lags When Loading New Chunks On A Large Sized World.

### ISSUE THREAD

**Issue by Gordae** [Multiverse/Multiverse-Core#2444]
So, My Server's Survival World Will Lag When I Am Loading New Chunks, Does Not Bring TPS Down, Only Brings FPS Down To Like 1fps. I Want This Resolved As Soon As Possible. This Really Effects The Performance Of My Base Building, Also I Am The Only One On The Survival World.

 <h2>How To Recreate: (At Least For Me)</h2>

- Get A World Of The Size Of 24.2 MBs Or Actual Size 43 MBs
- Load New Chunks

This Is A Very Odd Bug, I Do Not Know What Is Causing This Lag.

**Comment by benwoo1110** [comment]
New chunk loading has always been known to cause a lot of lag, you can pre-generate chunk generator https://www.spigotmc.org/resources/chunky.81534/ and latest papermc to mitigate this.

**Comment by benwoo1110** [comment]
Also next time, please follow the issue template.
