### ISSUE TITLE
Schedule in Multiverse world wont work correctly

### ISSUE THREAD

**Issue by AmitFuss** [Multiverse/Multiverse-Core#2448]
* **Server version:**  1.16.1

* **Full output of `/mv version -b`:**  4.2.2

* **Server log:**  

### Help request

**Problem**
 Hi, I'm trying to use /schedule command in my server for a map that I'm making, But whenever I'm in my "Multiverse World" (The world I've created) the command wont work and start immediately instead of the time that I set. But in my main world (Not the multiverse world )Its working just fine.

**What I have tried**
 I also tried it on a single player world with just the multiverse plugin to check if that causes it, and it still didnt work ( So I assume the problem is in the plugin )
Hope you can help me
Thanks

**Screenshots**

**Comment by benwoo1110** [comment]
It depends on the command you want to run, most if not all vanilla commands do not have per world support, so it will result in command it take effect in all the world or only the default worlds.

**Comment by benwoo1110** [comment]
#1983
