### ISSUE TITLE
Through portals don't trigger advancements

### ISSUE THREAD

**Issue by crizyx** [Multiverse/Multiverse-Core#2452]
### Information

* **Server version:** 
```JAVA 
[15:35:30 INFO]: This server is running Paper version git-Paper-220 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT) 
```

* **Full output of `/mv version -b`:** [https://pastebin.com/6Kk7cTaG](url)

### Details
I was **`able`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
Hello, I have a problem with the advancements, those which are triggered by the event of going through a portal do not trigger. I am using Multiverse-Core & Multiverse-NetherPortals.

I have a hub world (the first world in config priority) which is unlinked and two others "World", "World_Nether" linked together.

**Steps to reproduce**  
Revoke root advencements Nether or The End or Subspace Bubbles
Going through a portal does not trigger the event.

**Screenshots**
MV gamrules:
![](https://cdn.discordapp.com/attachments/325494796221415424/762241903264661504/unknown.png)

server.properties:
![](https://cdn.discordapp.com/attachments/325494796221415424/762242477121339412/unknown.png)

Advancement not triggerd :
![image](https://user-images.githubusercontent.com/46645389/95681086-33860b00-0bde-11eb-9332-b0b71b9e9f33.png)

Can you help me ?

**Comment by benwoo1110** [comment]
I think you are facing this issue https://github.com/Multiverse/Multiverse-NetherPortals/issues/184.

**Comment by crizyx** [comment]
Yes same case sorry for duplicate
