### ISSUE TITLE
New players keep spawning to the wrong world, how do i set the spawnpoint correctly.

### ISSUE THREAD

**Issue by VingGit** [Multiverse/Multiverse-Core#2453]
### Information

* **Server version:** 
1.16.3
* **Full output of `/mv version -b`:** 
-
* **Server log:** 
-
### Help request

**Problem**

I have two different kinds of worlds A and B,  A is the original one where me and my friends have played for quite some time and world B is a new creative world for newcomers and other outsiders.  I have no idea how to direct the spawning of new players to world B.
**What I have tried**

I tried to search the internet for ways to set the spawnpoint of newcomers to another world but they keep spawning in the original one. And i really wouldn't want to install a separate plugin just for that.
**Screenshots**

**Comment by benwoo1110** [comment]
For new players that have not joined your server, you can set `firstspawnworld: worldname` in mv config.yml

**Comment by VingGit** [comment]
As benwoo1110 said, thanks to him.
