### ISSUE TITLE
when i made a new world my old bed spawn overrides the world spawn

### ISSUE THREAD

**Issue by ArcticWRKPLC** [Multiverse/Multiverse-Core#2459]
### Information

* **Server version:**  craftbukkit version git-Bukkit-890130b (MC:1.16.3

* **Full output of `/mv version -b`:** 

* **Server log:** 

### Help request

**Problem**
 after making a different world and turning off essentials x respawn listening whenever i die in server B i spawn at my bed in server A 

**What I have tried**
 i've turned respawn listening in Essentials X to none i've tried /mcm set respawnworld serverA ServerB

**Screenshots**

**Comment by benwoo1110** [comment]
If you want to spawn in the same world you die you should be setting respawn world same as the death world, example: `/mvm set respawnWorld serverB serverB`
