### ISSUE TITLE
Error on every right-click

### ISSUE THREAD

**Issue by TerThesz** [Multiverse/Multiverse-Core#2463]
### Information

* **Server version:** 1.12.2

* **Full output of `/mv version -b`:** https://pastebin.com/dsM4ry4T

* **Server log:** https://gist.github.com/TerThesz/345106ec358c32e4fd5d3e01dbefc27d

### Details
I was **`able`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
An error shows up in the console after every right-click

**Steps to reproduce**  
1- Download latest version of Multiverse-Core from https://www.spigotmc.org/ to a 1.12.2 spigot server
2- Try right-clicking on anything

**Expected behavior**  
An error should pop out in console

**Screenshots**  
Non

**Comment by nicegamer7** [comment]
The latest version of MV is not compatible with 1.12, nor does it claim to be. For `1.12.x`, you will need to use an older version of Multiverse for it to work. Multiverse 2.5.0 should work: https://dev.bukkit.org/projects/multiverse-core/files/2428161
