### ISSUE TITLE
Add Support for Plugins which Utilize Chunk Populators

### ISSUE THREAD

**Issue by ValMobile** [Multiverse/Multiverse-Core#2464]
Request: Please add chunk populator support.

Reasoning: Many plugins cannot use the multiverse api to generate structures in worlds because there is no support for chunk populators. This severely limits the potential server administrators and developers have in creating games and plugins.

**Comment by benwoo1110** [comment]
plugins do not need to use MV API to generate chunks. You can try this plugin that I used before https://www.spigotmc.org/resources/chunky.81534/

**Comment by ValMobile** [comment]
Yes, world pregen plugins can generate worlds with the desired structures, but I have a plugin that specifically uses the multiverse API to generate worlds automatically. Running commands is a temporary and inelegant solution.

**Comment by benwoo1110** [comment]
I don’t think MV will implement chunky populator, as mentioned previously there are plugin with that. If you want to create a world then populate chunks, either auto commands will do, or just create a plugin that hook into both APIs and code as how you want it to be.
