### ISSUE TITLE
Support 1.16's new custom world generation.

### ISSUE THREAD

**Issue by IoIxDButStronger** [Multiverse/Multiverse-Core#2466]
### Feature request

**Feature description**
Among the features added in 1.16 is vanilla, plugin-less custom world generation via a .json file [(the wiki page for it is here](https://minecraft.gamepedia.com/Custom). Currently worlds that are made with this plugin are not supported - nor are [custom dimensions](https://minecraft.gamepedia.com/Custom_dimension), but this is understandably not supported due to how Multiverse's dimensions work. 

**How the feature is useful**
This would admittedly be a niche feature, but - according to the wiki - none of the generators currently available for Multiverse are maintained, and many are abandoned. Thus, this would be a nice replacement feature as it's something that 1.16 natively supports. It would be useful for people who use the current generators...or used, because as it stands the only generators that have been ported to 1.16 anyways are the void generator and the CleanRoomGenerator.

**Comment by IoIxDButStronger** [comment]
A possible alternative that somebody in the Discord mentioned is this [custom dimensions plugin](https://www.spigotmc.org/resources/1-16-custom-dimensions.83731/) which loads dimensions from datapacks as separate worlds. For me, the plugin throws this error:
`[05:47:16] [Server thread/WARN]: [CustomDimensions] Dimension manager already loaded with key minecraft:overworld! Skipping`
If somebody could replicate this error that would be nice because it seems the only possible problem is that it's seeing Multiverse as a dimension manager, even though it advertises compatibility with it and even recommends using it.

**Comment by benwoo1110** [comment]
#2636
