### ISSUE TITLE
My server crashes after trying to create a new world with MV

### ISSUE THREAD

**Issue by HelldemYT** [Multiverse/Multiverse-Core#2468]
# Information

* **Server version:** 1.16.3

* **Full output of `/mvc world_spawn normal`:**

* **Server log:** 
[latest.log](https://github.com/Multiverse/Multiverse-Core/files/5438356/latest.log)

### Help request

**Problem**
It crashed the server and it got stuck at preparing spawn area

**What I have tried**
I have tried removing some plugins that could've been the issue and still didn't work.

**Screenshots**

**Comment by benwoo1110** [comment]
Please do/provide the following:
1. Update mv http://ci.onarandombox.com/view/Multiverse/ and your server software https://papermc.io/downloads
2. Send your full startup log, found in logs/latest.log via https://hastebin.com/
3. Send link generated from `/mvversion -p`

**Comment by zoe02f** [comment]
I have this same issue! I use aternos server hosting and I tried deleting the only other plugin I have and it still 'times out' as I try to create another world.

**Comment by benwoo1110** [comment]
I do not wish to repeat myself but:

Please do/provide the following:

Update mv http://ci.onarandombox.com/view/Multiverse/ and your server software https://papermc.io/downloads
Send your full startup log, found in `logs/latest.log` via https://hastebin.com/
Send link generated from `/mvversion -p`

**Comment by zoe02f** [comment]
I have the most up-to-date version of multiverse (version 4.2.2), can't say I understand how to get the server software info though. For the server startup log: https://mclo.gs/ZxfBugu
As for the /mvversion -p I got: "Version info jumped here: https://j.mp/36KPLrG"

**Comment by benwoo1110** [comment]
Try latest version of papermc instead of spigot https://papermc.io/downloads. And also with only mv plugins installed.

**Comment by benwoo1110** [comment]
Another thing I woulkd like to point out is `aternos` is very very poor server specs. So even creating a new world can cause the server to lag, and timeout as you have experienced.

**Comment by zoe02f** [comment]
It worked! Thank you!
