### ISSUE TITLE
Spawn rates

### ISSUE THREAD

**Issue by argnapa** [Multiverse/Multiverse-Core#2470]
Hi,

I notice that in each of my worlds, there are no fish, dolphins, squid. The mobs are also limited. I'm trying to disable animal spawning in one of my worlds in the config. I've tried using mv modify as well and they still keep spawning. Can I please have some advise? I have also reduced the spawn rates in the bukkit.yml. I am using a paper server. 

Thanks,
Adrianne

**Comment by benwoo1110** [comment]
Please follow the issue template and also specify exact commands you ran. Thanks.

**Comment by argnapa** [comment]
* **Server version:** CMI: 8.7.9.0 ->8.7.9.3
Server: Paper(246) 1.16.3-R0.1-SNAPSHOT
CMI Economy: True Vault: 1.7.3-b131(CMIEInjector) CMI Chat:
True
Modules-> 49 Enabled 2 disabled: ranks, votifier

* **Full output of `/mv version -p`:**  https://pastebin.com/5n5YUA49

* **Server log:**  https://pastebin.com/89SRCpjp

### Help request

**Problem**
 I notice that in each of my worlds, there are no fish, dolphins, squid. The mobs are also limited. I'm trying to disable animal spawning in one of my worlds in the config. I am using a paper server.

**What I have tried**
I've tried using mv modify as well and they still keep spawning. Can I please have some advise? I have also reduced the spawn rates in the bukkit.yml.

**Screenshots**
