### ISSUE TITLE
Multiverse 1.61.1 keeps unloading server spawn world and breaking portals

### ISSUE THREAD

**Issue by The-Jade-Spartan** [Multiverse/Multiverse-Core#2471]
Whenever the server is restarted or reloaded, our main spawn world gets unloaded despite being in the world, which breaks all of our Multiverse Portals. I'm new to Bukkit and servers in general so I'm not sure what I'm doing

**Comment by The-Jade-Spartan** [comment]
![Help](https://user-images.githubusercontent.com/34993828/97796383-5a34d180-1bdf-11eb-8822-ed2f11cda1f5.PNG)
As you can see, it says that "ArtemisCommunityRealm" is unloaded, however, that is the world that the screenshot it was taken on

**Comment by benwoo1110** [comment]
Please follow the issue template. Also do not use `/reload`. For the worlds, are they generated on the same version as your server?

**Comment by benwoo1110** [comment]
Please create new issue following the issue template. Thanks!
