### ISSUE TITLE
Auto unloading World

### ISSUE THREAD

**Issue by Naarwhall** [Multiverse/Multiverse-Core#2472]
**Problem**

Whenever I log out of the world and log in the server, it automatically unloads the world and puts me in the mainworld.
**What I have tried**

I tried to do the /mv load command but it doesn’t keep loading the world and does what is stated above^, so my question is is there a command or a setting of some sort to keep the world loaded?
**Screenshots**

**Comment by benwoo1110** [comment]
Please follow the issue template.

**Comment by benwoo1110** [comment]
Please create new issue following the issue template. Thanks!
