### ISSUE TITLE
Thermos errors 

### ISSUE THREAD

**Issue by Besstyzhiy** [Multiverse/Multiverse-Core#2473]
[Mon, 2. Nov 2020 11:38:22 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[Mon, 2. Nov 2020 11:38:23 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[13:38]
[Mon, 2. Nov 2020 11:38:49 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[13:38]
[Mon, 2. Nov 2020 11:38:54 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[13:39]
[Mon, 2. Nov 2020 11:38:58 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[Mon, 2. Nov 2020 11:38:58 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[Mon, 2. Nov 2020 11:38:58 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[Mon, 2. Nov 2020 11:39:02 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[Mon, 2. Nov 2020 11:39:02 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[Mon, 2. Nov 2020 11:39:03 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[13:39]
[Mon, 2. Nov 2020 11:39:03 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[Mon, 2. Nov 2020 11:39:03 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[Mon, 2. Nov 2020 11:39:03 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[13:39]
[Mon, 2. Nov 2020 11:39:10 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[Mon, 2. Nov 2020 11:39:11 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[13:39]
[Mon, 2. Nov 2020 11:39:14 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[Mon, 2. Nov 2020 11:39:17 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[13:39]
[Mon, 2. Nov 2020 11:39:18 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[Mon, 2. Nov 2020 11:39:20 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[13:39]
[Mon, 2. Nov 2020 11:39:39 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[13:39]
[Mon, 2. Nov 2020 11:39:44 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812
[Mon, 2. Nov 2020 11:39:47 UTC ERROR] Could not pass event PlayerInteractEvent to Multiverse-Core v4.2.2-b812

**Comment by benwoo1110** [comment]
Thermos is unsuported by mv.
