### ISSUE TITLE
Multiverse-portals spawning portals where I don't want them.

### ISSUE THREAD

**Issue by FishbirdDD** [Multiverse/Multiverse-Core#2474]
I am trying to link a nether portal to specific coordinates in a different world. That part works, it takes me to the world and to those specific coordinates. However, after taking me there, it spawns in a nether portal where I teleport to which is not what I want. If it helps, there is only one nether world on my server and it is not for either world. 

These aren't the real world names but here is an example:
Portal is in: HubWorld
Portal links to: x,y,z in OtherWorld
There are no worlds called HubWorld_nether or OtherWorld_nether
The only nether world is world_nether

**Comment by benwoo1110** [comment]
1. Follow the issue template.
2. Use mv-portals repo for things related to mv-portals.

**Comment by FishbirdDD** [comment]
Hi, where do I find the template? I did not see one anywhere.

**Comment by benwoo1110** [comment]
![Uploading B7D3EEBE-8C02-4FBE-A8D4-0F16B2DE9923.png…]()

**Comment by benwoo1110** [comment]
Just click on new issue in mv-portal repo. It should give you 3 options with templates.
