### ISSUE TITLE
Traders and Patrols not spawning

### ISSUE THREAD

**Issue by Crixx007** [Multiverse/Multiverse-Core#2475]
-->

### Help request

**I started a survival map on my server with multiverse and want pillager Patrols and wandering traders to spawn but they arent spawning**

** i changed the gamerule settings and it says that they can spawn but dont**

**Screenshots**
Hz

**Comment by benwoo1110** [comment]
Please follow issue template.

**Comment by benwoo1110** [comment]
Was the issue fixed or?

**Comment by Crixx007** [comment]
Yes i got it fixed :)

**Comment by benwoo1110** [comment]
Alright good to hear!
