### ISSUE TITLE
Mob Spawning settings resetting

### ISSUE THREAD

**Issue by Crixx007** [Multiverse/Multiverse-Core#2476]
### Information

* **git-Bukkit-890130b (MC 1.16.3)** 

* **https://j.mp/38niyVV** 

* **https://gist.github.com/Crixx007/a1824dc50ae6ef9f6ac0b00c2101565e** 

### Help request

**After a server restart, some settings keep resetting mainly that monsters can spawn in my survival nether world or my survival end world. If i try to summon a monster into that world it says unable to summon entity due to duplicate UUIDs**

**I used /mvm set monsters true for those worlds and also put monsters to true in the server properties and in worlds.yml**

**http://prnt.sc/vfih3a
http://prnt.sc/vfihan**

**Comment by benwoo1110** [comment]
Try use the latest version of Papermc https://papermc.io/downloads

Possibility related to #2318

**Comment by Crixx007** [comment]
would that reset all my plugin settings or can i just swap it out?

**Comment by benwoo1110** [comment]
just swap the .jar and set your server to start up from the new .jar

**Comment by Crixx007** [comment]
ok ty

**Comment by Crixx007** [comment]
tysm paper seemed to have also fixed all the other minor issues I had

**Comment by benwoo1110** [comment]
Alright good to hear!

**Comment by Crixx007** [comment]
👍
