### ISSUE TITLE
i get items randomly when create a world

### ISSUE THREAD

**Issue by xuso5556589** [Multiverse/Multiverse-Core#2477]
### Information

* **Server version:** 1.16.3

* **Full output of `/mv version -p`:**  https://paste.gg/37d6496c8121462bbdcf517c5de05662
* **Server log:**  https://gist.github.com/xuso5556589/2895d951dd983d9d4ba378c310100268

### Help request

**Problem** 
i'm getting item all the time when i create a world  or i import or i clone whatever i do with multiverse i get items randomly on my inventory

**What I have tried**

**Screenshots**

**Comment by benwoo1110** [comment]
multiverse-core alone doesn’t touch inventories, so inv will also be share among all worlds. Can you try with only mv plugins installed on the latest version of paper?

**Comment by xuso5556589** [comment]
someone on discord told me can be for datapacks but i need those datapacks and i have one world called world with a datapack, but if i create another world should happen right?

**Comment by benwoo1110** [comment]
Datapacks are applied globally on all worlds, and out of mv control. If you remove the datapack and the issue is fixed, then you have to find another datapack or plugin as alternative. Nothing mv can do about it.
