### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by zNightLastTR** [Multiverse/Multiverse-Core#2478]
There is a systemic vulnerability in the plugin. Since there is no world control, the requested file can be deleted like 
/mv delete ../ ../plugins.

**Comment by benwoo1110** [comment]
I dont believe its possible, it need to be a MVWorld before its possible to delete it, just tested and this is what I got.

```
> mv delete "../../plugins"
[18:05:52 INFO]: The command mvdelete has been halted due to the fact that it could break something!
[18:05:52 INFO]: If you still wish to execute mvdelete
[18:05:52 INFO]: please type: /mvconfirm
[18:05:52 INFO]: /mvconfirm will only be available for 10 seconds.
> mvconfirm
[18:05:53 INFO]: World '../../plugins' could NOT be deleted!```

**Comment by zNightLastTR** [comment]
> I dont believe its possible, it need to be a MVWorld before its possible to delete it, just tested and this is what I got.
> 
> ```
> > mv delete "../../plugins"
> [18:05:52 INFO]: The command mvdelete has been halted due to the fact that it could break something!
> [18:05:52 INFO]: If you still wish to execute mvdelete
> [18:05:52 INFO]: please type: /mvconfirm
> [18:05:52 INFO]: /mvconfirm will only be available for 10 seconds.
> > mvconfirm
> [18:05:53 INFO]: World '../../plugins' could NOT be deleted!
> ```

/mv delete .../.../plugins Would you try
I have many friends who have the problem.
There is no world control in the plugin.

**Comment by benwoo1110** [comment]
Will need more info. Run `/mvversion -p` and send the link generated here for the server that is having the issue. Also ensure they are on the latest version of mv 4.2.2

**Comment by zNightLastTR** [comment]
> Will need more info. Run `/mvversion -p` and send the link generated here for the server that is having the issue. Also ensure they are on the latest version of mv 4.2.2

You can share an announcement for this problem in the old version, where I will do the necessary tests.

**Comment by benwoo1110** [comment]
old version? You need to test it with the latest version of MV as I do know MV changed the way delete command works to fix this issue about a year ago. So if you are using an old unsupported version of MV, then nothing I can do other than tell you to update.

**Comment by zNightLastTR** [comment]
I understand, thanks, I will inform my friends.
