### ISSUE TITLE
i have a .dat in a word but mport says its lacking a .dat file

### ISSUE THREAD

**Issue by windetrsfugwq** [Multiverse/Multiverse-Core#2479]
### Information

* **Server version:** 

* **Full output of `/mv version -p`:** 

* **Server log:** 

### Help request

**Problem**

**What I have tried**

**Screenshots**

**Comment by windetrsfugwq** [comment]
import*

**Comment by windetrsfugwq** [comment]
![image](https://user-images.githubusercontent.com/66659349/98871405-18532900-2432-11eb-8f93-95d6c52c5dd4.png)

**Comment by benwoo1110** [comment]
Fill in the issue template, thanks.
