### ISSUE TITLE
Disable Baby Piglin

### ISSUE THREAD

**Issue by Janninschko** [Multiverse/Multiverse-Core#2480]
Hello, i need your help guys.

Is it possible in Multiverse Core to disable just the baby piglins so that only the adults spawn?

**Comment by benwoo1110** [comment]
You can try set monster black list for it. https://github.com/Multiverse/Multiverse-Core/wiki/World-properties#monsters

**Comment by Janninschko** [comment]
I already blacklisted piglins but i still get the baby piglins but i just want the adults to spawn

**Comment by benwoo1110** [comment]
Can you send your full startup log, found in logs/latest.log via https://hastebin.com/ and send link generated from `/mvversion -p`
