### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by zSoLoFTW** [Multiverse/Multiverse-Core#2481]
### Information

* **Server version:** 

* **Full output of `/mv version -p`:** 

* **Server log:** 

### Help request

**Problem**
 Failed Import Multiverse-Core

**What I have tried**
 Why doesn't it work? Am I doing something wrong? Please help me

**Screenshots**
 
![unknown](https://user-images.githubusercontent.com/74455710/99147021-f6ea7b00-2685-11eb-9e1a-b52a8f8cbd89.png)

**Comment by benwoo1110** [comment]
Please follow the issue template. Also ensure the world you are trying to import is generated on the same mc version as your server.

**Comment by benwoo1110** [comment]
Closing this due to the lack of information. Create a new issue **with proper information provided** if needed, thanks.
