### ISSUE TITLE
Error with startup of Multiverse-Core

### ISSUE THREAD

**Issue by joeyk710** [Multiverse/Multiverse-Core#2482]
There is an error in the console when Multiverse-Core starts up. Not sure if it's a bug or maybe I should just ignore it. 

This is the error - 

**14.11 19:57:11 [Server] WARN [Multiverse-Core] "Multiverse-Core v4.2.2-b812" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].**

I can also send my config.yml, the worlds.yml as well as the scripts.bin if you want to look at those files.

**Comment by benwoo1110** [comment]
See #2000
