### ISSUE TITLE
 Problem when loading MultiverseCore

### ISSUE THREAD

**Issue by Goldfire2** [Multiverse/Multiverse-Core#2483]
I have this problem when I run my server. It is under Paper 1.8.8.
https://hastebin.com/sidiqiheli.sql

**Comment by benwoo1110** [comment]
MC 1.8.x You will need to use an even older version of Multiverse - 2.5 should work (not the same as 2.5.0): https://dev.bukkit.org/projects/multiverse-core/files/898527
