### ISSUE TITLE
Can't set price to tp to world in EssentialsX currency- only accepts positive numbers

### ISSUE THREAD

**Issue by imthegm** [Multiverse/Multiverse-Core#2484]
### Information

* **Server version: This server is running Paper version git-Paper-277 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
** 

* **Full output of `/mv version -p`: https://pastebin.com/0gLfDGgE** 

* **Server log: https://pastebin.com/27SrfLPM** 

### Help request
I am trying to set a price to tp to a world (Fair_Lands) in the currency of EssentialsX, which is currently working properly with Jobs and ChestShop.
When I try to do "/mvm set currency -1" I get the following error message, followed by a list of properties I can set; 
"Sorry, You can't set: 'currency'" 
I am not experiencing this issue when I try to set the currency to any other value, and I am op'd. My list of valid world properties is also attached below as well as being contained in the latest.log. When I try to do /mvm set entryfee I get 
"Spawn is the only param with no VALUE.
Type /mv modify ? For help."
I think there's just something about the world properties and how to set this up that isn't making sense to me, else there has to be an issue with the wiki or a bug going on here.
valid world properties https://pastebin.com/dDp0u9ZV
latest.log https://pastebin.com/27SrfLPM
/mvv version p https://pastebin.com/0gLfDGgE
/mvv -b --include-plugin-list https://pastebin.com/UXHsKeer

**Comment by benwoo1110** [comment]
Was able to reproduce this bug. Probably a small fixed needed for property validation. For now you can edit the value in mv `worlds.yml` and then run `/mv reload`.

```
> mvm set currency 3 all
[17:20:01 INFO]: Success! Property currency was set to 3
> mvm set currency -1 all
[17:20:03 INFO]: Sorry, You can't set: 'currency'
[17:20:03 INFO]: Valid world-properties: hidden alias color style pvp scale respawnWorld allowWeather difficulty spawning entryfee hunger autoHeal adjustSpawn portalForm gameMode keepSpawnInMemory spawnLocation autoLoad bedRespawn worldBlacklist environment seed generator playerLimit allowFlight
```

(all is the name of the world)
