### ISSUE TITLE
Mvtp permissions doesn't work

### ISSUE THREAD

**Issue by bryanquatremare** [Multiverse/Multiverse-Core#2485]
### Information

* **Server version: Paper version git-Paper-267 (MC: 1.16.4)**

* **Full output of `/mv version -p`: https://paste.gg/p/anonymous/8001d8491e4543848ece17521875df86** 

### Help request

**Problem**
I'm trying to disable access to Nephta_nether world through /mvtp command (but still accessible via NetherPortals) via permissions.

**What I have tried**
I added permission multiverse.teleport.self.w and disabled multiverse.teleport.self.Nephta_nether permission, but I can still teleport to Nephta_nether. 
![image](https://user-images.githubusercontent.com/17620337/99244125-f1b23b00-2801-11eb-9f0e-58b5eb65e5ee.png)
![image](https://user-images.githubusercontent.com/17620337/99244165-ff67c080-2801-11eb-93bc-c562b45d06a5.png)
![image](https://user-images.githubusercontent.com/17620337/99244338-3b028a80-2802-11eb-9e09-0a78edd97c44.png)

I tried disabling multiverse.teleport.self.w permission and enabling per world teleport, but when trying to mvtp the plugin says that i'm missing a permission.

![image](https://user-images.githubusercontent.com/17620337/99244894-04793f80-2803-11eb-8394-ab380267271e.png)
![image](https://user-images.githubusercontent.com/17620337/99244857-f4616000-2802-11eb-80b5-e2c316312b6a.png)

I also tried with the permission multiverse.teleport.self.w:WORLDNAME or multiverse.teleport.self.w.WORLDNAME, but nothing works.

Is the problem with the permissions I use ? Or is there any bug ? 

(I want to add that my permission plugin works fine with all my others plugins.)

Thank's in advance for your help !

**Comment by benwoo1110** [comment]
There is no per-world permissions at the moment. Probably only be implemented when we revamp the perm system, but it wont be anytime soon. Basically #1292
