### ISSUE TITLE
Help cant import

### ISSUE THREAD

**Issue by windetrsfugwq** [Multiverse/Multiverse-Core#2486]
### Information

* **Server version:** git-spigot-37d799b-3eb7236 (mc1.16.4) (implementing API version 1.16.4-r0.1-SNAPSHOT)

* **Full output of `/mv version -p`:**  cant 

* **Server log:** can t

### Help request

**Problem**
i am not abil to import

**What I have tried**
making the files but no

**Screenshots**

![Screenshot from 2020-11-11 18-39-20](https://user-images.githubusercontent.com/66659349/99330582-e6c8cc00-283c-11eb-8a39-89c4a73f5971.png)

**Comment by benwoo1110** [comment]
What can’t send your startup log? Please do so.

**Comment by windetrsfugwq** [comment]
![98871405-18532900-2432-11eb-8f93-95d6c52c5dd4](https://user-images.githubusercontent.com/66659349/99331892-4a52f980-283d-11eb-8c00-e58a3e2d8a42.png)

**Comment by windetrsfugwq** [comment]
ware do you gite the startup log?

**Comment by benwoo1110** [comment]
I think it was explained in the issue template. Server log found in `logs/latest.log`. Send it via https://hastebin.com/

**Comment by windetrsfugwq** [comment]
https://hastebin.com/ihupemahux.md

**Comment by benwoo1110** [comment]
That is completely cut into half also no no where near being a startup log. I can’t help if the information is not provide.

**Comment by benwoo1110** [comment]
Other things to note:
1. The world that you import must be generated on the same mc version as your server.
2. I suggest using papermc as your server software https://papermc.io/downloads

**Comment by windetrsfugwq** [comment]
wat do you mene

**Comment by benwoo1110** [comment]
I literally means what I say lol.... what do you not understand?

**Comment by benwoo1110** [comment]
Closing due to lack of information provided.
