### ISSUE TITLE
World Issue

### ISSUE THREAD

**Issue by HyperBo1YT** [Multiverse/Multiverse-Core#2488]
Hi, so I added a bedwars lobby map to my server and use Multiverse to import it and to get to it, here is the problem when I restart my server it clones the world again and make as new one, but as a different spawn, I don't know why this is happening is there a way to fix this issue? Since I want to keep it on one world. 
![Screenshot_20201123_235412](https://user-images.githubusercontent.com/74938636/100028616-413acd00-2de7-11eb-91d3-f9af7e4dd4c0.jpg) the one called BedLobby is the main one and then when we reset the server because of a rank issues we fixed it made a new world called bedlobby in lowercase and doesn't take us to the same world.

**Comment by benwoo1110** [comment]
Restarting the server shouldn’t result in any cloning of worlds. Also the screenshot has no context Bcu mv doesn’t have some web interface. And PLEASE follow the issue template.

**Comment by benwoo1110** [comment]
Anways, missing the entire template. Please fill it out and resubmit.
