### ISSUE TITLE
World Importing failed

### ISSUE THREAD

**Issue by ToxicMineNeedsHelp** [Multiverse/Multiverse-Core#2493]
Hey Multiverse team, Im having problems with importing world Idk if this is a bug or Im just doing something wrong, well I need to import my already made map that my builder made I tested to import it to my test world and it worked! So I tried importing it to my Bedwars server and it says its creating and then after that it will say a error and the server will crash, after it crashes multiverse doesn't work anymore so please help :)

**Comment by benwoo1110** [comment]
please follow the issue template. Also ensure the world you are trying to import is generated on the same mc version as your server.

**Comment by ToxicMineNeedsHelp** [comment]
I will send you a picture wait :)

**Comment by ToxicMineNeedsHelp** [comment]
I fixed it I just redownloaded Multiverse and restarted the server
