### ISSUE TITLE
A Problem

### ISSUE THREAD

**Issue by PmzHero** [Multiverse/Multiverse-Core#2495]
ahh my member cant go to other worlds with warps / bedwars / and and and / I Seted my rank to member with luckperms and it says warping to 'Warp Name' AND NOTHING HAPPENS pls tell me how to fix

**Comment by PmzHero** [comment]
Also members have acess perm

**Comment by benwoo1110** [comment]
1. mv doesnt have any warping commands.
2. Follow the issue template.
3. Be more detailed with all explaination.

**Comment by benwoo1110** [comment]
Closing as insufficient info is provided. If you feel like filling in the issue template, then open a new issue.
