### ISSUE TITLE
How would I do the following: (info in comments)

### ISSUE THREAD

**Issue by RhinoCodes** [Multiverse/Multiverse-Core#2496]
How would I go about the following:

- Users spawn in the world they die in

- Stop items from carrying from world to world

Thanks!

**Comment by benwoo1110** [comment]
1. use `/mvm set respawnWorld <respawnworldname> <deathworldname>`, in your case death and respawn world should be the same.
2. Use mv-inventories. https://dev.bukkit.org/projects/multiverse-inventories  https://github.com/Multiverse/Multiverse-Core/wiki/Basics-(Inventories)

**Comment by RhinoCodes** [comment]
Thanks!
