### ISSUE TITLE
world spawn

### ISSUE THREAD

**Issue by XtraKatYT** [Multiverse/Multiverse-Core#2497]
### Information

* **Server version:** minecraft 1.16.4

* **Full output of `/mv version -p`:** 

* **Server log:** 

### Help request

**Problem**
Don't know how to set a new world as the servers spawn

**What I have tried**
deleting the spawn world but i said it can't be deleted

**Screenshots**

**Comment by benwoo1110** [comment]
if its first spawn world, i.e. when player first join the server only, then just set the `firstspawnworld` in mv config.yml. If you are referring to always spawning on the same location on join, get a hub plugin or try our test build on join location #2460
