### ISSUE TITLE
Command block in 1 world changes the properties of every world on the server

### ISSUE THREAD

**Issue by BlueNerveTM** [Multiverse/Multiverse-Core#2500]
### Information

* **Server version:** git-Paper-293 (MC: 1.16.4)

* **Full output of `/mv version -p`:** https://paste.gg/p/anonymous/225ff15bddcf43e3a1ead7bff14a72f5

* **Server log:** https://gist.github.com/BlueNerveTM/11ce90a08c6ea9e606e5ee91f9e8a2eb

### Help request

**Problem**
Hello, I have an issue regarding command blocks when using multiverse.
I am trying to play a parkour map on a server where I also have different worlds (lobby, survival, creative, minigames) etc. The parkour map uses command blocks to set the weather, time etc. But my problem is that the weather or time changes across all of the multiverse worlds (which is bad because for example i need it to be nighttime in the lobby while the parkour map's command blocks change the time to DAY on every multiverse world on the server, and also added the night vision effect and now that is also present when switching to any multiverse world.)
now my question is, is it possible to change it so that commandblocks execute their command ONLY in the world that they have been placed in and not across every multiverse world? 

**What I have tried**
/time set night , doesnt work, stays day because of a commandblock executing the time set day command continuously on the parkour map

**Screenshots**
![image](https://user-images.githubusercontent.com/75436046/101225942-1aa44e00-3693-11eb-9ed5-bc263fc5b66e.png)

I am eagerly waiting for your answer, thanks!

**Comment by benwoo1110** [comment]
Its up to the command you run on the command block. MV cant and wont control the outcome of the commands. (unless its mv commands)
