### ISSUE TITLE
End portal not going back to survival world if user doesn't have a bed or home

### ISSUE THREAD

**Issue by opti21** [Multiverse/Multiverse-Core#2502]
### Information

* **Server version:** 
Paper version git-Paper-284(MC: 1.16.4)

* **Full output of `/mv version -p`:** 
https://paste.gg/p/anonymous/5393f5d175cc4170950d6a075b157e54

* **Server log:** 

### Help request

**Problem**

End portal isn't going back to survival world if user doesn't have a bed or home.

**What I have tried**

Tried linking the worlds together using MVNP

**Comment by benwoo1110** [comment]
try set `mvm set respawnworld <overworld> <endworld>`

**Comment by opti21** [comment]
That worked thank you!
