### ISSUE TITLE
Wiki issue: VoidGenerator is listed in "Custom Generator Plugins" page but it's not open source.

### ISSUE THREAD

**Issue by JasonTable** [Multiverse/Multiverse-Core#2509]
### Information

On the wiki page for [Custom Generator Plugins](https://github.com/Multiverse/Multiverse-Core/wiki/Custom-Generator-Plugins), it says at the top:

> Here you will find a list of open source generator plugins. If there is no source, the plugin will not be listed. Github is preferred for code hosting. Do not put JAR downloads here.

However the "VoidGenerator" plugin is listed which has no reference or link to the source code on its page. So it is assumed to be a closed-source plugin.

**Comment by benwoo1110** [comment]
Those Custom Generator Plugins are all not made by mv team, so it's up to that VoidGenerator plugin to make it code open source or not.

**Comment by JasonTable** [comment]
The issue is not with the plugin itself. It's with the wiki page being inconsistent because it says it lists open source plugins but not all the plugins listed are open source.

**Comment by benwoo1110** [comment]
Ah I see, it may need fixing, but its our lowest priority to do so atm, since the wiki is itself is open source and open to anyone to edit anyways.

**Comment by JasonTable** [comment]
Ah, I understand. I might go and make an edit then. I noticed one other thing on that page that might need fixing but I will probably just do that myself with an edit.
