### ISSUE TITLE
Scoreboard possibility?

### ISSUE THREAD

**Issue by TripleNothing** [Multiverse/Multiverse-Core#2512]
[Per world Scoreboard #1184](https://github.com/Multiverse/Multiverse-Core/issues/1184)
[Multiworld-Scoreboard #1209](https://github.com/Multiverse/Multiverse-Core/issues/1209)

I've never found an answer, or if it's impossible, but noticed running scoreboard independently across multiple worlds would not be easy, so it was ruled out. I did see a mention of grouping, such as teams, and was wondering if that would be a twist to pull such off.

Each world would be defined as a team, so the connected players would be grouped as such. The scoreboard would then display only that "team", being the players on the current world?

**Edit:** And it just crossed my mind that each world/"team" would need a different format/layout of what's to be displayed, which probably rules this out. :-/ Unless worlds/teams can be independently defined/referenced.

**Comment by benwoo1110** [comment]
It's not impossible, but I dont think multiverse-core wants to touch on scoreboards. If we ever implement it, it will be a new mv module. Also, plugins like featherboard already gives great customizability to scoreboards, and from what I can tell, you can Assign scoreboards based on groups, permissions, worlds with that plugin.
