### ISSUE TITLE
Error importing Spaced Named world 

### ISSUE THREAD

**Issue by ArcticRaven** [Multiverse/Multiverse-Core#2513]
### Information

git-Paper-325

https:/j.mp37mnKYV

Startup log attached [latest (2).log](https://github.com/Multiverse/Multiverse-Core/files/5701398/latest.2.log)

**Description**  
Importing of named world with spaces doesn't work properly/failed to import every time

**Steps to reproduce**  
Attempt to import a world with spaces in the name - we also tried various adaptations of the command to see if they would work as well. 

**Expected behavior**  
importing of the world

**Comment by benwoo1110** [comment]
world name with space should not be used, I thought I added a message to say it should be used. You should rename your world folder to not have spaces then import.  

if you want, you can give them aliases to change their name in the chat: https://github.com/Multiverse/Multiverse-Core/wiki/World-properties#alias
