### ISSUE TITLE
Gamerules reset on /mv regen

### ISSUE THREAD

**Issue by Darkweasam** [Multiverse/Multiverse-Core#2516]
### Information

* **Server version:**  1.16.4(324)

* **Full output of `/mv version -p`:**  4.1.0-b775

* **Server log:** there are no errors related to this issue

### Help request

**Problem**
Gamerules (such as KeepInv) resets when doing /mv regen

**What I have tried**
Looking through google, wiki checking if there is a way to keep flags

**Comment by benwoo1110** [comment]
This is expected as gamerule is stored in the world folder and, regening means deleting the world folder contents and re creating it. But I do feel this is a valid suggestion and may look into in time to come. Will mark it as open to PR for now.

**Comment by Darkweasam** [comment]
Is there any progress on this one? I am even willing to pay if someone makes it work

**Comment by benwoo1110** [comment]
@Darkweasam if you are still interested, here is a test build for it: https://github.com/Multiverse/Multiverse-Core/pull/2581#issuecomment-790387454. GameRules are now kept by default on world regen.

**Comment by Darkweasam** [comment]
@benwoo1110 works perfectly, thanks <3
