### ISSUE TITLE
Overworld music playing in End dimensions

### ISSUE THREAD

**Issue by Salsa24** [Multiverse/Multiverse-Core#2518]
### Information

* **Server version:** [23:47:21] [main/INFO]: [CHAT] This server is running Paper version git-Paper-344 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[23:47:21] [main/INFO]: [CHAT] Checking version, please wait...
[23:47:30] [main/INFO]: [CHAT] Previous version: git-Paper-207 (MC: 1.16.3)
[23:47:30] [main/INFO]: [CHAT] You are running the latest version

* **Full output of `/mv version -p`:** https://paste.gg/p/anonymous/52fe5514777b4192b2dafe01b147c294

### Help request

**Problem**
Music from the music.game namespace is playing in End dimensions, with the music.end namespace not seeming to trigger and play any tracks. The bug does not occur in Nether dimensions, as tracks from the correct namespaces are played in them.

**What I have tried**
I have tried replicating the issue in a vanilla singleplayer world and on a server running Paper version git-Paper-344 (concurrent with the server experiencing the issue) with no external plugins. The correct music is played in both of these cases. I have tried creating a new End world on the server and seeing if the issue continues to occur - the incorrect overworld tracks were still playing. I assume this is a Multiverse issue as a result; this bug occurred on the previous version of Paper (git-Paper-207 (MC: 1.16.3)) as well as prior to the Multiverse plugins being updated.

**Comment by nicegamer7** [comment]
This is most likely not a Multiverse issue. Please give Spigot a try, if it continues to happen, I'll report it to them.

**Comment by Salsa24** [comment]
Hi,

We switched over to Spigot just today and the bug is still occurring, but _only_ in End dimensions other than world_the_end (which is the server's first/original End). That world has the normal music.end rotation playing in it, while all other Ends still have the music.game issue.

**Server version:** [12:41:23] [main/INFO]: [CHAT] This server is running CraftBukkit version git-Spigot-628435a-6917945 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[12:41:23] [main/INFO]: [CHAT] Checking version, please wait...
[12:41:32] [main/INFO]: [CHAT] You are running the latest version

**Full output of /mv version -p:** https://j.mp/3rAgnWe

Please inform me if you need any other information (timings, etc.).

**Comment by Salsa24** [comment]
To add on to my previous comment, we just checked the behavior in Paper and it behaves the same as on Spigot (incorrect music in all dimensions except world_the_end).

**Comment by nicegamer7** [comment]
I've reported it to Spigot [here](https://hub.spigotmc.org/jira/browse/SPIGOT-6295).

**Comment by benwoo1110** [comment]
Closing as its not related to mv.
