### ISSUE TITLE
Not working with bukkit4fabric

### ISSUE THREAD

**Issue by anormalhedgehog** [Multiverse/Multiverse-Core#2520]
Multiverse-Core v4.2.3-SNAPSHOT-b821" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
 
After that nothing else happens it just makes the server freeze, i use bukkit4fabric to use carpet for other things that are usefull

**Comment by benwoo1110** [comment]
bukkit4fabric isnt a supported server type by mv, please use normal paper or spigot server.
