### ISSUE TITLE
Warning in the Server Console

### ISSUE THREAD

**Issue by Flearl** [Multiverse/Multiverse-Core#2521]
* **Server version:** Paper 1.16.4-345

mv version -p`: 4.2.2

* **Server log:** [03:17:59] [Server thread/WARN]: [Multiverse-Core] "Multiverse-Core v4.2.2-b812" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].

**Problem**
This is Coming in the Console when i starting the server

**Comment by benwoo1110** [comment]
See #2000
