### ISSUE TITLE
Buscript failed to load!

### ISSUE THREAD

**Issue by S4IVin** [Multiverse/Multiverse-Core#2529]
### Information

* **Server version:** This server is running Yatopia version git-Yatopia-"aaeb472" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

* **Full output of `/mv version -p`:** https://paste.gg/p/anonymous/58a6f2164733478e95d1317d40fc7aa6

* **Server log:** https://gist.github.com/S4IVin/a45a5b79e309fe832d60d605ce52a561

**Description**  
Simply when I start the server I get this warn: `[12:12:35 WARN]: [Multiverse-Core] Buscript failed to load! The script command will be disabled!`

**Steps to reproduce**  
1. Start the server

**Comment by S4IVin** [comment]
Also when I start the server I also noticed another warn:
`[12:12:33 WARN]: [Multiverse-Core]" Multiverse-Core v4.2.2-b812 "has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method" public void com.onarandombox.MultiverseCore. listeners.MVPortalListener.entityPortalCreate (org.bukkit.event.entity.EntityCreatePortalEvent) ", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main -].`

**Comment by benwoo1110** [comment]
Either due to using java 15 or a plugin conflict. Things you can try is with only mv plugins installed and also use paper instead of Yatopia. But honestly, if you don't use Buscript which most ppl don't, you can just ignore.

Same thing for your second issue. You can ignore it. #2000

**Comment by S4IVin** [comment]
> Either due to using java 15 or a plugin conflict. Things you can try is with only mv plugins installed and also use paper instead of Yatopia. But honestly, if you don't use Buscript which most ppl don't, you can just ignore.
> 
> Same thing for your second issue. You can ignore it. #2000

Ok!

**Comment by mrfloris** [comment]
Java16 and Paper 1.16.5, you get this as well. I have no idea what buscript is, never seen it before, setting it to false I guess.

**Comment by 811Alex** [comment]
I don't use buscript either, but I thought I'd confirm this too. The warning still appears on Java 16 (I'm migrating to it, in preparation for MC 1.17), latest version everything, Paper.

**Comment by benwoo1110** [comment]
If it just a log line without a stack trace of long error it’s fine. Buscript doesn’t work on java 16 so we just gracefully disable it for now.

**Comment by Meledosia** [comment]
It isn't an error OR a warning OR even Informational if Buscript isn't on the server so can't you just mute the warning unless Buscript exists????
