### ISSUE TITLE
Multiverse-Core create world crashing SERVER!!

### ISSUE THREAD

**Issue by WolfyRed** [Multiverse/Multiverse-Core#2530]
### Information

* **Server version:**
This server is running CraftBukkit version git-Spigot-f950f8e-0a81101 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)

* **Full output of `/mv version -p`:** 
Multiverse-Core Version: 2.5.0-b727
Bukkit Version: git-Spigot-f950f8e-0a81101 (MC: 1.11)

* **Server log:** * https://paste.gg/p/anonymous/7fc2205f9d42407a81603cb9660cbf52

### Details
I was **`<able / not able>`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
Putting a world already generated in a Minecraft 1.11 client is completely fine, while the server is off. It will load in when I use the command to load it in.

However, putting a world already generated in a Minecraft 1.11 client in the server while the server IS RUNNING, will result in saying "Loading world" with no "Finished loading" response + the server completely crashing 60 seconds later, only after loading the world with the command.

Creating a brand new world (/mv create) ALSO does the same trick as mentioned above, it will say "Loading..." until the server ultimately crashes and stops 1 minute later.

The only time I've seen this not occur while making a new world, is if it is a regular flatworld (custom flatworlds not tested yet). It loads in instantly.

**Steps to reproduce**  
/mv create WORLD world_type
Wait for it to say "Loading..."
Validate it hasn't responded after it said "Loading..."
You get kicked off of the server 1 minute later, unable to log back in, along with everyone else currently logged in to the server.

**Expected behavior**  
I expect it to act just like putting an already created world into the server, while it isn't running.

**Screenshots**  
![image](https://user-images.githubusercontent.com/66114400/104119667-08a37400-52ff-11eb-8e03-ff67ded7503d.png)
![2021-01-10_04 45 54](https://user-images.githubusercontent.com/66114400/104119674-135e0900-52ff-11eb-8dbb-1d9bf9b95f8e.png)
![2021-01-10_04 46 39](https://user-images.githubusercontent.com/66114400/104119688-2a9cf680-52ff-11eb-95cc-555ec0159057.png)
)

**Comment by benwoo1110** [comment]
Only think I can suggest is try with only mv plugins installed as you have many errors from other plugins. 1.11 is no longer supported by latest version of mv.

**Comment by WrongProgram1** [comment]
> Only thing I can suggest is try with only mv plugins installed as you have many errors from other plugins. 1.11 is no longer supported by the latest version of mv.

This didn't work either...

**Comment by benwoo1110** [comment]
Unfortunately 1.11 is a very old minecraft version and we no longer support it. Please use 1.13+.
