### ISSUE TITLE
Non OP can't use mvtp even with correct permissions

### ISSUE THREAD

**Issue by Henryws** [Multiverse/Multiverse-Core#2531]
### Information

* **Server version:** Paper-391 MC 1.16.4

* **Full output of `/mv version -p`:** https://j.mp/35tKmpg

* **Server log:** https://gist.github.com/Henryws/2804db35b126701f8378877d4c8024ef

**Description**  
Non OP users cannot use the command /hub which is an alias to mvtp hub even with the correct permissions  (using luckperm). 

**Steps to reproduce**  
Download Paper (papermc.io), multiverse core, and luckperms 

**Expected behavior**  
They should be able to teleport without a problem

**Screenshots**  
![9DA00F2A-69C9-48E5-AFED-69A07597FA44](https://user-images.githubusercontent.com/58742515/104139338-b3b93980-53a2-11eb-89de-ef2c98cdf618.jpeg)

**Comment by benwoo1110** [comment]
What exact permission you set? Do lp `lp verbose command <playername>  mvtp <worldname>` and send the result.

**Comment by Henryws** [comment]
![2021-01-10_18 27 34](https://user-images.githubusercontent.com/58742515/104139494-d26c0000-53a3-11eb-8a95-15aabdd8a575.png)

**Comment by benwoo1110** [comment]
Delete powerrank, it will cause issues with luckperms. If it doesn't fix your issues, the I suggest contacting luckperms support. Im using the latest beta build from  https://www.benergy10.dev/ tho I don't think it make a difference.
![image](https://user-images.githubusercontent.com/30431861/104139674-0b2dc880-53e8-11eb-97b8-dd625072246a.png)
