### ISSUE TITLE
How do you have Mutliverse generate worlds at lower version?

### ISSUE THREAD

**Issue by WolfyRed** [Multiverse/Multiverse-Core#2536]
### Information

* **Server version:** * 1.16.4

### Help request

**Why I'm here**
I don't know how to have world generate at 1.12 or 1.13 with the server being at version 1.16

**What I have tried**
I just... tried using a lower version. It worked fine, but newer plugins couldn't be used in the server. I was slightly limited.

**Relevant Information, might be important**
I do not want to just convert old version worlds to 1.16 and go from there, for a few reasons. 
If you must know the reasons, they are listed below here vv

**1.** New chunks will generate as 1.16 chunks (And newer terrain generation (like different mountains) will occur.)
**2.** New mobs will generate, especially in different areas.
**3.** Going back to the older version (to generate chunks in the old generation) may occur in corruption, as there's a problem with 1.13 to 1.14, and vice versa. 

**Screenshots**

I guess this is relevant.
This screenshot looks like normal 1.16 world generation if you don't look hard enough.
![2021-01-20_13 49 12](https://user-images.githubusercontent.com/66114400/105220872-53569480-5b26-11eb-9b65-2af49ac41716.png)

**Comment by benwoo1110** [comment]
It's just not possible with a single server. A 1.16 server can only generate a 1.16 world. If you have enough demand for multiple mc version typed worlds, I suggest using bungeecord and have multiple servers to achieve this.
