### ISSUE TITLE
World cannot load correctly

### ISSUE THREAD

**Issue by fhzzzs** [Multiverse/Multiverse-Core#2537]
I am trying to use the Mohist Server jar to open a server, but I found out that multiverse cannot load the DIM1 and DIM-1 correctly because the server store the dimensions like the single-player, all the dimensions are stored in one file, and when I create a new normal world, the nether portal will always teleport u back to the main world's nether instead of creating a new separate nether world.

**Comment by nicegamer7** [comment]
This is not something we can fix, and this is the reason Mohist is unsupported. MV only supports derivatives of CraftBukkit.
