### ISSUE TITLE
Nether Portal Error

### ISSUE THREAD

**Issue by XHyperDEVX** [Multiverse/Multiverse-Core#2542]
Hello, i have a Problem!

If I go into a Nether Portal without setting a Multiverse Portals Portal there, I get an Internal Server Error message and get kicked out of the game. See picture. When I rejoin I end up in an empty world with a strange construct, see picture 2. The following appears in the console: https://pastebin. com/RDcBN4mP How can I fix this?
Please answer me quickly! 

THX **HyperDEV**

![picture](https://user-images.githubusercontent.com/68189420/105627224-d1bc7a80-5e35-11eb-98f9-10c8adc789c0.png)
![Picture 2](https://user-images.githubusercontent.com/68189420/105627227-d6812e80-5e35-11eb-9820-14fec204c57d.png)

**Comment by benwoo1110** [comment]
The error doesn't really point anything to it being mv related. That being said, can you try with paper instead of spigot, https://papermc.io/downloads, and only mv plugins installed?

**Comment by XHyperDEVX** [comment]
Yes, only with Multiverse Portals and Multiverse Core the error is still there.

**Comment by benwoo1110** [comment]
And you tested with paper mc?

**Comment by XHyperDEVX** [comment]
I use a Nitrado Server! The servers are expensive, and I don't want to have to pay money for such a small thing. Is there also a free variant?

**Comment by benwoo1110** [comment]
Not sure what you mean, papermc is completely free to download and use.

**Comment by XHyperDEVX** [comment]
Okay, I’ll give it a try. I’ll call you when I’m finished

**Comment by XHyperDEVX** [comment]
I have now run Multiverse Core and Multiverse Portals on paper. The problem is still there.

**Comment by nicegamer7** [comment]
Please provide the full log instead of just the error. Also, please provide the link given by `/mvv -p`

**Comment by XHyperDEVX** [comment]
Is fixed, thx
