### ISSUE TITLE
[1.12.2] Multiverse doesn't load

### ISSUE THREAD

**Issue by rares1337** [Multiverse/Multiverse-Core#2545]
### Information

* **Server version:** 
![image](https://user-images.githubusercontent.com/75672400/105681464-d34f7680-5ef9-11eb-8469-3cdf1e26e992.png)

* **Full output of `/mv version -p`:** 
![image](https://user-images.githubusercontent.com/75672400/105681489-dcd8de80-5ef9-11eb-8257-87ff10d7d37b.png)

* **Server log:** 
https://gist.github.com/rares1337/0394a9b1bb6c54bcd93f8fcc8100a9cc
(i don't want my ip leaked)
### Help request

**Problem**
Multiverse doesn't load

**What I have tried**
Re-installing 

**Screenshots**
![image](https://user-images.githubusercontent.com/75672400/105681359-b61aa800-5ef9-11eb-8d1c-28f4f365db06.png)

**Log**

**Comment by nicegamer7** [comment]
You're using the wrong version for 1.12.

For `1.12.x`, you will need to use an older version of Multiverse for it to work. Multiverse 2.5.0 should work: https://dev.bukkit.org/projects/multiverse-core/files/2428161
