### ISSUE TITLE
Glitch when teleported

### ISSUE THREAD

**Issue by Semcurse** [Multiverse/Multiverse-Core#2546]
### Information

* **Server version:** 1.16.4

* **Full output of `/mv version -p`:** 

* **Server log:** 

### Help request

**Problem**

i got teleported into a different world, came back to the survival and all my stuff was gone
**What I have tried**

tried rebooting the game, nothing happened
**Screenshots**

**Comment by benwoo1110** [comment]
Issue template is present for a reason. Help yourself get help,  if you choose to ignore me and the issue template, providing little to no information for anyone to work on... then I'm sorry, I cant help you with the issue.
