### ISSUE TITLE
Config Resets when I change prefixchat: 'false'

### ISSUE THREAD

**Issue by Babobo88** [Multiverse/Multiverse-Core#2549]
### Information

* **Server version:** 

* **Full output of `/mv version -p`:** 

* **Server log:** 

### Details
I was **`<able / not able>`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  

**Steps to reproduce**  

**Expected behavior**  

**Screenshots**

**Comment by benwoo1110** [comment]
See #2443

You can also just use the commands to change config `/mv config prefixchat false`
