### ISSUE TITLE
Maven build failing notnull-instrumenter-maven-plugin Java 11

### ISSUE THREAD

**Issue by QuentiumYT** [Multiverse/Multiverse-Core#2559]
### Information

* **Machine version:** Debian 10, Java OpenJDK
```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)
```

### Help request

**Problem**
Compilation error while building Multiverse core latest commit (89fd700), it's stuck with `notnull-instrumenter-maven-plugin:0.6.8:instrument` package version

**What I have tried**
Both `mvn install` and `mvn clean package` were throwing this issue

**Solution**
Updated pom.xml file for compilation with new instrumenter plugin version that supports Java 11 since Sep 26
[Github here](https://github.com/osundblad/intellij-annotations-instrumenter-maven-plugin)

I set version to 1.0.0 and added
```
<configuration>
    <notNull>
        <param>org.jetbrains.annotations.NotNull</param>
        <param>javax.validation.constraints.NotNull</param>
    </notNull>
</configuration>
```
into the xml layout

The compiled plugin seems working fine

**Comment by benwoo1110** [comment]
I have tested and can confirm this issue, but before a PR to fix this, I kinda want to understand why this changed is need. @nicegamer7 @dumptruckman any thoughts?

**Comment by nicegamer7** [comment]
Does this only happen on Java 11?

Something that might be worth trying is updating the instrumenter and annotations to the latest versions. It doesn't really make sense to me that this is needed, but if updating doesn't work then I guess we can include the above snippet.
