### ISSUE TITLE
save player positions 

### ISSUE THREAD

**Issue by OtbordCord530** [Multiverse/Multiverse-Core#2561]
is there a setting in the config that saves where your position was after exiting the world? If not are you making one? if you are not making one are any plugins that fix this?

**Comment by benwoo1110** [comment]
Use multiverse inventories and enable last location. 

Relevant links:
 https://dev.bukkit.org/projects/multiverse-inventories
 https://github.com/Multiverse/Multiverse-Core/wiki/Basics-(Inventories)
https://github.com/Multiverse/Multiverse-Core/wiki/Shares-List-(Inventories)#optional-shares---must-be-enabled-via-mvinv-toggle-sharename-or-they-have-no-effect

**Comment by OtbordCord530** [comment]
Thx
