### ISSUE TITLE
Console messages sent to OP

### ISSUE THREAD

**Issue by SoMuchWessel** [Multiverse/Multiverse-Core#2562]
Hey there,

I got a problem.
If i have the line "broadcast-console-to-ops=false" in server.properties set to false.
But when i run a multiverse command, like '/mv load (world)' into the console, every user with OP gets this message in the chat on the server.

**Comment by benwoo1110** [comment]
You have to not give `bukkit.broadcast.admin` permission node (i.e. set it to false) with a permission plugin like luckperms if you don't want players to get the message.
