### ISSUE TITLE
Per world plugin [Suggestion]

### ISSUE THREAD

**Issue by Lennord** [Multiverse/Multiverse-Core#2563]
Hello, I have an idea for your plugin. I think it will be good if we can separate the plugins in world...

**Comment by benwoo1110** [comment]
We have considered it, and it has been deemed out of scope of mv.

The alternative solutions are:
1. Good plugins do have config options to disable features on certain worlds, or make them permission-based (see point 2)
2. With a permission plugin like luckperms, you can set permissions per world with its context feature, which can in most cases effectively make command/actions by plugin be per world.
3. If you have a sufficiently large server, use bungeecord to link multiple servers together where each of these servers can have different plugins and worlds.
