### ISSUE TITLE
Multiverse causing crash when debugging is active

### ISSUE THREAD

**Issue by fabmm** [Multiverse/Multiverse-Core#2566]
### Information

* **Server version:**  git-Paper-468 (MC: 1.16.5)

* **Full output of `/mv version -p`:** https://paste.dedimc.io/janatofija.md

* **Server log:** https://gist.github.com/fabmm/b363843a8dc1b4c05a92bb3374ca828b

### Details
I was **`not able** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
When a player joins the server, there is a brief period where they are loading IN-GAME, as in they are standing still but the chat is frozen, and based on their ping it takes some time till chat starts updating and inventory spawns, that's normal for bad pings... However, people with a really bad ping on my server, when they connect and they get kicked from the server for keepalive timeout, the server crashes and spams this in the logs

**Steps to reproduce**  
when a laggy user gets kicked out from keepalive timeout, or when someone connects then quickly disconnect before the server loads them i fully

**Expected behavior**  
not crash

**Comment by benwoo1110** [comment]
How are you getting that mv is causing a crash? I don't see any logs point to multiverse having errors or issues. The only issue I see is that you are doing Dynmap rendering while playing on the server at the same time which can overload your server as Dynmap rendering is quite performance expensive.

**Comment by fabmm** [comment]
Please avoid closing a ticket without getting information regarding your questions, it makes me feel like my words are being dismissed. I know for a fact that it has to be MV due to the fact that I did a binary plugin search and only when I remove MV does the server stop crashig.

**Comment by fabmm** [comment]
> How are you getting that mv is causing a crash? I don't see any logs point to multiverse having errors or issues. The only issue I see is that you are doing Dynmap rendering while playing on the server at the same time which can overload your server as Dynmap rendering is quite performance expensive.

Please avoid closing a ticket without getting information regarding your questions, it makes me feel like my words are being dismissed. I know for a fact that it has to be MV due to the fact that I did a binary plugin search and only when I remove MV does the server stop crashig.

**Comment by benwoo1110** [comment]
There is a 1001 issues to deal with, if you think its mv causing the issue, can you reproduce it with only mv installed? I will reopen the issue if this is the case. Thanks!
