### ISSUE TITLE
Teleport the closest player with Citizens

### ISSUE THREAD

**Issue by Impre-visible** [Multiverse/Multiverse-Core#2569]
### Information

* **Server version:** 1.16.4

* **Full output of `/mv version -p`:** https://paste.gg/p/anonymous/881dbb2e0b5145c090879821dbd80d29

* **Server log:** https://gist.github.com/Impre-visible/bd04ed65b02f0ec9c17d53046529c684

### Help request

**Problem**
I can't teleport the closest player with citizens

**What I have tried**
i have tried with @a or other but dont work

**Comment by benwoo1110** [comment]
There is no way for mv to know the player since the NPC is handled by citizens. afaik, citizens has its own placeholder for playername, I believe its `<P>`. If its not, then see their documentation or contact their support on it.
