### ISSUE TITLE
When I type a command I get an error....

### ISSUE THREAD

**Issue by Awerty16** [Multiverse/Multiverse-Core#2570]
When I type a command I get an error....
 That is not a valid environment.
This is the command I type: mv create "FastDiamonds" -s -93927677120122015 -g normal

### Information

* **Server version:** 

* **Full output of `/mv version -p`:** 

* **Server log:** 

### Help request

**Problem**

**What I have tried**

**Screenshots**

**Comment by nicegamer7** [comment]
The order of arguments matters. The command should be:
```
/mv create FastDiamonds normal -s -93927677120122015
```

**Comment by benwoo1110** [comment]
What nicegamer said should work. Next time, fill in the issue template. It's there for a reason.
