### ISSUE TITLE
Can you put a mod in a Multiverse core world?

### ISSUE THREAD

**Issue by Awerty16** [Multiverse/Multiverse-Core#2571]
Can you put a mod in a Multiverse core world?

### Information

* **Server version:** 

* **Full output of `/mv version -p`:** 

* **Server log:** 

### Help request

**Problem**

**What I have tried**

**Screenshots**

**Comment by benwoo1110** [comment]
mv doesnt control that. Naturally, mv is a bukkit plugin that only installs on bukkit based servers like spigot and paper. So you only can install other plugins that support this platform.

**Comment by Awerty16** [comment]
Is it possible?

**Comment by benwoo1110** [comment]
Nope, and out of scope of mv as well.

**Comment by Awerty16** [comment]
Oh
