### ISSUE TITLE
World gen in end and nether are broken

### ISSUE THREAD

**Issue by Domsmasher1** [Multiverse/Multiverse-Core#2572]
i will let the images and videos speak for them self
![2021-02-23_19 16 17](https://user-images.githubusercontent.com/47263379/108820126-d67c7600-760f-11eb-809d-75589ba8a90d.png)
![2021-02-23_19 17 10](https://user-images.githubusercontent.com/47263379/108820133-d8463980-760f-11eb-8c20-3005cbbbb0a6.png)
![2021-02-23_19 17 21](https://user-images.githubusercontent.com/47263379/108820138-d8ded000-760f-11eb-98f6-d68cad41c454.png)
![2021-02-23_19 18 16](https://user-images.githubusercontent.com/47263379/108820139-da0ffd00-760f-11eb-902b-0d98a36820a4.png)
![2021-02-23_19 16 03](https://user-images.githubusercontent.com/47263379/108820141-daa89380-760f-11eb-814a-aff0ad474b16.png)
https://streamable.com/t8w5xy

**Comment by benwoo1110** [comment]
The issue template is present for a reason, send the link from `/mv version -p`

**Comment by Domsmasher1** [comment]
https://paste.gg/p/anonymous/8488e9dcb48d4683a46f4136269bcb2b

**Comment by benwoo1110** [comment]
MV doesnt really do the chunk gen itself so I suggest trying on a new test server with latest papermc and mv only installed to see if you can reproduce this issue. https://papermc.io/downloads

**Comment by Domsmasher1** [comment]
we belive we know what happend, being that the world gen for the area was removed to it defaulted to overworld, the question we have is why it happend and im not sure if i could reproduce it if i tryed again

**Comment by benwoo1110** [comment]
Im still not convinced that this issue is cause by mv, it look either a rare spigot bug or world corrupt due to a server/computer crash.
