### ISSUE TITLE
Compile MV on  java 15

### ISSUE THREAD

**Issue by benwoo1110** [Multiverse/Multiverse-Core#2574]
There seems to be issue with junit and powermock when trying to compile mv on java 15, not sure why yet.

Things to note:
* Java 11 works fine. Anyone who can test with java version between 11-15 are welcomed.
* Exact java 15 version: openjdk-15 version 15.0.2
* Using mv plugin with mc server on JVM 15 shouldn't be an issue, just compiling.

Error logs: https://pastebin.com/40eLLUPa

**Comment by nicegamer7** [comment]
I fixed it locally. Just has to do with Buscript in the tests. PR soon (lol).

**Comment by nicegamer7** [comment]
Oh, it turns out there's something else that breaks it too 😁, @benwoo1110 are you okay if I push the fix to the `java-11` branch?

**Comment by benwoo1110** [comment]
Sure

**Comment by nicegamer7** [comment]
Alright, I pushed it. Let me know if it's working on your end.

**Comment by benwoo1110** [comment]
Fixed by #2573
