### ISSUE TITLE
Not able to enter a world

### ISSUE THREAD

**Issue by CactonGames** [Multiverse/Multiverse-Core#2577]
i made a seperate world from my main world with multiverse core(nether). wenn i tp to that world i get teleported back to my main world because i accidentaly built a netherportal where the player spawns. i cant enter the nether because i instantly get teleported back because it spawns me in the portal. how do i fix this?

**Comment by benwoo1110** [comment]
Not sure how you end up with that portal, but you can teleport to an exact destination instead of the world's spawn. See: https://github.com/Multiverse/Multiverse-Core/wiki/Destinations#exact-destinations
