### ISSUE TITLE
Nether Disables

### ISSUE THREAD

**Issue by GunsGoBangBang1** [Multiverse/Multiverse-Core#2579]
* **Server version:** 1.16.5 Paper

**Problem**
After a few minutes after a server restart the nether will unload and when i try to reload it, it loads and then disables after a few minutes. I also have auto load on

**What I have tried**
I have tried auto load but still no fix

**Comment by benwoo1110** [comment]
MV doesnt randomly upload worlds. I suggest trying with only the latest mc plugins install. The issue template is there for a reason, please fill it up.
