### ISSUE TITLE
Can't go to the nether

### ISSUE THREAD

**Issue by notdarkyy** [Multiverse/Multiverse-Core#2583]
[INFO] [Multiverse-Core] Bukkit Version: 3016-Spigot-73fb609-ea050e6 (MC: 1.16.5)

[INFO] [Multiverse-Core] Loaded Worlds: [{"MVWorld@2129674099":{"Gen":"null","Type":"NORMAL","Env":"THE_END","Name":"world_the_end"}}, {"MVWorld@1134561566":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world"}}, {"MVWorld@1012186558":{"Gen":"null","Type":"NORMAL","Env":"NETHER","Name":"world_nether"}}, {"MVWorld@1091434157":{"Gen":null,"Type":"NORMAL","Env":"NETHER","Name":"thenether"}}, {"MVWorld@229022119":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"thespawn"}}, {"MVWorld@1317902836":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"prison"}}]

I'm trying to set my nether portal outcome to "thenether" but dont know how to do it. The portal just doesnt tp me anywhere. I need help since this is a server with other people, and well, going to the nether is a big part of it.

**Comment by nicegamer7** [comment]
If nether portals are not working, it is most commonly because `allow-nether` is set to false in `server.properties`.

**Comment by notdarkyy** [comment]
> If nether portals are not working, it is most commonly because `allow-nether` is set to false in `server.properties`.

It's set to true, I forgot to mention, I deleted the original nether world so I could try to replace it... yeah, that didnt work.

**Comment by nicegamer7** [comment]
What do you mean by it didn't work?

**Comment by notdarkyy** [comment]
I mean that I couldn't set the nether to "thenether" and it ended in the nether not working because i deleted the current nether world.

**Comment by nicegamer7** [comment]
In that case, please open a new issue with the issue template fully filled. It's difficult for us to help when we don't have the required info.
