### ISSUE TITLE
Piglins arent spawning in my gold farm 

### ISSUE THREAD

**Issue by RizeUnlisted** [Multiverse/Multiverse-Core#2599]
### Information

* **Server version:** 

* **Full output of `/mv version -p`:** 

* **Server log:** 

### Help request

**Problem**

**What I have tried**

**Screenshots**

**Comment by RizeUnlisted** [comment]
![Goldfarm](https://user-images.githubusercontent.com/80503560/110893764-7863c880-835b-11eb-9a16-d246830b0de5.png)
An image of my gold farm (noone is on my server but the piglins arent spawning)

**Comment by benwoo1110** [comment]
Issue template is there for a reason, it's very hard to help of you are completely disregarding it.
