### ISSUE TITLE
Piglins not spawning

### ISSUE THREAD

**Issue by RizeUnlisted** [Multiverse/Multiverse-Core#2600]
### Information

* **Server version:** Paper Version git-Paper-546 (mc 1.16.5) (implementing api version 1.16.5-R0.1-SNAPSHOT) 

* **Full output of `/mv version -p`:** https://paste.gg/p/anonymous/6e3ac2bab0df41f7a81f7006db3d1607/revisions

* **Server log:** Done but I dont know how to share it

### Help request

**Problem**
Piglins not spawning

**What I have tried**
Turning on mobspawning(and mv mobspawning) and purging worlds

**Screenshots**

**Comment by benwoo1110** [comment]
Hi, can you test without any plugins installed (without mv as well). Or use a fresh server setup.

**Comment by RizeUnlisted** [comment]
Do you mean deleting all the plugins. Will it delete the worlds I have made?

**Comment by benwoo1110** [comment]
The world and plugin folder itself folder is still there, then it’s fine. Just remove the .jar

**Comment by RizeUnlisted** [comment]
I am doing it through aternos I'm not sure how that will affect it

**Comment by benwoo1110** [comment]
Doesn’t matter, as long as you only remove the .jar, just make a backup if you are worried.

**Comment by RizeUnlisted** [comment]
nvm it was in the wrong biome sorry for wasting your time
