### ISSUE TITLE
is there an option to enable keep inventory in all worlde

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [Multiverse/Multiverse-Core#2601]
### Information

* **Server version:** 

* **Full output of `/mv version -p`:** 

* **Server log:** 

### Help request

**Problem**

**What I have tried**

**Screenshots**

**Comment by benwoo1110** [comment]
keep inv is a vanilla gamerule. If you want keep inventory based on permission node, use essentials, they have such a feature.
