### ISSUE TITLE
event is Deprecated. "Server performance will be affected"

### ISSUE THREAD

**Issue by NDMR** [Multiverse/Multiverse-Core#2605]
Server version: Paper-567 (MC: 1.16.5)
Plugin version 4.2.2
Java version: 11

Console output:
[Multiverse-Core]: "Multiverse-Core v4.2.2-b812" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].

**Comment by benwoo1110** [comment]
#2000
