### ISSUE TITLE
Spawn point is being overridden by MV-Core

### ISSUE THREAD

**Issue by ZoomGC** [Multiverse/Multiverse-Core#2606]
I run an anarchy server on 1.12.2, anyway, I use the RandomSpawn plugin to, of course, spawn players in random locations within a 10000x10000 diameter, ranging from -5000,-5000 to 5000,5000 from 0,0, but the problem arises with mv-core, as it has spawn points set that cause people to spawn at specfic coordinates and can cause players to just fight constantly at that point when new people join, I would like to know if there's a way to disable these spawnpoints, preferrably per-world.
Thank you in advance.

-ZoomGC

**Comment by ZoomGC** [comment]
Would there also be a way to retain the player's postiton so when they teleport back into a world, they stay where they previously were

**Comment by benwoo1110** [comment]
Look into getting multiverse-inventories. 
https://dev.bukkit.org/projects/multiverse-inventories
https://github.com/Multiverse/Multiverse-Core/wiki/Basics-(Inventories)

> When teleporting between worlds, the default behavior is to go to the spawn of the world. This can be changed; however, it's not perfect. You'll require Multiverse-Inventories (same version as your MV-Core). Once installed, you'll need to toggle last_location on by doing `/mvinv toggle last_location.`
