### ISSUE TITLE
World Import

### ISSUE THREAD

**Issue by Grumpypjs08** [Multiverse/Multiverse-Core#2607]
### Information

* **Server version:This server is running Magma version 1bc8635 (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forage Version 14.23.5.2855** 

* **Full output of `/mv version -p`: https://paste.gg/p/anonymous/003acb6bc0ce44bca823a995649a9e3e** 

* **Server log: https://gist.github.com/Grumpypjs08/28431f5725c5d770ee90221a48fa76a7** 

### Help request

**Problem**
When I try to import I get an error

**What I have tried**
Nothing

**Screenshots**

**Comment by benwoo1110** [comment]
__**MC 1.12**__ You will need to use an older version of Multiverse - 2.5.0 should work https://dev.bukkit.org/projects/multiverse-core/files/2428161

but note, any forge + magma hacked servers are not supported.
