### ISSUE TITLE
ERROR Could not pass event AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by BboyZeroOne** [Multiverse/Multiverse-Core#2608]
### Information

* **Server version:** 
This server is running Paper version git-Paper-575 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 1 version(s) behind
Previous version: git-Paper-547 (MC: 1.16.5)

* **Full output of `/mv version -p`:** https://pastebin.com/xCTGrber

* **Server log:** https://gist.github.com/BboyZeroOne/bd3a91398c23d77907bf55c04948581c

### Details
I was not able to use the plugin CMI's "/cmi commandspy" when I tried to enable it. It produces the error log after i execute the command.

**Description**  
https://gist.github.com/BboyZeroOne/da6b00b85e92e46f035e9e63b0436f2f

**Steps to reproduce**  
1. Type "/cmi commandspy"

**Expected behavior**  
Commandspy feature should work as expected

**Screenshots**  
https://imgur.com/a/fVVVjlc

**Comment by benwoo1110** [comment]
mv's prefixchatformat is just very basic to add world name, there isn't `%vault_prefix%` or any other placeholders. I suggest you use a chat plugin of your liking to format chat and have vault prefix.
