### ISSUE TITLE
hey, i have a problem. I have a Spigot 1.16.5 server with MV running on it - but I have the problem that when I switch between multiple worlds I have got my inventory of the other world and when I want to switch, I am teleported to the spawn of the world. Someone help??

### ISSUE THREAD

**Issue by nevthereal** [Multiverse/Multiverse-Core#2609]
### Information

* **Server version:** 

* **Full output of `/mv version -p`:** 

* **Server log:** 

### Help request

**Problem**

**What I have tried**

**Screenshots**

**Comment by benwoo1110** [comment]
Please report issues properly. Do not put your entire question as the title and ignore the issue template. Thanks.
