### ISSUE TITLE
It says that my world is unloaded !!!

### ISSUE THREAD

**Issue by Pabluten7** [Multiverse/Multiverse-Core#2613]
### Information

* **Server version:* 1.8

* **Full output of `/mv version -p`:** 

* **Server log:** 

### Help request

**Problem**
when i try to tp to other world or to set de spawn it doesn't recognice it, it appers like 'unloaded'

**What I have tried: to **
 i haven't try anything

**Screenshots**
 
![image](https://user-images.githubusercontent.com/82288274/114283143-8f740400-9a48-11eb-9228-8dd533481e9f.png)
![image](https://user-images.githubusercontent.com/82288274/114283169-a9ade200-9a48-11eb-8e0b-d71b25a602cf.png)

**Comment by benwoo1110** [comment]
MC 1.8.x You will need to use an even older version of Multiverse - 2.5 should work (not the same as 2.5.0): https://dev.bukkit.org/projects/multiverse-core/files/898527

NOTE: We no longer officially support v2.5, use at your own discretion.
