### ISSUE TITLE
I need to use the original portals to connect to the normal world and nether and the end

### ISSUE THREAD

**Issue by EdwardXiaoran** [Multiverse/Multiverse-Core#2615]
I hope that part of the normal world can have its own "nether" and "The END" , and use the original nether portals and The end portals to connect with each other . How can I do this now . If the current version does not support this , I hope you can update to add this feature , we really need it .

**Comment by benwoo1110** [comment]
Get Multiverse-NetherPortals.

https://dev.bukkit.org/projects/multiverse-netherportals
https://github.com/Multiverse/Multiverse-Core/wiki/Basics-(NetherPortals)
