### ISSUE TITLE
Healt and Hunger bar are different between the nether and overworld

### ISSUE THREAD

**Issue by slavstic** [Multiverse/Multiverse-Core#2616]
I installed basically all multiverse plugins, and I used the Nether Portals one to link the correct nethers to the correct overworlds, but realized that the hunger, health and experience change between them. I don't know if this is a bug or if it's how I set up the plugins, but this is not what I wanted. Any advice on what to do?

**Comment by benwoo1110** [comment]
Since you said "basically all multiverse plugins" I assume you installed mv-inv. If so, read up on how to set it up https://github.com/Multiverse/Multiverse-Core/wiki/Basics-(Inventories)
