### ISSUE TITLE
Remember last player position.

### ISSUE THREAD

**Issue by hlnebula** [Multiverse/Multiverse-Core#2618]
### Feature request

**Feature description**

Add a setting in the worlds.yml file called remembered last player position.￼ so when people teleport to that world spawn at their last location.￼ I know about the optional share that kind of does that but that applies to all worlds this would only apply to one world. The only way to apply that optional share to a single world is kind of buggy.￼

**Comment by hlnebula** [comment]
Also add per world teleport permissions. Because right now it's either people can teleport to every world. Well they can't teleport to any world. And you can't really use the enforced access thing for this. I want people to be able to access the nether and end but I don't want them to be able to just teleport there.￼￼￼￼￼

**Comment by benwoo1110** [comment]
mvinv already has a last location feature, as for per world teleport it's tracked here #2621. 

In the future, please don't have multiple topics in a single issue.
