### ISSUE TITLE
Each time a player dies, they repeatly receive the items they had when they last exited the server

### ISSUE THREAD

**Issue by poly000** [Multiverse/Multiverse-Core#2623]
### Information

* **Server version:** 

```
[22:27:22 INFO]: This server is running Yatopia version git-Yatopia-ver/1.16.5-26 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[22:27:22 INFO]: Checking version, please wait...
```

* **Full output of `/mv version -p`:** 

https://paste.gg/p/anonymous/31561c4b37a94bdf9107f69238c52779

* **Server log:** 

https://gist.github.com/poly000/ee40c9d86f227ac7b21252aaa02df4b4

### Help request

**Problem**

Each time a player dies, they receive the items they had when they last exited the server

**What I have tried**

I tried disable KeepInvotory (by /gamerule and /mvgamerule), but nothing changes,

**Screenshots**

**Comment by benwoo1110** [comment]
Inventories isn't something managed by Multiverse-Core.

1. Test with only mv plugins installed
2. Yatopia is unstable, test with latest version of papermc https://papermc.io/downloads

**Comment by poly000** [comment]
Thanks. I found this bug was caused by SkyBlock, not MultiVerse.
