### ISSUE TITLE
Can't turn keepInventory to false

### ISSUE THREAD

**Issue by aokichangaming** [Multiverse/Multiverse-Core#2625]
### Information

* **Server version:**  This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

* **Full output of `/mv version -p`:**  [INFO] [Multiverse-Inventories] Multiverse-Inventories Version: 2.5.0-SNAPSHOT-b444

[INFO] [Multiverse-Inventories] First Run: false

[INFO] [Multiverse-Inventories] Using Bypass: false

[INFO] [Multiverse-Inventories] Default Ungrouped Worlds: false

[INFO] [Multiverse-Inventories] Using GameMode Profiles: false

[INFO] [Multiverse-Inventories] === Groups ===

[INFO] [Multiverse-Inventories] default: {Worlds: [world], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}

[INFO] [Multiverse-Inventories] survival: {Worlds: [world_the_end, world_nether, survival, pvp], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}

[INFO] [Multiverse-Inventories] survival2: {Worlds: [nether2, end2, survival2], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}

[INFO] [Multiverse-Inventories] creative: {Worlds: [creative], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}

[INFO] [Multiverse-Inventories] hardmode: {Worlds: [hardmode_nether, hardmode_the_end, hardmode], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}

[INFO] [Multiverse-Core] [Multiverse-Core] Multiverse-Core Version: 1.1

[INFO] [Multiverse-Core] [Multiverse-Core] Bukkit Version: git-Spigot-dcd1643-e60fc34 (MC: 1.12.2)

[INFO] [Multiverse-Core] [Multiverse-Core] Loaded Worlds: [{"MVWorld@1626367118":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"Hardmode"}}, {"MVWorld@2041335272":{"Gen":"null","Type":"NORMAL","Env":"NETHER","Name":"Nether2"}}, {"MVWorld@1253008826":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"PVP"}}, {"MVWorld@1937084353":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"Survival"}}, {"MVWorld@281166133":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"Survival2"}}, {"MVWorld@194678216":{"Gen":"null","Type":"NORMAL","Env":"THE_END","Name":"Hardmode_the_end"}}, {"MVWorld@984198068":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world"}}, {"MVWorld@1702699175":{"Gen":"null","Type":"NORMAL","Env":"THE_END","Name":"world_the_end"}}, {"MVWorld@1739857620":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"Creative"}}, {"MVWorld@941570855":{"Gen":"null","Type":"NORMAL","Env":"NETHER","Name":"world_nether"}}, {"MVWorld@1335677851":{"Gen":"null","Type":"NORMAL","Env":"NETHER","Name":"Hardmode_nether"}}, {"MVWorld@1139321559":{"Gen":"null","Type":"NORMAL","Env":"THE_END","Name":"end2"}}]

[INFO] [Multiverse-Core] [Multiverse-Core] Multiverse Plugins Loaded: 2

[INFO] [Multiverse-Core] [Multiverse-Core] Economy being used: Essentials Economy

[INFO] [Multiverse-Core] [Multiverse-Core] Permissions Plugin: Bukkit Permissions (SuperPerms)

[INFO] [Multiverse-Core] [Multiverse-Core] Dumping Config Values: (version 2.9)

[INFO] [Multiverse-Core] [Multiverse-Core] messagecooldown: 5000

[INFO] [Multiverse-Core] [Multiverse-Core] teleportcooldown: 1000

[INFO] [Multiverse-Core] [Multiverse-Core] worldnameprefix: true

[INFO] [Multiverse-Core] [Multiverse-Core] worldnameprefixFormat: [%world%]%chat%

[INFO] [Multiverse-Core] [Multiverse-Core] enforceaccess: true

[INFO] [Multiverse-Core] [Multiverse-Core] displaypermerrors: true

[INFO] [Multiverse-Core] [Multiverse-Core] teleportintercept: true

[INFO] [Multiverse-Core] [Multiverse-Core] firstspawnoverride: true

[INFO] [Multiverse-Core] [Multiverse-Core] firstspawnworld: world

[INFO] [Multiverse-Core] [Multiverse-Core] debug: 0

[INFO] [Multiverse-Core] [Multiverse-Core] Special Code: FRN002

[INFO] [Multiverse-Core] [Multiverse-Inventories] Multiverse-Inventories Version: 2.5.0-SNAPSHOT-b444

[INFO] [Multiverse-Core] [Multiverse-Inventories] First Run: false

[INFO] [Multiverse-Core] [Multiverse-Inventories] Using Bypass: false

[INFO] [Multiverse-Core] [Multiverse-Inventories] Default Ungrouped Worlds: false

[INFO] [Multiverse-Core] [Multiverse-Inventories] Using GameMode Profiles: false

[INFO] [Multiverse-Core] [Multiverse-Inventories] === Groups ===

[INFO] [Multiverse-Core] [Multiverse-Inventories] default: {Worlds: [world], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}

[INFO] [Multiverse-Core] [Multiverse-Inventories] survival: {Worlds: [world_the_end, world_nether, survival, pvp], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}

[INFO] [Multiverse-Core] [Multiverse-Inventories] survival2: {Worlds: [nether2, end2, survival2], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}

[INFO] [Multiverse-Core] [Multiverse-Inventories] creative: {Worlds: [creative], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}

[INFO] [Multiverse-Core] [Multiverse-Inventories] hardmode: {Worlds: [hardmode_nether, hardmode_the_end, hardmode], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}

[INFO] [Multiverse-Core] [Multiverse-NetherPortals] Multiverse-NetherPortals Version: 2.4-b530

[INFO] [Multiverse-Core] [Multiverse-NetherPortals] World links: {world_nether=Survival, Nether2=Survival2, Survival=world_nether, Survival2=Nether2}

[INFO] [Multiverse-Core] [Multiverse-NetherPortals] Nether Prefix:

[INFO] [Multiverse-Core] [Multiverse-NetherPortals] Nether Suffix: _nether

[INFO] [Multiverse-Core] [Multiverse-NetherPortals] Special Code: FRN001

[INFO] com.onarandombox.MultiverseCore.utils.webpaste.PasteFailedException: java.io.FileNotFoundException: http://pastie.org/pastes

[INFO] [Multiverse-Core] Version info dumped here: Error posting to service

* **Server log:**  https://gist.github.com/aokichangaming/51b22279c13aff5f4f23607ae236e56c

### Help request

**Problem**
 I can't turn keepInventory to false in my three worlds hardmode, hardmode_nether, and hardmode_the_end.

**What I have tried**
 I've tried using /mv gamerule keepInventory false & /gamerule keepInventory false in the worlds but it hasn't worked.

**Screenshots**

**Comment by benwoo1110** [comment]
What does it say when you run /mv gamerule keepInventory false? Also does the change reflect in /mv gamerules? 

Another possibility is the essentials has the ability to cause keep inventory to by bypassed.

**Comment by aokichangaming** [comment]
> What does it say when you run /mv gamerule keepInventory false? Also does the change reflect in /mv gamerules?
> 
> Another possibility is the essentials has the ability to cause keep inventory to by bypassed.

It says "Success! Gamerule keepInventory was set to false". And yes, the change is reflected in /mv gamerules. It says that keepInventory is false.

**Comment by benwoo1110** [comment]
It sounds like another plugin is causing it. Can you reproduce the issue with only mv plugins installed?

**Comment by aokichangaming** [comment]
I can try to see if I can reproduce the issue with only mv plugins installed.

**Comment by aokichangaming** [comment]
I got rid of every plugin except my Multiverse plugins. I was able to actually lose my items when I died in my world Hardmode. So it does sound like another plugin is causing the problem.
