### ISSUE TITLE
Unable to create nether worlds in PaperMC

### ISSUE THREAD

**Issue by aclare92** [Multiverse/Multiverse-Core#2627]
### Information

* **Server version:** This server is running Paper version git-Paper-642 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

* **Full output of `/mv version -p`:** https://paste.gg/p/anonymous/546cd652124940ac9db1e8ff3f09a2c4

* **Server log:** https://gist.githubusercontent.com/aclare92/f6c0700dff4cec40889cf9384af2b470/raw/4594dcfe62416645641b67f3310cf05324880310/latest.log

### Help request

**Problem**
Unable to create a nether world when running the /mv create command

**Repro Steps**
- Create a new fresh folder locally
- Add PaperMC version 1.16.5-642
- Start server
- Stop server
- Add multiverse-core, multiverse-netherportals and multiverse-inventories
- Start server
- Create a nether portal and go to nether, correctly loads [world_nether]
- Go back through nether portal, back to [world]
- Run "/mv create creative normal"
- Run /mv tp creative
- Correctly in [creative]
- Run "/mv create creative_nether nether"
- Create a nether portal and go to nether, world is a nether world but the world type is normal
- Fly (spectator mode) above the nether roof and see "overworld daylight" in screenshot attached

**What I have tried**
I tried the same steps above on a Spigot server to test and these worked fine and I have multiple nether worlds as expected.

**Screenshots**
Changing to spectator mode and flying above the nether roof, you can see the area is "overworld" and not the nether "atmosphere"
![2021-05-03_14 16 17](https://user-images.githubusercontent.com/6871661/116880822-5c252f00-ac1a-11eb-8d26-679dee016aee.png)

**Comment by benwoo1110** [comment]
If spigot works without issues, you may want to report the bug to papermc.

**Comment by aclare92** [comment]
Ah, sorry, is this not going to be a specific multiverse issue? Even with me running a multiverse command to generate these worlds?

**Comment by benwoo1110** [comment]
If it works on one server software but not the other, it likely some issue with that server software causing it. MV has not change how the world create works in a very long time as well, tho not impossible, unlikely that MV will suddenly cause such an issue.

**Comment by aclare92** [comment]
Ok, perfect, thank you very much. Additionally, thanks for the rapid response :thumbsup:

**Comment by aclare92** [comment]
[https://github.com/PaperMC/Paper/issues/5568](url)
