### ISSUE TITLE
Multiverse issue while trying to teleport to arenas

### ISSUE THREAD

**Issue by McDonaldsEnergy** [Multiverse/Multiverse-Core#2628]
Error:
`10.05 16:48:33 [Server] Startup [20:48:33 ERROR]: Could not pass event PlayerTeleportEvent to Multiverse-Core v2.5-b699
10.05 16:48:33 [Server] INFO org.bukkit.event.EventException
10.05 16:48:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:658) [custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:236) [custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at me.abhi.practice.command.impl.management.arena.ArenaCommand.arenaTp(ArenaCommand.java:189) [mPractice.jar:?]
10.05 16:48:33 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
10.05 16:48:33 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
10.05 16:48:33 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
10.05 16:48:33 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
10.05 16:48:33 [Server] INFO at me.abhi.practice.command.CommandFramework.handleCommand(CommandFramework.java:98) [mPractice.jar:?]
10.05 16:48:33 [Server] INFO at me.abhi.practice.command.CommandFramework.onCommand(CommandFramework.java:64) [mPractice.jar:?]
10.05 16:48:33 [Server] INFO at me.abhi.practice.command.BukkitCommand.execute(BukkitCommand.java:51) [mPractice.jar:?]
10.05 16:48:33 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) [custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:732) [custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1181) [custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:996) [custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:43) [custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) [custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265]
10.05 16:48:33 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_265]
10.05 16:48:33 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:881) [custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:382) [custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:820) [custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:721) [custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
10.05 16:48:33 [Server] INFO Caused by: java.lang.NullPointerException
10.05 16:48:33 [Server] INFO at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerTeleport(MVPlayerListener.java:178) ~[?:?]
10.05 16:48:33 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
10.05 16:48:33 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
10.05 16:48:33 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
10.05 16:48:33 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
10.05 16:48:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[custom.jar:1.8.8-R0.1-SNAPSHOT]
10.05 16:48:33 [Server] INFO ... 29 more`
### Information

* **Server version:** BlockSpigot 1.8.8 (Bukkit Version: 1.8.8-R0.1-SNAPSHOT (MC: 1.8.8))

* **Full output of `/mv version -p`:** * `
10.05 17:14:41 [Server] Startup [21:14:41 INFO]: [Multiverse-Core] [Multiverse-Core] Multiverse-Core Version: 2.5-b699
10.05 17:14:41 [Server] Startup [21:14:41 INFO]: [Multiverse-Core] [Multiverse-Core] Bukkit Version: 1.8.8-R0.1-SNAPSHOT (MC: 1.8.8)
10.05 17:14:41 [Server] Startup [21:14:41 INFO]: [Multiverse-Core] [Multiverse-Core] Loaded Worlds: [{"MVWorld@1984103684":{"Gen":"null","Type":"NORMAL","Env":"THE_END","Name":"world_the_end"}}, {"MVWorld@1369429502":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"world"}}, {"MVWorld@1594873558":{"Gen":"null","Type":"FLAT","Env":"NORMAL","Name":"Arenas"}}]
10.05 17:14:41 [Server] Startup [21:14:41 INFO]: [Multiverse-Core] [Multiverse-Core] Multiverse Plugins Loaded: 0
10.05 17:14:41 [Server] Startup [21:14:41 INFO]: [Multiverse-Core] [Multiverse-Core] Economy being used: Simple Item Economy
10.05 17:14:41 [Server] Startup [21:14:41 INFO]: [Multiverse-Core] [Multiverse-Core] Permissions Plugin: Bukkit Permissions (SuperPerms)
10.05 17:14:41 [Server] Startup [21:14:41 INFO]: [Multiverse-Core] [Multiverse-Core] Dumping Config Values: (version 2.9)
10.05 17:14:41 [Server] Startup [21:14:41 INFO]: [Multiverse-Core] [Multiverse-Core]  messagecooldown: 5000
10.05 17:14:41 [Server] Startup [21:14:41 INFO]: [Multiverse-Core] [Multiverse-Core]  teleportcooldown: 1000
10.05 17:14:41 [Server] Startup [21:14:41 INFO]: [Multiverse-Core] [Multiverse-Core]  worldnameprefix: true
10.05 17:14:41 [Server] Startup [21:14:41 INFO]: [Multiverse-Core] [Multiverse-Core]  worldnameprefixFormat: [%world%]%chat%
10.05 17:14:41 [Server] Startup [21:14:41 INFO]: [Multiverse-Core] [Multiverse-Core]  enforceaccess: true
10.05 17:14:41 [Server] Startup [21:14:41 INFO]: [Multiverse-Core] [Multiverse-Core]  displaypermerrors: true
10.05 17:14:41 [Server] Startup [21:14:41 INFO]: [Multiverse-Core] [Multiverse-Core]  teleportintercept: true
10.05 17:14:41 [Server] Startup [21:14:41 INFO]: [Multiverse-Core] [Multiverse-Core]  firstspawnoverride: true
10.05 17:14:41 [Server] Startup [21:14:41 INFO]: [Multiverse-Core] [Multiverse-Core]  firstspawnworld: world
10.05 17:14:41 [Server] Startup [21:14:41 INFO]: [Multiverse-Core] [Multiverse-Core]  debug: 1
10.05 17:14:41 [Server] Startup [21:14:41 INFO]: [Multiverse-Core] [Multiverse-Core] Special Code: FRN002`

* **Server log:** https://gist.github.com/McDonaldsEnergy/b4acf22798ae5945cd30bc77d1f01e69

### Details
I was not able to teleport to an arena with mPractice, by doing: /arena tp Mountains <-- It put an error in chat, and mPractice errors.

**Description** 
Kind of in details, you can't teleport to any arenas. You can teleport to the world itself, like /mvtp <world>, and it works. But when you try to do /arena tp it won't work for some reason. And I've tried all that would make sense (I think). Please help

**Steps to reproduce**  
I'm not even sure, I deleted Vault and that's it. I put Vault back in the server just incase that was the issue, but it's still erroring. I even tried to use the original spigot,

**Expected behavior**  
I expect to just teleport to the arena or queue a match, I do /arena tp to test if queuing would work. Since if you can't teleport to an arena manually, you can't teleport automatically when you queue a match. And so far I was correct, you can't queue at all

**Comment by benwoo1110** [comment]
This issue looks like arena plugin (or at least not by mv), `/arena Tp Mountains` is not an mv command.
