### ISSUE TITLE
mv.bypass.gamemode.* doesnt work on my configuration :(

### ISSUE THREAD

**Issue by geilmaker** [Multiverse/Multiverse-Core#2630]
### Information

* **Server version:** Paper 1.16.5

* **Full output of `/mv version -p`:** https://paste.gg/p/anonymous/f6de09f5c97a4cbf8871715312bcaeeb

### Help request

**Problem**

Im using LuckPerms as permission plugin and the permission mv.bypass.gamemode.* doesn't work, im still changing my gamemode on world change automatically.... I dont know why and cant find anything usefull in web....

**What I have tried**
Just adding the permission that should work and looking over the config, but couldnt find anything.... I just want admins not to change from gamemode 3 to gamemode 0 cause they want to spectate somebody else in another world....

**Comment by benwoo1110** [comment]
Unless you can prove that the permission `mv.bypass.gamemode.*` is set to true and correctly applied to the user in luckperms, and that this issue still occurs when only luckperms and mv plugin is installed. I'm not convinced this issue is with mv.

**Comment by benwoo1110** [comment]
Just tested on my server - cant reproduce the issue.

**Comment by geilmaker** [comment]
Wait, it sounds like im stupid, sorry.... What do you mean with mv plugin? ...sorry ^^

**Comment by benwoo1110** [comment]
multiverse plugins

**Comment by geilmaker** [comment]
Okay well, thank you, ill try to remove all other plugins and test it, I thought this is general issue.... :) Sorry for that....

**Comment by benwoo1110** [comment]
99% of the time is just you set the permission wrong.

**Comment by geilmaker** [comment]
Im very sorry for wasting your time....
But thank you, with your help I found the issue, I have a plugin named GamemodeInventories and in this config file you can set survival on world change and that was set on true.... thanks for your help and sorry for this time waste :(
