### ISSUE TITLE
Have the multiverse.core.version permission default to false

### ISSUE THREAD

**Issue by WhatsTheBadNews** [Multiverse/Multiverse-Core#2637]
### Feature request

**Feature description**
Have the `multiverse.core.version` permission default to false. Regular players don't need it and shouldn't have it unless explicitly given the permission. 

**How the feature is useful**
I assume there are quite a few server owners who are unware of the command/permission. I also assume most of them are not going negate the permission, as they are unware of it/what it can do. Given these 2 (reasonable) assumptions, most servers with Multiverse will allow any player to get access to their seed info, plugin list, and other config options simply by logging in and doing `/mv version -p --include-plugin-list`

**Comment by benwoo1110** [comment]
https://github.com/Multiverse/Multiverse-Core/commit/1c483148dc978365937c620800fa58180dfcf7f8
