### ISSUE TITLE
Updating from PaperMC 1.16.3 to 1.16.5 - Urgent Help

### ISSUE THREAD

**Issue by LegoMySuperEgo** [Multiverse/Multiverse-Core#2641]
https://pastebin.com/LSvtGW4Z

Multiverse keeps telling me it's disabled in-game.
Someone recommended I legitimately need to change the title of every single freaking world on this server to be lowercase.  It's been fine on 1.16.3 for the past two years.  Why would this be the case **now** and do I actually need to do this in the configs for every plugin manually?  Is there a quicker way to do it?

**Comment by benwoo1110** [comment]
Paper updated such that you can only a-z./_- for world names. `<` is not allowed. Nothing mv can do.

**Comment by LegoMySuperEgo** [comment]
I changed all the folders and changed the names in the Multiverse core worlds.yml but when I loaded the server all the builds were deleted and Multiverse re-generated the worlds with the capitals so I had duplicates of each....do I have to edit out capitals it for EVERY plugin on my server as well? 
I am also now getting
org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
