### ISSUE TITLE
BUG when new player join the server

### ISSUE THREAD

**Issue by kedavlar** [Multiverse/Multiverse-Core#2642]
VERSION PLUGIN: 4.2.3 b845

SERVER VERSION: airplane 125aff7 1.16.5

INFO: every time i restart the server i have this error https://pastebin.com/ww6nYMYi 
and every time when new player join ther server the first time my console spam this
error https://pastebin.com/WHTtqtHy

I only create one void world with MV with void generator.

**Comment by benwoo1110** [comment]
Can you produce this with papermc?

Also "World name should not contain spaces or special characters".

**Comment by kedavlar** [comment]
i cant change jar for now :/ and i know .. i cant use space in world name.. the world with space are going to reset soon. my preoccupation is the error when someone new join and the firt error on start up

**Comment by benwoo1110** [comment]
Update mv to the latest dev build, the line that the error occur is a comment and not code for some reason...

**Comment by kedavlar** [comment]
i updated after reload as u can see on first pastebin, the second screen is in old version.. im waiting new player for see if change something

**Comment by benwoo1110** [comment]
Don't reload. Stop your server, update mv .jar and start your server. Then send new logs.

**Comment by kedavlar** [comment]
for now, the error with new player join is fixed.. tomorrow ill test with restart if is all okay

**Comment by kedavlar** [comment]
ok, with stop and restart , the error on start remain the same as before

**Comment by benwoo1110** [comment]
I still cannot reproduce with only mv-core installed on a fresh papermc server.

**Comment by kedavlar** [comment]
no problem, for now its only error on consol but the plugin work fine
