### ISSUE TITLE
Tests Fail on Java 16

### ISSUE THREAD

**Issue by AngelOtiz** [Multiverse/Multiverse-Core#2644]
mvn -v

> Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
> Maven home: /opt/maven
> Java version: 16.0.1, vendor: Private Build, runtime: /usr/lib/jvm/java-16-openjdk-amd64
> Default locale: en, platform encoding: UTF-8
> OS name: "linux", version: "5.8.0-1035-aws", arch: "amd64", family: "unix"

java --version

> openjdk 16.0.1 2021-04-20
> OpenJDK Runtime Environment (build 16.0.1+9-Ubuntu-120.04)
> OpenJDK 64-Bit Server VM (build 16.0.1+9-Ubuntu-120.04, mixed mode, sharing)

I'm getting this result, trying to do mvn install on Multiverse-Core-4.2.3-SNAPSHOT:

> [ERROR] Errors:
> [ERROR]   PowerMock internal error: Should never throw exception at this level
> [INFO]
> [ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0
> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  15.193 s
> [INFO] Finished at: 2021-06-16T22:16:16Z
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project Multiverse-Core: There are test failures.

> [ERROR] There was an error in the forked process
> [ERROR] Test mechanism :: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @4434095f
> [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
> [ERROR] Test mechanism :: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @4434095f

> [ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:657)
> [ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:283)
> [ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
> [ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1161)
> [ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1002)
> [ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:848)
> [ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
> [ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
> [ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
> [ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
> [ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
> [ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
> [ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
> [ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
> [ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
> [ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
> [ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
> [ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
> [ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
> [ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
> [ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
> [ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
> [ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
> [ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
> [ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
> [ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

**Comment by benwoo1110** [comment]
Did you try to change any code?

**Comment by benwoo1110** [comment]
Likely caused by https://github.com/powermock/powermock/issues/1099, will need to see if they fix it or any workaround can be done. Since this is just for test, want to point out mv itself still works fine when running on a Java 16 minecraft server.

**Comment by AngelOtiz** [comment]
I haven't tried to change any code, just downloaded maven from https://maven.apache.org/download.cgi and installed it. Then I cloned multiverse-core from git and ran mvn install.
I would like to use the latest build, but it seems that I don't get any .jar file when the tests fail...

**Comment by benwoo1110** [comment]
Either skip the test (not sure the exact way to do that) or use java 8-15 to o compile. You will still be able to use mv on java 16 no issues.

**Comment by cs8425** [comment]
I skip the test by `mvn package -Dmaven.test.skip=true` and build success with Java 16.
reference: https://stackoverflow.com/questions/7456006/maven-package-install-without-test-skip-tests
