### ISSUE TITLE
java.lang.IllegalStateException: Invalid pool element found

### ISSUE THREAD

**Issue by zhro** [Multiverse/Multiverse-Core#2651]
* **Server version:** CraftBukkit version 3161-Spigot-f773da8-f81f499 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

* **Full output of `/mv version -p`:** https://j.mp/3wUF9lQ

* **Server log:** https://gist.github.com/zhro/f9c8f517a34dd14e64532e4206963561

### Details
I was **`<able / not able>`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  

Tested on latest Multiverse-Core 4.3.1 snapshot with Spigot 1.17

There is an unknown error that is occurring when the server starts up since updating to 1.17. This error does not appear when creating a new world. It only appeared when updating an existing wold.

**Steps to reproduce**  

Occurs in the log when the server starts up.

**Comment by benwoo1110** [comment]
I suggest reporting this to spigot or paper, doesn't look like something caused by mv.

**Comment by benwoo1110** [comment]
Can this issue be reproduced in 1.16?

**Comment by benwoo1110** [comment]
https://bugs.mojang.com/browse/MC-227945
