### ISSUE TITLE
Team prefix don't show in chat

### ISSUE THREAD

**Issue by comand100vip** [Multiverse/Multiverse-Core#2654]
### Information

* **Server version:** This server is running CraftBukkit version 2991-Bukkit-f3f3094 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) Checking version, please wait.. You are 26 version(s) behind

* **Full output of `/mv version -p`:** https://paste.gg/p/anonymous/8222a25427aa4378be4d5fa421b593c0

* **Server log:** https://gist.github.com/comand100vip/899a4d593f535b3f1e0db6659ad81246

### Help request

**Problem**
I setup role using /team command that make my nick gold and add dark red prefix [OWNER], but it soesn't work.

**What I have tried**
I switch world prefix to false (Don't show **_(hub)_**<comand100vip> test)

**Screenshots**
![AHHHHHH](https://user-images.githubusercontent.com/82674108/123511671-f89c0880-d682-11eb-96b2-affbe1016772.png)->

**Comment by benwoo1110** [comment]
MV has nothing to do with team prefix.

**Comment by comand100vip** [comment]
But Mv hide it.

**Comment by comand100vip** [comment]
/team is minecraft build in command and multiverse disable it in chat

**Comment by benwoo1110** [comment]
No mv doesn't hide such things, not sure how you are concluding that?

**Comment by comand100vip** [comment]
I just want that it display prefix that I set with /team command.
Then I run server without Mv see what happend:
![image](https://user-images.githubusercontent.com/82674108/123512482-fee0b380-d687-11eb-9945-af7e456e152d.png)
