### ISSUE TITLE
Hi, can someone please help me with this?

### ISSUE THREAD

**Issue by M0rky123** [Multiverse/Multiverse-Core#2655]
### Information

* **Server version:**  This server is running Paper version git-Paper-416 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT) 

* **Full output of `/mv version -p`:**  https://paste.gg/p/anonymous/1c9734b39a25419ba42880f9ad96d4d3

* **Server log:**  https://gist.github.com/M0rky123/770b6106832ae136ab7a4fb1481c7797

### Help request

**Problem**
 I did not notice any problem, but it is stated here to contact the authors.

**What I have tried**
Nothing until now.

**Comment by benwoo1110** [comment]
#2000
