### ISSUE TITLE
Original Default Unknown To Multiverse?

### ISSUE THREAD

**Issue by DylanWriter** [Multiverse/Multiverse-Core#2656]
### Information

* **Server version:**  1.16.5

* **Full output of `/mv version -p`:**  1.16

* **Server log:** 

### Help request

**Problem**
 I downloaded the multiverse plugin after a long time of being in one world, but i cant get back to my original world unless my player dies. i did "/mv info" while being in the original default world but it said, it does exists but the plugin doesnt know it is there? it tells me i can import it by using "/mv import" but it just doesnt work. it tells me it is doing it but then it says failed?

**What I have tried**
 i have searched for a while now for a solution. at first it is because the default world name has a space in it. The world name is "K_G World" so i did /mv import "K_G World" then /mv import "K_G World" normal
and that works until it says failed? i am not sure what else to do...

**Screenshots**
 
![Screenshot_2](https://user-images.githubusercontent.com/86581724/123571722-c09bdf00-d7c2-11eb-997a-5528a2041bf6.png)
![Screenshot_3](https://user-images.githubusercontent.com/86581724/123571723-c1347580-d7c2-11eb-9de3-84e1b21710ef.png)
![Screenshot_4](https://user-images.githubusercontent.com/86581724/123571725-c1cd0c00-d7c2-11eb-9cfd-508425f8a3b1.png)
![Screenshot_5](https://user-images.githubusercontent.com/86581724/123571728-c265a280-d7c2-11eb-89ea-e88b6188da51.png)
![Screenshot_6](https://user-images.githubusercontent.com/86581724/123571730-c396cf80-d7c2-11eb-9b50-4a5d65ad6b3d.png)
![Screenshot_1](https://user-images.githubusercontent.com/86581724/123571732-c396cf80-d7c2-11eb-9713-ed73b1b45d02.png)

**Comment by benwoo1110** [comment]
Worldname should not have spaces in them.

**Comment by DylanWriter** [comment]
> Worldname should not have spaces in them.

i thought that at first but if i do that then it doesnt work at all. it says to add the quotes if the world name has a space in it

**Comment by benwoo1110** [comment]
No, it's just not allowed. Nothing to with putting quotes or not.

**Comment by DylanWriter** [comment]
> No, it's just not allowed. Nothing to with putting quotes or not.

![1](https://user-images.githubusercontent.com/86581724/123576412-47a08580-d7ca-11eb-86f9-01ae9ba5821b.png)
![2](https://user-images.githubusercontent.com/86581724/123576453-4a02df80-d7ca-11eb-9d6d-b9d9b7da07bd.png)
![3](https://user-images.githubusercontent.com/86581724/123576496-4c653980-d7ca-11eb-8987-ec1486f29cca.png)
![4](https://user-images.githubusercontent.com/86581724/123576533-4e2efd00-d7ca-11eb-8693-559cf5e6fb44.png)

**Comment by benwoo1110** [comment]
You need to rename your worlds somehow. Usually by manually changing the folder name. The import command syntax you sue is also wrong see https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#import-command

**Comment by DylanWriter** [comment]
> You need to rename your worlds somehow. Usually by manually changing the folder name. The import command syntax you use is also wrong see https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#import-command

okay thankyou, ill have to work around it
