### ISSUE TITLE
Unexpected terrain generation change in the end

### ISSUE THREAD

**Issue by C4K3** [Multiverse/Multiverse-Core#2658]
On updating the paper version the end generation changes unexpectedly, causing chunk borders. This is triggered by a paper update, but only happens if multiverse-core is installed. If no plugins are installed, then the terrain generation does not change on this update. I'm aware it may not be a bug in multiverse-core itself, but as it only happens with multiverse-core installed, it's at least some kind of faulty interaction possibly caused by a change in craftbukkit. I'm opening this issue here for now.

# How to reproduce

Download [paper 1.16.5 build 593](https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/593/downloads/paper-1.16.5-593.jar) and install multiverse-core (I tested with an earlier 4.2.3 build as well as latest commit bbd9211845e137fa9a8fa74bedb10914a755c0cd).

Go to anywhere in the end outside the main island (I teleported to 5000 5000)

Disconnect and close the server.

Start the server up again on paper [1.16.5 build 594](https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/594/downloads/paper-1.16.5-594.jar).

Travel a short distance from where you were before, and you should see chunk borders, indicating that the terrain generation has changed, as if the seed was changed.

# Discussion

This is the commit that changed between the two paper builds: https://github.com/PaperMC/Paper/commit/a08be1ec7cfe9a7aa134a073382407c53264fcba

The only craftbukkit change in that rebase is https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/9294ebbf051ad7340d7e37265568884439973a4a

**Comment by benwoo1110** [comment]
Does it occur on the latest papermc version? And also if only that commit starts the issue likely a server software bug.

**Comment by C4K3** [comment]
Paper 1.16.5 build 779 has the same behavior as build 594, so yes. I haven't tested on 1.17.

**Comment by benwoo1110** [comment]
I suggest report to paper or spigot and see what they say. (don't tone the report and make it seem like mv is the issue else they will just close it lol)

**Comment by C4K3** [comment]
I've now managed to reproduce it with no plugins, so definitely not multiverse-core related.

Will report directly to spigot. Thanks!
