### ISSUE TITLE
Server crashes on world unload

### ISSUE THREAD

**Issue by debian-user-france1** [Multiverse/Multiverse-Core#2659]
### Information

* **Server version:** 

* **Full output of `/mv version -p`:** 

* **Server log:** 

### Details
I was **`<able / not able>`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  

**Steps to reproduce**  

**Expected behavior**  

**Screenshots**  

I am using the newest version with 1.17 spigotmc
When I join a world it prob. works and loads the world but if I unload the world the server crashes (shut down)

**Comment by benwoo1110** [comment]
Follow the issue template with logs of errors and other requested information.

**Comment by debian-user-france1** [comment]
WHY DO YOU CLOSE THIS

WICH LOG

**Comment by benwoo1110** [comment]
>Information
>
> Server version:
>
> Full output of /mv version -p:
>
> Server log:

Provide proper information with valid prove of the issue. Then yes, it shall be reopen.

**Comment by debian-user-france1** [comment]
Ok server log...

I currently can't reproduce it but I assume it is:

1. Server issues crash because ticks too high or
2. Server issues crash because no free ram (But that's special because unloading a world shouldn't use much RAM)

But the bug persists. It depends on how many players are online and how much RAM is free on the server (there is also a nextcloud server running)
I copy the Server log if it happens again

**Comment by debian-user-france1** [comment]
Please open that again

Here your log:
http://cloud.bubicloud.ch/nextcloud/index.php/s/8e3qtwn69ZtWbTZ (no ssl)

All that can happen because of RAM wich is confusing but the Server tries to issue a command and it can't be executed because the zram is uncompressing the cached files wich struggles the server and ticks slow down so - well - the server issues a crash

**Comment by debian-user-france1** [comment]
Now futher Information:

Unloading a world wich isn't loaded will cause a world load and directly a world unload
That's the problem! 
Please fix this in your mod

**Comment by debian-user-france1** [comment]
OMG YOUR MOD IS SO BAD WHY DO YOU LOAD THE F???? WORLD IF I PRESS UNLOAD

**Comment by benwoo1110** [comment]
I tested creating and unloading of worlds on a papermc 1.17 server. No issue faced, you can see the logs at https://paste.lucko.me/uwoCxYOFJz

**Comment by debian-user-france1** [comment]
Can't reproduce? I'm not the only one with this bug

reproduce:
Server has 1700M RAM (-xms)
Use for example a Virtual Machine to give the Ubuntu System (20.10, ubuntu.com) 4G RAM
Open Firefox Browser to simulate consumption of nextcloud
Set up and install zram* (sudo apt install zram* -y)
Start zram service: sudo service ((press TAB)) start
start Minecraft Server
generate a world (1.17) named world2 (normal world, pvp on difficulty NORMAL, AUTOLOAD OFF)
stop the server
start the server (make sure you hav min. 80% of ram used when started)
log in to the server
make 3 command blocks: mvunload world2, mvload world2, mvtp @p world2
place a button for every command block
Load world2
tp into it
unload world2
load it again
unload twice
Now at least the server should crash!

**Comment by debian-user-france1** [comment]
Oh maybe you want to skip some steps but please use the OS ubuntu

**Comment by debian-user-france1** [comment]
please reopen it BECAUSE NO FIX

Why do you close things with no fix

**Comment by benwoo1110** [comment]
Haven't seen the crash log and stacktrace btw.

**Comment by debian-user-france1** [comment]
??

**Comment by debian-user-france1** [comment]
http://cloud.bubicloud.ch/nextcloud/index.php/s/8e3qtwn69ZtWbTZ (no ssl)

**Comment by benwoo1110** [comment]
You keep saying there is an error and crash by mv. But the logs you send has no errors by mv.

**Comment by debian-user-france1** [comment]
mv causes the errors - server never crashed before and was more smooth

It is using a function by spigot that crashes the server (maybe syntax wrong or - unloading a world that's not prob. loaded

**Comment by benwoo1110** [comment]
I see you said command blocks, duplicate of #2560

**Comment by debian-user-france1** [comment]
ok I'll take a look
