### ISSUE TITLE
Mohist - importing already existing "labworld" seems to import a void

### ISSUE THREAD

**Issue by DNAmaster10** [Multiverse/Multiverse-Core#2661]
I'm currently migrating my server from Paper to Mohist to support mods, and i've encountered an issue with multiverse. The world im trying to import functions as our lab world, and is an earth map. The earth world is a void world, with a replica of earth inside it. For whatever reason, when importing the world and then teleporting it, it spawns you in a complete void. Thanks if anyone can help, and let me know if you need links to other files.

**Comment by benwoo1110** [comment]
MV as well as most plugins doesn’t support mohist due to its instability.
