### ISSUE TITLE
Change default `defaultportalsearch` to `true`

### ISSUE THREAD

**Issue by phemmer** [Multiverse/Multiverse-Core#2662]
### Feature request

**Feature description**

Change the default value of `defaultportalsearch` to `true`.

**How the feature is useful**

Currently the functionality of overriding the default portal search radius causes a major difference in behavior when Multiverse-Core is installed. In vanilla (including Spigot & Paper), the portal search radius in overworld is 128, and the search radius in the nether is 16. However due to the default `defaultportalsearch: false` and `portalsearchradius: 128`, the server ends up using 128 for the portal search radius in both Overworld and Nether. This means that a player would have to go >1024 blocks in overworld to create a portal that won't link to an existing one in the Nether.

Tracking down why my portals weren't working correctly was a pain. And I'm not sure why this functionality is within Multiverse-Core's area of responsibility. But as it causes a major deviation from vanilla behavior, I'm proposing that the functionality be turned off by default.

Issue reproduced on Paper 1.17 build # 75 & Multiverse-Core 4.2.3

**Comment by benwoo1110** [comment]
Yea most ppl doesn’t need custom portal radius. Can you open a pr for it? (So I can approve and not need another dev)

**Comment by benwoo1110** [comment]
https://github.com/Multiverse/Multiverse-Core/blob/bbd9211845e137fa9a8fa74bedb10914a755c0cd/src/main/java/com/onarandombox/MultiverseCore/MultiverseCoreConfiguration.java#L110

**Comment by nicegamer7** [comment]
I can approve it for you @benwoo1110.

@phemmer, I assume this is in MV because while Paper allows you to change these values, Spigot does not.

**Comment by benwoo1110** [comment]
I think no one raise it is Bcu portal search config in mv didnt do anything until my recent commit loll

**Comment by nicegamer7** [comment]
Yeah lol, it's been broken since 1.13, but you fixed it recently.
