### ISSUE TITLE
I updated from 1.16.5 to 1.17.1

### ISSUE THREAD

**Issue by CookingStick** [Multiverse/Multiverse-Core#2670]
When loading worlds that aren't the overworld, nether, and end I get massive amounts of errors. I could only grab these errors. Please look at the paste bin below.

https://pastebin.com/4nA38xMc

Spigot multiverse-core v 4.3.0

**Comment by benwoo1110** [comment]
Report the issue to the devs of the server software that you are using.

**Comment by CookingStick** [comment]
Define what you mean by server software please.

> Report the issue to the devs of the server software that you are using.

**Comment by benwoo1110** [comment]
paper, spigot etc... the software that runs your entire Minecraft server itself.

**Comment by CookingStick** [comment]
Ah gotcha sorry xD. Im using Spigot.
