### ISSUE TITLE
Minecraft 1.17.1

### ISSUE THREAD

**Issue by vdl19** [Multiverse/Multiverse-Core#2674]
Hello, I am currently testing the DEV versions to try to prepare my server for Minecraft 1.17.1 but my server is crashing during startup with the Dev versions of Multiverse-core at the moment.

>.... [11:44:22 INFO]: [Multiverse-Core] Enabling Multiverse-Core v4.3.1-SNAPSHOT-b856
>.... [11:44:22 WARN]: [Multiverse-Core] "Multiverse-Core v4.3.1-SNAPSHOT-b856" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
>.... [11:44:22 INFO]: [Multiverse-Core] We are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
>.... [11:44:22 INFO]: -------- World Settings For [world] --------
>.... [11:44:22 INFO]: Experience Merge Radius: 3.0
>.... [11:44:22 INFO]: Cactus Growth Modifier: 100%
>.... [11:44:22 INFO]: Cane Growth Modifier: 100%
>.... [11:44:22 INFO]: Melon Growth Modifier: 100%
>.... [11:44:22 INFO]: Mushroom Growth Modifier: 100%
>.... [11:44:22 INFO]: Pumpkin Growth Modifier: 100%
>.... [11:44:22 INFO]: Sapling Growth Modifier: 100%
>.... [11:44:22 INFO]: Beetroot Growth Modifier: 100%
>.... [11:44:22 INFO]: Carrot Growth Modifier: 100%
>.... [11:44:22 INFO]: Potato Growth Modifier: 100%
>.... [11:44:22 INFO]: Wheat Growth Modifier: 100%
>.... [11:44:22 INFO]: NetherWart Growth Modifier: 100%
>.... [11:44:22 INFO]: Vine Growth Modifier: 100%
>.... [11:44:22 INFO]: Cocoa Growth Modifier: 100%
>.... [11:44:22 INFO]: Bamboo Growth Modifier: 100%
>.... [11:44:22 INFO]: SweetBerry Growth Modifier: 100%
>.... [11:44:22 INFO]: Kelp Growth Modifier: 100%
>.... [11:44:22 INFO]: Entity Activation Range: An 16 / Mo 24 / Ra 48 / Mi 8 / Tiv true
>.... [11:44:22 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
>.... [11:44:22 INFO]: Custom Map Seeds: Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
>.... [11:44:22 INFO]: Max TNT Explosions: 100
>.... [11:44:22 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
>.... [11:44:22 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
>.... [11:44:22 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
>.... [11:44:22 INFO]: Item Merge Radius: 2.5
>.... [11:44:22 INFO]: Item Despawn Rate: 6000
>.... [11:44:22 INFO]: View Distance: 6
>.... [11:44:22 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
>.... [11:44:22 INFO]: Zombie Aggressive Towards Villager: true
>.... [11:44:22 INFO]: Nerfing mobs spawned from spawners: false
>.... [11:44:22 INFO]: Mob Spawn Range: 5
>.... [11:44:22 INFO]: Preparing start region for dimension minecraft:world
>.... [11:44:24 INFO]: Preparing spawn area: 0%
>.... [11:44:24 INFO]: Preparing spawn area: 0%
>.... [11:44:24 INFO]: Preparing spawn area: 0%
>.... [11:44:24 INFO]: Preparing spawn area: 0%
>.... [11:44:24 INFO]: Preparing spawn area: 0%
>.... [11:44:25 INFO]: Preparing spawn area: 0%
>.... [11:44:25 INFO]: Time elapsed: 2675 ms
>.... [11:44:25 INFO]: -------- World Settings For [eventpvp] --------
>.... [11:44:25 INFO]: Experience Merge Radius: 3.0
>.... [11:44:25 INFO]: Cactus Growth Modifier: 100%
>.... [11:44:25 INFO]: Cane Growth Modifier: 100%
>.... [11:44:25 INFO]: Melon Growth Modifier: 100%
>.... [11:44:25 INFO]: Mushroom Growth Modifier: 100%
>.... [11:44:25 INFO]: Pumpkin Growth Modifier: 100%
>.... [11:44:25 INFO]: Sapling Growth Modifier: 100%
>.... [11:44:25 INFO]: Beetroot Growth Modifier: 100%
>.... [11:44:25 INFO]: Carrot Growth Modifier: 100%
>.... [11:44:25 INFO]: Potato Growth Modifier: 100%
>.... [11:44:25 INFO]: Wheat Growth Modifier: 100%
>.... [11:44:25 INFO]: NetherWart Growth Modifier: 100%
>.... [11:44:25 INFO]: Vine Growth Modifier: 100%
>.... [11:44:25 INFO]: Cocoa Growth Modifier: 100%
>.... [11:44:25 INFO]: Bamboo Growth Modifier: 100%
>.... [11:44:25 INFO]: SweetBerry Growth Modifier: 100%
>.... [11:44:25 INFO]: Kelp Growth Modifier: 100%
>.... [11:44:25 INFO]: Entity Activation Range: An 16 / Mo 24 / Ra 48 / Mi 8 / Tiv true
>.... [11:44:25 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
>.... [11:44:25 INFO]: Custom Map Seeds: Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
>.... [11:44:25 INFO]: Max TNT Explosions: 100
>.... [11:44:25 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
>.... [11:44:25 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
>.... [11:44:25 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
>.... [11:44:25 INFO]: Item Merge Radius: 2.5
>.... [11:44:25 INFO]: Item Despawn Rate: 6000
>.... [11:44:25 INFO]: View Distance: 6
>.... [11:44:25 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
>.... [11:44:25 INFO]: Zombie Aggressive Towards Villager: true
>.... [11:44:25 INFO]: Nerfing mobs spawned from spawners: false
>.... [11:44:25 INFO]: Mob Spawn Range: 5
>.... [11:44:25 INFO]: Preparing start region for dimension minecraft:eventpvp
>.... [11:44:27 ERROR]: No key dirt_provider in MapLike[{decorators:[],foliage_placer:{height:3,offset:0,radius:2,type:"minecraft:blob_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:oak_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:1},trunk_placer:{base_height:4,height_rand_a:2,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:oak_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key sapling_provider in MapLike[{decorators:[],foliage_placer:{height:3,offset:0,radius:2,type:"minecraft:blob_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:oak_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:1},trunk_placer:{base_height:4,height_rand_a:2,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:oak_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key foliage_provider in MapLike[{decorators:[],foliage_placer:{height:3,offset:0,radius:2,type:"minecraft:blob_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:oak_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:1},trunk_placer:{base_height:4,height_rand_a:2,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:oak_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]
>.... [11:44:27 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.<init>(PoolElementStructurePiece.java:54) ~[?:?]
at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[patched_1.17.1.jar:git-Paper-107]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:717) ~[?:?]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:272) ~[?:?]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[patched_1.17.1.jar:git-Paper-107]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[patched_1.17.1.jar:git-Paper-107]
at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.17.1.jar:git-Paper-107]
at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.17.1.jar:git-Paper-107]
>.... [11:44:27 ERROR]: No key dirt_provider in MapLike[{decorators:[],foliage_placer:{height:3,offset:0,radius:2,type:"minecraft:blob_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:oak_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:1},trunk_placer:{base_height:4,height_rand_a:2,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:oak_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key sapling_provider in MapLike[{decorators:[],foliage_placer:{height:3,offset:0,radius:2,type:"minecraft:blob_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:oak_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:1},trunk_placer:{base_height:4,height_rand_a:2,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:oak_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key foliage_provider in MapLike[{decorators:[],foliage_placer:{height:3,offset:0,radius:2,type:"minecraft:blob_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:oak_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:1},trunk_placer:{base_height:4,height_rand_a:2,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:oak_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]
>.... [11:44:27 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.<init>(PoolElementStructurePiece.java:54) ~[?:?]
at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[patched_1.17.1.jar:git-Paper-107]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:717) ~[?:?]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:272) ~[?:?]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[patched_1.17.1.jar:git-Paper-107]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[patched_1.17.1.jar:git-Paper-107]
at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.17.1.jar:git-Paper-107]
at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.17.1.jar:git-Paper-107]
>.... [11:44:27 ERROR]: No key dirt_provider in MapLike[{decorators:[],foliage_placer:{height:3,offset:0,radius:2,type:"minecraft:blob_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:oak_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:1},trunk_placer:{base_height:4,height_rand_a:2,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:oak_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key sapling_provider in MapLike[{decorators:[],foliage_placer:{height:3,offset:0,radius:2,type:"minecraft:blob_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:oak_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:1},trunk_placer:{base_height:4,height_rand_a:2,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:oak_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]; No key foliage_provider in MapLike[{decorators:[],foliage_placer:{height:3,offset:0,radius:2,type:"minecraft:blob_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:oak_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:1,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:1},trunk_placer:{base_height:4,height_rand_a:2,height_rand_b:0,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:oak_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}}]
>.... [11:44:27 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.<init>(PoolElementStructurePiece.java:54) ~[?:?]
at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[patched_1.17.1.jar:git-Paper-107]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:717) ~[?:?]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:272) ~[?:?]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[patched_1.17.1.jar:git-Paper-107]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[patched_1.17.1.jar:git-Paper-107]
at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.17.1.jar:git-Paper-107]
at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.17.1.jar:git-Paper-107]
>.... [11:44:27 INFO]: Preparing spawn area: 0%
>.... [11:44:27 INFO]: Preparing spawn area: 0%
>.... [11:44:27 INFO]: Preparing spawn area: 0%
>.... [11:44:27 INFO]: Preparing spawn area: 0%
>.... [11:44:27 INFO]: Preparing spawn area: 0%
>.... [11:44:27 INFO]: Time elapsed: 2243 ms
>.... [11:44:27 INFO]: -------- World Settings For [crea] --------
>.... [11:44:27 INFO]: Experience Merge Radius: 3.0
>.... [11:44:27 INFO]: Cactus Growth Modifier: 100%
>.... [11:44:27 INFO]: Cane Growth Modifier: 100%
>.... [11:44:27 INFO]: Melon Growth Modifier: 100%
>.... [11:44:27 INFO]: Mushroom Growth Modifier: 100%
>.... [11:44:27 INFO]: Pumpkin Growth Modifier: 100%
>.... [11:44:27 INFO]: Sapling Growth Modifier: 100%
>.... [11:44:27 INFO]: Beetroot Growth Modifier: 100%
>.... [11:44:27 INFO]: Carrot Growth Modifier: 100%
>.... [11:44:27 INFO]: Potato Growth Modifier: 100%
>.... [11:44:27 INFO]: Wheat Growth Modifier: 100%
>.... [11:44:27 INFO]: NetherWart Growth Modifier: 100%
>.... [11:44:27 INFO]: Vine Growth Modifier: 100%
>.... [11:44:27 INFO]: Cocoa Growth Modifier: 100%
>.... [11:44:27 INFO]: Bamboo Growth Modifier: 100%
>.... [11:44:27 INFO]: SweetBerry Growth Modifier: 100%
>.... [11:44:27 INFO]: Kelp Growth Modifier: 100%
>.... [11:44:27 INFO]: Entity Activation Range: An 16 / Mo 24 / Ra 48 / Mi 8 / Tiv true
>.... [11:44:27 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
>.... [11:44:27 INFO]: Custom Map Seeds: Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
>.... [11:44:27 INFO]: Max TNT Explosions: 100
>.... [11:44:27 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
>.... [11:44:27 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
>.... [11:44:27 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
>.... [11:44:27 INFO]: Item Merge Radius: 2.5
>.... [11:44:27 INFO]: Item Despawn Rate: 6000
>.... [11:44:27 INFO]: View Distance: 6
>.... [11:44:27 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
>.... [11:44:27 INFO]: Zombie Aggressive Towards Villager: true
>.... [11:44:27 INFO]: Nerfing mobs spawned from spawners: false
>.... [11:44:27 INFO]: Mob Spawn Range: 5
>.... [11:44:27 INFO]: Preparing start region for dimension minecraft:crea
>.... [11:44:31 INFO]: Preparing spawn area: 0%
>.... [11:44:31 INFO]: Preparing spawn area: 0%
>.... [11:44:31 INFO]: Preparing spawn area: 0%
>.... [11:44:31 INFO]: Preparing spawn area: 0%
>.... [11:44:31 INFO]: Preparing spawn area: 0%
>.... [11:44:31 INFO]: Preparing spawn area: 0%
>.... [11:44:31 INFO]: Preparing spawn area: 0%
>.... [11:44:31 INFO]: Preparing spawn area: 0%
>.... [11:44:31 INFO]: Preparing spawn area: 0%
>.... [11:44:31 INFO]: Time elapsed: 4082 ms
>.... [11:44:31 INFO]: -------- World Settings For [minage] --------
>.... [11:44:31 INFO]: Experience Merge Radius: 3.0
>.... [11:44:31 INFO]: Cactus Growth Modifier: 100%
>.... [11:44:31 INFO]: Cane Growth Modifier: 100%
>.... [11:44:31 INFO]: Melon Growth Modifier: 100%
>.... [11:44:31 INFO]: Mushroom Growth Modifier: 100%
>.... [11:44:31 INFO]: Pumpkin Growth Modifier: 100%
>.... [11:44:31 INFO]: Sapling Growth Modifier: 100%
>.... [11:44:31 INFO]: Beetroot Growth Modifier: 100%
>.... [11:44:31 INFO]: Carrot Growth Modifier: 100%
>.... [11:44:31 INFO]: Potato Growth Modifier: 100%
>.... [11:44:31 INFO]: Wheat Growth Modifier: 100%
>.... [11:44:31 INFO]: NetherWart Growth Modifier: 100%
>.... [11:44:31 INFO]: Vine Growth Modifier: 100%
>.... [11:44:31 INFO]: Cocoa Growth Modifier: 100%
>.... [11:44:31 INFO]: Bamboo Growth Modifier: 100%
>.... [11:44:31 INFO]: SweetBerry Growth Modifier: 100%
>.... [11:44:31 INFO]: Kelp Growth Modifier: 100%
>.... [11:44:31 INFO]: Entity Activation Range: An 16 / Mo 24 / Ra 48 / Mi 8 / Tiv true
>.... [11:44:31 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
>.... [11:44:31 INFO]: Custom Map Seeds: Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
>.... [11:44:31 INFO]: Max TNT Explosions: 100
>.... [11:44:31 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
>.... [11:44:31 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
>.... [11:44:31 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
>.... [11:44:31 INFO]: Item Merge Radius: 2.5
>.... [11:44:31 INFO]: Item Despawn Rate: 6000
>.... [11:44:31 INFO]: View Distance: 6
>.... [11:44:31 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
>.... [11:44:31 INFO]: Zombie Aggressive Towards Villager: true
>.... [11:44:31 INFO]: Nerfing mobs spawned from spawners: false
>.... [11:44:31 INFO]: Mob Spawn Range: 5
>.... [11:44:31 INFO]: Preparing start region for dimension minecraft:minage
>.... [11:44:34 INFO]: Preparing spawn area: 0%
>.... [11:44:34 INFO]: Preparing spawn area: 0%
>.... [11:44:34 INFO]: Preparing spawn area: 0%
>.... [11:44:34 INFO]: Preparing spawn area: 0%
>.... [11:44:34 INFO]: Preparing spawn area: 0%
>.... [11:44:34 INFO]: Preparing spawn area: 0%
>.... [11:44:34 INFO]: Time elapsed: 2985 ms
>.... [11:44:34 INFO]: -------- World Settings For [nethernew] --------
>.... [11:44:34 INFO]: Experience Merge Radius: 3.0
>.... [11:44:34 INFO]: Cactus Growth Modifier: 100%
>.... [11:44:34 INFO]: Cane Growth Modifier: 100%
>.... [11:44:34 INFO]: Melon Growth Modifier: 100%
>.... [11:44:34 INFO]: Mushroom Growth Modifier: 100%
>.... [11:44:34 INFO]: Pumpkin Growth Modifier: 100%
>.... [11:44:34 INFO]: Sapling Growth Modifier: 100%
>.... [11:44:34 INFO]: Beetroot Growth Modifier: 100%
>.... [11:44:34 INFO]: Carrot Growth Modifier: 100%
>.... [11:44:34 INFO]: Potato Growth Modifier: 100%
>.... [11:44:34 INFO]: Wheat Growth Modifier: 100%
>.... [11:44:34 INFO]: NetherWart Growth Modifier: 100%
>.... [11:44:34 INFO]: Vine Growth Modifier: 100%
>.... [11:44:34 INFO]: Cocoa Growth Modifier: 100%
>.... [11:44:34 INFO]: Bamboo Growth Modifier: 100%
>.... [11:44:34 INFO]: SweetBerry Growth Modifier: 100%
>.... [11:44:34 INFO]: Kelp Growth Modifier: 100%
>.... [11:44:34 INFO]: Entity Activation Range: An 16 / Mo 24 / Ra 48 / Mi 8 / Tiv true
>.... [11:44:34 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
>.... [11:44:34 INFO]: Custom Map Seeds: Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
>.... [11:44:34 INFO]: Max TNT Explosions: 100
>.... [11:44:34 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
>.... [11:44:34 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
>.... [11:44:34 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
>.... [11:44:34 INFO]: Item Merge Radius: 2.5
>.... [11:44:34 INFO]: Item Despawn Rate: 6000
>.... [11:44:34 INFO]: View Distance: 6
>.... [11:44:34 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
>.... [11:44:34 INFO]: Zombie Aggressive Towards Villager: true
>.... [11:44:34 INFO]: Nerfing mobs spawned from spawners: false
>.... [11:44:34 INFO]: Mob Spawn Range: 5
>.... [11:44:34 INFO]: Preparing start region for dimension minecraft:nethernew
>.... [11:44:36 INFO]: Preparing spawn area: 0%
>.... [11:44:36 INFO]: Preparing spawn area: 0%
>.... [11:44:36 INFO]: Preparing spawn area: 0%
>.... [11:44:36 INFO]: Preparing spawn area: 0%
>.... [11:44:36 INFO]: Time elapsed: 1743 ms
>.... [11:44:36 INFO]: -------- World Settings For [nouveau] --------
>.... [11:44:36 INFO]: Experience Merge Radius: 3.0
>.... [11:44:36 INFO]: Cactus Growth Modifier: 100%
>.... [11:44:36 INFO]: Cane Growth Modifier: 100%
>.... [11:44:36 INFO]: Melon Growth Modifier: 100%
>.... [11:44:36 INFO]: Mushroom Growth Modifier: 100%
>.... [11:44:36 INFO]: Pumpkin Growth Modifier: 100%
>.... [11:44:36 INFO]: Sapling Growth Modifier: 100%
>.... [11:44:36 INFO]: Beetroot Growth Modifier: 100%
>.... [11:44:36 INFO]: Carrot Growth Modifier: 100%
>.... [11:44:36 INFO]: Potato Growth Modifier: 100%
>.... [11:44:36 INFO]: Wheat Growth Modifier: 100%
>.... [11:44:36 INFO]: NetherWart Growth Modifier: 100%
>.... [11:44:36 INFO]: Vine Growth Modifier: 100%
>.... [11:44:36 INFO]: Cocoa Growth Modifier: 100%
>.... [11:44:36 INFO]: Bamboo Growth Modifier: 100%
>.... [11:44:36 INFO]: SweetBerry Growth Modifier: 100%
>.... [11:44:36 INFO]: Kelp Growth Modifier: 100%
>.... [11:44:36 INFO]: Entity Activation Range: An 16 / Mo 24 / Ra 48 / Mi 8 / Tiv true
>.... [11:44:36 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
>.... [11:44:36 INFO]: Custom Map Seeds: Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
>.... [11:44:36 INFO]: Max TNT Explosions: 100
>.... [11:44:36 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
>.... [11:44:36 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
>.... [11:44:36 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
>.... [11:44:36 INFO]: Item Merge Radius: 2.5
>.... [11:44:36 INFO]: Item Despawn Rate: 6000
>.... [11:44:36 INFO]: View Distance: 6
>.... [11:44:36 INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
>.... [11:44:36 INFO]: Zombie Aggressive Towards Villager: true
>.... [11:44:36 INFO]: Nerfing mobs spawned from spawners: false
>.... [11:44:36 INFO]: Mob Spawn Range: 5

**Comment by benwoo1110** [comment]
Similar to #2670, report it to the server software you use.

**Comment by vdl19** [comment]
Hello, Minecraft 1.17.1 PAPER #109 :
paper-1.17.1-119.jar

**Comment by nicegamer7** [comment]
Yes, so report the issue to Paper.
