### ISSUE TITLE
Bugs with portals of worlds

### ISSUE THREAD

**Issue by Snele** [Multiverse/Multiverse-Core#2680]
(My English is bad. Sorry if I explained it very confusing)

I have a problem with portals and I don't think it's related to the Multiverse-Portals module.
Server. properties level-name=spawn (where the players initially appear). The game world is "world"

For example, I want to go to the nether portal in the world "world" I appear in "world_nether", but when I want to exit from there I appear already in "spawn_nether" and if I exit from there, I will appear already in the world "spawn"

I want the player from " world_nether" to go back to "world " or not to interact with the world "world_nether" at all, but to go to "spawn_nether" came out in "world".

I understand that can do level-name=world and then such a problem will disappear, but when the player first enters the server, he is teleported from the game world to spawn (the player sees it) and it is terrible

**Comment by benwoo1110** [comment]
Install mv-netherportals and see https://github.com/Multiverse/Multiverse-Core/wiki/Basics-(NetherPortals)
