### ISSUE TITLE
World is not doing anything-dont seem to have permission (i am server master)

### ISSUE THREAD

**Issue by Zrules987** [Multiverse/Multiverse-Core#2681]
### Information

* **Server version:** 

* **Full output of `/mv version -p`:** 

* **Server log:** 

### Details
I was **`<able / not able>`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  

**Steps to reproduce**  

**Expected behavior**  

**Screenshots**  

![Screenshot (179)](https://user-images.githubusercontent.com/88238004/127740606-0c1d39df-ddab-450e-b0d4-c17fc95df3d3.png)

**Comment by benwoo1110** [comment]
Follow the issue template if you wish to get help.
