### ISSUE TITLE
Maps not leading to correct locations!

### ISSUE THREAD

**Issue by monkeyno0dle** [Multiverse/Multiverse-Core#2682]
### Information

* **Server version:**  31.07 18:59:38 [Server] INFO This server is running Paper version git-Paper-136 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 7480b94)
31.07 18:59:38 [Server] INFO You are 4 version(s) behind
31.07 18:59:38 [Server] INFO Previous version: git-Tuinity-17 (MC: 1.17.1) 

* **Full output of `/mv version -p`:**  https://paste.gg/p/anonymous/d88a74034f414194aaab351fcbe7958e 

* **Server log:** https://gist.github.com/

### Details
I was **`<unable>`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
The bug occurs with server generated maps such as those used to find buried treasure, mansions, and sea temples. The maps appear correct but when you follow them to the location displayed there is nothing there. However, the maps work fine once the chunks are loaded in, so if you go to the temple then do the process detailed below it works. I was unable to recreate it on a separate server with just multiverse and paper, but when I did it on the original server with every plugin but multiverse disabled it was still happening, and then it worked once multiverse was disabled, so I'm not sure what could be causing that.

**Steps to reproduce**  
Create a new world using the /mv create command, spawn a villager with cartography table, trade up to an ocean monument map, follow it and find nothing there. 

**Expected behavior**  
 I expected to find an ocean monument where the map was telling me there was one.

**Comment by PapiCapi** [comment]
I had the same issue. Actually, it is coming from paper and you can "fix" it by enabling in paper.yml "seed-based-feature-search"
