### ISSUE TITLE
The problem with the end portal

### ISSUE THREAD

**Issue by Snele** [Multiverse/Multiverse-Core#2687]
I linked the worlds "world" with "spawn_nether" and world with "spawn_the_end" and vice versa. The nether portal works both ways, but everything is bad with the end world. Before restarting the server, it works both ways, but when the reboot was, it writes that it can't find world_the_end (although I don't have it).
What should I do?
https://imgur.com/8Aea4WI

**Comment by Plut090** [comment]
dunno

**Comment by benwoo1110** [comment]
Please follow the issue template. Send you logs and output of /mv version -p

**Comment by Snele** [comment]
https://paste.gg/p/anonymous/b1b583ad8d424f54bcf24adaf416d45c

**Comment by benwoo1110** [comment]
Update to latest dev builds, it is already fixed. http://ci.onarandombox.com/view/Multiverse/
