### ISSUE TITLE
/mv import fails at all times

### ISSUE THREAD

**Issue by Plut090** [Multiverse/Multiverse-Core#2688]
ok so i want to import a world from my other server. im using minehut and i cant use /ul or /dl cause for some reason minehut fricking hates me and disabled those commands. so im using this plugin. i rename my world so it doesnt get an error, and it STILL says: FAILED. That folder does not exist. i hate life. my folder for the world is named smp and idk what to do pls help

**Comment by benwoo1110** [comment]
I don’t know what is /ul or /dl. But please follow the issue template and send your logs Also, is the world you trying to import generated on the same mc version as your server?

**Comment by Plut090** [comment]
yes. its same version. this is minehut and it doesnt have logs that you can check. so ye

**Comment by benwoo1110** [comment]
Without logs, it will be near impossible to debug.

**Comment by DarinDev1000** [comment]
I ha issues on minehut.
It appears to work fine not on minehut

**Comment by benwoo1110** [comment]
Likely minehut issue then
