### ISSUE TITLE
Multiverse Custom Dimension Spawn Chunk Error

### ISSUE THREAD

**Issue by BabyGhast** [Multiverse/Multiverse-Core#2689]
### Information

* **Server version:** This server is running Paper version git-Paper-172 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: fdef125)
You are running the latest version

* **Full output of `/mv version -p`:** https://paste.gg/p/anonymous/e9da1f678e2a40bfaa720545ca878037

* **Server log:** https://gist.github.com/BabyGhast/9d94b8c9abd1a1a79cddb0559c7e8a64

### Details
I was **`able`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
Using custom dimension from a Minecraft datapack, custom biomes (not regular minecraft biomes) inside the spawn chunks are reverted to "minecraft:ocean" but still generate the biome chunks when using multiverse-core. This issue doesn't exist in vanilla. When moving the world spawn and deleting the region data, the error follows the new location of the world spawn. 

**Steps to reproduce**  
Create a papermc server and install the multiverse-core plugin.
Add a datapack that includes a dimension with custom biomes.
Start the server and execute "/mvtp (world-name)(underscore)(dimension-name-space)(underscore)(dimension-name)"
For example: My main world was "world" my namespace was "goa" and the name was "titan" so I would execute "/mvtp world(underscore)goa(underscore)titan"
(You may need to restart the server if the datapack doesn't load upon the first initialization.)

If the dimension has a custom sky or particles, you will not see them in the spawn chunks. Pressing f3 and checking the biome will show "minecraft:ocean". This issue should only work for custom biomes and not regular minecraft biomes. If you fly away from the spawn chunks, the biome is created as it's supposed to.
For more clarification, the biome inside the spawn chunks will be "minecraft:ocean" regardless if water is generated or not. I have a dimension with no water at all and it still says its an ocean biome.

**Expected behavior**  
We expect the spawn chunks to reproduce the biome correctly just like the rest of the regular chunks.
[example.zip](https://github.com/Multiverse/Multiverse-Core/files/6972424/example.zip)
Above is a pack I made just in case you cannot find a custom dimension with custom biomes.

**Screenshots**  
![2021-08-11_17 05 44](https://user-images.githubusercontent.com/85755412/129127930-54699458-ce9c-42fa-be03-077dc7f3ffc0.png)
![2021-08-11_17 05 47](https://user-images.githubusercontent.com/85755412/129127931-81f71f0f-81e1-4ba2-a8cb-0eb30b600531.png)
![2021-08-11_17 05 52](https://user-images.githubusercontent.com/85755412/129127934-727aaf89-bb91-43fe-b6d0-948b96a9b797.png)
![2021-08-11_17 17 42](https://user-images.githubusercontent.com/85755412/129127937-77798b9f-f5c5-4986-883d-a4ee88e4596c.png)
![2021-08-11_17 17 53](https://user-images.githubusercontent.com/85755412/129127938-ac47c207-280c-437d-94ac-01958dbbf695.png)

**Comment by benwoo1110** [comment]
MV does not touch datapacks at all.
