### ISSUE TITLE
In the config of multiverse I put enforced access off but still requires access

### ISSUE THREAD

**Issue by whatsupyo99** [Multiverse/Multiverse-Core#2691]
**Problem**

I encountered in the config file when i change enforced access to false you still need access. Only OP can use those commands
**What I have tried**

I have tried giving permissions from luck perms and try reloading the config file.
![sdsada](https://user-images.githubusercontent.com/87584728/129461621-e1ffb36c-c6ef-45b0-9c34-c705b5c1236b.png)

**Comment by benwoo1110** [comment]
That has nothing to do with enforce access. You need permissions to do mvtp command. The permissions needed are already shown in the screenshots your send.
