### ISSUE TITLE
world_the_nether not showing on files and also I cant return to overworld when going through nether portal

### ISSUE THREAD

**Issue by InfiniteXgg** [Multiverse/Multiverse-Core#2694]
Pls help! I just had an issue while having my main world(survival) and the lobby world, a player entered on a nether portal while in the survival world and it transported him into the lobby world, then I was never able to enter overworld again, all nether world files were deleted, I need the default sheet for worlds.yml

**Comment by benwoo1110** [comment]
Please follow the issue template.
