### ISSUE TITLE
Nether portals cloning when entering and exiting them

### ISSUE THREAD

**Issue by InfiniteXgg** [Multiverse/Multiverse-Core#2695]
<!-- Multiverse-Core bug reporting guide

Don't put anything inside this block, as it won't be included in the issue.

Get latest build from: http://ci.onarandombox.com/view/Multiverse/

If you are having issues with other submodules of Multiverse, go to their respective git repo:
    Multiverse-Portals: https://github.com/Multiverse/Multiverse-Portals/issues
    Multiverse-NetherPortals: https://github.com/Multiverse/Multiverse-NetherPortals/issues
    Multiverse-Inventories: https://github.com/Multiverse/Multiverse-Inventories/issues
    Multiverse-SignPortals: https://github.com/Multiverse/Multiverse-SignPortals/issues

If you are reporting a bug, please follow the following steps:

1.  Fill out the template in full.
      Run the commands in the console. Don't just put "latest" as a version,
      or we will ignore it.

2.  When linking files, do not attach them to the post!
      Copy and paste any logs into https://gist.github.com/, then paste a
      link to them in the relevant parts of the template.
      **DO NOT drag files into this box!**

3.  Make sure not to write between the arrows, as anything there will be
    hidden.

### Information

* **Server version:1.17.1** 

* **Full output of `/mv version -p`: https://paste.gg/p/anonymous/07ef0c5f3c7d4314b7ff7593e4249a12**

* **Server log: https://gist.github.com/InfiniteXgg/821c99a1ba15306bcaf65b714b193215** 

### Details
I was **not able`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
When I enter a nether portal on the world "sandbox" it naturally teleports me to "sandbox_nether" but then when I go back to the same overworld ("sandbox") the game just generates another portal near to the first one I used to go to the nether

**Steps to reproduce**  
1.- Enter a nether portal on a world having two or more worlds created on the server (the world you´re in doesnt have to be the main spawning world)

2.- When in the nether, enter the same portal you came

3.- See how there's a cloned portal right near to the first one you entered 

**Expected behavior**  
I expected to come back to the overworld in the same portal I entered the nether and viceversa

**Screenshots**  
https://imgur.com/a/wyJzAwK

**Comment by benwoo1110** [comment]
Please follow the issue template.
