### ISSUE TITLE
Wrong Nether terrain generation with "mv create" and provided seed

### ISSUE THREAD

**Issue by hohoaisan** [Multiverse/Multiverse-Core#2697]
### Information

* **Server version:** Paper version git-Paper-188 (MC: 1.17.1) (Reproduced on Spigot as well)

* **Full output of `/mv version -p`:** https://pastebin.com/Gp3fLmYV

* **Server log:** https://pastebin.com/J0ggBWYA

### Details
I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
My server faced an issue that the default nether (world_nether) have a massive number of chunks had been cut off. It once recreated using Multiverse Core's "mv create world_nether nether", and after several time server restarts, every "new" chunks in nether were generated differently and don't match with old ones.
However, I discovered that if I use mv create with the same seed with current (fresh, new) nether, both worlds were generated very different.
**Steps to reproduce**  
1. With a fresh server that only has Multiverse Core plugin, start it
2. Go to nether, type "/seed" to get its seed
3. Use "mv create testnether nether -s <seed>"
4. Teleport to testnether and compare the terrain of both worlds
5. The terrain is different, how ever, the structures location is the same

**Expected behavior**  
The terrain must be the same

**Screenshots**  
![world_nether](https://user-images.githubusercontent.com/26185060/130186570-931a6737-89b0-438f-ba14-ef5740c2f4d0.png)

![new nether with the same seed](https://user-images.githubusercontent.com/26185060/130186858-99b67714-e25c-49b3-acda-02bb3b9a2fdb.png)

**Comment by benwoo1110** [comment]
MV doesnt dictate the actual chunk loading, so I don't see how mv will cause this. If the seed you specific in mvcreate command is correctly reflected, then nothing wrong with mv.
