### ISSUE TITLE
automatic portal creation - wiki has an empty section

### ISSUE THREAD

**Issue by oltdaniel** [Multiverse/Multiverse-Core#2699]
### Information

* **Server version:** This server is running Paper version git-Paper-214 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 789bc79)

* **Full output of `/mv version -p`:** https://j.mp/3ylqzE4

* **Server log:** no errors happend. log not needed.

### Help request

**Problem**
Creating  a new Nether Portal in Survival will link it automatically to the first one very created. I would like to have the vanilla behavior here. 

**What I have tried**
I looked into the wiki, and the section I need here to solve is empty..... https://github.com/Multiverse/Multiverse-Core/wiki/FAQ-(NetherPortals)#2-how-to-activate-nether-portal-auto-creation

**Screenshots**
not relevant.

**Comment by benwoo1110** [comment]
yea wiki is a pain, its all covered here anyways https://github.com/Multiverse/Multiverse-Core/wiki/Basics-(NetherPortals)#standard

**Comment by oltdaniel** [comment]
@benwoo1110 That documentation is better. Turns out, it has something to do with the search and create radius. The issue now is, that I can create endless nether portals, by going through a new one, which creates a new one, repeat.

Which means now, it is impossible to have two portals automatically linked in normal survival.
