### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Spelicious** [Multiverse/Multiverse-Core#2705]
There is a bad command for multiverse that ruins the server.
There has been a person throwing
`/mv ^(.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.++)$^`
and server instantly crashes after that.

**Comment by MrPranklez** [comment]
Join the discord or download the latest version from spigot. The issue should be resolved with those builds

**Comment by nicegamer7** [comment]
Duplicate of #2703.

**Comment by benwoo1110** [comment]
For those using older multiverse builds and can't update for whatever reason: https://www.spigotmc.org/resources/multiverse-patches.96390/
