### ISSUE TITLE
Newcomers fall into void in MV world when unsuccessfully registered

### ISSUE THREAD

**Issue by xR4Z3R** [Multiverse/Multiverse-Core#2710]
### Information

* **Server version:** This server is running Tuinity version git-Tuinity-"935b901" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

* **Full output of `/mv version -p`:** https://paste.gg/p/anonymous/602fbb38035a43e98ce3c16b39cf6fb1
* **Server log:** no need, no errors or anything pointing to this 

### Help request

**Problem**
I don't know if this is mv problem, essentialsxspawn or authme so I will submit this problem in all of those githubs. But to the point: I have create new void world and created small room that will only available as spawnpoint for newcomers. There are rules etc. But when somebody joins the server, then leaves(without registering or anything) and then joins again they spawn at the same X and Z coordinates as they should but they are falling into the void

**What I have tried**
I have tried to set spawn coordinates in MV worlds.yml, authme spawn and essentialsx spawn but with one block higher than actual floor. Yay! Didnt work xd

**Screenshots**
none

**Comment by benwoo1110** [comment]
Test with only mv installed first then. I doubt is mv since mv does not touch your location upon joining the server. You will always join at where you left the server.

**Comment by xR4Z3R** [comment]
Okay, wrong plugin. It is AuthMe issue :P
