### ISSUE TITLE
Weird symbols on the client side

### ISSUE THREAD

**Issue by RealHenning** [Multiverse/Multiverse-Core#2713]
### Information

* **Server version:** 
3242-Spigot-6c1c1b2-d3cc412 (MC: 1.17.1)
* **Full output of `/mv version -p`:** 
https://j.mp/3kEcbTy
* **Server log:** 
https://gist.github.com/RealHenning/72479a11ba9e319d15334f0d6f69473a
### Help request

**Problem**

When I join my newly setup server I see som weird symbols and letters in the lower right corner of the screen. The letters are upside down and I believe that there's a hex digit among them.
**What I have tried**

I tried removing plugins from my server one by one. When I reached Multiverse-Core the symbols disappeared.
**Screenshots**

![Message](https://user-images.githubusercontent.com/25371643/134641010-63502b6a-6690-4874-9424-e17565ad7692.png)

**Comment by benwoo1110** [comment]
Test with only mv installed, and ensure you are not using a modded client.

**Comment by RealHenning** [comment]
Thanks for the tip. I thought I had tried every possible constelation, but I just retried and figured out that the problem is somehow related to InTheWilds special resource pack combined with changing worlds with MV.
