### ISSUE TITLE
Blocking "multiverse.help" DOES NOT prevent people from crashing your server.

### ISSUE THREAD

**Issue by TomLewis** [Multiverse/Multiverse-Core#2715]
I cant even reply to my ticket as you blocked replys.
https://github.com/Multiverse/Multiverse-Core/issues/2706

Your advice to block `multiverse.help` to prevent the hack to crash the server does not work, last night when I was sleeping I had a host of people from a youtube channel come and crash my server over and over and over, after you recommended denying the permission `multiverse.help` This did NOT work and caused absolute chaos.

**Comment by benwoo1110** [comment]
https://www.spigotmc.org/resources/multiverse-patches.96390/

**Comment by benwoo1110** [comment]
Please read my replies, I dont need to keep repeating myself.
