### ISSUE TITLE
mv create bug

### ISSUE THREAD

**Issue by joandotcodina** [Multiverse/Multiverse-Core#2716]
### Information

* **Server version:** 
This server is running CraftBukkit version 3242-Spigot-6c1c1b2-d3cc412 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

* **Full output of `/mv version -p`:** [link version](https://pastebin.com/CTj5fuPG)

* **Server log:** There was nothing, just an error

**Description**  
[Link to wiki](https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#create-command)
Using the command reference of multiverse, the example that its show, doesn't work.

Because i was trying to make a world of only water and.....

**Expected behavior**  
Create a world without error.
In console doesn't appear nothing in 1.17 (lastest version)

**Screenshots**  
[Screenshot](https://i.imgur.com/Gcqe8lB.png)

**Comment by benwoo1110** [comment]
Do include your server log.

**Comment by joandotcodina** [comment]
[link](https://i.imgur.com/prFyq5C.png )

There is nothing strange

**Comment by benwoo1110** [comment]
Yea, I cant tell as well if you just screenshot 5 lines of logs.

**Comment by joandotcodina** [comment]
[here u have](https://pastebin.com/6rscbsUA)

**Comment by benwoo1110** [comment]
Do you even have a plugin named `WaterWorlds` installed? Your logs don't contain the startup so cant tell. If so, will be good you link me to that custom generator plugin as well.
