### ISSUE TITLE
Empty World

### ISSUE THREAD

**Issue by iJory** [Multiverse/Multiverse-Core#2718]
Hi, I think I have an issue with mv core. 
The problem is the next: when i log in and I´m in a different world of the spawn world I see the world empty and I have to go to the spawn world and after go to the world that I want to see the world loaded. I don´t know if it´s an issue or a bug. 
Thanks!
![2021-10-01_14 28 19](https://user-images.githubusercontent.com/91736484/135619770-4a942c69-edc0-450b-bbec-7a696d7a4782.png)

**Comment by zax71** [comment]
Hello! This would be better handled on the Multiverse discord but if you wish to continue here can I get the full logs

**Comment by joaninitv** [comment]
I have the same Issue. I need hel too. I f you can help me please. I don't know how to send you my logs.  
And How does the discord work? Do you know the link?

**Comment by iJory** [comment]
[2021-10-01-9.log.zip](https://github.com/Multiverse/Multiverse-Core/files/7271589/2021-10-01-9.log.zip)

**Comment by joaninitv** [comment]
[2021-10-01-1.log.zip](https://github.com/Multiverse/Multiverse-Core/files/7271676/2021-10-01-1.log.zip)

**Comment by zax71** [comment]
This would be better continued on discord ([https://discord.gg/KWnjq7CreC](https://discord.gg/KWnjq7CreC) )
