### ISSUE TITLE
How do I set a gamerule for new worlds in Multiverse-Core?

### ISSUE THREAD

**Issue by WolfyRed** [Multiverse/Multiverse-Core#2722]
### Information

* **Server version:**  git-Paper-655 `1.13.2-R0.1-SNAPSHOT` (Paper 1.13.2)

* **Full output of `/mv version -p`:** https://paste.gg/p/anonymous/59f1d48ae76f4355943c9d2da4428861

* **Server log:** https://gist.github.com/WolfyRed/5454572c29adc4b8a1bebd4585b6a76d

### Help request

**Problem**
I cannot seem to auto-set gamerules for worlds in the process of being created in Multiverse-Core, is there a way to do so? Like, for every world created in the future?

**What I have tried**
Manually setting the gamerule every time. Tiring.

**Comment by benwoo1110** [comment]
Please don't open the same exact issue twice.

**Comment by WolfyRed** [comment]
THIS IS NOT A DUPLICATE ISSUE.

**Comment by benwoo1110** [comment]
Tell me how is this different form #2721

**Comment by benwoo1110** [comment]
Ah game rules, I will put it under the same issue.
