### ISSUE TITLE
bug on a map or a schematic

### ISSUE THREAD

**Issue by ewenadou** [Multiverse/Multiverse-Core#2724]
### Information

* **Server version: Airplane version git-Airplane-"36c9bc8" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 36c9bc8 on HEAD)
Unknown version** 

* **Full output of `/mv version -p`: https://j.mp/2YbHYDj** 

### Help request

**Problem : I try to import a map or a schematic, it imports well and we can go on it as if nothing had happened. This is a map from 1.12.1 but it works very well in appearance.
The problem is that Multiverse doesn't like it and gives looping errors in the console

[16:43:32 WARN]: [Multiverse-Core] An error occurred while parsing selector '@p[r=2]' for @. Is it is the correct format?
>.... [16:43:32 WARN]: java.lang.IllegalArgumentException: Could not parse selector: @p[r=2]
>.... [16:43:32 WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.selectEntities(CraftServer.java:2399)
>.... [16:43:32 WARN]: at org.bukkit.Bukkit.selectEntities(Bukkit.java:1934)
>.... [16:43:32 WARN]: at com.onarandombox.MultiverseCore.utils.PlayerFinder.getMultiBySelector(PlayerFinder.java:165)
>.... [16:43:32 WARN]: at com.onarandombox.MultiverseCore.utils.PlayerFinder.getBySelector(PlayerFinder.java:136)
>.... [16:43:32 WARN]: at com.onarandombox.MultiverseCore.utils.PlayerFinder.get(PlayerFinder.java:43)
>.... [16:43:32 WARN]: at com.onarandombox.MultiverseCore.commands.TeleportCommand.runCommand(TeleportCommand.java:63)
>.... [16:43:32 WARN]: at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:296)
>.... [16:43:32 WARN]: at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143)
>.... [16:43:32 WARN]: at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
>.... [16:43:32 WARN]: at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:839)
>.... [16:43:32 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [16:43:32 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [16:43:32 WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:830)
>.... [16:43:32 WARN]: at org.bukkit.craftbukkit.v1_17_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:53)
>.... [16:43:32 WARN]: at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
>.... [16:43:32 WARN]: at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177)
>.... [16:43:32 WARN]: at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:275)
>.... [16:43:32 WARN]: at net.minecraft.commands.CommandDispatcher.dispatchServerCommand(CommandDispatcher.java:252)
>.... [16:43:32 WARN]: at net.minecraft.world.level.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:135)
>.... [16:43:32 WARN]: at net.minecraft.world.level.block.BlockCommand.a(BlockCommand.java:120)
>.... [16:43:32 WARN]: at net.minecraft.world.level.block.BlockCommand.tickAlways(BlockCommand.java:97)
>.... [16:43:32 WARN]: at net.minecraft.world.level.block.state.BlockBase$BlockData.a(BlockBase.java:918)
>.... [16:43:32 WARN]: at net.minecraft.server.level.WorldServer.b(WorldServer.java:1082)
>.... [16:43:32 WARN]: at com.destroystokyo.paper.server.ticklist.PaperTickList.b(PaperTickList.java:306)
>.... [16:43:32 WARN]: at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:721)
>.... [16:43:32 WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1613)
>.... [16:43:32 WARN]: at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:482)
>.... [16:43:32 WARN]: at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1465)
>.... [16:43:32 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1261)
>.... [16:43:32 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
>.... [16:43:32 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
>.... [16:43:32 WARN]: Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown option 'r' at position 3: @p[<--[HERE]
>.... [16:43:32 WARN]: [Multiverse-Core] An error occurred while parsing selector '@p[r=2]' for @. Is it is the correct format?
>.... [16:43:32 WARN]: java.lang.IllegalArgumentException: Could not parse selector: @p[r=2]
>.... [16:43:32 WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.selectEntities(CraftServer.java:2399)
>.... [16:43:32 WARN]: at org.bukkit.Bukkit.selectEntities(Bukkit.java:1934)
>.... [16:43:32 WARN]: at com.onarandombox.MultiverseCore.utils.PlayerFinder.getMultiBySelector(PlayerFinder.java:165)
>.... [16:43:32 WARN]: at com.onarandombox.MultiverseCore.utils.PlayerFinder.getBySelector(PlayerFinder.java:136)
>.... [16:43:32 WARN]: at com.onarandombox.MultiverseCore.utils.PlayerFinder.get(PlayerFinder.java:43)
>.... [16:43:32 WARN]: at com.onarandombox.MultiverseCore.commands.TeleportCommand.runCommand(TeleportCommand.java:63)
>.... [16:43:32 WARN]: at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:296)
>.... [16:43:32 WARN]: at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143)
>.... [16:43:32 WARN]: at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
>.... [16:43:32 WARN]: at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:839)
>.... [16:43:32 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [16:43:32 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [16:43:32 WARN]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:830)
>.... [16:43:32 WARN]: at org.bukkit.craftbukkit.v1_17_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:53)
>.... [16:43:32 WARN]: at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
>.... [16:43:32 WARN]: at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177)
>.... [16:43:32 WARN]: at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:275)
>.... [16:43:32 WARN]: at net.minecraft.commands.CommandDispatcher.dispatchServerCommand(CommandDispatcher.java:252)
>.... [16:43:32 WARN]: at net.minecraft.world.level.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:135)
>.... [16:43:32 WARN]: at net.minecraft.world.level.block.BlockCommand.a(BlockCommand.java:120)
>.... [16:43:32 WARN]: at net.minecraft.world.level.block.BlockCommand.tickAlways(BlockCommand.java:97)
>.... [16:43:32 WARN]: at net.minecraft.world.level.block.state.BlockBase$BlockData.a(BlockBase.java:918)
>.... [16:43:32 WARN]: at net.minecraft.server.level.WorldServer.b(WorldServer.java:1082)
>.... [16:43:32 WARN]: at com.destroystokyo.paper.server.ticklist.PaperTickList.b(PaperTickList.java:306)
>.... [16:43:32 WARN]: at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:721)
>.... [16:43:32 WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1613)
>.... [16:43:32 WARN]: at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:482)
>.... [16:43:32 WARN]: at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1465)
>.... [16:43:32 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1261)
>.... [16:43:32 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
>.... [16:43:32 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
>.... [16:43:32 WARN]: Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown option 'r' at position 3: @p[<--[HERE]-->

**

**What I have tried : Edit the map with MC edit but it crashes, make in 1.12.1 the schematic and reimport in 1.17 
Disabling the command-blocks seems to return to normal, but I need them.
(I removed all command-blocks from the map with WorldEdit to be sure)**
<!--

**Comment by benwoo1110** [comment]
What exact command are you running?

**Comment by ewenadou** [comment]
I finally managed to solve the problem, it was some block commands that escaped the //replace command_block air 
Probably because of their type. As they are 1.12 commands Multiverse should not understand with the new commands. 
I spent hours trying to fix it, but it's ok !
Thanks anyway for your answer :)
