### ISSUE TITLE
When a user enter to the server is a Void World Multiverse Core

### ISSUE THREAD

**Issue by joaninitv** [Multiverse/Multiverse-Core#2725]
Hello, I have a Magma server of plugins and Mods with Friends and I have this problem with multiverse-core: When someone disconnects in a world other than the world (Main World) and later log in in the server, appears in the sky and cannot move or do anything. And for him to see everything again I have to make TP to the world and they see everything well. The truth is that it is quite uncomfortable, if someone can give me a solution. The version is 1.12.2 and my logs are these

[2021-10-01-1.log.zip](https://github.com/Multiverse/Multiverse-Core/files/7271870/2021-10-01-1.log.zip)
:

**Comment by zax71** [comment]
We don’t support magma. If the issue persists on a paper server I can continue

**Comment by LuisMi1245** [comment]
This problem also occurs on a mohist server. I have been looking for days for a way to solve the bug/conflict/problem.

**Comment by zax71** [comment]
Multiverse doesn’t support bukkit on forge mods (like magma)

**Comment by LuisMi1245** [comment]
However, Mohist or Magma support spigot or bukkit plugins. Do you know why Multiverse-Core is not compatible?

**Comment by zax71** [comment]
That is them saying that. Those are a compatibility layer that isn’t good enough yet for most Bukkit plugins to work
