### ISSUE TITLE
Why not use Pattern.quote(filter) in the "cleanFilter" method?

### ISSUE THREAD

**Issue by Qveshn** [Multiverse/Multiverse-Core#2726]
Please help me figure out the code.
I wonder why such a complex construct is used to escape characters instead of the simple action`Pattern.quote(filter)`?

https://github.com/Multiverse/Multiverse-Core/blob/71054197f2387b8c86a1e3c37670a38f6c1b0967/src/main/java/com/onarandombox/MultiverseCore/commands/PaginatedCommand.java#L58-L60

**Comment by benwoo1110** [comment]
Not sure what say. We just didn't think if that method of solving the issue when writing that part of the code, and I can tell you you probably going to find another 100 things that "why don't do another way" throughout the entire codebase. What we came up with achieve what it needs to do so nothing wrong there.

If you feel there is a reasonable improvement to codebase that you can make, feel free to PR.
