### ISSUE TITLE
[Idea]: Don't tab complete commands without permissions

### ISSUE THREAD

**Issue by Artuto** [Multiverse/Multiverse-Core#2729]
### `/mv version -p` output

https://paste.gg/p/anonymous/2e95a3cd2ec04d83b6d6d3af34f00458

### Server logs

Not needed

### Server Version

```shell
his server is running Prismarine version git-Prismarine-18 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 664f819 on HEAD)
```

### Server Version

Commands the user cannot use (because of lacking permissions) should not be displayed when tab completing.

This is usually fixed by properly declaring the commands and their permissions in the plugin.yml file or via the API.

### Steps to reproduce

1. Start the server
2. Make sure you are not OP
3. Join and type into the chat `/mv`
4. Look at all the Multiverse commands that are completed but cannot be used because of lacking permissions:

![image](https://user-images.githubusercontent.com/9273973/136496322-939140d3-cb27-40dd-b330-def6cd522319.png)

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment]
As long as they cannot actually run it, it's not a huge concern. While plugins.yml works for some simple commands, quite a few are dynamic so it won't work. There is a plan to use a better command handler, but mv just has too many commands to be viable in terms of dev time.

**Comment by zax71** [comment]
Added when switching to ACF in the [MV5](https://github.com/Multiverse/Multiverse-Core/tree/MV5) branch
