### ISSUE TITLE
[Bug]: Nether portals no longer connect as they do in vanilla

### ISSUE THREAD

**Issue by FleXCrash** [Multiverse/Multiverse-Core#2735]
### `/mv version -p` output

https://j.mp/3GMjUbm

### Server logs

https://pastebin.com/1LWqfrBk

### Server Version

```shell
[19:36:11 INFO]: This server is running Paper version git-Paper-359 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bc43f40)
You are running the latest version
```

### Bug Description

As of Multiverse Core version 4.3.0 nether portal linking is no longer working properly. We have some very closely build portals in our world, which has been working perfectly before, but as of 4.3.0 (and 4.3.1) the highest portal block is no longer properly connected. Our set up of nether portals works fine in vanilla. Upon downgrading to Multiverse Core 4.2.2 this issue is fixed.

### Steps to reproduce

I could explain all the coordinates of each portal block and how it should link up, but I figured a test world would work better.

https://drive.google.com/file/d/1lJQEM4GYrkKPhw6jt1CbiIhowR-nsdmh/view?usp=sharing (Git wasnt allowing the zip file)

The portals are located around -513 162 -181

The two gold portals should be linked to one another and the same goes for the diamond portals. Unfortunately this does not seem to work anymore with Multiverse 4.3.0+ installed. Upon removing the plugin or installing v4.2.2, the portals link as they should.

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment]
set `defaultportalsearch` to true in mv config.yml.
