### ISSUE TITLE
[Bug]: Teleporting to another world bugged this one !

### ISSUE THREAD

**Issue by TMCN010** [Multiverse/Multiverse-Core#2738]
### `/mv version -p` output

https://j.mp/3r67hCP

### Server logs

https://paste.gg/p/anonymous/f54c7e5b0d5142f09a11cb1b3ebdb981

### Server Version

```shell
[18.11 20:35:06] [Server] [INFO] This server is running Mohist version 1.16.5-818 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.8)
```

### Bug Description

When I teleport to a world on my list (no matter the type of world) I am tp in a parallel universe to the world I came from but bugged. For a flat world it is the same problem as before except that there is indeed a place which will be flat. Unfortunately this flat area is not accessible because I bug in the air.

### Steps to reproduce

1. Start a server with the same version as that of my server, all multiverse plugins (core, inventory and portal) and the worldedit plugin.
2. Create a world using the / mv create command (try all types of worlds as not all of them work)
3. Use the command / mv tp (the name of the created world)

If the bug doesn't appear it's either I'm cursed or the world wants me to end my life (even though I wouldn't kill myself)

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment]
Multiverse doesnt support any bukkit on forge mods, these include magma, mohist, etc...
