### ISSUE TITLE
[Idea]:  MV TP

### ISSUE THREAD

**Issue by RaviatOfficial** [Multiverse/Multiverse-Core#2739]
### Describe the feature

I dont know if this is there or not or it is possible or not.
Is there a way so that i can teleport my players from lobby to a specific location in my survival world.
Example : I have allowed my player to open shops anywhere. There are some shops that are necessary so i want that players can directly teleport from lobby too directly to the shop. 

### How is the feature useful to all Multiverse users?

It may help some server which allow players to open shop anywhere.
And for those who dont allow anywhere but allow in a specific  place this can help with some iconic public places.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by RaviatOfficial** [comment]
Please tell me if this is already there.
:D

**Comment by nicegamer7** [comment]
Yes, you can use an exact destination. See [here](https://github.com/Multiverse/Multiverse-Core/wiki/Destinations#exact-destinations).
