### ISSUE TITLE
[Problem]: None of the custom generator are working 1.12.2

### ISSUE THREAD

**Issue by Theangelito2704** [Multiverse/Multiverse-Core#2741]
### `/mv version -p` output

2.5.0

### Server logs

Don't

### Server Version

```shell
1.12.2
```

### Bug Description

I am testing a server in version 1.12.2 and using mv 2.5.0 does not recognize me any generator

It always says "No generators plugins found"

My server uses Magma software

### Steps to reproduce

1: Download mv plugin
2: download any custom generator
3: custom generator does not appear in mv list

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment]
We do not support magma server software.
