### ISSUE TITLE
[Bug]: gamemode changes to the default world gamemode when i move worlds instead of keeping the same gamemode

### ISSUE THREAD

**Issue by KryanThePacifist** [Multiverse/Multiverse-Core#2743]
### `/mv version -p` output

https://paste.gg/p/anonymous/e2cf7f4a2ecc4c32806e8292c8a9ff27

### Server logs

n/a

### Server Version

```shell
This server is running Paper version git-Paper-68 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 1c779c2)
You are running the latest version
Previous version: git-Paper-58 (MC: 1.18)
```

### Bug Description

Whenever i jump a nether or end portal, or swap between other worlds, my gamemode is changed to survival.
I would like as a server operator to bypass this function for my account, as when i'm in creative mode is usually when i'm tracking.
if it is something that i can change on my config, please let me know.
Thnaks a lot.

### Steps to reproduce

Enter any portal in a gamemode that is not the default gamemode for the world.

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by JamesRagnarok** [comment]
This is actually not a bug. You need to gain mv.bypass.gamemode.WORLDNAME permission node to bypass the default game mode setting while entering a world.

**Comment by soshimee** [comment]
Just add option to disable gamemode globally!
