### ISSUE TITLE
[Bug]: Listener für veraltetes Ereignis

### ISSUE THREAD

**Issue by saschacraftgamer** [Multiverse/Multiverse-Core#2744]
### `/mv version -p` output

https://paste.gg/p/anonymous/beec722faa2f46d6a5bb9ada0407c1ac

### Server logs

https://paste.gg/p/anonymous/bab2ee33c7ea4b229d0d3796aa39b14f

### Server Version

```shell
Konsolenausgabe: 
/version
[11:33:29] [Server thread/INFO]: This server is running CraftBukkit version 3284-Spigot-3892929-0ebef35 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
[11:33:29] [Server thread/INFO]: Checking version, please wait...
[11:33:29] [Thread-27/INFO]: You are 42 version(s) behind
```

### Bug Description

Folgender Fehler meldet mein Server: 

Multiverse-Core v4.3.1-b861" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].

### Steps to reproduce

1. Ich habe mein Server gestartet und während des Starts kam der oben beschriebene Fehler. 

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [x] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by ljacqu** [comment]
Duplicates #2000
