### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by bramdaniel** [Multiverse/Multiverse-Core#2749]
### `/mv version -p` output

https://paste.gg/p/anonymous/d616451008cf4ade9da769d6015e44b2

### Server logs

https://paste.gg/p/anonymous/bd01e4a4a9ad446f82c53160ccdd6907

### Server Version

```shell
[INFO] This server is running CraftBukkit version 3284a-Spigot-3892929-0ab8487 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
```

### Bug Description

Whenever a player does something in a world like opening a chest or killing a mob the console will start putting out these warnings and depending on the amount of players the console gets spammed a lot

### Steps to reproduce

Example:
Start the server after a reboot
Load into a world
open a chest
See warnings in console

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment]
I dont see anything wrong with multiverse, look into your Quests and Coreprotect plugins. Seems like those have some issues.

**Comment by bramdaniel** [comment]
Alright Thank you

> I dont see anything wrong with multiverse, look into your Quests and Coreprotect plugins. Seems like those have some issues.
