### ISSUE TITLE
[Idea]: Please add spawn to the aliases for mvs to the plugin.yml inside the jar. It takes seconds, but would solve the problem of players used to typing /spawn receiving a command not found error when they do. 

### ISSUE THREAD

**Issue by Dave-Redisfa** [Multiverse/Multiverse-Core#2750]
### Describe the feature

Make the following change to the plugin.yml file inside the .jar   Add spawn as an alias along with mvs.

 mvspawn:
    description: Teleport to the spawn area
    aliases: [mvs, **spawn**]    <<---------<<<<<
    usage: /<command> [player] -- Teleports you to the spawn area of your current world.

### How is the feature useful to all Multiverse users?

Players will be able to use the command they are most used to, without getting an error, and without having to be reminded to use /mvs.

This is not so much a feature as a convenience. It takes me about ten seconds to do this myself, and once done it is permanent. Just do it now for everyone and problem solved.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by ryantheleach** [comment]
Aliases can be configured.

https://www.spigotmc.org/wiki/command-alias/

```
aliases:
    spawn:
    - "mvspawn $1-"
```

Should do it.

**Comment by Dave-Redisfa** [comment]
Did you even read what I wrote? Do you really want to be responding to
people to tell them things they already know, when you can make a change
inside the jar that will be forever that you never have to think of again?

In other words, you could have done this in the time it took you to respond
to me. I already told you I was capable of making the change and had
already. Now it's your turn. If you so choose.

**Comment by ryantheleach** [comment]
You said you could do it yourself. You didn't provide enough context on how. For all I know you may have thought it was difficult.

Personally, I much rather MV stays in it's lane, so I don't need to prevent conflicts with other plugins that use /spawn.

**Comment by benwoo1110** [comment]
@Dave-Redisfa `Commands.yml` is not changing the mv's jar in any way. And I agree with @ryantheleach, mv does not want to override any vanilla commands.

**Comment by ryantheleach** [comment]
@Dave-Redisfa There's 2 Commands.yml if you wern't aware. One in each jar and one in the root directory of bukkit. I was talking about the one in the root directory of bukkit.
