### ISSUE TITLE
SOLVED

### ISSUE THREAD

**Issue by FrostBlade5** [Multiverse/Multiverse-Core#2755]
### `/mv version -p` output

4.3.1

### Server logs

Multiverse-Core

### Server Version

```shell
1.18.1
```

### Bug Description

I need help.
Running a MC Server on 1.18.1 with Multiverse-Core 4.3.1 and WarpPortals.
I know WarpPortals is outdated but still works.
However Netherportals are NOT working at all.
Now i installed Multiverse-Netherportals but it doesn't seem to help.

Is this ment to be like that? Netherportals by default are not supposed to work with just Multiverse-Core?
Or else how can i get them working? This is depressing...
Had this problem for months and dont know what to do, would be nice if someone here can help me out.

### Steps to reproduce

Nether portals are not working when using multiverse core 4.3.1
How to fix?

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment]
Please include your full logs. And for you issue, I would like to see you server.properties file as well. Thanks!

**Comment by FrostBlade5** [comment]
> Please include your full logs. And for you issue, I would like to see you server.properties file as well. Thanks!

Thanks for the reply, by logs you mean the server console where you could find possible errors/conflicts?
I stoped and restarted the server, now i copy pasted the whole log here: https://pastebin.com/VunYN86z

Back to topic, i can only say so much that since 1.16.5 aswell as 1.17 and now also 1.18.1 the nether portals never worked on my server when using multiverse core. Like i said i also use warp portals which is an outdated but still functional plugin. When i install multiverse netherportals and try to walk into a portal which was created by warpportals then multiverse netherportals shows an error in the chat saying the portal leads nowhere and has not been linked to a speicifc netherworld yet, however i dont even want those portals to be linked with any nether, they are for warpportals not for multiverse.

when i have the server running only with multiverse-core and warpportals i cannot use any nether portals, when i walk into one, nothing happens. do i have to edit the config or something? i have read that others have the same issue but the author said it was fixed in a previous release?

**Comment by FrostBlade5** [comment]
Update:

Sorry for opening an issue this was false alaram.
I tested again and it appear that the outdated plugin warp portals caused nether portals to lose functionallity.
Cannot blame multiverse for this!

**Comment by nicegamer7** [comment]
Glad to hear you figured it out.

**Comment by nopeless** [comment]
Sorry for necro

@FrostBlade5 please do not update titles when its solved. A better way is for maintainers to put an invalid tag
