### ISSUE TITLE
[Idea]: New Module: Multiverse-Commands

### ISSUE THREAD

**Issue by wizardsof-code** [Multiverse/Multiverse-Core#2757]
### Describe the feature

ability to use commands (from other plugins) in a per-world or per group manner 

### How is the feature useful to all Multiverse users?

i think it would be good

### Agreements

- [x] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by benwoo1110** [comment]
Every plugin codes their own command different, unfortunately MV won't be able to control those. It is up to each plugin to implement per world support in their features. Most major plugins such as essentials, worldguard, luckperms do have per world abilities.
