### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by FrostBlade5** [Multiverse/Multiverse-Core#2758]
### Describe the feature

How can i generate a world with a seed and at the same time use large biomes preset?
I tryed and failed.

/mv create Survival normal -s -4820730562798214825 -t LARGE_BIOMES
/mv create Survival normal -t LARGE_BIOMES -s -4820730562798114825

Those dont work.

### How is the feature useful to all Multiverse users?

they can find a solution

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by benwoo1110** [comment]
You will have to explain a lot more than "it failed". Also, please follow the bug report issue template.
