### ISSUE TITLE
[Bug]: Failure to compile code

### ISSUE THREAD

**Issue by Tsoccerguy3** [Multiverse/Multiverse-Core#2759]
### `/mv version -p` output

Master

### Server logs

NA

### Server Version

```shell
NA
```

### Bug Description

[compile_log.txt](https://github.com/Multiverse/Multiverse-Core/files/8000231/compile_log.txt)

### Steps to reproduce

from command line enter

mvn install

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by Tsoccerguy3** [comment]
For others that are having this compile error . It wont compile on Java 17 and needs Java 8

https://github.com/Multiverse/Multiverse-Core/wiki/Building

Closing this issue

**Comment by nicegamer7** [comment]
This is actually a bug. It should compile on Java 17.
