### ISSUE TITLE
[Bug]: Signs offset themselves after teleport use, return to normal after right click. 

### ISSUE THREAD

**Issue by purejosh** [Multiverse/Multiverse-Core#2760]
### `/mv version -p` output

https://paste.gg/p/anonymous/c86100e4f2b248a8b689ef334f3ad9a5

### Server logs

none

### Server Version

```shell
This server is running Paper version git-Paper-175 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9490475)
You are 23 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-76 (MC: 1.18.1)
```

### Bug Description

After using a sign teleport to a location b, the sign in location b that returns you to location a is offset 2 blocks from where it was originally placed, and the text is missing. If you right click the sign in location b, it disappears, and if you right click where the sign was supposed to be, it teleports you back to location a. 

### Steps to reproduce

create two signs that teleport to eachother in the same world, over 5000 blocks away from each other. 

teleport between them and observe the sign offsetting itself. 

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by purejosh** [comment]
![image](https://user-images.githubusercontent.com/70633949/154108018-6918f7b8-b805-42c5-8355-a5ad20614aee.png)
![image](https://user-images.githubusercontent.com/70633949/154108056-9005e7c5-7cd0-4d39-9a4d-4a2d7a40e5fb.png)

**Comment by zax71** [comment]
I could not reproduce this issue. Below is what I have done

- Create a 1.20.1 server with Multiverse Core and Multiverse Sign Portals
- Go to `0, 0` and create a sign that goes to `e:world:5100,100,0`
- Click on that sign and create another that goes to `e:world:0,100,0`
- Click on that sign to go back to `0,0` and then the sign at `0,0`
- Observe no change in the sign's positions

If I have done something wrong, then feel free to reopen this issue or create a new issue with updated reproduction instructions.

**Comment by purejosh** [comment]
Well yeah, this bug was opened against 1.18.1, over a year and a half ago. 

I assume you've fixed it at some point down the line, or it was an interaction between plugins.
