### ISSUE TITLE
[Idea]: Per world Datapack

### ISSUE THREAD

**Issue by ProJ-Yeet** [Multiverse/Multiverse-Core#2761]
### Describe the feature

To allow specific multiverse worlds to have specific set of datapacks.

### How is the feature useful to all Multiverse users?

This will be very helpful for server creators as you can then have a normal vanilla world side by side with a datapack modded world like with Terralith 2.0

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by benwoo1110** [comment]
Unfortunately, the server software currently doesn't handle datapacks. It is a completely vanilla behaviour that mv can't control. So won't be possible anytime soon.

**Comment by baiyuxiang12** [comment]
nooooo
