### ISSUE TITLE
[Idea]: kill every entity in a specific world

### ISSUE THREAD

**Issue by AlphqDev** [Multiverse/Multiverse-Core#2762]
### Describe the feature

/mv kill @e will kill all entities in the world you are in.

### How is the feature useful to all Multiverse users?

when creating a flat world, a bunch of mobs spawns automatically. this can lag the server and can be awful for people creating a world for a specific purpose(tutorial, spawn)

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Tsoccerguy3** [comment]
This plugin will do this https://dev.bukkit.org/projects/clearlagg

**Comment by Tsoccerguy3** [comment]
[](https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#description-15)[](https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#usage-15)[](https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#examples-14)[](https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#aliases-15)[](https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#permission-15)[](https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#details-15)Purge Command
Description:

Removes the specified entities from the specified worlds
Usage:

/mv purge [WORLD|all] {all|animals|monsters|MOBNAME}
Examples:

/mv purge all
/mv purge world all
/mv purge all all
/mv purge world CREEPER /mv purge world CREEPER,PIG,ZOMBIE
/mv purge all monsters
Aliases:

/mv purge /mvpurge
Permission:

multiverse.core.purge
Details:

The Purge command allows you to remove all of a specified type of entity from a world. Understand that if the spawn rules allow the purged type of mob to spawn, they'll populate almost instantly after the purge. This is used to clear out any remaining mobs from a setting change or if a user abuses a mob spawn command.

If you specify the first parameter as all All worlds will be purged of the specified mob type. You are allowed to specify multiple mob types. Feel free to mix monsters and animals.

**Comment by benwoo1110** [comment]
As stated above, this feature is already present in MV.
