### ISSUE TITLE
[Bug]: Multiverse-Core v4.1.0-b775 - plugin is disabled

### ISSUE THREAD

**Issue by splatchoot** [Multiverse/Multiverse-Core#2768]
### `/mv version -p` output

[WARNING] ....>.... Unexpected exception while parsing console command "mv version -p"  org.bukkit.command.CommandException: Cannot execute command 'mv' in plugin Multiverse-Core v4.1.0-b775 - plugin is disabled.  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-295]  at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:510) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:484) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-295]  at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Server logs

[INFO] .... Time elapsed: 993 ms  [INFO] .... [SimpleTpa] Enabling SimpleTpa v5.9*  [INFO] .... [SimpleTpa] If you need support contact me at https://discord.gg/SZUkza9  [INFO] .... [SimpleTpa] Simple Tpa has been enabled on version 5.9  [INFO] .... Enabled metrics. You may opt-out by changing plugins/bStats/config.yml  [INFO] .... [SkinsRestorer] Enabling SkinsRestorer v14.1.15  [INFO] .... [SkinsRestorer] Using PaperSkinRefresher  [INFO] .... [SkinsRestorer] Detected Minecraft v1_18_R2, using PaperSkinRefresher.  [INFO] .... [SkinsRestorer] [ACF] Enabled Asynchronous Tab Completion Support!  [INFO] .... [CombatWeaponryPlus] Enabling CombatWeaponryPlus v1.4.7  [INFO] .... [InvSee] Enabling InvSee v1.0*  [WARNING] .... java.io.FileNotFoundException: http://kineticraft.net/checkUpdate.php?plugin=InvSee  [WARNING] .... at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)  [WARNING] .... at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)  [WARNING] .... at InvSee.jar//com.snap.invsee.Updater.httpRequest(Updater.java:51)  [WARNING] .... at InvSee.jar//com.snap.invsee.Updater.isUpToDate(Updater.java:63)  [WARNING] .... at InvSee.jar//com.snap.invsee.InvSee.onEnable(InvSee.java:24)  [WARNING] .... at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)  [WARNING] .... at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)  [WARNING] .... at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:535)  [WARNING] .... at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)  [WARNING] .... at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)  [WARNING] .... at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)  [WARNING] .... at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)  [WARNING] .... at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)  [WARNING] .... at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)  [WARNING] .... at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)  [WARNING] .... at java.base/java.lang.Thread.run(Thread.java:833)  [INFO] .... [InvSee] Please install PowerNBT to view offline player inventories  [INFO] .... [Multiverse-Core] Enabling Multiverse-Core v4.1.0-b775  [WARNING] .... [Multiverse-Core] "Multiverse-Core v4.1.0-b775" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Rigby, fernferret, lithium3141, main--, dumptruckman].  [INFO] .... [Multiverse-Core] We are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do. The performance impact is negligible.  [INFO] .... [Multiverse-Core] 3 - World(s) loaded.  [ERROR] .... Error occurred while enabling Multiverse-Core v4.1.0-b775 (Is it up to date?)  java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.getContext()" because "this.scriptEngine" is null  at com.onarandombox.buscript.ScriptManager.<init>(ScriptManager.java:31) ~[Multiverse-Core-4.1.0.jar:?]  at com.onarandombox.buscript.Buscript.<init>(Buscript.java:77) ~[Multiverse-Core-4.1.0.jar:?]  at com.onarandombox.buscript.Buscript.<init>(Buscript.java:65) ~[Multiverse-Core-4.1.0.jar:?]  at com.onarandombox.MultiverseCore.MultiverseCore.initializeBuscript(MultiverseCore.java:351) ~[Multiverse-Core-4.1.0.jar:?]  at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:337) ~[Multiverse-Core-4.1.0.jar:?]  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:535) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-295]  at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-295]  at java.lang.Thread.run(Thread.java:833) ~[?:?]  [INFO] .... [Multiverse-Core] Disabling Multiverse-Core v4.1.0-b775  [INFO] .... [Multiverse-SignPortals] Enabling Multiverse-SignPortals v4.1.0-b748  [ERROR] .... Error occurred while enabling Multiverse-SignPortals v4.1.0-b748 (Is it up to date?)  java.lang.NoClassDefFoundError: com/onarandombox/MultiverseCore/MultiverseCore  at com.onarandombox.MultiverseSignPortals.MultiverseSignPortals.onEnable(MultiverseSignPortals.java:36) ~[Multiverse-SignPortals-4.1.0.jar:?]  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:535) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-295]  at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-295]  at java.lang.Thread.run(Thread.java:833) ~[?:?]  Caused by: java.lang.ClassNotFoundException: com.onarandombox.MultiverseCore.MultiverseCore  at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]  ... 12 more  [INFO] .... [Multiverse-SignPortals] Disabling Multiverse-SignPortals v4.1.0-b748  [INFO] .... [Multiverse-SignPortals] - Disabled  [INFO] .... [Multiverse-Portals] Enabling Multiverse-Portals v4.1.0-b805  [ERROR] .... Error occurred while enabling Multiverse-Portals v4.1.0-b805 (Is it up to date?)  java.lang.NoClassDefFoundError: com/onarandombox/MultiverseCore/MultiverseCore  at com.onarandombox.MultiversePortals.MultiversePortals.onEnable(MultiversePortals.java:106) ~[Multiverse-Portals-4.1.0.jar:?]  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:535) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-295]  at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-295]  at java.lang.Thread.run(Thread.java:833) ~[?:?]  Caused by: java.lang.ClassNotFoundException: com.onarandombox.MultiverseCore.MultiverseCore  at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]  ... 12 more  [INFO] .... [Multiverse-Portals] Disabling Multiverse-Portals v4.1.0-b805  [INFO] .... [Multiverse-NetherPortals] Enabling Multiverse-NetherPortals v4.1.0-b763  [ERROR] .... Error occurred while enabling Multiverse-NetherPortals v4.1.0-b763 (Is it up to date?)  java.lang.NoClassDefFoundError: com/onarandombox/MultiverseCore/MultiverseCore  at com.onarandombox.MultiverseNetherPortals.MultiverseNetherPortals.onEnable(MultiverseNetherPortals.java:60) ~[Multiverse-NetherPortals-4.1.0.jar:?]  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:535) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-295]  at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-295]  at java.lang.Thread.run(Thread.java:833) ~[?:?]  Caused by: java.lang.ClassNotFoundException: com.onarandombox.MultiverseCore.MultiverseCore  at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]  ... 12 more  [INFO] .... [Multiverse-NetherPortals] Disabling Multiverse-NetherPortals v4.1.0-b763  [INFO] .... [Multiverse-NetherPortals] - Disabled  [INFO] .... Starting GS4 status listener  [INFO] .... Thread Query Listener started  [INFO] .... Query running on 0.0.0.0:25565  [INFO] .... Running delayed init tasks  [INFO] .... Done (18.881s)! For help, type "help"  [INFO] .... Timings Reset  [INFO] .... [NexAuth] Auto-save: Saved 0 online users | 0 offline users.  [INFO] .... [Server] Loading Venturecraft.  [INFO] .... [Server] Loading Venturecraft..  [INFO] .... [Server] Loading Venturecraft...  [INFO] .... [Server] Loaded Venturecraft  [INFO] .... [SkinsRestorer] ----------------------------------------------  [INFO] .... [SkinsRestorer] +==================+  [INFO] .... [SkinsRestorer] | SkinsRestorer |  [INFO] .... [SkinsRestorer] |------------------|  [INFO] .... [SkinsRestorer] | Standalone Mode |  [INFO] .... [SkinsRestorer] +==================+  [INFO] .... [SkinsRestorer] ----------------------------------------------  [INFO] .... [SkinsRestorer] Current version: 14.1.15  [INFO] .... [SkinsRestorer] This is the latest version!  [INFO] .... [SkinsRestorer] ----------------------------------------------  [INFO] .... [NexAuth] Auto-save: Saved 0 online users | 0 offline users.  [INFO] ....>.... [Server] [in construction]  [INFO] .... [NexAuth] Auto-save: Saved 0 online users | 0 offline users.  [INFO] .... [NexAuth] Auto-save: Saved 0 online users | 0 offline users.  [INFO] .... [NexAuth] Auto-save: Saved 0 online users | 0 offline users.  [INFO] .... [NexAuth] Auto-save: Saved 0 online users | 0 offline users.  [INFO] .... [NexAuth] Auto-save: Saved 0 online users | 0 offline users.  [INFO] .... [NexAuth] Auto-save: Saved 0 online users | 0 offline users.  [INFO] ....>.... [Server] [in construction]  [INFO] .... [NexAuth] Auto-save: Saved 0 online users | 0 offline users.  [INFO] .... [NexAuth] Auto-save: Saved 0 online users | 0 offline users.  [INFO] .... [NexAuth] Auto-save: Saved 0 online users | 0 offline users.  [INFO] ....>.... [Server] [in construction]  [INFO] .... [NexAuth] Auto-save: Saved 0 online users | 0 offline users.  [INFO] .... [NexAuth] Auto-save: Saved 0 online users | 0 offline users.  [INFO] .... [NexAuth] Auto-save: Saved 0 online users | 0 offline users.  [INFO] ....>.... [Server] [in construction]  [INFO] .... [NexAuth] Auto-save: Saved 0 online users | 0 offline users.  [INFO] .... [NexAuth] Auto-save: Saved 0 online users | 0 offline users.  [INFO] .... [NexAuth] Auto-save: Saved 0 online users | 0 offline users.  [INFO] ....>.... [Server] [in construction]  [INFO] .... [NexAuth] Auto-save: Saved 0 online users | 0 offline users.  [INFO] .... UUID of player splatchoot is 379e89a1-1686-3769-b11e-d9cd6b5b267c  [INFO] .... splatchoot joined the game  [INFO] .... splatchoot[/78.218.222.11:60155] logged in with entity id 225 at ([world]-412.5, 81.0, 40.5)  [INFO] .... [NexAuth] Auto-save: Saved 1 online users | 0 offline users.  [INFO] .... splatchoot lost connection: Login timeout!  [INFO] .... splatchoot left the game  [INFO] .... UUID of player splatchoot is 379e89a1-1686-3769-b11e-d9cd6b5b267c  [INFO] .... splatchoot joined the game  [INFO] .... splatchoot[/78.218.222.11:60188] logged in with entity id 583 at ([world]-412.5, 81.0, 40.5)  [INFO] .... [NexAuth] Player splatchoot logged in!  [INFO] .... Named entity EntitySkeleton['ninja'/633, uuid='ad2fd15e-eb1b-4873-822d-3e4a84580f76', l='ServerLevel[world]', x=-411.40, y=77.75, z=40.27, cpos=[-26, 2], tl=13439, v=true] died: ninja was slain by splatchoot using [Emerald Longsword]  [INFO] .... splatchoot issued server command: /gamemode spectator  [INFO] .... splatchoot issued server command: /gamemode survival  [INFO] .... splatchoot issued server command: /gamemode spectator  [INFO] .... splatchoot issued server command: /gamemode survival  [INFO] .... splatchoot issued server command: /mvcreate survie normal -t  [ERROR] .... null  org.bukkit.command.CommandException: Cannot execute command 'mvcreate' in plugin Multiverse-Core v4.1.0-b775 - plugin is disabled.  at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]  at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2306) ~[?:?]  at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2117) ~[?:?]  at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2098) ~[?:?]  at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]  at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]  at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]  at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]  at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]  at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]  at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]  at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[paper-1.18.2.jar:git-Paper-295]  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-295]  at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Server Version

```shell
[INFO] ....>.... Checking version, please wait...

[INFO] .... This server is running Paper version git-Paper-295 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: c642d25)

You are 4 version(s) behind

Download the new version at: https://papermc.io/downloads

Previous version: git-Paper-290 (MC: 1.18.2)
```

### Bug Description

When running /mv create "world name" etc... it's say [Internal error as occured]

### Steps to reproduce

1. Install multiverse
2. run the server
3. run /mv create <world name> etc...

result = [an internal error as occured while attempting to run this command

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by nicegamer7** [comment]
This was a bug that was fixed in MV Core 4.2.2, please update (preferably to the latest version).
