### ISSUE TITLE
[Bug]: Mobs cannot reach the overworld through the portal in the nether unless all other players are near either the portal in the overworld

### ISSUE THREAD

**Issue by crizyx** [Multiverse/Multiverse-Core#2770]
### `/mv version -p` output

https://bit.ly/3OYWDHu

### Server logs

https://paste.gg/p/anonymous/2ec187ae89a5444d8407836004c118ae

### Server Version

```shell
[10:08:31 INFO]: This server is running Paper version git-Paper-317 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e5da93a)
```

### Bug Description

Mobs (zombie, hoglin, spider, ghast...) cannot arrive in the overworld by crossing the nether portal in the nether world when another player is in the same overworld as me.

It's only when the other player is next to the portal I want the mobs to go through that they can spawn.
I tried with another type of creature, animals (chiken, pig, cow, horse) and with these creatures it works fine.

The problem is only related to mobs type creatures.

This has an impact on the game experience of players because they can no longer factory Shulkers for example but it also prevents obtaining advancements:
- Uneasy Alliance (Rescue a Ghast from the Nether, bring it safely home to the Overworld... and then kill it)
- Monster **Hunted** (Kill any hostile monster; To kill a Zoglin we need to transform a Hoglin in Zoglin by passing it in the Overworld)

### Steps to reproduce

Steps to reproduce :
1. Make a server with latest paper build and multiverse-core & multiverseNetherPortals (This problem has existed for several years, at least two and a half years so it does not matter the build but for more accuracy use the latest).

2. Create a new worlds, like world_other and world_other_nether.
  /mvc world_other normal
  /mvc world_other_nether nether

3. Link world_other with world_other_nether.
  /mvnp link nether world_other world_other_nether
  /mvnp link nether world_other world_other_nether

5. Connect a player[1] and go to make vanilla nether portals in your new Overworld (world_other) and Nether (world_other_nether).
  One in Overworld (world_other)
  One in Nether (world_other_nether)
  Sync it with coords if you want to be sure
  
 6. Connect another player[2] and go far to the first portals to make vanilla nether portals in your new Overworld (world_other) and Nether (world_other_nether) and let him close by preference.
  One in Overworld (world_other)
  One in Nether (world_other_nether)
  Sync it with coords if you want to be sure
  
  7. Go to the nether with the player[1] and try moving creatures from the nether to the overworld, try animals, then mobs.
  As you can see :
  Animals can arriving in the Overworld
  Mobs **can't** arriving in the Overworld
```
  Animals are (cows, horses, bats, chickens...)
  Mobs are (zombies, ghasts, hoglins, slimes...) 
```
  
8. Teleport the player[2] close to you or close to the Overworld nether portal which you use to pass your creatures.
  As you can see :
  Animals can arriving in the Overworld
  Mobs can arriving in the Overworld
 
9. Teleport the player[2] to another world than the overworld in which you want to move creatures or disconnect him.
  As you can see :
  Animals can arriving in the Overworld
  Mobs can arriving in the Overworld
  
 10. In conclusion, if a player other than you is in the world you want to pass mobs through and they're not near the portal you want them to pass through, the mobs won't arrive in the Overworld you're targeting

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by Podgorica** [comment]
Not an issue with MV but behaviour of the server/Minecraft itself. See [issue #2261](https://github.com/PaperMC/Paper/issues/2261) on Paper.
