### ISSUE TITLE
[Idea]: Add new world property: gravity

### ISSUE THREAD

**Issue by BookWyrm114** [Multiverse/Multiverse-Core#2772]
### Describe the feature

Allow for setting the value of a world's gravity from -50 to 50. this affects all entities in the world. 0 gravity would cause everything to float, anything above 0 would cause stuff to fall downwards at a rate depending on the gravity value, and anything below 0 would cause all entities to float upwards at a rate depending on the gravity value. preferably 0 gravity would still allow players to slowly move in all directions via WASD, space, and shift.

### How is the feature useful to all Multiverse users?

besides being fun to play around with, it will allow for adding worlds with very unique properties, such as an empty world with 0 gravity that players can access and use for building, and will be especially useful on servers that are space-themed, but will also be useful on any server implementing custom dimensions to make each dimension feel a little more unique.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by zax71** [comment]
Seams very out of scope, would be much more fitting in another plugin
