### ISSUE TITLE
[Idea]: Add support for java 17

### ISSUE THREAD

**Issue by Remering** [Multiverse/Multiverse-Core#2779]
### Describe the feature

Java 17 no longer support nashorn script engine, is there a replaced way?

### How is the feature useful to all Multiverse users?

I use minecraft version 1.16.5, there are many plugins which only supports Java 17.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by willkroboth** [comment]
I'm pretty sure Multiverse does support Java 17? It works for me at least. As far as I know, Java is backwards compatible, so programs compiled in Java 16 (and lower) can run on Java 17 automatically. I suppose your comment suggests that the "nashorn script engine" is not backwards compatible, though I don't understand how that is connected to Multiverse? I'm also pretty sure that the maximum Java version allowed by Spigot when running 1.16.5 is Java 16, so you can't use your minecraft version with Java 17 anyways (unless you're using something other than Spigot).

Could you explain your idea further?

**Comment by dggamingk** [comment]
i have the same problem, anyone have a solution for this?

**Comment by willkroboth** [comment]
What exactly is not working? Can you send a server log? Multiverse seems to work for me on Java 17 for adding, deleting, teleporting between worlds etc, and I'm not sure what to try next to reproduce the issue you all have.

**Comment by benwoo1110** [comment]
buscript will be removed
