### ISSUE TITLE
[Bug]: Plugin disabling itself 

### ISSUE THREAD

**Issue by MaouGoku** [Multiverse/Multiverse-Core#2782]
### `/mv version -p` output

some internal error occurred

### Server logs

https://gist.github.com/MaouGoku/44261e89a63eb7d4e946c7981161336b

### Server Version

```shell
1.16.5
```

### Bug Description

while starting the server the plugin will fail to enable itself
cant use commands of the plugin

### Steps to reproduce

dunno

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by nicegamer7** [comment]
Mohist is not a supported platform. The reason for this is that Mohist, as mentioned above, often causes errors that would not occur on a regular Bukkit server.
