### ISSUE TITLE
[Bug]: Create World Crash / Kick Player

### ISSUE THREAD

**Issue by Bossbirdyman51** [Multiverse/Multiverse-Core#2790]
### `/mv version -p` output

https://bit.ly/3cG3QgZ

### Server logs

https://pastebin.com/DaFYzMKu

### Server Version

```shell
This server is running Paper version git-Paper-77 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 44b6869)
```

### Bug Description

When i create a world like /mv create test normal -g VoidGen the server crash and kick all player, after 20/30 Secs we can reconnect and the world was created.

### Steps to reproduce

Start the server
/mv create test normal -g VoidGen

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment]
This is normally an issue with server peformance, can you send a spark report of the issue by installing the [Spark plugin](https://www.spigotmc.org/resources/spark.57242/) then running the following commands

`/spark profiler start`
`/mvcreate <world name> NORMAL`
`/spark profiler upload`

Once complete, send the generated link.

**Comment by zax71** [comment]
Stale issue
