### ISSUE TITLE
[Bug]: Initial world not in mv list. Cannot import, add, or teleport back to it as it's deemed "null".

### ISSUE THREAD

**Issue by MadKat913** [Multiverse/Multiverse-Core#2792]
### `/mv version -p` output

https://paste.gg/9ea669baad56426d859c428de40b4b0a

### Server logs

https://paste.gg/p/anonymous/0e207c486bf94a429f12126c95098c7e

### Server Version

```shell
Craftbukkit 3554-Spigot-2183145-6da8266 (MC: 1.19.1)
(Implementing API version 1.19.1-RO.1-SNAPSHOT)
```

### Bug Description

When using /mv list, the initial world, end world, and nether world do not appear. Trying to import the initial world in said world, or importing it into other worlds does not work. 

When teleporting to a successfully made world, I cannot teleport back to the initial one as it's marked as "null". 

I am trying to do an online summer camp and don't know how to solve this. The initial world includes the camp map, and I need the additional worlds for mini games for the campers. I'm clearly not that tech savvy, and appreciate any help.

### Steps to reproduce

1. Jump into server
2. /mv list
3. Nothing shows up
4. I added two new worlds (creative, and parkour)
5. Teleport to either world
6. Cannot teleport back to initial world it says it's "null"
7. Cannot create initial world into it's own world
8. Brain explodes

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment]
```
  | 29.07 16:46:54 [Server] Server thread/WARN World name should not contain spaces or special characters!
  | 29.07 16:46:54 [Server] Server thread/WARN Invalid world name 'Tech Camp_nether'
  | 29.07 16:46:54 [Server] Server thread/WARN World name should not contain spaces or special characters!
  | 29.07 16:46:54 [Server] Server thread/WARN Invalid world name 'Tech Camp_the_end'
  | 29.07 16:46:54 [Server] Server thread/WARN World name should not contain spaces or special characters!
```
**World name should not contain spaces or special characters!**
