### ISSUE TITLE
[Idea]: Add release builds in case someone doesn't want to compile it themselves

### ISSUE THREAD

**Issue by Bigmancozmo** [Multiverse/Multiverse-Core#2797]
### Describe the feature

I think that the plugin should have release builds. This is because I am hosting my server on a Raspberry Pi and my web browser is broken and does not work, but using the Spigot download just returned an error

### How is the feature useful to all Multiverse users?

The plugin can be easily downloaded from a terminal.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by benwoo1110** [comment]
We have a Jenkins CI website: http://ci.onarandombox.com/job/Multiverse-Core/

It has direct download links such as http://ci.onarandombox.com/job/Multiverse-Core/861/artifact/target/Multiverse-Core-4.3.1.jar

For raspberry pi, I believe you can use the wget command in terminal for downloading from urls

**Comment by Bigmancozmo** [comment]
Oh, could not find that.
