### ISSUE TITLE
[Bug]: Plugin Disabling

### ISSUE THREAD

**Issue by MegaJeuxyt** [Multiverse/Multiverse-Core#2798]
### `/mv version -p` output

Multiverse-Core v4.1.0-b775

### Server logs

https://pastebin.com/NYaFLdkg

### Server Version

```shell
Mohist 1.16.5 #1075
```

### Bug Description

Server Disable plugin

### Steps to reproduce

1. install Mohist 1.16.5 #1075 server
2. install Multiverse-Core v4.1.0-b775 plugin
3. launch server

### Agreements

- [x] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment]
Mohist is not a supported platform. Please use spigot or paper.
