### ISSUE TITLE
[Idea]: Portal Traveling with other worlds!

### ISSUE THREAD

**Issue by emlm244** [Multiverse/Multiverse-Core#2801]
### Describe the feature

This feature is not listed for Multiverse Portals. 

When you create a normal, a nether, and an end world with multiverse and try to go through the nether, it would teleport you to the ORGINAL nether. (Orginal as in default nether) It would not teleport you to the new nether that you created.

What I want is a feature where you can link up the nether and the end to the normal world you want. Furthermore, I could not find this feature in Multiverse Portals so I was wondering If you guys could do something about it.

### How is the feature useful to all Multiverse users?

When you try to host multiple different worlds with nethers and ends you can have all your friends play on their "Singleplayer" worlds without interference. So the server can deal with all their computing resources while they can just load up free of lag, and join their "SinglePlayer" worlds. 

This is like you hosting their "Singleplayer" worlds without nobody joining it except you.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by willkroboth** [comment]
This is possible already, not using Multiverse-Portals, but [Multiverse-NetherPortals](https://dev.bukkit.org/projects/multiverse-netherportals/). The [core page](https://dev.bukkit.org/projects/multiverse-core) lists this after Multiverse-Portal features:

[Multiverse-NetherPortals](https://dev.bukkit.org/projects/multiverse-netherportals/) features:
- Have nether and end worlds per for any of your overworlds!
...
- For more information, visit the [wiki for Multiverse-NetherPortals](https://github.com/Multiverse/Multiverse-Core/wiki/Home-(NetherPortals)/).

You want the `/mvnp link` command, which is described [here](https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference-%28NetherPortals%29#link).

Hope that works for you!

**Comment by emlm244** [comment]
Thanks! I will go try that out immediately.
