### ISSUE TITLE
[Idea]: Suggestion about performing a blocking I/O operation on the main thread

### ISSUE THREAD

**Issue by FunkyNico** [Multiverse/Multiverse-Core#2803]
### Describe the feature

Hello, I have found this suggestion from another spigot plugin called [Lagmonitor ](https://github.com/games647/LagMonitor): Make stop the plugin from doing a blocking I/O operation on the main thread because this could affect the server performance, the thread pauses until it gets the response. Such operations should be performed asynchronous from the main thread.

Multiverse-Core Version: v4.3.2-SNAPSHOT-b870 / Server: Purpur-1762 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 39e30d6 on HEAD).

Log: https://logs.apexminecrafthosting.com/RbFMxn5

### How is the feature useful to all Multiverse users?

Besides gameplay performance it could also improve startup time.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by benwoo1110** [comment]
Unfortunately world operations such as load/unload/create/delete cannot be done asynchronously with the current bukkit api.
