### ISSUE TITLE
[Bug]: I can never import or create world because it fails

### ISSUE THREAD

**Issue by Laggyzzz** [Multiverse/Multiverse-Core#2804]
### `/mv version -p` output

https://paste.gg/p/anonymous/aff85438f98444e5b1ad4c08cc800880

### Server logs

https://paste.gg/p/anonymous/6500ad8a6b8249bf91a88bd0a4123f34

### Server Version

```shell
This server is running CraftBukkit version 286405ee (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge Version 40.1.54)
```

### Bug Description

when I try to create or import a world it always fails.

### Steps to reproduce

run the create or import world command

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by RBGAMING1** [comment]
Same to me

**Comment by kotarobo** [comment]
I seem to be getting the same error with 1.19.2 paper
https://pastebin.com/fBNV2tV8

**Comment by NeverGrowUp** [comment]
Multiverse doesn't work on forge, magma or modded type servers. Spigot, paper, or it's forks only type servers

**Comment by kotarobo** [comment]
Sorry, mine just had the wrong file owner.

**Comment by benwoo1110** [comment]
> Multiverse doesn't work on forge, magma or modded type servers. Spigot, paper, or it's forks only type servers

^^
