### ISSUE TITLE
[Bug]: Failed to log in to a different world

### ISSUE THREAD

**Issue by LycanrockZ** [Multiverse/Multiverse-Core#2807]
### `/mv version -p` output

2.5

### Server logs

https://paste.gg/p/anonymous/59ba41682c2d4c2b8c1b6344e4a1be65

### Server Version

```shell
1.12.2 magma
```

### Bug Description

When I start on my server I appear in nowhere and I have to put /mv tp world , but if I connect in world that does not happen to me. Could someone help me with this problem, the other world is imported.
Thanks.

### Steps to reproduce

1-Start on the server and travel to the imported world
2-Disconnect and reconnect
3- I would already be

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment]
Multiverse does not support hybrid server types such as magma
