### ISSUE TITLE
[Bug]: Error when create a new world

### ISSUE THREAD

**Issue by Valenn1898** [Multiverse/Multiverse-Core#2808]
### `/mv version -p` output

Multiverse-Core Version: 4.3.1-b861

### Server logs

https://gist.github.com/Valenn1898/1d0535aac91c9cd148f370535ff11ba6

### Server Version

```shell
arclight-1.18.2-1.0.6-7e754e7e (MC: 1.18.2)
```

### Bug Description

when i try to create a world  it is failed

### Steps to reproduce

1- Start server with multiversecore instaled
2- put command /mv create (worldname) normal
3- failed 

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [ ] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by ImCardiaK** [comment]
same problem !

**Comment by WazzouGFX** [comment]
Hello 

I have the same problem 

when i go to /mv list i see my world but is unload and is imposible to load 

they say faild to load world 

how to fix this

**Comment by benwoo1110** [comment]
MV doesnt support arclight. Please use spigot or paper.
