### ISSUE TITLE
[Bug]: server warning Buscript failed to load

### ISSUE THREAD

**Issue by KobraDad** [Multiverse/Multiverse-Core#2809]
### `/mv version -p` output

https://paste.gg/07ad4ea96da14859ba0487e9a48fcce3

### Server logs

https://paste.gg/p/anonymous/086c92b296cd46ea8acc5855612db612

### Server Version

```shell
This server is running Paper version git-Paper-135 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: eff22eb)
You are running the latest version
Previous version: git-Paper-111 (MC: 1.19.1)
```

### Bug Description

on server startup, received warning:
29.08 19:31:05 [Server] WARN [Multiverse-Core] Buscript failed to load! The script command will be disabled! If you would like not to see this message, use `/mv conf enablebuscript false` to disable Buscript from loading.

### Steps to reproduce

restart server

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by nicegamer7** [comment]
This isn't an issue, just a warning that the `/mv script` command won't work. You can disable the warning by running `/mv conf enablebuscript false`.
