### ISSUE TITLE
[Idea]: Per World Resource Packs

### ISSUE THREAD

**Issue by DarkAxi0m** [Multiverse/Multiverse-Core#2810]
### Describe the feature

I have no idea if this is possible (or if it should be working, and mine just isnt), but i think it would be great to be able to set a Resource Pack that is included an a downloaded world.  (like single player)

e.g. https://www.minecraftmaps.com/finding-maps/a-snowy-christmas

### How is the feature useful to all Multiverse users?

It would over up the Multiverse to more themes etc

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by zax71** [comment]
Seams out of scope for MV, per world resource packs could also be an annoyance for players
