### ISSUE TITLE
[Idea]: `/mv gamerule` option to apply the new rule setting to all worlds.

### ISSUE THREAD

**Issue by ccrvincent** [Multiverse/Multiverse-Core#2814]
### Describe the feature

Example:
The Vanilla Tweaks 'Graves' datapack requires the `keepInventory` gamerule to be set to `true` in all dimensions.  As the rule defaults to `false`, this requires walking the list of all dimensions and setting the rule individually when adding the datapack to an existing world.

### How is the feature useful to all Multiverse users?

The ability to change a rule in all worlds with a single command would be a benefit for consistency and complexity to the admin.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by zax71** [comment]
Added in the [MV5](https://github.com/Multiverse/Multiverse-Core/tree/MV5) branch, will be merged to master when the whole update is complete
