### ISSUE TITLE
[Bug]: Multiverse-Patches doesn't work

### ISSUE THREAD

**Issue by rageyh** [Multiverse/Multiverse-Core#2818]
### `/mv version -p` output

https://prnt.sc/cW0JE9z8olZe

### Server logs

https://prnt.sc/qZdOddWUcvDU

### Server Version

```shell
This server is running Paper version git-Paper-411 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6625db3 on ver/1.17.1)
```

### Bug Description

When starting the server, the plugin gives an error and is disabled

### Steps to reproduce

1. Start the server
2. Error

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by nicegamer7** [comment]
You're using the latest version of MV, so you don't need the patch plugin. The patch plugin is only needed for old versions of MV.
