### ISSUE TITLE
[Bug]: locked in FLAT worldtype generation

### ISSUE THREAD

**Issue by AKtomik** [Multiverse/Multiverse-Core#2819]
### `/mv version -p` output

https://paste.gg/edb119025e374aee99fbae7161cbaac1

### Server logs

https://paste.gg/p/anonymous/9b25ffe134254adda3c2496b66ffd962

### Server Version

```shell
This server is running Paper version git-Paper-366 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 8d7d927)
You are running the latest version
Previous version: git-Paper-323 (MC: 1.19.3)
```

### Bug Description

since a while, I fail to get a world with a NORMAL generation, because all my worlds - old or new-created - generating with the FLAT worldtype generation.

For example, when i create a new world - even in specifying the world type (with `-t NORMAL`) - the world generation is flat :
![image](https://user-images.githubusercontent.com/97125853/210178592-c84177a3-fa40-4df6-a8bc-a2f40aad3314.png)
But its not the same thing when i dirrectly create a flat world : we can see the sky is not the same. (⬆dark, but not night ⬇️normal)
![image](https://user-images.githubusercontent.com/97125853/210179269-868d4ea9-e1dd-409b-9a6a-4f6a00ae9ab7.png)

### Steps to reproduce

I dont konw exactlty when and why its happend, i used some generator and update my server in the 1.19.3 version at the same time.
But now, I have removed any generator plugin when i saw the bug, and the bug is still there, even in new-created worlds.
**I can't try to get the trigger of the bug beceause I cant remove the bug :/**

So, step to reproduct **but im not sure** : 
1. create a server in 1.19.3 with multiverse and multiverse-inventory
2. _try to use VoidGenerator and Terra ?_
3. type `/mv create test normal -t normal` or generate new chuncks in a existing world
And normaly, your world generation is flat 
(you can now remove VoidGenerator and Terra, and the bug is still here)

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by Jeenvries** [comment]
Same issue on my server

**Comment by zax71** [comment]
I cannot reproduce this issue, can you re-open the issue with tested reproduction instructions
