### ISSUE TITLE
[Bug]: regenerate with --keep-gamerules and -s ignores seed

### ISSUE THREAD

**Issue by FakEEE14** [Multiverse/Multiverse-Core#2822]
### `/mv version -p` output

4.3.2-SNAPSHOT-b870

### Server logs

none

### Server Version

```shell
paper 1.19.3
```

### Bug Description

when you use /mv regen {WORLD} [-s [SEED]] [--keep-gamerules]
this should regenerate the world with seed you want and all flags keep same but the seed should be a word, if you use a number in the [Seed] it's get changed to 0

### Steps to reproduce

- Create a 1.20.1 Paper server with Multiverse core
- Create a testing world `/mv create test normal`
- Regenerate it: `/mv regen test -s 11111 --keep-gamerules`
- Run `/mv info` and notice seed is `0` not `11111`

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment]
The world border is not a gamerule, and thus it does not get remembered with `--keep-gamerules` but the `-s` is ignored in testing

**Comment by VOrlando520** [comment]
Can also confirm I am having these issues as well
