### ISSUE TITLE
[Multiverse-Core] "Multiverse-Core v4.3.1-b861" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].[Bug]: 

### ISSUE THREAD

**Issue by Xipher81** [Multiverse/Multiverse-Core#2823]
### `/mv version -p` output

https://paste.gg/94b10dde291f4e2b94154734c56611e4

### Server logs

https://mclo.gs/4ca0kso

### Server Version

```shell
[15:48:07 INFO]: This server is running Paper version git-Paper-386 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4da844f)
```

### Bug Description

Was reading through the logs and seen the warning to report to devs

### Steps to reproduce

Started server

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by Lildirt** [comment]
.. and right on the line after this warning message, you see this:

```
[15:30:07 INFO]: [Multiverse-Core] §aWe are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.
```

This event does not have a noticeable performance impact with the way that Multiverse uses it. This is also addressed in the Discord, under #deprecated-event. MV staff have been aware of it, and we just have to live with it for right now until a better solution comes around.

**Comment by benwoo1110** [comment]
#2000
