### ISSUE TITLE
[Bug]:  MV GENS ERROR

### ISSUE THREAD

**Issue by Faustyu1** [Multiverse/Multiverse-Core#2830]
### `/mv version -p` output

[17:04:05 INFO]: [Multiverse-Core] Multiverse-Core Version: 4.3.1-b861 [17:04:05 INFO]: [Multiverse-Core] Bukkit Version: git-Purpur-1171 (MC: 1.16.5)

### Server logs

https://paste.gg/p/anonymous/ab2ce6fc9a1d402c8ac40d5113b70650

### Server Version

```shell
This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
```

### Bug Description

i write nv gens

### Steps to reproduce

1. Start the server plugin is multiverse-core and moongenerator2 and...
2. console write /mv gens
3. error write 

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment]
Likely an issue with other plugin's configuration. Please give more detailed reproduction instructions.

**Comment by zax71** [comment]
Closing as stale
