### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DerpChrisGaming** [Multiverse/Multiverse-Core#2831]
### `/mv version -p` output

https://paste.gg/e57a21f4209849e4b0f2a9b0968e6a7c

### Server logs

https://paste.gg/p/anonymous/3239fe470a874854b51689221a24fa34

### Server Version

```shell
git-[a[er-372 (MC:1.19.3)
```

### Bug Description

Players are randomly teleported to another world, with no commands being run. We have our normal world, (With its Nether & End) and then I added a dropper map to the server. Players are reporting randomly being teleported to the spawn area in the Dropper world. There doesnt appear to be any commands being run from looking at server console.

### Steps to reproduce

1. Start Server with multiverse installed.
2. play the game
3. get randomly teleported to the other world

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by DerpChrisGaming** [comment]
Here is a link to a video of the bug https://youtu.be/kWCLvlFNJTc

**Comment by zax71** [comment]
This is likely not a MV issue. Please re-open another issue with working reproduction instructions if this is not the case
