### ISSUE TITLE
[Bug]: When players dies in Nether, they're spawning in Nether.

### ISSUE THREAD

**Issue by MrGortyIMP** [Multiverse/Multiverse-Core#2860]
### `/mv version -p` output

https://paste.gg/2fa99de53ffc4214af544f23c9c4fea9

### Server logs

none

### Server Version

```shell
This server is running CraftBukkit version 3661-Spigot-19641c7-8434e36 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT)
```

### Bug Description

When players dies in the any nether dimension, they're spawning in dimension where died.
Server have this plugins: LuckPerms, FInvsee, WorldEdit, GSit, ArmorStandAdjustor, SuperVanish, LoginSecurity, Multiverse-Core, CoreProtect, Multiverse-Portals, TabList, Multiverse-NetherPortals
Multiverse plugins: Multiverse-Core, Multiverse-Portals, Multiverse-NetherPortals

I wasn't used any spawn command for /mv, /mvp, /mvnp
I tried to start second server with this plugins, but result was same.

How to fix that?

### Steps to reproduce

1. Go to the any nether portal (2 world and 2 nether dimensions connected)
2. Died
3. Spawn in the world, where i died (Nether too)

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by Lildirt** [comment]
This is possibly the default behaviour, respawning a player at their death world's spawn.

See the [`/mv modify` command](https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#modify-command-set) for how to set the respawn world. Set the Nether's respawn world to your Overworld. Do the same for the End world.

**Comment by zax71** [comment]
Closing the issue as this is resolved. Feel free to open a new issue or contact us via Discord if you require any further assistance.
