### ISSUE TITLE
[Bug]: Teleportation Denied

### ISSUE THREAD

**Issue by Steev93** [Multiverse/Multiverse-Core#2868]
### `/mv version -p` output

https://paste.gg/8740de35438f41049d7ab649269c41dd

### Server logs

https://paste.gg/p/anonymous/dda7285939cd4b63ac17ce2bcb6d2a25

### Server Version

```shell
git-Paper-365 (MC: 1.19.3)
```

### Bug Description

Players all have access to multiverse.access.world_nether for example, the debug reads it as they don't have access however in lucky perms they have access.

https://prnt.sc/2tTe27gCDnTu

However it carries out that "You Don't Have permission"

Debug Logs
https://paste.gg/p/anonymous/1b8c7b82e1d64efbaf78241d9fb5f052

### Steps to reproduce

Start the server and got through the portal, no access to teleport to that world.

[15:27:42 INFO]: [Multiverse-Core-Debug] Checking 'CraftPlayer{name=Grim801}' can send 'CraftPlayer{name=Grim801}' somewhere
[15:27:42 INFO]: [Multiverse-Core-Debug] Checking to see if player [Grim801] has permission [multiverse.access.world_the_end]... NO
[15:27:42 INFO]: [Multiverse-Core-Debug] Player 'Grim801' was DENIED ACCESS to 'world_the_end' because they don't have: multiverse.access.world_the_en

However in luckyperms, the group he is in has the permission. 
multiverse.access.world_the_end

https://prnt.sc/Z7i8s3yVv83f

https://prnt.sc/EOZB-okDQf06 

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by Lildirt** [comment]
Seems to be a permissions config issue here and not a MV bug.

Based on the screenshot of your permissions list (no context for what this list is for, assuming it's the group), they don't have the `multiverse.access.world_the_end` permission. They *do* have `multiverse.access.world_nether`, but not the other one.

LuckPerms has a means for you to test a permission on a specific player (e.g., `/lp user <user> permission check multiverse.access.world_the_end`), so I'd recommend using that to validate your permissions setup.

**Comment by Steev93** [comment]
> Seems to be a permissions config issue here and not a MV bug.
> 
> Based on the screenshot of your permissions list (no context for what this list is for, assuming it's the group), they don't have the `multiverse.access.world_the_end` permission. They _do_ have `multiverse.access.world_nether`, but not the other one.
> 
> LuckPerms has a means for you to test a permission on a specific player (e.g., `/lp user <user> permission check multiverse.access.world_the_end`), so I'd recommend using that to validate your permissions setup.

They definitely have the right permissions, I even added it to every rank.
