### ISSUE TITLE
[Idea]: First-party support for Placeholders

### ISSUE THREAD

**Issue by Lildirt** [Multiverse/Multiverse-Core#2876]
### Describe the feature

Multiverse doesn't have placeholder support built into any of the plugins. We should arrange that once more of the backlog is churned through. [Link to the original inquiry on Discord](https://discord.com/channels/325459248047980545/325494796221415424/1080197415421870110) which caused us to open this issue.

Looks like there's been some work by nicegamer7 (and maybe others), which [can be found here](https://github.com/PlaceholderAPI/Multiverse-Expansion).

### How is the feature useful to all Multiverse users?

Lots of people have asked for placeholders and we've had some (kind of) third-party PlaceholderAPI support for a while, but it's not actually baked into the MV plugins themselves.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by zax71** [comment]
Current List of placeholders made by third party's:

%multiverse_world_alias%

%multiverse_world_all_property_names%

%multiverse_world_generator%

%multiverse_world_name%

%multiverse_world_name_colored%

%multiverse_world_permissible_name%

%multiverse_world_time%

%multiverse_world_animals_spawn_enabled%

%multiverse_world_monsters_spawn_enabled%

%multiverse_world_access_permission%

%multiverse_world_adjust_spawn_enabled%

%multiverse_world_allow_flight_enabled%

%multiverse_world_auto_heal_enabled%

%multiverse_world_auto_load_enabled%

%multiverse_world_bed_respawn_enabled%

%multiverse_world_color%

%multiverse_world_currency%

%multiverse_world_difficulty%

%multiverse_world_environment%

%multiverse_world_gamemode%

%multiverse_world_hunger_enabled%

%multiverse_world_player_limit%

%multiverse_world_price%

%multiverse_world_seed%

%multiverse_world_style%

%multiverse_world_type%

**Comment by zax71** [comment]
Implemented in the MV5 branch
