### ISSUE TITLE
[Idea]: Join world config option

### ISSUE THREAD

**Issue by zax71** [Multiverse/Multiverse-Core#2889]
### Describe the feature

A listener for the playerJoinEvent that teleports the player to a specified world in config

### How is the feature useful to all Multiverse users?

Commonly requested in Discord support

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by dumptruckman** [comment]
Just make sure it's called something other than "default world" because that carries very little meaning.

**Comment by zax71** [comment]
Requires the config PR to be merged first (can’t link as it isn’t open yet)

**Comment by zax71** [comment]
Implemented in #2992
