### ISSUE TITLE
[Bug]: Multiverse switching generators for chunks

### ISSUE THREAD

**Issue by Arthurmeade12** [Multiverse/Multiverse-Core#2890]
### `/mv version -p` output

https://paste.gg/161c938ef063460684f9ace6e7aedd4a

### Server logs

https://gist.github.com/Arthurmeade12/b09c1812e9f4b2c48ed88acbc0983d43

### Server Version

```shell
[18:47:52 INFO]: Checking version, please wait...
[18:47:52 INFO]: Current: git-Purpur-1933 (MC: 1.19.3)*
Previous: git-Purpur-1930 (MC: 1.19.3)
* You are running the latest version
```

### Bug Description

In my world, creative2, I have set the custom generator [Terra](https://terra.polydev.org), with the default generation pack. Multiverse decides to generate vanilla terrain in certain chunks, however, creating a wall of terrain.

### Steps to reproduce

1. Generate a world with Terra: seed 93106867 and all the Multiverse extras installed.
2. Teleport to 1661 77 577
3. 
![2023-03-15_19 02 48](https://user-images.githubusercontent.com/71673838/225472801-74d31b92-5de2-46a4-b7bf-db88ec1305a3.png)
![2023-03-15_19 02 56](https://user-images.githubusercontent.com/71673838/225472809-84d22e1d-05f1-4111-8797-8548e54d28b4.png)
![2023-03-15_19 03 08](https://user-images.githubusercontent.com/71673838/225472812-714f76db-a32e-4c48-bf81-935b6c8895f5.png)

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment]
Likely an Issue with Terra, please report there.
