### ISSUE TITLE
[Bug]: Cant Remove Alias

### ISSUE THREAD

**Issue by rbcoder117** [Multiverse/Multiverse-Core#2891]
### `/mv version -p` output

https://paste.gg/a0564991fea04b629fbe3bbd5f5e39e2

### Server logs

/mvm remove alias Game1 -- With No Other Output

### Server Version

```shell
[20:15:16 INFO]: This server is running Paper version git-Paper-431 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: e574412)
You are 17 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-307 (MC: 1.19.2)
```

### Bug Description

Cant Remove an alias after its created

### Steps to reproduce

Start a server 
Create a Alias by doing /mvm set alias _Name_
Then run /mvm remove alais _Name_

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment]
Have you tried `/mv modify set alias "" <worldname>`

**Comment by rbcoder117** [comment]
thank you
