### ISSUE TITLE
[Bug]: Circular plugin loading detected!

### ISSUE THREAD

**Issue by pricelessdev** [Multiverse/Multiverse-Core#2894]
### `/mv version -p` output

Multiverse-Core-4.3.1.jar

### Server logs

https://paste.gg/p/anonymous/e81f5d3a52a54ffeac00253377a569c0

### Server Version

```shell
1.19.4
```

### Bug Description

Can't start the server cause of [14:14:06 ERROR]: [io.papermc.paper.plugin.storage.SimpleProviderStorage] Circular plugin loading detected!

Can't issue /mv for obvious reasons.

### Steps to reproduce

Start the server in 1.19.4

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment]
Another plugin is loading MV as a dependency wrongly directly/indirectly. Seems like the plugin with the issue is `WildStacker`. You can test by remove plugins until the error stops.
