### ISSUE TITLE
[Idea]: Teleport, view direction, 

### ISSUE THREAD

**Issue by TheOverlord-1019** [Multiverse/Multiverse-Core#2905]
### Describe the feature

Hello. Who I teleport I often stand, sideways, in the portal 
Is it possible to add one, viewing direction 

### How is the feature useful to all Multiverse users?

if I stand on the side of the portal I can walk out the wrong way and Porte back again 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by TheOverlord-1019** [comment]
Gibt es keine möglichkeit beim teleportieren die Blickrichtung zu ändern ich stege immer seitwärts im Portal oder Falschrum

**Comment by zax71** [comment]
Is this related to Multiverse nether portals or Multiverse Portals?
