### ISSUE TITLE
[Bug]: Maven repo down

### ISSUE THREAD

**Issue by Matthewn7** [Multiverse/Multiverse-Core#2906]
### `/mv version -p` output

NA

### Server logs

NA

### Server Version

```shell
NA
```

### Bug Description

https://repo.onarandombox.com/content/groups/public/com/onarandombox/multiversecore/Multiverse-Core/4.3.8/

Seems the repo is down. Can anything be done?

Thanks.

### Steps to reproduce

NA

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by dumptruckman** [comment]
Please note that per the wiki the artifact id is now lowercased https://github.com/Multiverse/Multiverse-Core/wiki/Developer-API-Starter

This is a requirement for hosting our packages on GitHub Packages. Additionally, because of that change, you generally cannot browse the repo for an artifact. However, it should still be resolvable via Maven.

**Comment by Matthewn7** [comment]
Thanks for the quick response.

```
[ERROR] Failed to execute goal on project (redacted): Could not resolve dependencies for project (redacted): Could not find artifact com.onarandombox.multiversecore:multiverse-core:jar:4.3.8 in OnARandomBox (https://repo.onarandombox.com/content/groups/public/) -> [Help 1]

```
<repositories>
  <repository>
      <id>minebench-repo</id>
      <url>https://repo.minebench.de/</url>
  </repository>

  <repository>
      <id>OnARandomBox</id>
      <url>https://repo.onarandombox.com/content/groups/public/</url>
  </repository>
...
```

```    
<dependencies>
  <dependency>
      <groupId>de.themoep.idconverter</groupId>
      <artifactId>mappings</artifactId>
      <version>1.2-SNAPSHOT</version>
  </dependency>

  <dependency>
      <groupId>com.onarandombox.multiversecore</groupId> 
      <artifactId>multiverse-core</artifactId> 
      <version>4.3.8</version> 
      <scope>provided</scope>
  </dependency>
...
```

idconverter also does not resolve, however, adding their repo fixes that and it is not your issue.

**Comment by dumptruckman** [comment]
Hmm... This has worked for me. I'm not sure why it's not working for you. One notable difference is my project downloads `com.onarandombox.multiversecore:multiverse-core:all:4.3.8` rather than `com.onarandombox.multiversecore:multiverse-core:jar:4.3.8`. It's possible we have something misconfigured but I'm not really sure what that would be.

**Comment by Matthewn7** [comment]
With the dependency type set to `all`:

```
<dependency>
    <groupId>com.onarandombox.multiversecore</groupId> <!-- Don't forget to replace this -->
    <artifactId>multiverse-core</artifactId> <!-- Replace this as well -->
    <version>4.3.8</version> <!-- This too -->
    <scope>provided</scope>
    <type>all</type>
</dependency>
```

```
[ERROR] Failed to execute goal on project (redacted): Could not resolve dependencies for project (redacted): Could not find artifact com.onarandombox.multiversecore:multiverse-core:all:4.3.8 in OnARandomBox (https://repo.onarandombox.com/content/groups/public/) -> [Help 1]
```

Strange, I can get by with a system dependency for now.

Just FYI: I don't seem to be the only one https://www.spigotmc.org/threads/cant-get-multiverse-core-to-work.598814/

Thanks for the help.

**Comment by benwoo1110** [comment]
if you manually enter this URL into your web browser, what do you get?
https://repo.onarandombox.com/content/groups/public/com/onarandombox/multiversecore/multiverse-core/4.3.8/

**Comment by dumptruckman** [comment]
I recently made a change that made it possible to browse the repo. However, that doesn't change the fact that there is no plain .jar in there.

**Comment by Matthewn7** [comment]
> if you manually enter this URL into your web browser, what do you get? https://repo.onarandombox.com/content/groups/public/com/onarandombox/multiversecore/multiverse-core/4.3.8/

https://imagedelivery.net/H0ZxB-euirrsPPuyZWi9xQ/d9bc651c-85fe-49b4-9e4f-20c07d2fee00/public

I tried again with the repo, same issue:
```
[ERROR] Failed to execute goal on project (redacted): Could not resolve dependencies for project (redacted): Could not find artifact com.onarandombox.multiversecore:multiverse-core:all:4.3.8 in OnARandomBox (https://repo.onarandombox.com/content/groups/public/) -> [Help 1]
```

With Maven debug enabled:

```
[DEBUG] Using transporter WagonTransporter with priority -1.0 for https://repo.onarandombox.com/content/groups/public/
[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for https://repo.onarandombox.com/content/groups/public/
Downloading from OnARandomBox: https://repo.onarandombox.com/content/groups/public/com/onarandombox/multiversecore/multiverse-core/4.3.8/multiverse-core-4.3.8.jar
[DEBUG] Writing tracking file /Users/matt/.m2/repository/com/onarandombox/multiversecore/multiverse-core/4.3.8/multiverse-core-4.3.8.jar.lastUpdated
```

With Maven debug with the dependency type set too `all`:

```
[DEBUG] Using transporter WagonTransporter with priority -1.0 for https://repo.onarandombox.com/content/groups/public/
[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for https://repo.onarandombox.com/content/groups/public/
Downloading from OnARandomBox: https://repo.onarandombox.com/content/groups/public/com/onarandombox/multiversecore/multiverse-core/4.3.8/multiverse-core-4.3.8.all
[DEBUG] Writing tracking file /Users/matt/.m2/repository/com/onarandombox/multiversecore/multiverse-core/4.3.8/multiverse-core-4.3.8.all.lastUpdated
```

Happy to share full POM via Discord (Matt#5727) or email (matt@matthogan.co.uk) if that helps.

Thanks.

**Comment by Matthewn7** [comment]
Using a classifier seems to resolve the issue:

```
<dependency>
    <groupId>com.onarandombox.multiversecore</groupId> <!-- Don't forget to replace this -->
    <artifactId>multiverse-core</artifactId> <!-- Replace this as well -->
    <version>4.3.8</version> <!-- This too -->
    <scope>provided</scope>
    <classifier>all</classifier>
</dependency>
```

```
Downloading from OnARandomBox: https://repo.onarandombox.com/content/groups/public/com/onarandombox/multiversecore/multiverse-core/4.3.8/multiverse-core-4.3.8-all.jar
Downloaded from OnARandomBox: https://repo.onarandombox.com/content/groups/public/com/onarandombox/multiversecore/multiverse-core/4.3.8/multiverse-core-4.3.8-all.jar (527 kB at 559 kB/s)
[DEBUG] Writing tracking file /Users/matt/.m2/repository/com/onarandombox/multiversecore/multiverse-core/4.3.8/_remote.repositories
[DEBUG] Writing tracking file /Users/matt/.m2/repository/com/onarandombox/multiversecore/multiverse-core/4.3.8/multiverse-core-4.3.8-all.jar.lastUpdated
```

The minebench-repo is still needed for idconverter

**Comment by dumptruckman** [comment]
It should now work for version 4.3.9 without the classifier.
