### ISSUE TITLE
Maven: unable to use 2.5.0 dependency

### ISSUE THREAD

**Issue by Nik9094** [Multiverse/Multiverse-Core#2910]
### `/mv version -p` output

N/A

### Server logs

N/A

### Server Version

```shell
This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
```

### Bug Description

(Using IntelliJ IDEA)
When trying to use the Maven dependency for MV-Core 2.5.0, I get [this](https://pastebin.com/YVGNwMbJ) error message on the Build window.

Things I've tried:
- Changing versions from 2.5.0 to 2.5.0-SNAPSHOT and 2.5
- Changing ArtifactId
- Adding an org.bukkit exclusion as per [this](https://www.spigotmc.org/goto/post?id=2243477#post-2243477) post

What actually works:
- Manually adding the .jar file (Multiverse-Core-2.5.0.jar)

However, this way, I have to rebuild the project and then mvn install every time. I wouldn't want to keep doing this for future projects.

Here's what I put in my pom.xml:

```xml
   <repositories>
   <!-- paper and sonatype repos -->
        <repository>
            <id>OnARandomBox</id>
            <url>https://repo.onarandombox.com/content/groups/public</url>
        </repository>
    </repositories>
```
```xml
    <dependencies>
    <!-- paper dependency -->
        <dependency>
            <groupId>com.onarandombox.multiversecore</groupId>
            <artifactId>Multiverse-Core</artifactId>
            <version>2.5.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
```

### Steps to reproduce

- Create a new IntelliJ Project using the Minecraft plugin. Select 1.12.2 paper - use Maven (or open an appropriate one)
- Add the repository and dependency as reported above
- Reload all Maven projects / download dependencies
-  Error appears

### Agreements

- [x] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by Nik9094** [comment]
Bump, anyone bothers?

**Comment by benwoo1110** [comment]
We dont support older versions. Essentially some of the older dependencies repo links we use is HTTP and not HTTPS. In the latest maven versions, they block HTTP connections due to security risks. So either see if there is a flag to bypass it, or use an older version of maven.

Perhaps this will help https://gist.github.com/vegaasen/1d545aafeda867fcb48ae3f6cd8fd7c7

**Comment by zax71** [comment]
Stale issue
