### ISSUE TITLE
Close and open worlds

### ISSUE THREAD

**Issue by FewerElk** [Multiverse/Multiverse-Core#2912]
### Describe the feature

A feature where an admin can « close a world », and only people with admin perm can go with a command in this world. Then they can open this world like that every people can go to this world
(
/mv open world
/mv close world
/mvtp -bypassesecurity world
)

### How is the feature useful to all Multiverse users?

For maintenances people in builds server for example, or servers with mini games….

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by dumptruckman** [comment]
This can be already be accomplished using permissions. As such, it does not feel like it would be worth our time to implement this feature directly.

**Comment by FewerElk** [comment]
Which perm ?
I saw a line "blacklist" but I don't know how it work and what is its utilities...

**Comment by dumptruckman** [comment]
https://github.com/Multiverse/Multiverse-Core/wiki/Big-List-O%27-Permissions#access-permissions
