### ISSUE TITLE
Dont now how to teleport to [worldname]

### ISSUE THREAD

**Issue by Rodney257oke** [Multiverse/Multiverse-Core#2914]
### `/mv version -p` output  [buge]

19.0

### Server logs

Nope

### Server Version

```shell
1.19
```

### Bug Description

I wanna teleport to my other world with /mvtp [worldname] its says Multiverse dont no how to telepoort you to [worldname] pls help me

### Steps to reproduce

1: I come in my server
2: i typ in the chat /mvtp [worldname] i type than KitPVP
3 it says multiverse dont now to telepoort 

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by Rodney257oke** [comment]
Pls someone help me

**Comment by zax71** [comment]
Firstly, asking pleas someone can help really doesn't help. If you want quick support go to Discord and don't beg like that.

To answer your question, you probably need to import the world. If not then can you send the `/mvv -p` link
