### ISSUE TITLE
[Idea]: add holograms that says how much players there are in a specific world

### ISSUE THREAD

**Issue by FewerElk** [Multiverse/Multiverse-Core#2917]
### Describe the feature

I hope that MultiVerse can implement the following idea :
a new comman (/mv holo <world>) that create an hologram that show how many players are in the specified world (for example, "23 players in this world" or somethings like it that can be configurable in config.yml.).
Thank you for read it and think about it.

### How is the feature useful to all Multiverse users?

Players and admin can see very quikly how much players there are in the world, that is useful when there are a max players per world, and for the servers that have minigames in a specific world. Like that users can see how many players are playing at this game.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by zax71** [comment]
Can be solved with [MV Placeholders](https://github.com/Multiverse/Multiverse-Core/wiki/Placeholders), [PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/) and a holograms plugin (I like [DecentHolograms](https://www.spigotmc.org/resources/decentholograms-1-8-1-19-4-papi-support-no-dependencies.96927/) myself)
