### ISSUE TITLE
Gamemode in world

### ISSUE THREAD

**Issue by GinoCarino** [Multiverse/Multiverse-Core#2920]
### `/mv version -p` output

https://paste.gg/0eb5d85fc0e748df8c1747980e9ff7cf

### Server logs

https://mclo.gs/bW20fuY

### Server Version

```shell
Paper 1.19.3
```

### Bug Description

Idk if it's a bug, but I've set gamemode survival for one world, but when I join this world my gamemode is adventure.

### Steps to reproduce

.

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment]
Was your gamemode Adventure before joining the world?

Are you op, if not then do you have `mv.bypass.gamemode.*`?
