### ISSUE TITLE
[Bug]: Crash System Fail Plugin Not Loading

### ISSUE THREAD

**Issue by Grizzlybln** [Multiverse/Multiverse-Core#2922]
### `/mv version -p` output

https://paste.gg/e62d60a086af4aa78fb0725be50ae016

### Server logs

https://paste.gg/p/Anonymous/131e8d20faed48cab5e4cdd808448f91

### Server Version

```shell
Craftbukkit Version 3766-Spigot-81b9def-a345bb9 (MC: 1.20) (IMPLEMENTING API Version 1.20-R0.1-SNAPSHOT)
```

### Bug Description

I'm in a world , i'm using "/mv tp worldname"

Plugin answer:
[MV] Plugin Can't Take You Go To The World

Or 
Can't Find Player Name

### Steps to reproduce

1. Stay in a Server world
2. Use /mv tp worldname
3. Plugin Said Can't Took You In ....
4. Plugin Will Crash or Not Work restart The Server try IT again.

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [x] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by NeverGrowUp** [comment]
No server logs..

**Comment by Grizzlybln** [comment]
The Server Log is added a netter Log can i Not added

**Comment by NeverGrowUp** [comment]
Your logs aren't visible. Try using https://mclo.gs/

**Comment by Grizzlybln** [comment]
Latest https://mclo.gs/lk9yrZx

**Comment by NeverGrowUp** [comment]
None of those logs show you trying to mvtp anywhere.
But I do note that several other plugins don't like 1.20 (as expected)

**Comment by Grizzlybln** [comment]
It doesnt work... You have logs

**Comment by NeverGrowUp** [comment]
As mentioned, the 3 logs you provided show no indication of multiverse failing. 
As mentioned, provide logs which show multiverse having an issue.

**Comment by Grizzlybln** [comment]
I can give you access to my server to join and to use the command to see the problem the issue logs have you already

**Comment by Grizzlybln** [comment]
Hello ,

Now i will send it that you can fix it

I'm Bedrock Player (Pocket-Edition)
we using geyserMC 

Now i'm typing 
"/mv tp Grizzlybln CB1"


But Server Said
"Multiverse Does Not Know How To Take You In CB1"

**Comment by NeverGrowUp** [comment]
Still no logs. 🙄

**Comment by Grizzlybln** [comment]
Yes No logs i Can't send logs... How often Said It ?

**Comment by NeverGrowUp** [comment]
To continue with your support we need your server logs. These can be found in /logs/latest.log or if we ask for an old log they are in a .log.gz format that has to be extracted.

After you open that file you will see lots of text, copy and paste that with CTRL+C and CTRL+V it in https://mclo.gs/ , just click save and send the link to the page it sends you to and we can continue with support!

**Comment by benwoo1110** [comment]
From the logs, the error is caused by plotsquared, which caused MV to be unable to load worlds that use plotsquared generator.
