### ISSUE TITLE
[Bug]: Natural healing doesn`t work in Nether and End

### ISSUE THREAD

**Issue by Limonchelloq** [Multiverse/Multiverse-Core#2924]
### `/mv version -p` output

https://paste.gg/8095036bb45e41c180b5f5e8a6fa1368

### Server logs

https://paste.gg/p/anonymous/9dfa9eaece0b48b3b663f5eff121b57d

### Server Version

```shell
14.06 19:51:06 [Server] INFO Checking version, please wait...
14.06 19:51:06 [Server] INFO Current: git-Purpur-1985 (MC: 1.19.4)*
14.06 19:51:06 [Server] INFO Previous: git-Purpur-1933 (MC: 1.19.3)
14.06 19:51:06 [Server] INFO * You are running the latest version
```

### Bug Description

When player in world_nether or world_end - healing doesn`t work even when hunger is full. HP bar just stays the same

### Steps to reproduce

Everytime when server is up and somebody enters world_nether or world_end

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [ ] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by castozen** [comment]
Hi. I'm having the same issue with one of my worlds. Did you ever figure this out?
