### ISSUE TITLE
add a way to convert .dat playerdata  into .json playerdata

### ISSUE THREAD

**Issue by nicogb2007** [Multiverse/Multiverse-Core#2926]
### Describe the feature

add a something to convert minecraft base playerdata into multiverse playerdata.

### How is the feature useful to all Multiverse users?

it will be usefull to transfer worlds form vanilla minecraft to multiverse worlds

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by zax71** [comment]
Although useful, this is a tad out of scope for MVINV. PRs welcome though!
