### ISSUE TITLE
[Idea]: A Biomes O'Plenty option

### ISSUE THREAD

**Issue by joni7878** [Multiverse/Multiverse-Core#2935]
### Describe the feature

Hi, is a modpack creator that wants to make a Minecraft server I can't use this plugin in the server.
as a modpack server, I want to use plugins too and I can make it throw (Magma server),

my modpack run over a Biomes O'Plenty mod and I can't make a world with it,
soo if you can add an option to make a Biomes O'Plenty Biome.

Tnx for reading this
joni.

### How is the feature useful to all Multiverse users?

It will make more options for a mods+bukkit servers. 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by NeverGrowUp** [comment]
Multiverse doesn't support modded servers. But there are plugins that are similar to biomes O plenty. 
Check out iris plugin or Terra plugin.
