### ISSUE TITLE
[Bug]: every player gets spawned inside of a portal covered in barrier blocks when leaveing the nether.

### ISSUE THREAD

**Issue by MangoOffical** [Multiverse/Multiverse-Core#2936]
### `/mv version -p` output

https://paste.gg/p/anonymous/dc1768ea9d8041dabf8d1c515bb435d9

### Server logs

there is none

### Server Version

```shell
https://papermc.io/downloads/paper
```

### Bug Description

the expected behavior is to bring the players to the over world but instead it traps them

### Steps to reproduce

1.start a server
2. enter nether then leave
3. get stuck. 

### Agreements

- [x] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by Lildirt** [comment]
Well, MV certainly doesn't have any code to place barrier blocks anywhere.
There's not a lot to go on here. Need some better evidence to say anything.

**Comment by benwoo1110** [comment]
Too little info to work with, and no server logs or visual evidence to suggest any related to MV.
