### ISSUE TITLE
[Bug]: Error importing flat with void preset new created world

### ISSUE THREAD

**Issue by vovchukegor** [Multiverse/Multiverse-Core#2938]
### `/mv version -p` output

https://paste.gg/p/anonymous/c490e1b7d340453aa311f2cf595fd1f2

### Server logs

https://gist.github.com/vovchukegor/34400ab2a580b55d177f3c12f370704c

### Server Version

```shell
1.19.4
```

### Bug Description

I needed to import void world, but plugin gave me an error and I tried to use regionfixer, but it says that world hasn't got any problems

Welcome to Region Fixer!
(v 0.3.6)

############################################################
############################################################

World info:
 - 4 region/level files,
 - 0 POI files,
 - 4 entities files,
 - 1 player files,
 - and 1 data files.

-------------------- Checking level.dat --------------------
'level.dat' is readable

---------------- Scanning UUID player files ----------------
0 of 1|                                                         |ETA:  --:--1 of 1|##########################################################|ETA:  0:001 of 1|##########################################################|Time: 0:00:00

------------- Scanning old format player files -------------
Info: No files to scan.

---------- Scanning structures and map data files ----------
0 of 1|                                                         |ETA:  --:--1 of 1|##########################################################|ETA:  0:001 of 1|##########################################################|Time: 0:00:00

--------- Scanning region, POI and entities files ----------
0 of 8|                                                         |ETA:  --:--1 of 8|#######                                                   |ETA:  0:002 of 8|##############                                            |ETA:  0:003 of 8|#####################                                     |ETA:  0:004 of 8|#############################                             |ETA:  0:005 of 8|####################################                      |ETA:  0:006 of 8|###########################################               |ETA:  0:007 of 8|##################################################        |ETA:  0:008 of 8|##########################################################|ETA:  0:008 of 8|##########################################################|Time: 0:00:01

############################################################
############################################################

Unreadable player files:
No problems found.

Unreadable data files:
No problems found.

Chunk problems:
No problems found.

Region problems:
No problems found.

No chunks to delete with status: Corrupted

### Steps to reproduce

mv import [flat world with the minecraft void preset] normal

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by NeverGrowUp** [comment]
`java.nio.file.AccessDeniedException: ./dim2/paper-world.yml`

Your server can't write to that location. Check security/permissions.
