### ISSUE TITLE
[Idea]: support folia

### ISSUE THREAD

**Issue by xyfwdy** [Multiverse/Multiverse-Core#2940]
### Describe the feature

https://github.com/PaperMC/Folia

### How is the feature useful to all Multiverse users?

Folia is a great project, he solved many problems

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by NeverGrowUp** [comment]
You ticked the box agreeing that you 

> searched for and ensured there isn't already an open issue regarding this.

Didnt see this? https://github.com/Multiverse/Multiverse-Core/issues/2901
