### ISSUE TITLE
[Bug]: When create world, server down

### ISSUE THREAD

**Issue by MuYuehe** [Multiverse/Multiverse-Core#2941]
### `/mv version -p` output

https://paste.gg/396dd5ca9eaa43e0aa38c72728f7563c

### Server logs

https://gist.github.com/MuYuehe/7942d63ceefda4b6991544d47d26ebf7

### Server Version

```shell
This server is running CraftBukkit version 3822-Spigot-9ebce8a-b60a95c (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)
```

### Bug Description

When running `/mv create` it cause the server to crash...

### Steps to reproduce

1. start server only multiverse-core
2. /mv create create NORMAL
3. server down

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment]
What are your server specs? Seems like doesn't have enough computing power to run your server.
