### ISSUE TITLE
[Bug]: Hardcore Mode Not Working

### ISSUE THREAD

**Issue by gabessdsp** [Multiverse/Multiverse-Core#2942]
### `/mv version -p` output

https://paste.gg/p/anonymous/d3dc70e95c034dd7a4bc192c21133b4e

### Server logs

N/A

### Server Version

```shell
git-paper-c793bd9 MC 1.20.1
```

### Bug Description

I knew I couldn't generate a hardcore world with MV. So I generated some new world, and modified the level.dat files with NBTExplorer to set hardcore = 1. This would normally work without MultiVerse but apparently it still does not work. I am not sure how/why the level.dat settings are being blatantly ignored.

### Steps to reproduce

Create a new world
Modify the level.dat to set hardcore = 1 to enable hardcore mode.

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by NeverGrowUp** [comment]
You can use the command `/mvm set mode hard <worldname>` to make a world hard mode. No need to mess with level.dat

**Comment by zax71** [comment]
Multiverse does not support hardcore mode, this would need to be done with a death ban plugin

**Comment by gabessdsp** [comment]
@zax71 Is it not possible to support it? Just wondering why close it instead of creating a feature request or something for the future of MV.

**Comment by zax71** [comment]
If you’d like to make a feature request then feel free. As a dev team we are mainly focussed on MV5 currently so this wouldn’t be added quickly
