### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Malek1324** [Multiverse/Multiverse-Core#2966]
### `/mv version -p` output

https://paste.gg/8c74af1128764c3e8e940a210d6acb7e

### Server logs

 [01:33:55 INFO]: FAILED.  [01:33:55 INFO]: 'spawn' does not appear to be a world. It is lacking a .dat file

### Server Version

```shell
This server is running Paper version git-Paper-36 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: faf9a65)

You are 122 version(s) behind
```

### Bug Description

 [01:33:55 INFO]: FAILED.  [01:33:55 INFO]: 'spawn' does not appear to be a world. It is lacking a .dat file

Hello Iam trying to import a world but it tolds me lacking a  .dat file i tried pn different worlds and its the same error

### Steps to reproduce

 [01:33:55 INFO]: FAILED.  [01:33:55 INFO]: 'spawn' does not appear to be a world. It is lacking a .dat file

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by NeverGrowUp** [comment]
Proper logs would help. Assume it's missing the `level.dat` file.
Where did you get the world from? Is it an overworld, nether or end?
