### ISSUE TITLE
[Bug]: A event is deprecated on Multiverse core 

### ISSUE THREAD

**Issue by richardGonzalez-std** [Multiverse/Multiverse-Core#2976]
### `/mv version -p` output

https://paste.gg/5ced27c16e264916a6b9d343b6f33b76

### Server logs

https://paste.gg/p/anonymous/59d00351bbd34718a2210c7cd5169aac

### Server Version

```shell
git-Paper-160 (MC: 1.20.1)
```

### Bug Description

the console shows me a deprecated event what it causes a lag of 100 ticks behind
[Multiverse-Core]: "Multiverse-Core v4.3.11" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].
INFO15:18:49
[Multiverse-Core]: §aWe are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.

### Steps to reproduce

1. Start server with Multiverse installed

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by ljacqu** [comment]
In your bug description:

> We are aware of the warning about the deprecated event. There is no alternative that allows us to do what we need to do and performance impact is negligible. It is safe to ignore.

in your agreement, this is checked:

> I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.

See #2000
