### ISSUE TITLE
[Bug]: Settings stays the same even after changing them

### ISSUE THREAD

**Issue by MrRagtime** [Multiverse/Multiverse-Core#3005]
### `/mv version -p` output

https://paste.gg/p/anonymous/606203594924413c909db2ce37b48fce

### Server logs

https://paste.gg/p/anonymous/3faba0479ff04ec5a6263eaacc3900fa

### Server Version

```shell
Server is running Leaves version git-Leaves-"10e2199" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 10e2199)
```

### Bug Description

Changing the settings for Multiverse does not change when I restart the server
Ex: autoload 'true'  >  'false'  doesn't do anything and in the config for MV it is still set to 'true'

### Steps to reproduce

1 Start Server
2 Change a setting in the MV World Config
3 Restart Server
4 Check MV Config
5 Still the same

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment]
This is known behaviour, you need to change config values while the server is off
