### ISSUE TITLE
[Docs]: Missing `-n` flag explanation for `/mv create`

### ISSUE THREAD

**Issue by nopeless** [Multiverse/Multiverse-Core#3009]
### Describe the feature

https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#create-command

```text
> mv help create
====[ Multiverse Help ]====
Add a '?' after a command to see more about it.
/mv create {NAME} {ENV} -s [SEED] -g [GENERATOR[:ID]] -t [WORLDTYPE] [-n] -a [true|false]
/mv anchor {name} [-d]
```

`-n` is not explained in the wiki link

I am willing to contribute to the wiki

### How is the feature useful to all Multiverse users?

Would be nice to have a documentation of this option, as its probably a feature

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by zax71** [comment]
Unlikely to be fixed as MV5 is in heavy development and the docs will need to be rewritten for that update
