### ISSUE TITLE
[Support]: Importing issues

### ISSUE THREAD

**Issue by UltimateDevSaksham** [Multiverse/Multiverse-Core#3021]
### `/mv version -p` output

Multiverse-Core Version: 4.3.1-b861, the link: https://paste.gg/5d9c1d95f60045b5bfb84d8c46a69603

### Server logs

https://paste.gg/5d9c1d95f60045b5bfb84d8c46a69603

### Server Version

```shell
1.20.1
```

### Bug Description

I used `/mv import Havenbrook NORMAL`

I am loading a city map using the `/mv import` command, first if a user is in the server, it gets disconnected with a message "Timed Out". So I tried from console without any user in the server. Then it imports the world but when I use `/mvtp {WORLD_NAME}` so there is a simple world not the city map... When I try to delete, it says "Are you sure that {WORLDNAME} directory exists?" How should I fix these all?

### Steps to reproduce

Steps to reproduce....

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by UltimateDevSaksham** [comment]
Actually those who are confused. The main issue, is the world I am importing, is not being registered on Multiverse Core. Rather a normal minecraft world is coming when I teleport to the world. My map is of city. The world gets imported successfully without any error from console. But when I teleport to the world, the world is a simple minecraft world....

**Comment by Chris6ix** [comment]
Holy sh*t this guy put basically the entire issue into the title, and only a single line under description.
Never seen something like that before lmao

**Comment by zax71** [comment]
Could you upload the server logs (to https://mclo.gs) as well for debug purposes? Please post the generated link in here.
