### ISSUE TITLE
[Bug]: enforceaccess resets to 'false'

### ISSUE THREAD

**Issue by mczero80** [Multiverse/Multiverse-Core#3037]
### `/mv version -p` output

https://pastebin.com/hqcmvzDp

### Server logs

https://gist.github.com/mczero80/f37f26fbe195f961c166600509cded20

### Server Version

```shell
This server is running CraftBukkit version
3836-Spigot-3374045-08ec344 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)
Checking version, plrease wait...
You are 32 version(s) behind
```

### Bug Description

When trying to activate permissions by setting **enforceaccess: 'false'** to **enforceaccess: 'true'**, it resets to **enforceaccess: 'false'** after restarting the server.

LuckPerms is installed. No permissions where set prior, and LuckPerms was installed just now.

### Steps to reproduce

1. Editing config.yml
2. Setting enforceaccess: 'false' to enforceaccess: 'true'
3. Restarting the server
4. Taking a look at config.yml

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment]
This is standard behaviour. If the server is still running then you must turn it off, change the config value and start it again.

**Comment by mczero80** [comment]
Ahh that makes sense. Thanks!
