### ISSUE TITLE
How to disable plugins 

### ISSUE THREAD

**Issue by Davidx01** [Multiverse/Multiverse-Core#3038]
### `/mv version -p` output

2.5b699

### Server logs

Nothing

### Server Version

```shell
1.8.8
```

### Bug Description

I have one vanilla world and one world server, how can I disable bedwars plugin in vanilla world?

### Steps to reproduce

Nothing

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment]
You can change the permissions per world using LuckPerms or look in your plugin's config to see if it has the option. If you have any further questions then ask your bedwars plugin directly or in the [LuckPerms Discord](https://discord.gg/luckperms) respectively.

**Comment by Davidx01** [comment]
How can I use luck perms for disabling plugins?

Il lun 9 ott 2023, 19:33 Zax71 ***@***.***> ha scritto:

**Comment by zax71** [comment]
You can use per world permissions using contexts. Please continue this on the LuckPerms Discord server or GitHub.
