### ISSUE TITLE
[Idea]: Can we Get Multiverse Objective Global

### ISSUE THREAD

**Issue by matinomp69** [Multiverse/Multiverse-Core#3040]
### Describe the feature

I am Creating server That Has Datapack In it in The Survival World And Has Objective I want To show The Objective In A Hologram And the Hologram is in the Another World Yeah...
It Cannot Be showed Because The Datapack is Not In The In The World That I Want To Show In Hologram
And I Know How To Show Objective In Hologram

### How is the feature useful to all Multiverse users?

You Know It =/

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by zax71** [comment]
Multiverse will not do anything with Datapacks.
