### ISSUE TITLE
[Bug]: bedrespawn??

### ISSUE THREAD

**Issue by nogame1** [Multiverse/Multiverse-Core#3045]
### `/mv version -p` output

https://paste.gg/p/anonymous/75fdfc95844e4506b677cf1da5b5f66b

### Server logs

https://paste.gg/p/anonymous/93d4e8dafbc942849303b8358b8c3d73

### Server Version

```shell
git-paper-241 (MC: 1.20.2)
```

### Bug Description

When someone sets point using a bed, if that person dies that person will respawn in the lobby, not on the bed (Even though bedrespawn is true)

### Steps to reproduce

1. Someone sets point using the bed
2. When the person dies, they do not respawn in bed

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by NeverGrowUp** [comment]
You have `respawnworld` set to `lobby` for all your worlds. So thats where you will go. 
You can change with `/mvm set respawnworld <worldtorespawnin> <deathworldname>`
eg `/mvm set respawnworld world_nether world`

**Comment by zax71** [comment]
This seems like it is solved, if you have more queries then please open a new issue
