### ISSUE TITLE
[Bug]:Virus detected

### ISSUE THREAD

**Issue by SonnenPingu** [Multiverse/Multiverse-Core#3048]
### `/mv version -p` output

-

### Server logs

-

### Server Version

```shell
1.20.2
```

### Bug Description

https://www.virustotal.com/gui/file/98237aaf35c6ee7bfd95fb7f399ef703b3e72bff8eab488a904aad9d4530cd10/detection

### Steps to reproduce

Download the Jar.

Start a virus scan and it will be flagged.

See Virus Total

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment]
![image](https://github.com/Multiverse/Multiverse-Core/assets/67716263/9b349dff-7591-4239-9521-97d43fabcb79)
A few do detect it

**Comment by benwoo1110** [comment]
It's just the nature of .jar files. If you put any minecraft plugin into virus total, some over-sensitive AV engines will generate such false positive. Nothing we can do and it's safe to ignore.
