### ISSUE TITLE
[Bug]: Very long chunk loading times when logging in after a server starts up with paper anti xray engine mode 3

### ISSUE THREAD

**Issue by partydev** [Multiverse/Multiverse-Core#3051]
### `/mv version -p` output

https://paste.gg/p/anonymous/78bec465cf194470b3bc0c31fc357bc5

### Server logs

https://gist.github.com/partydev/87222f020f8223fa3bdf89fd6eb3de59

### Server Version

```shell
This server is running Paper version git-Paper-"905f4e7" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 905f4e7)
Error obtaining version information
Previous version: git-Paper-"07b956e" (MC: 1.20.4)

Fork of paper up to date with this patch.
https://github.com/PaperMC/Paper/commit/76da4bc683a51057eadfabc6e6694486a20a0d20
```

### Bug Description

When a server starts up for the first time and has engine mode 3 enabled in paper config, it can take up to or more than 30 seconds for a player to finish loading terrain and see the chunks around them.

### Steps to reproduce

1. Download Paper.
2. Set anti xray engine mode to 3 following their recommended config.
3. Download Multiverse Core.
4. Start the server.
5. Attempt to connect.

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by NeverGrowUp** [comment]
You have 24 world's... I assume you have decent server specs. I note you spawn in world `spawn` but have set keepspawninmemory set to false. Change this to true.
I assume you removed Terra and VoidGen to rule out those as potential issues.
There are no errors from multiverse, and no mention of chunks loading, so can only assume between your PC specs and your server specs, is where the issue lies.

**Comment by partydev** [comment]
> You have 24 world's... I assume you have decent server specs. I note you spawn in world `spawn` but have set keepspawninmemory set to false. Change this to true. I assume you removed Terra and VoidGen to rule out those as potential issues. There are no errors from multiverse, and no mention of chunks loading, so can only assume between your PC specs and your server specs, is where the issue lies.

This issue does not happen when Multiverse is disabled. This issue only happens when both Multiverse and Paper Antixray are enabled as mentioned above.

Server is a dedicated OVH server with 10GB of RAM allocated with a 5600x with 250mbps up bandwidth. Spark profiler shows there is no issue there.

PC is 7900x 64GB memory on a 3070. Specs are not the issue. I will not be turning on keep spawn chunks in memory because it is unnecessary chunk loading and has zero impact on resolving this issue as the issue disappears when Multiverse is disabled even though spawn chunks in memory is set to false.

Yes, as seen in the log file provided Multiverse is the only plugin enabled.

**Comment by partydev** [comment]
Confirmed that with fewer (5) worlds loaded the issue goes away. However, I would expect to be able to load more worlds as the issue does not happen when paper anti-xray is disabled.

**Comment by benwoo1110** [comment]
Its just a matter of paper anti-xray needing to process to many chunks from too many worlds. 24 worlds is crazy for a single server. At that point you should consider multiple servers with velocity/bungeecord proxy.
