### ISSUE TITLE
[Bug]: Buscript fails to load when world-container is modified

### ISSUE THREAD

**Issue by IvanMishin1** [Multiverse/Multiverse-Core#3053]
### `/mv version -p` output

https://paste.gg/p/anonymous/521ec08fc96e476581ac2c349eeee9bc

### Server logs

https://paste.gg/p/anonymous/4a7131cdd0524532bb0c3ca971ad0648

### Server Version

```shell
[19:04:08 INFO]: Current: git-Purpur-2149 (MC: 1.20.4)*
Previous: git-Purpur-2143 (MC: 1.20.4)
* You are running the latest version
```

### Bug Description

Buscript fails to load if the world container is anything but the server's root directory.

The beggining of my bukkit.yml:
`settings: world-container: worlds`

My world container structure:
![image](https://github.com/Multiverse/Multiverse-Core/assets/88932074/069084ad-7570-4f23-a537-ca8ef8aea249)

### Steps to reproduce

1. Add `settings: world-container: worlds`  to bukkit.yml
2. Relocate worlds to that container 
3. Start the server (with Multiverse-Core enabled)

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [x] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment]
I know it sounds silly… can you confirm that you actually *want* to use buscript. It’s quite old now and will most likely be removed soon. You can disable the warning in config if that is what you need
