### ISSUE TITLE
[Idea]: summon command to a precise location

### ISSUE THREAD

**Issue by LPTEole** [Multiverse/Multiverse-Core#3054]
### Describe the feature

Hello,

I comes for an issue in my server :
I'm creating an RPG server, but, when I write the command "/summon ...", in the quest plugin (Beauty-Quest), the mob is created in "vanilla" world.

My request is so : have you got a command to spawn a creature in precise location, I have found the command for players, but not for mobs.

To precise, I'm in 1.16.5, and I used this commad :
summon minecraft:zombie_villager 3709.473 51 1939.402 {IsBaby:1b,profession:"morevillagers:hunter",CustomName:"{\"text\":\"Pumpking Creature\",\"color\":\"gold\"}",ArmorItems:[{},{},{},{id:"minecraft:pumpkin",Count:1}]} 

Thanks in advance for response.

### How is the feature useful to all Multiverse users?

Can help to avoid issue like I wrote ^^'

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by zax71** [comment]
Doesn’t feel like it’s in scope imo, I’ll discuss with the other devs before I close this though.
