### ISSUE TITLE
[Idea]: Spawning not at spawnpoint when joining a world

### ISSUE THREAD

**Issue by fynnob** [Multiverse/Multiverse-Core#3060]
### Describe the feature

Hi I don't know if this is already a thing but if I leave my survival world and join back in I always spawn at the spawnpoint and not where I left off.

### How is the feature useful to all Multiverse users?

This would be helpful for people who made a survival server

### Agreements

- [ ] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by zax71** [comment]
This is achievable using MV Inventories [LastLocation](https://github.com/Multiverse/Multiverse-Core/wiki/Shares-List-(Inventories)#optional-shares---must-be-enabled-via-mvinv-toggle-sharename-or-they-have-no-effect) or the [StayPut plugin](https://www.spigotmc.org/resources/stayput-remixed.69564/)

**Comment by fynnob** [comment]
Thanks

**Comment by fynnob** [comment]
I have a follow up question
Every time a use the /Hub it uses teleport and will not remember where I was

I used stayput

**Comment by NeverGrowUp** [comment]
`/hub` isn't a multiverse command.
