### ISSUE TITLE
[Bug]: Dimensions mixup

### ISSUE THREAD

**Issue by oskarbukovsky** [Multiverse/Multiverse-Core#3066]
### `/mv version -p` output

https://paste.gg/9aad88fba41b48a8927a07c37dae7ee6

### Server logs

https://paste.gg/p/anonymous/5161aa4362754ee6b3e5d24df1d5a7c3

### Server Version

```shell
[11:18:19 INFO]: This server is running Mohist version 1.18.2-146 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge version 40.2.17)
```

### Bug Description

When i put mv plugin to server spawn location is set to another dimension, and weird things happen to default, end, nether and other dims some of the mods add and i'm trying to find what is causing the problem here, so it might not be mv fault, but it do weird things like retyping dimensions already existing on the server from like nether to become end, multiple dimensions get same modded dimension type and when creating another custom dimension, it gets messed up too. I know i use mods (so if you promptly delete this issue is probably right) which can cause this issue, but if anyone can find a thing to look for i'll really appreciate it. 

### Steps to reproduce

Thied removing mv plugin, removing all the worlds and when i put i back it start again

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment]
Mohist isnt supported
