### ISSUE TITLE
[Bug]: Potion effects cannot be added

### ISSUE THREAD

**Issue by ZEROkvg** [Multiverse/Multiverse-Core#3071]
### `/mv version -p` output

https://paste.gg/72ded729af9a4ae7a44c5333d6e6dc94

### Server logs

no logs

### Server Version

```shell
1.21
```

### Bug Description

Potion effects cannot be added，whether it's using beacons or eating golden apples

### Steps to reproduce

1.eating golden apples
2.effects cannot be added

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment]
Can you provide more detailed reproduction instructions that are tested on a server with only Multiverse plugins installed

**Comment by Kimiblock** [comment]
I'm facing the same issue here. Paper 1.21 (Build #37), cannot be reproduced on a test server.

This server is running with no other plugin.

**Comment by Kimiblock** [comment]
```
This server is running Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-21-0a1b133 (MC: 1.21)
```

**Comment by zax71** [comment]
If you could find a way to reproduce this on a test server then I can look in to it.
