### ISSUE TITLE
[Bug]: Why do I always turn on this option when I shut down the server?

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [Multiverse/Multiverse-Core#3075]
### `/mv version -p` output

your lastest version

### Server logs

none

### Server Version

```shell
1.20.1
```

### Bug Description

It was originally false, but every time the server is closed, it becomes true, causing a lot of lag
<img width="357" alt="image" src="https://github.com/Multiverse/Multiverse-Core/assets/141799770/c90efd34-df35-4502-912c-6ede1b28ec82">

### Steps to reproduce

1.worlds.yml  
keepSpawnInMemory: 'false'
2.stop server
3.look
keepSpawnInMemory: 'true'

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by NeverGrowUp** [comment]
https://github.com/Multiverse/Multiverse-Core/issues/3072#issuecomment-2221814144

**Comment by Leoparking** [comment]
> [#3072 (comment)](https://github.com/Multiverse/Multiverse-Core/issues/3072#issuecomment-2221814144)

对于mohist服务端如何解决此问题？

**Comment by NeverGrowUp** [comment]
Multiverse doesn't support modded/hybrid servers like mohist, arclight etc..

**Comment by timriker** [comment]
Running:
Paper version 1.20.6-147-ver/1.20.6@e41d44f
Multiverse-Core v4.3.12

1. Stop server
2. change all keepSpawnInMemory to false in Multiverse-Core/worlds.yml
3. start server
4. when worlds load, worlds.yml is re-written with all keepSpawnInMemory reset to true.
5. mvm set keepspawninmemory false [world] does NOT change them back

**Comment by zax71** [comment]
Thanks for the reproduction info! I have reproduced this in 1.21 Paper successfully

**Comment by benwoo1110** [comment]
Fixed by the latest spigot/paper

**Comment by timriker** [comment]
Do you have a version, date or release number that it's fixed in? I don't see it in the changelog yet.
