### ISSUE TITLE
[Bug]: Could not pass event PlayerTeleportEvent to Multiverse-Core v4.3.12

### ISSUE THREAD

**Issue by BerndPixel** [Multiverse/Multiverse-Core#3079]
### `/mv version -p` output

https://paste.gg/p/anonymous/8ff149fd62f54269b14bf6c5ef0be4c2

### Server logs

https://paste.gg/p/anonymous/e6f7b57204b44180a8dbd3b74c850aaa

### Server Version

```shell
Checking version, please wait...
This server is running Paper version 1.21-119-master@100d75a (2024-07-29T16:00:13Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-113-f82bea6 (MC: 1.21)
```

### Bug Description

Error occurs when players teleport.

### Steps to reproduce

See Bug Description

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by NeverGrowUp** [comment]
Would need to see more of the logs, and not just a snippet. What command/method is used to change worlds? Does it happen with everyone, or just certain players? Also might be a good idea to change to Paper....https://papermc.io/software/paper

**Comment by BerndPixel** [comment]
As you can already see, I use Paper. Therefore, this is no longer necessary. In addition, only one command was entered to change the world. /mvtp <worldName>. Nothing more.

The error occurs regardless of which player enters the command.

**Comment by zax71** [comment]
We'll need more detailed reproduction instructions than that. Just using `/mvtp world_2` perfectly fine for me in 1.21 paper with only MV plugins installed. Ensure your instructions are clear and **tested**.

**Comment by Delmortis** [comment]
The PaperMC github has an open issue for this bug too (however it seems they think the plugins need to be updated):
[https://github.com/PaperMC/Paper/issues/11137](https://github.com/PaperMC/Paper/issues/11137)

I've run into the same issue myself when I have PaperMC 1.21 with both Multiverse and Worldguard.

Just PaperMC + Multiverse has no issues for me. It's when I have WorldGuard installed too that I get non-stop NPE's. PaperMC + WorldGuard and no Multiverse has no issues. As someone mentioned in the PaperMC issue, there might be some sort of issue with the combination of the three.
