### ISSUE TITLE
[Bug]: Setting "access" and "tp" permissions.

### ISSUE THREAD

**Issue by Equinoxe10** [Multiverse/Multiverse-Core#3080]
### `/mv version -p` output

4.3.12

### Server logs

https://paste.gg/p/anonymous/63295f9ead134e68bfb8387638506e73

### Server Version

```shell
Paper version 1.21-123-master@0a1be9a
```

### Bug Description

Hello!
It's not exactly a bug, but I need help to configure the plugin permissions to achieve the following:
I have 4 worlds: world, world_the_end, world_nether and barrio.
What I need to achieve and I haven't been able to, is that the players have access to all the worlds BUT CAN ONLY USE THE TELEPORT COMMAND to go to "world" or "barrio". They should be able to access the End or the Nether through portals, but not through the /mv tp command.

I'm very grateful for anyone who can help me!

### Steps to reproduce

It's not exactly a bug, but I can't find the right combination of permissions to achieve the configuration I want.

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment]
The `/mvtp` command is not designed to be used by players, only by admins. Hence, I suggest using a custom command plugin (like [MyCommand](https://www.spigotmc.org/resources/mycommand.22272/)) and running it as console with [PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/). I.e: `/mvtp %player_name% barrio` or `/mvtp %player_name% world` aliased to `/world` or `/barrio`. The access permissions are not designed for a situation like this.
