### ISSUE TITLE
[Bug]: Building Latest source 1.21.x , Fails

### ISSUE THREAD

**Issue by Tsoccerguy3** [Multiverse/Multiverse-Core#3086]
### `/mv version -p` output

Build failed

### Server logs

build failed

### Server Version

```shell
D:\Dev>cd multiv

D:\Dev\multiv>git pull
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 2 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (2/2), 1.26 KiB | 323.00 KiB/s, done.
From https://github.com/Multiverse/Multiverse-Core
   2cf8b696..2d059eab  main         -> origin/main
 * [new tag]           4.3.13-pre.2 -> 4.3.13-pre.2
Updating 2cf8b696..2d059eab
Fast-forward
 .../com/onarandombox/MultiverseCore/listeners/MVPlayerListener.java  | 5 +++++
 1 file changed, 5 insertions(+)

D:\Dev\multiv>gradlew build
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not open cp_settings generic class cache for settings file 'D:\Dev\multiv\settings.gradle' (C:\Users\socce\.gradle\caches\7.6\scripts\a1qxzrlbjut6www0ivxf7nogo).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
```

### Bug Description

Building compile fails

### Steps to reproduce

gradlew build , in console Git for Windows , I don't think it can use JDK 21

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment]
Try building in IntelliJ. We use Java 17 internally

if you just want a 1.21 version then the ones on Modrinth are tested to work on there

**Comment by Remodactyl** [comment]
I just succeeded in building multiverse on its latest commit, had to download Java JDK 19 since later versions are not supported by the version of gradle on the project, but I can confirm it works fine beyond that!

**Comment by zax71** [comment]
Ahah, maybe another issue regarding updating Gradle would be more accurate then. It would be nice to prepare to support newer Java versions

**Comment by Remodactyl** [comment]
Intellij pops up with a little warning down the bottom-right to indicate the current Java JDK is not valid with the gradle version at least, but it will definitely be worth updating down the line.

**Comment by benwoo1110** [comment]
The current gradle targets Java 17 iirc

**Comment by Tsoccerguy3** [comment]
Yes I built with JDK 17 just now. I saw you updated to 1.21.x so I tried to build with JDK 21. I saw the target in the build.gradle was JDK 17 . I will close as no issue
