### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AdhityaXD1604** [Multiverse/Multiverse-Core#3100]
### `/mv version -p` output

Multiverse-Core v4.3.13-SNAPSHOT

### Server logs

https://paste.gg/p/anonymous/9d7a5b65f3e242de85e35b7bcf19d5a0

### Server Version

```shell
LightingLuminol version git-Luminol-"5dc57c8" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 5dc57c8 on ver/1.20.4)
```

### Bug Description

i cant running multiversecore

### Steps to reproduce

1. i put multiversecore
2. start server
3. error

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by zax71** [comment]
Can you please send your **full** server logs on https://mclo.gs

<details>
    <summary>How do I do that?</summary>

    1. Copy the file in `/logs/latest.log`
    2. Copy the contents of that file with `Ctrl`+`A` then `Ctrl`+`C`
    3. Paste that in the large text box on https://mclo.gs with `Ctrl`+`V`
    4. Press save
    5. Copy the address of the website that it redirects you to
    6. Paste that here so that we can see it!


</details>

**Comment by AdhityaXD1604** [comment]
https://mclo.gs/h2CKU2B its affect to my custom plugin too

**Comment by zax71** [comment]
We do not support offline mode servers.
