### ISSUE TITLE
[Bug]: vanilla /spawnpoint command doesn't work (being overriden by multiverse worldspawn)

### ISSUE THREAD

**Issue by Study-Grind-Developers** [Multiverse/Multiverse-Core#3112]
### `/mv version -p` output

https://paste.gg/3401c6021b264336a757c08e569e01de

### Server logs

https://gist.github.com/Study-Grind-Developers/b52bcf83a4c7d96a6b054d281e7bdd7c

### Server Version

```shell
Current Purpur Version: 1.21.1-2308-8332fa4 (MC: 1.21.1)*
* You are 13 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.21-2283-75e81d8 (MC: 1.21)
```

### Bug Description

Whenever I use a vanilla /spawnpoint, it flat out does not work, in any world. even if its in the most safe location, just on normal terrain, when I die I will always respawn at the world spawn, /mvss. The /mvss overrides all other spawns except beds. Beds DO work as respawn points (so beds are not an issue), but vanilla commands like /spawnpoint do not work. (and yes i also tried putting /minecraft:spawnpoint and it flat out doesn't work). This has been a big issue for a long time on my server, and it's getting very annoying now. It is definitely multiverse causing the issue because removing mv makes it work, and running the server with only mv causes this issue again.

No errors come, it says I set my spawnpoint to whatever coordinates, but when I die i respawn back at the /mvss spot. I am very sure this is not exactly a BUG, just the behaviour of the plugin and the developers never thought about /spawnpoint. However, I personally use a lot of vanilla commands and datapacks and I use /spawnpoint for my minigames, it is an important command. Thank you! (and no i dont want to use a plugin spawnpoint i want the vanilla version)

Expected behaviour: Upon dying, I respawn at the specified coordinates of my /spawnpoint command
Actual behaviour: Upon dying, I respawn at the world spawn set by /mvss (not /setworldspawn)

### Steps to reproduce

1. Start a server with only Multiverse installed
2. go to any location, and do /spawnpoint (and enter in coords and other parameters if you'd like)
3. /kill yourself, or die in any other method

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by benwoo1110** [comment]
Same as #3089
