### ISSUE TITLE
Split "hidden" into two properties - prefixchat per world.

### ISSUE THREAD

**Issue by Dritz** [Multiverse/Multiverse-Core#441]
Currently, the world property for "hidden" does two things: one, it removes the world from the world list, and two, it removes the chat prefix (if enabled) when a user chats from that world. I would like to be able to configure a world to be hidden from the world list, but still show the chat prefix, to hide nether/end worlds from the world list (and make it less cluttered) but still advertise that a user is currently in those worlds when chatting.

**Comment by dumptruckman** [comment]
This has been been implemented.
