### ISSUE TITLE
Autoheal non-peaceful

### ISSUE THREAD

**Issue by toasterparty** [Multiverse/Multiverse-Core#667]
I think it would be beneficial to implement a setting to disallow heath regeneration regardless of hunger bar status or the game difficulty. The current autoheal setting only affects worlds that are in peaceful, which I find impractical.  A second setting could be used to control if players can be healed by potions and golden apples. Thanks you for your time.

**Comment by benwoo1110** [comment]
I dont think its in the scope of MV-core to alter gamemode mechanics.
