### ISSUE TITLE
Request: Items for access

### ISSUE THREAD

**Issue by Jobsti** [Multiverse/Multiverse-Core#689]
Heyho, a simple Request
- Option to define x-Amount of items in inventory to access the world.

Why? We've got a PVP Skylands, accessable per Stargate, but there's no appeal to visit this world, if the Users have empty inventories.

Possible?

Sorry for postung it unter "Issues", but I can't see a "add Request" button under Reqests.....

**Comment by benwoo1110** [comment]
MV does have world pricing https://github.com/Multiverse/Multiverse-Core/wiki/World-properties#fees as said, if you want very specific customisation of pricing, its probably better suited for another plugin targeted at this specific feature set.
