### ISSUE TITLE
Sorry you can't be in this world anymore!

### ISSUE THREAD

**Issue by NeilSeligmann** [Multiverse/Multiverse-Core#729]
every time people connect at my server, MV says"Sorry you can't be at this world anymore". AND THEY APPEAR AT THE SPAWN!

Also they were in world1 and when the messages appears the go to they spawn of world1!

PLEASE HELP ME!!!!!!!!!!!!

**Comment by marek2005** [comment]
ele problema lo solucione dandome op desde la consola, puede que tengan permisos de rangos bajos
