### ISSUE TITLE
World Gen reverting back to default generator on world/server reload

### ISSUE THREAD

**Issue by mazirian** [Multiverse/Multiverse-Core#778]
Please re-open issue ( #752 Custom World Generator World Reverts Back to Normal.)

I am also experiencing this issue except I'm Using TerrainControl and also experienced this issue with Skylands+ But there are no errors in the console.

Every time the server restarts or the world is unloaded then reloaded this happens causing new chunks to generate with the default generator instead of the Custom generator.

10:36:51 [INFO] [Multiverse-Core] [Multiverse-Core] Multiverse-Core Version: 2.5-b554
10:36:51 [INFO] [Multiverse-Core] [Multiverse-Core] Bukkit Version: git-Bukkit-1.2.5-R4.0-b2222jnks (MC: 1.2.5)
10:36:51 [INFO] [Multiverse-Core] [Multiverse-Core] Loaded Worlds: 5
10:36:51 [INFO] [Multiverse-Core] [Multiverse-Core] Multiverse Plugins Loaded: 0
10:36:51 [INFO] [Multiverse-Core] [Multiverse-Core] Economy being used: Essentials Economy
10:36:51 [INFO] [Multiverse-Core] [Multiverse-Core] Permissions Plugin: Bukkit Permissions (SuperPerms)
10:36:51 [INFO] [Multiverse-Core] [Multiverse-Core] Dumping Config Values: (version 2.9)
10:36:51 [INFO] [Multiverse-Core] [Multiverse-Core]  messagecooldown: 5000
10:36:51 [INFO] [Multiverse-Core] [Multiverse-Core]  teleportcooldown: 1000
10:36:51 [INFO] [Multiverse-Core] [Multiverse-Core]  worldnameprefix: true
10:36:51 [INFO] [Multiverse-Core] [Multiverse-Core]  enforceaccess: false
10:36:51 [INFO] [Multiverse-Core] [Multiverse-Core]  displaypermerrors: true
10:36:51 [INFO] [Multiverse-Core] [Multiverse-Core]  teleportintercept: true
10:36:51 [INFO] [Multiverse-Core] [Multiverse-Core]  firstspawnoverride: true
10:36:51 [INFO] [Multiverse-Core] [Multiverse-Core]  firstspawnworld: world
10:36:51 [INFO] [Multiverse-Core] [Multiverse-Core]  debug: 0
10:36:51 [INFO] [Multiverse-Core] [Multiverse-Core] Special Code: FRN002

**Comment by Seggan** [comment]
A user of my plugin (also with custom world gen) is experiencing the same problem. After doing some Python scriipting, I found that the only plugins they share with [this reduced list](https://github.com/Multiverse/Multiverse-Core/issues/778#issuecomment-11047236) are:
```
Citizens
Essentials
EssentialsChat
EssentialsSpawn
Multiverse-Core
Vault
Votifier
WorldEdit
```
I will do some more testing.

**Comment by Seggan** [comment]
Strangely enough, I was not able to replicate the issue using just Multiverse Core. `worlds.yml` did say the generator was `null`, but the chunks were generating fine.

**Comment by ElMoha943** [comment]
Having the same problem in my server
![imagen](https://user-images.githubusercontent.com/25410859/160421563-694951e5-63df-4fb2-a613-5f9aea0e83b5.png)

**Comment by benwoo1110** [comment]
Unable to reproduce
