### ISSUE TITLE
Don't spawn villages (setting)

### ISSUE THREAD

**Issue by BenWoodworth** [Multiverse/Multiverse-Core#789]
I think there should be a world setting to not spawn villages. Thanks :D

**Comment by chezpaul** [comment]
I totally agree. there is no command for that. There should be a setting not to spawn villages.
Or at least to chose how many you want. I have like 100 villages in my multiverse created worlds and I hate it.

**Comment by robbiemcleod56** [comment]
Even though you posted that link, and this issue is old and closed, I still can't find the setting to turn off villages. Please update your manuals to include this.
