### ISSUE TITLE
Multiverse Reload

### ISSUE THREAD

**Issue by OJACheung** [Multiverse/Multiverse-Core#803]
Hello, when I type /mv reload, it says an internal error occurred and in my console it gives me:

05.08 20:45:46 [Server] INFO ... 15 more
05.08 20:45:46 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
05.08 20:45:46 [Server] INFO at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:731)
05.08 20:45:46 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
05.08 20:45:46 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
05.08 20:45:46 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
05.08 20:45:46 [Server] INFO at com.onarandombox.MultiverseCore.commands.ReloadCommand.runCommand(ReloadCommand.java:38)
05.08 20:45:46 [Server] INFO at com.onarandombox.MultiverseCore.MultiverseCore.loadConfigs(MultiverseCore.java:353)
05.08 20:45:46 [Server] INFO at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorldConfig(WorldManager.java:598)
05.08 20:45:46 [Server] INFO Caused by: java.lang.NullPointerException
05.08 20:45:46 [Server] INFO at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
05.08 20:45:46 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
05.08 20:45:46 [Server] INFO at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:476)
05.08 20:45:46 [Server] INFO at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
05.08 20:45:46 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:583)
05.08 20:45:46 [Server] INFO at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
05.08 20:45:46 [Server] INFO at net.minecraft.server.ServerConnection.b(SourceFile:35)
05.08 20:45:46 [Server] INFO at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
05.08 20:45:46 [Server] INFO at net.minecraft.server.NetworkManager.b(NetworkManager.java:281)
05.08 20:45:46 [Server] INFO at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
05.08 20:45:46 [Server] INFO at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:808)
05.08 20:45:46 [Server] INFO at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:826)
05.08 20:45:46 [Server] INFO at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:879)
05.08 20:45:46 [Server] INFO at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:490)
05.08 20:45:46 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
05.08 20:45:46 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
05.08 20:45:46 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mv' in plugin Multiverse-Core v2.5-b554

Please help me, thanks.

**Comment by Maxx3242** [comment]
tengo un problema con el multiverse que cuando pongo el comando /mv reload o /mv create me dice you not do have any of the required permission (s):- Multiverse.core.reload. y entro a ese link y no pasa nada

**Comment by NeverGrowUp** [comment]
> tengo un problema con el multiverse que cuando pongo el comando /mv reload o /mv create me dice you not do have any of the required permission (s):- Multiverse.core.reload. y entro a ese link y no pasa nada

Commenting on a closed thread about an issue that is not related to OP, does not help your cause.
List of perms here. https://github.com/Multiverse/Multiverse-Core/wiki/Big-List-O'-Permissions
