### ISSUE TITLE
World Access Owner - Give players the right to grant access to specific worlds.

### ISSUE THREAD

**Issue by Ruok2bu** [Multiverse/Multiverse-Core#908]
I have several words on my server that can only be accessed by a specific group of people (private worlds).  Rather than giving the world owner admin (which would allow them to invite users to any group), i would prefer that the world owners could create their own access groups and invite users to their group to access the world.

Can you add this sort of functionality?

P.S. The way im doing it now, world owners tell me who should have access. But this is slow since they have to wait until i add those users before they can access the world.

**Comment by benwoo1110** [comment]
Unless MV implements custom storing to which player have access to which world, I don't think it's possible with MV. I think with now more advance permission plugin like luckperms you should be able to fine-tune the adding of rank and permissions. https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions
