### ISSUE TITLE
Multiverse - World keeps unloading 

### ISSUE THREAD

**Issue by mattyluggs** [Multiverse/Multiverse-Core#950]
Hey there,

Every-time I make a new world, when I restart the server and use the command "/mv list" the world is renamed "1" and it says unloaded next to it. 

Also in the   multiverse.core   worlds.yml   it is renamed 1 and I get the following line in the config that clearly shouldn't be there:

spawnLocation:
      ==: MVNullLocation (It's a bug if you see this in your config file)

How do I stop my new world unloading?

Many thanks,

Matt.

**Comment by krzmaciek** [comment]
I have this error too.

**Comment by krzmaciek** [comment]
I have the same issue :(

**Comment by RPS1222** [comment]
I am still having this issue on my server, even after the command

**Comment by Jadiction** [comment]
@RPS1222 This is from 2012. Request assistance in the Discord or make a new ticket.
