### ISSUE TITLE
Fix NPEs caused by using Citizens 2 NPCs

### ISSUE THREAD

**Issue by Jeebiss** [Multiverse/Multiverse-Core#956]
This is an oddly specific request. but worth noting. Citizens 2 is a plugin that is becoming quite popular with there newest release of version 2. It allows you to create NPCs that do all sorts of stuff. The issue however, is it makes essentially empty player entities, and nearly every plugin throws an NPE with them since it never checks. So Im requesting some compatibility with the Citizens 2 plugin.

Its a fairly simple check, since they have made it so all NPCs are created with 'NPC ' in the metadata of the entity. So a simple entity.hasMetadata("NPC") check before assuming its a player would fix a lot of the NPE issues. 

I love Multiverse, and use it despite the conflicts.

If you need anymore information, #citizens on esper.net and http://goo.gl/qsBZH for the GitHub of the project.

Thanks for any considerations!

**Comment by TWSSYesterday** [comment]
Definitely no longer the case.
