### ISSUE TITLE
worlds.yml is rewritten wrongly at startup

### ISSUE THREAD

**Issue by vanderfr** [Multiverse/Multiverse-Core#982]
MultiVers Build 639
Craftbukkit -1.4.5-R0.2-Build : 2488

"keepSpawnInMemory" sometimes return to "false" even if you set it to "true" when the server is shutdown.

**Comment by TWSSYesterday** [comment]
This cannot be reproduced at all, if you have an issue similar to this, be sure to let us know. For now, closed due to inactivity.
