### ISSUE TITLE
Manipulate portals with Command Blocks

### ISSUE THREAD

**Issue by Scooter789** [Multiverse/Multiverse-Core#998]
I tried changing the destination of a portal with a command block, only to discover that the command:
```
/mvp modify dest <DEST> -p <PORTAL>
```

is not allowed for non-players (console or command block).

Would it be possible to allow this change from console or command block?

**Comment by FernFerret** [comment]
Someone has a pull request in for this https://github.com/Multiverse/Multiverse-Portals/pull/412 I'll be looking at it soon.

**Comment by FernFerret** [comment]
The link didn't happen because this one got put in core (and yes, I realize you put this in 3 years ago) but I'll link it to the commit: https://github.com/Multiverse/Multiverse-Portals/commit/2c13885ff567edce3c44cdfac8e8ed0948d96f00

**Comment by Scooter789** [comment]
Thank you for doing this. I probably won't be taking advantage of it
anymore, but hopefully others will make some cool stuff with it.
