### ISSUE TITLE
Scaling not working with Nether Portals

### ISSUE THREAD

**Issue by Vasher** [Multiverse/Multiverse-Core#999]
Here is what I did.
1. Clean install with MV-Core, NetherPortals, and Portals on a fresh world.
2. Create a nether portal.
3. Go through nether portal. Once in the nether return to the Overworld from the created nether portal.

You should come back to your original overworld portal but you do not. Instead a new portal is create in a completely new location.

I have the default scaling for the worlds. overworld: 1, nether: 8, the_end: 16

**Comment by benwoo1110** [comment]
Closing old issue. please create a new one if needed. Thanks!
